# NOTE: Assertions have been autogenerated by utils/update_mca_test_checks.py
# RUN: llvm-mca -mtriple=x86_64-unknown-unknown -mcpu=gracemont -instruction-tables < %s | FileCheck %s

crc32b      %al, %ecx
crc32b      (%rax), %ecx

crc32l      %eax, %ecx
crc32l      (%rax), %ecx

crc32w      %ax, %ecx
crc32w      (%rax), %ecx

crc32b      %al, %rcx
crc32b      (%rax), %rcx

crc32q      %rax, %rcx
crc32q      (%rax), %rcx

pcmpestri   $1, %xmm0, %xmm2
pcmpestri   $1, (%rax), %xmm2

pcmpestrm   $1, %xmm0, %xmm2
pcmpestrm   $1, (%rax), %xmm2

pcmpistri   $1, %xmm0, %xmm2
pcmpistri   $1, (%rax), %xmm2

pcmpistrm   $1, %xmm0, %xmm2
pcmpistrm   $1, (%rax), %xmm2

pcmpgtq     %xmm0, %xmm2
pcmpgtq     (%rax), %xmm2

# CHECK:      Instruction Info:
# CHECK-NEXT: [1]: #uOps
# CHECK-NEXT: [2]: Latency
# CHECK-NEXT: [3]: RThroughput
# CHECK-NEXT: [4]: MayLoad
# CHECK-NEXT: [5]: MayStore
# CHECK-NEXT: [6]: HasSideEffects (U)

# CHECK:      [1]    [2]    [3]    [4]    [5]    [6]    Instructions:
# CHECK-NEXT:  1      3     1.00                        crc32b	%al, %ecx
# CHECK-NEXT:  2      7     1.00    *                   crc32b	(%rax), %ecx
# CHECK-NEXT:  1      3     1.00                        crc32l	%eax, %ecx
# CHECK-NEXT:  2      7     1.00    *                   crc32l	(%rax), %ecx
# CHECK-NEXT:  1      3     1.00                        crc32w	%ax, %ecx
# CHECK-NEXT:  2      7     1.00    *                   crc32w	(%rax), %ecx
# CHECK-NEXT:  1      3     1.00                        crc32b	%al, %rcx
# CHECK-NEXT:  2      7     1.00    *                   crc32b	(%rax), %rcx
# CHECK-NEXT:  1      3     1.00                        crc32q	%rax, %rcx
# CHECK-NEXT:  2      7     1.00    *                   crc32q	(%rax), %rcx
# CHECK-NEXT:  1      50    0.33                        pcmpestri	$1, %xmm0, %xmm2
# CHECK-NEXT:  1      50    0.25    *                   pcmpestri	$1, (%rax), %xmm2
# CHECK-NEXT:  1      50    0.33                        pcmpestrm	$1, %xmm0, %xmm2
# CHECK-NEXT:  1      50    0.25    *                   pcmpestrm	$1, (%rax), %xmm2
# CHECK-NEXT:  1      50    0.33                        pcmpistri	$1, %xmm0, %xmm2
# CHECK-NEXT:  1      50    0.25    *                   pcmpistri	$1, (%rax), %xmm2
# CHECK-NEXT:  1      50    0.33                        pcmpistrm	$1, %xmm0, %xmm2
# CHECK-NEXT:  1      50    0.25    *                   pcmpistrm	$1, (%rax), %xmm2
# CHECK-NEXT:  1      1     0.33                        pcmpgtq	%xmm0, %xmm2
# CHECK-NEXT:  2      6     0.50    *                   pcmpgtq	(%rax), %xmm2

# CHECK:      Resources:
# CHECK-NEXT: [0]   - GRTPort00
# CHECK-NEXT: [1]   - GRTPort01
# CHECK-NEXT: [2]   - GRTPort02
# CHECK-NEXT: [3]   - GRTPort03
# CHECK-NEXT: [4]   - GRTPort08
# CHECK-NEXT: [5]   - GRTPort09
# CHECK-NEXT: [6]   - GRTPort10
# CHECK-NEXT: [7]   - GRTPort11
# CHECK-NEXT: [8]   - GRTPort12
# CHECK-NEXT: [9]   - GRTPort13
# CHECK-NEXT: [10]  - GRTPort20
# CHECK-NEXT: [11]  - GRTPort21
# CHECK-NEXT: [12]  - GRTPort22
# CHECK-NEXT: [13]  - GRTPort28
# CHECK-NEXT: [14]  - GRTPort29
# CHECK-NEXT: [15]  - GRTPort30
# CHECK-NEXT: [16]  - GRTPort31
# CHECK-NEXT: [17]  - GRTPortInvalid

# CHECK:      Resource pressure per iteration:
# CHECK-NEXT: [0]    [1]    [2]    [3]    [4]    [5]    [6]    [7]    [8]    [9]    [10]   [11]   [12]   [13]   [14]   [15]   [16]   [17]
# CHECK-NEXT: 1.00   11.00  1.00   1.00    -      -     3.00   3.00    -      -     2.00   2.00   2.00    -      -      -      -      -

# CHECK:      Resource pressure by instruction:
# CHECK-NEXT: [0]    [1]    [2]    [3]    [4]    [5]    [6]    [7]    [8]    [9]    [10]   [11]   [12]   [13]   [14]   [15]   [16]   [17]   Instructions:
# CHECK-NEXT:  -     1.00    -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     crc32b	%al, %ecx
# CHECK-NEXT:  -     1.00    -      -      -      -     0.50   0.50    -      -      -      -      -      -      -      -      -      -     crc32b	(%rax), %ecx
# CHECK-NEXT:  -     1.00    -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     crc32l	%eax, %ecx
# CHECK-NEXT:  -     1.00    -      -      -      -     0.50   0.50    -      -      -      -      -      -      -      -      -      -     crc32l	(%rax), %ecx
# CHECK-NEXT:  -     1.00    -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     crc32w	%ax, %ecx
# CHECK-NEXT:  -     1.00    -      -      -      -     0.50   0.50    -      -      -      -      -      -      -      -      -      -     crc32w	(%rax), %ecx
# CHECK-NEXT:  -     1.00    -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     crc32b	%al, %rcx
# CHECK-NEXT:  -     1.00    -      -      -      -     0.50   0.50    -      -      -      -      -      -      -      -      -      -     crc32b	(%rax), %rcx
# CHECK-NEXT:  -     1.00    -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     crc32q	%rax, %rcx
# CHECK-NEXT:  -     1.00    -      -      -      -     0.50   0.50    -      -      -      -      -      -      -      -      -      -     crc32q	(%rax), %rcx
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.33   0.33   0.33    -      -      -      -      -     pcmpestri	$1, %xmm0, %xmm2
# CHECK-NEXT: 0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -      -      -      -      -      -      -     pcmpestri	$1, (%rax), %xmm2
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.33   0.33   0.33    -      -      -      -      -     pcmpestrm	$1, %xmm0, %xmm2
# CHECK-NEXT: 0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -      -      -      -      -      -      -     pcmpestrm	$1, (%rax), %xmm2
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.33   0.33   0.33    -      -      -      -      -     pcmpistri	$1, %xmm0, %xmm2
# CHECK-NEXT: 0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -      -      -      -      -      -      -     pcmpistri	$1, (%rax), %xmm2
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.33   0.33   0.33    -      -      -      -      -     pcmpistrm	$1, %xmm0, %xmm2
# CHECK-NEXT: 0.25   0.25   0.25   0.25    -      -      -      -      -      -      -      -      -      -      -      -      -      -     pcmpistrm	$1, (%rax), %xmm2
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -     0.33   0.33   0.33    -      -      -      -      -     pcmpgtq	%xmm0, %xmm2
# CHECK-NEXT:  -      -      -      -      -      -     0.50   0.50    -      -     0.33   0.33   0.33    -      -      -      -      -     pcmpgtq	(%rax), %xmm2
