; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: intel_feature_isa_avx_ifma
; RUN: llc < %s -mtriple=i686-unknown-unknown -mattr=+avxifma --show-mc-encoding | FileCheck %s --check-prefixes=AVX-X86
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avxifma --show-mc-encoding | FileCheck %s --check-prefixes=AVX-X64
; RUN: llc < %s -mtriple=i686-unknown-unknown -mattr=+avxifma,+avx512ifma,+avx512vl --show-mc-encoding | FileCheck %s --check-prefixes=AVX512-X86
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avxifma,+avx512ifma,+avx512vl --show-mc-encoding | FileCheck %s --check-prefixes=AVX512-X64

declare <2 x i64> @llvm.x86.avx.vpmadd52h.uq.128(<2 x i64>, <2 x i64>, <2 x i64>)

define <2 x i64>@test_int_x86_avx_vpmadd52h_uq_128(<2 x i64> %x0, <2 x i64> %x1, <2 x i64> %x2) {
; AVX-X86-LABEL: test_int_x86_avx_vpmadd52h_uq_128:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpmadd52huq %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0xf1,0xb5,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx_vpmadd52h_uq_128:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpmadd52huq %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0xf1,0xb5,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx_vpmadd52h_uq_128:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    vpmadd52huq %xmm2, %xmm1, %xmm0 # encoding: [0x62,0xf2,0xf5,0x08,0xb5,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx_vpmadd52h_uq_128:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    vpmadd52huq %xmm2, %xmm1, %xmm0 # encoding: [0x62,0xf2,0xf5,0x08,0xb5,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <2 x i64> @llvm.x86.avx.vpmadd52h.uq.128(<2 x i64> %x0, <2 x i64> %x1, <2 x i64> %x2)
  ret <2 x i64> %res
}

declare <4 x i64> @llvm.x86.avx.vpmadd52h.uq.256(<4 x i64>, <4 x i64>, <4 x i64>)

define <4 x i64>@test_int_x86_avx_vpmadd52h_uq_256(<4 x i64> %x0, <4 x i64> %x1, <4 x i64> %x2) {
; AVX-X86-LABEL: test_int_x86_avx_vpmadd52h_uq_256:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpmadd52huq %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0xf5,0xb5,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx_vpmadd52h_uq_256:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpmadd52huq %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0xf5,0xb5,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx_vpmadd52h_uq_256:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    vpmadd52huq %ymm2, %ymm1, %ymm0 # encoding: [0x62,0xf2,0xf5,0x28,0xb5,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx_vpmadd52h_uq_256:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    vpmadd52huq %ymm2, %ymm1, %ymm0 # encoding: [0x62,0xf2,0xf5,0x28,0xb5,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <4 x i64> @llvm.x86.avx.vpmadd52h.uq.256(<4 x i64> %x0, <4 x i64> %x1, <4 x i64> %x2)
  ret <4 x i64> %res
}

declare <2 x i64> @llvm.x86.avx.vpmadd52l.uq.128(<2 x i64>, <2 x i64>, <2 x i64>)

define <2 x i64>@test_int_x86_avx_vpmadd52l_uq_128(<2 x i64> %x0, <2 x i64> %x1, <2 x i64> %x2) {
; AVX-X86-LABEL: test_int_x86_avx_vpmadd52l_uq_128:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpmadd52luq %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0xf1,0xb4,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx_vpmadd52l_uq_128:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpmadd52luq %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0xf1,0xb4,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx_vpmadd52l_uq_128:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    vpmadd52luq %xmm2, %xmm1, %xmm0 # encoding: [0x62,0xf2,0xf5,0x08,0xb4,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx_vpmadd52l_uq_128:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    vpmadd52luq %xmm2, %xmm1, %xmm0 # encoding: [0x62,0xf2,0xf5,0x08,0xb4,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <2 x i64> @llvm.x86.avx.vpmadd52l.uq.128(<2 x i64> %x0, <2 x i64> %x1, <2 x i64> %x2)
  ret <2 x i64> %res
}

declare <4 x i64> @llvm.x86.avx.vpmadd52l.uq.256(<4 x i64>, <4 x i64>, <4 x i64>)

define <4 x i64>@test_int_x86_avx_vpmadd52l_uq_256(<4 x i64> %x0, <4 x i64> %x1, <4 x i64> %x2) {
; AVX-X86-LABEL: test_int_x86_avx_vpmadd52l_uq_256:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpmadd52luq %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0xf5,0xb4,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx_vpmadd52l_uq_256:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpmadd52luq %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0xf5,0xb4,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx_vpmadd52l_uq_256:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    vpmadd52luq %ymm2, %ymm1, %ymm0 # encoding: [0x62,0xf2,0xf5,0x28,0xb4,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx_vpmadd52l_uq_256:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    vpmadd52luq %ymm2, %ymm1, %ymm0 # encoding: [0x62,0xf2,0xf5,0x28,0xb4,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <4 x i64> @llvm.x86.avx.vpmadd52l.uq.256(<4 x i64> %x0, <4 x i64> %x1, <4 x i64> %x2)
  ret <4 x i64> %res
}
