# Makefile for hello pass

# Path to top level of LLVM hierarchy
LEVEL = ../../../

# Name of the library to build
LIBRARYNAME = LLVMBasicBlockDumper

# Make the shared library become a loadable module so the tools can
# dlopen/dlsym on the resulting library.
#LOADABLE_MODULE = 1
#LLVM_LINK_LLVM_DYLIB = 1

#LLVMLIBS += lib/Transforms/Utils/Debug+Asserts/CloneModule.o
#USEDLIBS += LLVMTransformUtils.a
#LINK_COMPONENTS := transformUtils
#LINK_LIBS_IN_SHARED=1

BUILD_ARCHIVE=1



# Include the makefile implementation stuff
include $(LEVEL)/Makefile.common
