// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: intel_feature_isa_avx512_dotprod
// RUN: %clang_cc1 -flax-vector-conversions=none -ffreestanding %s -triple=x86_64-unknown-unknown -target-feature +avx512vl -target-feature +avx512dotprod -target-feature +avx512fp16 -emit-llvm -o - -Wall -Werror | FileCheck %s

#include <immintrin.h>

__m128 test_mm_mask_vdpphps_ps(__m128 __W, __mmask8 __U, __m128h __A, __m128h __B) {
  // CHECK-LABEL: @test_mm_mask_vdpphps_ps(
  // CHECK:     call <4 x float> @llvm.x86.avx512.mask.vdpphps.128
  return _mm_mask_vdpphps_ps(__W, __U, __A, __B);
}

__m128 test_mm_maskz_vdpphps_ps(__mmask8 __U, __m128 __W, __m128h __A, __m128h __B) {
  // CHECK-LABEL: @test_mm_maskz_vdpphps_ps(
  // CHECK:     call <4 x float> @llvm.x86.avx512.maskz.vdpphps.128
  return _mm_maskz_vdpphps_ps(__U, __W, __A, __B);
}

__m128i test_mm_mask_vpdpbssd_epi32(__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_mask_vpdpbssd_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssd.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_mask_vpdpbssd_epi32(__W, __U, __A, __B);
}

__m128i test_mm_maskz_vpdpbssd_epi32(__mmask8 __U, __m128i __W, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_maskz_vpdpbssd_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssd.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_maskz_vpdpbssd_epi32(__U, __W, __A, __B);
}

__m128i test_mm_mask_vpdpbssds_epi32(__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_mask_vpdpbssds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssds.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_mask_vpdpbssds_epi32(__W, __U, __A, __B);
}

__m128i test_mm_maskz_vpdpbssds_epi32(__mmask8 __U, __m128i __W, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_maskz_vpdpbssds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssds.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_maskz_vpdpbssds_epi32(__U, __W, __A, __B);
}

__m128i test_mm_mask_vpdpbsud_epi32(__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_mask_vpdpbsud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsud.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_mask_vpdpbsud_epi32(__W, __U, __A, __B);
}

__m128i test_mm_maskz_vpdpbsud_epi32(__mmask8 __U, __m128i __W, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_maskz_vpdpbsud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsud.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_maskz_vpdpbsud_epi32(__U, __W, __A, __B);
}

__m128i test_mm_mask_vpdpbsuds_epi32(__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_mask_vpdpbsuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsuds.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_mask_vpdpbsuds_epi32(__W, __U, __A, __B);
}

__m128i test_mm_maskz_vpdpbsuds_epi32(__mmask8 __U, __m128i __W, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_maskz_vpdpbsuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsuds.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_maskz_vpdpbsuds_epi32(__U, __W, __A, __B);
}

__m128i test_mm_mask_vpdpbuud_epi32(__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_mask_vpdpbuud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuud.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_mask_vpdpbuud_epi32(__W, __U, __A, __B);
}

__m128i test_mm_maskz_vpdpbuud_epi32(__mmask8 __U, __m128i __W, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_maskz_vpdpbuud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuud.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_maskz_vpdpbuud_epi32(__U, __W, __A, __B);
}

__m128i test_mm_mask_vpdpbuuds_epi32(__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_mask_vpdpbuuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuuds.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_mask_vpdpbuuds_epi32(__W, __U, __A, __B);
}

__m128i test_mm_maskz_vpdpbuuds_epi32(__mmask8 __U, __m128i __W, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_maskz_vpdpbuuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuuds.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_maskz_vpdpbuuds_epi32(__U, __W, __A, __B);
}

// CHECK-LABEL: @test_mm256_mask_vdpphps_ps(
// CHECK:     call <8 x float> @llvm.x86.avx512.mask.vdpphps.256
__m256 test_mm256_mask_vdpphps_ps(__m256 __W, __mmask8 __U, __m256h __A, __m256h __B) {
  return _mm256_mask_vdpphps_ps(__W, __U,  __A, __B);
}

// CHECK-LABEL: @test_mm256_maskz_vdpphps_ps(
// CHECK:     call <8 x float> @llvm.x86.avx512.maskz.vdpphps.256
__m256 test_mm256_maskz_vdpphps_ps(__mmask8 __U, __m256 __W, __m256h __A, __m256h __B) {
  return _mm256_maskz_vdpphps_ps(__U, __W, __A, __B);
}

__m256i test_mm256_mask_vpdpbssd_epi32(__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_mask_vpdpbssd_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssd.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_mask_vpdpbssd_epi32(__W, __U, __A, __B);
}

__m256i test_mm256_maskz_vpdpbssd_epi32(__mmask8 __U, __m256i __W, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_maskz_vpdpbssd_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssd.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_maskz_vpdpbssd_epi32(__U, __W, __A, __B);
}

__m256i test_mm256_mask_vpdpbssds_epi32(__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_mask_vpdpbssds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssds.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_mask_vpdpbssds_epi32(__W, __U, __A, __B);
}

__m256i test_mm256_maskz_vpdpbssds_epi32(__mmask8 __U, __m256i __W, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_maskz_vpdpbssds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssds.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_maskz_vpdpbssds_epi32(__U, __W, __A, __B);
}

__m256i test_mm256_mask_vpdpbsud_epi32(__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_mask_vpdpbsud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsud.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_mask_vpdpbsud_epi32(__W, __U, __A, __B);
}

__m256i test_mm256_maskz_vpdpbsud_epi32(__mmask8 __U, __m256i __W, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_maskz_vpdpbsud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsud.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_maskz_vpdpbsud_epi32(__U, __W, __A, __B);
}

__m256i test_mm256_mask_vpdpbsuds_epi32(__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_mask_vpdpbsuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsuds.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_mask_vpdpbsuds_epi32(__W, __U, __A, __B);
}

__m256i test_mm256_maskz_vpdpbsuds_epi32(__mmask8 __U, __m256i __W, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_maskz_vpdpbsuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsuds.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_maskz_vpdpbsuds_epi32(__U, __W, __A, __B);
}

__m256i test_mm256_mask_vpdpbuud_epi32(__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_mask_vpdpbuud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuud.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_mask_vpdpbuud_epi32(__W, __U, __A, __B);
}

__m256i test_mm256_maskz_vpdpbuud_epi32(__mmask8 __U, __m256i __W, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_maskz_vpdpbuud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuud.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_maskz_vpdpbuud_epi32(__U, __W, __A, __B);
}

__m256i test_mm256_mask_vpdpbuuds_epi32(__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_mask_vpdpbuuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuuds.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_mask_vpdpbuuds_epi32(__W, __U, __A, __B);
}

__m256i test_mm256_maskz_vpdpbuuds_epi32(__mmask8 __U, __m256i __W, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_maskz_vpdpbuuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuuds.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_maskz_vpdpbuuds_epi32(__U, __W, __A, __B);
}
