; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=avx512fp16 --fp-contract=fast --enable-unsafe-fp-math | FileCheck %s

define dso_local <32 x half> @test1(<32 x half> %acc.coerce, <32 x half> %lhs.coerce.conj, <32 x half> %rhs.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: test1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vfcmaddcph %zmm1, %zmm2, %zmm0
; CHECK-NEXT:    retq
entry:
  %0 = bitcast <32 x half> %lhs.coerce.conj to <16 x i32>
  %xor.i.i = xor <16 x i32> %0, <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>
  %1 = bitcast <16 x i32> %xor.i.i to <16 x float>
  %2 = bitcast <32 x half> %rhs.coerce to <16 x float>
  %3 = tail call fast <16 x float> @llvm.x86.avx512fp16.mask.vfmulc.ph.512(<16 x float> %1, <16 x float> %2, <16 x float> zeroinitializer, i16 -1, i32 4) #2
  %4 = bitcast <16 x float> %3 to <32 x half>
  %add = fadd fast <32 x half> %4, %acc.coerce
  ret <32 x half> %add
}

define dso_local <32 x half> @test2(<32 x half> %acc.coerce, <32 x half> %lhs.coerce.conj, <32 x half> %rhs.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: test2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vfcmaddcph %zmm1, %zmm2, %zmm0
; CHECK-NEXT:    retq
entry:
  %0 = bitcast <32 x half> %lhs.coerce.conj to <16 x i32>
  %xor.i.i = xor <16 x i32> %0, <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>
  %1 = bitcast <16 x i32> %xor.i.i to <16 x float>
  %2 = bitcast <32 x half> %rhs.coerce to <16 x float>
  %3 = tail call fast <16 x float> @llvm.x86.avx512fp16.mask.vfmulc.ph.512(<16 x float> %2, <16 x float> %1, <16 x float> zeroinitializer, i16 -1, i32 4) #2
  %4 = bitcast <16 x float> %3 to <32 x half>
  %add = fadd fast <32 x half> %4, %acc.coerce
  ret <32 x half> %add
}

define dso_local <16 x half> @test3(<16 x half> %acc.coerce, <16 x half> %lhs.coerce.conj, <16 x half> %rhs.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: test3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vfcmaddcph %ymm1, %ymm2, %ymm0
; CHECK-NEXT:    retq
entry:
  %0 = bitcast <16 x half> %lhs.coerce.conj to <8 x i32>
  %xor.i.i = xor <8 x i32> %0, <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>
  %1 = bitcast <8 x i32> %xor.i.i to <8 x float>
  %2 = bitcast <16 x half> %rhs.coerce to <8 x float>
  %3 = tail call fast <8 x float> @llvm.x86.avx512fp16.mask.vfmulc.ph.256(<8 x float> %1, <8 x float> %2, <8 x float> zeroinitializer, i8 -1) #2
  %4 = bitcast <8 x float> %3 to <16 x half>
  %add = fadd fast <16 x half> %4, %acc.coerce
  ret <16 x half> %add
}

define dso_local <8 x half> @test4(<8 x half> %acc.coerce, <8 x half> %lhs.coerce.conj, <8 x half> %rhs.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: test4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vfcmaddcph %xmm1, %xmm2, %xmm0
; CHECK-NEXT:    retq
entry:
  %0 = bitcast <8 x half> %lhs.coerce.conj to <4 x i32>
  %xor.i.i = xor <4 x i32> %0, <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>
  %1 = bitcast <4 x i32> %xor.i.i to <4 x float>
  %2 = bitcast <8 x half> %rhs.coerce to <4 x float>
  %3 = tail call fast <4 x float> @llvm.x86.avx512fp16.mask.vfmulc.ph.128(<4 x float> %1, <4 x float> %2, <4 x float> zeroinitializer, i8 -1) #2
  %4 = bitcast <4 x float> %3 to <8 x half>
  %add = fadd fast <8 x half> %4, %acc.coerce
  ret <8 x half> %add
}

define dso_local <8 x half> @test5(<8 x half> %acc.coerce, <8 x half> %lhs.coerce.conj, <8 x half> %rhs.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: test5:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vfcmaddcph %xmm1, %xmm2, %xmm0
; CHECK-NEXT:    retq
entry:
  %0 = bitcast <8 x half> %lhs.coerce.conj to <4 x i32>
  %xor.i.i = xor <4 x i32> <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>, %0
  %1 = bitcast <4 x i32> %xor.i.i to <4 x float>
  %2 = bitcast <8 x half> %rhs.coerce to <4 x float>
  %3 = tail call fast <4 x float> @llvm.x86.avx512fp16.mask.vfmulc.ph.128(<4 x float> %1, <4 x float> %2, <4 x float> zeroinitializer, i8 -1) #2
  %4 = bitcast <4 x float> %3 to <8 x half>
  %add = fadd fast <8 x half> %4, %acc.coerce
  ret <8 x half> %add
}

define dso_local <8 x half> @test6(<8 x half> %acc.coerce, <8 x half> %lhs.coerce.conj, <8 x half> %rhs.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: test6:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vxorps {{.*}}(%rip){1to4}, %xmm1, %xmm1
; CHECK-NEXT:    vfmaddcph %xmm2, %xmm1, %xmm0
; CHECK-NEXT:    retq
entry:
  %0 = bitcast <8 x half> %lhs.coerce.conj to <4 x i32>
  %xor.i.i = xor <4 x i32> <i32 1, i32 1, i32 1, i32 1>, %0
  %1 = bitcast <4 x i32> %xor.i.i to <4 x float>
  %2 = bitcast <8 x half> %rhs.coerce to <4 x float>
  %3 = tail call fast <4 x float> @llvm.x86.avx512fp16.mask.vfmulc.ph.128(<4 x float> %1, <4 x float> %2, <4 x float> zeroinitializer, i8 -1) #2
  %4 = bitcast <4 x float> %3 to <8 x half>
  %add = fadd fast <8 x half> %4, %acc.coerce
  ret <8 x half> %add
}

define dso_local <8 x half> @test7(<8 x half> %acc.coerce, <8 x half> %lhs.coerce.conj, <8 x half> %rhs.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: test7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vfcmaddcph %xmm1, %xmm2, %xmm0
; CHECK-NEXT:    retq
entry:
  %0 = bitcast <8 x half> %lhs.coerce.conj to <4 x i32>
  %xor.i.i = xor <4 x i32> <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>, %0
  %1 = bitcast <4 x i32> %xor.i.i to <4 x float>
  %2 = bitcast <8 x half> %rhs.coerce to <4 x float>
  %3 = tail call fast <4 x float> @llvm.x86.avx512fp16.mask.vfmulc.ph.128(<4 x float> %1, <4 x float> %2, <4 x float> zeroinitializer, i8 -1) #2
  %4 = bitcast <4 x float> %3 to <8 x half>
  %add = fadd fast <8 x half> %acc.coerce, %4
  ret <8 x half> %add
}

define dso_local <8 x half> @test8(<8 x half> %acc.coerce, <4 x float> %lhs.coerce.conj, <8 x half> %rhs.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: test8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vfcmaddcph %xmm1, %xmm2, %xmm0
; CHECK-NEXT:    retq
entry:
  %0 = bitcast <4 x float> %lhs.coerce.conj to <4 x i32>
  %xor.i.i = xor <4 x i32> <i32 -2147483648, i32 -2147483648, i32 -2147483648, i32 -2147483648>, %0
  %1 = bitcast <4 x i32> %xor.i.i to <4 x float>
  %2 = bitcast <8 x half> %rhs.coerce to <4 x float>
  %3 = tail call fast <4 x float> @llvm.x86.avx512fp16.mask.vfmulc.ph.128(<4 x float> %1, <4 x float> %2, <4 x float> zeroinitializer, i8 -1) #2
  %4 = bitcast <4 x float> %3 to <8 x half>
  %add = fadd fast <8 x half> %acc.coerce, %4
  ret <8 x half> %add
}

define dso_local <32 x half> @test9(<32 x half> %acc.coerce, <8 x i64> %lhs.coerce.conj, <32 x half> %rhs.coerce) local_unnamed_addr #0 {
; CHECK-LABEL: test9:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vfcmaddcph %zmm1, %zmm2, %zmm0
; CHECK-NEXT:    retq
entry:
  %xor1.i = xor <8 x i64> %lhs.coerce.conj, <i64 -9223372034707292160, i64 -9223372034707292160, i64 -9223372034707292160, i64 -9223372034707292160, i64 -9223372034707292160, i64 -9223372034707292160, i64 -9223372034707292160, i64 -9223372034707292160>
  %0 = bitcast <8 x i64> %xor1.i to <16 x float>
  %1 = bitcast <32 x half> %rhs.coerce to <16 x float>
  %2 = tail call fast <16 x float> @llvm.x86.avx512fp16.mask.vfmulc.ph.512(<16 x float> %0, <16 x float> %1, <16 x float> zeroinitializer, i16 -1, i32 4) #2
  %3 = bitcast <16 x float> %2 to <32 x half>
  %add = fadd fast <32 x half> %3, %acc.coerce
  ret <32 x half> %add
}

declare <16 x float> @llvm.x86.avx512fp16.mask.vfmulc.ph.512(<16 x float>, <16 x float>, <16 x float>, i16, i32 immarg)
declare <8 x float> @llvm.x86.avx512fp16.mask.vfmulc.ph.256(<8 x float>, <8 x float>, <8 x float>, i8)
declare <4 x float> @llvm.x86.avx512fp16.mask.vfmulc.ph.128(<4 x float>, <4 x float>, <4 x float>, i8)