; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: intel_feature_isa_fp16
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=FEATURE-INIT
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse | FileCheck %s --check-prefix=CHECK-PINIT-FTZ

define dso_local i32 @main() #0 {
; FEATURE-INIT-LABEL: main:
; FEATURE-INIT:       # %bb.0: # %entry
; FEATURE-INIT-NEXT:    pushq %rax
; FEATURE-INIT-NEXT:    .cfi_def_cfa_offset 16
; FEATURE-INIT-NEXT:    movl $32, %esi
; FEATURE-INIT-NEXT:    movl $24, %edi
; FEATURE-INIT-NEXT:    callq __intel_new_feature_proc_init
; FEATURE-INIT-NEXT:    movl $0, {{[0-9]+}}(%rsp)
; FEATURE-INIT-NEXT:    xorl %eax, %eax
; FEATURE-INIT-NEXT:    popq %rcx
; FEATURE-INIT-NEXT:    .cfi_def_cfa_offset 8
; FEATURE-INIT-NEXT:    retq
;
; CHECK-PINIT-FTZ-LABEL: main:
; CHECK-PINIT-FTZ:       # %bb.0: # %entry
; CHECK-PINIT-FTZ-NEXT:    stmxcsr -{{[0-9]+}}(%rsp)
; CHECK-PINIT-FTZ-NEXT:    orb $12, -{{[0-9]+}}(%rsp)
; CHECK-PINIT-FTZ-NEXT:    ldmxcsr -{{[0-9]+}}(%rsp)
; CHECK-PINIT-FTZ-NEXT:    movl $0, -{{[0-9]+}}(%rsp)
; CHECK-PINIT-FTZ-NEXT:    xorl %eax, %eax
; CHECK-PINIT-FTZ-NEXT:    retq
entry:
  %retval = alloca i32, align 4
  store i32 0, i32* %retval, align 4
  ret i32 0
}
attributes #0 = { "denormal-fp-math-f16"="preserve-sign,preserve-sign" }
