# NOTE: Assertions have been autogenerated by utils/update_mca_test_checks.py
# REQUIRES: intel_feature_cpu_dmr
# RUN: llvm-mca -mtriple=x86_64-unknown-unknown -mcpu=diamondrapids -instruction-tables %p/../../../../MC/X86/intel_apx/sar-att.s | FileCheck %s

# CHECK:      Instruction Info:
# CHECK-NEXT: [1]: #uOps
# CHECK-NEXT: [2]: Latency
# CHECK-NEXT: [3]: RThroughput
# CHECK-NEXT: [4]: MayLoad
# CHECK-NEXT: [5]: MayStore
# CHECK-NEXT: [6]: HasSideEffects (U)

# CHECK:      [1]    [2]    [3]    [4]    [5]    [6]    Instructions:
# CHECK-NEXT:  1      1     0.50                        {evex}	sarb	$123, %bl
# CHECK-NEXT:  1      1     0.50                        {nf}	sarb	$123, %bl
# CHECK-NEXT:  1      1     0.50                        sarb	$123, %bl, %bl
# CHECK-NEXT:  1      1     0.50                        {nf}	sarb	$123, %bl, %bl
# CHECK-NEXT:  1      1     0.50                        {evex}	sarw	$123, %dx
# CHECK-NEXT:  1      1     0.50                        {nf}	sarw	$123, %dx
# CHECK-NEXT:  1      1     0.50                        sarw	$123, %dx, %dx
# CHECK-NEXT:  1      1     0.50                        {nf}	sarw	$123, %dx, %dx
# CHECK-NEXT:  1      1     0.50                        {evex}	sarl	$123, %ecx
# CHECK-NEXT:  1      1     0.50                        {nf}	sarl	$123, %ecx
# CHECK-NEXT:  1      1     0.50                        sarl	$123, %ecx, %ecx
# CHECK-NEXT:  1      1     0.50                        {nf}	sarl	$123, %ecx, %ecx
# CHECK-NEXT:  1      1     0.50                        {evex}	sarq	$123, %r9
# CHECK-NEXT:  1      1     0.50                        {nf}	sarq	$123, %r9
# CHECK-NEXT:  1      1     0.50                        sarq	$123, %r9, %r9
# CHECK-NEXT:  1      1     0.50                        {nf}	sarq	$123, %r9, %r9
# CHECK-NEXT:  4      12    0.50    *      *            {evex}	sarb	$123, 291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *      *            {nf}	sarb	$123, 291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *                   sarb	$123, 291(%r8,%rax,4), %bl
# CHECK-NEXT:  4      12    0.50    *                   {nf}	sarb	$123, 291(%r8,%rax,4), %bl
# CHECK-NEXT:  4      12    0.50    *      *            {evex}	sarw	$123, 291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *      *            {nf}	sarw	$123, 291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *                   sarw	$123, 291(%r8,%rax,4), %dx
# CHECK-NEXT:  4      12    0.50    *                   {nf}	sarw	$123, 291(%r8,%rax,4), %dx
# CHECK-NEXT:  4      12    0.50    *      *            {evex}	sarl	$123, 291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *      *            {nf}	sarl	$123, 291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *                   sarl	$123, 291(%r8,%rax,4), %ecx
# CHECK-NEXT:  4      12    0.50    *                   {nf}	sarl	$123, 291(%r8,%rax,4), %ecx
# CHECK-NEXT:  4      12    0.50    *      *            {evex}	sarq	$123, 291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *      *            {nf}	sarq	$123, 291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *                   sarq	$123, 291(%r8,%rax,4), %r9
# CHECK-NEXT:  4      12    0.50    *                   {nf}	sarq	$123, 291(%r8,%rax,4), %r9
# CHECK-NEXT:  1      1     0.50                        {evex}	sarb	%bl
# CHECK-NEXT:  1      1     0.50                        {nf}	sarb	%bl
# CHECK-NEXT:  1      1     0.50                        sarb	%bl, %bl
# CHECK-NEXT:  1      1     0.50                        {nf}	sarb	%bl, %bl
# CHECK-NEXT:  2      2     1.00                        {evex}	sarb	%cl, %bl
# CHECK-NEXT:  2      2     1.00                        {nf}	sarb	%cl, %bl
# CHECK-NEXT:  2      2     1.00                        sarb	%cl, %bl, %bl
# CHECK-NEXT:  2      2     1.00                        {nf}	sarb	%cl, %bl, %bl
# CHECK-NEXT:  2      2     1.00                        {evex}	sarw	%cl, %dx
# CHECK-NEXT:  2      2     1.00                        {nf}	sarw	%cl, %dx
# CHECK-NEXT:  2      2     1.00                        sarw	%cl, %dx, %dx
# CHECK-NEXT:  2      2     1.00                        {nf}	sarw	%cl, %dx, %dx
# CHECK-NEXT:  2      2     1.00                        {evex}	sarl	%cl, %ecx
# CHECK-NEXT:  2      2     1.00                        {nf}	sarl	%cl, %ecx
# CHECK-NEXT:  2      2     1.00                        sarl	%cl, %ecx, %ecx
# CHECK-NEXT:  2      2     1.00                        {nf}	sarl	%cl, %ecx, %ecx
# CHECK-NEXT:  2      2     1.00                        {evex}	sarq	%cl, %r9
# CHECK-NEXT:  2      2     1.00                        {nf}	sarq	%cl, %r9
# CHECK-NEXT:  2      2     1.00                        sarq	%cl, %r9, %r9
# CHECK-NEXT:  2      2     1.00                        {nf}	sarq	%cl, %r9, %r9
# CHECK-NEXT:  5      12    1.00    *      *            {evex}	sarb	%cl, 291(%r8,%rax,4)
# CHECK-NEXT:  5      12    1.00    *      *            {nf}	sarb	%cl, 291(%r8,%rax,4)
# CHECK-NEXT:  5      12    1.00    *                   sarb	%cl, 291(%r8,%rax,4), %bl
# CHECK-NEXT:  5      12    1.00    *                   {nf}	sarb	%cl, 291(%r8,%rax,4), %bl
# CHECK-NEXT:  5      12    1.00    *      *            {evex}	sarw	%cl, 291(%r8,%rax,4)
# CHECK-NEXT:  5      12    1.00    *      *            {nf}	sarw	%cl, 291(%r8,%rax,4)
# CHECK-NEXT:  5      12    1.00    *                   sarw	%cl, 291(%r8,%rax,4), %dx
# CHECK-NEXT:  5      12    1.00    *                   {nf}	sarw	%cl, 291(%r8,%rax,4), %dx
# CHECK-NEXT:  5      12    1.00    *      *            {evex}	sarl	%cl, 291(%r8,%rax,4)
# CHECK-NEXT:  5      12    1.00    *      *            {nf}	sarl	%cl, 291(%r8,%rax,4)
# CHECK-NEXT:  5      12    1.00    *                   sarl	%cl, 291(%r8,%rax,4), %ecx
# CHECK-NEXT:  5      12    1.00    *                   {nf}	sarl	%cl, 291(%r8,%rax,4), %ecx
# CHECK-NEXT:  5      12    1.00    *      *            {evex}	sarq	%cl, 291(%r8,%rax,4)
# CHECK-NEXT:  5      12    1.00    *      *            {nf}	sarq	%cl, 291(%r8,%rax,4)
# CHECK-NEXT:  5      12    1.00    *                   sarq	%cl, 291(%r8,%rax,4), %r9
# CHECK-NEXT:  5      12    1.00    *                   {nf}	sarq	%cl, 291(%r8,%rax,4), %r9
# CHECK-NEXT:  1      1     0.50                        {evex}	sarw	%dx
# CHECK-NEXT:  1      1     0.50                        {nf}	sarw	%dx
# CHECK-NEXT:  1      1     0.50                        sarw	%dx, %dx
# CHECK-NEXT:  1      1     0.50                        {nf}	sarw	%dx, %dx
# CHECK-NEXT:  1      1     0.50                        {evex}	sarl	%ecx
# CHECK-NEXT:  1      1     0.50                        {nf}	sarl	%ecx
# CHECK-NEXT:  1      1     0.50                        sarl	%ecx, %ecx
# CHECK-NEXT:  1      1     0.50                        {nf}	sarl	%ecx, %ecx
# CHECK-NEXT:  1      1     0.50                        {evex}	sarq	%r9
# CHECK-NEXT:  1      1     0.50                        {nf}	sarq	%r9
# CHECK-NEXT:  1      1     0.50                        sarq	%r9, %r9
# CHECK-NEXT:  1      1     0.50                        {nf}	sarq	%r9, %r9
# CHECK-NEXT:  4      12    0.50    *      *            {evex}	sarb	291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *      *            {nf}	sarb	291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *                   sarb	291(%r8,%rax,4), %bl
# CHECK-NEXT:  4      12    0.50    *                   {nf}	sarb	291(%r8,%rax,4), %bl
# CHECK-NEXT:  4      12    0.50    *      *            {evex}	sarw	291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *      *            {nf}	sarw	291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *                   sarw	291(%r8,%rax,4), %dx
# CHECK-NEXT:  4      12    0.50    *                   {nf}	sarw	291(%r8,%rax,4), %dx
# CHECK-NEXT:  4      12    0.50    *      *            {evex}	sarl	291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *      *            {nf}	sarl	291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *                   sarl	291(%r8,%rax,4), %ecx
# CHECK-NEXT:  4      12    0.50    *                   {nf}	sarl	291(%r8,%rax,4), %ecx
# CHECK-NEXT:  4      12    0.50    *      *            {evex}	sarq	291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *      *            {nf}	sarq	291(%r8,%rax,4)
# CHECK-NEXT:  4      12    0.50    *                   sarq	291(%r8,%rax,4), %r9
# CHECK-NEXT:  4      12    0.50    *                   {nf}	sarq	291(%r8,%rax,4), %r9

# CHECK:      Resources:
# CHECK-NEXT: [0]   - SPRPort00
# CHECK-NEXT: [1]   - SPRPort01
# CHECK-NEXT: [2]   - SPRPort02
# CHECK-NEXT: [3]   - SPRPort03
# CHECK-NEXT: [4]   - SPRPort04
# CHECK-NEXT: [5]   - SPRPort05
# CHECK-NEXT: [6]   - SPRPort06
# CHECK-NEXT: [7]   - SPRPort07
# CHECK-NEXT: [8]   - SPRPort08
# CHECK-NEXT: [9]   - SPRPort09
# CHECK-NEXT: [10]  - SPRPort10
# CHECK-NEXT: [11]  - SPRPort11
# CHECK-NEXT: [12]  - SPRPortInvalid

# CHECK:      Resource pressure per iteration:
# CHECK-NEXT: [0]    [1]    [2]    [3]    [4]    [5]    [6]    [7]    [8]    [9]    [10]   [11]   [12]
# CHECK-NEXT: 64.00   -     16.00  16.00  24.00   -     64.00  24.00  24.00  24.00   -     16.00   -

# CHECK:      Resource pressure by instruction:
# CHECK-NEXT: [0]    [1]    [2]    [3]    [4]    [5]    [6]    [7]    [8]    [9]    [10]   [11]   [12]   Instructions:
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {evex}	sarb	$123, %bl
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarb	$123, %bl
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     sarb	$123, %bl, %bl
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarb	$123, %bl, %bl
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {evex}	sarw	$123, %dx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarw	$123, %dx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     sarw	$123, %dx, %dx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarw	$123, %dx, %dx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {evex}	sarl	$123, %ecx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarl	$123, %ecx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     sarl	$123, %ecx, %ecx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarl	$123, %ecx, %ecx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {evex}	sarq	$123, %r9
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarq	$123, %r9
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     sarq	$123, %r9, %r9
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarq	$123, %r9, %r9
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {evex}	sarb	$123, 291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarb	$123, 291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     sarb	$123, 291(%r8,%rax,4), %bl
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarb	$123, 291(%r8,%rax,4), %bl
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {evex}	sarw	$123, 291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarw	$123, 291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     sarw	$123, 291(%r8,%rax,4), %dx
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarw	$123, 291(%r8,%rax,4), %dx
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {evex}	sarl	$123, 291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarl	$123, 291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     sarl	$123, 291(%r8,%rax,4), %ecx
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarl	$123, 291(%r8,%rax,4), %ecx
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {evex}	sarq	$123, 291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarq	$123, 291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     sarq	$123, 291(%r8,%rax,4), %r9
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarq	$123, 291(%r8,%rax,4), %r9
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {evex}	sarb	%bl
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarb	%bl
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     sarb	%bl, %bl
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarb	%bl, %bl
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     {evex}	sarb	%cl, %bl
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     {nf}	sarb	%cl, %bl
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     sarb	%cl, %bl, %bl
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     {nf}	sarb	%cl, %bl, %bl
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     {evex}	sarw	%cl, %dx
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     {nf}	sarw	%cl, %dx
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     sarw	%cl, %dx, %dx
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     {nf}	sarw	%cl, %dx, %dx
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     {evex}	sarl	%cl, %ecx
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     {nf}	sarl	%cl, %ecx
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     sarl	%cl, %ecx, %ecx
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     {nf}	sarl	%cl, %ecx, %ecx
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     {evex}	sarq	%cl, %r9
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     {nf}	sarq	%cl, %r9
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     sarq	%cl, %r9, %r9
# CHECK-NEXT: 1.00    -      -      -      -      -     1.00    -      -      -      -      -      -     {nf}	sarq	%cl, %r9, %r9
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     {evex}	sarb	%cl, 291(%r8,%rax,4)
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     {nf}	sarb	%cl, 291(%r8,%rax,4)
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     sarb	%cl, 291(%r8,%rax,4), %bl
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     {nf}	sarb	%cl, 291(%r8,%rax,4), %bl
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     {evex}	sarw	%cl, 291(%r8,%rax,4)
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     {nf}	sarw	%cl, 291(%r8,%rax,4)
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     sarw	%cl, 291(%r8,%rax,4), %dx
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     {nf}	sarw	%cl, 291(%r8,%rax,4), %dx
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     {evex}	sarl	%cl, 291(%r8,%rax,4)
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     {nf}	sarl	%cl, 291(%r8,%rax,4)
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     sarl	%cl, 291(%r8,%rax,4), %ecx
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     {nf}	sarl	%cl, 291(%r8,%rax,4), %ecx
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     {evex}	sarq	%cl, 291(%r8,%rax,4)
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     {nf}	sarq	%cl, 291(%r8,%rax,4)
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     sarq	%cl, 291(%r8,%rax,4), %r9
# CHECK-NEXT: 1.00    -     0.33   0.33   0.50    -     1.00   0.50   0.50   0.50    -     0.33    -     {nf}	sarq	%cl, 291(%r8,%rax,4), %r9
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {evex}	sarw	%dx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarw	%dx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     sarw	%dx, %dx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarw	%dx, %dx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {evex}	sarl	%ecx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarl	%ecx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     sarl	%ecx, %ecx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarl	%ecx, %ecx
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {evex}	sarq	%r9
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarq	%r9
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     sarq	%r9, %r9
# CHECK-NEXT: 0.50    -      -      -      -      -     0.50    -      -      -      -      -      -     {nf}	sarq	%r9, %r9
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {evex}	sarb	291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarb	291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     sarb	291(%r8,%rax,4), %bl
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarb	291(%r8,%rax,4), %bl
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {evex}	sarw	291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarw	291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     sarw	291(%r8,%rax,4), %dx
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarw	291(%r8,%rax,4), %dx
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {evex}	sarl	291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarl	291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     sarl	291(%r8,%rax,4), %ecx
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarl	291(%r8,%rax,4), %ecx
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {evex}	sarq	291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarq	291(%r8,%rax,4)
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     sarq	291(%r8,%rax,4), %r9
# CHECK-NEXT: 0.50    -     0.33   0.33   0.50    -     0.50   0.50   0.50   0.50    -     0.33    -     {nf}	sarq	291(%r8,%rax,4), %r9
