; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes="instcombine" < %s -mtriple=x86_64-unknown-unknown -mattr=+bmi -S | FileCheck %s
; RUN: opt -passes="instcombine" < %s -mtriple=x86_64-unknown-unknown -mattr=-bmi -S | FileCheck %s --check-prefix=NOBMI
; REQUIRES: x86-registered-target

@_ZL10magictable = internal constant [64 x i32] [i32 0, i32 1, i32 12, i32 2, i32 13, i32 22, i32 17, i32 3, i32 14, i32 33, i32 23, i32 36, i32 18, i32 58, i32 28, i32 4, i32 62, i32 15, i32 34, i32 26, i32 24, i32 48, i32 50, i32 37, i32 19, i32 55, i32 59, i32 52, i32 29, i32 44, i32 39, i32 5, i32 63, i32 11, i32 21, i32 16, i32 32, i32 35, i32 57, i32 27, i32 61, i32 25, i32 47, i32 49, i32 54, i32 51, i32 43, i32 38, i32 10, i32 20, i32 31, i32 56, i32 60, i32 46, i32 53, i32 42, i32 9, i32 30, i32 45, i32 41, i32 8, i32 40, i32 7, i32 6]

@_ZL10notmagictable = internal constant [64 x i32] [i32 0, i32 1, i32 12, i32 2, i32 13, i32 90, i32 17, i32 3, i32 14, i32 33, i32 23, i32 36, i32 18, i32 58, i32 28, i32 4, i32 62, i32 15, i32 34, i32 26, i32 24, i32 48, i32 50, i32 37, i32 19, i32 55, i32 59, i32 52, i32 29, i32 44, i32 39, i32 5, i32 63, i32 11, i32 21, i32 16, i32 32, i32 35, i32 57, i32 27, i32 39, i32 25, i32 47, i32 49, i32 54, i32 51, i32 43, i32 38, i32 10, i32 20, i32 31, i32 56, i32 43, i32 46, i32 53, i32 42, i32 9, i32 30, i32 45, i32 13, i32 8, i32 40, i32 7, i32 6]

define i32 @_Z9FindFirsty(i64 %b) {
; CHECK-LABEL: @_Z9FindFirsty(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cttz.i64(i64 [[B:%.*]], i1 true), !range [[RNG0:![0-9]+]]
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i64 [[B]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[TMP0]] to i32
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[DOTNOT]], i32 0, i32 [[TMP1]]
; CHECK-NEXT:    ret i32 [[TMP2]]
;
; NOBMI-LABEL: @_Z9FindFirsty(
; NOBMI-NEXT:  entry:
; NOBMI-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cttz.i64(i64 [[B:%.*]], i1 true), !range [[RNG0:![0-9]+]]
; NOBMI-NEXT:    [[DOTNOT:%.*]] = icmp eq i64 [[B]], 0
; NOBMI-NEXT:    [[TMP1:%.*]] = trunc i64 [[TMP0]] to i32
; NOBMI-NEXT:    [[TMP2:%.*]] = select i1 [[DOTNOT]], i32 0, i32 [[TMP1]]
; NOBMI-NEXT:    ret i32 [[TMP2]]
;
entry:
  %sub = sub i64 0, %b
  %and = and i64 %sub, %b
  %mul = mul i64 %and, 283881067100198605
  %shr = lshr i64 %mul, 58
  %arrayidx = getelementptr inbounds [64 x i32], ptr @_ZL10magictable, i64 0, i64 %shr
  %0 = load i32, ptr %arrayidx, align 4
  ret i32 %0
}

define i32 @_Z9FindFirst2y(i64 %b) {
; CHECK-LABEL: @_Z9FindFirst2y(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SUB:%.*]] = sub i64 0, [[B:%.*]]
; CHECK-NEXT:    [[AND:%.*]] = and i64 [[SUB]], [[B]]
; CHECK-NEXT:    [[MUL:%.*]] = mul i64 [[AND]], 283881067100198605
; CHECK-NEXT:    [[SHR:%.*]] = lshr i64 [[MUL]], 58
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [64 x i32], ptr @_ZL10notmagictable, i64 0, i64 [[SHR]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    ret i32 [[TMP0]]
;
; NOBMI-LABEL: @_Z9FindFirst2y(
; NOBMI-NEXT:  entry:
; NOBMI-NEXT:    [[SUB:%.*]] = sub i64 0, [[B:%.*]]
; NOBMI-NEXT:    [[AND:%.*]] = and i64 [[SUB]], [[B]]
; NOBMI-NEXT:    [[MUL:%.*]] = mul i64 [[AND]], 283881067100198605
; NOBMI-NEXT:    [[SHR:%.*]] = lshr i64 [[MUL]], 58
; NOBMI-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [64 x i32], ptr @_ZL10notmagictable, i64 0, i64 [[SHR]]
; NOBMI-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; NOBMI-NEXT:    ret i32 [[TMP0]]
;
entry:
  %sub = sub i64 0, %b
  %and = and i64 %sub, %b
  %mul = mul i64 %and, 283881067100198605
  %shr = lshr i64 %mul, 58
  %arrayidx = getelementptr inbounds [64 x i32], ptr @_ZL10notmagictable, i64 0, i64 %shr
  %0 = load i32, ptr %arrayidx, align 4
  ret i32 %0
}

define i32 @_Z15FindFirstRemovePy(ptr nocapture %b) {
; CHECK-LABEL: @_Z15FindFirstRemovePy(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B:%.*]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[TMP0]], -1
; CHECK-NEXT:    [[XOR:%.*]] = and i64 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    store i64 [[XOR]], ptr [[B]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @llvm.cttz.i64(i64 [[TMP0]], i1 true), !range [[RNG0]]
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i64 [[TMP0]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = select i1 [[DOTNOT]], i32 0, i32 [[TMP3]]
; CHECK-NEXT:    ret i32 [[TMP4]]
;
; NOBMI-LABEL: @_Z15FindFirstRemovePy(
; NOBMI-NEXT:  entry:
; NOBMI-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B:%.*]], align 8
; NOBMI-NEXT:    [[TMP1:%.*]] = add i64 [[TMP0]], -1
; NOBMI-NEXT:    [[XOR:%.*]] = and i64 [[TMP0]], [[TMP1]]
; NOBMI-NEXT:    store i64 [[XOR]], ptr [[B]], align 8
; NOBMI-NEXT:    [[TMP2:%.*]] = call i64 @llvm.cttz.i64(i64 [[TMP0]], i1 true), !range [[RNG0]]
; NOBMI-NEXT:    [[DOTNOT:%.*]] = icmp eq i64 [[TMP0]], 0
; NOBMI-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
; NOBMI-NEXT:    [[TMP4:%.*]] = select i1 [[DOTNOT]], i32 0, i32 [[TMP3]]
; NOBMI-NEXT:    ret i32 [[TMP4]]
;
entry:
  %0 = load i64, ptr %b, align 8
  %sub = sub i64 0, %0
  %and = and i64 %0, %sub
  %xor = xor i64 %and, %0
  store i64 %xor, ptr %b, align 8
  %mul = mul i64 %and, 283881067100198605
  %shr = lshr i64 %mul, 58
  %arrayidx = getelementptr inbounds [64 x i32], ptr @_ZL10magictable, i64 0, i64 %shr
  %1 = load i32, ptr %arrayidx, align 4
  ret i32 %1
}

@magictable32 = internal constant [32 x i32] [i32 0, i32 1, i32 28, i32 2, i32 29, i32 14, i32 24, i32 3, i32 30, i32 22, i32 20, i32 15, i32 25, i32 17, i32 4, i32 8, i32 31, i32 27, i32 13, i32 23, i32 21, i32 19, i32 16, i32 7, i32 26, i32 12, i32 18, i32 6, i32 11, i32 5, i32 10, i32 9]

define i32 @FindFirst32(i32 %b) {
; CHECK-LABEL: @FindFirst32(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.cttz.i32(i32 [[B:%.*]], i1 true), !range [[RNG1:![0-9]+]]
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i32 [[B]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[DOTNOT]], i32 0, i32 [[TMP0]]
; CHECK-NEXT:    ret i32 [[TMP1]]
;
; NOBMI-LABEL: @FindFirst32(
; NOBMI-NEXT:  entry:
; NOBMI-NEXT:    [[TMP0:%.*]] = call i32 @llvm.cttz.i32(i32 [[B:%.*]], i1 true), !range [[RNG1:![0-9]+]]
; NOBMI-NEXT:    [[DOTNOT:%.*]] = icmp eq i32 [[B]], 0
; NOBMI-NEXT:    [[TMP1:%.*]] = select i1 [[DOTNOT]], i32 0, i32 [[TMP0]]
; NOBMI-NEXT:    ret i32 [[TMP1]]
;
entry:
  %sub = sub i32 0, %b
  %and = and i32 %sub, %b
  %mul = mul i32 %and, 125613361
  %shr = lshr i32 %mul, 27
  %ext = sext i32 %shr to i64
  %arrayidx = getelementptr inbounds [32 x i32], ptr @magictable32, i64 0, i64 %ext
  %0 = load i32, ptr %arrayidx, align 4
  ret i32 %0
}
