; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; This test case checks that the interprocedural sparse conditional constant
; propagation passes when the beginning of an array is casted to a pointer
; and it is used inside a callback.

; RUN: opt -passes=ipsccp -S %s | FileCheck %s --check-prefix OPAQUE

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%TestStruct = type { [16 x i8], [16 x i8], i32 }
@globArray = internal global [1000 x %TestStruct] zeroinitializer

; Check that @globArray was casted correctly and %Arr was replaced with
; %bc_const in the GEP %dummy
define internal void @callback(ptr %ID, ptr %Arr) {
; OPAQUE-LABEL: @callback(
; OPAQUE-NEXT:  entry:
; OPAQUE-NEXT:    ret void
;
entry:
  %dummy = getelementptr [1000 x %TestStruct], ptr %Arr, i64 0, i64 0
  ret void
}

; Check that the parameter in the call site for @callback was updated with the
; correct type
define internal void @foo(ptr %Arr) {
; OPAQUE-LABEL: @foo(
; OPAQUE-NEXT:  entry:
; OPAQUE-NEXT:    call void (i32, ptr, ...) @broker(i32 3, ptr @callback, ptr @globArray)
; OPAQUE-NEXT:    ret void
;
entry:
  call void (i32, void (ptr, ...)*, ...) @broker(i32 3, void (ptr, ...)* bitcast (void (ptr, ptr)* @callback to void (ptr, ...)*), ptr %Arr)
  ret void
}

define void @bar() {
; OPAQUE-LABEL: @bar(
; OPAQUE-NEXT:  entry:
; OPAQUE-NEXT:    call void @foo(ptr @globArray)
; OPAQUE-NEXT:    ret void
;
entry:
  call void @foo(ptr getelementptr inbounds ([1000 x %TestStruct], ptr bitcast (ptr @globArray to ptr), i64 0, i64 0))
  ret void
}

declare !callback !0 void @broker(i32, void (ptr, ...)*, ...)

!0 = !{!1}
!1 = !{i64 1, i64 -1, i1 true}
