// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: intel_feature_isa_avx512_vpmm
// RUN: %clang_cc1 -flax-vector-conversions=none -ffreestanding %s -triple=x86_64-linux-gnu -target-feature +avx512vpmm -target-feature +avx512vl -emit-llvm -o - -Wall -Werror | FileCheck %s

#include <immintrin.h>

__m128 test_mm_vmmf16_ps(__m128h Src1, __m128h Src2, __m128 SrcDst) {
  // CHECK-LABEL: @test_mm_vmmf16_ps(
  // CHECK: call <4 x float> @llvm.x86.vpmm.vmmf16ps.128(<4 x float> {{%.*}}, <8 x half> {{%.*}}, <8 x half> {{%.*}})
  return _mm_vmmf16_ps(Src1, Src2, SrcDst);
}

__m256 test_mm256_vmmf16_ps(__m256h Src1, __m256h Src2, __m256 SrcDst) {
  // CHECK-LABEL: @test_mm256_vmmf16_ps(
  // CHECK: call <8 x float> @llvm.x86.vpmm.vmmf16ps.256(<8 x float> {{%.*}}, <16 x half> {{%.*}}, <16 x half> {{%.*}})
  return _mm256_vmmf16_ps(Src1, Src2, SrcDst);
}

__m256 test_mm256_vmmbf16_ps(__m256 __A, __m256bh __B, __m256bh __C) {
  // CHECK-LABEL: @test_mm256_vmmbf16_ps(
  // CHECK: call <8 x float> @llvm.x86.vpmm.vmmbf16ps.256(<8 x float> {{%.*}}, <16 x bfloat> {{%.*}}, <16 x bfloat> {{%.*}})
  return _mm256_vmmbf16_ps(__B, __C, __A);
}

__m256 test_mm256_vmmbf8_ps(__m256 __A, __m256i __B, __m256i __C) {
  // CHECK-LABEL: @test_mm256_vmmbf8_ps(
  // CHECK: call <8 x float> @llvm.x86.vpmm.vmmbf8ps.256(<8 x float> {{%.*}}, <32 x i8> {{%.*}}, <32 x i8> {{%.*}})
  return _mm256_vmmbf8_ps(__B, __C, __A);
}

__m256 test_mm256_vmmbhf8_ps(__m256 __A, __m256i __B, __m256i __C) {
  // CHECK-LABEL: @test_mm256_vmmbhf8_ps(
  // CHECK: call <8 x float> @llvm.x86.vpmm.vmmbhf8ps.256(<8 x float> {{%.*}}, <32 x i8> {{%.*}}, <32 x i8> {{%.*}})
  return _mm256_vmmbhf8_ps(__B, __C, __A);
}

__m256 test_mm256_vmmhbf8_ps(__m256 __A, __m256i __B, __m256i __C) {
  // CHECK-LABEL: @test_mm256_vmmhbf8_ps(
  // CHECK: call <8 x float> @llvm.x86.vpmm.vmmhbf8ps.256(<8 x float> {{%.*}}, <32 x i8> {{%.*}}, <32 x i8> {{%.*}})
  return _mm256_vmmhbf8_ps(__B, __C, __A);
}

__m256 test_mm256_vmmhf8_ps(__m256 __A, __m256i __B, __m256i __C) {
  // CHECK-LABEL: @test_mm256_vmmhf8_ps(
  // CHECK: call <8 x float> @llvm.x86.vpmm.vmmhf8ps.256(<8 x float> {{%.*}}, <32 x i8> {{%.*}}, <32 x i8> {{%.*}})
  return _mm256_vmmhf8_ps(__B, __C, __A);
}

__m256 test_mm256_vmmtf32_ps(__m256 __A, __m256i __B, __m256i __C) {
  // CHECK-LABEL: @test_mm256_vmmtf32_ps(
  // CHECK: call <8 x float> @llvm.x86.vpmm.vmmtf32ps.256(<8 x float> {{%.*}}, <8 x i32> {{%.*}}, <8 x i32> {{%.*}})
  return _mm256_vmmtf32_ps(__B, __C, __A);
}

__m256i test_mm256_vpmmssbd_epi32(__m256i __A, __m256i __B, __m256i __C) {
  // CHECK-LABEL: @test_mm256_vpmmssbd_epi32(
  // CHECK: call <8 x i32> @llvm.x86.vpmm.vpmmssbd.256(<8 x i32> {{%.*}}, <32 x i8> {{%.*}}, <32 x i8> {{%.*}})
  return _mm256_vpmmssbd_epi32(__B, __C, __A);
}

__m256i test_mm256_vpmmsubd_epi32(__m256i __A, __m256i __B, __m256i __C) {
  // CHECK-LABEL: @test_mm256_vpmmsubd_epi32(
  // CHECK: call <8 x i32> @llvm.x86.vpmm.vpmmsubd.256(<8 x i32> {{%.*}}, <32 x i8> {{%.*}}, <32 x i8> {{%.*}})
  return _mm256_vpmmsubd_epi32(__B, __C, __A);
}

__m256i test_mm256_vpmmusbd_epi32(__m256i __A, __m256i __B, __m256i __C) {
  // CHECK-LABEL: @test_mm256_vpmmusbd_epi32(
  // CHECK: call <8 x i32> @llvm.x86.vpmm.vpmmusbd.256(<8 x i32> {{%.*}}, <32 x i8> {{%.*}}, <32 x i8> {{%.*}})
  return _mm256_vpmmusbd_epi32(__B, __C, __A);
}

__m256i test_mm256_vpmmuubd_epi32(__m256i __A, __m256i __B, __m256i __C) {
  // CHECK-LABEL: @test_mm256_vpmmuubd_epi32(
  // CHECK: call <8 x i32> @llvm.x86.vpmm.vpmmuubd.256(<8 x i32> {{%.*}}, <32 x i8> {{%.*}}, <32 x i8> {{%.*}})
  return _mm256_vpmmuubd_epi32(__B, __C, __A);
}

__m128 test_mm_vmmbf16_ps(__m128 __A, __m128bh __B, __m128bh __C) {
  // CHECK-LABEL: @test_mm_vmmbf16_ps(
  // CHECK: call <4 x float> @llvm.x86.vpmm.vmmbf16ps.128(<4 x float> {{%.*}}, <8 x bfloat> {{%.*}}, <8 x bfloat> {{%.*}})
  return _mm_vmmbf16_ps(__B, __C, __A);
}

__m128 test_mm_vmmbf8_ps(__m128 __A, __m128i __B, __m128i __C) {
  // CHECK-LABEL: @test_mm_vmmbf8_ps(
  // CHECK: call <4 x float> @llvm.x86.vpmm.vmmbf8ps.128(<4 x float> {{%.*}}, <16 x i8> {{%.*}}, <16 x i8> {{%.*}})
  return _mm_vmmbf8_ps(__B, __C, __A);
}

__m128 test_mm_vmmbhf8_ps(__m128 __A, __m128i __B, __m128i __C) {
  // CHECK-LABEL: @test_mm_vmmbhf8_ps(
  // CHECK: call <4 x float> @llvm.x86.vpmm.vmmbhf8ps.128(<4 x float> {{%.*}}, <16 x i8> {{%.*}}, <16 x i8> {{%.*}})
  return _mm_vmmbhf8_ps(__B, __C, __A);
}

__m128 test_mm_vmmhbf8_ps(__m128 __A, __m128i __B, __m128i __C) {
  // CHECK-LABEL: @test_mm_vmmhbf8_ps(
  // CHECK: call <4 x float> @llvm.x86.vpmm.vmmhbf8ps.128(<4 x float> {{%.*}}, <16 x i8> {{%.*}}, <16 x i8> {{%.*}})
  return _mm_vmmhbf8_ps(__B, __C, __A);
}

__m128 test_mm_vmmhf8_ps(__m128 __A, __m128i __B, __m128i __C) {
  // CHECK-LABEL: @test_mm_vmmhf8_ps(
  // CHECK: call <4 x float> @llvm.x86.vpmm.vmmhf8ps.128(<4 x float> {{%.*}}, <16 x i8> {{%.*}}, <16 x i8> {{%.*}})
  return _mm_vmmhf8_ps(__B, __C, __A);
}

__m128 test_mm_vmmtf32_ps(__m128 __A, __m128i __B, __m128i __C) {
  // CHECK-LABEL: @test_mm_vmmtf32_ps(
  // CHECK: call <4 x float> @llvm.x86.vpmm.vmmtf32ps.128(<4 x float> {{%.*}}, <4 x i32> {{%.*}}, <4 x i32> {{%.*}})
  return _mm_vmmtf32_ps(__B, __C, __A);
}

__m128i test_mm_vpmmssbd_epi32(__m128i __A, __m128i __B, __m128i __C) {
  // CHECK-LABEL: @test_mm_vpmmssbd_epi32(
  // CHECK: call <4 x i32> @llvm.x86.vpmm.vpmmssbd.128(<4 x i32> {{%.*}}, <16 x i8> {{%.*}}, <16 x i8> {{%.*}})
  return _mm_vpmmssbd_epi32(__B, __C, __A);
}

__m128i test_mm_vpmmsubd_epi32(__m128i __A, __m128i __B, __m128i __C) {
  // CHECK-LABEL: @test_mm_vpmmsubd_epi32(
  // CHECK: call <4 x i32> @llvm.x86.vpmm.vpmmsubd.128(<4 x i32> {{%.*}}, <16 x i8> {{%.*}}, <16 x i8> {{%.*}})
  return _mm_vpmmsubd_epi32(__B, __C, __A);
}

__m128i test_mm_vpmmusbd_epi32(__m128i __A, __m128i __B, __m128i __C) {
  // CHECK-LABEL: @test_mm_vpmmusbd_epi32(
  // CHECK: call <4 x i32> @llvm.x86.vpmm.vpmmusbd.128(<4 x i32> {{%.*}}, <16 x i8> {{%.*}}, <16 x i8> {{%.*}})
  return _mm_vpmmusbd_epi32(__B, __C, __A);
}

__m128i test_mm_vpmmuubd_epi32(__m128i __A, __m128i __B, __m128i __C) {
  // CHECK-LABEL: @test_mm_vpmmuubd_epi32(
  // CHECK: call <4 x i32> @llvm.x86.vpmm.vpmmuubd.128(<4 x i32> {{%.*}}, <16 x i8> {{%.*}}, <16 x i8> {{%.*}})
  return _mm_vpmmuubd_epi32(__B, __C, __A);
}
