// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: intel_feature_isa_avx512_vpmm
// RUN: %clang_cc1 -flax-vector-conversions=none -ffreestanding %s -triple=x86_64-linux-gnu -target-feature +avx512vpmm -emit-llvm -o - -Wall -Werror | FileCheck %s

#include <immintrin.h>

__m512 test_mm512_vmmf16_ps(__m512h Src1, __m512h Src2, __m512 SrcDst) {
// CHECK-LABEL: @test_mm512_vmmf16_ps(
// CHECK: call <16 x float> @llvm.x86.vpmm.vmmf16ps.512(<16 x float> {{%.*}}, <32 x half> {{%.*}}, <32 x half> {{%.*}})
  return _mm512_vmmf16_ps(Src1, Src2, SrcDst);
}

__m512 test_mm512_vmmbf16_ps(__m512 __A, __m512bh __B, __m512bh __C) {
  // CHECK-LABEL: @test_mm512_vmmbf16_ps(
  // CHECK: call <16 x float> @llvm.x86.vpmm.vmmbf16ps.512(<16 x float> {{%.*}}, <32 x bfloat> {{%.*}}, <32 x bfloat> {{%.*}})
  return _mm512_vmmbf16_ps(__B, __C, __A);
}

__m512 test_mm512_vmmbf8_ps(__m512 __A, __m512i __B, __m512i __C) {
  // CHECK-LABEL: @test_mm512_vmmbf8_ps(
  // CHECK: call <16 x float> @llvm.x86.vpmm.vmmbf8ps.512(<16 x float> {{%.*}}, <64 x i8> {{%.*}}, <64 x i8> {{%.*}})
  return _mm512_vmmbf8_ps(__B, __C, __A);
}

__m512 test_mm512_vmmbhf8_ps(__m512 __A, __m512i __B, __m512i __C) {
  // CHECK-LABEL: @test_mm512_vmmbhf8_ps(
  // CHECK: call <16 x float> @llvm.x86.vpmm.vmmbhf8ps.512(<16 x float> {{%.*}}, <64 x i8> {{%.*}}, <64 x i8> {{%.*}})
  return _mm512_vmmbhf8_ps(__B, __C, __A);
}

__m512 test_mm512_vmmhbf8_ps(__m512 __A, __m512i __B, __m512i __C) {
  // CHECK-LABEL: @test_mm512_vmmhbf8_ps(
  // CHECK: call <16 x float> @llvm.x86.vpmm.vmmhbf8ps.512(<16 x float> {{%.*}}, <64 x i8> {{%.*}}, <64 x i8> {{%.*}})
  return _mm512_vmmhbf8_ps(__B, __C, __A);
}

__m512 test_mm512_vmmhf8_ps(__m512 __A, __m512i __B, __m512i __C) {
  // CHECK-LABEL: @test_mm512_vmmhf8_ps(
  // CHECK: call <16 x float> @llvm.x86.vpmm.vmmhf8ps.512(<16 x float> {{%.*}}, <64 x i8> {{%.*}}, <64 x i8> {{%.*}})
  return _mm512_vmmhf8_ps(__B, __C, __A);
}

__m512 test_mm512_vmmtf32_ps(__m512 __A, __m512i __B, __m512i __C) {
  // CHECK-LABEL: @test_mm512_vmmtf32_ps(
  // CHECK: call <16 x float> @llvm.x86.vpmm.vmmtf32ps.512(<16 x float> {{%.*}}, <16 x i32> {{%.*}}, <16 x i32> {{%.*}})
  return _mm512_vmmtf32_ps(__B, __C, __A);
}

__m512i test_mm512_vpmmssbd_epi32(__m512i __A, __m512i __B, __m512i __C) {
  // CHECK-LABEL: @test_mm512_vpmmssbd_epi32(
  // CHECK: call <16 x i32> @llvm.x86.vpmm.vpmmssbd.512(<16 x i32> {{%.*}}, <64 x i8> {{%.*}}, <64 x i8> {{%.*}})
  return _mm512_vpmmssbd_epi32(__B, __C, __A);
}

__m512i test_mm512_vpmmsubd_epi32(__m512i __A, __m512i __B, __m512i __C) {
  // CHECK-LABEL: @test_mm512_vpmmsubd_epi32(
  // CHECK: call <16 x i32> @llvm.x86.vpmm.vpmmsubd.512(<16 x i32> {{%.*}}, <64 x i8> {{%.*}}, <64 x i8> {{%.*}})
  return _mm512_vpmmsubd_epi32(__B, __C, __A);
}

__m512i test_mm512_vpmmusbd_epi32(__m512i __A, __m512i __B, __m512i __C) {
  // CHECK-LABEL: @test_mm512_vpmmusbd_epi32(
  // CHECK: call <16 x i32> @llvm.x86.vpmm.vpmmusbd.512(<16 x i32> {{%.*}}, <64 x i8> {{%.*}}, <64 x i8> {{%.*}})
  return _mm512_vpmmusbd_epi32(__B, __C, __A);
}

__m512i test_mm512_vpmmuubd_epi32(__m512i __A, __m512i __B, __m512i __C) {
  // CHECK-LABEL: @test_mm512_vpmmuubd_epi32(
  // CHECK: call <16 x i32> @llvm.x86.vpmm.vpmmuubd.512(<16 x i32> {{%.*}}, <64 x i8> {{%.*}}, <64 x i8> {{%.*}})
  return _mm512_vpmmuubd_epi32(__B, __C, __A);
}
