// INTEL_COLLAB
// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --prefix-filecheck-ir-name a
// RUN: %clang_cc1 -no-opaque-pointers -verify -triple x86_64-unknown-linux-gnu -fopenmp -x c \
// RUN:  -fopenmp-late-outline -fopenmp-version=51 -emit-llvm %s -o - \
// RUN:  | FileCheck %s --check-prefix CHK-C

// RUN: %clang_cc1 -no-opaque-pointers -verify -triple x86_64-unknown-linux-gnu -fopenmp -x c \
// RUN: -fopenmp-late-outline -fopenmp-version=51 -emit-pch %s -o %t.pch

// RUN: %clang_cc1 -no-opaque-pointers -verify -triple x86_64-unknown-linux-gnu -fopenmp  -x c \
// RUN:  -fopenmp-late-outline -fopenmp-version=51 -emit-llvm %s -o - \
// RUN:  -include-pch %t.pch | FileCheck %s --check-prefix CHK-C
//
// RUN: %clang_cc1 -no-opaque-pointers -verify -triple x86_64-unknown-linux-gnu -fopenmp \
// RUN:  -fopenmp-late-outline -fopenmp-version=51 -emit-llvm %s -o - \
// RUN:  | FileCheck %s --check-prefix CHK-CXX
//
// RUN: %clang_cc1 -no-opaque-pointers -verify -triple x86_64-unknown-linux-gnu -fopenmp \
// RUN: -fopenmp-late-outline -fopenmp-version=51 -emit-pch %s -o %t.pch

// RUN: %clang_cc1 -no-opaque-pointers -verify -triple x86_64-unknown-linux-gnu -fopenmp \
// RUN:  -fopenmp-late-outline -fopenmp-version=51 -emit-llvm %s -o - \
// RUN:  -include-pch %t.pch | FileCheck %s --check-prefix CHK-CXX
//
// expected-no-diagnostics
#ifndef HEADER
#define HEADER

// CHK-C-LABEL: @test_int(
// CHK-C-NEXT:  entry:
// CHK-C-NEXT:    [[X:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[EXPR:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[D:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[E:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[V:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[R:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[TMP:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP5:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP7:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP10:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP16:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP18:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP21:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP27:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP29:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP32:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP39:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP41:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP44:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP50:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP52:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP55:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP62:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP64:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP67:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP73:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP75:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP78:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP85:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP87:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP90:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP96:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP98:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP101:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP108:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP110:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP113:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP120:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP122:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP125:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP131:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP133:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP136:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[TMP0:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD]], i32* [[TMP]], align 4
// CHK-C-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[ATOMIC_LOAD]], [[TMP0]]
// CHK-C-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-C:       atomic_cont:
// CHK-C-NEXT:    [[TMP1:%.*]] = phi i32 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP4:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP0]], i32* [[ATOMIC_TEMP]], align 4
// CHK-C-NEXT:    [[TMP2:%.*]] = load i32, i32* [[ATOMIC_TEMP]], align 4
// CHK-C-NEXT:    [[TMP3:%.*]] = cmpxchg i32* [[X]], i32 [[TMP1]], i32 [[TMP2]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP4]] = extractvalue { i32, i1 } [[TMP3]], 0
// CHK-C-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i1 } [[TMP3]], 1
// CHK-C-NEXT:    br i1 [[TMP5]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-C:       atomic_cmp:
// CHK-C-NEXT:    store i32 [[TMP4]], i32* [[TMP]], align 4
// CHK-C-NEXT:    [[CMP2:%.*]] = icmp sgt i32 [[TMP4]], [[TMP0]]
// CHK-C-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[CMP2]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL3]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP2]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-C:       atomic_exit:
// CHK-C-NEXT:    [[TMP6:%.*]] = load i32, i32* [[TMP]], align 4
// CHK-C-NEXT:    [[TMP7:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-C-NEXT:    store i32 [[TMP6]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP8:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD4:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD4]], i32* [[ATMP5]], align 4
// CHK-C-NEXT:    [[CMP6:%.*]] = icmp sgt i32 [[ATOMIC_LOAD4]], [[TMP8]]
// CHK-C-NEXT:    [[FROMBOOL8:%.*]] = zext i1 [[CMP6]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL8]], i8* [[ATMP7]], align 1
// CHK-C-NEXT:    br i1 [[CMP6]], label [[ATOMIC_CONT9:%.*]], label [[ATOMIC_EXIT14:%.*]]
// CHK-C:       atomic_cont9:
// CHK-C-NEXT:    [[TMP9:%.*]] = phi i32 [ [[ATOMIC_LOAD4]], [[ATOMIC_EXIT]] ], [ [[TMP12:%.*]], [[ATOMIC_CMP11:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP8]], i32* [[ATOMIC_TEMP10]], align 4
// CHK-C-NEXT:    [[TMP10:%.*]] = load i32, i32* [[ATOMIC_TEMP10]], align 4
// CHK-C-NEXT:    [[TMP11:%.*]] = cmpxchg i32* [[X]], i32 [[TMP9]], i32 [[TMP10]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP12]] = extractvalue { i32, i1 } [[TMP11]], 0
// CHK-C-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i1 } [[TMP11]], 1
// CHK-C-NEXT:    br i1 [[TMP13]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP11]]
// CHK-C:       atomic_upd_exit:
// CHK-C-NEXT:    store i32 [[TMP8]], i32* [[ATMP5]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT14]]
// CHK-C:       atomic_cmp11:
// CHK-C-NEXT:    store i32 [[TMP12]], i32* [[ATMP5]], align 4
// CHK-C-NEXT:    [[CMP12:%.*]] = icmp sgt i32 [[TMP12]], [[TMP8]]
// CHK-C-NEXT:    [[FROMBOOL13:%.*]] = zext i1 [[CMP12]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL13]], i8* [[ATMP7]], align 1
// CHK-C-NEXT:    br i1 [[CMP12]], label [[ATOMIC_CONT9]], label [[ATOMIC_EXIT14]]
// CHK-C:       atomic_exit14:
// CHK-C-NEXT:    [[TMP14:%.*]] = load i32, i32* [[ATMP5]], align 4
// CHK-C-NEXT:    [[TMP15:%.*]] = load i8, i8* [[ATMP7]], align 1
// CHK-C-NEXT:    store i32 [[TMP14]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP16:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD15:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD15]], i32* [[ATMP16]], align 4
// CHK-C-NEXT:    [[CMP17:%.*]] = icmp slt i32 [[ATOMIC_LOAD15]], [[TMP16]]
// CHK-C-NEXT:    [[FROMBOOL19:%.*]] = zext i1 [[CMP17]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL19]], i8* [[ATMP18]], align 1
// CHK-C-NEXT:    br i1 [[CMP17]], label [[ATOMIC_CONT20:%.*]], label [[ATOMIC_EXIT25:%.*]]
// CHK-C:       atomic_cont20:
// CHK-C-NEXT:    [[TMP17:%.*]] = phi i32 [ [[ATOMIC_LOAD15]], [[ATOMIC_EXIT14]] ], [ [[TMP20:%.*]], [[ATOMIC_CMP22:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP16]], i32* [[ATOMIC_TEMP21]], align 4
// CHK-C-NEXT:    [[TMP18:%.*]] = load i32, i32* [[ATOMIC_TEMP21]], align 4
// CHK-C-NEXT:    [[TMP19:%.*]] = cmpxchg i32* [[X]], i32 [[TMP17]], i32 [[TMP18]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP20]] = extractvalue { i32, i1 } [[TMP19]], 0
// CHK-C-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i1 } [[TMP19]], 1
// CHK-C-NEXT:    br i1 [[TMP21]], label [[ATOMIC_EXIT25]], label [[ATOMIC_CMP22]]
// CHK-C:       atomic_cmp22:
// CHK-C-NEXT:    store i32 [[TMP20]], i32* [[ATMP16]], align 4
// CHK-C-NEXT:    [[CMP23:%.*]] = icmp slt i32 [[TMP20]], [[TMP16]]
// CHK-C-NEXT:    [[FROMBOOL24:%.*]] = zext i1 [[CMP23]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL24]], i8* [[ATMP18]], align 1
// CHK-C-NEXT:    br i1 [[CMP23]], label [[ATOMIC_CONT20]], label [[ATOMIC_EXIT25]]
// CHK-C:       atomic_exit25:
// CHK-C-NEXT:    [[TMP22:%.*]] = load i32, i32* [[ATMP16]], align 4
// CHK-C-NEXT:    [[TMP23:%.*]] = load i8, i8* [[ATMP18]], align 1
// CHK-C-NEXT:    store i32 [[TMP22]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP24:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD26:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD26]], i32* [[ATMP27]], align 4
// CHK-C-NEXT:    [[CMP28:%.*]] = icmp slt i32 [[ATOMIC_LOAD26]], [[TMP24]]
// CHK-C-NEXT:    [[FROMBOOL30:%.*]] = zext i1 [[CMP28]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL30]], i8* [[ATMP29]], align 1
// CHK-C-NEXT:    br i1 [[CMP28]], label [[ATOMIC_CONT31:%.*]], label [[ATOMIC_EXIT37:%.*]]
// CHK-C:       atomic_cont31:
// CHK-C-NEXT:    [[TMP25:%.*]] = phi i32 [ [[ATOMIC_LOAD26]], [[ATOMIC_EXIT25]] ], [ [[TMP28:%.*]], [[ATOMIC_CMP34:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP24]], i32* [[ATOMIC_TEMP32]], align 4
// CHK-C-NEXT:    [[TMP26:%.*]] = load i32, i32* [[ATOMIC_TEMP32]], align 4
// CHK-C-NEXT:    [[TMP27:%.*]] = cmpxchg i32* [[X]], i32 [[TMP25]], i32 [[TMP26]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP28]] = extractvalue { i32, i1 } [[TMP27]], 0
// CHK-C-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i1 } [[TMP27]], 1
// CHK-C-NEXT:    br i1 [[TMP29]], label [[ATOMIC_UPD_EXIT33:%.*]], label [[ATOMIC_CMP34]]
// CHK-C:       atomic_upd_exit33:
// CHK-C-NEXT:    store i32 [[TMP24]], i32* [[ATMP27]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT37]]
// CHK-C:       atomic_cmp34:
// CHK-C-NEXT:    store i32 [[TMP28]], i32* [[ATMP27]], align 4
// CHK-C-NEXT:    [[CMP35:%.*]] = icmp slt i32 [[TMP28]], [[TMP24]]
// CHK-C-NEXT:    [[FROMBOOL36:%.*]] = zext i1 [[CMP35]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL36]], i8* [[ATMP29]], align 1
// CHK-C-NEXT:    br i1 [[CMP35]], label [[ATOMIC_CONT31]], label [[ATOMIC_EXIT37]]
// CHK-C:       atomic_exit37:
// CHK-C-NEXT:    [[TMP30:%.*]] = load i32, i32* [[ATMP27]], align 4
// CHK-C-NEXT:    [[TMP31:%.*]] = load i8, i8* [[ATMP29]], align 1
// CHK-C-NEXT:    store i32 [[TMP30]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP32:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD38:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD38]], i32* [[ATMP39]], align 4
// CHK-C-NEXT:    [[CMP40:%.*]] = icmp slt i32 [[ATOMIC_LOAD38]], [[TMP32]]
// CHK-C-NEXT:    [[FROMBOOL42:%.*]] = zext i1 [[CMP40]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL42]], i8* [[ATMP41]], align 1
// CHK-C-NEXT:    br i1 [[CMP40]], label [[ATOMIC_CONT43:%.*]], label [[ATOMIC_EXIT48:%.*]]
// CHK-C:       atomic_cont43:
// CHK-C-NEXT:    [[TMP33:%.*]] = phi i32 [ [[ATOMIC_LOAD38]], [[ATOMIC_EXIT37]] ], [ [[TMP36:%.*]], [[ATOMIC_CMP45:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP32]], i32* [[ATOMIC_TEMP44]], align 4
// CHK-C-NEXT:    [[TMP34:%.*]] = load i32, i32* [[ATOMIC_TEMP44]], align 4
// CHK-C-NEXT:    [[TMP35:%.*]] = cmpxchg i32* [[X]], i32 [[TMP33]], i32 [[TMP34]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP36]] = extractvalue { i32, i1 } [[TMP35]], 0
// CHK-C-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i1 } [[TMP35]], 1
// CHK-C-NEXT:    br i1 [[TMP37]], label [[ATOMIC_EXIT48]], label [[ATOMIC_CMP45]]
// CHK-C:       atomic_cmp45:
// CHK-C-NEXT:    store i32 [[TMP36]], i32* [[ATMP39]], align 4
// CHK-C-NEXT:    [[CMP46:%.*]] = icmp slt i32 [[TMP36]], [[TMP32]]
// CHK-C-NEXT:    [[FROMBOOL47:%.*]] = zext i1 [[CMP46]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL47]], i8* [[ATMP41]], align 1
// CHK-C-NEXT:    br i1 [[CMP46]], label [[ATOMIC_CONT43]], label [[ATOMIC_EXIT48]]
// CHK-C:       atomic_exit48:
// CHK-C-NEXT:    [[TMP38:%.*]] = load i32, i32* [[ATMP39]], align 4
// CHK-C-NEXT:    [[TMP39:%.*]] = load i8, i8* [[ATMP41]], align 1
// CHK-C-NEXT:    store i32 [[TMP38]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP40:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD49:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD49]], i32* [[ATMP50]], align 4
// CHK-C-NEXT:    [[CMP51:%.*]] = icmp slt i32 [[ATOMIC_LOAD49]], [[TMP40]]
// CHK-C-NEXT:    [[FROMBOOL53:%.*]] = zext i1 [[CMP51]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL53]], i8* [[ATMP52]], align 1
// CHK-C-NEXT:    br i1 [[CMP51]], label [[ATOMIC_CONT54:%.*]], label [[ATOMIC_EXIT60:%.*]]
// CHK-C:       atomic_cont54:
// CHK-C-NEXT:    [[TMP41:%.*]] = phi i32 [ [[ATOMIC_LOAD49]], [[ATOMIC_EXIT48]] ], [ [[TMP44:%.*]], [[ATOMIC_CMP57:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP40]], i32* [[ATOMIC_TEMP55]], align 4
// CHK-C-NEXT:    [[TMP42:%.*]] = load i32, i32* [[ATOMIC_TEMP55]], align 4
// CHK-C-NEXT:    [[TMP43:%.*]] = cmpxchg i32* [[X]], i32 [[TMP41]], i32 [[TMP42]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP44]] = extractvalue { i32, i1 } [[TMP43]], 0
// CHK-C-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i1 } [[TMP43]], 1
// CHK-C-NEXT:    br i1 [[TMP45]], label [[ATOMIC_UPD_EXIT56:%.*]], label [[ATOMIC_CMP57]]
// CHK-C:       atomic_upd_exit56:
// CHK-C-NEXT:    store i32 [[TMP40]], i32* [[ATMP50]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT60]]
// CHK-C:       atomic_cmp57:
// CHK-C-NEXT:    store i32 [[TMP44]], i32* [[ATMP50]], align 4
// CHK-C-NEXT:    [[CMP58:%.*]] = icmp slt i32 [[TMP44]], [[TMP40]]
// CHK-C-NEXT:    [[FROMBOOL59:%.*]] = zext i1 [[CMP58]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL59]], i8* [[ATMP52]], align 1
// CHK-C-NEXT:    br i1 [[CMP58]], label [[ATOMIC_CONT54]], label [[ATOMIC_EXIT60]]
// CHK-C:       atomic_exit60:
// CHK-C-NEXT:    [[TMP46:%.*]] = load i32, i32* [[ATMP50]], align 4
// CHK-C-NEXT:    [[TMP47:%.*]] = load i8, i8* [[ATMP52]], align 1
// CHK-C-NEXT:    store i32 [[TMP46]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP48:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD61:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD61]], i32* [[ATMP62]], align 4
// CHK-C-NEXT:    [[CMP63:%.*]] = icmp sgt i32 [[ATOMIC_LOAD61]], [[TMP48]]
// CHK-C-NEXT:    [[FROMBOOL65:%.*]] = zext i1 [[CMP63]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL65]], i8* [[ATMP64]], align 1
// CHK-C-NEXT:    br i1 [[CMP63]], label [[ATOMIC_CONT66:%.*]], label [[ATOMIC_EXIT71:%.*]]
// CHK-C:       atomic_cont66:
// CHK-C-NEXT:    [[TMP49:%.*]] = phi i32 [ [[ATOMIC_LOAD61]], [[ATOMIC_EXIT60]] ], [ [[TMP52:%.*]], [[ATOMIC_CMP68:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP48]], i32* [[ATOMIC_TEMP67]], align 4
// CHK-C-NEXT:    [[TMP50:%.*]] = load i32, i32* [[ATOMIC_TEMP67]], align 4
// CHK-C-NEXT:    [[TMP51:%.*]] = cmpxchg i32* [[X]], i32 [[TMP49]], i32 [[TMP50]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP52]] = extractvalue { i32, i1 } [[TMP51]], 0
// CHK-C-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i1 } [[TMP51]], 1
// CHK-C-NEXT:    br i1 [[TMP53]], label [[ATOMIC_EXIT71]], label [[ATOMIC_CMP68]]
// CHK-C:       atomic_cmp68:
// CHK-C-NEXT:    store i32 [[TMP52]], i32* [[ATMP62]], align 4
// CHK-C-NEXT:    [[CMP69:%.*]] = icmp sgt i32 [[TMP52]], [[TMP48]]
// CHK-C-NEXT:    [[FROMBOOL70:%.*]] = zext i1 [[CMP69]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL70]], i8* [[ATMP64]], align 1
// CHK-C-NEXT:    br i1 [[CMP69]], label [[ATOMIC_CONT66]], label [[ATOMIC_EXIT71]]
// CHK-C:       atomic_exit71:
// CHK-C-NEXT:    [[TMP54:%.*]] = load i32, i32* [[ATMP62]], align 4
// CHK-C-NEXT:    [[TMP55:%.*]] = load i8, i8* [[ATMP64]], align 1
// CHK-C-NEXT:    store i32 [[TMP54]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP56:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD72:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD72]], i32* [[ATMP73]], align 4
// CHK-C-NEXT:    [[CMP74:%.*]] = icmp sgt i32 [[ATOMIC_LOAD72]], [[TMP56]]
// CHK-C-NEXT:    [[FROMBOOL76:%.*]] = zext i1 [[CMP74]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL76]], i8* [[ATMP75]], align 1
// CHK-C-NEXT:    br i1 [[CMP74]], label [[ATOMIC_CONT77:%.*]], label [[ATOMIC_EXIT83:%.*]]
// CHK-C:       atomic_cont77:
// CHK-C-NEXT:    [[TMP57:%.*]] = phi i32 [ [[ATOMIC_LOAD72]], [[ATOMIC_EXIT71]] ], [ [[TMP60:%.*]], [[ATOMIC_CMP80:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP56]], i32* [[ATOMIC_TEMP78]], align 4
// CHK-C-NEXT:    [[TMP58:%.*]] = load i32, i32* [[ATOMIC_TEMP78]], align 4
// CHK-C-NEXT:    [[TMP59:%.*]] = cmpxchg i32* [[X]], i32 [[TMP57]], i32 [[TMP58]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP60]] = extractvalue { i32, i1 } [[TMP59]], 0
// CHK-C-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i1 } [[TMP59]], 1
// CHK-C-NEXT:    br i1 [[TMP61]], label [[ATOMIC_UPD_EXIT79:%.*]], label [[ATOMIC_CMP80]]
// CHK-C:       atomic_upd_exit79:
// CHK-C-NEXT:    store i32 [[TMP56]], i32* [[ATMP73]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT83]]
// CHK-C:       atomic_cmp80:
// CHK-C-NEXT:    store i32 [[TMP60]], i32* [[ATMP73]], align 4
// CHK-C-NEXT:    [[CMP81:%.*]] = icmp sgt i32 [[TMP60]], [[TMP56]]
// CHK-C-NEXT:    [[FROMBOOL82:%.*]] = zext i1 [[CMP81]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL82]], i8* [[ATMP75]], align 1
// CHK-C-NEXT:    br i1 [[CMP81]], label [[ATOMIC_CONT77]], label [[ATOMIC_EXIT83]]
// CHK-C:       atomic_exit83:
// CHK-C-NEXT:    [[TMP62:%.*]] = load i32, i32* [[ATMP73]], align 4
// CHK-C-NEXT:    [[TMP63:%.*]] = load i8, i8* [[ATMP75]], align 1
// CHK-C-NEXT:    store i32 [[TMP62]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP64:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP65:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD84:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD84]], i32* [[ATMP85]], align 4
// CHK-C-NEXT:    [[CMP86:%.*]] = icmp eq i32 [[ATOMIC_LOAD84]], [[TMP65]]
// CHK-C-NEXT:    [[FROMBOOL88:%.*]] = zext i1 [[CMP86]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL88]], i8* [[ATMP87]], align 1
// CHK-C-NEXT:    br i1 [[CMP86]], label [[ATOMIC_CONT89:%.*]], label [[ATOMIC_EXIT94:%.*]]
// CHK-C:       atomic_cont89:
// CHK-C-NEXT:    [[TMP66:%.*]] = phi i32 [ [[ATOMIC_LOAD84]], [[ATOMIC_EXIT83]] ], [ [[TMP69:%.*]], [[ATOMIC_CMP91:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP64]], i32* [[ATOMIC_TEMP90]], align 4
// CHK-C-NEXT:    [[TMP67:%.*]] = load i32, i32* [[ATOMIC_TEMP90]], align 4
// CHK-C-NEXT:    [[TMP68:%.*]] = cmpxchg i32* [[X]], i32 [[TMP66]], i32 [[TMP67]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP69]] = extractvalue { i32, i1 } [[TMP68]], 0
// CHK-C-NEXT:    [[TMP70:%.*]] = extractvalue { i32, i1 } [[TMP68]], 1
// CHK-C-NEXT:    br i1 [[TMP70]], label [[ATOMIC_EXIT94]], label [[ATOMIC_CMP91]]
// CHK-C:       atomic_cmp91:
// CHK-C-NEXT:    store i32 [[TMP69]], i32* [[ATMP85]], align 4
// CHK-C-NEXT:    [[CMP92:%.*]] = icmp eq i32 [[TMP69]], [[TMP65]]
// CHK-C-NEXT:    [[FROMBOOL93:%.*]] = zext i1 [[CMP92]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL93]], i8* [[ATMP87]], align 1
// CHK-C-NEXT:    br i1 [[CMP92]], label [[ATOMIC_CONT89]], label [[ATOMIC_EXIT94]]
// CHK-C:       atomic_exit94:
// CHK-C-NEXT:    [[TMP71:%.*]] = load i32, i32* [[ATMP85]], align 4
// CHK-C-NEXT:    [[TMP72:%.*]] = load i8, i8* [[ATMP87]], align 1
// CHK-C-NEXT:    store i32 [[TMP71]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP73:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP74:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD95:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD95]], i32* [[ATMP96]], align 4
// CHK-C-NEXT:    [[CMP97:%.*]] = icmp eq i32 [[ATOMIC_LOAD95]], [[TMP74]]
// CHK-C-NEXT:    [[FROMBOOL99:%.*]] = zext i1 [[CMP97]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL99]], i8* [[ATMP98]], align 1
// CHK-C-NEXT:    br i1 [[CMP97]], label [[ATOMIC_CONT100:%.*]], label [[ATOMIC_EXIT106:%.*]]
// CHK-C:       atomic_cont100:
// CHK-C-NEXT:    [[TMP75:%.*]] = phi i32 [ [[ATOMIC_LOAD95]], [[ATOMIC_EXIT94]] ], [ [[TMP78:%.*]], [[ATOMIC_CMP103:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP73]], i32* [[ATOMIC_TEMP101]], align 4
// CHK-C-NEXT:    [[TMP76:%.*]] = load i32, i32* [[ATOMIC_TEMP101]], align 4
// CHK-C-NEXT:    [[TMP77:%.*]] = cmpxchg i32* [[X]], i32 [[TMP75]], i32 [[TMP76]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP78]] = extractvalue { i32, i1 } [[TMP77]], 0
// CHK-C-NEXT:    [[TMP79:%.*]] = extractvalue { i32, i1 } [[TMP77]], 1
// CHK-C-NEXT:    br i1 [[TMP79]], label [[ATOMIC_UPD_EXIT102:%.*]], label [[ATOMIC_CMP103]]
// CHK-C:       atomic_upd_exit102:
// CHK-C-NEXT:    store i32 [[TMP73]], i32* [[ATMP96]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT106]]
// CHK-C:       atomic_cmp103:
// CHK-C-NEXT:    store i32 [[TMP78]], i32* [[ATMP96]], align 4
// CHK-C-NEXT:    [[CMP104:%.*]] = icmp eq i32 [[TMP78]], [[TMP74]]
// CHK-C-NEXT:    [[FROMBOOL105:%.*]] = zext i1 [[CMP104]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL105]], i8* [[ATMP98]], align 1
// CHK-C-NEXT:    br i1 [[CMP104]], label [[ATOMIC_CONT100]], label [[ATOMIC_EXIT106]]
// CHK-C:       atomic_exit106:
// CHK-C-NEXT:    [[TMP80:%.*]] = load i32, i32* [[ATMP96]], align 4
// CHK-C-NEXT:    [[TMP81:%.*]] = load i8, i8* [[ATMP98]], align 1
// CHK-C-NEXT:    store i32 [[TMP80]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP82:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP83:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD107:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD107]], i32* [[ATMP108]], align 4
// CHK-C-NEXT:    [[CMP109:%.*]] = icmp eq i32 [[ATOMIC_LOAD107]], [[TMP83]]
// CHK-C-NEXT:    [[FROMBOOL111:%.*]] = zext i1 [[CMP109]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL111]], i8* [[ATMP110]], align 1
// CHK-C-NEXT:    br i1 [[CMP109]], label [[ATOMIC_CONT112:%.*]], label [[ATOMIC_EXIT118:%.*]]
// CHK-C:       atomic_cont112:
// CHK-C-NEXT:    [[TMP84:%.*]] = phi i32 [ [[ATOMIC_LOAD107]], [[ATOMIC_EXIT106]] ], [ [[TMP87:%.*]], [[ATOMIC_CMP115:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP82]], i32* [[ATOMIC_TEMP113]], align 4
// CHK-C-NEXT:    [[TMP85:%.*]] = load i32, i32* [[ATOMIC_TEMP113]], align 4
// CHK-C-NEXT:    [[TMP86:%.*]] = cmpxchg i32* [[X]], i32 [[TMP84]], i32 [[TMP85]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP87]] = extractvalue { i32, i1 } [[TMP86]], 0
// CHK-C-NEXT:    [[TMP88:%.*]] = extractvalue { i32, i1 } [[TMP86]], 1
// CHK-C-NEXT:    br i1 [[TMP88]], label [[ATOMIC_UPD_EXIT114:%.*]], label [[ATOMIC_CMP115]]
// CHK-C:       atomic_upd_exit114:
// CHK-C-NEXT:    store i32 [[TMP82]], i32* [[ATMP108]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT118]]
// CHK-C:       atomic_cmp115:
// CHK-C-NEXT:    store i32 [[TMP87]], i32* [[ATMP108]], align 4
// CHK-C-NEXT:    [[CMP116:%.*]] = icmp eq i32 [[TMP87]], [[TMP83]]
// CHK-C-NEXT:    [[FROMBOOL117:%.*]] = zext i1 [[CMP116]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL117]], i8* [[ATMP110]], align 1
// CHK-C-NEXT:    br i1 [[CMP116]], label [[ATOMIC_CONT112]], label [[ATOMIC_EXIT118]]
// CHK-C:       atomic_exit118:
// CHK-C-NEXT:    [[TMP89:%.*]] = load i32, i32* [[ATMP108]], align 4
// CHK-C-NEXT:    [[TMP90:%.*]] = load i8, i8* [[ATMP110]], align 1
// CHK-C-NEXT:    [[TMP91:%.*]] = trunc i8 [[TMP90]] to i1
// CHK-C-NEXT:    br i1 [[TMP91]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-C:       atomic_capture:
// CHK-C-NEXT:    store i32 [[TMP89]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-C:       atomic_capture_cont:
// CHK-C-NEXT:    [[TMP92:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP93:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD119:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD119]], i32* [[ATMP120]], align 4
// CHK-C-NEXT:    [[CMP121:%.*]] = icmp eq i32 [[ATOMIC_LOAD119]], [[TMP93]]
// CHK-C-NEXT:    [[FROMBOOL123:%.*]] = zext i1 [[CMP121]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL123]], i8* [[ATMP122]], align 1
// CHK-C-NEXT:    br i1 [[CMP121]], label [[ATOMIC_CONT124:%.*]], label [[ATOMIC_EXIT129:%.*]]
// CHK-C:       atomic_cont124:
// CHK-C-NEXT:    [[TMP94:%.*]] = phi i32 [ [[ATOMIC_LOAD119]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP97:%.*]], [[ATOMIC_CMP126:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP92]], i32* [[ATOMIC_TEMP125]], align 4
// CHK-C-NEXT:    [[TMP95:%.*]] = load i32, i32* [[ATOMIC_TEMP125]], align 4
// CHK-C-NEXT:    [[TMP96:%.*]] = cmpxchg i32* [[X]], i32 [[TMP94]], i32 [[TMP95]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP97]] = extractvalue { i32, i1 } [[TMP96]], 0
// CHK-C-NEXT:    [[TMP98:%.*]] = extractvalue { i32, i1 } [[TMP96]], 1
// CHK-C-NEXT:    br i1 [[TMP98]], label [[ATOMIC_EXIT129]], label [[ATOMIC_CMP126]]
// CHK-C:       atomic_cmp126:
// CHK-C-NEXT:    store i32 [[TMP97]], i32* [[ATMP120]], align 4
// CHK-C-NEXT:    [[CMP127:%.*]] = icmp eq i32 [[TMP97]], [[TMP93]]
// CHK-C-NEXT:    [[FROMBOOL128:%.*]] = zext i1 [[CMP127]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL128]], i8* [[ATMP122]], align 1
// CHK-C-NEXT:    br i1 [[CMP127]], label [[ATOMIC_CONT124]], label [[ATOMIC_EXIT129]]
// CHK-C:       atomic_exit129:
// CHK-C-NEXT:    [[TMP99:%.*]] = load i32, i32* [[ATMP120]], align 4
// CHK-C-NEXT:    [[TMP100:%.*]] = load i8, i8* [[ATMP122]], align 1
// CHK-C-NEXT:    store i8 [[TMP100]], i8* [[R]], align 1
// CHK-C-NEXT:    [[TMP101:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP102:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD130:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD130]], i32* [[ATMP131]], align 4
// CHK-C-NEXT:    [[CMP132:%.*]] = icmp eq i32 [[ATOMIC_LOAD130]], [[TMP102]]
// CHK-C-NEXT:    [[FROMBOOL134:%.*]] = zext i1 [[CMP132]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL134]], i8* [[ATMP133]], align 1
// CHK-C-NEXT:    br i1 [[CMP132]], label [[ATOMIC_CONT135:%.*]], label [[ATOMIC_EXIT140:%.*]]
// CHK-C:       atomic_cont135:
// CHK-C-NEXT:    [[TMP103:%.*]] = phi i32 [ [[ATOMIC_LOAD130]], [[ATOMIC_EXIT129]] ], [ [[TMP106:%.*]], [[ATOMIC_CMP137:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP101]], i32* [[ATOMIC_TEMP136]], align 4
// CHK-C-NEXT:    [[TMP104:%.*]] = load i32, i32* [[ATOMIC_TEMP136]], align 4
// CHK-C-NEXT:    [[TMP105:%.*]] = cmpxchg i32* [[X]], i32 [[TMP103]], i32 [[TMP104]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP106]] = extractvalue { i32, i1 } [[TMP105]], 0
// CHK-C-NEXT:    [[TMP107:%.*]] = extractvalue { i32, i1 } [[TMP105]], 1
// CHK-C-NEXT:    br i1 [[TMP107]], label [[ATOMIC_EXIT140]], label [[ATOMIC_CMP137]]
// CHK-C:       atomic_cmp137:
// CHK-C-NEXT:    store i32 [[TMP106]], i32* [[ATMP131]], align 4
// CHK-C-NEXT:    [[CMP138:%.*]] = icmp eq i32 [[TMP106]], [[TMP102]]
// CHK-C-NEXT:    [[FROMBOOL139:%.*]] = zext i1 [[CMP138]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL139]], i8* [[ATMP133]], align 1
// CHK-C-NEXT:    br i1 [[CMP138]], label [[ATOMIC_CONT135]], label [[ATOMIC_EXIT140]]
// CHK-C:       atomic_exit140:
// CHK-C-NEXT:    [[TMP108:%.*]] = load i32, i32* [[ATMP131]], align 4
// CHK-C-NEXT:    [[TMP109:%.*]] = load i8, i8* [[ATMP133]], align 1
// CHK-C-NEXT:    store i8 [[TMP109]], i8* [[R]], align 1
// CHK-C-NEXT:    [[TMP110:%.*]] = trunc i8 [[TMP109]] to i1
// CHK-C-NEXT:    br i1 [[TMP110]], label [[ATOMIC_CAPTURE_CONT142:%.*]], label [[ATOMIC_CAPTURE141:%.*]]
// CHK-C:       atomic_capture141:
// CHK-C-NEXT:    store i32 [[TMP108]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT142]]
// CHK-C:       atomic_capture_cont142:
// CHK-C-NEXT:    ret void
//
// CHK-CXX-LABEL: @_Z8test_intv(
// CHK-CXX-NEXT:  entry:
// CHK-CXX-NEXT:    [[X:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[EXPR:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[D:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[E:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[V:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[R:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[TMP:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP5:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP7:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP10:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP16:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP18:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP21:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP27:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP29:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP32:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP39:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP41:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP44:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP50:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP52:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP55:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP62:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP64:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP67:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP73:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP75:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP78:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP85:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP87:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP90:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP96:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP98:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP101:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP108:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP110:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP113:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP120:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP122:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP125:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP131:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP133:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP136:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[TMP0:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD]], i32* [[TMP]], align 4
// CHK-CXX-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[ATOMIC_LOAD]], [[TMP0]]
// CHK-CXX-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-CXX:       atomic_cont:
// CHK-CXX-NEXT:    [[TMP1:%.*]] = phi i32 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP4:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP0]], i32* [[ATOMIC_TEMP]], align 4
// CHK-CXX-NEXT:    [[TMP2:%.*]] = load i32, i32* [[ATOMIC_TEMP]], align 4
// CHK-CXX-NEXT:    [[TMP3:%.*]] = cmpxchg i32* [[X]], i32 [[TMP1]], i32 [[TMP2]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP4]] = extractvalue { i32, i1 } [[TMP3]], 0
// CHK-CXX-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i1 } [[TMP3]], 1
// CHK-CXX-NEXT:    br i1 [[TMP5]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-CXX:       atomic_cmp:
// CHK-CXX-NEXT:    store i32 [[TMP4]], i32* [[TMP]], align 4
// CHK-CXX-NEXT:    [[CMP2:%.*]] = icmp sgt i32 [[TMP4]], [[TMP0]]
// CHK-CXX-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[CMP2]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL3]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP2]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-CXX:       atomic_exit:
// CHK-CXX-NEXT:    [[TMP6:%.*]] = load i32, i32* [[TMP]], align 4
// CHK-CXX-NEXT:    [[TMP7:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP6]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP8:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD4:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD4]], i32* [[ATMP5]], align 4
// CHK-CXX-NEXT:    [[CMP6:%.*]] = icmp sgt i32 [[ATOMIC_LOAD4]], [[TMP8]]
// CHK-CXX-NEXT:    [[FROMBOOL8:%.*]] = zext i1 [[CMP6]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL8]], i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP6]], label [[ATOMIC_CONT9:%.*]], label [[ATOMIC_EXIT14:%.*]]
// CHK-CXX:       atomic_cont9:
// CHK-CXX-NEXT:    [[TMP9:%.*]] = phi i32 [ [[ATOMIC_LOAD4]], [[ATOMIC_EXIT]] ], [ [[TMP12:%.*]], [[ATOMIC_CMP11:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP8]], i32* [[ATOMIC_TEMP10]], align 4
// CHK-CXX-NEXT:    [[TMP10:%.*]] = load i32, i32* [[ATOMIC_TEMP10]], align 4
// CHK-CXX-NEXT:    [[TMP11:%.*]] = cmpxchg i32* [[X]], i32 [[TMP9]], i32 [[TMP10]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP12]] = extractvalue { i32, i1 } [[TMP11]], 0
// CHK-CXX-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i1 } [[TMP11]], 1
// CHK-CXX-NEXT:    br i1 [[TMP13]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP11]]
// CHK-CXX:       atomic_upd_exit:
// CHK-CXX-NEXT:    store i32 [[TMP8]], i32* [[ATMP5]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT14]]
// CHK-CXX:       atomic_cmp11:
// CHK-CXX-NEXT:    store i32 [[TMP12]], i32* [[ATMP5]], align 4
// CHK-CXX-NEXT:    [[CMP12:%.*]] = icmp sgt i32 [[TMP12]], [[TMP8]]
// CHK-CXX-NEXT:    [[FROMBOOL13:%.*]] = zext i1 [[CMP12]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL13]], i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP12]], label [[ATOMIC_CONT9]], label [[ATOMIC_EXIT14]]
// CHK-CXX:       atomic_exit14:
// CHK-CXX-NEXT:    [[TMP14:%.*]] = load i32, i32* [[ATMP5]], align 4
// CHK-CXX-NEXT:    [[TMP15:%.*]] = load i8, i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP14]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP16:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD15:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD15]], i32* [[ATMP16]], align 4
// CHK-CXX-NEXT:    [[CMP17:%.*]] = icmp slt i32 [[ATOMIC_LOAD15]], [[TMP16]]
// CHK-CXX-NEXT:    [[FROMBOOL19:%.*]] = zext i1 [[CMP17]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL19]], i8* [[ATMP18]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP17]], label [[ATOMIC_CONT20:%.*]], label [[ATOMIC_EXIT25:%.*]]
// CHK-CXX:       atomic_cont20:
// CHK-CXX-NEXT:    [[TMP17:%.*]] = phi i32 [ [[ATOMIC_LOAD15]], [[ATOMIC_EXIT14]] ], [ [[TMP20:%.*]], [[ATOMIC_CMP22:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP16]], i32* [[ATOMIC_TEMP21]], align 4
// CHK-CXX-NEXT:    [[TMP18:%.*]] = load i32, i32* [[ATOMIC_TEMP21]], align 4
// CHK-CXX-NEXT:    [[TMP19:%.*]] = cmpxchg i32* [[X]], i32 [[TMP17]], i32 [[TMP18]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP20]] = extractvalue { i32, i1 } [[TMP19]], 0
// CHK-CXX-NEXT:    [[TMP21:%.*]] = extractvalue { i32, i1 } [[TMP19]], 1
// CHK-CXX-NEXT:    br i1 [[TMP21]], label [[ATOMIC_EXIT25]], label [[ATOMIC_CMP22]]
// CHK-CXX:       atomic_cmp22:
// CHK-CXX-NEXT:    store i32 [[TMP20]], i32* [[ATMP16]], align 4
// CHK-CXX-NEXT:    [[CMP23:%.*]] = icmp slt i32 [[TMP20]], [[TMP16]]
// CHK-CXX-NEXT:    [[FROMBOOL24:%.*]] = zext i1 [[CMP23]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL24]], i8* [[ATMP18]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP23]], label [[ATOMIC_CONT20]], label [[ATOMIC_EXIT25]]
// CHK-CXX:       atomic_exit25:
// CHK-CXX-NEXT:    [[TMP22:%.*]] = load i32, i32* [[ATMP16]], align 4
// CHK-CXX-NEXT:    [[TMP23:%.*]] = load i8, i8* [[ATMP18]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP22]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP24:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD26:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD26]], i32* [[ATMP27]], align 4
// CHK-CXX-NEXT:    [[CMP28:%.*]] = icmp slt i32 [[ATOMIC_LOAD26]], [[TMP24]]
// CHK-CXX-NEXT:    [[FROMBOOL30:%.*]] = zext i1 [[CMP28]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL30]], i8* [[ATMP29]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP28]], label [[ATOMIC_CONT31:%.*]], label [[ATOMIC_EXIT37:%.*]]
// CHK-CXX:       atomic_cont31:
// CHK-CXX-NEXT:    [[TMP25:%.*]] = phi i32 [ [[ATOMIC_LOAD26]], [[ATOMIC_EXIT25]] ], [ [[TMP28:%.*]], [[ATOMIC_CMP34:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP24]], i32* [[ATOMIC_TEMP32]], align 4
// CHK-CXX-NEXT:    [[TMP26:%.*]] = load i32, i32* [[ATOMIC_TEMP32]], align 4
// CHK-CXX-NEXT:    [[TMP27:%.*]] = cmpxchg i32* [[X]], i32 [[TMP25]], i32 [[TMP26]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP28]] = extractvalue { i32, i1 } [[TMP27]], 0
// CHK-CXX-NEXT:    [[TMP29:%.*]] = extractvalue { i32, i1 } [[TMP27]], 1
// CHK-CXX-NEXT:    br i1 [[TMP29]], label [[ATOMIC_UPD_EXIT33:%.*]], label [[ATOMIC_CMP34]]
// CHK-CXX:       atomic_upd_exit33:
// CHK-CXX-NEXT:    store i32 [[TMP24]], i32* [[ATMP27]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT37]]
// CHK-CXX:       atomic_cmp34:
// CHK-CXX-NEXT:    store i32 [[TMP28]], i32* [[ATMP27]], align 4
// CHK-CXX-NEXT:    [[CMP35:%.*]] = icmp slt i32 [[TMP28]], [[TMP24]]
// CHK-CXX-NEXT:    [[FROMBOOL36:%.*]] = zext i1 [[CMP35]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL36]], i8* [[ATMP29]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP35]], label [[ATOMIC_CONT31]], label [[ATOMIC_EXIT37]]
// CHK-CXX:       atomic_exit37:
// CHK-CXX-NEXT:    [[TMP30:%.*]] = load i32, i32* [[ATMP27]], align 4
// CHK-CXX-NEXT:    [[TMP31:%.*]] = load i8, i8* [[ATMP29]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP30]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP32:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD38:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD38]], i32* [[ATMP39]], align 4
// CHK-CXX-NEXT:    [[CMP40:%.*]] = icmp slt i32 [[ATOMIC_LOAD38]], [[TMP32]]
// CHK-CXX-NEXT:    [[FROMBOOL42:%.*]] = zext i1 [[CMP40]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL42]], i8* [[ATMP41]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP40]], label [[ATOMIC_CONT43:%.*]], label [[ATOMIC_EXIT48:%.*]]
// CHK-CXX:       atomic_cont43:
// CHK-CXX-NEXT:    [[TMP33:%.*]] = phi i32 [ [[ATOMIC_LOAD38]], [[ATOMIC_EXIT37]] ], [ [[TMP36:%.*]], [[ATOMIC_CMP45:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP32]], i32* [[ATOMIC_TEMP44]], align 4
// CHK-CXX-NEXT:    [[TMP34:%.*]] = load i32, i32* [[ATOMIC_TEMP44]], align 4
// CHK-CXX-NEXT:    [[TMP35:%.*]] = cmpxchg i32* [[X]], i32 [[TMP33]], i32 [[TMP34]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP36]] = extractvalue { i32, i1 } [[TMP35]], 0
// CHK-CXX-NEXT:    [[TMP37:%.*]] = extractvalue { i32, i1 } [[TMP35]], 1
// CHK-CXX-NEXT:    br i1 [[TMP37]], label [[ATOMIC_EXIT48]], label [[ATOMIC_CMP45]]
// CHK-CXX:       atomic_cmp45:
// CHK-CXX-NEXT:    store i32 [[TMP36]], i32* [[ATMP39]], align 4
// CHK-CXX-NEXT:    [[CMP46:%.*]] = icmp slt i32 [[TMP36]], [[TMP32]]
// CHK-CXX-NEXT:    [[FROMBOOL47:%.*]] = zext i1 [[CMP46]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL47]], i8* [[ATMP41]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP46]], label [[ATOMIC_CONT43]], label [[ATOMIC_EXIT48]]
// CHK-CXX:       atomic_exit48:
// CHK-CXX-NEXT:    [[TMP38:%.*]] = load i32, i32* [[ATMP39]], align 4
// CHK-CXX-NEXT:    [[TMP39:%.*]] = load i8, i8* [[ATMP41]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP38]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP40:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD49:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD49]], i32* [[ATMP50]], align 4
// CHK-CXX-NEXT:    [[CMP51:%.*]] = icmp slt i32 [[ATOMIC_LOAD49]], [[TMP40]]
// CHK-CXX-NEXT:    [[FROMBOOL53:%.*]] = zext i1 [[CMP51]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL53]], i8* [[ATMP52]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP51]], label [[ATOMIC_CONT54:%.*]], label [[ATOMIC_EXIT60:%.*]]
// CHK-CXX:       atomic_cont54:
// CHK-CXX-NEXT:    [[TMP41:%.*]] = phi i32 [ [[ATOMIC_LOAD49]], [[ATOMIC_EXIT48]] ], [ [[TMP44:%.*]], [[ATOMIC_CMP57:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP40]], i32* [[ATOMIC_TEMP55]], align 4
// CHK-CXX-NEXT:    [[TMP42:%.*]] = load i32, i32* [[ATOMIC_TEMP55]], align 4
// CHK-CXX-NEXT:    [[TMP43:%.*]] = cmpxchg i32* [[X]], i32 [[TMP41]], i32 [[TMP42]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP44]] = extractvalue { i32, i1 } [[TMP43]], 0
// CHK-CXX-NEXT:    [[TMP45:%.*]] = extractvalue { i32, i1 } [[TMP43]], 1
// CHK-CXX-NEXT:    br i1 [[TMP45]], label [[ATOMIC_UPD_EXIT56:%.*]], label [[ATOMIC_CMP57]]
// CHK-CXX:       atomic_upd_exit56:
// CHK-CXX-NEXT:    store i32 [[TMP40]], i32* [[ATMP50]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT60]]
// CHK-CXX:       atomic_cmp57:
// CHK-CXX-NEXT:    store i32 [[TMP44]], i32* [[ATMP50]], align 4
// CHK-CXX-NEXT:    [[CMP58:%.*]] = icmp slt i32 [[TMP44]], [[TMP40]]
// CHK-CXX-NEXT:    [[FROMBOOL59:%.*]] = zext i1 [[CMP58]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL59]], i8* [[ATMP52]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP58]], label [[ATOMIC_CONT54]], label [[ATOMIC_EXIT60]]
// CHK-CXX:       atomic_exit60:
// CHK-CXX-NEXT:    [[TMP46:%.*]] = load i32, i32* [[ATMP50]], align 4
// CHK-CXX-NEXT:    [[TMP47:%.*]] = load i8, i8* [[ATMP52]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP46]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP48:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD61:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD61]], i32* [[ATMP62]], align 4
// CHK-CXX-NEXT:    [[CMP63:%.*]] = icmp sgt i32 [[ATOMIC_LOAD61]], [[TMP48]]
// CHK-CXX-NEXT:    [[FROMBOOL65:%.*]] = zext i1 [[CMP63]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL65]], i8* [[ATMP64]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP63]], label [[ATOMIC_CONT66:%.*]], label [[ATOMIC_EXIT71:%.*]]
// CHK-CXX:       atomic_cont66:
// CHK-CXX-NEXT:    [[TMP49:%.*]] = phi i32 [ [[ATOMIC_LOAD61]], [[ATOMIC_EXIT60]] ], [ [[TMP52:%.*]], [[ATOMIC_CMP68:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP48]], i32* [[ATOMIC_TEMP67]], align 4
// CHK-CXX-NEXT:    [[TMP50:%.*]] = load i32, i32* [[ATOMIC_TEMP67]], align 4
// CHK-CXX-NEXT:    [[TMP51:%.*]] = cmpxchg i32* [[X]], i32 [[TMP49]], i32 [[TMP50]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP52]] = extractvalue { i32, i1 } [[TMP51]], 0
// CHK-CXX-NEXT:    [[TMP53:%.*]] = extractvalue { i32, i1 } [[TMP51]], 1
// CHK-CXX-NEXT:    br i1 [[TMP53]], label [[ATOMIC_EXIT71]], label [[ATOMIC_CMP68]]
// CHK-CXX:       atomic_cmp68:
// CHK-CXX-NEXT:    store i32 [[TMP52]], i32* [[ATMP62]], align 4
// CHK-CXX-NEXT:    [[CMP69:%.*]] = icmp sgt i32 [[TMP52]], [[TMP48]]
// CHK-CXX-NEXT:    [[FROMBOOL70:%.*]] = zext i1 [[CMP69]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL70]], i8* [[ATMP64]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP69]], label [[ATOMIC_CONT66]], label [[ATOMIC_EXIT71]]
// CHK-CXX:       atomic_exit71:
// CHK-CXX-NEXT:    [[TMP54:%.*]] = load i32, i32* [[ATMP62]], align 4
// CHK-CXX-NEXT:    [[TMP55:%.*]] = load i8, i8* [[ATMP64]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP54]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP56:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD72:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD72]], i32* [[ATMP73]], align 4
// CHK-CXX-NEXT:    [[CMP74:%.*]] = icmp sgt i32 [[ATOMIC_LOAD72]], [[TMP56]]
// CHK-CXX-NEXT:    [[FROMBOOL76:%.*]] = zext i1 [[CMP74]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL76]], i8* [[ATMP75]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP74]], label [[ATOMIC_CONT77:%.*]], label [[ATOMIC_EXIT83:%.*]]
// CHK-CXX:       atomic_cont77:
// CHK-CXX-NEXT:    [[TMP57:%.*]] = phi i32 [ [[ATOMIC_LOAD72]], [[ATOMIC_EXIT71]] ], [ [[TMP60:%.*]], [[ATOMIC_CMP80:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP56]], i32* [[ATOMIC_TEMP78]], align 4
// CHK-CXX-NEXT:    [[TMP58:%.*]] = load i32, i32* [[ATOMIC_TEMP78]], align 4
// CHK-CXX-NEXT:    [[TMP59:%.*]] = cmpxchg i32* [[X]], i32 [[TMP57]], i32 [[TMP58]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP60]] = extractvalue { i32, i1 } [[TMP59]], 0
// CHK-CXX-NEXT:    [[TMP61:%.*]] = extractvalue { i32, i1 } [[TMP59]], 1
// CHK-CXX-NEXT:    br i1 [[TMP61]], label [[ATOMIC_UPD_EXIT79:%.*]], label [[ATOMIC_CMP80]]
// CHK-CXX:       atomic_upd_exit79:
// CHK-CXX-NEXT:    store i32 [[TMP56]], i32* [[ATMP73]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT83]]
// CHK-CXX:       atomic_cmp80:
// CHK-CXX-NEXT:    store i32 [[TMP60]], i32* [[ATMP73]], align 4
// CHK-CXX-NEXT:    [[CMP81:%.*]] = icmp sgt i32 [[TMP60]], [[TMP56]]
// CHK-CXX-NEXT:    [[FROMBOOL82:%.*]] = zext i1 [[CMP81]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL82]], i8* [[ATMP75]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP81]], label [[ATOMIC_CONT77]], label [[ATOMIC_EXIT83]]
// CHK-CXX:       atomic_exit83:
// CHK-CXX-NEXT:    [[TMP62:%.*]] = load i32, i32* [[ATMP73]], align 4
// CHK-CXX-NEXT:    [[TMP63:%.*]] = load i8, i8* [[ATMP75]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP62]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP64:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP65:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD84:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD84]], i32* [[ATMP85]], align 4
// CHK-CXX-NEXT:    [[CMP86:%.*]] = icmp eq i32 [[ATOMIC_LOAD84]], [[TMP65]]
// CHK-CXX-NEXT:    [[FROMBOOL88:%.*]] = zext i1 [[CMP86]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL88]], i8* [[ATMP87]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP86]], label [[ATOMIC_CONT89:%.*]], label [[ATOMIC_EXIT94:%.*]]
// CHK-CXX:       atomic_cont89:
// CHK-CXX-NEXT:    [[TMP66:%.*]] = phi i32 [ [[ATOMIC_LOAD84]], [[ATOMIC_EXIT83]] ], [ [[TMP69:%.*]], [[ATOMIC_CMP91:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP64]], i32* [[ATOMIC_TEMP90]], align 4
// CHK-CXX-NEXT:    [[TMP67:%.*]] = load i32, i32* [[ATOMIC_TEMP90]], align 4
// CHK-CXX-NEXT:    [[TMP68:%.*]] = cmpxchg i32* [[X]], i32 [[TMP66]], i32 [[TMP67]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP69]] = extractvalue { i32, i1 } [[TMP68]], 0
// CHK-CXX-NEXT:    [[TMP70:%.*]] = extractvalue { i32, i1 } [[TMP68]], 1
// CHK-CXX-NEXT:    br i1 [[TMP70]], label [[ATOMIC_EXIT94]], label [[ATOMIC_CMP91]]
// CHK-CXX:       atomic_cmp91:
// CHK-CXX-NEXT:    store i32 [[TMP69]], i32* [[ATMP85]], align 4
// CHK-CXX-NEXT:    [[CMP92:%.*]] = icmp eq i32 [[TMP69]], [[TMP65]]
// CHK-CXX-NEXT:    [[FROMBOOL93:%.*]] = zext i1 [[CMP92]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL93]], i8* [[ATMP87]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP92]], label [[ATOMIC_CONT89]], label [[ATOMIC_EXIT94]]
// CHK-CXX:       atomic_exit94:
// CHK-CXX-NEXT:    [[TMP71:%.*]] = load i32, i32* [[ATMP85]], align 4
// CHK-CXX-NEXT:    [[TMP72:%.*]] = load i8, i8* [[ATMP87]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP71]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP73:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP74:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD95:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD95]], i32* [[ATMP96]], align 4
// CHK-CXX-NEXT:    [[CMP97:%.*]] = icmp eq i32 [[ATOMIC_LOAD95]], [[TMP74]]
// CHK-CXX-NEXT:    [[FROMBOOL99:%.*]] = zext i1 [[CMP97]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL99]], i8* [[ATMP98]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP97]], label [[ATOMIC_CONT100:%.*]], label [[ATOMIC_EXIT106:%.*]]
// CHK-CXX:       atomic_cont100:
// CHK-CXX-NEXT:    [[TMP75:%.*]] = phi i32 [ [[ATOMIC_LOAD95]], [[ATOMIC_EXIT94]] ], [ [[TMP78:%.*]], [[ATOMIC_CMP103:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP73]], i32* [[ATOMIC_TEMP101]], align 4
// CHK-CXX-NEXT:    [[TMP76:%.*]] = load i32, i32* [[ATOMIC_TEMP101]], align 4
// CHK-CXX-NEXT:    [[TMP77:%.*]] = cmpxchg i32* [[X]], i32 [[TMP75]], i32 [[TMP76]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP78]] = extractvalue { i32, i1 } [[TMP77]], 0
// CHK-CXX-NEXT:    [[TMP79:%.*]] = extractvalue { i32, i1 } [[TMP77]], 1
// CHK-CXX-NEXT:    br i1 [[TMP79]], label [[ATOMIC_UPD_EXIT102:%.*]], label [[ATOMIC_CMP103]]
// CHK-CXX:       atomic_upd_exit102:
// CHK-CXX-NEXT:    store i32 [[TMP73]], i32* [[ATMP96]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT106]]
// CHK-CXX:       atomic_cmp103:
// CHK-CXX-NEXT:    store i32 [[TMP78]], i32* [[ATMP96]], align 4
// CHK-CXX-NEXT:    [[CMP104:%.*]] = icmp eq i32 [[TMP78]], [[TMP74]]
// CHK-CXX-NEXT:    [[FROMBOOL105:%.*]] = zext i1 [[CMP104]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL105]], i8* [[ATMP98]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP104]], label [[ATOMIC_CONT100]], label [[ATOMIC_EXIT106]]
// CHK-CXX:       atomic_exit106:
// CHK-CXX-NEXT:    [[TMP80:%.*]] = load i32, i32* [[ATMP96]], align 4
// CHK-CXX-NEXT:    [[TMP81:%.*]] = load i8, i8* [[ATMP98]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP80]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP82:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP83:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD107:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD107]], i32* [[ATMP108]], align 4
// CHK-CXX-NEXT:    [[CMP109:%.*]] = icmp eq i32 [[ATOMIC_LOAD107]], [[TMP83]]
// CHK-CXX-NEXT:    [[FROMBOOL111:%.*]] = zext i1 [[CMP109]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL111]], i8* [[ATMP110]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP109]], label [[ATOMIC_CONT112:%.*]], label [[ATOMIC_EXIT118:%.*]]
// CHK-CXX:       atomic_cont112:
// CHK-CXX-NEXT:    [[TMP84:%.*]] = phi i32 [ [[ATOMIC_LOAD107]], [[ATOMIC_EXIT106]] ], [ [[TMP87:%.*]], [[ATOMIC_CMP115:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP82]], i32* [[ATOMIC_TEMP113]], align 4
// CHK-CXX-NEXT:    [[TMP85:%.*]] = load i32, i32* [[ATOMIC_TEMP113]], align 4
// CHK-CXX-NEXT:    [[TMP86:%.*]] = cmpxchg i32* [[X]], i32 [[TMP84]], i32 [[TMP85]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP87]] = extractvalue { i32, i1 } [[TMP86]], 0
// CHK-CXX-NEXT:    [[TMP88:%.*]] = extractvalue { i32, i1 } [[TMP86]], 1
// CHK-CXX-NEXT:    br i1 [[TMP88]], label [[ATOMIC_UPD_EXIT114:%.*]], label [[ATOMIC_CMP115]]
// CHK-CXX:       atomic_upd_exit114:
// CHK-CXX-NEXT:    store i32 [[TMP82]], i32* [[ATMP108]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT118]]
// CHK-CXX:       atomic_cmp115:
// CHK-CXX-NEXT:    store i32 [[TMP87]], i32* [[ATMP108]], align 4
// CHK-CXX-NEXT:    [[CMP116:%.*]] = icmp eq i32 [[TMP87]], [[TMP83]]
// CHK-CXX-NEXT:    [[FROMBOOL117:%.*]] = zext i1 [[CMP116]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL117]], i8* [[ATMP110]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP116]], label [[ATOMIC_CONT112]], label [[ATOMIC_EXIT118]]
// CHK-CXX:       atomic_exit118:
// CHK-CXX-NEXT:    [[TMP89:%.*]] = load i32, i32* [[ATMP108]], align 4
// CHK-CXX-NEXT:    [[TMP90:%.*]] = load i8, i8* [[ATMP110]], align 1
// CHK-CXX-NEXT:    [[TMP91:%.*]] = trunc i8 [[TMP90]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP91]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-CXX:       atomic_capture:
// CHK-CXX-NEXT:    store i32 [[TMP89]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-CXX:       atomic_capture_cont:
// CHK-CXX-NEXT:    [[TMP92:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP93:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD119:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD119]], i32* [[ATMP120]], align 4
// CHK-CXX-NEXT:    [[CMP121:%.*]] = icmp eq i32 [[ATOMIC_LOAD119]], [[TMP93]]
// CHK-CXX-NEXT:    [[FROMBOOL123:%.*]] = zext i1 [[CMP121]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL123]], i8* [[ATMP122]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP121]], label [[ATOMIC_CONT124:%.*]], label [[ATOMIC_EXIT129:%.*]]
// CHK-CXX:       atomic_cont124:
// CHK-CXX-NEXT:    [[TMP94:%.*]] = phi i32 [ [[ATOMIC_LOAD119]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP97:%.*]], [[ATOMIC_CMP126:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP92]], i32* [[ATOMIC_TEMP125]], align 4
// CHK-CXX-NEXT:    [[TMP95:%.*]] = load i32, i32* [[ATOMIC_TEMP125]], align 4
// CHK-CXX-NEXT:    [[TMP96:%.*]] = cmpxchg i32* [[X]], i32 [[TMP94]], i32 [[TMP95]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP97]] = extractvalue { i32, i1 } [[TMP96]], 0
// CHK-CXX-NEXT:    [[TMP98:%.*]] = extractvalue { i32, i1 } [[TMP96]], 1
// CHK-CXX-NEXT:    br i1 [[TMP98]], label [[ATOMIC_EXIT129]], label [[ATOMIC_CMP126]]
// CHK-CXX:       atomic_cmp126:
// CHK-CXX-NEXT:    store i32 [[TMP97]], i32* [[ATMP120]], align 4
// CHK-CXX-NEXT:    [[CMP127:%.*]] = icmp eq i32 [[TMP97]], [[TMP93]]
// CHK-CXX-NEXT:    [[FROMBOOL128:%.*]] = zext i1 [[CMP127]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL128]], i8* [[ATMP122]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP127]], label [[ATOMIC_CONT124]], label [[ATOMIC_EXIT129]]
// CHK-CXX:       atomic_exit129:
// CHK-CXX-NEXT:    [[TMP99:%.*]] = load i32, i32* [[ATMP120]], align 4
// CHK-CXX-NEXT:    [[TMP100:%.*]] = load i8, i8* [[ATMP122]], align 1
// CHK-CXX-NEXT:    store i8 [[TMP100]], i8* [[R]], align 1
// CHK-CXX-NEXT:    [[TMP101:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP102:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD130:%.*]] = load atomic i32, i32* [[X]] monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD130]], i32* [[ATMP131]], align 4
// CHK-CXX-NEXT:    [[CMP132:%.*]] = icmp eq i32 [[ATOMIC_LOAD130]], [[TMP102]]
// CHK-CXX-NEXT:    [[FROMBOOL134:%.*]] = zext i1 [[CMP132]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL134]], i8* [[ATMP133]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP132]], label [[ATOMIC_CONT135:%.*]], label [[ATOMIC_EXIT140:%.*]]
// CHK-CXX:       atomic_cont135:
// CHK-CXX-NEXT:    [[TMP103:%.*]] = phi i32 [ [[ATOMIC_LOAD130]], [[ATOMIC_EXIT129]] ], [ [[TMP106:%.*]], [[ATOMIC_CMP137:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP101]], i32* [[ATOMIC_TEMP136]], align 4
// CHK-CXX-NEXT:    [[TMP104:%.*]] = load i32, i32* [[ATOMIC_TEMP136]], align 4
// CHK-CXX-NEXT:    [[TMP105:%.*]] = cmpxchg i32* [[X]], i32 [[TMP103]], i32 [[TMP104]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP106]] = extractvalue { i32, i1 } [[TMP105]], 0
// CHK-CXX-NEXT:    [[TMP107:%.*]] = extractvalue { i32, i1 } [[TMP105]], 1
// CHK-CXX-NEXT:    br i1 [[TMP107]], label [[ATOMIC_EXIT140]], label [[ATOMIC_CMP137]]
// CHK-CXX:       atomic_cmp137:
// CHK-CXX-NEXT:    store i32 [[TMP106]], i32* [[ATMP131]], align 4
// CHK-CXX-NEXT:    [[CMP138:%.*]] = icmp eq i32 [[TMP106]], [[TMP102]]
// CHK-CXX-NEXT:    [[FROMBOOL139:%.*]] = zext i1 [[CMP138]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL139]], i8* [[ATMP133]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP138]], label [[ATOMIC_CONT135]], label [[ATOMIC_EXIT140]]
// CHK-CXX:       atomic_exit140:
// CHK-CXX-NEXT:    [[TMP108:%.*]] = load i32, i32* [[ATMP131]], align 4
// CHK-CXX-NEXT:    [[TMP109:%.*]] = load i8, i8* [[ATMP133]], align 1
// CHK-CXX-NEXT:    store i8 [[TMP109]], i8* [[R]], align 1
// CHK-CXX-NEXT:    [[TMP110:%.*]] = trunc i8 [[TMP109]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP110]], label [[ATOMIC_CAPTURE_CONT142:%.*]], label [[ATOMIC_CAPTURE141:%.*]]
// CHK-CXX:       atomic_capture141:
// CHK-CXX-NEXT:    store i32 [[TMP108]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT142]]
// CHK-CXX:       atomic_capture_cont142:
// CHK-CXX-NEXT:    ret void
//
void test_int() {
  // One of each form with 'int'.
  int x, expr, d, e, v;
#ifdef __cplusplus
  bool r;
#else
  _Bool r;
#endif

  #pragma omp atomic compare capture
  { v = x; if (expr < x) { x = expr; } } // MIN

  #pragma omp atomic compare capture
  { if (expr < x) { x = expr; } v = x; } // MIN

  #pragma omp atomic compare capture
  { v = x; if (expr > x) { x = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (expr > x) { x = expr; } v = x; } // MAX

  #pragma omp atomic compare capture
  { v = x; if (x < expr) { x = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (x < expr) { x = expr; } v = x; } // MAX

  #pragma omp atomic compare capture
  { v = x; if (x > expr) { x = expr; } } // MIN

  #pragma omp atomic compare capture
  { if (x > expr) { x = expr; } v = x; } // MIN

  #pragma omp atomic compare capture
  { v = x; if (x == e) { x = d; } }

  #pragma omp atomic compare capture
  { if (x == e) { x = d; } v = x; }

  #pragma omp atomic compare capture
  if (x == e) { x = d; } else { v = x; }

  #pragma omp atomic compare capture
  { r = x == e; if(r) { x = d; } }

  #pragma omp atomic compare capture
  { r = x == e; if(r) { x = d; } else { v = x; } }
}

// CHK-C-LABEL: @test_unsigned_short(
// CHK-C-NEXT:  entry:
// CHK-C-NEXT:    [[X:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[EXPR:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[D:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[E:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[V:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[R:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[TMP:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP5:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP7:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP10:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP16:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP18:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP21:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP27:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP29:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP32:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP39:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP41:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP44:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP50:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP52:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP55:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP62:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP64:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP67:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP73:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP75:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP78:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP85:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP87:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP90:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP96:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP98:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP101:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP108:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP110:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP113:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP120:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP122:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP125:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP131:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[ATMP133:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP136:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[TMP0:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-C-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-C-NEXT:    store i16 [[ATOMIC_LOAD]], i16* [[TMP]], align 2
// CHK-C-NEXT:    [[CMP:%.*]] = icmp ugt i16 [[ATOMIC_LOAD]], [[TMP0]]
// CHK-C-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-C:       atomic_cont:
// CHK-C-NEXT:    [[TMP1:%.*]] = phi i16 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP4:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-C-NEXT:    store i16 [[TMP0]], i16* [[ATOMIC_TEMP]], align 2
// CHK-C-NEXT:    [[TMP2:%.*]] = load i16, i16* [[ATOMIC_TEMP]], align 2
// CHK-C-NEXT:    [[TMP3:%.*]] = cmpxchg i16* [[X]], i16 [[TMP1]], i16 [[TMP2]] monotonic monotonic, align 2
// CHK-C-NEXT:    [[TMP4]] = extractvalue { i16, i1 } [[TMP3]], 0
// CHK-C-NEXT:    [[TMP5:%.*]] = extractvalue { i16, i1 } [[TMP3]], 1
// CHK-C-NEXT:    br i1 [[TMP5]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-C:       atomic_cmp:
// CHK-C-NEXT:    store i16 [[TMP4]], i16* [[TMP]], align 2
// CHK-C-NEXT:    [[CMP2:%.*]] = icmp ugt i16 [[TMP4]], [[TMP0]]
// CHK-C-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[CMP2]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL3]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP2]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-C:       atomic_exit:
// CHK-C-NEXT:    [[TMP6:%.*]] = load i16, i16* [[TMP]], align 2
// CHK-C-NEXT:    [[TMP7:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-C-NEXT:    store i16 [[TMP6]], i16* [[V]], align 2
// CHK-C-NEXT:    [[TMP8:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-C-NEXT:    [[ATOMIC_LOAD4:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-C-NEXT:    store i16 [[ATOMIC_LOAD4]], i16* [[ATMP5]], align 2
// CHK-C-NEXT:    [[CMP6:%.*]] = icmp ugt i16 [[ATOMIC_LOAD4]], [[TMP8]]
// CHK-C-NEXT:    [[FROMBOOL8:%.*]] = zext i1 [[CMP6]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL8]], i8* [[ATMP7]], align 1
// CHK-C-NEXT:    br i1 [[CMP6]], label [[ATOMIC_CONT9:%.*]], label [[ATOMIC_EXIT14:%.*]]
// CHK-C:       atomic_cont9:
// CHK-C-NEXT:    [[TMP9:%.*]] = phi i16 [ [[ATOMIC_LOAD4]], [[ATOMIC_EXIT]] ], [ [[TMP12:%.*]], [[ATOMIC_CMP11:%.*]] ]
// CHK-C-NEXT:    store i16 [[TMP8]], i16* [[ATOMIC_TEMP10]], align 2
// CHK-C-NEXT:    [[TMP10:%.*]] = load i16, i16* [[ATOMIC_TEMP10]], align 2
// CHK-C-NEXT:    [[TMP11:%.*]] = cmpxchg i16* [[X]], i16 [[TMP9]], i16 [[TMP10]] monotonic monotonic, align 2
// CHK-C-NEXT:    [[TMP12]] = extractvalue { i16, i1 } [[TMP11]], 0
// CHK-C-NEXT:    [[TMP13:%.*]] = extractvalue { i16, i1 } [[TMP11]], 1
// CHK-C-NEXT:    br i1 [[TMP13]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP11]]
// CHK-C:       atomic_upd_exit:
// CHK-C-NEXT:    store i16 [[TMP8]], i16* [[ATMP5]], align 2
// CHK-C-NEXT:    br label [[ATOMIC_EXIT14]]
// CHK-C:       atomic_cmp11:
// CHK-C-NEXT:    store i16 [[TMP12]], i16* [[ATMP5]], align 2
// CHK-C-NEXT:    [[CMP12:%.*]] = icmp ugt i16 [[TMP12]], [[TMP8]]
// CHK-C-NEXT:    [[FROMBOOL13:%.*]] = zext i1 [[CMP12]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL13]], i8* [[ATMP7]], align 1
// CHK-C-NEXT:    br i1 [[CMP12]], label [[ATOMIC_CONT9]], label [[ATOMIC_EXIT14]]
// CHK-C:       atomic_exit14:
// CHK-C-NEXT:    [[TMP14:%.*]] = load i16, i16* [[ATMP5]], align 2
// CHK-C-NEXT:    [[TMP15:%.*]] = load i8, i8* [[ATMP7]], align 1
// CHK-C-NEXT:    store i16 [[TMP14]], i16* [[V]], align 2
// CHK-C-NEXT:    [[TMP16:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-C-NEXT:    [[ATOMIC_LOAD15:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-C-NEXT:    store i16 [[ATOMIC_LOAD15]], i16* [[ATMP16]], align 2
// CHK-C-NEXT:    [[CMP17:%.*]] = icmp ult i16 [[ATOMIC_LOAD15]], [[TMP16]]
// CHK-C-NEXT:    [[FROMBOOL19:%.*]] = zext i1 [[CMP17]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL19]], i8* [[ATMP18]], align 1
// CHK-C-NEXT:    br i1 [[CMP17]], label [[ATOMIC_CONT20:%.*]], label [[ATOMIC_EXIT25:%.*]]
// CHK-C:       atomic_cont20:
// CHK-C-NEXT:    [[TMP17:%.*]] = phi i16 [ [[ATOMIC_LOAD15]], [[ATOMIC_EXIT14]] ], [ [[TMP20:%.*]], [[ATOMIC_CMP22:%.*]] ]
// CHK-C-NEXT:    store i16 [[TMP16]], i16* [[ATOMIC_TEMP21]], align 2
// CHK-C-NEXT:    [[TMP18:%.*]] = load i16, i16* [[ATOMIC_TEMP21]], align 2
// CHK-C-NEXT:    [[TMP19:%.*]] = cmpxchg i16* [[X]], i16 [[TMP17]], i16 [[TMP18]] monotonic monotonic, align 2
// CHK-C-NEXT:    [[TMP20]] = extractvalue { i16, i1 } [[TMP19]], 0
// CHK-C-NEXT:    [[TMP21:%.*]] = extractvalue { i16, i1 } [[TMP19]], 1
// CHK-C-NEXT:    br i1 [[TMP21]], label [[ATOMIC_EXIT25]], label [[ATOMIC_CMP22]]
// CHK-C:       atomic_cmp22:
// CHK-C-NEXT:    store i16 [[TMP20]], i16* [[ATMP16]], align 2
// CHK-C-NEXT:    [[CMP23:%.*]] = icmp ult i16 [[TMP20]], [[TMP16]]
// CHK-C-NEXT:    [[FROMBOOL24:%.*]] = zext i1 [[CMP23]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL24]], i8* [[ATMP18]], align 1
// CHK-C-NEXT:    br i1 [[CMP23]], label [[ATOMIC_CONT20]], label [[ATOMIC_EXIT25]]
// CHK-C:       atomic_exit25:
// CHK-C-NEXT:    [[TMP22:%.*]] = load i16, i16* [[ATMP16]], align 2
// CHK-C-NEXT:    [[TMP23:%.*]] = load i8, i8* [[ATMP18]], align 1
// CHK-C-NEXT:    store i16 [[TMP22]], i16* [[V]], align 2
// CHK-C-NEXT:    [[TMP24:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-C-NEXT:    [[ATOMIC_LOAD26:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-C-NEXT:    store i16 [[ATOMIC_LOAD26]], i16* [[ATMP27]], align 2
// CHK-C-NEXT:    [[CMP28:%.*]] = icmp ult i16 [[ATOMIC_LOAD26]], [[TMP24]]
// CHK-C-NEXT:    [[FROMBOOL30:%.*]] = zext i1 [[CMP28]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL30]], i8* [[ATMP29]], align 1
// CHK-C-NEXT:    br i1 [[CMP28]], label [[ATOMIC_CONT31:%.*]], label [[ATOMIC_EXIT37:%.*]]
// CHK-C:       atomic_cont31:
// CHK-C-NEXT:    [[TMP25:%.*]] = phi i16 [ [[ATOMIC_LOAD26]], [[ATOMIC_EXIT25]] ], [ [[TMP28:%.*]], [[ATOMIC_CMP34:%.*]] ]
// CHK-C-NEXT:    store i16 [[TMP24]], i16* [[ATOMIC_TEMP32]], align 2
// CHK-C-NEXT:    [[TMP26:%.*]] = load i16, i16* [[ATOMIC_TEMP32]], align 2
// CHK-C-NEXT:    [[TMP27:%.*]] = cmpxchg i16* [[X]], i16 [[TMP25]], i16 [[TMP26]] monotonic monotonic, align 2
// CHK-C-NEXT:    [[TMP28]] = extractvalue { i16, i1 } [[TMP27]], 0
// CHK-C-NEXT:    [[TMP29:%.*]] = extractvalue { i16, i1 } [[TMP27]], 1
// CHK-C-NEXT:    br i1 [[TMP29]], label [[ATOMIC_UPD_EXIT33:%.*]], label [[ATOMIC_CMP34]]
// CHK-C:       atomic_upd_exit33:
// CHK-C-NEXT:    store i16 [[TMP24]], i16* [[ATMP27]], align 2
// CHK-C-NEXT:    br label [[ATOMIC_EXIT37]]
// CHK-C:       atomic_cmp34:
// CHK-C-NEXT:    store i16 [[TMP28]], i16* [[ATMP27]], align 2
// CHK-C-NEXT:    [[CMP35:%.*]] = icmp ult i16 [[TMP28]], [[TMP24]]
// CHK-C-NEXT:    [[FROMBOOL36:%.*]] = zext i1 [[CMP35]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL36]], i8* [[ATMP29]], align 1
// CHK-C-NEXT:    br i1 [[CMP35]], label [[ATOMIC_CONT31]], label [[ATOMIC_EXIT37]]
// CHK-C:       atomic_exit37:
// CHK-C-NEXT:    [[TMP30:%.*]] = load i16, i16* [[ATMP27]], align 2
// CHK-C-NEXT:    [[TMP31:%.*]] = load i8, i8* [[ATMP29]], align 1
// CHK-C-NEXT:    store i16 [[TMP30]], i16* [[V]], align 2
// CHK-C-NEXT:    [[TMP32:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-C-NEXT:    [[ATOMIC_LOAD38:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-C-NEXT:    store i16 [[ATOMIC_LOAD38]], i16* [[ATMP39]], align 2
// CHK-C-NEXT:    [[CMP40:%.*]] = icmp ult i16 [[ATOMIC_LOAD38]], [[TMP32]]
// CHK-C-NEXT:    [[FROMBOOL42:%.*]] = zext i1 [[CMP40]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL42]], i8* [[ATMP41]], align 1
// CHK-C-NEXT:    br i1 [[CMP40]], label [[ATOMIC_CONT43:%.*]], label [[ATOMIC_EXIT48:%.*]]
// CHK-C:       atomic_cont43:
// CHK-C-NEXT:    [[TMP33:%.*]] = phi i16 [ [[ATOMIC_LOAD38]], [[ATOMIC_EXIT37]] ], [ [[TMP36:%.*]], [[ATOMIC_CMP45:%.*]] ]
// CHK-C-NEXT:    store i16 [[TMP32]], i16* [[ATOMIC_TEMP44]], align 2
// CHK-C-NEXT:    [[TMP34:%.*]] = load i16, i16* [[ATOMIC_TEMP44]], align 2
// CHK-C-NEXT:    [[TMP35:%.*]] = cmpxchg i16* [[X]], i16 [[TMP33]], i16 [[TMP34]] monotonic monotonic, align 2
// CHK-C-NEXT:    [[TMP36]] = extractvalue { i16, i1 } [[TMP35]], 0
// CHK-C-NEXT:    [[TMP37:%.*]] = extractvalue { i16, i1 } [[TMP35]], 1
// CHK-C-NEXT:    br i1 [[TMP37]], label [[ATOMIC_EXIT48]], label [[ATOMIC_CMP45]]
// CHK-C:       atomic_cmp45:
// CHK-C-NEXT:    store i16 [[TMP36]], i16* [[ATMP39]], align 2
// CHK-C-NEXT:    [[CMP46:%.*]] = icmp ult i16 [[TMP36]], [[TMP32]]
// CHK-C-NEXT:    [[FROMBOOL47:%.*]] = zext i1 [[CMP46]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL47]], i8* [[ATMP41]], align 1
// CHK-C-NEXT:    br i1 [[CMP46]], label [[ATOMIC_CONT43]], label [[ATOMIC_EXIT48]]
// CHK-C:       atomic_exit48:
// CHK-C-NEXT:    [[TMP38:%.*]] = load i16, i16* [[ATMP39]], align 2
// CHK-C-NEXT:    [[TMP39:%.*]] = load i8, i8* [[ATMP41]], align 1
// CHK-C-NEXT:    store i16 [[TMP38]], i16* [[V]], align 2
// CHK-C-NEXT:    [[TMP40:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-C-NEXT:    [[ATOMIC_LOAD49:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-C-NEXT:    store i16 [[ATOMIC_LOAD49]], i16* [[ATMP50]], align 2
// CHK-C-NEXT:    [[CMP51:%.*]] = icmp ult i16 [[ATOMIC_LOAD49]], [[TMP40]]
// CHK-C-NEXT:    [[FROMBOOL53:%.*]] = zext i1 [[CMP51]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL53]], i8* [[ATMP52]], align 1
// CHK-C-NEXT:    br i1 [[CMP51]], label [[ATOMIC_CONT54:%.*]], label [[ATOMIC_EXIT60:%.*]]
// CHK-C:       atomic_cont54:
// CHK-C-NEXT:    [[TMP41:%.*]] = phi i16 [ [[ATOMIC_LOAD49]], [[ATOMIC_EXIT48]] ], [ [[TMP44:%.*]], [[ATOMIC_CMP57:%.*]] ]
// CHK-C-NEXT:    store i16 [[TMP40]], i16* [[ATOMIC_TEMP55]], align 2
// CHK-C-NEXT:    [[TMP42:%.*]] = load i16, i16* [[ATOMIC_TEMP55]], align 2
// CHK-C-NEXT:    [[TMP43:%.*]] = cmpxchg i16* [[X]], i16 [[TMP41]], i16 [[TMP42]] monotonic monotonic, align 2
// CHK-C-NEXT:    [[TMP44]] = extractvalue { i16, i1 } [[TMP43]], 0
// CHK-C-NEXT:    [[TMP45:%.*]] = extractvalue { i16, i1 } [[TMP43]], 1
// CHK-C-NEXT:    br i1 [[TMP45]], label [[ATOMIC_UPD_EXIT56:%.*]], label [[ATOMIC_CMP57]]
// CHK-C:       atomic_upd_exit56:
// CHK-C-NEXT:    store i16 [[TMP40]], i16* [[ATMP50]], align 2
// CHK-C-NEXT:    br label [[ATOMIC_EXIT60]]
// CHK-C:       atomic_cmp57:
// CHK-C-NEXT:    store i16 [[TMP44]], i16* [[ATMP50]], align 2
// CHK-C-NEXT:    [[CMP58:%.*]] = icmp ult i16 [[TMP44]], [[TMP40]]
// CHK-C-NEXT:    [[FROMBOOL59:%.*]] = zext i1 [[CMP58]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL59]], i8* [[ATMP52]], align 1
// CHK-C-NEXT:    br i1 [[CMP58]], label [[ATOMIC_CONT54]], label [[ATOMIC_EXIT60]]
// CHK-C:       atomic_exit60:
// CHK-C-NEXT:    [[TMP46:%.*]] = load i16, i16* [[ATMP50]], align 2
// CHK-C-NEXT:    [[TMP47:%.*]] = load i8, i8* [[ATMP52]], align 1
// CHK-C-NEXT:    store i16 [[TMP46]], i16* [[V]], align 2
// CHK-C-NEXT:    [[TMP48:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-C-NEXT:    [[ATOMIC_LOAD61:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-C-NEXT:    store i16 [[ATOMIC_LOAD61]], i16* [[ATMP62]], align 2
// CHK-C-NEXT:    [[CMP63:%.*]] = icmp ugt i16 [[ATOMIC_LOAD61]], [[TMP48]]
// CHK-C-NEXT:    [[FROMBOOL65:%.*]] = zext i1 [[CMP63]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL65]], i8* [[ATMP64]], align 1
// CHK-C-NEXT:    br i1 [[CMP63]], label [[ATOMIC_CONT66:%.*]], label [[ATOMIC_EXIT71:%.*]]
// CHK-C:       atomic_cont66:
// CHK-C-NEXT:    [[TMP49:%.*]] = phi i16 [ [[ATOMIC_LOAD61]], [[ATOMIC_EXIT60]] ], [ [[TMP52:%.*]], [[ATOMIC_CMP68:%.*]] ]
// CHK-C-NEXT:    store i16 [[TMP48]], i16* [[ATOMIC_TEMP67]], align 2
// CHK-C-NEXT:    [[TMP50:%.*]] = load i16, i16* [[ATOMIC_TEMP67]], align 2
// CHK-C-NEXT:    [[TMP51:%.*]] = cmpxchg i16* [[X]], i16 [[TMP49]], i16 [[TMP50]] monotonic monotonic, align 2
// CHK-C-NEXT:    [[TMP52]] = extractvalue { i16, i1 } [[TMP51]], 0
// CHK-C-NEXT:    [[TMP53:%.*]] = extractvalue { i16, i1 } [[TMP51]], 1
// CHK-C-NEXT:    br i1 [[TMP53]], label [[ATOMIC_EXIT71]], label [[ATOMIC_CMP68]]
// CHK-C:       atomic_cmp68:
// CHK-C-NEXT:    store i16 [[TMP52]], i16* [[ATMP62]], align 2
// CHK-C-NEXT:    [[CMP69:%.*]] = icmp ugt i16 [[TMP52]], [[TMP48]]
// CHK-C-NEXT:    [[FROMBOOL70:%.*]] = zext i1 [[CMP69]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL70]], i8* [[ATMP64]], align 1
// CHK-C-NEXT:    br i1 [[CMP69]], label [[ATOMIC_CONT66]], label [[ATOMIC_EXIT71]]
// CHK-C:       atomic_exit71:
// CHK-C-NEXT:    [[TMP54:%.*]] = load i16, i16* [[ATMP62]], align 2
// CHK-C-NEXT:    [[TMP55:%.*]] = load i8, i8* [[ATMP64]], align 1
// CHK-C-NEXT:    store i16 [[TMP54]], i16* [[V]], align 2
// CHK-C-NEXT:    [[TMP56:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-C-NEXT:    [[ATOMIC_LOAD72:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-C-NEXT:    store i16 [[ATOMIC_LOAD72]], i16* [[ATMP73]], align 2
// CHK-C-NEXT:    [[CMP74:%.*]] = icmp ugt i16 [[ATOMIC_LOAD72]], [[TMP56]]
// CHK-C-NEXT:    [[FROMBOOL76:%.*]] = zext i1 [[CMP74]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL76]], i8* [[ATMP75]], align 1
// CHK-C-NEXT:    br i1 [[CMP74]], label [[ATOMIC_CONT77:%.*]], label [[ATOMIC_EXIT83:%.*]]
// CHK-C:       atomic_cont77:
// CHK-C-NEXT:    [[TMP57:%.*]] = phi i16 [ [[ATOMIC_LOAD72]], [[ATOMIC_EXIT71]] ], [ [[TMP60:%.*]], [[ATOMIC_CMP80:%.*]] ]
// CHK-C-NEXT:    store i16 [[TMP56]], i16* [[ATOMIC_TEMP78]], align 2
// CHK-C-NEXT:    [[TMP58:%.*]] = load i16, i16* [[ATOMIC_TEMP78]], align 2
// CHK-C-NEXT:    [[TMP59:%.*]] = cmpxchg i16* [[X]], i16 [[TMP57]], i16 [[TMP58]] monotonic monotonic, align 2
// CHK-C-NEXT:    [[TMP60]] = extractvalue { i16, i1 } [[TMP59]], 0
// CHK-C-NEXT:    [[TMP61:%.*]] = extractvalue { i16, i1 } [[TMP59]], 1
// CHK-C-NEXT:    br i1 [[TMP61]], label [[ATOMIC_UPD_EXIT79:%.*]], label [[ATOMIC_CMP80]]
// CHK-C:       atomic_upd_exit79:
// CHK-C-NEXT:    store i16 [[TMP56]], i16* [[ATMP73]], align 2
// CHK-C-NEXT:    br label [[ATOMIC_EXIT83]]
// CHK-C:       atomic_cmp80:
// CHK-C-NEXT:    store i16 [[TMP60]], i16* [[ATMP73]], align 2
// CHK-C-NEXT:    [[CMP81:%.*]] = icmp ugt i16 [[TMP60]], [[TMP56]]
// CHK-C-NEXT:    [[FROMBOOL82:%.*]] = zext i1 [[CMP81]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL82]], i8* [[ATMP75]], align 1
// CHK-C-NEXT:    br i1 [[CMP81]], label [[ATOMIC_CONT77]], label [[ATOMIC_EXIT83]]
// CHK-C:       atomic_exit83:
// CHK-C-NEXT:    [[TMP62:%.*]] = load i16, i16* [[ATMP73]], align 2
// CHK-C-NEXT:    [[TMP63:%.*]] = load i8, i8* [[ATMP75]], align 1
// CHK-C-NEXT:    store i16 [[TMP62]], i16* [[V]], align 2
// CHK-C-NEXT:    [[TMP64:%.*]] = load i16, i16* [[D]], align 2
// CHK-C-NEXT:    [[TMP65:%.*]] = load i16, i16* [[E]], align 2
// CHK-C-NEXT:    [[ATOMIC_LOAD84:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-C-NEXT:    store i16 [[ATOMIC_LOAD84]], i16* [[ATMP85]], align 2
// CHK-C-NEXT:    [[CMP86:%.*]] = icmp eq i16 [[ATOMIC_LOAD84]], [[TMP65]]
// CHK-C-NEXT:    [[FROMBOOL88:%.*]] = zext i1 [[CMP86]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL88]], i8* [[ATMP87]], align 1
// CHK-C-NEXT:    br i1 [[CMP86]], label [[ATOMIC_CONT89:%.*]], label [[ATOMIC_EXIT94:%.*]]
// CHK-C:       atomic_cont89:
// CHK-C-NEXT:    [[TMP66:%.*]] = phi i16 [ [[ATOMIC_LOAD84]], [[ATOMIC_EXIT83]] ], [ [[TMP69:%.*]], [[ATOMIC_CMP91:%.*]] ]
// CHK-C-NEXT:    store i16 [[TMP64]], i16* [[ATOMIC_TEMP90]], align 2
// CHK-C-NEXT:    [[TMP67:%.*]] = load i16, i16* [[ATOMIC_TEMP90]], align 2
// CHK-C-NEXT:    [[TMP68:%.*]] = cmpxchg i16* [[X]], i16 [[TMP66]], i16 [[TMP67]] monotonic monotonic, align 2
// CHK-C-NEXT:    [[TMP69]] = extractvalue { i16, i1 } [[TMP68]], 0
// CHK-C-NEXT:    [[TMP70:%.*]] = extractvalue { i16, i1 } [[TMP68]], 1
// CHK-C-NEXT:    br i1 [[TMP70]], label [[ATOMIC_EXIT94]], label [[ATOMIC_CMP91]]
// CHK-C:       atomic_cmp91:
// CHK-C-NEXT:    store i16 [[TMP69]], i16* [[ATMP85]], align 2
// CHK-C-NEXT:    [[CMP92:%.*]] = icmp eq i16 [[TMP69]], [[TMP65]]
// CHK-C-NEXT:    [[FROMBOOL93:%.*]] = zext i1 [[CMP92]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL93]], i8* [[ATMP87]], align 1
// CHK-C-NEXT:    br i1 [[CMP92]], label [[ATOMIC_CONT89]], label [[ATOMIC_EXIT94]]
// CHK-C:       atomic_exit94:
// CHK-C-NEXT:    [[TMP71:%.*]] = load i16, i16* [[ATMP85]], align 2
// CHK-C-NEXT:    [[TMP72:%.*]] = load i8, i8* [[ATMP87]], align 1
// CHK-C-NEXT:    store i16 [[TMP71]], i16* [[V]], align 2
// CHK-C-NEXT:    [[TMP73:%.*]] = load i16, i16* [[D]], align 2
// CHK-C-NEXT:    [[TMP74:%.*]] = load i16, i16* [[E]], align 2
// CHK-C-NEXT:    [[ATOMIC_LOAD95:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-C-NEXT:    store i16 [[ATOMIC_LOAD95]], i16* [[ATMP96]], align 2
// CHK-C-NEXT:    [[CMP97:%.*]] = icmp eq i16 [[ATOMIC_LOAD95]], [[TMP74]]
// CHK-C-NEXT:    [[FROMBOOL99:%.*]] = zext i1 [[CMP97]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL99]], i8* [[ATMP98]], align 1
// CHK-C-NEXT:    br i1 [[CMP97]], label [[ATOMIC_CONT100:%.*]], label [[ATOMIC_EXIT106:%.*]]
// CHK-C:       atomic_cont100:
// CHK-C-NEXT:    [[TMP75:%.*]] = phi i16 [ [[ATOMIC_LOAD95]], [[ATOMIC_EXIT94]] ], [ [[TMP78:%.*]], [[ATOMIC_CMP103:%.*]] ]
// CHK-C-NEXT:    store i16 [[TMP73]], i16* [[ATOMIC_TEMP101]], align 2
// CHK-C-NEXT:    [[TMP76:%.*]] = load i16, i16* [[ATOMIC_TEMP101]], align 2
// CHK-C-NEXT:    [[TMP77:%.*]] = cmpxchg i16* [[X]], i16 [[TMP75]], i16 [[TMP76]] monotonic monotonic, align 2
// CHK-C-NEXT:    [[TMP78]] = extractvalue { i16, i1 } [[TMP77]], 0
// CHK-C-NEXT:    [[TMP79:%.*]] = extractvalue { i16, i1 } [[TMP77]], 1
// CHK-C-NEXT:    br i1 [[TMP79]], label [[ATOMIC_UPD_EXIT102:%.*]], label [[ATOMIC_CMP103]]
// CHK-C:       atomic_upd_exit102:
// CHK-C-NEXT:    store i16 [[TMP73]], i16* [[ATMP96]], align 2
// CHK-C-NEXT:    br label [[ATOMIC_EXIT106]]
// CHK-C:       atomic_cmp103:
// CHK-C-NEXT:    store i16 [[TMP78]], i16* [[ATMP96]], align 2
// CHK-C-NEXT:    [[CMP104:%.*]] = icmp eq i16 [[TMP78]], [[TMP74]]
// CHK-C-NEXT:    [[FROMBOOL105:%.*]] = zext i1 [[CMP104]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL105]], i8* [[ATMP98]], align 1
// CHK-C-NEXT:    br i1 [[CMP104]], label [[ATOMIC_CONT100]], label [[ATOMIC_EXIT106]]
// CHK-C:       atomic_exit106:
// CHK-C-NEXT:    [[TMP80:%.*]] = load i16, i16* [[ATMP96]], align 2
// CHK-C-NEXT:    [[TMP81:%.*]] = load i8, i8* [[ATMP98]], align 1
// CHK-C-NEXT:    store i16 [[TMP80]], i16* [[V]], align 2
// CHK-C-NEXT:    [[TMP82:%.*]] = load i16, i16* [[D]], align 2
// CHK-C-NEXT:    [[TMP83:%.*]] = load i16, i16* [[E]], align 2
// CHK-C-NEXT:    [[ATOMIC_LOAD107:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-C-NEXT:    store i16 [[ATOMIC_LOAD107]], i16* [[ATMP108]], align 2
// CHK-C-NEXT:    [[CMP109:%.*]] = icmp eq i16 [[ATOMIC_LOAD107]], [[TMP83]]
// CHK-C-NEXT:    [[FROMBOOL111:%.*]] = zext i1 [[CMP109]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL111]], i8* [[ATMP110]], align 1
// CHK-C-NEXT:    br i1 [[CMP109]], label [[ATOMIC_CONT112:%.*]], label [[ATOMIC_EXIT118:%.*]]
// CHK-C:       atomic_cont112:
// CHK-C-NEXT:    [[TMP84:%.*]] = phi i16 [ [[ATOMIC_LOAD107]], [[ATOMIC_EXIT106]] ], [ [[TMP87:%.*]], [[ATOMIC_CMP115:%.*]] ]
// CHK-C-NEXT:    store i16 [[TMP82]], i16* [[ATOMIC_TEMP113]], align 2
// CHK-C-NEXT:    [[TMP85:%.*]] = load i16, i16* [[ATOMIC_TEMP113]], align 2
// CHK-C-NEXT:    [[TMP86:%.*]] = cmpxchg i16* [[X]], i16 [[TMP84]], i16 [[TMP85]] monotonic monotonic, align 2
// CHK-C-NEXT:    [[TMP87]] = extractvalue { i16, i1 } [[TMP86]], 0
// CHK-C-NEXT:    [[TMP88:%.*]] = extractvalue { i16, i1 } [[TMP86]], 1
// CHK-C-NEXT:    br i1 [[TMP88]], label [[ATOMIC_UPD_EXIT114:%.*]], label [[ATOMIC_CMP115]]
// CHK-C:       atomic_upd_exit114:
// CHK-C-NEXT:    store i16 [[TMP82]], i16* [[ATMP108]], align 2
// CHK-C-NEXT:    br label [[ATOMIC_EXIT118]]
// CHK-C:       atomic_cmp115:
// CHK-C-NEXT:    store i16 [[TMP87]], i16* [[ATMP108]], align 2
// CHK-C-NEXT:    [[CMP116:%.*]] = icmp eq i16 [[TMP87]], [[TMP83]]
// CHK-C-NEXT:    [[FROMBOOL117:%.*]] = zext i1 [[CMP116]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL117]], i8* [[ATMP110]], align 1
// CHK-C-NEXT:    br i1 [[CMP116]], label [[ATOMIC_CONT112]], label [[ATOMIC_EXIT118]]
// CHK-C:       atomic_exit118:
// CHK-C-NEXT:    [[TMP89:%.*]] = load i16, i16* [[ATMP108]], align 2
// CHK-C-NEXT:    [[TMP90:%.*]] = load i8, i8* [[ATMP110]], align 1
// CHK-C-NEXT:    [[TMP91:%.*]] = trunc i8 [[TMP90]] to i1
// CHK-C-NEXT:    br i1 [[TMP91]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-C:       atomic_capture:
// CHK-C-NEXT:    store i16 [[TMP89]], i16* [[V]], align 2
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-C:       atomic_capture_cont:
// CHK-C-NEXT:    [[TMP92:%.*]] = load i16, i16* [[D]], align 2
// CHK-C-NEXT:    [[TMP93:%.*]] = load i16, i16* [[E]], align 2
// CHK-C-NEXT:    [[ATOMIC_LOAD119:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-C-NEXT:    store i16 [[ATOMIC_LOAD119]], i16* [[ATMP120]], align 2
// CHK-C-NEXT:    [[CMP121:%.*]] = icmp eq i16 [[ATOMIC_LOAD119]], [[TMP93]]
// CHK-C-NEXT:    [[FROMBOOL123:%.*]] = zext i1 [[CMP121]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL123]], i8* [[ATMP122]], align 1
// CHK-C-NEXT:    br i1 [[CMP121]], label [[ATOMIC_CONT124:%.*]], label [[ATOMIC_EXIT129:%.*]]
// CHK-C:       atomic_cont124:
// CHK-C-NEXT:    [[TMP94:%.*]] = phi i16 [ [[ATOMIC_LOAD119]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP97:%.*]], [[ATOMIC_CMP126:%.*]] ]
// CHK-C-NEXT:    store i16 [[TMP92]], i16* [[ATOMIC_TEMP125]], align 2
// CHK-C-NEXT:    [[TMP95:%.*]] = load i16, i16* [[ATOMIC_TEMP125]], align 2
// CHK-C-NEXT:    [[TMP96:%.*]] = cmpxchg i16* [[X]], i16 [[TMP94]], i16 [[TMP95]] monotonic monotonic, align 2
// CHK-C-NEXT:    [[TMP97]] = extractvalue { i16, i1 } [[TMP96]], 0
// CHK-C-NEXT:    [[TMP98:%.*]] = extractvalue { i16, i1 } [[TMP96]], 1
// CHK-C-NEXT:    br i1 [[TMP98]], label [[ATOMIC_EXIT129]], label [[ATOMIC_CMP126]]
// CHK-C:       atomic_cmp126:
// CHK-C-NEXT:    store i16 [[TMP97]], i16* [[ATMP120]], align 2
// CHK-C-NEXT:    [[CMP127:%.*]] = icmp eq i16 [[TMP97]], [[TMP93]]
// CHK-C-NEXT:    [[FROMBOOL128:%.*]] = zext i1 [[CMP127]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL128]], i8* [[ATMP122]], align 1
// CHK-C-NEXT:    br i1 [[CMP127]], label [[ATOMIC_CONT124]], label [[ATOMIC_EXIT129]]
// CHK-C:       atomic_exit129:
// CHK-C-NEXT:    [[TMP99:%.*]] = load i16, i16* [[ATMP120]], align 2
// CHK-C-NEXT:    [[TMP100:%.*]] = load i8, i8* [[ATMP122]], align 1
// CHK-C-NEXT:    [[CONV:%.*]] = zext i8 [[TMP100]] to i32
// CHK-C-NEXT:    store i32 [[CONV]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP101:%.*]] = load i16, i16* [[D]], align 2
// CHK-C-NEXT:    [[TMP102:%.*]] = load i16, i16* [[E]], align 2
// CHK-C-NEXT:    [[ATOMIC_LOAD130:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-C-NEXT:    store i16 [[ATOMIC_LOAD130]], i16* [[ATMP131]], align 2
// CHK-C-NEXT:    [[CMP132:%.*]] = icmp eq i16 [[ATOMIC_LOAD130]], [[TMP102]]
// CHK-C-NEXT:    [[FROMBOOL134:%.*]] = zext i1 [[CMP132]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL134]], i8* [[ATMP133]], align 1
// CHK-C-NEXT:    br i1 [[CMP132]], label [[ATOMIC_CONT135:%.*]], label [[ATOMIC_EXIT140:%.*]]
// CHK-C:       atomic_cont135:
// CHK-C-NEXT:    [[TMP103:%.*]] = phi i16 [ [[ATOMIC_LOAD130]], [[ATOMIC_EXIT129]] ], [ [[TMP106:%.*]], [[ATOMIC_CMP137:%.*]] ]
// CHK-C-NEXT:    store i16 [[TMP101]], i16* [[ATOMIC_TEMP136]], align 2
// CHK-C-NEXT:    [[TMP104:%.*]] = load i16, i16* [[ATOMIC_TEMP136]], align 2
// CHK-C-NEXT:    [[TMP105:%.*]] = cmpxchg i16* [[X]], i16 [[TMP103]], i16 [[TMP104]] monotonic monotonic, align 2
// CHK-C-NEXT:    [[TMP106]] = extractvalue { i16, i1 } [[TMP105]], 0
// CHK-C-NEXT:    [[TMP107:%.*]] = extractvalue { i16, i1 } [[TMP105]], 1
// CHK-C-NEXT:    br i1 [[TMP107]], label [[ATOMIC_EXIT140]], label [[ATOMIC_CMP137]]
// CHK-C:       atomic_cmp137:
// CHK-C-NEXT:    store i16 [[TMP106]], i16* [[ATMP131]], align 2
// CHK-C-NEXT:    [[CMP138:%.*]] = icmp eq i16 [[TMP106]], [[TMP102]]
// CHK-C-NEXT:    [[FROMBOOL139:%.*]] = zext i1 [[CMP138]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL139]], i8* [[ATMP133]], align 1
// CHK-C-NEXT:    br i1 [[CMP138]], label [[ATOMIC_CONT135]], label [[ATOMIC_EXIT140]]
// CHK-C:       atomic_exit140:
// CHK-C-NEXT:    [[TMP108:%.*]] = load i16, i16* [[ATMP131]], align 2
// CHK-C-NEXT:    [[TMP109:%.*]] = load i8, i8* [[ATMP133]], align 1
// CHK-C-NEXT:    [[CONV141:%.*]] = zext i8 [[TMP109]] to i32
// CHK-C-NEXT:    store i32 [[CONV141]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP110:%.*]] = trunc i8 [[TMP109]] to i1
// CHK-C-NEXT:    br i1 [[TMP110]], label [[ATOMIC_CAPTURE_CONT143:%.*]], label [[ATOMIC_CAPTURE142:%.*]]
// CHK-C:       atomic_capture142:
// CHK-C-NEXT:    store i16 [[TMP108]], i16* [[V]], align 2
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT143]]
// CHK-C:       atomic_capture_cont143:
// CHK-C-NEXT:    ret void
//
// CHK-CXX-LABEL: @_Z19test_unsigned_shortv(
// CHK-CXX-NEXT:  entry:
// CHK-CXX-NEXT:    [[X:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[EXPR:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[D:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[E:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[V:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[R:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[TMP:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP5:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP7:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP10:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP16:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP18:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP21:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP27:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP29:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP32:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP39:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP41:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP44:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP50:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP52:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP55:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP62:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP64:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP67:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP73:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP75:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP78:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP85:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP87:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP90:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP96:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP98:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP101:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP108:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP110:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP113:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP120:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP122:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP125:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP131:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[ATMP133:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP136:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[TMP0:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-CXX-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-CXX-NEXT:    store i16 [[ATOMIC_LOAD]], i16* [[TMP]], align 2
// CHK-CXX-NEXT:    [[CMP:%.*]] = icmp ugt i16 [[ATOMIC_LOAD]], [[TMP0]]
// CHK-CXX-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-CXX:       atomic_cont:
// CHK-CXX-NEXT:    [[TMP1:%.*]] = phi i16 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP4:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-CXX-NEXT:    store i16 [[TMP0]], i16* [[ATOMIC_TEMP]], align 2
// CHK-CXX-NEXT:    [[TMP2:%.*]] = load i16, i16* [[ATOMIC_TEMP]], align 2
// CHK-CXX-NEXT:    [[TMP3:%.*]] = cmpxchg i16* [[X]], i16 [[TMP1]], i16 [[TMP2]] monotonic monotonic, align 2
// CHK-CXX-NEXT:    [[TMP4]] = extractvalue { i16, i1 } [[TMP3]], 0
// CHK-CXX-NEXT:    [[TMP5:%.*]] = extractvalue { i16, i1 } [[TMP3]], 1
// CHK-CXX-NEXT:    br i1 [[TMP5]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-CXX:       atomic_cmp:
// CHK-CXX-NEXT:    store i16 [[TMP4]], i16* [[TMP]], align 2
// CHK-CXX-NEXT:    [[CMP2:%.*]] = icmp ugt i16 [[TMP4]], [[TMP0]]
// CHK-CXX-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[CMP2]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL3]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP2]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-CXX:       atomic_exit:
// CHK-CXX-NEXT:    [[TMP6:%.*]] = load i16, i16* [[TMP]], align 2
// CHK-CXX-NEXT:    [[TMP7:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    store i16 [[TMP6]], i16* [[V]], align 2
// CHK-CXX-NEXT:    [[TMP8:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-CXX-NEXT:    [[ATOMIC_LOAD4:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-CXX-NEXT:    store i16 [[ATOMIC_LOAD4]], i16* [[ATMP5]], align 2
// CHK-CXX-NEXT:    [[CMP6:%.*]] = icmp ugt i16 [[ATOMIC_LOAD4]], [[TMP8]]
// CHK-CXX-NEXT:    [[FROMBOOL8:%.*]] = zext i1 [[CMP6]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL8]], i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP6]], label [[ATOMIC_CONT9:%.*]], label [[ATOMIC_EXIT14:%.*]]
// CHK-CXX:       atomic_cont9:
// CHK-CXX-NEXT:    [[TMP9:%.*]] = phi i16 [ [[ATOMIC_LOAD4]], [[ATOMIC_EXIT]] ], [ [[TMP12:%.*]], [[ATOMIC_CMP11:%.*]] ]
// CHK-CXX-NEXT:    store i16 [[TMP8]], i16* [[ATOMIC_TEMP10]], align 2
// CHK-CXX-NEXT:    [[TMP10:%.*]] = load i16, i16* [[ATOMIC_TEMP10]], align 2
// CHK-CXX-NEXT:    [[TMP11:%.*]] = cmpxchg i16* [[X]], i16 [[TMP9]], i16 [[TMP10]] monotonic monotonic, align 2
// CHK-CXX-NEXT:    [[TMP12]] = extractvalue { i16, i1 } [[TMP11]], 0
// CHK-CXX-NEXT:    [[TMP13:%.*]] = extractvalue { i16, i1 } [[TMP11]], 1
// CHK-CXX-NEXT:    br i1 [[TMP13]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP11]]
// CHK-CXX:       atomic_upd_exit:
// CHK-CXX-NEXT:    store i16 [[TMP8]], i16* [[ATMP5]], align 2
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT14]]
// CHK-CXX:       atomic_cmp11:
// CHK-CXX-NEXT:    store i16 [[TMP12]], i16* [[ATMP5]], align 2
// CHK-CXX-NEXT:    [[CMP12:%.*]] = icmp ugt i16 [[TMP12]], [[TMP8]]
// CHK-CXX-NEXT:    [[FROMBOOL13:%.*]] = zext i1 [[CMP12]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL13]], i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP12]], label [[ATOMIC_CONT9]], label [[ATOMIC_EXIT14]]
// CHK-CXX:       atomic_exit14:
// CHK-CXX-NEXT:    [[TMP14:%.*]] = load i16, i16* [[ATMP5]], align 2
// CHK-CXX-NEXT:    [[TMP15:%.*]] = load i8, i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    store i16 [[TMP14]], i16* [[V]], align 2
// CHK-CXX-NEXT:    [[TMP16:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-CXX-NEXT:    [[ATOMIC_LOAD15:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-CXX-NEXT:    store i16 [[ATOMIC_LOAD15]], i16* [[ATMP16]], align 2
// CHK-CXX-NEXT:    [[CMP17:%.*]] = icmp ult i16 [[ATOMIC_LOAD15]], [[TMP16]]
// CHK-CXX-NEXT:    [[FROMBOOL19:%.*]] = zext i1 [[CMP17]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL19]], i8* [[ATMP18]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP17]], label [[ATOMIC_CONT20:%.*]], label [[ATOMIC_EXIT25:%.*]]
// CHK-CXX:       atomic_cont20:
// CHK-CXX-NEXT:    [[TMP17:%.*]] = phi i16 [ [[ATOMIC_LOAD15]], [[ATOMIC_EXIT14]] ], [ [[TMP20:%.*]], [[ATOMIC_CMP22:%.*]] ]
// CHK-CXX-NEXT:    store i16 [[TMP16]], i16* [[ATOMIC_TEMP21]], align 2
// CHK-CXX-NEXT:    [[TMP18:%.*]] = load i16, i16* [[ATOMIC_TEMP21]], align 2
// CHK-CXX-NEXT:    [[TMP19:%.*]] = cmpxchg i16* [[X]], i16 [[TMP17]], i16 [[TMP18]] monotonic monotonic, align 2
// CHK-CXX-NEXT:    [[TMP20]] = extractvalue { i16, i1 } [[TMP19]], 0
// CHK-CXX-NEXT:    [[TMP21:%.*]] = extractvalue { i16, i1 } [[TMP19]], 1
// CHK-CXX-NEXT:    br i1 [[TMP21]], label [[ATOMIC_EXIT25]], label [[ATOMIC_CMP22]]
// CHK-CXX:       atomic_cmp22:
// CHK-CXX-NEXT:    store i16 [[TMP20]], i16* [[ATMP16]], align 2
// CHK-CXX-NEXT:    [[CMP23:%.*]] = icmp ult i16 [[TMP20]], [[TMP16]]
// CHK-CXX-NEXT:    [[FROMBOOL24:%.*]] = zext i1 [[CMP23]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL24]], i8* [[ATMP18]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP23]], label [[ATOMIC_CONT20]], label [[ATOMIC_EXIT25]]
// CHK-CXX:       atomic_exit25:
// CHK-CXX-NEXT:    [[TMP22:%.*]] = load i16, i16* [[ATMP16]], align 2
// CHK-CXX-NEXT:    [[TMP23:%.*]] = load i8, i8* [[ATMP18]], align 1
// CHK-CXX-NEXT:    store i16 [[TMP22]], i16* [[V]], align 2
// CHK-CXX-NEXT:    [[TMP24:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-CXX-NEXT:    [[ATOMIC_LOAD26:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-CXX-NEXT:    store i16 [[ATOMIC_LOAD26]], i16* [[ATMP27]], align 2
// CHK-CXX-NEXT:    [[CMP28:%.*]] = icmp ult i16 [[ATOMIC_LOAD26]], [[TMP24]]
// CHK-CXX-NEXT:    [[FROMBOOL30:%.*]] = zext i1 [[CMP28]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL30]], i8* [[ATMP29]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP28]], label [[ATOMIC_CONT31:%.*]], label [[ATOMIC_EXIT37:%.*]]
// CHK-CXX:       atomic_cont31:
// CHK-CXX-NEXT:    [[TMP25:%.*]] = phi i16 [ [[ATOMIC_LOAD26]], [[ATOMIC_EXIT25]] ], [ [[TMP28:%.*]], [[ATOMIC_CMP34:%.*]] ]
// CHK-CXX-NEXT:    store i16 [[TMP24]], i16* [[ATOMIC_TEMP32]], align 2
// CHK-CXX-NEXT:    [[TMP26:%.*]] = load i16, i16* [[ATOMIC_TEMP32]], align 2
// CHK-CXX-NEXT:    [[TMP27:%.*]] = cmpxchg i16* [[X]], i16 [[TMP25]], i16 [[TMP26]] monotonic monotonic, align 2
// CHK-CXX-NEXT:    [[TMP28]] = extractvalue { i16, i1 } [[TMP27]], 0
// CHK-CXX-NEXT:    [[TMP29:%.*]] = extractvalue { i16, i1 } [[TMP27]], 1
// CHK-CXX-NEXT:    br i1 [[TMP29]], label [[ATOMIC_UPD_EXIT33:%.*]], label [[ATOMIC_CMP34]]
// CHK-CXX:       atomic_upd_exit33:
// CHK-CXX-NEXT:    store i16 [[TMP24]], i16* [[ATMP27]], align 2
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT37]]
// CHK-CXX:       atomic_cmp34:
// CHK-CXX-NEXT:    store i16 [[TMP28]], i16* [[ATMP27]], align 2
// CHK-CXX-NEXT:    [[CMP35:%.*]] = icmp ult i16 [[TMP28]], [[TMP24]]
// CHK-CXX-NEXT:    [[FROMBOOL36:%.*]] = zext i1 [[CMP35]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL36]], i8* [[ATMP29]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP35]], label [[ATOMIC_CONT31]], label [[ATOMIC_EXIT37]]
// CHK-CXX:       atomic_exit37:
// CHK-CXX-NEXT:    [[TMP30:%.*]] = load i16, i16* [[ATMP27]], align 2
// CHK-CXX-NEXT:    [[TMP31:%.*]] = load i8, i8* [[ATMP29]], align 1
// CHK-CXX-NEXT:    store i16 [[TMP30]], i16* [[V]], align 2
// CHK-CXX-NEXT:    [[TMP32:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-CXX-NEXT:    [[ATOMIC_LOAD38:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-CXX-NEXT:    store i16 [[ATOMIC_LOAD38]], i16* [[ATMP39]], align 2
// CHK-CXX-NEXT:    [[CMP40:%.*]] = icmp ult i16 [[ATOMIC_LOAD38]], [[TMP32]]
// CHK-CXX-NEXT:    [[FROMBOOL42:%.*]] = zext i1 [[CMP40]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL42]], i8* [[ATMP41]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP40]], label [[ATOMIC_CONT43:%.*]], label [[ATOMIC_EXIT48:%.*]]
// CHK-CXX:       atomic_cont43:
// CHK-CXX-NEXT:    [[TMP33:%.*]] = phi i16 [ [[ATOMIC_LOAD38]], [[ATOMIC_EXIT37]] ], [ [[TMP36:%.*]], [[ATOMIC_CMP45:%.*]] ]
// CHK-CXX-NEXT:    store i16 [[TMP32]], i16* [[ATOMIC_TEMP44]], align 2
// CHK-CXX-NEXT:    [[TMP34:%.*]] = load i16, i16* [[ATOMIC_TEMP44]], align 2
// CHK-CXX-NEXT:    [[TMP35:%.*]] = cmpxchg i16* [[X]], i16 [[TMP33]], i16 [[TMP34]] monotonic monotonic, align 2
// CHK-CXX-NEXT:    [[TMP36]] = extractvalue { i16, i1 } [[TMP35]], 0
// CHK-CXX-NEXT:    [[TMP37:%.*]] = extractvalue { i16, i1 } [[TMP35]], 1
// CHK-CXX-NEXT:    br i1 [[TMP37]], label [[ATOMIC_EXIT48]], label [[ATOMIC_CMP45]]
// CHK-CXX:       atomic_cmp45:
// CHK-CXX-NEXT:    store i16 [[TMP36]], i16* [[ATMP39]], align 2
// CHK-CXX-NEXT:    [[CMP46:%.*]] = icmp ult i16 [[TMP36]], [[TMP32]]
// CHK-CXX-NEXT:    [[FROMBOOL47:%.*]] = zext i1 [[CMP46]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL47]], i8* [[ATMP41]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP46]], label [[ATOMIC_CONT43]], label [[ATOMIC_EXIT48]]
// CHK-CXX:       atomic_exit48:
// CHK-CXX-NEXT:    [[TMP38:%.*]] = load i16, i16* [[ATMP39]], align 2
// CHK-CXX-NEXT:    [[TMP39:%.*]] = load i8, i8* [[ATMP41]], align 1
// CHK-CXX-NEXT:    store i16 [[TMP38]], i16* [[V]], align 2
// CHK-CXX-NEXT:    [[TMP40:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-CXX-NEXT:    [[ATOMIC_LOAD49:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-CXX-NEXT:    store i16 [[ATOMIC_LOAD49]], i16* [[ATMP50]], align 2
// CHK-CXX-NEXT:    [[CMP51:%.*]] = icmp ult i16 [[ATOMIC_LOAD49]], [[TMP40]]
// CHK-CXX-NEXT:    [[FROMBOOL53:%.*]] = zext i1 [[CMP51]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL53]], i8* [[ATMP52]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP51]], label [[ATOMIC_CONT54:%.*]], label [[ATOMIC_EXIT60:%.*]]
// CHK-CXX:       atomic_cont54:
// CHK-CXX-NEXT:    [[TMP41:%.*]] = phi i16 [ [[ATOMIC_LOAD49]], [[ATOMIC_EXIT48]] ], [ [[TMP44:%.*]], [[ATOMIC_CMP57:%.*]] ]
// CHK-CXX-NEXT:    store i16 [[TMP40]], i16* [[ATOMIC_TEMP55]], align 2
// CHK-CXX-NEXT:    [[TMP42:%.*]] = load i16, i16* [[ATOMIC_TEMP55]], align 2
// CHK-CXX-NEXT:    [[TMP43:%.*]] = cmpxchg i16* [[X]], i16 [[TMP41]], i16 [[TMP42]] monotonic monotonic, align 2
// CHK-CXX-NEXT:    [[TMP44]] = extractvalue { i16, i1 } [[TMP43]], 0
// CHK-CXX-NEXT:    [[TMP45:%.*]] = extractvalue { i16, i1 } [[TMP43]], 1
// CHK-CXX-NEXT:    br i1 [[TMP45]], label [[ATOMIC_UPD_EXIT56:%.*]], label [[ATOMIC_CMP57]]
// CHK-CXX:       atomic_upd_exit56:
// CHK-CXX-NEXT:    store i16 [[TMP40]], i16* [[ATMP50]], align 2
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT60]]
// CHK-CXX:       atomic_cmp57:
// CHK-CXX-NEXT:    store i16 [[TMP44]], i16* [[ATMP50]], align 2
// CHK-CXX-NEXT:    [[CMP58:%.*]] = icmp ult i16 [[TMP44]], [[TMP40]]
// CHK-CXX-NEXT:    [[FROMBOOL59:%.*]] = zext i1 [[CMP58]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL59]], i8* [[ATMP52]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP58]], label [[ATOMIC_CONT54]], label [[ATOMIC_EXIT60]]
// CHK-CXX:       atomic_exit60:
// CHK-CXX-NEXT:    [[TMP46:%.*]] = load i16, i16* [[ATMP50]], align 2
// CHK-CXX-NEXT:    [[TMP47:%.*]] = load i8, i8* [[ATMP52]], align 1
// CHK-CXX-NEXT:    store i16 [[TMP46]], i16* [[V]], align 2
// CHK-CXX-NEXT:    [[TMP48:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-CXX-NEXT:    [[ATOMIC_LOAD61:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-CXX-NEXT:    store i16 [[ATOMIC_LOAD61]], i16* [[ATMP62]], align 2
// CHK-CXX-NEXT:    [[CMP63:%.*]] = icmp ugt i16 [[ATOMIC_LOAD61]], [[TMP48]]
// CHK-CXX-NEXT:    [[FROMBOOL65:%.*]] = zext i1 [[CMP63]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL65]], i8* [[ATMP64]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP63]], label [[ATOMIC_CONT66:%.*]], label [[ATOMIC_EXIT71:%.*]]
// CHK-CXX:       atomic_cont66:
// CHK-CXX-NEXT:    [[TMP49:%.*]] = phi i16 [ [[ATOMIC_LOAD61]], [[ATOMIC_EXIT60]] ], [ [[TMP52:%.*]], [[ATOMIC_CMP68:%.*]] ]
// CHK-CXX-NEXT:    store i16 [[TMP48]], i16* [[ATOMIC_TEMP67]], align 2
// CHK-CXX-NEXT:    [[TMP50:%.*]] = load i16, i16* [[ATOMIC_TEMP67]], align 2
// CHK-CXX-NEXT:    [[TMP51:%.*]] = cmpxchg i16* [[X]], i16 [[TMP49]], i16 [[TMP50]] monotonic monotonic, align 2
// CHK-CXX-NEXT:    [[TMP52]] = extractvalue { i16, i1 } [[TMP51]], 0
// CHK-CXX-NEXT:    [[TMP53:%.*]] = extractvalue { i16, i1 } [[TMP51]], 1
// CHK-CXX-NEXT:    br i1 [[TMP53]], label [[ATOMIC_EXIT71]], label [[ATOMIC_CMP68]]
// CHK-CXX:       atomic_cmp68:
// CHK-CXX-NEXT:    store i16 [[TMP52]], i16* [[ATMP62]], align 2
// CHK-CXX-NEXT:    [[CMP69:%.*]] = icmp ugt i16 [[TMP52]], [[TMP48]]
// CHK-CXX-NEXT:    [[FROMBOOL70:%.*]] = zext i1 [[CMP69]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL70]], i8* [[ATMP64]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP69]], label [[ATOMIC_CONT66]], label [[ATOMIC_EXIT71]]
// CHK-CXX:       atomic_exit71:
// CHK-CXX-NEXT:    [[TMP54:%.*]] = load i16, i16* [[ATMP62]], align 2
// CHK-CXX-NEXT:    [[TMP55:%.*]] = load i8, i8* [[ATMP64]], align 1
// CHK-CXX-NEXT:    store i16 [[TMP54]], i16* [[V]], align 2
// CHK-CXX-NEXT:    [[TMP56:%.*]] = load i16, i16* [[EXPR]], align 2
// CHK-CXX-NEXT:    [[ATOMIC_LOAD72:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-CXX-NEXT:    store i16 [[ATOMIC_LOAD72]], i16* [[ATMP73]], align 2
// CHK-CXX-NEXT:    [[CMP74:%.*]] = icmp ugt i16 [[ATOMIC_LOAD72]], [[TMP56]]
// CHK-CXX-NEXT:    [[FROMBOOL76:%.*]] = zext i1 [[CMP74]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL76]], i8* [[ATMP75]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP74]], label [[ATOMIC_CONT77:%.*]], label [[ATOMIC_EXIT83:%.*]]
// CHK-CXX:       atomic_cont77:
// CHK-CXX-NEXT:    [[TMP57:%.*]] = phi i16 [ [[ATOMIC_LOAD72]], [[ATOMIC_EXIT71]] ], [ [[TMP60:%.*]], [[ATOMIC_CMP80:%.*]] ]
// CHK-CXX-NEXT:    store i16 [[TMP56]], i16* [[ATOMIC_TEMP78]], align 2
// CHK-CXX-NEXT:    [[TMP58:%.*]] = load i16, i16* [[ATOMIC_TEMP78]], align 2
// CHK-CXX-NEXT:    [[TMP59:%.*]] = cmpxchg i16* [[X]], i16 [[TMP57]], i16 [[TMP58]] monotonic monotonic, align 2
// CHK-CXX-NEXT:    [[TMP60]] = extractvalue { i16, i1 } [[TMP59]], 0
// CHK-CXX-NEXT:    [[TMP61:%.*]] = extractvalue { i16, i1 } [[TMP59]], 1
// CHK-CXX-NEXT:    br i1 [[TMP61]], label [[ATOMIC_UPD_EXIT79:%.*]], label [[ATOMIC_CMP80]]
// CHK-CXX:       atomic_upd_exit79:
// CHK-CXX-NEXT:    store i16 [[TMP56]], i16* [[ATMP73]], align 2
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT83]]
// CHK-CXX:       atomic_cmp80:
// CHK-CXX-NEXT:    store i16 [[TMP60]], i16* [[ATMP73]], align 2
// CHK-CXX-NEXT:    [[CMP81:%.*]] = icmp ugt i16 [[TMP60]], [[TMP56]]
// CHK-CXX-NEXT:    [[FROMBOOL82:%.*]] = zext i1 [[CMP81]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL82]], i8* [[ATMP75]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP81]], label [[ATOMIC_CONT77]], label [[ATOMIC_EXIT83]]
// CHK-CXX:       atomic_exit83:
// CHK-CXX-NEXT:    [[TMP62:%.*]] = load i16, i16* [[ATMP73]], align 2
// CHK-CXX-NEXT:    [[TMP63:%.*]] = load i8, i8* [[ATMP75]], align 1
// CHK-CXX-NEXT:    store i16 [[TMP62]], i16* [[V]], align 2
// CHK-CXX-NEXT:    [[TMP64:%.*]] = load i16, i16* [[D]], align 2
// CHK-CXX-NEXT:    [[TMP65:%.*]] = load i16, i16* [[E]], align 2
// CHK-CXX-NEXT:    [[ATOMIC_LOAD84:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-CXX-NEXT:    store i16 [[ATOMIC_LOAD84]], i16* [[ATMP85]], align 2
// CHK-CXX-NEXT:    [[CMP86:%.*]] = icmp eq i16 [[ATOMIC_LOAD84]], [[TMP65]]
// CHK-CXX-NEXT:    [[FROMBOOL88:%.*]] = zext i1 [[CMP86]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL88]], i8* [[ATMP87]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP86]], label [[ATOMIC_CONT89:%.*]], label [[ATOMIC_EXIT94:%.*]]
// CHK-CXX:       atomic_cont89:
// CHK-CXX-NEXT:    [[TMP66:%.*]] = phi i16 [ [[ATOMIC_LOAD84]], [[ATOMIC_EXIT83]] ], [ [[TMP69:%.*]], [[ATOMIC_CMP91:%.*]] ]
// CHK-CXX-NEXT:    store i16 [[TMP64]], i16* [[ATOMIC_TEMP90]], align 2
// CHK-CXX-NEXT:    [[TMP67:%.*]] = load i16, i16* [[ATOMIC_TEMP90]], align 2
// CHK-CXX-NEXT:    [[TMP68:%.*]] = cmpxchg i16* [[X]], i16 [[TMP66]], i16 [[TMP67]] monotonic monotonic, align 2
// CHK-CXX-NEXT:    [[TMP69]] = extractvalue { i16, i1 } [[TMP68]], 0
// CHK-CXX-NEXT:    [[TMP70:%.*]] = extractvalue { i16, i1 } [[TMP68]], 1
// CHK-CXX-NEXT:    br i1 [[TMP70]], label [[ATOMIC_EXIT94]], label [[ATOMIC_CMP91]]
// CHK-CXX:       atomic_cmp91:
// CHK-CXX-NEXT:    store i16 [[TMP69]], i16* [[ATMP85]], align 2
// CHK-CXX-NEXT:    [[CMP92:%.*]] = icmp eq i16 [[TMP69]], [[TMP65]]
// CHK-CXX-NEXT:    [[FROMBOOL93:%.*]] = zext i1 [[CMP92]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL93]], i8* [[ATMP87]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP92]], label [[ATOMIC_CONT89]], label [[ATOMIC_EXIT94]]
// CHK-CXX:       atomic_exit94:
// CHK-CXX-NEXT:    [[TMP71:%.*]] = load i16, i16* [[ATMP85]], align 2
// CHK-CXX-NEXT:    [[TMP72:%.*]] = load i8, i8* [[ATMP87]], align 1
// CHK-CXX-NEXT:    store i16 [[TMP71]], i16* [[V]], align 2
// CHK-CXX-NEXT:    [[TMP73:%.*]] = load i16, i16* [[D]], align 2
// CHK-CXX-NEXT:    [[TMP74:%.*]] = load i16, i16* [[E]], align 2
// CHK-CXX-NEXT:    [[ATOMIC_LOAD95:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-CXX-NEXT:    store i16 [[ATOMIC_LOAD95]], i16* [[ATMP96]], align 2
// CHK-CXX-NEXT:    [[CMP97:%.*]] = icmp eq i16 [[ATOMIC_LOAD95]], [[TMP74]]
// CHK-CXX-NEXT:    [[FROMBOOL99:%.*]] = zext i1 [[CMP97]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL99]], i8* [[ATMP98]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP97]], label [[ATOMIC_CONT100:%.*]], label [[ATOMIC_EXIT106:%.*]]
// CHK-CXX:       atomic_cont100:
// CHK-CXX-NEXT:    [[TMP75:%.*]] = phi i16 [ [[ATOMIC_LOAD95]], [[ATOMIC_EXIT94]] ], [ [[TMP78:%.*]], [[ATOMIC_CMP103:%.*]] ]
// CHK-CXX-NEXT:    store i16 [[TMP73]], i16* [[ATOMIC_TEMP101]], align 2
// CHK-CXX-NEXT:    [[TMP76:%.*]] = load i16, i16* [[ATOMIC_TEMP101]], align 2
// CHK-CXX-NEXT:    [[TMP77:%.*]] = cmpxchg i16* [[X]], i16 [[TMP75]], i16 [[TMP76]] monotonic monotonic, align 2
// CHK-CXX-NEXT:    [[TMP78]] = extractvalue { i16, i1 } [[TMP77]], 0
// CHK-CXX-NEXT:    [[TMP79:%.*]] = extractvalue { i16, i1 } [[TMP77]], 1
// CHK-CXX-NEXT:    br i1 [[TMP79]], label [[ATOMIC_UPD_EXIT102:%.*]], label [[ATOMIC_CMP103]]
// CHK-CXX:       atomic_upd_exit102:
// CHK-CXX-NEXT:    store i16 [[TMP73]], i16* [[ATMP96]], align 2
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT106]]
// CHK-CXX:       atomic_cmp103:
// CHK-CXX-NEXT:    store i16 [[TMP78]], i16* [[ATMP96]], align 2
// CHK-CXX-NEXT:    [[CMP104:%.*]] = icmp eq i16 [[TMP78]], [[TMP74]]
// CHK-CXX-NEXT:    [[FROMBOOL105:%.*]] = zext i1 [[CMP104]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL105]], i8* [[ATMP98]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP104]], label [[ATOMIC_CONT100]], label [[ATOMIC_EXIT106]]
// CHK-CXX:       atomic_exit106:
// CHK-CXX-NEXT:    [[TMP80:%.*]] = load i16, i16* [[ATMP96]], align 2
// CHK-CXX-NEXT:    [[TMP81:%.*]] = load i8, i8* [[ATMP98]], align 1
// CHK-CXX-NEXT:    store i16 [[TMP80]], i16* [[V]], align 2
// CHK-CXX-NEXT:    [[TMP82:%.*]] = load i16, i16* [[D]], align 2
// CHK-CXX-NEXT:    [[TMP83:%.*]] = load i16, i16* [[E]], align 2
// CHK-CXX-NEXT:    [[ATOMIC_LOAD107:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-CXX-NEXT:    store i16 [[ATOMIC_LOAD107]], i16* [[ATMP108]], align 2
// CHK-CXX-NEXT:    [[CMP109:%.*]] = icmp eq i16 [[ATOMIC_LOAD107]], [[TMP83]]
// CHK-CXX-NEXT:    [[FROMBOOL111:%.*]] = zext i1 [[CMP109]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL111]], i8* [[ATMP110]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP109]], label [[ATOMIC_CONT112:%.*]], label [[ATOMIC_EXIT118:%.*]]
// CHK-CXX:       atomic_cont112:
// CHK-CXX-NEXT:    [[TMP84:%.*]] = phi i16 [ [[ATOMIC_LOAD107]], [[ATOMIC_EXIT106]] ], [ [[TMP87:%.*]], [[ATOMIC_CMP115:%.*]] ]
// CHK-CXX-NEXT:    store i16 [[TMP82]], i16* [[ATOMIC_TEMP113]], align 2
// CHK-CXX-NEXT:    [[TMP85:%.*]] = load i16, i16* [[ATOMIC_TEMP113]], align 2
// CHK-CXX-NEXT:    [[TMP86:%.*]] = cmpxchg i16* [[X]], i16 [[TMP84]], i16 [[TMP85]] monotonic monotonic, align 2
// CHK-CXX-NEXT:    [[TMP87]] = extractvalue { i16, i1 } [[TMP86]], 0
// CHK-CXX-NEXT:    [[TMP88:%.*]] = extractvalue { i16, i1 } [[TMP86]], 1
// CHK-CXX-NEXT:    br i1 [[TMP88]], label [[ATOMIC_UPD_EXIT114:%.*]], label [[ATOMIC_CMP115]]
// CHK-CXX:       atomic_upd_exit114:
// CHK-CXX-NEXT:    store i16 [[TMP82]], i16* [[ATMP108]], align 2
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT118]]
// CHK-CXX:       atomic_cmp115:
// CHK-CXX-NEXT:    store i16 [[TMP87]], i16* [[ATMP108]], align 2
// CHK-CXX-NEXT:    [[CMP116:%.*]] = icmp eq i16 [[TMP87]], [[TMP83]]
// CHK-CXX-NEXT:    [[FROMBOOL117:%.*]] = zext i1 [[CMP116]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL117]], i8* [[ATMP110]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP116]], label [[ATOMIC_CONT112]], label [[ATOMIC_EXIT118]]
// CHK-CXX:       atomic_exit118:
// CHK-CXX-NEXT:    [[TMP89:%.*]] = load i16, i16* [[ATMP108]], align 2
// CHK-CXX-NEXT:    [[TMP90:%.*]] = load i8, i8* [[ATMP110]], align 1
// CHK-CXX-NEXT:    [[TMP91:%.*]] = trunc i8 [[TMP90]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP91]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-CXX:       atomic_capture:
// CHK-CXX-NEXT:    store i16 [[TMP89]], i16* [[V]], align 2
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-CXX:       atomic_capture_cont:
// CHK-CXX-NEXT:    [[TMP92:%.*]] = load i16, i16* [[D]], align 2
// CHK-CXX-NEXT:    [[TMP93:%.*]] = load i16, i16* [[E]], align 2
// CHK-CXX-NEXT:    [[ATOMIC_LOAD119:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-CXX-NEXT:    store i16 [[ATOMIC_LOAD119]], i16* [[ATMP120]], align 2
// CHK-CXX-NEXT:    [[CMP121:%.*]] = icmp eq i16 [[ATOMIC_LOAD119]], [[TMP93]]
// CHK-CXX-NEXT:    [[FROMBOOL123:%.*]] = zext i1 [[CMP121]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL123]], i8* [[ATMP122]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP121]], label [[ATOMIC_CONT124:%.*]], label [[ATOMIC_EXIT129:%.*]]
// CHK-CXX:       atomic_cont124:
// CHK-CXX-NEXT:    [[TMP94:%.*]] = phi i16 [ [[ATOMIC_LOAD119]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP97:%.*]], [[ATOMIC_CMP126:%.*]] ]
// CHK-CXX-NEXT:    store i16 [[TMP92]], i16* [[ATOMIC_TEMP125]], align 2
// CHK-CXX-NEXT:    [[TMP95:%.*]] = load i16, i16* [[ATOMIC_TEMP125]], align 2
// CHK-CXX-NEXT:    [[TMP96:%.*]] = cmpxchg i16* [[X]], i16 [[TMP94]], i16 [[TMP95]] monotonic monotonic, align 2
// CHK-CXX-NEXT:    [[TMP97]] = extractvalue { i16, i1 } [[TMP96]], 0
// CHK-CXX-NEXT:    [[TMP98:%.*]] = extractvalue { i16, i1 } [[TMP96]], 1
// CHK-CXX-NEXT:    br i1 [[TMP98]], label [[ATOMIC_EXIT129]], label [[ATOMIC_CMP126]]
// CHK-CXX:       atomic_cmp126:
// CHK-CXX-NEXT:    store i16 [[TMP97]], i16* [[ATMP120]], align 2
// CHK-CXX-NEXT:    [[CMP127:%.*]] = icmp eq i16 [[TMP97]], [[TMP93]]
// CHK-CXX-NEXT:    [[FROMBOOL128:%.*]] = zext i1 [[CMP127]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL128]], i8* [[ATMP122]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP127]], label [[ATOMIC_CONT124]], label [[ATOMIC_EXIT129]]
// CHK-CXX:       atomic_exit129:
// CHK-CXX-NEXT:    [[TMP99:%.*]] = load i16, i16* [[ATMP120]], align 2
// CHK-CXX-NEXT:    [[TMP100:%.*]] = load i8, i8* [[ATMP122]], align 1
// CHK-CXX-NEXT:    [[CONV:%.*]] = zext i8 [[TMP100]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP101:%.*]] = load i16, i16* [[D]], align 2
// CHK-CXX-NEXT:    [[TMP102:%.*]] = load i16, i16* [[E]], align 2
// CHK-CXX-NEXT:    [[ATOMIC_LOAD130:%.*]] = load atomic i16, i16* [[X]] monotonic, align 2
// CHK-CXX-NEXT:    store i16 [[ATOMIC_LOAD130]], i16* [[ATMP131]], align 2
// CHK-CXX-NEXT:    [[CMP132:%.*]] = icmp eq i16 [[ATOMIC_LOAD130]], [[TMP102]]
// CHK-CXX-NEXT:    [[FROMBOOL134:%.*]] = zext i1 [[CMP132]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL134]], i8* [[ATMP133]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP132]], label [[ATOMIC_CONT135:%.*]], label [[ATOMIC_EXIT140:%.*]]
// CHK-CXX:       atomic_cont135:
// CHK-CXX-NEXT:    [[TMP103:%.*]] = phi i16 [ [[ATOMIC_LOAD130]], [[ATOMIC_EXIT129]] ], [ [[TMP106:%.*]], [[ATOMIC_CMP137:%.*]] ]
// CHK-CXX-NEXT:    store i16 [[TMP101]], i16* [[ATOMIC_TEMP136]], align 2
// CHK-CXX-NEXT:    [[TMP104:%.*]] = load i16, i16* [[ATOMIC_TEMP136]], align 2
// CHK-CXX-NEXT:    [[TMP105:%.*]] = cmpxchg i16* [[X]], i16 [[TMP103]], i16 [[TMP104]] monotonic monotonic, align 2
// CHK-CXX-NEXT:    [[TMP106]] = extractvalue { i16, i1 } [[TMP105]], 0
// CHK-CXX-NEXT:    [[TMP107:%.*]] = extractvalue { i16, i1 } [[TMP105]], 1
// CHK-CXX-NEXT:    br i1 [[TMP107]], label [[ATOMIC_EXIT140]], label [[ATOMIC_CMP137]]
// CHK-CXX:       atomic_cmp137:
// CHK-CXX-NEXT:    store i16 [[TMP106]], i16* [[ATMP131]], align 2
// CHK-CXX-NEXT:    [[CMP138:%.*]] = icmp eq i16 [[TMP106]], [[TMP102]]
// CHK-CXX-NEXT:    [[FROMBOOL139:%.*]] = zext i1 [[CMP138]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL139]], i8* [[ATMP133]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP138]], label [[ATOMIC_CONT135]], label [[ATOMIC_EXIT140]]
// CHK-CXX:       atomic_exit140:
// CHK-CXX-NEXT:    [[TMP108:%.*]] = load i16, i16* [[ATMP131]], align 2
// CHK-CXX-NEXT:    [[TMP109:%.*]] = load i8, i8* [[ATMP133]], align 1
// CHK-CXX-NEXT:    [[CONV141:%.*]] = zext i8 [[TMP109]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV141]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP110:%.*]] = trunc i8 [[TMP109]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP110]], label [[ATOMIC_CAPTURE_CONT143:%.*]], label [[ATOMIC_CAPTURE142:%.*]]
// CHK-CXX:       atomic_capture142:
// CHK-CXX-NEXT:    store i16 [[TMP108]], i16* [[V]], align 2
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT143]]
// CHK-CXX:       atomic_capture_cont143:
// CHK-CXX-NEXT:    ret void
//
void test_unsigned_short() {
    // One of each form with 'unsigned short'.
    unsigned short x, expr, d, e, v;
    int r;

    #pragma omp atomic compare capture
    { v = x; if (expr < x) { x = expr; } } // MIN

    #pragma omp atomic compare capture
    { if (expr < x) { x = expr; } v = x; } // MIN

    #pragma omp atomic compare capture
    { v = x; if (expr > x) { x = expr; } } // MAX

    #pragma omp atomic compare capture
    { if (expr > x) { x = expr; } v = x; } // MAX

    #pragma omp atomic compare capture
    { v = x; if (x < expr) { x = expr; } } // MAX

    #pragma omp atomic compare capture
    { if (x < expr) { x = expr; } v = x; } // MAX

    #pragma omp atomic compare capture
    { v = x; if (x > expr) { x = expr; } } // MIN

    #pragma omp atomic compare capture
    { if (x > expr) { x = expr; } v = x; } // MIN

    #pragma omp atomic compare capture
    { v = x; if (x == e) { x = d; } }

    #pragma omp atomic compare capture
    { if (x == e) { x = d; } v = x; }

    #pragma omp atomic compare capture
    if (x == e) { x = d; } else { v = x; }

    #pragma omp atomic compare capture
    { r = x == e; if(r) { x = d; } }

    #pragma omp atomic compare capture
    { r = x == e; if(r) { x = d; } else { v = x; } }
}

// CHK-C-LABEL: @test_double(
// CHK-C-NEXT:  entry:
// CHK-C-NEXT:    [[X:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[EXPR:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[D:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[E:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[V:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[R:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[TMP:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP5:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP7:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP10:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP16:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP18:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP21:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP27:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP29:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP32:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP39:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP41:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP44:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP50:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP52:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP55:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP62:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP64:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP67:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP73:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP75:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP78:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP85:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP87:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP90:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP96:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP98:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP101:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP108:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP110:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP113:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP120:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP122:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP125:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP131:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[ATMP133:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP136:%.*]] = alloca double, align 8
// CHK-C-NEXT:    [[TMP0:%.*]] = load double, double* [[EXPR]], align 8
// CHK-C-NEXT:    [[TMP1:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i64, i64* [[TMP1]] monotonic, align 8
// CHK-C-NEXT:    [[TMP2:%.*]] = bitcast i64 [[ATOMIC_LOAD]] to double
// CHK-C-NEXT:    store double [[TMP2]], double* [[TMP]], align 8
// CHK-C-NEXT:    [[CMP:%.*]] = fcmp ogt double [[TMP2]], [[TMP0]]
// CHK-C-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-C:       atomic_cont:
// CHK-C-NEXT:    [[TMP3:%.*]] = phi i64 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP9:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-C-NEXT:    [[TMP4:%.*]] = bitcast double* [[ATOMIC_TEMP]] to i64*
// CHK-C-NEXT:    [[TMP5:%.*]] = bitcast double [[TMP0]] to i64
// CHK-C-NEXT:    store i64 [[TMP5]], i64* [[TMP4]], align 8
// CHK-C-NEXT:    [[TMP6:%.*]] = load i64, i64* [[TMP4]], align 8
// CHK-C-NEXT:    [[TMP7:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[TMP8:%.*]] = cmpxchg i64* [[TMP7]], i64 [[TMP3]], i64 [[TMP6]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP9]] = extractvalue { i64, i1 } [[TMP8]], 0
// CHK-C-NEXT:    [[TMP10:%.*]] = extractvalue { i64, i1 } [[TMP8]], 1
// CHK-C-NEXT:    br i1 [[TMP10]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-C:       atomic_cmp:
// CHK-C-NEXT:    [[TMP11:%.*]] = bitcast i64 [[TMP9]] to double
// CHK-C-NEXT:    store double [[TMP11]], double* [[TMP]], align 8
// CHK-C-NEXT:    [[CMP2:%.*]] = fcmp ogt double [[TMP11]], [[TMP0]]
// CHK-C-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[CMP2]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL3]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP2]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-C:       atomic_exit:
// CHK-C-NEXT:    [[TMP12:%.*]] = load double, double* [[TMP]], align 8
// CHK-C-NEXT:    [[TMP13:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-C-NEXT:    store double [[TMP12]], double* [[V]], align 8
// CHK-C-NEXT:    [[TMP14:%.*]] = load double, double* [[EXPR]], align 8
// CHK-C-NEXT:    [[TMP15:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD4:%.*]] = load atomic i64, i64* [[TMP15]] monotonic, align 8
// CHK-C-NEXT:    [[TMP16:%.*]] = bitcast i64 [[ATOMIC_LOAD4]] to double
// CHK-C-NEXT:    store double [[TMP16]], double* [[ATMP5]], align 8
// CHK-C-NEXT:    [[CMP6:%.*]] = fcmp ogt double [[TMP16]], [[TMP14]]
// CHK-C-NEXT:    [[FROMBOOL8:%.*]] = zext i1 [[CMP6]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL8]], i8* [[ATMP7]], align 1
// CHK-C-NEXT:    br i1 [[CMP6]], label [[ATOMIC_CONT9:%.*]], label [[ATOMIC_EXIT14:%.*]]
// CHK-C:       atomic_cont9:
// CHK-C-NEXT:    [[TMP17:%.*]] = phi i64 [ [[ATOMIC_LOAD4]], [[ATOMIC_EXIT]] ], [ [[TMP23:%.*]], [[ATOMIC_CMP11:%.*]] ]
// CHK-C-NEXT:    [[TMP18:%.*]] = bitcast double* [[ATOMIC_TEMP10]] to i64*
// CHK-C-NEXT:    [[TMP19:%.*]] = bitcast double [[TMP14]] to i64
// CHK-C-NEXT:    store i64 [[TMP19]], i64* [[TMP18]], align 8
// CHK-C-NEXT:    [[TMP20:%.*]] = load i64, i64* [[TMP18]], align 8
// CHK-C-NEXT:    [[TMP21:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[TMP22:%.*]] = cmpxchg i64* [[TMP21]], i64 [[TMP17]], i64 [[TMP20]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP23]] = extractvalue { i64, i1 } [[TMP22]], 0
// CHK-C-NEXT:    [[TMP24:%.*]] = extractvalue { i64, i1 } [[TMP22]], 1
// CHK-C-NEXT:    br i1 [[TMP24]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP11]]
// CHK-C:       atomic_upd_exit:
// CHK-C-NEXT:    store double [[TMP14]], double* [[ATMP5]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_EXIT14]]
// CHK-C:       atomic_cmp11:
// CHK-C-NEXT:    [[TMP25:%.*]] = bitcast i64 [[TMP23]] to double
// CHK-C-NEXT:    store double [[TMP25]], double* [[ATMP5]], align 8
// CHK-C-NEXT:    [[CMP12:%.*]] = fcmp ogt double [[TMP25]], [[TMP14]]
// CHK-C-NEXT:    [[FROMBOOL13:%.*]] = zext i1 [[CMP12]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL13]], i8* [[ATMP7]], align 1
// CHK-C-NEXT:    br i1 [[CMP12]], label [[ATOMIC_CONT9]], label [[ATOMIC_EXIT14]]
// CHK-C:       atomic_exit14:
// CHK-C-NEXT:    [[TMP26:%.*]] = load double, double* [[ATMP5]], align 8
// CHK-C-NEXT:    [[TMP27:%.*]] = load i8, i8* [[ATMP7]], align 1
// CHK-C-NEXT:    store double [[TMP26]], double* [[V]], align 8
// CHK-C-NEXT:    [[TMP28:%.*]] = load double, double* [[EXPR]], align 8
// CHK-C-NEXT:    [[TMP29:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD15:%.*]] = load atomic i64, i64* [[TMP29]] monotonic, align 8
// CHK-C-NEXT:    [[TMP30:%.*]] = bitcast i64 [[ATOMIC_LOAD15]] to double
// CHK-C-NEXT:    store double [[TMP30]], double* [[ATMP16]], align 8
// CHK-C-NEXT:    [[CMP17:%.*]] = fcmp olt double [[TMP30]], [[TMP28]]
// CHK-C-NEXT:    [[FROMBOOL19:%.*]] = zext i1 [[CMP17]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL19]], i8* [[ATMP18]], align 1
// CHK-C-NEXT:    br i1 [[CMP17]], label [[ATOMIC_CONT20:%.*]], label [[ATOMIC_EXIT25:%.*]]
// CHK-C:       atomic_cont20:
// CHK-C-NEXT:    [[TMP31:%.*]] = phi i64 [ [[ATOMIC_LOAD15]], [[ATOMIC_EXIT14]] ], [ [[TMP37:%.*]], [[ATOMIC_CMP22:%.*]] ]
// CHK-C-NEXT:    [[TMP32:%.*]] = bitcast double* [[ATOMIC_TEMP21]] to i64*
// CHK-C-NEXT:    [[TMP33:%.*]] = bitcast double [[TMP28]] to i64
// CHK-C-NEXT:    store i64 [[TMP33]], i64* [[TMP32]], align 8
// CHK-C-NEXT:    [[TMP34:%.*]] = load i64, i64* [[TMP32]], align 8
// CHK-C-NEXT:    [[TMP35:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[TMP36:%.*]] = cmpxchg i64* [[TMP35]], i64 [[TMP31]], i64 [[TMP34]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP37]] = extractvalue { i64, i1 } [[TMP36]], 0
// CHK-C-NEXT:    [[TMP38:%.*]] = extractvalue { i64, i1 } [[TMP36]], 1
// CHK-C-NEXT:    br i1 [[TMP38]], label [[ATOMIC_EXIT25]], label [[ATOMIC_CMP22]]
// CHK-C:       atomic_cmp22:
// CHK-C-NEXT:    [[TMP39:%.*]] = bitcast i64 [[TMP37]] to double
// CHK-C-NEXT:    store double [[TMP39]], double* [[ATMP16]], align 8
// CHK-C-NEXT:    [[CMP23:%.*]] = fcmp olt double [[TMP39]], [[TMP28]]
// CHK-C-NEXT:    [[FROMBOOL24:%.*]] = zext i1 [[CMP23]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL24]], i8* [[ATMP18]], align 1
// CHK-C-NEXT:    br i1 [[CMP23]], label [[ATOMIC_CONT20]], label [[ATOMIC_EXIT25]]
// CHK-C:       atomic_exit25:
// CHK-C-NEXT:    [[TMP40:%.*]] = load double, double* [[ATMP16]], align 8
// CHK-C-NEXT:    [[TMP41:%.*]] = load i8, i8* [[ATMP18]], align 1
// CHK-C-NEXT:    store double [[TMP40]], double* [[V]], align 8
// CHK-C-NEXT:    [[TMP42:%.*]] = load double, double* [[EXPR]], align 8
// CHK-C-NEXT:    [[TMP43:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD26:%.*]] = load atomic i64, i64* [[TMP43]] monotonic, align 8
// CHK-C-NEXT:    [[TMP44:%.*]] = bitcast i64 [[ATOMIC_LOAD26]] to double
// CHK-C-NEXT:    store double [[TMP44]], double* [[ATMP27]], align 8
// CHK-C-NEXT:    [[CMP28:%.*]] = fcmp olt double [[TMP44]], [[TMP42]]
// CHK-C-NEXT:    [[FROMBOOL30:%.*]] = zext i1 [[CMP28]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL30]], i8* [[ATMP29]], align 1
// CHK-C-NEXT:    br i1 [[CMP28]], label [[ATOMIC_CONT31:%.*]], label [[ATOMIC_EXIT37:%.*]]
// CHK-C:       atomic_cont31:
// CHK-C-NEXT:    [[TMP45:%.*]] = phi i64 [ [[ATOMIC_LOAD26]], [[ATOMIC_EXIT25]] ], [ [[TMP51:%.*]], [[ATOMIC_CMP34:%.*]] ]
// CHK-C-NEXT:    [[TMP46:%.*]] = bitcast double* [[ATOMIC_TEMP32]] to i64*
// CHK-C-NEXT:    [[TMP47:%.*]] = bitcast double [[TMP42]] to i64
// CHK-C-NEXT:    store i64 [[TMP47]], i64* [[TMP46]], align 8
// CHK-C-NEXT:    [[TMP48:%.*]] = load i64, i64* [[TMP46]], align 8
// CHK-C-NEXT:    [[TMP49:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[TMP50:%.*]] = cmpxchg i64* [[TMP49]], i64 [[TMP45]], i64 [[TMP48]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP51]] = extractvalue { i64, i1 } [[TMP50]], 0
// CHK-C-NEXT:    [[TMP52:%.*]] = extractvalue { i64, i1 } [[TMP50]], 1
// CHK-C-NEXT:    br i1 [[TMP52]], label [[ATOMIC_UPD_EXIT33:%.*]], label [[ATOMIC_CMP34]]
// CHK-C:       atomic_upd_exit33:
// CHK-C-NEXT:    store double [[TMP42]], double* [[ATMP27]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_EXIT37]]
// CHK-C:       atomic_cmp34:
// CHK-C-NEXT:    [[TMP53:%.*]] = bitcast i64 [[TMP51]] to double
// CHK-C-NEXT:    store double [[TMP53]], double* [[ATMP27]], align 8
// CHK-C-NEXT:    [[CMP35:%.*]] = fcmp olt double [[TMP53]], [[TMP42]]
// CHK-C-NEXT:    [[FROMBOOL36:%.*]] = zext i1 [[CMP35]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL36]], i8* [[ATMP29]], align 1
// CHK-C-NEXT:    br i1 [[CMP35]], label [[ATOMIC_CONT31]], label [[ATOMIC_EXIT37]]
// CHK-C:       atomic_exit37:
// CHK-C-NEXT:    [[TMP54:%.*]] = load double, double* [[ATMP27]], align 8
// CHK-C-NEXT:    [[TMP55:%.*]] = load i8, i8* [[ATMP29]], align 1
// CHK-C-NEXT:    store double [[TMP54]], double* [[V]], align 8
// CHK-C-NEXT:    [[TMP56:%.*]] = load double, double* [[EXPR]], align 8
// CHK-C-NEXT:    [[TMP57:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD38:%.*]] = load atomic i64, i64* [[TMP57]] monotonic, align 8
// CHK-C-NEXT:    [[TMP58:%.*]] = bitcast i64 [[ATOMIC_LOAD38]] to double
// CHK-C-NEXT:    store double [[TMP58]], double* [[ATMP39]], align 8
// CHK-C-NEXT:    [[CMP40:%.*]] = fcmp olt double [[TMP58]], [[TMP56]]
// CHK-C-NEXT:    [[FROMBOOL42:%.*]] = zext i1 [[CMP40]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL42]], i8* [[ATMP41]], align 1
// CHK-C-NEXT:    br i1 [[CMP40]], label [[ATOMIC_CONT43:%.*]], label [[ATOMIC_EXIT48:%.*]]
// CHK-C:       atomic_cont43:
// CHK-C-NEXT:    [[TMP59:%.*]] = phi i64 [ [[ATOMIC_LOAD38]], [[ATOMIC_EXIT37]] ], [ [[TMP65:%.*]], [[ATOMIC_CMP45:%.*]] ]
// CHK-C-NEXT:    [[TMP60:%.*]] = bitcast double* [[ATOMIC_TEMP44]] to i64*
// CHK-C-NEXT:    [[TMP61:%.*]] = bitcast double [[TMP56]] to i64
// CHK-C-NEXT:    store i64 [[TMP61]], i64* [[TMP60]], align 8
// CHK-C-NEXT:    [[TMP62:%.*]] = load i64, i64* [[TMP60]], align 8
// CHK-C-NEXT:    [[TMP63:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[TMP64:%.*]] = cmpxchg i64* [[TMP63]], i64 [[TMP59]], i64 [[TMP62]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP65]] = extractvalue { i64, i1 } [[TMP64]], 0
// CHK-C-NEXT:    [[TMP66:%.*]] = extractvalue { i64, i1 } [[TMP64]], 1
// CHK-C-NEXT:    br i1 [[TMP66]], label [[ATOMIC_EXIT48]], label [[ATOMIC_CMP45]]
// CHK-C:       atomic_cmp45:
// CHK-C-NEXT:    [[TMP67:%.*]] = bitcast i64 [[TMP65]] to double
// CHK-C-NEXT:    store double [[TMP67]], double* [[ATMP39]], align 8
// CHK-C-NEXT:    [[CMP46:%.*]] = fcmp olt double [[TMP67]], [[TMP56]]
// CHK-C-NEXT:    [[FROMBOOL47:%.*]] = zext i1 [[CMP46]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL47]], i8* [[ATMP41]], align 1
// CHK-C-NEXT:    br i1 [[CMP46]], label [[ATOMIC_CONT43]], label [[ATOMIC_EXIT48]]
// CHK-C:       atomic_exit48:
// CHK-C-NEXT:    [[TMP68:%.*]] = load double, double* [[ATMP39]], align 8
// CHK-C-NEXT:    [[TMP69:%.*]] = load i8, i8* [[ATMP41]], align 1
// CHK-C-NEXT:    store double [[TMP68]], double* [[V]], align 8
// CHK-C-NEXT:    [[TMP70:%.*]] = load double, double* [[EXPR]], align 8
// CHK-C-NEXT:    [[TMP71:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD49:%.*]] = load atomic i64, i64* [[TMP71]] monotonic, align 8
// CHK-C-NEXT:    [[TMP72:%.*]] = bitcast i64 [[ATOMIC_LOAD49]] to double
// CHK-C-NEXT:    store double [[TMP72]], double* [[ATMP50]], align 8
// CHK-C-NEXT:    [[CMP51:%.*]] = fcmp olt double [[TMP72]], [[TMP70]]
// CHK-C-NEXT:    [[FROMBOOL53:%.*]] = zext i1 [[CMP51]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL53]], i8* [[ATMP52]], align 1
// CHK-C-NEXT:    br i1 [[CMP51]], label [[ATOMIC_CONT54:%.*]], label [[ATOMIC_EXIT60:%.*]]
// CHK-C:       atomic_cont54:
// CHK-C-NEXT:    [[TMP73:%.*]] = phi i64 [ [[ATOMIC_LOAD49]], [[ATOMIC_EXIT48]] ], [ [[TMP79:%.*]], [[ATOMIC_CMP57:%.*]] ]
// CHK-C-NEXT:    [[TMP74:%.*]] = bitcast double* [[ATOMIC_TEMP55]] to i64*
// CHK-C-NEXT:    [[TMP75:%.*]] = bitcast double [[TMP70]] to i64
// CHK-C-NEXT:    store i64 [[TMP75]], i64* [[TMP74]], align 8
// CHK-C-NEXT:    [[TMP76:%.*]] = load i64, i64* [[TMP74]], align 8
// CHK-C-NEXT:    [[TMP77:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[TMP78:%.*]] = cmpxchg i64* [[TMP77]], i64 [[TMP73]], i64 [[TMP76]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP79]] = extractvalue { i64, i1 } [[TMP78]], 0
// CHK-C-NEXT:    [[TMP80:%.*]] = extractvalue { i64, i1 } [[TMP78]], 1
// CHK-C-NEXT:    br i1 [[TMP80]], label [[ATOMIC_UPD_EXIT56:%.*]], label [[ATOMIC_CMP57]]
// CHK-C:       atomic_upd_exit56:
// CHK-C-NEXT:    store double [[TMP70]], double* [[ATMP50]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_EXIT60]]
// CHK-C:       atomic_cmp57:
// CHK-C-NEXT:    [[TMP81:%.*]] = bitcast i64 [[TMP79]] to double
// CHK-C-NEXT:    store double [[TMP81]], double* [[ATMP50]], align 8
// CHK-C-NEXT:    [[CMP58:%.*]] = fcmp olt double [[TMP81]], [[TMP70]]
// CHK-C-NEXT:    [[FROMBOOL59:%.*]] = zext i1 [[CMP58]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL59]], i8* [[ATMP52]], align 1
// CHK-C-NEXT:    br i1 [[CMP58]], label [[ATOMIC_CONT54]], label [[ATOMIC_EXIT60]]
// CHK-C:       atomic_exit60:
// CHK-C-NEXT:    [[TMP82:%.*]] = load double, double* [[ATMP50]], align 8
// CHK-C-NEXT:    [[TMP83:%.*]] = load i8, i8* [[ATMP52]], align 1
// CHK-C-NEXT:    store double [[TMP82]], double* [[V]], align 8
// CHK-C-NEXT:    [[TMP84:%.*]] = load double, double* [[EXPR]], align 8
// CHK-C-NEXT:    [[TMP85:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD61:%.*]] = load atomic i64, i64* [[TMP85]] monotonic, align 8
// CHK-C-NEXT:    [[TMP86:%.*]] = bitcast i64 [[ATOMIC_LOAD61]] to double
// CHK-C-NEXT:    store double [[TMP86]], double* [[ATMP62]], align 8
// CHK-C-NEXT:    [[CMP63:%.*]] = fcmp ogt double [[TMP86]], [[TMP84]]
// CHK-C-NEXT:    [[FROMBOOL65:%.*]] = zext i1 [[CMP63]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL65]], i8* [[ATMP64]], align 1
// CHK-C-NEXT:    br i1 [[CMP63]], label [[ATOMIC_CONT66:%.*]], label [[ATOMIC_EXIT71:%.*]]
// CHK-C:       atomic_cont66:
// CHK-C-NEXT:    [[TMP87:%.*]] = phi i64 [ [[ATOMIC_LOAD61]], [[ATOMIC_EXIT60]] ], [ [[TMP93:%.*]], [[ATOMIC_CMP68:%.*]] ]
// CHK-C-NEXT:    [[TMP88:%.*]] = bitcast double* [[ATOMIC_TEMP67]] to i64*
// CHK-C-NEXT:    [[TMP89:%.*]] = bitcast double [[TMP84]] to i64
// CHK-C-NEXT:    store i64 [[TMP89]], i64* [[TMP88]], align 8
// CHK-C-NEXT:    [[TMP90:%.*]] = load i64, i64* [[TMP88]], align 8
// CHK-C-NEXT:    [[TMP91:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[TMP92:%.*]] = cmpxchg i64* [[TMP91]], i64 [[TMP87]], i64 [[TMP90]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP93]] = extractvalue { i64, i1 } [[TMP92]], 0
// CHK-C-NEXT:    [[TMP94:%.*]] = extractvalue { i64, i1 } [[TMP92]], 1
// CHK-C-NEXT:    br i1 [[TMP94]], label [[ATOMIC_EXIT71]], label [[ATOMIC_CMP68]]
// CHK-C:       atomic_cmp68:
// CHK-C-NEXT:    [[TMP95:%.*]] = bitcast i64 [[TMP93]] to double
// CHK-C-NEXT:    store double [[TMP95]], double* [[ATMP62]], align 8
// CHK-C-NEXT:    [[CMP69:%.*]] = fcmp ogt double [[TMP95]], [[TMP84]]
// CHK-C-NEXT:    [[FROMBOOL70:%.*]] = zext i1 [[CMP69]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL70]], i8* [[ATMP64]], align 1
// CHK-C-NEXT:    br i1 [[CMP69]], label [[ATOMIC_CONT66]], label [[ATOMIC_EXIT71]]
// CHK-C:       atomic_exit71:
// CHK-C-NEXT:    [[TMP96:%.*]] = load double, double* [[ATMP62]], align 8
// CHK-C-NEXT:    [[TMP97:%.*]] = load i8, i8* [[ATMP64]], align 1
// CHK-C-NEXT:    store double [[TMP96]], double* [[V]], align 8
// CHK-C-NEXT:    [[TMP98:%.*]] = load double, double* [[EXPR]], align 8
// CHK-C-NEXT:    [[TMP99:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD72:%.*]] = load atomic i64, i64* [[TMP99]] monotonic, align 8
// CHK-C-NEXT:    [[TMP100:%.*]] = bitcast i64 [[ATOMIC_LOAD72]] to double
// CHK-C-NEXT:    store double [[TMP100]], double* [[ATMP73]], align 8
// CHK-C-NEXT:    [[CMP74:%.*]] = fcmp ogt double [[TMP100]], [[TMP98]]
// CHK-C-NEXT:    [[FROMBOOL76:%.*]] = zext i1 [[CMP74]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL76]], i8* [[ATMP75]], align 1
// CHK-C-NEXT:    br i1 [[CMP74]], label [[ATOMIC_CONT77:%.*]], label [[ATOMIC_EXIT83:%.*]]
// CHK-C:       atomic_cont77:
// CHK-C-NEXT:    [[TMP101:%.*]] = phi i64 [ [[ATOMIC_LOAD72]], [[ATOMIC_EXIT71]] ], [ [[TMP107:%.*]], [[ATOMIC_CMP80:%.*]] ]
// CHK-C-NEXT:    [[TMP102:%.*]] = bitcast double* [[ATOMIC_TEMP78]] to i64*
// CHK-C-NEXT:    [[TMP103:%.*]] = bitcast double [[TMP98]] to i64
// CHK-C-NEXT:    store i64 [[TMP103]], i64* [[TMP102]], align 8
// CHK-C-NEXT:    [[TMP104:%.*]] = load i64, i64* [[TMP102]], align 8
// CHK-C-NEXT:    [[TMP105:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[TMP106:%.*]] = cmpxchg i64* [[TMP105]], i64 [[TMP101]], i64 [[TMP104]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP107]] = extractvalue { i64, i1 } [[TMP106]], 0
// CHK-C-NEXT:    [[TMP108:%.*]] = extractvalue { i64, i1 } [[TMP106]], 1
// CHK-C-NEXT:    br i1 [[TMP108]], label [[ATOMIC_UPD_EXIT79:%.*]], label [[ATOMIC_CMP80]]
// CHK-C:       atomic_upd_exit79:
// CHK-C-NEXT:    store double [[TMP98]], double* [[ATMP73]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_EXIT83]]
// CHK-C:       atomic_cmp80:
// CHK-C-NEXT:    [[TMP109:%.*]] = bitcast i64 [[TMP107]] to double
// CHK-C-NEXT:    store double [[TMP109]], double* [[ATMP73]], align 8
// CHK-C-NEXT:    [[CMP81:%.*]] = fcmp ogt double [[TMP109]], [[TMP98]]
// CHK-C-NEXT:    [[FROMBOOL82:%.*]] = zext i1 [[CMP81]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL82]], i8* [[ATMP75]], align 1
// CHK-C-NEXT:    br i1 [[CMP81]], label [[ATOMIC_CONT77]], label [[ATOMIC_EXIT83]]
// CHK-C:       atomic_exit83:
// CHK-C-NEXT:    [[TMP110:%.*]] = load double, double* [[ATMP73]], align 8
// CHK-C-NEXT:    [[TMP111:%.*]] = load i8, i8* [[ATMP75]], align 1
// CHK-C-NEXT:    store double [[TMP110]], double* [[V]], align 8
// CHK-C-NEXT:    [[TMP112:%.*]] = load double, double* [[D]], align 8
// CHK-C-NEXT:    [[TMP113:%.*]] = load double, double* [[E]], align 8
// CHK-C-NEXT:    [[TMP114:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD84:%.*]] = load atomic i64, i64* [[TMP114]] monotonic, align 8
// CHK-C-NEXT:    [[TMP115:%.*]] = bitcast i64 [[ATOMIC_LOAD84]] to double
// CHK-C-NEXT:    store double [[TMP115]], double* [[ATMP85]], align 8
// CHK-C-NEXT:    [[TMP116:%.*]] = bitcast double [[TMP115]] to i64
// CHK-C-NEXT:    [[TMP117:%.*]] = bitcast double [[TMP113]] to i64
// CHK-C-NEXT:    [[CMP86:%.*]] = icmp eq i64 [[TMP116]], [[TMP117]]
// CHK-C-NEXT:    [[FROMBOOL88:%.*]] = zext i1 [[CMP86]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL88]], i8* [[ATMP87]], align 1
// CHK-C-NEXT:    br i1 [[CMP86]], label [[ATOMIC_CONT89:%.*]], label [[ATOMIC_EXIT94:%.*]]
// CHK-C:       atomic_cont89:
// CHK-C-NEXT:    [[TMP118:%.*]] = phi i64 [ [[ATOMIC_LOAD84]], [[ATOMIC_EXIT83]] ], [ [[TMP124:%.*]], [[ATOMIC_CMP91:%.*]] ]
// CHK-C-NEXT:    [[TMP119:%.*]] = bitcast double* [[ATOMIC_TEMP90]] to i64*
// CHK-C-NEXT:    [[TMP120:%.*]] = bitcast double [[TMP112]] to i64
// CHK-C-NEXT:    store i64 [[TMP120]], i64* [[TMP119]], align 8
// CHK-C-NEXT:    [[TMP121:%.*]] = load i64, i64* [[TMP119]], align 8
// CHK-C-NEXT:    [[TMP122:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[TMP123:%.*]] = cmpxchg i64* [[TMP122]], i64 [[TMP118]], i64 [[TMP121]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP124]] = extractvalue { i64, i1 } [[TMP123]], 0
// CHK-C-NEXT:    [[TMP125:%.*]] = extractvalue { i64, i1 } [[TMP123]], 1
// CHK-C-NEXT:    br i1 [[TMP125]], label [[ATOMIC_EXIT94]], label [[ATOMIC_CMP91]]
// CHK-C:       atomic_cmp91:
// CHK-C-NEXT:    [[TMP126:%.*]] = bitcast i64 [[TMP124]] to double
// CHK-C-NEXT:    store double [[TMP126]], double* [[ATMP85]], align 8
// CHK-C-NEXT:    [[TMP127:%.*]] = bitcast double [[TMP126]] to i64
// CHK-C-NEXT:    [[TMP128:%.*]] = bitcast double [[TMP113]] to i64
// CHK-C-NEXT:    [[CMP92:%.*]] = icmp eq i64 [[TMP127]], [[TMP128]]
// CHK-C-NEXT:    [[FROMBOOL93:%.*]] = zext i1 [[CMP92]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL93]], i8* [[ATMP87]], align 1
// CHK-C-NEXT:    br i1 [[CMP92]], label [[ATOMIC_CONT89]], label [[ATOMIC_EXIT94]]
// CHK-C:       atomic_exit94:
// CHK-C-NEXT:    [[TMP129:%.*]] = load double, double* [[ATMP85]], align 8
// CHK-C-NEXT:    [[TMP130:%.*]] = load i8, i8* [[ATMP87]], align 1
// CHK-C-NEXT:    store double [[TMP129]], double* [[V]], align 8
// CHK-C-NEXT:    [[TMP131:%.*]] = load double, double* [[D]], align 8
// CHK-C-NEXT:    [[TMP132:%.*]] = load double, double* [[E]], align 8
// CHK-C-NEXT:    [[TMP133:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD95:%.*]] = load atomic i64, i64* [[TMP133]] monotonic, align 8
// CHK-C-NEXT:    [[TMP134:%.*]] = bitcast i64 [[ATOMIC_LOAD95]] to double
// CHK-C-NEXT:    store double [[TMP134]], double* [[ATMP96]], align 8
// CHK-C-NEXT:    [[TMP135:%.*]] = bitcast double [[TMP134]] to i64
// CHK-C-NEXT:    [[TMP136:%.*]] = bitcast double [[TMP132]] to i64
// CHK-C-NEXT:    [[CMP97:%.*]] = icmp eq i64 [[TMP135]], [[TMP136]]
// CHK-C-NEXT:    [[FROMBOOL99:%.*]] = zext i1 [[CMP97]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL99]], i8* [[ATMP98]], align 1
// CHK-C-NEXT:    br i1 [[CMP97]], label [[ATOMIC_CONT100:%.*]], label [[ATOMIC_EXIT106:%.*]]
// CHK-C:       atomic_cont100:
// CHK-C-NEXT:    [[TMP137:%.*]] = phi i64 [ [[ATOMIC_LOAD95]], [[ATOMIC_EXIT94]] ], [ [[TMP143:%.*]], [[ATOMIC_CMP103:%.*]] ]
// CHK-C-NEXT:    [[TMP138:%.*]] = bitcast double* [[ATOMIC_TEMP101]] to i64*
// CHK-C-NEXT:    [[TMP139:%.*]] = bitcast double [[TMP131]] to i64
// CHK-C-NEXT:    store i64 [[TMP139]], i64* [[TMP138]], align 8
// CHK-C-NEXT:    [[TMP140:%.*]] = load i64, i64* [[TMP138]], align 8
// CHK-C-NEXT:    [[TMP141:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[TMP142:%.*]] = cmpxchg i64* [[TMP141]], i64 [[TMP137]], i64 [[TMP140]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP143]] = extractvalue { i64, i1 } [[TMP142]], 0
// CHK-C-NEXT:    [[TMP144:%.*]] = extractvalue { i64, i1 } [[TMP142]], 1
// CHK-C-NEXT:    br i1 [[TMP144]], label [[ATOMIC_UPD_EXIT102:%.*]], label [[ATOMIC_CMP103]]
// CHK-C:       atomic_upd_exit102:
// CHK-C-NEXT:    store double [[TMP131]], double* [[ATMP96]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_EXIT106]]
// CHK-C:       atomic_cmp103:
// CHK-C-NEXT:    [[TMP145:%.*]] = bitcast i64 [[TMP143]] to double
// CHK-C-NEXT:    store double [[TMP145]], double* [[ATMP96]], align 8
// CHK-C-NEXT:    [[TMP146:%.*]] = bitcast double [[TMP145]] to i64
// CHK-C-NEXT:    [[TMP147:%.*]] = bitcast double [[TMP132]] to i64
// CHK-C-NEXT:    [[CMP104:%.*]] = icmp eq i64 [[TMP146]], [[TMP147]]
// CHK-C-NEXT:    [[FROMBOOL105:%.*]] = zext i1 [[CMP104]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL105]], i8* [[ATMP98]], align 1
// CHK-C-NEXT:    br i1 [[CMP104]], label [[ATOMIC_CONT100]], label [[ATOMIC_EXIT106]]
// CHK-C:       atomic_exit106:
// CHK-C-NEXT:    [[TMP148:%.*]] = load double, double* [[ATMP96]], align 8
// CHK-C-NEXT:    [[TMP149:%.*]] = load i8, i8* [[ATMP98]], align 1
// CHK-C-NEXT:    store double [[TMP148]], double* [[V]], align 8
// CHK-C-NEXT:    [[TMP150:%.*]] = load double, double* [[D]], align 8
// CHK-C-NEXT:    [[TMP151:%.*]] = load double, double* [[E]], align 8
// CHK-C-NEXT:    [[TMP152:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD107:%.*]] = load atomic i64, i64* [[TMP152]] monotonic, align 8
// CHK-C-NEXT:    [[TMP153:%.*]] = bitcast i64 [[ATOMIC_LOAD107]] to double
// CHK-C-NEXT:    store double [[TMP153]], double* [[ATMP108]], align 8
// CHK-C-NEXT:    [[TMP154:%.*]] = bitcast double [[TMP153]] to i64
// CHK-C-NEXT:    [[TMP155:%.*]] = bitcast double [[TMP151]] to i64
// CHK-C-NEXT:    [[CMP109:%.*]] = icmp eq i64 [[TMP154]], [[TMP155]]
// CHK-C-NEXT:    [[FROMBOOL111:%.*]] = zext i1 [[CMP109]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL111]], i8* [[ATMP110]], align 1
// CHK-C-NEXT:    br i1 [[CMP109]], label [[ATOMIC_CONT112:%.*]], label [[ATOMIC_EXIT118:%.*]]
// CHK-C:       atomic_cont112:
// CHK-C-NEXT:    [[TMP156:%.*]] = phi i64 [ [[ATOMIC_LOAD107]], [[ATOMIC_EXIT106]] ], [ [[TMP162:%.*]], [[ATOMIC_CMP115:%.*]] ]
// CHK-C-NEXT:    [[TMP157:%.*]] = bitcast double* [[ATOMIC_TEMP113]] to i64*
// CHK-C-NEXT:    [[TMP158:%.*]] = bitcast double [[TMP150]] to i64
// CHK-C-NEXT:    store i64 [[TMP158]], i64* [[TMP157]], align 8
// CHK-C-NEXT:    [[TMP159:%.*]] = load i64, i64* [[TMP157]], align 8
// CHK-C-NEXT:    [[TMP160:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[TMP161:%.*]] = cmpxchg i64* [[TMP160]], i64 [[TMP156]], i64 [[TMP159]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP162]] = extractvalue { i64, i1 } [[TMP161]], 0
// CHK-C-NEXT:    [[TMP163:%.*]] = extractvalue { i64, i1 } [[TMP161]], 1
// CHK-C-NEXT:    br i1 [[TMP163]], label [[ATOMIC_UPD_EXIT114:%.*]], label [[ATOMIC_CMP115]]
// CHK-C:       atomic_upd_exit114:
// CHK-C-NEXT:    store double [[TMP150]], double* [[ATMP108]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_EXIT118]]
// CHK-C:       atomic_cmp115:
// CHK-C-NEXT:    [[TMP164:%.*]] = bitcast i64 [[TMP162]] to double
// CHK-C-NEXT:    store double [[TMP164]], double* [[ATMP108]], align 8
// CHK-C-NEXT:    [[TMP165:%.*]] = bitcast double [[TMP164]] to i64
// CHK-C-NEXT:    [[TMP166:%.*]] = bitcast double [[TMP151]] to i64
// CHK-C-NEXT:    [[CMP116:%.*]] = icmp eq i64 [[TMP165]], [[TMP166]]
// CHK-C-NEXT:    [[FROMBOOL117:%.*]] = zext i1 [[CMP116]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL117]], i8* [[ATMP110]], align 1
// CHK-C-NEXT:    br i1 [[CMP116]], label [[ATOMIC_CONT112]], label [[ATOMIC_EXIT118]]
// CHK-C:       atomic_exit118:
// CHK-C-NEXT:    [[TMP167:%.*]] = load double, double* [[ATMP108]], align 8
// CHK-C-NEXT:    [[TMP168:%.*]] = load i8, i8* [[ATMP110]], align 1
// CHK-C-NEXT:    [[TMP169:%.*]] = trunc i8 [[TMP168]] to i1
// CHK-C-NEXT:    br i1 [[TMP169]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-C:       atomic_capture:
// CHK-C-NEXT:    store double [[TMP167]], double* [[V]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-C:       atomic_capture_cont:
// CHK-C-NEXT:    [[TMP170:%.*]] = load double, double* [[D]], align 8
// CHK-C-NEXT:    [[TMP171:%.*]] = load double, double* [[E]], align 8
// CHK-C-NEXT:    [[TMP172:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD119:%.*]] = load atomic i64, i64* [[TMP172]] monotonic, align 8
// CHK-C-NEXT:    [[TMP173:%.*]] = bitcast i64 [[ATOMIC_LOAD119]] to double
// CHK-C-NEXT:    store double [[TMP173]], double* [[ATMP120]], align 8
// CHK-C-NEXT:    [[TMP174:%.*]] = bitcast double [[TMP173]] to i64
// CHK-C-NEXT:    [[TMP175:%.*]] = bitcast double [[TMP171]] to i64
// CHK-C-NEXT:    [[CMP121:%.*]] = icmp eq i64 [[TMP174]], [[TMP175]]
// CHK-C-NEXT:    [[FROMBOOL123:%.*]] = zext i1 [[CMP121]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL123]], i8* [[ATMP122]], align 1
// CHK-C-NEXT:    br i1 [[CMP121]], label [[ATOMIC_CONT124:%.*]], label [[ATOMIC_EXIT129:%.*]]
// CHK-C:       atomic_cont124:
// CHK-C-NEXT:    [[TMP176:%.*]] = phi i64 [ [[ATOMIC_LOAD119]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP182:%.*]], [[ATOMIC_CMP126:%.*]] ]
// CHK-C-NEXT:    [[TMP177:%.*]] = bitcast double* [[ATOMIC_TEMP125]] to i64*
// CHK-C-NEXT:    [[TMP178:%.*]] = bitcast double [[TMP170]] to i64
// CHK-C-NEXT:    store i64 [[TMP178]], i64* [[TMP177]], align 8
// CHK-C-NEXT:    [[TMP179:%.*]] = load i64, i64* [[TMP177]], align 8
// CHK-C-NEXT:    [[TMP180:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[TMP181:%.*]] = cmpxchg i64* [[TMP180]], i64 [[TMP176]], i64 [[TMP179]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP182]] = extractvalue { i64, i1 } [[TMP181]], 0
// CHK-C-NEXT:    [[TMP183:%.*]] = extractvalue { i64, i1 } [[TMP181]], 1
// CHK-C-NEXT:    br i1 [[TMP183]], label [[ATOMIC_EXIT129]], label [[ATOMIC_CMP126]]
// CHK-C:       atomic_cmp126:
// CHK-C-NEXT:    [[TMP184:%.*]] = bitcast i64 [[TMP182]] to double
// CHK-C-NEXT:    store double [[TMP184]], double* [[ATMP120]], align 8
// CHK-C-NEXT:    [[TMP185:%.*]] = bitcast double [[TMP184]] to i64
// CHK-C-NEXT:    [[TMP186:%.*]] = bitcast double [[TMP171]] to i64
// CHK-C-NEXT:    [[CMP127:%.*]] = icmp eq i64 [[TMP185]], [[TMP186]]
// CHK-C-NEXT:    [[FROMBOOL128:%.*]] = zext i1 [[CMP127]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL128]], i8* [[ATMP122]], align 1
// CHK-C-NEXT:    br i1 [[CMP127]], label [[ATOMIC_CONT124]], label [[ATOMIC_EXIT129]]
// CHK-C:       atomic_exit129:
// CHK-C-NEXT:    [[TMP187:%.*]] = load double, double* [[ATMP120]], align 8
// CHK-C-NEXT:    [[TMP188:%.*]] = load i8, i8* [[ATMP122]], align 1
// CHK-C-NEXT:    store i8 [[TMP188]], i8* [[R]], align 1
// CHK-C-NEXT:    [[TMP189:%.*]] = load double, double* [[D]], align 8
// CHK-C-NEXT:    [[TMP190:%.*]] = load double, double* [[E]], align 8
// CHK-C-NEXT:    [[TMP191:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD130:%.*]] = load atomic i64, i64* [[TMP191]] monotonic, align 8
// CHK-C-NEXT:    [[TMP192:%.*]] = bitcast i64 [[ATOMIC_LOAD130]] to double
// CHK-C-NEXT:    store double [[TMP192]], double* [[ATMP131]], align 8
// CHK-C-NEXT:    [[TMP193:%.*]] = bitcast double [[TMP192]] to i64
// CHK-C-NEXT:    [[TMP194:%.*]] = bitcast double [[TMP190]] to i64
// CHK-C-NEXT:    [[CMP132:%.*]] = icmp eq i64 [[TMP193]], [[TMP194]]
// CHK-C-NEXT:    [[FROMBOOL134:%.*]] = zext i1 [[CMP132]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL134]], i8* [[ATMP133]], align 1
// CHK-C-NEXT:    br i1 [[CMP132]], label [[ATOMIC_CONT135:%.*]], label [[ATOMIC_EXIT140:%.*]]
// CHK-C:       atomic_cont135:
// CHK-C-NEXT:    [[TMP195:%.*]] = phi i64 [ [[ATOMIC_LOAD130]], [[ATOMIC_EXIT129]] ], [ [[TMP201:%.*]], [[ATOMIC_CMP137:%.*]] ]
// CHK-C-NEXT:    [[TMP196:%.*]] = bitcast double* [[ATOMIC_TEMP136]] to i64*
// CHK-C-NEXT:    [[TMP197:%.*]] = bitcast double [[TMP189]] to i64
// CHK-C-NEXT:    store i64 [[TMP197]], i64* [[TMP196]], align 8
// CHK-C-NEXT:    [[TMP198:%.*]] = load i64, i64* [[TMP196]], align 8
// CHK-C-NEXT:    [[TMP199:%.*]] = bitcast double* [[X]] to i64*
// CHK-C-NEXT:    [[TMP200:%.*]] = cmpxchg i64* [[TMP199]], i64 [[TMP195]], i64 [[TMP198]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP201]] = extractvalue { i64, i1 } [[TMP200]], 0
// CHK-C-NEXT:    [[TMP202:%.*]] = extractvalue { i64, i1 } [[TMP200]], 1
// CHK-C-NEXT:    br i1 [[TMP202]], label [[ATOMIC_EXIT140]], label [[ATOMIC_CMP137]]
// CHK-C:       atomic_cmp137:
// CHK-C-NEXT:    [[TMP203:%.*]] = bitcast i64 [[TMP201]] to double
// CHK-C-NEXT:    store double [[TMP203]], double* [[ATMP131]], align 8
// CHK-C-NEXT:    [[TMP204:%.*]] = bitcast double [[TMP203]] to i64
// CHK-C-NEXT:    [[TMP205:%.*]] = bitcast double [[TMP190]] to i64
// CHK-C-NEXT:    [[CMP138:%.*]] = icmp eq i64 [[TMP204]], [[TMP205]]
// CHK-C-NEXT:    [[FROMBOOL139:%.*]] = zext i1 [[CMP138]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL139]], i8* [[ATMP133]], align 1
// CHK-C-NEXT:    br i1 [[CMP138]], label [[ATOMIC_CONT135]], label [[ATOMIC_EXIT140]]
// CHK-C:       atomic_exit140:
// CHK-C-NEXT:    [[TMP206:%.*]] = load double, double* [[ATMP131]], align 8
// CHK-C-NEXT:    [[TMP207:%.*]] = load i8, i8* [[ATMP133]], align 1
// CHK-C-NEXT:    store i8 [[TMP207]], i8* [[R]], align 1
// CHK-C-NEXT:    [[TMP208:%.*]] = trunc i8 [[TMP207]] to i1
// CHK-C-NEXT:    br i1 [[TMP208]], label [[ATOMIC_CAPTURE_CONT142:%.*]], label [[ATOMIC_CAPTURE141:%.*]]
// CHK-C:       atomic_capture141:
// CHK-C-NEXT:    store double [[TMP206]], double* [[V]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT142]]
// CHK-C:       atomic_capture_cont142:
// CHK-C-NEXT:    ret void
//
// CHK-CXX-LABEL: @_Z11test_doublev(
// CHK-CXX-NEXT:  entry:
// CHK-CXX-NEXT:    [[X:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[EXPR:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[D:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[E:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[V:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[R:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[TMP:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP5:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP7:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP10:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP16:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP18:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP21:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP27:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP29:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP32:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP39:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP41:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP44:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP50:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP52:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP55:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP62:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP64:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP67:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP73:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP75:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP78:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP85:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP87:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP90:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP96:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP98:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP101:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP108:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP110:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP113:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP120:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP122:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP125:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP131:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[ATMP133:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP136:%.*]] = alloca double, align 8
// CHK-CXX-NEXT:    [[TMP0:%.*]] = load double, double* [[EXPR]], align 8
// CHK-CXX-NEXT:    [[TMP1:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i64, i64* [[TMP1]] monotonic, align 8
// CHK-CXX-NEXT:    [[TMP2:%.*]] = bitcast i64 [[ATOMIC_LOAD]] to double
// CHK-CXX-NEXT:    store double [[TMP2]], double* [[TMP]], align 8
// CHK-CXX-NEXT:    [[CMP:%.*]] = fcmp ogt double [[TMP2]], [[TMP0]]
// CHK-CXX-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-CXX:       atomic_cont:
// CHK-CXX-NEXT:    [[TMP3:%.*]] = phi i64 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP9:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-CXX-NEXT:    [[TMP4:%.*]] = bitcast double* [[ATOMIC_TEMP]] to i64*
// CHK-CXX-NEXT:    [[TMP5:%.*]] = bitcast double [[TMP0]] to i64
// CHK-CXX-NEXT:    store i64 [[TMP5]], i64* [[TMP4]], align 8
// CHK-CXX-NEXT:    [[TMP6:%.*]] = load i64, i64* [[TMP4]], align 8
// CHK-CXX-NEXT:    [[TMP7:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[TMP8:%.*]] = cmpxchg i64* [[TMP7]], i64 [[TMP3]], i64 [[TMP6]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP9]] = extractvalue { i64, i1 } [[TMP8]], 0
// CHK-CXX-NEXT:    [[TMP10:%.*]] = extractvalue { i64, i1 } [[TMP8]], 1
// CHK-CXX-NEXT:    br i1 [[TMP10]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-CXX:       atomic_cmp:
// CHK-CXX-NEXT:    [[TMP11:%.*]] = bitcast i64 [[TMP9]] to double
// CHK-CXX-NEXT:    store double [[TMP11]], double* [[TMP]], align 8
// CHK-CXX-NEXT:    [[CMP2:%.*]] = fcmp ogt double [[TMP11]], [[TMP0]]
// CHK-CXX-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[CMP2]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL3]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP2]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-CXX:       atomic_exit:
// CHK-CXX-NEXT:    [[TMP12:%.*]] = load double, double* [[TMP]], align 8
// CHK-CXX-NEXT:    [[TMP13:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    store double [[TMP12]], double* [[V]], align 8
// CHK-CXX-NEXT:    [[TMP14:%.*]] = load double, double* [[EXPR]], align 8
// CHK-CXX-NEXT:    [[TMP15:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD4:%.*]] = load atomic i64, i64* [[TMP15]] monotonic, align 8
// CHK-CXX-NEXT:    [[TMP16:%.*]] = bitcast i64 [[ATOMIC_LOAD4]] to double
// CHK-CXX-NEXT:    store double [[TMP16]], double* [[ATMP5]], align 8
// CHK-CXX-NEXT:    [[CMP6:%.*]] = fcmp ogt double [[TMP16]], [[TMP14]]
// CHK-CXX-NEXT:    [[FROMBOOL8:%.*]] = zext i1 [[CMP6]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL8]], i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP6]], label [[ATOMIC_CONT9:%.*]], label [[ATOMIC_EXIT14:%.*]]
// CHK-CXX:       atomic_cont9:
// CHK-CXX-NEXT:    [[TMP17:%.*]] = phi i64 [ [[ATOMIC_LOAD4]], [[ATOMIC_EXIT]] ], [ [[TMP23:%.*]], [[ATOMIC_CMP11:%.*]] ]
// CHK-CXX-NEXT:    [[TMP18:%.*]] = bitcast double* [[ATOMIC_TEMP10]] to i64*
// CHK-CXX-NEXT:    [[TMP19:%.*]] = bitcast double [[TMP14]] to i64
// CHK-CXX-NEXT:    store i64 [[TMP19]], i64* [[TMP18]], align 8
// CHK-CXX-NEXT:    [[TMP20:%.*]] = load i64, i64* [[TMP18]], align 8
// CHK-CXX-NEXT:    [[TMP21:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[TMP22:%.*]] = cmpxchg i64* [[TMP21]], i64 [[TMP17]], i64 [[TMP20]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP23]] = extractvalue { i64, i1 } [[TMP22]], 0
// CHK-CXX-NEXT:    [[TMP24:%.*]] = extractvalue { i64, i1 } [[TMP22]], 1
// CHK-CXX-NEXT:    br i1 [[TMP24]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP11]]
// CHK-CXX:       atomic_upd_exit:
// CHK-CXX-NEXT:    store double [[TMP14]], double* [[ATMP5]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT14]]
// CHK-CXX:       atomic_cmp11:
// CHK-CXX-NEXT:    [[TMP25:%.*]] = bitcast i64 [[TMP23]] to double
// CHK-CXX-NEXT:    store double [[TMP25]], double* [[ATMP5]], align 8
// CHK-CXX-NEXT:    [[CMP12:%.*]] = fcmp ogt double [[TMP25]], [[TMP14]]
// CHK-CXX-NEXT:    [[FROMBOOL13:%.*]] = zext i1 [[CMP12]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL13]], i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP12]], label [[ATOMIC_CONT9]], label [[ATOMIC_EXIT14]]
// CHK-CXX:       atomic_exit14:
// CHK-CXX-NEXT:    [[TMP26:%.*]] = load double, double* [[ATMP5]], align 8
// CHK-CXX-NEXT:    [[TMP27:%.*]] = load i8, i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    store double [[TMP26]], double* [[V]], align 8
// CHK-CXX-NEXT:    [[TMP28:%.*]] = load double, double* [[EXPR]], align 8
// CHK-CXX-NEXT:    [[TMP29:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD15:%.*]] = load atomic i64, i64* [[TMP29]] monotonic, align 8
// CHK-CXX-NEXT:    [[TMP30:%.*]] = bitcast i64 [[ATOMIC_LOAD15]] to double
// CHK-CXX-NEXT:    store double [[TMP30]], double* [[ATMP16]], align 8
// CHK-CXX-NEXT:    [[CMP17:%.*]] = fcmp olt double [[TMP30]], [[TMP28]]
// CHK-CXX-NEXT:    [[FROMBOOL19:%.*]] = zext i1 [[CMP17]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL19]], i8* [[ATMP18]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP17]], label [[ATOMIC_CONT20:%.*]], label [[ATOMIC_EXIT25:%.*]]
// CHK-CXX:       atomic_cont20:
// CHK-CXX-NEXT:    [[TMP31:%.*]] = phi i64 [ [[ATOMIC_LOAD15]], [[ATOMIC_EXIT14]] ], [ [[TMP37:%.*]], [[ATOMIC_CMP22:%.*]] ]
// CHK-CXX-NEXT:    [[TMP32:%.*]] = bitcast double* [[ATOMIC_TEMP21]] to i64*
// CHK-CXX-NEXT:    [[TMP33:%.*]] = bitcast double [[TMP28]] to i64
// CHK-CXX-NEXT:    store i64 [[TMP33]], i64* [[TMP32]], align 8
// CHK-CXX-NEXT:    [[TMP34:%.*]] = load i64, i64* [[TMP32]], align 8
// CHK-CXX-NEXT:    [[TMP35:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[TMP36:%.*]] = cmpxchg i64* [[TMP35]], i64 [[TMP31]], i64 [[TMP34]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP37]] = extractvalue { i64, i1 } [[TMP36]], 0
// CHK-CXX-NEXT:    [[TMP38:%.*]] = extractvalue { i64, i1 } [[TMP36]], 1
// CHK-CXX-NEXT:    br i1 [[TMP38]], label [[ATOMIC_EXIT25]], label [[ATOMIC_CMP22]]
// CHK-CXX:       atomic_cmp22:
// CHK-CXX-NEXT:    [[TMP39:%.*]] = bitcast i64 [[TMP37]] to double
// CHK-CXX-NEXT:    store double [[TMP39]], double* [[ATMP16]], align 8
// CHK-CXX-NEXT:    [[CMP23:%.*]] = fcmp olt double [[TMP39]], [[TMP28]]
// CHK-CXX-NEXT:    [[FROMBOOL24:%.*]] = zext i1 [[CMP23]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL24]], i8* [[ATMP18]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP23]], label [[ATOMIC_CONT20]], label [[ATOMIC_EXIT25]]
// CHK-CXX:       atomic_exit25:
// CHK-CXX-NEXT:    [[TMP40:%.*]] = load double, double* [[ATMP16]], align 8
// CHK-CXX-NEXT:    [[TMP41:%.*]] = load i8, i8* [[ATMP18]], align 1
// CHK-CXX-NEXT:    store double [[TMP40]], double* [[V]], align 8
// CHK-CXX-NEXT:    [[TMP42:%.*]] = load double, double* [[EXPR]], align 8
// CHK-CXX-NEXT:    [[TMP43:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD26:%.*]] = load atomic i64, i64* [[TMP43]] monotonic, align 8
// CHK-CXX-NEXT:    [[TMP44:%.*]] = bitcast i64 [[ATOMIC_LOAD26]] to double
// CHK-CXX-NEXT:    store double [[TMP44]], double* [[ATMP27]], align 8
// CHK-CXX-NEXT:    [[CMP28:%.*]] = fcmp olt double [[TMP44]], [[TMP42]]
// CHK-CXX-NEXT:    [[FROMBOOL30:%.*]] = zext i1 [[CMP28]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL30]], i8* [[ATMP29]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP28]], label [[ATOMIC_CONT31:%.*]], label [[ATOMIC_EXIT37:%.*]]
// CHK-CXX:       atomic_cont31:
// CHK-CXX-NEXT:    [[TMP45:%.*]] = phi i64 [ [[ATOMIC_LOAD26]], [[ATOMIC_EXIT25]] ], [ [[TMP51:%.*]], [[ATOMIC_CMP34:%.*]] ]
// CHK-CXX-NEXT:    [[TMP46:%.*]] = bitcast double* [[ATOMIC_TEMP32]] to i64*
// CHK-CXX-NEXT:    [[TMP47:%.*]] = bitcast double [[TMP42]] to i64
// CHK-CXX-NEXT:    store i64 [[TMP47]], i64* [[TMP46]], align 8
// CHK-CXX-NEXT:    [[TMP48:%.*]] = load i64, i64* [[TMP46]], align 8
// CHK-CXX-NEXT:    [[TMP49:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[TMP50:%.*]] = cmpxchg i64* [[TMP49]], i64 [[TMP45]], i64 [[TMP48]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP51]] = extractvalue { i64, i1 } [[TMP50]], 0
// CHK-CXX-NEXT:    [[TMP52:%.*]] = extractvalue { i64, i1 } [[TMP50]], 1
// CHK-CXX-NEXT:    br i1 [[TMP52]], label [[ATOMIC_UPD_EXIT33:%.*]], label [[ATOMIC_CMP34]]
// CHK-CXX:       atomic_upd_exit33:
// CHK-CXX-NEXT:    store double [[TMP42]], double* [[ATMP27]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT37]]
// CHK-CXX:       atomic_cmp34:
// CHK-CXX-NEXT:    [[TMP53:%.*]] = bitcast i64 [[TMP51]] to double
// CHK-CXX-NEXT:    store double [[TMP53]], double* [[ATMP27]], align 8
// CHK-CXX-NEXT:    [[CMP35:%.*]] = fcmp olt double [[TMP53]], [[TMP42]]
// CHK-CXX-NEXT:    [[FROMBOOL36:%.*]] = zext i1 [[CMP35]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL36]], i8* [[ATMP29]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP35]], label [[ATOMIC_CONT31]], label [[ATOMIC_EXIT37]]
// CHK-CXX:       atomic_exit37:
// CHK-CXX-NEXT:    [[TMP54:%.*]] = load double, double* [[ATMP27]], align 8
// CHK-CXX-NEXT:    [[TMP55:%.*]] = load i8, i8* [[ATMP29]], align 1
// CHK-CXX-NEXT:    store double [[TMP54]], double* [[V]], align 8
// CHK-CXX-NEXT:    [[TMP56:%.*]] = load double, double* [[EXPR]], align 8
// CHK-CXX-NEXT:    [[TMP57:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD38:%.*]] = load atomic i64, i64* [[TMP57]] monotonic, align 8
// CHK-CXX-NEXT:    [[TMP58:%.*]] = bitcast i64 [[ATOMIC_LOAD38]] to double
// CHK-CXX-NEXT:    store double [[TMP58]], double* [[ATMP39]], align 8
// CHK-CXX-NEXT:    [[CMP40:%.*]] = fcmp olt double [[TMP58]], [[TMP56]]
// CHK-CXX-NEXT:    [[FROMBOOL42:%.*]] = zext i1 [[CMP40]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL42]], i8* [[ATMP41]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP40]], label [[ATOMIC_CONT43:%.*]], label [[ATOMIC_EXIT48:%.*]]
// CHK-CXX:       atomic_cont43:
// CHK-CXX-NEXT:    [[TMP59:%.*]] = phi i64 [ [[ATOMIC_LOAD38]], [[ATOMIC_EXIT37]] ], [ [[TMP65:%.*]], [[ATOMIC_CMP45:%.*]] ]
// CHK-CXX-NEXT:    [[TMP60:%.*]] = bitcast double* [[ATOMIC_TEMP44]] to i64*
// CHK-CXX-NEXT:    [[TMP61:%.*]] = bitcast double [[TMP56]] to i64
// CHK-CXX-NEXT:    store i64 [[TMP61]], i64* [[TMP60]], align 8
// CHK-CXX-NEXT:    [[TMP62:%.*]] = load i64, i64* [[TMP60]], align 8
// CHK-CXX-NEXT:    [[TMP63:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[TMP64:%.*]] = cmpxchg i64* [[TMP63]], i64 [[TMP59]], i64 [[TMP62]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP65]] = extractvalue { i64, i1 } [[TMP64]], 0
// CHK-CXX-NEXT:    [[TMP66:%.*]] = extractvalue { i64, i1 } [[TMP64]], 1
// CHK-CXX-NEXT:    br i1 [[TMP66]], label [[ATOMIC_EXIT48]], label [[ATOMIC_CMP45]]
// CHK-CXX:       atomic_cmp45:
// CHK-CXX-NEXT:    [[TMP67:%.*]] = bitcast i64 [[TMP65]] to double
// CHK-CXX-NEXT:    store double [[TMP67]], double* [[ATMP39]], align 8
// CHK-CXX-NEXT:    [[CMP46:%.*]] = fcmp olt double [[TMP67]], [[TMP56]]
// CHK-CXX-NEXT:    [[FROMBOOL47:%.*]] = zext i1 [[CMP46]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL47]], i8* [[ATMP41]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP46]], label [[ATOMIC_CONT43]], label [[ATOMIC_EXIT48]]
// CHK-CXX:       atomic_exit48:
// CHK-CXX-NEXT:    [[TMP68:%.*]] = load double, double* [[ATMP39]], align 8
// CHK-CXX-NEXT:    [[TMP69:%.*]] = load i8, i8* [[ATMP41]], align 1
// CHK-CXX-NEXT:    store double [[TMP68]], double* [[V]], align 8
// CHK-CXX-NEXT:    [[TMP70:%.*]] = load double, double* [[EXPR]], align 8
// CHK-CXX-NEXT:    [[TMP71:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD49:%.*]] = load atomic i64, i64* [[TMP71]] monotonic, align 8
// CHK-CXX-NEXT:    [[TMP72:%.*]] = bitcast i64 [[ATOMIC_LOAD49]] to double
// CHK-CXX-NEXT:    store double [[TMP72]], double* [[ATMP50]], align 8
// CHK-CXX-NEXT:    [[CMP51:%.*]] = fcmp olt double [[TMP72]], [[TMP70]]
// CHK-CXX-NEXT:    [[FROMBOOL53:%.*]] = zext i1 [[CMP51]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL53]], i8* [[ATMP52]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP51]], label [[ATOMIC_CONT54:%.*]], label [[ATOMIC_EXIT60:%.*]]
// CHK-CXX:       atomic_cont54:
// CHK-CXX-NEXT:    [[TMP73:%.*]] = phi i64 [ [[ATOMIC_LOAD49]], [[ATOMIC_EXIT48]] ], [ [[TMP79:%.*]], [[ATOMIC_CMP57:%.*]] ]
// CHK-CXX-NEXT:    [[TMP74:%.*]] = bitcast double* [[ATOMIC_TEMP55]] to i64*
// CHK-CXX-NEXT:    [[TMP75:%.*]] = bitcast double [[TMP70]] to i64
// CHK-CXX-NEXT:    store i64 [[TMP75]], i64* [[TMP74]], align 8
// CHK-CXX-NEXT:    [[TMP76:%.*]] = load i64, i64* [[TMP74]], align 8
// CHK-CXX-NEXT:    [[TMP77:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[TMP78:%.*]] = cmpxchg i64* [[TMP77]], i64 [[TMP73]], i64 [[TMP76]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP79]] = extractvalue { i64, i1 } [[TMP78]], 0
// CHK-CXX-NEXT:    [[TMP80:%.*]] = extractvalue { i64, i1 } [[TMP78]], 1
// CHK-CXX-NEXT:    br i1 [[TMP80]], label [[ATOMIC_UPD_EXIT56:%.*]], label [[ATOMIC_CMP57]]
// CHK-CXX:       atomic_upd_exit56:
// CHK-CXX-NEXT:    store double [[TMP70]], double* [[ATMP50]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT60]]
// CHK-CXX:       atomic_cmp57:
// CHK-CXX-NEXT:    [[TMP81:%.*]] = bitcast i64 [[TMP79]] to double
// CHK-CXX-NEXT:    store double [[TMP81]], double* [[ATMP50]], align 8
// CHK-CXX-NEXT:    [[CMP58:%.*]] = fcmp olt double [[TMP81]], [[TMP70]]
// CHK-CXX-NEXT:    [[FROMBOOL59:%.*]] = zext i1 [[CMP58]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL59]], i8* [[ATMP52]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP58]], label [[ATOMIC_CONT54]], label [[ATOMIC_EXIT60]]
// CHK-CXX:       atomic_exit60:
// CHK-CXX-NEXT:    [[TMP82:%.*]] = load double, double* [[ATMP50]], align 8
// CHK-CXX-NEXT:    [[TMP83:%.*]] = load i8, i8* [[ATMP52]], align 1
// CHK-CXX-NEXT:    store double [[TMP82]], double* [[V]], align 8
// CHK-CXX-NEXT:    [[TMP84:%.*]] = load double, double* [[EXPR]], align 8
// CHK-CXX-NEXT:    [[TMP85:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD61:%.*]] = load atomic i64, i64* [[TMP85]] monotonic, align 8
// CHK-CXX-NEXT:    [[TMP86:%.*]] = bitcast i64 [[ATOMIC_LOAD61]] to double
// CHK-CXX-NEXT:    store double [[TMP86]], double* [[ATMP62]], align 8
// CHK-CXX-NEXT:    [[CMP63:%.*]] = fcmp ogt double [[TMP86]], [[TMP84]]
// CHK-CXX-NEXT:    [[FROMBOOL65:%.*]] = zext i1 [[CMP63]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL65]], i8* [[ATMP64]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP63]], label [[ATOMIC_CONT66:%.*]], label [[ATOMIC_EXIT71:%.*]]
// CHK-CXX:       atomic_cont66:
// CHK-CXX-NEXT:    [[TMP87:%.*]] = phi i64 [ [[ATOMIC_LOAD61]], [[ATOMIC_EXIT60]] ], [ [[TMP93:%.*]], [[ATOMIC_CMP68:%.*]] ]
// CHK-CXX-NEXT:    [[TMP88:%.*]] = bitcast double* [[ATOMIC_TEMP67]] to i64*
// CHK-CXX-NEXT:    [[TMP89:%.*]] = bitcast double [[TMP84]] to i64
// CHK-CXX-NEXT:    store i64 [[TMP89]], i64* [[TMP88]], align 8
// CHK-CXX-NEXT:    [[TMP90:%.*]] = load i64, i64* [[TMP88]], align 8
// CHK-CXX-NEXT:    [[TMP91:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[TMP92:%.*]] = cmpxchg i64* [[TMP91]], i64 [[TMP87]], i64 [[TMP90]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP93]] = extractvalue { i64, i1 } [[TMP92]], 0
// CHK-CXX-NEXT:    [[TMP94:%.*]] = extractvalue { i64, i1 } [[TMP92]], 1
// CHK-CXX-NEXT:    br i1 [[TMP94]], label [[ATOMIC_EXIT71]], label [[ATOMIC_CMP68]]
// CHK-CXX:       atomic_cmp68:
// CHK-CXX-NEXT:    [[TMP95:%.*]] = bitcast i64 [[TMP93]] to double
// CHK-CXX-NEXT:    store double [[TMP95]], double* [[ATMP62]], align 8
// CHK-CXX-NEXT:    [[CMP69:%.*]] = fcmp ogt double [[TMP95]], [[TMP84]]
// CHK-CXX-NEXT:    [[FROMBOOL70:%.*]] = zext i1 [[CMP69]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL70]], i8* [[ATMP64]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP69]], label [[ATOMIC_CONT66]], label [[ATOMIC_EXIT71]]
// CHK-CXX:       atomic_exit71:
// CHK-CXX-NEXT:    [[TMP96:%.*]] = load double, double* [[ATMP62]], align 8
// CHK-CXX-NEXT:    [[TMP97:%.*]] = load i8, i8* [[ATMP64]], align 1
// CHK-CXX-NEXT:    store double [[TMP96]], double* [[V]], align 8
// CHK-CXX-NEXT:    [[TMP98:%.*]] = load double, double* [[EXPR]], align 8
// CHK-CXX-NEXT:    [[TMP99:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD72:%.*]] = load atomic i64, i64* [[TMP99]] monotonic, align 8
// CHK-CXX-NEXT:    [[TMP100:%.*]] = bitcast i64 [[ATOMIC_LOAD72]] to double
// CHK-CXX-NEXT:    store double [[TMP100]], double* [[ATMP73]], align 8
// CHK-CXX-NEXT:    [[CMP74:%.*]] = fcmp ogt double [[TMP100]], [[TMP98]]
// CHK-CXX-NEXT:    [[FROMBOOL76:%.*]] = zext i1 [[CMP74]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL76]], i8* [[ATMP75]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP74]], label [[ATOMIC_CONT77:%.*]], label [[ATOMIC_EXIT83:%.*]]
// CHK-CXX:       atomic_cont77:
// CHK-CXX-NEXT:    [[TMP101:%.*]] = phi i64 [ [[ATOMIC_LOAD72]], [[ATOMIC_EXIT71]] ], [ [[TMP107:%.*]], [[ATOMIC_CMP80:%.*]] ]
// CHK-CXX-NEXT:    [[TMP102:%.*]] = bitcast double* [[ATOMIC_TEMP78]] to i64*
// CHK-CXX-NEXT:    [[TMP103:%.*]] = bitcast double [[TMP98]] to i64
// CHK-CXX-NEXT:    store i64 [[TMP103]], i64* [[TMP102]], align 8
// CHK-CXX-NEXT:    [[TMP104:%.*]] = load i64, i64* [[TMP102]], align 8
// CHK-CXX-NEXT:    [[TMP105:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[TMP106:%.*]] = cmpxchg i64* [[TMP105]], i64 [[TMP101]], i64 [[TMP104]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP107]] = extractvalue { i64, i1 } [[TMP106]], 0
// CHK-CXX-NEXT:    [[TMP108:%.*]] = extractvalue { i64, i1 } [[TMP106]], 1
// CHK-CXX-NEXT:    br i1 [[TMP108]], label [[ATOMIC_UPD_EXIT79:%.*]], label [[ATOMIC_CMP80]]
// CHK-CXX:       atomic_upd_exit79:
// CHK-CXX-NEXT:    store double [[TMP98]], double* [[ATMP73]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT83]]
// CHK-CXX:       atomic_cmp80:
// CHK-CXX-NEXT:    [[TMP109:%.*]] = bitcast i64 [[TMP107]] to double
// CHK-CXX-NEXT:    store double [[TMP109]], double* [[ATMP73]], align 8
// CHK-CXX-NEXT:    [[CMP81:%.*]] = fcmp ogt double [[TMP109]], [[TMP98]]
// CHK-CXX-NEXT:    [[FROMBOOL82:%.*]] = zext i1 [[CMP81]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL82]], i8* [[ATMP75]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP81]], label [[ATOMIC_CONT77]], label [[ATOMIC_EXIT83]]
// CHK-CXX:       atomic_exit83:
// CHK-CXX-NEXT:    [[TMP110:%.*]] = load double, double* [[ATMP73]], align 8
// CHK-CXX-NEXT:    [[TMP111:%.*]] = load i8, i8* [[ATMP75]], align 1
// CHK-CXX-NEXT:    store double [[TMP110]], double* [[V]], align 8
// CHK-CXX-NEXT:    [[TMP112:%.*]] = load double, double* [[D]], align 8
// CHK-CXX-NEXT:    [[TMP113:%.*]] = load double, double* [[E]], align 8
// CHK-CXX-NEXT:    [[TMP114:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD84:%.*]] = load atomic i64, i64* [[TMP114]] monotonic, align 8
// CHK-CXX-NEXT:    [[TMP115:%.*]] = bitcast i64 [[ATOMIC_LOAD84]] to double
// CHK-CXX-NEXT:    store double [[TMP115]], double* [[ATMP85]], align 8
// CHK-CXX-NEXT:    [[TMP116:%.*]] = bitcast double [[TMP115]] to i64
// CHK-CXX-NEXT:    [[TMP117:%.*]] = bitcast double [[TMP113]] to i64
// CHK-CXX-NEXT:    [[CMP86:%.*]] = icmp eq i64 [[TMP116]], [[TMP117]]
// CHK-CXX-NEXT:    [[FROMBOOL88:%.*]] = zext i1 [[CMP86]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL88]], i8* [[ATMP87]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP86]], label [[ATOMIC_CONT89:%.*]], label [[ATOMIC_EXIT94:%.*]]
// CHK-CXX:       atomic_cont89:
// CHK-CXX-NEXT:    [[TMP118:%.*]] = phi i64 [ [[ATOMIC_LOAD84]], [[ATOMIC_EXIT83]] ], [ [[TMP124:%.*]], [[ATOMIC_CMP91:%.*]] ]
// CHK-CXX-NEXT:    [[TMP119:%.*]] = bitcast double* [[ATOMIC_TEMP90]] to i64*
// CHK-CXX-NEXT:    [[TMP120:%.*]] = bitcast double [[TMP112]] to i64
// CHK-CXX-NEXT:    store i64 [[TMP120]], i64* [[TMP119]], align 8
// CHK-CXX-NEXT:    [[TMP121:%.*]] = load i64, i64* [[TMP119]], align 8
// CHK-CXX-NEXT:    [[TMP122:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[TMP123:%.*]] = cmpxchg i64* [[TMP122]], i64 [[TMP118]], i64 [[TMP121]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP124]] = extractvalue { i64, i1 } [[TMP123]], 0
// CHK-CXX-NEXT:    [[TMP125:%.*]] = extractvalue { i64, i1 } [[TMP123]], 1
// CHK-CXX-NEXT:    br i1 [[TMP125]], label [[ATOMIC_EXIT94]], label [[ATOMIC_CMP91]]
// CHK-CXX:       atomic_cmp91:
// CHK-CXX-NEXT:    [[TMP126:%.*]] = bitcast i64 [[TMP124]] to double
// CHK-CXX-NEXT:    store double [[TMP126]], double* [[ATMP85]], align 8
// CHK-CXX-NEXT:    [[TMP127:%.*]] = bitcast double [[TMP126]] to i64
// CHK-CXX-NEXT:    [[TMP128:%.*]] = bitcast double [[TMP113]] to i64
// CHK-CXX-NEXT:    [[CMP92:%.*]] = icmp eq i64 [[TMP127]], [[TMP128]]
// CHK-CXX-NEXT:    [[FROMBOOL93:%.*]] = zext i1 [[CMP92]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL93]], i8* [[ATMP87]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP92]], label [[ATOMIC_CONT89]], label [[ATOMIC_EXIT94]]
// CHK-CXX:       atomic_exit94:
// CHK-CXX-NEXT:    [[TMP129:%.*]] = load double, double* [[ATMP85]], align 8
// CHK-CXX-NEXT:    [[TMP130:%.*]] = load i8, i8* [[ATMP87]], align 1
// CHK-CXX-NEXT:    store double [[TMP129]], double* [[V]], align 8
// CHK-CXX-NEXT:    [[TMP131:%.*]] = load double, double* [[D]], align 8
// CHK-CXX-NEXT:    [[TMP132:%.*]] = load double, double* [[E]], align 8
// CHK-CXX-NEXT:    [[TMP133:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD95:%.*]] = load atomic i64, i64* [[TMP133]] monotonic, align 8
// CHK-CXX-NEXT:    [[TMP134:%.*]] = bitcast i64 [[ATOMIC_LOAD95]] to double
// CHK-CXX-NEXT:    store double [[TMP134]], double* [[ATMP96]], align 8
// CHK-CXX-NEXT:    [[TMP135:%.*]] = bitcast double [[TMP134]] to i64
// CHK-CXX-NEXT:    [[TMP136:%.*]] = bitcast double [[TMP132]] to i64
// CHK-CXX-NEXT:    [[CMP97:%.*]] = icmp eq i64 [[TMP135]], [[TMP136]]
// CHK-CXX-NEXT:    [[FROMBOOL99:%.*]] = zext i1 [[CMP97]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL99]], i8* [[ATMP98]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP97]], label [[ATOMIC_CONT100:%.*]], label [[ATOMIC_EXIT106:%.*]]
// CHK-CXX:       atomic_cont100:
// CHK-CXX-NEXT:    [[TMP137:%.*]] = phi i64 [ [[ATOMIC_LOAD95]], [[ATOMIC_EXIT94]] ], [ [[TMP143:%.*]], [[ATOMIC_CMP103:%.*]] ]
// CHK-CXX-NEXT:    [[TMP138:%.*]] = bitcast double* [[ATOMIC_TEMP101]] to i64*
// CHK-CXX-NEXT:    [[TMP139:%.*]] = bitcast double [[TMP131]] to i64
// CHK-CXX-NEXT:    store i64 [[TMP139]], i64* [[TMP138]], align 8
// CHK-CXX-NEXT:    [[TMP140:%.*]] = load i64, i64* [[TMP138]], align 8
// CHK-CXX-NEXT:    [[TMP141:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[TMP142:%.*]] = cmpxchg i64* [[TMP141]], i64 [[TMP137]], i64 [[TMP140]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP143]] = extractvalue { i64, i1 } [[TMP142]], 0
// CHK-CXX-NEXT:    [[TMP144:%.*]] = extractvalue { i64, i1 } [[TMP142]], 1
// CHK-CXX-NEXT:    br i1 [[TMP144]], label [[ATOMIC_UPD_EXIT102:%.*]], label [[ATOMIC_CMP103]]
// CHK-CXX:       atomic_upd_exit102:
// CHK-CXX-NEXT:    store double [[TMP131]], double* [[ATMP96]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT106]]
// CHK-CXX:       atomic_cmp103:
// CHK-CXX-NEXT:    [[TMP145:%.*]] = bitcast i64 [[TMP143]] to double
// CHK-CXX-NEXT:    store double [[TMP145]], double* [[ATMP96]], align 8
// CHK-CXX-NEXT:    [[TMP146:%.*]] = bitcast double [[TMP145]] to i64
// CHK-CXX-NEXT:    [[TMP147:%.*]] = bitcast double [[TMP132]] to i64
// CHK-CXX-NEXT:    [[CMP104:%.*]] = icmp eq i64 [[TMP146]], [[TMP147]]
// CHK-CXX-NEXT:    [[FROMBOOL105:%.*]] = zext i1 [[CMP104]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL105]], i8* [[ATMP98]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP104]], label [[ATOMIC_CONT100]], label [[ATOMIC_EXIT106]]
// CHK-CXX:       atomic_exit106:
// CHK-CXX-NEXT:    [[TMP148:%.*]] = load double, double* [[ATMP96]], align 8
// CHK-CXX-NEXT:    [[TMP149:%.*]] = load i8, i8* [[ATMP98]], align 1
// CHK-CXX-NEXT:    store double [[TMP148]], double* [[V]], align 8
// CHK-CXX-NEXT:    [[TMP150:%.*]] = load double, double* [[D]], align 8
// CHK-CXX-NEXT:    [[TMP151:%.*]] = load double, double* [[E]], align 8
// CHK-CXX-NEXT:    [[TMP152:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD107:%.*]] = load atomic i64, i64* [[TMP152]] monotonic, align 8
// CHK-CXX-NEXT:    [[TMP153:%.*]] = bitcast i64 [[ATOMIC_LOAD107]] to double
// CHK-CXX-NEXT:    store double [[TMP153]], double* [[ATMP108]], align 8
// CHK-CXX-NEXT:    [[TMP154:%.*]] = bitcast double [[TMP153]] to i64
// CHK-CXX-NEXT:    [[TMP155:%.*]] = bitcast double [[TMP151]] to i64
// CHK-CXX-NEXT:    [[CMP109:%.*]] = icmp eq i64 [[TMP154]], [[TMP155]]
// CHK-CXX-NEXT:    [[FROMBOOL111:%.*]] = zext i1 [[CMP109]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL111]], i8* [[ATMP110]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP109]], label [[ATOMIC_CONT112:%.*]], label [[ATOMIC_EXIT118:%.*]]
// CHK-CXX:       atomic_cont112:
// CHK-CXX-NEXT:    [[TMP156:%.*]] = phi i64 [ [[ATOMIC_LOAD107]], [[ATOMIC_EXIT106]] ], [ [[TMP162:%.*]], [[ATOMIC_CMP115:%.*]] ]
// CHK-CXX-NEXT:    [[TMP157:%.*]] = bitcast double* [[ATOMIC_TEMP113]] to i64*
// CHK-CXX-NEXT:    [[TMP158:%.*]] = bitcast double [[TMP150]] to i64
// CHK-CXX-NEXT:    store i64 [[TMP158]], i64* [[TMP157]], align 8
// CHK-CXX-NEXT:    [[TMP159:%.*]] = load i64, i64* [[TMP157]], align 8
// CHK-CXX-NEXT:    [[TMP160:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[TMP161:%.*]] = cmpxchg i64* [[TMP160]], i64 [[TMP156]], i64 [[TMP159]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP162]] = extractvalue { i64, i1 } [[TMP161]], 0
// CHK-CXX-NEXT:    [[TMP163:%.*]] = extractvalue { i64, i1 } [[TMP161]], 1
// CHK-CXX-NEXT:    br i1 [[TMP163]], label [[ATOMIC_UPD_EXIT114:%.*]], label [[ATOMIC_CMP115]]
// CHK-CXX:       atomic_upd_exit114:
// CHK-CXX-NEXT:    store double [[TMP150]], double* [[ATMP108]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT118]]
// CHK-CXX:       atomic_cmp115:
// CHK-CXX-NEXT:    [[TMP164:%.*]] = bitcast i64 [[TMP162]] to double
// CHK-CXX-NEXT:    store double [[TMP164]], double* [[ATMP108]], align 8
// CHK-CXX-NEXT:    [[TMP165:%.*]] = bitcast double [[TMP164]] to i64
// CHK-CXX-NEXT:    [[TMP166:%.*]] = bitcast double [[TMP151]] to i64
// CHK-CXX-NEXT:    [[CMP116:%.*]] = icmp eq i64 [[TMP165]], [[TMP166]]
// CHK-CXX-NEXT:    [[FROMBOOL117:%.*]] = zext i1 [[CMP116]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL117]], i8* [[ATMP110]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP116]], label [[ATOMIC_CONT112]], label [[ATOMIC_EXIT118]]
// CHK-CXX:       atomic_exit118:
// CHK-CXX-NEXT:    [[TMP167:%.*]] = load double, double* [[ATMP108]], align 8
// CHK-CXX-NEXT:    [[TMP168:%.*]] = load i8, i8* [[ATMP110]], align 1
// CHK-CXX-NEXT:    [[TMP169:%.*]] = trunc i8 [[TMP168]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP169]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-CXX:       atomic_capture:
// CHK-CXX-NEXT:    store double [[TMP167]], double* [[V]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-CXX:       atomic_capture_cont:
// CHK-CXX-NEXT:    [[TMP170:%.*]] = load double, double* [[D]], align 8
// CHK-CXX-NEXT:    [[TMP171:%.*]] = load double, double* [[E]], align 8
// CHK-CXX-NEXT:    [[TMP172:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD119:%.*]] = load atomic i64, i64* [[TMP172]] monotonic, align 8
// CHK-CXX-NEXT:    [[TMP173:%.*]] = bitcast i64 [[ATOMIC_LOAD119]] to double
// CHK-CXX-NEXT:    store double [[TMP173]], double* [[ATMP120]], align 8
// CHK-CXX-NEXT:    [[TMP174:%.*]] = bitcast double [[TMP173]] to i64
// CHK-CXX-NEXT:    [[TMP175:%.*]] = bitcast double [[TMP171]] to i64
// CHK-CXX-NEXT:    [[CMP121:%.*]] = icmp eq i64 [[TMP174]], [[TMP175]]
// CHK-CXX-NEXT:    [[FROMBOOL123:%.*]] = zext i1 [[CMP121]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL123]], i8* [[ATMP122]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP121]], label [[ATOMIC_CONT124:%.*]], label [[ATOMIC_EXIT129:%.*]]
// CHK-CXX:       atomic_cont124:
// CHK-CXX-NEXT:    [[TMP176:%.*]] = phi i64 [ [[ATOMIC_LOAD119]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP182:%.*]], [[ATOMIC_CMP126:%.*]] ]
// CHK-CXX-NEXT:    [[TMP177:%.*]] = bitcast double* [[ATOMIC_TEMP125]] to i64*
// CHK-CXX-NEXT:    [[TMP178:%.*]] = bitcast double [[TMP170]] to i64
// CHK-CXX-NEXT:    store i64 [[TMP178]], i64* [[TMP177]], align 8
// CHK-CXX-NEXT:    [[TMP179:%.*]] = load i64, i64* [[TMP177]], align 8
// CHK-CXX-NEXT:    [[TMP180:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[TMP181:%.*]] = cmpxchg i64* [[TMP180]], i64 [[TMP176]], i64 [[TMP179]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP182]] = extractvalue { i64, i1 } [[TMP181]], 0
// CHK-CXX-NEXT:    [[TMP183:%.*]] = extractvalue { i64, i1 } [[TMP181]], 1
// CHK-CXX-NEXT:    br i1 [[TMP183]], label [[ATOMIC_EXIT129]], label [[ATOMIC_CMP126]]
// CHK-CXX:       atomic_cmp126:
// CHK-CXX-NEXT:    [[TMP184:%.*]] = bitcast i64 [[TMP182]] to double
// CHK-CXX-NEXT:    store double [[TMP184]], double* [[ATMP120]], align 8
// CHK-CXX-NEXT:    [[TMP185:%.*]] = bitcast double [[TMP184]] to i64
// CHK-CXX-NEXT:    [[TMP186:%.*]] = bitcast double [[TMP171]] to i64
// CHK-CXX-NEXT:    [[CMP127:%.*]] = icmp eq i64 [[TMP185]], [[TMP186]]
// CHK-CXX-NEXT:    [[FROMBOOL128:%.*]] = zext i1 [[CMP127]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL128]], i8* [[ATMP122]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP127]], label [[ATOMIC_CONT124]], label [[ATOMIC_EXIT129]]
// CHK-CXX:       atomic_exit129:
// CHK-CXX-NEXT:    [[TMP187:%.*]] = load double, double* [[ATMP120]], align 8
// CHK-CXX-NEXT:    [[TMP188:%.*]] = load i8, i8* [[ATMP122]], align 1
// CHK-CXX-NEXT:    store i8 [[TMP188]], i8* [[R]], align 1
// CHK-CXX-NEXT:    [[TMP189:%.*]] = load double, double* [[D]], align 8
// CHK-CXX-NEXT:    [[TMP190:%.*]] = load double, double* [[E]], align 8
// CHK-CXX-NEXT:    [[TMP191:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD130:%.*]] = load atomic i64, i64* [[TMP191]] monotonic, align 8
// CHK-CXX-NEXT:    [[TMP192:%.*]] = bitcast i64 [[ATOMIC_LOAD130]] to double
// CHK-CXX-NEXT:    store double [[TMP192]], double* [[ATMP131]], align 8
// CHK-CXX-NEXT:    [[TMP193:%.*]] = bitcast double [[TMP192]] to i64
// CHK-CXX-NEXT:    [[TMP194:%.*]] = bitcast double [[TMP190]] to i64
// CHK-CXX-NEXT:    [[CMP132:%.*]] = icmp eq i64 [[TMP193]], [[TMP194]]
// CHK-CXX-NEXT:    [[FROMBOOL134:%.*]] = zext i1 [[CMP132]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL134]], i8* [[ATMP133]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP132]], label [[ATOMIC_CONT135:%.*]], label [[ATOMIC_EXIT140:%.*]]
// CHK-CXX:       atomic_cont135:
// CHK-CXX-NEXT:    [[TMP195:%.*]] = phi i64 [ [[ATOMIC_LOAD130]], [[ATOMIC_EXIT129]] ], [ [[TMP201:%.*]], [[ATOMIC_CMP137:%.*]] ]
// CHK-CXX-NEXT:    [[TMP196:%.*]] = bitcast double* [[ATOMIC_TEMP136]] to i64*
// CHK-CXX-NEXT:    [[TMP197:%.*]] = bitcast double [[TMP189]] to i64
// CHK-CXX-NEXT:    store i64 [[TMP197]], i64* [[TMP196]], align 8
// CHK-CXX-NEXT:    [[TMP198:%.*]] = load i64, i64* [[TMP196]], align 8
// CHK-CXX-NEXT:    [[TMP199:%.*]] = bitcast double* [[X]] to i64*
// CHK-CXX-NEXT:    [[TMP200:%.*]] = cmpxchg i64* [[TMP199]], i64 [[TMP195]], i64 [[TMP198]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP201]] = extractvalue { i64, i1 } [[TMP200]], 0
// CHK-CXX-NEXT:    [[TMP202:%.*]] = extractvalue { i64, i1 } [[TMP200]], 1
// CHK-CXX-NEXT:    br i1 [[TMP202]], label [[ATOMIC_EXIT140]], label [[ATOMIC_CMP137]]
// CHK-CXX:       atomic_cmp137:
// CHK-CXX-NEXT:    [[TMP203:%.*]] = bitcast i64 [[TMP201]] to double
// CHK-CXX-NEXT:    store double [[TMP203]], double* [[ATMP131]], align 8
// CHK-CXX-NEXT:    [[TMP204:%.*]] = bitcast double [[TMP203]] to i64
// CHK-CXX-NEXT:    [[TMP205:%.*]] = bitcast double [[TMP190]] to i64
// CHK-CXX-NEXT:    [[CMP138:%.*]] = icmp eq i64 [[TMP204]], [[TMP205]]
// CHK-CXX-NEXT:    [[FROMBOOL139:%.*]] = zext i1 [[CMP138]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL139]], i8* [[ATMP133]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP138]], label [[ATOMIC_CONT135]], label [[ATOMIC_EXIT140]]
// CHK-CXX:       atomic_exit140:
// CHK-CXX-NEXT:    [[TMP206:%.*]] = load double, double* [[ATMP131]], align 8
// CHK-CXX-NEXT:    [[TMP207:%.*]] = load i8, i8* [[ATMP133]], align 1
// CHK-CXX-NEXT:    store i8 [[TMP207]], i8* [[R]], align 1
// CHK-CXX-NEXT:    [[TMP208:%.*]] = trunc i8 [[TMP207]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP208]], label [[ATOMIC_CAPTURE_CONT142:%.*]], label [[ATOMIC_CAPTURE141:%.*]]
// CHK-CXX:       atomic_capture141:
// CHK-CXX-NEXT:    store double [[TMP206]], double* [[V]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT142]]
// CHK-CXX:       atomic_capture_cont142:
// CHK-CXX-NEXT:    ret void
//
void test_double() {
    // One of each form with 'double'.
    double x, expr, d, e, v;
    char r;

    #pragma omp atomic compare capture
    { v = x; if (expr < x) { x = expr; } } // MIN

    #pragma omp atomic compare capture
    { if (expr < x) { x = expr; } v =x ;} // MIN

    #pragma omp atomic compare capture
    { v = x; if (expr > x) { x = expr; } } // MAX

    #pragma omp atomic compare capture
    { if (expr > x) { x = expr; } v = x; } // MAX

    #pragma omp atomic compare capture
    { v = x; if (x < expr) { x = expr; } } // MAX

    #pragma omp atomic compare capture
    { if (x < expr) { x = expr; } v = x; } // MAX

    #pragma omp atomic compare capture
    { v = x; if (x > expr) { x = expr; } } // MIN

    #pragma omp atomic compare capture
    { if (x > expr) { x = expr; } v = x; } // MIN

    #pragma omp atomic compare capture
    { v = x; if (x == e) { x = d; } }

    #pragma omp atomic compare capture
    { if (x == e) { x = d; } v = x; }

    #pragma omp atomic compare capture
    if (x == e) { x = d; } else { v = x; }

    #pragma omp atomic compare capture
    { r = x == e; if(r) { x = d; } }

    #pragma omp atomic compare capture
    { r = x == e; if(r) { x = d; } else { v = x; } }
}

// CHK-C-LABEL: @test_bool(
// CHK-C-NEXT:  entry:
// CHK-C-NEXT:    [[X:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[EXPR:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[D:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[E:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[V:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[R:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[TMP:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATMP7:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATMP9:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP12:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATMP21:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATMP23:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP26:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATMP36:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATMP38:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP41:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATMP50:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATMP52:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP55:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[TMP0:%.*]] = load i8, i8* [[EXPR]], align 1
// CHK-C-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP0]] to i1
// CHK-C-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i8, i8* [[X]] monotonic, align 1
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD]], i8* [[TMP]], align 1
// CHK-C-NEXT:    [[TMP1:%.*]] = trunc i8 [[ATOMIC_LOAD]] to i1
// CHK-C-NEXT:    [[CMP:%.*]] = icmp ult i1 [[TMP1]], [[TOBOOL]]
// CHK-C-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-C:       atomic_cont:
// CHK-C-NEXT:    [[TMP2:%.*]] = phi i8 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP5:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-C-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TOBOOL]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL2]], i8* [[ATOMIC_TEMP]], align 1
// CHK-C-NEXT:    [[TMP3:%.*]] = load i8, i8* [[ATOMIC_TEMP]], align 1
// CHK-C-NEXT:    [[TMP4:%.*]] = cmpxchg i8* [[X]], i8 [[TMP2]], i8 [[TMP3]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP5]] = extractvalue { i8, i1 } [[TMP4]], 0
// CHK-C-NEXT:    [[TMP6:%.*]] = extractvalue { i8, i1 } [[TMP4]], 1
// CHK-C-NEXT:    br i1 [[TMP6]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-C:       atomic_cmp:
// CHK-C-NEXT:    store i8 [[TMP5]], i8* [[TMP]], align 1
// CHK-C-NEXT:    [[TMP7:%.*]] = trunc i8 [[TMP5]] to i1
// CHK-C-NEXT:    [[CMP3:%.*]] = icmp ult i1 [[TMP7]], [[TOBOOL]]
// CHK-C-NEXT:    [[FROMBOOL4:%.*]] = zext i1 [[CMP3]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL4]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP3]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-C:       atomic_exit:
// CHK-C-NEXT:    [[TMP8:%.*]] = load i8, i8* [[TMP]], align 1
// CHK-C-NEXT:    [[TMP9:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-C-NEXT:    store i8 [[TMP8]], i8* [[V]], align 1
// CHK-C-NEXT:    [[TMP10:%.*]] = load i8, i8* [[EXPR]], align 1
// CHK-C-NEXT:    [[TOBOOL5:%.*]] = trunc i8 [[TMP10]] to i1
// CHK-C-NEXT:    [[ATOMIC_LOAD6:%.*]] = load atomic i8, i8* [[X]] monotonic, align 1
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD6]], i8* [[ATMP7]], align 1
// CHK-C-NEXT:    [[TMP11:%.*]] = trunc i8 [[ATOMIC_LOAD6]] to i1
// CHK-C-NEXT:    [[CMP8:%.*]] = icmp ult i1 [[TMP11]], [[TOBOOL5]]
// CHK-C-NEXT:    [[FROMBOOL10:%.*]] = zext i1 [[CMP8]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL10]], i8* [[ATMP9]], align 1
// CHK-C-NEXT:    br i1 [[CMP8]], label [[ATOMIC_CONT11:%.*]], label [[ATOMIC_EXIT17:%.*]]
// CHK-C:       atomic_cont11:
// CHK-C-NEXT:    [[TMP12:%.*]] = phi i8 [ [[ATOMIC_LOAD6]], [[ATOMIC_EXIT]] ], [ [[TMP15:%.*]], [[ATOMIC_CMP14:%.*]] ]
// CHK-C-NEXT:    [[FROMBOOL13:%.*]] = zext i1 [[TOBOOL5]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL13]], i8* [[ATOMIC_TEMP12]], align 1
// CHK-C-NEXT:    [[TMP13:%.*]] = load i8, i8* [[ATOMIC_TEMP12]], align 1
// CHK-C-NEXT:    [[TMP14:%.*]] = cmpxchg i8* [[X]], i8 [[TMP12]], i8 [[TMP13]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP15]] = extractvalue { i8, i1 } [[TMP14]], 0
// CHK-C-NEXT:    [[TMP16:%.*]] = extractvalue { i8, i1 } [[TMP14]], 1
// CHK-C-NEXT:    br i1 [[TMP16]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP14]]
// CHK-C:       atomic_upd_exit:
// CHK-C-NEXT:    [[TMP17:%.*]] = zext i1 [[TOBOOL5]] to i8
// CHK-C-NEXT:    store i8 [[TMP17]], i8* [[ATMP7]], align 1
// CHK-C-NEXT:    br label [[ATOMIC_EXIT17]]
// CHK-C:       atomic_cmp14:
// CHK-C-NEXT:    store i8 [[TMP15]], i8* [[ATMP7]], align 1
// CHK-C-NEXT:    [[TMP18:%.*]] = trunc i8 [[TMP15]] to i1
// CHK-C-NEXT:    [[CMP15:%.*]] = icmp ult i1 [[TMP18]], [[TOBOOL5]]
// CHK-C-NEXT:    [[FROMBOOL16:%.*]] = zext i1 [[CMP15]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL16]], i8* [[ATMP9]], align 1
// CHK-C-NEXT:    br i1 [[CMP15]], label [[ATOMIC_CONT11]], label [[ATOMIC_EXIT17]]
// CHK-C:       atomic_exit17:
// CHK-C-NEXT:    [[TMP19:%.*]] = load i8, i8* [[ATMP7]], align 1
// CHK-C-NEXT:    [[TMP20:%.*]] = load i8, i8* [[ATMP9]], align 1
// CHK-C-NEXT:    store i8 [[TMP19]], i8* [[V]], align 1
// CHK-C-NEXT:    [[TMP21:%.*]] = load i8, i8* [[D]], align 1
// CHK-C-NEXT:    [[TOBOOL18:%.*]] = trunc i8 [[TMP21]] to i1
// CHK-C-NEXT:    [[TMP22:%.*]] = load i8, i8* [[E]], align 1
// CHK-C-NEXT:    [[TOBOOL19:%.*]] = trunc i8 [[TMP22]] to i1
// CHK-C-NEXT:    [[ATOMIC_LOAD20:%.*]] = load atomic i8, i8* [[X]] monotonic, align 1
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD20]], i8* [[ATMP21]], align 1
// CHK-C-NEXT:    [[TMP23:%.*]] = trunc i8 [[ATOMIC_LOAD20]] to i1
// CHK-C-NEXT:    [[CMP22:%.*]] = icmp eq i1 [[TMP23]], [[TOBOOL19]]
// CHK-C-NEXT:    [[FROMBOOL24:%.*]] = zext i1 [[CMP22]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL24]], i8* [[ATMP23]], align 1
// CHK-C-NEXT:    br i1 [[CMP22]], label [[ATOMIC_CONT25:%.*]], label [[ATOMIC_EXIT32:%.*]]
// CHK-C:       atomic_cont25:
// CHK-C-NEXT:    [[TMP24:%.*]] = phi i8 [ [[ATOMIC_LOAD20]], [[ATOMIC_EXIT17]] ], [ [[TMP27:%.*]], [[ATOMIC_CMP29:%.*]] ]
// CHK-C-NEXT:    [[FROMBOOL27:%.*]] = zext i1 [[TOBOOL18]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL27]], i8* [[ATOMIC_TEMP26]], align 1
// CHK-C-NEXT:    [[TMP25:%.*]] = load i8, i8* [[ATOMIC_TEMP26]], align 1
// CHK-C-NEXT:    [[TMP26:%.*]] = cmpxchg i8* [[X]], i8 [[TMP24]], i8 [[TMP25]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP27]] = extractvalue { i8, i1 } [[TMP26]], 0
// CHK-C-NEXT:    [[TMP28:%.*]] = extractvalue { i8, i1 } [[TMP26]], 1
// CHK-C-NEXT:    br i1 [[TMP28]], label [[ATOMIC_UPD_EXIT28:%.*]], label [[ATOMIC_CMP29]]
// CHK-C:       atomic_upd_exit28:
// CHK-C-NEXT:    [[TMP29:%.*]] = zext i1 [[TOBOOL18]] to i8
// CHK-C-NEXT:    store i8 [[TMP29]], i8* [[ATMP21]], align 1
// CHK-C-NEXT:    br label [[ATOMIC_EXIT32]]
// CHK-C:       atomic_cmp29:
// CHK-C-NEXT:    store i8 [[TMP27]], i8* [[ATMP21]], align 1
// CHK-C-NEXT:    [[TMP30:%.*]] = trunc i8 [[TMP27]] to i1
// CHK-C-NEXT:    [[CMP30:%.*]] = icmp eq i1 [[TMP30]], [[TOBOOL19]]
// CHK-C-NEXT:    [[FROMBOOL31:%.*]] = zext i1 [[CMP30]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL31]], i8* [[ATMP23]], align 1
// CHK-C-NEXT:    br i1 [[CMP30]], label [[ATOMIC_CONT25]], label [[ATOMIC_EXIT32]]
// CHK-C:       atomic_exit32:
// CHK-C-NEXT:    [[TMP31:%.*]] = load i8, i8* [[ATMP21]], align 1
// CHK-C-NEXT:    [[TMP32:%.*]] = load i8, i8* [[ATMP23]], align 1
// CHK-C-NEXT:    [[TMP33:%.*]] = trunc i8 [[TMP32]] to i1
// CHK-C-NEXT:    br i1 [[TMP33]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-C:       atomic_capture:
// CHK-C-NEXT:    store i8 [[TMP31]], i8* [[V]], align 1
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-C:       atomic_capture_cont:
// CHK-C-NEXT:    [[TMP34:%.*]] = load i8, i8* [[D]], align 1
// CHK-C-NEXT:    [[TOBOOL33:%.*]] = trunc i8 [[TMP34]] to i1
// CHK-C-NEXT:    [[TMP35:%.*]] = load i8, i8* [[E]], align 1
// CHK-C-NEXT:    [[TOBOOL34:%.*]] = trunc i8 [[TMP35]] to i1
// CHK-C-NEXT:    [[ATOMIC_LOAD35:%.*]] = load atomic i8, i8* [[X]] monotonic, align 1
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD35]], i8* [[ATMP36]], align 1
// CHK-C-NEXT:    [[TMP36:%.*]] = trunc i8 [[ATOMIC_LOAD35]] to i1
// CHK-C-NEXT:    [[CMP37:%.*]] = icmp eq i1 [[TMP36]], [[TOBOOL34]]
// CHK-C-NEXT:    [[FROMBOOL39:%.*]] = zext i1 [[CMP37]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL39]], i8* [[ATMP38]], align 1
// CHK-C-NEXT:    br i1 [[CMP37]], label [[ATOMIC_CONT40:%.*]], label [[ATOMIC_EXIT46:%.*]]
// CHK-C:       atomic_cont40:
// CHK-C-NEXT:    [[TMP37:%.*]] = phi i8 [ [[ATOMIC_LOAD35]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP40:%.*]], [[ATOMIC_CMP43:%.*]] ]
// CHK-C-NEXT:    [[FROMBOOL42:%.*]] = zext i1 [[TOBOOL33]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL42]], i8* [[ATOMIC_TEMP41]], align 1
// CHK-C-NEXT:    [[TMP38:%.*]] = load i8, i8* [[ATOMIC_TEMP41]], align 1
// CHK-C-NEXT:    [[TMP39:%.*]] = cmpxchg i8* [[X]], i8 [[TMP37]], i8 [[TMP38]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP40]] = extractvalue { i8, i1 } [[TMP39]], 0
// CHK-C-NEXT:    [[TMP41:%.*]] = extractvalue { i8, i1 } [[TMP39]], 1
// CHK-C-NEXT:    br i1 [[TMP41]], label [[ATOMIC_EXIT46]], label [[ATOMIC_CMP43]]
// CHK-C:       atomic_cmp43:
// CHK-C-NEXT:    store i8 [[TMP40]], i8* [[ATMP36]], align 1
// CHK-C-NEXT:    [[TMP42:%.*]] = trunc i8 [[TMP40]] to i1
// CHK-C-NEXT:    [[CMP44:%.*]] = icmp eq i1 [[TMP42]], [[TOBOOL34]]
// CHK-C-NEXT:    [[FROMBOOL45:%.*]] = zext i1 [[CMP44]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL45]], i8* [[ATMP38]], align 1
// CHK-C-NEXT:    br i1 [[CMP44]], label [[ATOMIC_CONT40]], label [[ATOMIC_EXIT46]]
// CHK-C:       atomic_exit46:
// CHK-C-NEXT:    [[TMP43:%.*]] = load i8, i8* [[ATMP36]], align 1
// CHK-C-NEXT:    [[TMP44:%.*]] = load i8, i8* [[ATMP38]], align 1
// CHK-C-NEXT:    store i8 [[TMP44]], i8* [[R]], align 1
// CHK-C-NEXT:    [[TMP45:%.*]] = load i8, i8* [[D]], align 1
// CHK-C-NEXT:    [[TOBOOL47:%.*]] = trunc i8 [[TMP45]] to i1
// CHK-C-NEXT:    [[TMP46:%.*]] = load i8, i8* [[E]], align 1
// CHK-C-NEXT:    [[TOBOOL48:%.*]] = trunc i8 [[TMP46]] to i1
// CHK-C-NEXT:    [[ATOMIC_LOAD49:%.*]] = load atomic i8, i8* [[X]] monotonic, align 1
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD49]], i8* [[ATMP50]], align 1
// CHK-C-NEXT:    [[TMP47:%.*]] = trunc i8 [[ATOMIC_LOAD49]] to i1
// CHK-C-NEXT:    [[CMP51:%.*]] = icmp eq i1 [[TMP47]], [[TOBOOL48]]
// CHK-C-NEXT:    [[FROMBOOL53:%.*]] = zext i1 [[CMP51]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL53]], i8* [[ATMP52]], align 1
// CHK-C-NEXT:    br i1 [[CMP51]], label [[ATOMIC_CONT54:%.*]], label [[ATOMIC_EXIT60:%.*]]
// CHK-C:       atomic_cont54:
// CHK-C-NEXT:    [[TMP48:%.*]] = phi i8 [ [[ATOMIC_LOAD49]], [[ATOMIC_EXIT46]] ], [ [[TMP51:%.*]], [[ATOMIC_CMP57:%.*]] ]
// CHK-C-NEXT:    [[FROMBOOL56:%.*]] = zext i1 [[TOBOOL47]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL56]], i8* [[ATOMIC_TEMP55]], align 1
// CHK-C-NEXT:    [[TMP49:%.*]] = load i8, i8* [[ATOMIC_TEMP55]], align 1
// CHK-C-NEXT:    [[TMP50:%.*]] = cmpxchg i8* [[X]], i8 [[TMP48]], i8 [[TMP49]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP51]] = extractvalue { i8, i1 } [[TMP50]], 0
// CHK-C-NEXT:    [[TMP52:%.*]] = extractvalue { i8, i1 } [[TMP50]], 1
// CHK-C-NEXT:    br i1 [[TMP52]], label [[ATOMIC_EXIT60]], label [[ATOMIC_CMP57]]
// CHK-C:       atomic_cmp57:
// CHK-C-NEXT:    store i8 [[TMP51]], i8* [[ATMP50]], align 1
// CHK-C-NEXT:    [[TMP53:%.*]] = trunc i8 [[TMP51]] to i1
// CHK-C-NEXT:    [[CMP58:%.*]] = icmp eq i1 [[TMP53]], [[TOBOOL48]]
// CHK-C-NEXT:    [[FROMBOOL59:%.*]] = zext i1 [[CMP58]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL59]], i8* [[ATMP52]], align 1
// CHK-C-NEXT:    br i1 [[CMP58]], label [[ATOMIC_CONT54]], label [[ATOMIC_EXIT60]]
// CHK-C:       atomic_exit60:
// CHK-C-NEXT:    [[TMP54:%.*]] = load i8, i8* [[ATMP50]], align 1
// CHK-C-NEXT:    [[TMP55:%.*]] = load i8, i8* [[ATMP52]], align 1
// CHK-C-NEXT:    store i8 [[TMP55]], i8* [[R]], align 1
// CHK-C-NEXT:    [[TMP56:%.*]] = trunc i8 [[TMP55]] to i1
// CHK-C-NEXT:    br i1 [[TMP56]], label [[ATOMIC_CAPTURE_CONT62:%.*]], label [[ATOMIC_CAPTURE61:%.*]]
// CHK-C:       atomic_capture61:
// CHK-C-NEXT:    store i8 [[TMP54]], i8* [[V]], align 1
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT62]]
// CHK-C:       atomic_capture_cont62:
// CHK-C-NEXT:    ret void
//
// CHK-CXX-LABEL: @_Z9test_boolv(
// CHK-CXX-NEXT:  entry:
// CHK-CXX-NEXT:    [[X:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[EXPR:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[D:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[E:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[V:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[R:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[TMP:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATMP7:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATMP9:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP12:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATMP21:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATMP23:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP26:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATMP36:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATMP38:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP41:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATMP50:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATMP52:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP55:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[TMP0:%.*]] = load i8, i8* [[EXPR]], align 1
// CHK-CXX-NEXT:    [[TOBOOL:%.*]] = trunc i8 [[TMP0]] to i1
// CHK-CXX-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i8, i8* [[X]] monotonic, align 1
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD]], i8* [[TMP]], align 1
// CHK-CXX-NEXT:    [[TMP1:%.*]] = trunc i8 [[ATOMIC_LOAD]] to i1
// CHK-CXX-NEXT:    [[CMP:%.*]] = icmp ult i1 [[TMP1]], [[TOBOOL]]
// CHK-CXX-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-CXX:       atomic_cont:
// CHK-CXX-NEXT:    [[TMP2:%.*]] = phi i8 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP5:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-CXX-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TOBOOL]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL2]], i8* [[ATOMIC_TEMP]], align 1
// CHK-CXX-NEXT:    [[TMP3:%.*]] = load i8, i8* [[ATOMIC_TEMP]], align 1
// CHK-CXX-NEXT:    [[TMP4:%.*]] = cmpxchg i8* [[X]], i8 [[TMP2]], i8 [[TMP3]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP5]] = extractvalue { i8, i1 } [[TMP4]], 0
// CHK-CXX-NEXT:    [[TMP6:%.*]] = extractvalue { i8, i1 } [[TMP4]], 1
// CHK-CXX-NEXT:    br i1 [[TMP6]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-CXX:       atomic_cmp:
// CHK-CXX-NEXT:    store i8 [[TMP5]], i8* [[TMP]], align 1
// CHK-CXX-NEXT:    [[TMP7:%.*]] = trunc i8 [[TMP5]] to i1
// CHK-CXX-NEXT:    [[CMP3:%.*]] = icmp ult i1 [[TMP7]], [[TOBOOL]]
// CHK-CXX-NEXT:    [[FROMBOOL4:%.*]] = zext i1 [[CMP3]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL4]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP3]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-CXX:       atomic_exit:
// CHK-CXX-NEXT:    [[TMP8:%.*]] = load i8, i8* [[TMP]], align 1
// CHK-CXX-NEXT:    [[TMP9:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    store i8 [[TMP8]], i8* [[V]], align 1
// CHK-CXX-NEXT:    [[TMP10:%.*]] = load i8, i8* [[EXPR]], align 1
// CHK-CXX-NEXT:    [[TOBOOL5:%.*]] = trunc i8 [[TMP10]] to i1
// CHK-CXX-NEXT:    [[ATOMIC_LOAD6:%.*]] = load atomic i8, i8* [[X]] monotonic, align 1
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD6]], i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    [[TMP11:%.*]] = trunc i8 [[ATOMIC_LOAD6]] to i1
// CHK-CXX-NEXT:    [[CMP8:%.*]] = icmp ult i1 [[TMP11]], [[TOBOOL5]]
// CHK-CXX-NEXT:    [[FROMBOOL10:%.*]] = zext i1 [[CMP8]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL10]], i8* [[ATMP9]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP8]], label [[ATOMIC_CONT11:%.*]], label [[ATOMIC_EXIT17:%.*]]
// CHK-CXX:       atomic_cont11:
// CHK-CXX-NEXT:    [[TMP12:%.*]] = phi i8 [ [[ATOMIC_LOAD6]], [[ATOMIC_EXIT]] ], [ [[TMP15:%.*]], [[ATOMIC_CMP14:%.*]] ]
// CHK-CXX-NEXT:    [[FROMBOOL13:%.*]] = zext i1 [[TOBOOL5]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL13]], i8* [[ATOMIC_TEMP12]], align 1
// CHK-CXX-NEXT:    [[TMP13:%.*]] = load i8, i8* [[ATOMIC_TEMP12]], align 1
// CHK-CXX-NEXT:    [[TMP14:%.*]] = cmpxchg i8* [[X]], i8 [[TMP12]], i8 [[TMP13]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP15]] = extractvalue { i8, i1 } [[TMP14]], 0
// CHK-CXX-NEXT:    [[TMP16:%.*]] = extractvalue { i8, i1 } [[TMP14]], 1
// CHK-CXX-NEXT:    br i1 [[TMP16]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP14]]
// CHK-CXX:       atomic_upd_exit:
// CHK-CXX-NEXT:    [[TMP17:%.*]] = zext i1 [[TOBOOL5]] to i8
// CHK-CXX-NEXT:    store i8 [[TMP17]], i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT17]]
// CHK-CXX:       atomic_cmp14:
// CHK-CXX-NEXT:    store i8 [[TMP15]], i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    [[TMP18:%.*]] = trunc i8 [[TMP15]] to i1
// CHK-CXX-NEXT:    [[CMP15:%.*]] = icmp ult i1 [[TMP18]], [[TOBOOL5]]
// CHK-CXX-NEXT:    [[FROMBOOL16:%.*]] = zext i1 [[CMP15]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL16]], i8* [[ATMP9]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP15]], label [[ATOMIC_CONT11]], label [[ATOMIC_EXIT17]]
// CHK-CXX:       atomic_exit17:
// CHK-CXX-NEXT:    [[TMP19:%.*]] = load i8, i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    [[TMP20:%.*]] = load i8, i8* [[ATMP9]], align 1
// CHK-CXX-NEXT:    store i8 [[TMP19]], i8* [[V]], align 1
// CHK-CXX-NEXT:    [[TMP21:%.*]] = load i8, i8* [[D]], align 1
// CHK-CXX-NEXT:    [[TOBOOL18:%.*]] = trunc i8 [[TMP21]] to i1
// CHK-CXX-NEXT:    [[TMP22:%.*]] = load i8, i8* [[E]], align 1
// CHK-CXX-NEXT:    [[TOBOOL19:%.*]] = trunc i8 [[TMP22]] to i1
// CHK-CXX-NEXT:    [[ATOMIC_LOAD20:%.*]] = load atomic i8, i8* [[X]] monotonic, align 1
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD20]], i8* [[ATMP21]], align 1
// CHK-CXX-NEXT:    [[TMP23:%.*]] = trunc i8 [[ATOMIC_LOAD20]] to i1
// CHK-CXX-NEXT:    [[CMP22:%.*]] = icmp eq i1 [[TMP23]], [[TOBOOL19]]
// CHK-CXX-NEXT:    [[FROMBOOL24:%.*]] = zext i1 [[CMP22]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL24]], i8* [[ATMP23]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP22]], label [[ATOMIC_CONT25:%.*]], label [[ATOMIC_EXIT32:%.*]]
// CHK-CXX:       atomic_cont25:
// CHK-CXX-NEXT:    [[TMP24:%.*]] = phi i8 [ [[ATOMIC_LOAD20]], [[ATOMIC_EXIT17]] ], [ [[TMP27:%.*]], [[ATOMIC_CMP29:%.*]] ]
// CHK-CXX-NEXT:    [[FROMBOOL27:%.*]] = zext i1 [[TOBOOL18]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL27]], i8* [[ATOMIC_TEMP26]], align 1
// CHK-CXX-NEXT:    [[TMP25:%.*]] = load i8, i8* [[ATOMIC_TEMP26]], align 1
// CHK-CXX-NEXT:    [[TMP26:%.*]] = cmpxchg i8* [[X]], i8 [[TMP24]], i8 [[TMP25]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP27]] = extractvalue { i8, i1 } [[TMP26]], 0
// CHK-CXX-NEXT:    [[TMP28:%.*]] = extractvalue { i8, i1 } [[TMP26]], 1
// CHK-CXX-NEXT:    br i1 [[TMP28]], label [[ATOMIC_UPD_EXIT28:%.*]], label [[ATOMIC_CMP29]]
// CHK-CXX:       atomic_upd_exit28:
// CHK-CXX-NEXT:    [[TMP29:%.*]] = zext i1 [[TOBOOL18]] to i8
// CHK-CXX-NEXT:    store i8 [[TMP29]], i8* [[ATMP21]], align 1
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT32]]
// CHK-CXX:       atomic_cmp29:
// CHK-CXX-NEXT:    store i8 [[TMP27]], i8* [[ATMP21]], align 1
// CHK-CXX-NEXT:    [[TMP30:%.*]] = trunc i8 [[TMP27]] to i1
// CHK-CXX-NEXT:    [[CMP30:%.*]] = icmp eq i1 [[TMP30]], [[TOBOOL19]]
// CHK-CXX-NEXT:    [[FROMBOOL31:%.*]] = zext i1 [[CMP30]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL31]], i8* [[ATMP23]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP30]], label [[ATOMIC_CONT25]], label [[ATOMIC_EXIT32]]
// CHK-CXX:       atomic_exit32:
// CHK-CXX-NEXT:    [[TMP31:%.*]] = load i8, i8* [[ATMP21]], align 1
// CHK-CXX-NEXT:    [[TMP32:%.*]] = load i8, i8* [[ATMP23]], align 1
// CHK-CXX-NEXT:    [[TMP33:%.*]] = trunc i8 [[TMP32]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP33]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-CXX:       atomic_capture:
// CHK-CXX-NEXT:    store i8 [[TMP31]], i8* [[V]], align 1
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-CXX:       atomic_capture_cont:
// CHK-CXX-NEXT:    [[TMP34:%.*]] = load i8, i8* [[D]], align 1
// CHK-CXX-NEXT:    [[TOBOOL33:%.*]] = trunc i8 [[TMP34]] to i1
// CHK-CXX-NEXT:    [[TMP35:%.*]] = load i8, i8* [[E]], align 1
// CHK-CXX-NEXT:    [[TOBOOL34:%.*]] = trunc i8 [[TMP35]] to i1
// CHK-CXX-NEXT:    [[ATOMIC_LOAD35:%.*]] = load atomic i8, i8* [[X]] monotonic, align 1
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD35]], i8* [[ATMP36]], align 1
// CHK-CXX-NEXT:    [[TMP36:%.*]] = trunc i8 [[ATOMIC_LOAD35]] to i1
// CHK-CXX-NEXT:    [[CMP37:%.*]] = icmp eq i1 [[TMP36]], [[TOBOOL34]]
// CHK-CXX-NEXT:    [[FROMBOOL39:%.*]] = zext i1 [[CMP37]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL39]], i8* [[ATMP38]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP37]], label [[ATOMIC_CONT40:%.*]], label [[ATOMIC_EXIT46:%.*]]
// CHK-CXX:       atomic_cont40:
// CHK-CXX-NEXT:    [[TMP37:%.*]] = phi i8 [ [[ATOMIC_LOAD35]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP40:%.*]], [[ATOMIC_CMP43:%.*]] ]
// CHK-CXX-NEXT:    [[FROMBOOL42:%.*]] = zext i1 [[TOBOOL33]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL42]], i8* [[ATOMIC_TEMP41]], align 1
// CHK-CXX-NEXT:    [[TMP38:%.*]] = load i8, i8* [[ATOMIC_TEMP41]], align 1
// CHK-CXX-NEXT:    [[TMP39:%.*]] = cmpxchg i8* [[X]], i8 [[TMP37]], i8 [[TMP38]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP40]] = extractvalue { i8, i1 } [[TMP39]], 0
// CHK-CXX-NEXT:    [[TMP41:%.*]] = extractvalue { i8, i1 } [[TMP39]], 1
// CHK-CXX-NEXT:    br i1 [[TMP41]], label [[ATOMIC_EXIT46]], label [[ATOMIC_CMP43]]
// CHK-CXX:       atomic_cmp43:
// CHK-CXX-NEXT:    store i8 [[TMP40]], i8* [[ATMP36]], align 1
// CHK-CXX-NEXT:    [[TMP42:%.*]] = trunc i8 [[TMP40]] to i1
// CHK-CXX-NEXT:    [[CMP44:%.*]] = icmp eq i1 [[TMP42]], [[TOBOOL34]]
// CHK-CXX-NEXT:    [[FROMBOOL45:%.*]] = zext i1 [[CMP44]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL45]], i8* [[ATMP38]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP44]], label [[ATOMIC_CONT40]], label [[ATOMIC_EXIT46]]
// CHK-CXX:       atomic_exit46:
// CHK-CXX-NEXT:    [[TMP43:%.*]] = load i8, i8* [[ATMP36]], align 1
// CHK-CXX-NEXT:    [[TMP44:%.*]] = load i8, i8* [[ATMP38]], align 1
// CHK-CXX-NEXT:    store i8 [[TMP44]], i8* [[R]], align 1
// CHK-CXX-NEXT:    [[TMP45:%.*]] = load i8, i8* [[D]], align 1
// CHK-CXX-NEXT:    [[TOBOOL47:%.*]] = trunc i8 [[TMP45]] to i1
// CHK-CXX-NEXT:    [[TMP46:%.*]] = load i8, i8* [[E]], align 1
// CHK-CXX-NEXT:    [[TOBOOL48:%.*]] = trunc i8 [[TMP46]] to i1
// CHK-CXX-NEXT:    [[ATOMIC_LOAD49:%.*]] = load atomic i8, i8* [[X]] monotonic, align 1
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD49]], i8* [[ATMP50]], align 1
// CHK-CXX-NEXT:    [[TMP47:%.*]] = trunc i8 [[ATOMIC_LOAD49]] to i1
// CHK-CXX-NEXT:    [[CMP51:%.*]] = icmp eq i1 [[TMP47]], [[TOBOOL48]]
// CHK-CXX-NEXT:    [[FROMBOOL53:%.*]] = zext i1 [[CMP51]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL53]], i8* [[ATMP52]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP51]], label [[ATOMIC_CONT54:%.*]], label [[ATOMIC_EXIT60:%.*]]
// CHK-CXX:       atomic_cont54:
// CHK-CXX-NEXT:    [[TMP48:%.*]] = phi i8 [ [[ATOMIC_LOAD49]], [[ATOMIC_EXIT46]] ], [ [[TMP51:%.*]], [[ATOMIC_CMP57:%.*]] ]
// CHK-CXX-NEXT:    [[FROMBOOL56:%.*]] = zext i1 [[TOBOOL47]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL56]], i8* [[ATOMIC_TEMP55]], align 1
// CHK-CXX-NEXT:    [[TMP49:%.*]] = load i8, i8* [[ATOMIC_TEMP55]], align 1
// CHK-CXX-NEXT:    [[TMP50:%.*]] = cmpxchg i8* [[X]], i8 [[TMP48]], i8 [[TMP49]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP51]] = extractvalue { i8, i1 } [[TMP50]], 0
// CHK-CXX-NEXT:    [[TMP52:%.*]] = extractvalue { i8, i1 } [[TMP50]], 1
// CHK-CXX-NEXT:    br i1 [[TMP52]], label [[ATOMIC_EXIT60]], label [[ATOMIC_CMP57]]
// CHK-CXX:       atomic_cmp57:
// CHK-CXX-NEXT:    store i8 [[TMP51]], i8* [[ATMP50]], align 1
// CHK-CXX-NEXT:    [[TMP53:%.*]] = trunc i8 [[TMP51]] to i1
// CHK-CXX-NEXT:    [[CMP58:%.*]] = icmp eq i1 [[TMP53]], [[TOBOOL48]]
// CHK-CXX-NEXT:    [[FROMBOOL59:%.*]] = zext i1 [[CMP58]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL59]], i8* [[ATMP52]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP58]], label [[ATOMIC_CONT54]], label [[ATOMIC_EXIT60]]
// CHK-CXX:       atomic_exit60:
// CHK-CXX-NEXT:    [[TMP54:%.*]] = load i8, i8* [[ATMP50]], align 1
// CHK-CXX-NEXT:    [[TMP55:%.*]] = load i8, i8* [[ATMP52]], align 1
// CHK-CXX-NEXT:    store i8 [[TMP55]], i8* [[R]], align 1
// CHK-CXX-NEXT:    [[TMP56:%.*]] = trunc i8 [[TMP55]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP56]], label [[ATOMIC_CAPTURE_CONT62:%.*]], label [[ATOMIC_CAPTURE61:%.*]]
// CHK-CXX:       atomic_capture61:
// CHK-CXX-NEXT:    store i8 [[TMP54]], i8* [[V]], align 1
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT62]]
// CHK-CXX:       atomic_capture_cont62:
// CHK-CXX-NEXT:    ret void
//
void test_bool() {
#ifdef __cplusplus
  bool x, expr, d, e, v, r;
#else
  _Bool x, expr, d, e, v, r;
#endif

  #pragma omp atomic compare capture
  { v = x; if (x < expr) { x = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (x < expr) { x = expr; } v = x; } // MAX

  #pragma omp atomic compare capture
  if (x == e) { x = d; } else { v = x; }

  #pragma omp atomic compare capture
  { r = x == e; if(r) { x = d; } }

  #pragma omp atomic compare capture
  { r = x == e; if(r) { x = d; } else { v = x; } }
}

// CHK-C-LABEL: @test_long_long(
// CHK-C-NEXT:  entry:
// CHK-C-NEXT:    [[X:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[EXPR:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[D:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[E:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[V:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[R:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[TMP:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP5:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP7:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP10:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP16:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP18:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP21:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP28:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP30:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP33:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP39:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP41:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP44:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[TMP0:%.*]] = load i64, i64* [[EXPR]], align 8
// CHK-C-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i64, i64* [[X]] monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD]], i64* [[TMP]], align 8
// CHK-C-NEXT:    [[CMP:%.*]] = icmp slt i64 [[ATOMIC_LOAD]], [[TMP0]]
// CHK-C-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-C:       atomic_cont:
// CHK-C-NEXT:    [[TMP1:%.*]] = phi i64 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP4:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP0]], i64* [[ATOMIC_TEMP]], align 8
// CHK-C-NEXT:    [[TMP2:%.*]] = load i64, i64* [[ATOMIC_TEMP]], align 8
// CHK-C-NEXT:    [[TMP3:%.*]] = cmpxchg i64* [[X]], i64 [[TMP1]], i64 [[TMP2]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP4]] = extractvalue { i64, i1 } [[TMP3]], 0
// CHK-C-NEXT:    [[TMP5:%.*]] = extractvalue { i64, i1 } [[TMP3]], 1
// CHK-C-NEXT:    br i1 [[TMP5]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-C:       atomic_cmp:
// CHK-C-NEXT:    store i64 [[TMP4]], i64* [[TMP]], align 8
// CHK-C-NEXT:    [[CMP2:%.*]] = icmp slt i64 [[TMP4]], [[TMP0]]
// CHK-C-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[CMP2]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL3]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP2]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-C:       atomic_exit:
// CHK-C-NEXT:    [[TMP6:%.*]] = load i64, i64* [[TMP]], align 8
// CHK-C-NEXT:    [[TMP7:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-C-NEXT:    store i64 [[TMP6]], i64* [[V]], align 8
// CHK-C-NEXT:    [[TMP8:%.*]] = load i64, i64* [[EXPR]], align 8
// CHK-C-NEXT:    [[ATOMIC_LOAD4:%.*]] = load atomic i64, i64* [[X]] monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD4]], i64* [[ATMP5]], align 8
// CHK-C-NEXT:    [[CMP6:%.*]] = icmp slt i64 [[ATOMIC_LOAD4]], [[TMP8]]
// CHK-C-NEXT:    [[FROMBOOL8:%.*]] = zext i1 [[CMP6]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL8]], i8* [[ATMP7]], align 1
// CHK-C-NEXT:    br i1 [[CMP6]], label [[ATOMIC_CONT9:%.*]], label [[ATOMIC_EXIT14:%.*]]
// CHK-C:       atomic_cont9:
// CHK-C-NEXT:    [[TMP9:%.*]] = phi i64 [ [[ATOMIC_LOAD4]], [[ATOMIC_EXIT]] ], [ [[TMP12:%.*]], [[ATOMIC_CMP11:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP8]], i64* [[ATOMIC_TEMP10]], align 8
// CHK-C-NEXT:    [[TMP10:%.*]] = load i64, i64* [[ATOMIC_TEMP10]], align 8
// CHK-C-NEXT:    [[TMP11:%.*]] = cmpxchg i64* [[X]], i64 [[TMP9]], i64 [[TMP10]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP12]] = extractvalue { i64, i1 } [[TMP11]], 0
// CHK-C-NEXT:    [[TMP13:%.*]] = extractvalue { i64, i1 } [[TMP11]], 1
// CHK-C-NEXT:    br i1 [[TMP13]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP11]]
// CHK-C:       atomic_upd_exit:
// CHK-C-NEXT:    store i64 [[TMP8]], i64* [[ATMP5]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_EXIT14]]
// CHK-C:       atomic_cmp11:
// CHK-C-NEXT:    store i64 [[TMP12]], i64* [[ATMP5]], align 8
// CHK-C-NEXT:    [[CMP12:%.*]] = icmp slt i64 [[TMP12]], [[TMP8]]
// CHK-C-NEXT:    [[FROMBOOL13:%.*]] = zext i1 [[CMP12]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL13]], i8* [[ATMP7]], align 1
// CHK-C-NEXT:    br i1 [[CMP12]], label [[ATOMIC_CONT9]], label [[ATOMIC_EXIT14]]
// CHK-C:       atomic_exit14:
// CHK-C-NEXT:    [[TMP14:%.*]] = load i64, i64* [[ATMP5]], align 8
// CHK-C-NEXT:    [[TMP15:%.*]] = load i8, i8* [[ATMP7]], align 1
// CHK-C-NEXT:    store i64 [[TMP14]], i64* [[V]], align 8
// CHK-C-NEXT:    [[TMP16:%.*]] = load i64, i64* [[D]], align 8
// CHK-C-NEXT:    [[TMP17:%.*]] = load i64, i64* [[E]], align 8
// CHK-C-NEXT:    [[ATOMIC_LOAD15:%.*]] = load atomic i64, i64* [[X]] monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD15]], i64* [[ATMP16]], align 8
// CHK-C-NEXT:    [[CMP17:%.*]] = icmp eq i64 [[ATOMIC_LOAD15]], [[TMP17]]
// CHK-C-NEXT:    [[FROMBOOL19:%.*]] = zext i1 [[CMP17]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL19]], i8* [[ATMP18]], align 1
// CHK-C-NEXT:    br i1 [[CMP17]], label [[ATOMIC_CONT20:%.*]], label [[ATOMIC_EXIT26:%.*]]
// CHK-C:       atomic_cont20:
// CHK-C-NEXT:    [[TMP18:%.*]] = phi i64 [ [[ATOMIC_LOAD15]], [[ATOMIC_EXIT14]] ], [ [[TMP21:%.*]], [[ATOMIC_CMP23:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP16]], i64* [[ATOMIC_TEMP21]], align 8
// CHK-C-NEXT:    [[TMP19:%.*]] = load i64, i64* [[ATOMIC_TEMP21]], align 8
// CHK-C-NEXT:    [[TMP20:%.*]] = cmpxchg i64* [[X]], i64 [[TMP18]], i64 [[TMP19]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP21]] = extractvalue { i64, i1 } [[TMP20]], 0
// CHK-C-NEXT:    [[TMP22:%.*]] = extractvalue { i64, i1 } [[TMP20]], 1
// CHK-C-NEXT:    br i1 [[TMP22]], label [[ATOMIC_UPD_EXIT22:%.*]], label [[ATOMIC_CMP23]]
// CHK-C:       atomic_upd_exit22:
// CHK-C-NEXT:    store i64 [[TMP16]], i64* [[ATMP16]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_EXIT26]]
// CHK-C:       atomic_cmp23:
// CHK-C-NEXT:    store i64 [[TMP21]], i64* [[ATMP16]], align 8
// CHK-C-NEXT:    [[CMP24:%.*]] = icmp eq i64 [[TMP21]], [[TMP17]]
// CHK-C-NEXT:    [[FROMBOOL25:%.*]] = zext i1 [[CMP24]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL25]], i8* [[ATMP18]], align 1
// CHK-C-NEXT:    br i1 [[CMP24]], label [[ATOMIC_CONT20]], label [[ATOMIC_EXIT26]]
// CHK-C:       atomic_exit26:
// CHK-C-NEXT:    [[TMP23:%.*]] = load i64, i64* [[ATMP16]], align 8
// CHK-C-NEXT:    [[TMP24:%.*]] = load i8, i8* [[ATMP18]], align 1
// CHK-C-NEXT:    [[TMP25:%.*]] = trunc i8 [[TMP24]] to i1
// CHK-C-NEXT:    br i1 [[TMP25]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-C:       atomic_capture:
// CHK-C-NEXT:    store i64 [[TMP23]], i64* [[V]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-C:       atomic_capture_cont:
// CHK-C-NEXT:    [[TMP26:%.*]] = load i64, i64* [[D]], align 8
// CHK-C-NEXT:    [[TMP27:%.*]] = load i64, i64* [[E]], align 8
// CHK-C-NEXT:    [[ATOMIC_LOAD27:%.*]] = load atomic i64, i64* [[X]] monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD27]], i64* [[ATMP28]], align 8
// CHK-C-NEXT:    [[CMP29:%.*]] = icmp eq i64 [[ATOMIC_LOAD27]], [[TMP27]]
// CHK-C-NEXT:    [[FROMBOOL31:%.*]] = zext i1 [[CMP29]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL31]], i8* [[ATMP30]], align 1
// CHK-C-NEXT:    br i1 [[CMP29]], label [[ATOMIC_CONT32:%.*]], label [[ATOMIC_EXIT37:%.*]]
// CHK-C:       atomic_cont32:
// CHK-C-NEXT:    [[TMP28:%.*]] = phi i64 [ [[ATOMIC_LOAD27]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP31:%.*]], [[ATOMIC_CMP34:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP26]], i64* [[ATOMIC_TEMP33]], align 8
// CHK-C-NEXT:    [[TMP29:%.*]] = load i64, i64* [[ATOMIC_TEMP33]], align 8
// CHK-C-NEXT:    [[TMP30:%.*]] = cmpxchg i64* [[X]], i64 [[TMP28]], i64 [[TMP29]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP31]] = extractvalue { i64, i1 } [[TMP30]], 0
// CHK-C-NEXT:    [[TMP32:%.*]] = extractvalue { i64, i1 } [[TMP30]], 1
// CHK-C-NEXT:    br i1 [[TMP32]], label [[ATOMIC_EXIT37]], label [[ATOMIC_CMP34]]
// CHK-C:       atomic_cmp34:
// CHK-C-NEXT:    store i64 [[TMP31]], i64* [[ATMP28]], align 8
// CHK-C-NEXT:    [[CMP35:%.*]] = icmp eq i64 [[TMP31]], [[TMP27]]
// CHK-C-NEXT:    [[FROMBOOL36:%.*]] = zext i1 [[CMP35]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL36]], i8* [[ATMP30]], align 1
// CHK-C-NEXT:    br i1 [[CMP35]], label [[ATOMIC_CONT32]], label [[ATOMIC_EXIT37]]
// CHK-C:       atomic_exit37:
// CHK-C-NEXT:    [[TMP33:%.*]] = load i64, i64* [[ATMP28]], align 8
// CHK-C-NEXT:    [[TMP34:%.*]] = load i8, i8* [[ATMP30]], align 1
// CHK-C-NEXT:    [[CONV:%.*]] = zext i8 [[TMP34]] to i64
// CHK-C-NEXT:    store i64 [[CONV]], i64* [[R]], align 8
// CHK-C-NEXT:    [[TMP35:%.*]] = load i64, i64* [[D]], align 8
// CHK-C-NEXT:    [[TMP36:%.*]] = load i64, i64* [[E]], align 8
// CHK-C-NEXT:    [[ATOMIC_LOAD38:%.*]] = load atomic i64, i64* [[X]] monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD38]], i64* [[ATMP39]], align 8
// CHK-C-NEXT:    [[CMP40:%.*]] = icmp eq i64 [[ATOMIC_LOAD38]], [[TMP36]]
// CHK-C-NEXT:    [[FROMBOOL42:%.*]] = zext i1 [[CMP40]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL42]], i8* [[ATMP41]], align 1
// CHK-C-NEXT:    br i1 [[CMP40]], label [[ATOMIC_CONT43:%.*]], label [[ATOMIC_EXIT48:%.*]]
// CHK-C:       atomic_cont43:
// CHK-C-NEXT:    [[TMP37:%.*]] = phi i64 [ [[ATOMIC_LOAD38]], [[ATOMIC_EXIT37]] ], [ [[TMP40:%.*]], [[ATOMIC_CMP45:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP35]], i64* [[ATOMIC_TEMP44]], align 8
// CHK-C-NEXT:    [[TMP38:%.*]] = load i64, i64* [[ATOMIC_TEMP44]], align 8
// CHK-C-NEXT:    [[TMP39:%.*]] = cmpxchg i64* [[X]], i64 [[TMP37]], i64 [[TMP38]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP40]] = extractvalue { i64, i1 } [[TMP39]], 0
// CHK-C-NEXT:    [[TMP41:%.*]] = extractvalue { i64, i1 } [[TMP39]], 1
// CHK-C-NEXT:    br i1 [[TMP41]], label [[ATOMIC_EXIT48]], label [[ATOMIC_CMP45]]
// CHK-C:       atomic_cmp45:
// CHK-C-NEXT:    store i64 [[TMP40]], i64* [[ATMP39]], align 8
// CHK-C-NEXT:    [[CMP46:%.*]] = icmp eq i64 [[TMP40]], [[TMP36]]
// CHK-C-NEXT:    [[FROMBOOL47:%.*]] = zext i1 [[CMP46]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL47]], i8* [[ATMP41]], align 1
// CHK-C-NEXT:    br i1 [[CMP46]], label [[ATOMIC_CONT43]], label [[ATOMIC_EXIT48]]
// CHK-C:       atomic_exit48:
// CHK-C-NEXT:    [[TMP42:%.*]] = load i64, i64* [[ATMP39]], align 8
// CHK-C-NEXT:    [[TMP43:%.*]] = load i8, i8* [[ATMP41]], align 1
// CHK-C-NEXT:    [[CONV49:%.*]] = zext i8 [[TMP43]] to i64
// CHK-C-NEXT:    store i64 [[CONV49]], i64* [[R]], align 8
// CHK-C-NEXT:    [[TMP44:%.*]] = trunc i8 [[TMP43]] to i1
// CHK-C-NEXT:    br i1 [[TMP44]], label [[ATOMIC_CAPTURE_CONT51:%.*]], label [[ATOMIC_CAPTURE50:%.*]]
// CHK-C:       atomic_capture50:
// CHK-C-NEXT:    store i64 [[TMP42]], i64* [[V]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT51]]
// CHK-C:       atomic_capture_cont51:
// CHK-C-NEXT:    ret void
//
// CHK-CXX-LABEL: @_Z14test_long_longv(
// CHK-CXX-NEXT:  entry:
// CHK-CXX-NEXT:    [[X:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[EXPR:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[D:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[E:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[V:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[R:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[TMP:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP5:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP7:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP10:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP16:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP18:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP21:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP28:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP30:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP33:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP39:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP41:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP44:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[TMP0:%.*]] = load i64, i64* [[EXPR]], align 8
// CHK-CXX-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i64, i64* [[X]] monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD]], i64* [[TMP]], align 8
// CHK-CXX-NEXT:    [[CMP:%.*]] = icmp slt i64 [[ATOMIC_LOAD]], [[TMP0]]
// CHK-CXX-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-CXX:       atomic_cont:
// CHK-CXX-NEXT:    [[TMP1:%.*]] = phi i64 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP4:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP0]], i64* [[ATOMIC_TEMP]], align 8
// CHK-CXX-NEXT:    [[TMP2:%.*]] = load i64, i64* [[ATOMIC_TEMP]], align 8
// CHK-CXX-NEXT:    [[TMP3:%.*]] = cmpxchg i64* [[X]], i64 [[TMP1]], i64 [[TMP2]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP4]] = extractvalue { i64, i1 } [[TMP3]], 0
// CHK-CXX-NEXT:    [[TMP5:%.*]] = extractvalue { i64, i1 } [[TMP3]], 1
// CHK-CXX-NEXT:    br i1 [[TMP5]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-CXX:       atomic_cmp:
// CHK-CXX-NEXT:    store i64 [[TMP4]], i64* [[TMP]], align 8
// CHK-CXX-NEXT:    [[CMP2:%.*]] = icmp slt i64 [[TMP4]], [[TMP0]]
// CHK-CXX-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[CMP2]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL3]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP2]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-CXX:       atomic_exit:
// CHK-CXX-NEXT:    [[TMP6:%.*]] = load i64, i64* [[TMP]], align 8
// CHK-CXX-NEXT:    [[TMP7:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    store i64 [[TMP6]], i64* [[V]], align 8
// CHK-CXX-NEXT:    [[TMP8:%.*]] = load i64, i64* [[EXPR]], align 8
// CHK-CXX-NEXT:    [[ATOMIC_LOAD4:%.*]] = load atomic i64, i64* [[X]] monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD4]], i64* [[ATMP5]], align 8
// CHK-CXX-NEXT:    [[CMP6:%.*]] = icmp slt i64 [[ATOMIC_LOAD4]], [[TMP8]]
// CHK-CXX-NEXT:    [[FROMBOOL8:%.*]] = zext i1 [[CMP6]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL8]], i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP6]], label [[ATOMIC_CONT9:%.*]], label [[ATOMIC_EXIT14:%.*]]
// CHK-CXX:       atomic_cont9:
// CHK-CXX-NEXT:    [[TMP9:%.*]] = phi i64 [ [[ATOMIC_LOAD4]], [[ATOMIC_EXIT]] ], [ [[TMP12:%.*]], [[ATOMIC_CMP11:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP8]], i64* [[ATOMIC_TEMP10]], align 8
// CHK-CXX-NEXT:    [[TMP10:%.*]] = load i64, i64* [[ATOMIC_TEMP10]], align 8
// CHK-CXX-NEXT:    [[TMP11:%.*]] = cmpxchg i64* [[X]], i64 [[TMP9]], i64 [[TMP10]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP12]] = extractvalue { i64, i1 } [[TMP11]], 0
// CHK-CXX-NEXT:    [[TMP13:%.*]] = extractvalue { i64, i1 } [[TMP11]], 1
// CHK-CXX-NEXT:    br i1 [[TMP13]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP11]]
// CHK-CXX:       atomic_upd_exit:
// CHK-CXX-NEXT:    store i64 [[TMP8]], i64* [[ATMP5]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT14]]
// CHK-CXX:       atomic_cmp11:
// CHK-CXX-NEXT:    store i64 [[TMP12]], i64* [[ATMP5]], align 8
// CHK-CXX-NEXT:    [[CMP12:%.*]] = icmp slt i64 [[TMP12]], [[TMP8]]
// CHK-CXX-NEXT:    [[FROMBOOL13:%.*]] = zext i1 [[CMP12]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL13]], i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP12]], label [[ATOMIC_CONT9]], label [[ATOMIC_EXIT14]]
// CHK-CXX:       atomic_exit14:
// CHK-CXX-NEXT:    [[TMP14:%.*]] = load i64, i64* [[ATMP5]], align 8
// CHK-CXX-NEXT:    [[TMP15:%.*]] = load i8, i8* [[ATMP7]], align 1
// CHK-CXX-NEXT:    store i64 [[TMP14]], i64* [[V]], align 8
// CHK-CXX-NEXT:    [[TMP16:%.*]] = load i64, i64* [[D]], align 8
// CHK-CXX-NEXT:    [[TMP17:%.*]] = load i64, i64* [[E]], align 8
// CHK-CXX-NEXT:    [[ATOMIC_LOAD15:%.*]] = load atomic i64, i64* [[X]] monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD15]], i64* [[ATMP16]], align 8
// CHK-CXX-NEXT:    [[CMP17:%.*]] = icmp eq i64 [[ATOMIC_LOAD15]], [[TMP17]]
// CHK-CXX-NEXT:    [[FROMBOOL19:%.*]] = zext i1 [[CMP17]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL19]], i8* [[ATMP18]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP17]], label [[ATOMIC_CONT20:%.*]], label [[ATOMIC_EXIT26:%.*]]
// CHK-CXX:       atomic_cont20:
// CHK-CXX-NEXT:    [[TMP18:%.*]] = phi i64 [ [[ATOMIC_LOAD15]], [[ATOMIC_EXIT14]] ], [ [[TMP21:%.*]], [[ATOMIC_CMP23:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP16]], i64* [[ATOMIC_TEMP21]], align 8
// CHK-CXX-NEXT:    [[TMP19:%.*]] = load i64, i64* [[ATOMIC_TEMP21]], align 8
// CHK-CXX-NEXT:    [[TMP20:%.*]] = cmpxchg i64* [[X]], i64 [[TMP18]], i64 [[TMP19]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP21]] = extractvalue { i64, i1 } [[TMP20]], 0
// CHK-CXX-NEXT:    [[TMP22:%.*]] = extractvalue { i64, i1 } [[TMP20]], 1
// CHK-CXX-NEXT:    br i1 [[TMP22]], label [[ATOMIC_UPD_EXIT22:%.*]], label [[ATOMIC_CMP23]]
// CHK-CXX:       atomic_upd_exit22:
// CHK-CXX-NEXT:    store i64 [[TMP16]], i64* [[ATMP16]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT26]]
// CHK-CXX:       atomic_cmp23:
// CHK-CXX-NEXT:    store i64 [[TMP21]], i64* [[ATMP16]], align 8
// CHK-CXX-NEXT:    [[CMP24:%.*]] = icmp eq i64 [[TMP21]], [[TMP17]]
// CHK-CXX-NEXT:    [[FROMBOOL25:%.*]] = zext i1 [[CMP24]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL25]], i8* [[ATMP18]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP24]], label [[ATOMIC_CONT20]], label [[ATOMIC_EXIT26]]
// CHK-CXX:       atomic_exit26:
// CHK-CXX-NEXT:    [[TMP23:%.*]] = load i64, i64* [[ATMP16]], align 8
// CHK-CXX-NEXT:    [[TMP24:%.*]] = load i8, i8* [[ATMP18]], align 1
// CHK-CXX-NEXT:    [[TMP25:%.*]] = trunc i8 [[TMP24]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP25]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-CXX:       atomic_capture:
// CHK-CXX-NEXT:    store i64 [[TMP23]], i64* [[V]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-CXX:       atomic_capture_cont:
// CHK-CXX-NEXT:    [[TMP26:%.*]] = load i64, i64* [[D]], align 8
// CHK-CXX-NEXT:    [[TMP27:%.*]] = load i64, i64* [[E]], align 8
// CHK-CXX-NEXT:    [[ATOMIC_LOAD27:%.*]] = load atomic i64, i64* [[X]] monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD27]], i64* [[ATMP28]], align 8
// CHK-CXX-NEXT:    [[CMP29:%.*]] = icmp eq i64 [[ATOMIC_LOAD27]], [[TMP27]]
// CHK-CXX-NEXT:    [[FROMBOOL31:%.*]] = zext i1 [[CMP29]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL31]], i8* [[ATMP30]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP29]], label [[ATOMIC_CONT32:%.*]], label [[ATOMIC_EXIT37:%.*]]
// CHK-CXX:       atomic_cont32:
// CHK-CXX-NEXT:    [[TMP28:%.*]] = phi i64 [ [[ATOMIC_LOAD27]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP31:%.*]], [[ATOMIC_CMP34:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP26]], i64* [[ATOMIC_TEMP33]], align 8
// CHK-CXX-NEXT:    [[TMP29:%.*]] = load i64, i64* [[ATOMIC_TEMP33]], align 8
// CHK-CXX-NEXT:    [[TMP30:%.*]] = cmpxchg i64* [[X]], i64 [[TMP28]], i64 [[TMP29]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP31]] = extractvalue { i64, i1 } [[TMP30]], 0
// CHK-CXX-NEXT:    [[TMP32:%.*]] = extractvalue { i64, i1 } [[TMP30]], 1
// CHK-CXX-NEXT:    br i1 [[TMP32]], label [[ATOMIC_EXIT37]], label [[ATOMIC_CMP34]]
// CHK-CXX:       atomic_cmp34:
// CHK-CXX-NEXT:    store i64 [[TMP31]], i64* [[ATMP28]], align 8
// CHK-CXX-NEXT:    [[CMP35:%.*]] = icmp eq i64 [[TMP31]], [[TMP27]]
// CHK-CXX-NEXT:    [[FROMBOOL36:%.*]] = zext i1 [[CMP35]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL36]], i8* [[ATMP30]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP35]], label [[ATOMIC_CONT32]], label [[ATOMIC_EXIT37]]
// CHK-CXX:       atomic_exit37:
// CHK-CXX-NEXT:    [[TMP33:%.*]] = load i64, i64* [[ATMP28]], align 8
// CHK-CXX-NEXT:    [[TMP34:%.*]] = load i8, i8* [[ATMP30]], align 1
// CHK-CXX-NEXT:    [[CONV:%.*]] = zext i8 [[TMP34]] to i64
// CHK-CXX-NEXT:    store i64 [[CONV]], i64* [[R]], align 8
// CHK-CXX-NEXT:    [[TMP35:%.*]] = load i64, i64* [[D]], align 8
// CHK-CXX-NEXT:    [[TMP36:%.*]] = load i64, i64* [[E]], align 8
// CHK-CXX-NEXT:    [[ATOMIC_LOAD38:%.*]] = load atomic i64, i64* [[X]] monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD38]], i64* [[ATMP39]], align 8
// CHK-CXX-NEXT:    [[CMP40:%.*]] = icmp eq i64 [[ATOMIC_LOAD38]], [[TMP36]]
// CHK-CXX-NEXT:    [[FROMBOOL42:%.*]] = zext i1 [[CMP40]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL42]], i8* [[ATMP41]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP40]], label [[ATOMIC_CONT43:%.*]], label [[ATOMIC_EXIT48:%.*]]
// CHK-CXX:       atomic_cont43:
// CHK-CXX-NEXT:    [[TMP37:%.*]] = phi i64 [ [[ATOMIC_LOAD38]], [[ATOMIC_EXIT37]] ], [ [[TMP40:%.*]], [[ATOMIC_CMP45:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP35]], i64* [[ATOMIC_TEMP44]], align 8
// CHK-CXX-NEXT:    [[TMP38:%.*]] = load i64, i64* [[ATOMIC_TEMP44]], align 8
// CHK-CXX-NEXT:    [[TMP39:%.*]] = cmpxchg i64* [[X]], i64 [[TMP37]], i64 [[TMP38]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP40]] = extractvalue { i64, i1 } [[TMP39]], 0
// CHK-CXX-NEXT:    [[TMP41:%.*]] = extractvalue { i64, i1 } [[TMP39]], 1
// CHK-CXX-NEXT:    br i1 [[TMP41]], label [[ATOMIC_EXIT48]], label [[ATOMIC_CMP45]]
// CHK-CXX:       atomic_cmp45:
// CHK-CXX-NEXT:    store i64 [[TMP40]], i64* [[ATMP39]], align 8
// CHK-CXX-NEXT:    [[CMP46:%.*]] = icmp eq i64 [[TMP40]], [[TMP36]]
// CHK-CXX-NEXT:    [[FROMBOOL47:%.*]] = zext i1 [[CMP46]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL47]], i8* [[ATMP41]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP46]], label [[ATOMIC_CONT43]], label [[ATOMIC_EXIT48]]
// CHK-CXX:       atomic_exit48:
// CHK-CXX-NEXT:    [[TMP42:%.*]] = load i64, i64* [[ATMP39]], align 8
// CHK-CXX-NEXT:    [[TMP43:%.*]] = load i8, i8* [[ATMP41]], align 1
// CHK-CXX-NEXT:    [[CONV49:%.*]] = zext i8 [[TMP43]] to i64
// CHK-CXX-NEXT:    store i64 [[CONV49]], i64* [[R]], align 8
// CHK-CXX-NEXT:    [[TMP44:%.*]] = trunc i8 [[TMP43]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP44]], label [[ATOMIC_CAPTURE_CONT51:%.*]], label [[ATOMIC_CAPTURE50:%.*]]
// CHK-CXX:       atomic_capture50:
// CHK-CXX-NEXT:    store i64 [[TMP42]], i64* [[V]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT51]]
// CHK-CXX:       atomic_capture_cont51:
// CHK-CXX-NEXT:    ret void
//
void test_long_long() {
  long long x, expr, d, e, v, r;

  #pragma omp atomic compare capture
  { v = x; if (x < expr) { x = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (x < expr) { x = expr; } v = x; } // MAX

  #pragma omp atomic compare capture
  if (x == e) { x = d; } else { v = x; }

  #pragma omp atomic compare capture
  { r = x == e; if(r) { x = d; } }

  #pragma omp atomic compare capture
  { r = x == e; if(r) { x = d; } else { v = x; } }
}

#ifdef LIBCALLS
void test_Complex_float()
{
  _Complex float x, expr, d, e, v;
  int r;

  #pragma omp atomic compare capture
  { v = x; if (x == e) { x = d; } }

  #pragma omp atomic compare capture
  { if (x == e) { x = d; } v = x; }

  #pragma omp atomic compare capture
  if (x == e) { x = d; } else { v = x; }

  #pragma omp atomic compare capture
  { r = x == e; if(r) { x = d; } }

  #pragma omp atomic compare capture
  { r = x == e; if(r) { x = d; } else { v = x; } }
}

void test_long_double() {
  long double x, expr, d, e;
  short r;

  #pragma omp atomic compare capture
  { v = x; if (x < expr) { x = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (x < expr) { x = expr; } v = x; } // MAX

  #pragma omp atomic compare capture
  if (x == e) { x = d; } else { v = x; }

  #pragma omp atomic compare capture
  { r = x == e; if(r) { x = d; } }

  #pragma omp atomic compare capture
  { r = x == e; if(r) { x = d; } else { v = x; } }
}

void test_vec() {
  typedef int int4 __attribute__((__vector_size__(16)));
  int4 x;
  int expr, d, e, v;
  long r;

  #pragma omp atomic compare
  { v = x[1]; if (x[1] < expr) { x[1] = expr; } } // MAX

  #pragma omp atomic compare
  { if (x[1] < expr) { x[1] = expr; } v = x[1]; } // MAX

  #pragma omp atomic compare capture
  if (x == e) { x = d; } else { v = x; }

  #pragma omp atomic compare capture
  { r = x == e; if(r) { x = d; } }

  #pragma omp atomic compare capture
  { r = x == e; if(r) { x = d; } else { v = x; } }
}
#endif


struct BitFields {
  int : 32;
  int a : 31;
} bfx;

struct BitFields_packed {
  int : 32;
  int a : 31;
} __attribute__ ((__packed__)) bfx_packed;

struct BitFields2 {
  int : 31;
  int a : 1;
} bfx2;

struct BitFields2_packed {
  int : 31;
  int a : 1;
} __attribute__ ((__packed__)) bfx2_packed;

struct BitFields3 {
  int : 11;
  int a : 14;
} bfx3;

struct BitFields3_packed {
  int : 11;
  int a : 14;
} __attribute__ ((__packed__)) bfx3_packed;

struct BitFields4 {
  short : 16;
  int a: 1;
  long b : 7;
} bfx4;

struct BitFields4_packed {
  short : 16;
  int a: 1;
  long b : 7;
} __attribute__ ((__packed__)) bfx4_packed;

// CHK-C-LABEL: @test_bitfield(
// CHK-C-NEXT:  entry:
// CHK-C-NEXT:    [[EXPR:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[D:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[E:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[V:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[R:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[TMP:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP2:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP4:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP11:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP12:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP17:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP20:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP26:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP34:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP35:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP40:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP43:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP50:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP58:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP59:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP64:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP67:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP73:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP81:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP82:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP87:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP90:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP96:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP107:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP108:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP112:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP115:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP122:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP129:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP130:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP134:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP137:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP145:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP152:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP153:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP157:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP160:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP168:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP177:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP178:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP182:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP185:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP192:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP200:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP201:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP205:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP208:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP215:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP225:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP226:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP230:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP233:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP240:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP248:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP249:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP254:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP257:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP265:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP273:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP274:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP279:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP282:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP290:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP300:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP301:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP306:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP309:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP316:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP325:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP326:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP331:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP334:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP341:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP352:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP353:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP358:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP361:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP368:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP376:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP377:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP382:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP385:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP393:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP401:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP402:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP407:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP410:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP418:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP428:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP429:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP434:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP437:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP444:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP453:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP454:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP459:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP462:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP469:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATMP480:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP481:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP487:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP490:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP497:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP506:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP507:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP513:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP516:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP524:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP533:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP534:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP540:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP543:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP551:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP562:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP563:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP569:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP572:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP579:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP589:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP590:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP596:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP599:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP606:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP619:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP620:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP625:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP628:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP635:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP645:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP646:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP651:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP654:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP662:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP673:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP674:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP679:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP682:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP690:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP703:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP704:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP709:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP712:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP719:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP730:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP731:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP736:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP739:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP746:%.*]] = alloca i64, align 8
// CHK-C-NEXT:    [[ATMP758:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP759:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP765:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP768:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP774:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP783:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP784:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP790:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP793:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP800:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP809:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP810:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP816:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP819:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP826:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP837:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP838:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP844:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP847:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP853:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP863:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP864:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATMP870:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP873:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP879:%.*]] = alloca i32, align 1
// CHK-C-NEXT:    [[TMP0:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i32, i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD]], i32* [[ATOMIC_TEMP]], align 4
// CHK-C-NEXT:    [[BF_LOAD:%.*]] = load i32, i32* [[ATOMIC_TEMP]], align 4
// CHK-C-NEXT:    [[BF_SHL:%.*]] = shl i32 [[BF_LOAD]], 1
// CHK-C-NEXT:    [[BF_ASHR:%.*]] = ashr i32 [[BF_SHL]], 1
// CHK-C-NEXT:    store i32 [[BF_ASHR]], i32* [[TMP]], align 4
// CHK-C-NEXT:    [[CMP:%.*]] = icmp slt i32 [[BF_ASHR]], [[TMP0]]
// CHK-C-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-C:       atomic_cont:
// CHK-C-NEXT:    [[TMP1:%.*]] = phi i32 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP4:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP1]], i32* [[ATOMIC_TEMP2]], align 4
// CHK-C-NEXT:    [[BF_LOAD3:%.*]] = load i32, i32* [[ATOMIC_TEMP2]], align 4
// CHK-C-NEXT:    [[BF_VALUE:%.*]] = and i32 [[TMP0]], 2147483647
// CHK-C-NEXT:    [[BF_CLEAR:%.*]] = and i32 [[BF_LOAD3]], -2147483648
// CHK-C-NEXT:    [[BF_SET:%.*]] = or i32 [[BF_CLEAR]], [[BF_VALUE]]
// CHK-C-NEXT:    store i32 [[BF_SET]], i32* [[ATOMIC_TEMP2]], align 4
// CHK-C-NEXT:    [[TMP2:%.*]] = load i32, i32* [[ATOMIC_TEMP2]], align 4
// CHK-C-NEXT:    [[TMP3:%.*]] = cmpxchg i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*), i32 [[TMP1]], i32 [[TMP2]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP4]] = extractvalue { i32, i1 } [[TMP3]], 0
// CHK-C-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i1 } [[TMP3]], 1
// CHK-C-NEXT:    br i1 [[TMP5]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-C:       atomic_cmp:
// CHK-C-NEXT:    store i32 [[TMP4]], i32* [[ATOMIC_TEMP4]], align 4
// CHK-C-NEXT:    [[BF_LOAD5:%.*]] = load i32, i32* [[ATOMIC_TEMP4]], align 4
// CHK-C-NEXT:    [[BF_SHL6:%.*]] = shl i32 [[BF_LOAD5]], 1
// CHK-C-NEXT:    [[BF_ASHR7:%.*]] = ashr i32 [[BF_SHL6]], 1
// CHK-C-NEXT:    store i32 [[BF_ASHR7]], i32* [[TMP]], align 4
// CHK-C-NEXT:    [[CMP8:%.*]] = icmp slt i32 [[BF_ASHR7]], [[TMP0]]
// CHK-C-NEXT:    [[FROMBOOL9:%.*]] = zext i1 [[CMP8]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL9]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP8]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-C:       atomic_exit:
// CHK-C-NEXT:    [[TMP6:%.*]] = load i32, i32* [[TMP]], align 4
// CHK-C-NEXT:    [[TMP7:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-C-NEXT:    store i32 [[TMP6]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP8:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD10:%.*]] = load atomic i32, i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD10]], i32* [[ATOMIC_TEMP12]], align 4
// CHK-C-NEXT:    [[BF_LOAD13:%.*]] = load i32, i32* [[ATOMIC_TEMP12]], align 4
// CHK-C-NEXT:    [[BF_SHL14:%.*]] = shl i32 [[BF_LOAD13]], 1
// CHK-C-NEXT:    [[BF_ASHR15:%.*]] = ashr i32 [[BF_SHL14]], 1
// CHK-C-NEXT:    store i32 [[BF_ASHR15]], i32* [[ATMP11]], align 4
// CHK-C-NEXT:    [[CMP16:%.*]] = icmp slt i32 [[BF_ASHR15]], [[TMP8]]
// CHK-C-NEXT:    [[FROMBOOL18:%.*]] = zext i1 [[CMP16]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL18]], i8* [[ATMP17]], align 1
// CHK-C-NEXT:    br i1 [[CMP16]], label [[ATOMIC_CONT19:%.*]], label [[ATOMIC_EXIT32:%.*]]
// CHK-C:       atomic_cont19:
// CHK-C-NEXT:    [[TMP9:%.*]] = phi i32 [ [[ATOMIC_LOAD10]], [[ATOMIC_EXIT]] ], [ [[TMP12:%.*]], [[ATOMIC_CMP25:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP9]], i32* [[ATOMIC_TEMP20]], align 4
// CHK-C-NEXT:    [[BF_LOAD21:%.*]] = load i32, i32* [[ATOMIC_TEMP20]], align 4
// CHK-C-NEXT:    [[BF_VALUE22:%.*]] = and i32 [[TMP8]], 2147483647
// CHK-C-NEXT:    [[BF_CLEAR23:%.*]] = and i32 [[BF_LOAD21]], -2147483648
// CHK-C-NEXT:    [[BF_SET24:%.*]] = or i32 [[BF_CLEAR23]], [[BF_VALUE22]]
// CHK-C-NEXT:    store i32 [[BF_SET24]], i32* [[ATOMIC_TEMP20]], align 4
// CHK-C-NEXT:    [[TMP10:%.*]] = load i32, i32* [[ATOMIC_TEMP20]], align 4
// CHK-C-NEXT:    [[TMP11:%.*]] = cmpxchg i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*), i32 [[TMP9]], i32 [[TMP10]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP12]] = extractvalue { i32, i1 } [[TMP11]], 0
// CHK-C-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i1 } [[TMP11]], 1
// CHK-C-NEXT:    br i1 [[TMP13]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP25]]
// CHK-C:       atomic_upd_exit:
// CHK-C-NEXT:    store i32 [[TMP8]], i32* [[ATMP11]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT32]]
// CHK-C:       atomic_cmp25:
// CHK-C-NEXT:    store i32 [[TMP12]], i32* [[ATOMIC_TEMP26]], align 4
// CHK-C-NEXT:    [[BF_LOAD27:%.*]] = load i32, i32* [[ATOMIC_TEMP26]], align 4
// CHK-C-NEXT:    [[BF_SHL28:%.*]] = shl i32 [[BF_LOAD27]], 1
// CHK-C-NEXT:    [[BF_ASHR29:%.*]] = ashr i32 [[BF_SHL28]], 1
// CHK-C-NEXT:    store i32 [[BF_ASHR29]], i32* [[ATMP11]], align 4
// CHK-C-NEXT:    [[CMP30:%.*]] = icmp slt i32 [[BF_ASHR29]], [[TMP8]]
// CHK-C-NEXT:    [[FROMBOOL31:%.*]] = zext i1 [[CMP30]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL31]], i8* [[ATMP17]], align 1
// CHK-C-NEXT:    br i1 [[CMP30]], label [[ATOMIC_CONT19]], label [[ATOMIC_EXIT32]]
// CHK-C:       atomic_exit32:
// CHK-C-NEXT:    [[TMP14:%.*]] = load i32, i32* [[ATMP11]], align 4
// CHK-C-NEXT:    [[TMP15:%.*]] = load i8, i8* [[ATMP17]], align 1
// CHK-C-NEXT:    store i32 [[TMP14]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP16:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP17:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD33:%.*]] = load atomic i32, i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD33]], i32* [[ATOMIC_TEMP35]], align 4
// CHK-C-NEXT:    [[BF_LOAD36:%.*]] = load i32, i32* [[ATOMIC_TEMP35]], align 4
// CHK-C-NEXT:    [[BF_SHL37:%.*]] = shl i32 [[BF_LOAD36]], 1
// CHK-C-NEXT:    [[BF_ASHR38:%.*]] = ashr i32 [[BF_SHL37]], 1
// CHK-C-NEXT:    store i32 [[BF_ASHR38]], i32* [[ATMP34]], align 4
// CHK-C-NEXT:    [[CMP39:%.*]] = icmp eq i32 [[BF_ASHR38]], [[TMP17]]
// CHK-C-NEXT:    [[FROMBOOL41:%.*]] = zext i1 [[CMP39]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL41]], i8* [[ATMP40]], align 1
// CHK-C-NEXT:    br i1 [[CMP39]], label [[ATOMIC_CONT42:%.*]], label [[ATOMIC_EXIT56:%.*]]
// CHK-C:       atomic_cont42:
// CHK-C-NEXT:    [[TMP18:%.*]] = phi i32 [ [[ATOMIC_LOAD33]], [[ATOMIC_EXIT32]] ], [ [[TMP21:%.*]], [[ATOMIC_CMP49:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP18]], i32* [[ATOMIC_TEMP43]], align 4
// CHK-C-NEXT:    [[BF_LOAD44:%.*]] = load i32, i32* [[ATOMIC_TEMP43]], align 4
// CHK-C-NEXT:    [[BF_VALUE45:%.*]] = and i32 [[TMP16]], 2147483647
// CHK-C-NEXT:    [[BF_CLEAR46:%.*]] = and i32 [[BF_LOAD44]], -2147483648
// CHK-C-NEXT:    [[BF_SET47:%.*]] = or i32 [[BF_CLEAR46]], [[BF_VALUE45]]
// CHK-C-NEXT:    store i32 [[BF_SET47]], i32* [[ATOMIC_TEMP43]], align 4
// CHK-C-NEXT:    [[TMP19:%.*]] = load i32, i32* [[ATOMIC_TEMP43]], align 4
// CHK-C-NEXT:    [[TMP20:%.*]] = cmpxchg i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*), i32 [[TMP18]], i32 [[TMP19]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP21]] = extractvalue { i32, i1 } [[TMP20]], 0
// CHK-C-NEXT:    [[TMP22:%.*]] = extractvalue { i32, i1 } [[TMP20]], 1
// CHK-C-NEXT:    br i1 [[TMP22]], label [[ATOMIC_UPD_EXIT48:%.*]], label [[ATOMIC_CMP49]]
// CHK-C:       atomic_upd_exit48:
// CHK-C-NEXT:    store i32 [[TMP16]], i32* [[ATMP34]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT56]]
// CHK-C:       atomic_cmp49:
// CHK-C-NEXT:    store i32 [[TMP21]], i32* [[ATOMIC_TEMP50]], align 4
// CHK-C-NEXT:    [[BF_LOAD51:%.*]] = load i32, i32* [[ATOMIC_TEMP50]], align 4
// CHK-C-NEXT:    [[BF_SHL52:%.*]] = shl i32 [[BF_LOAD51]], 1
// CHK-C-NEXT:    [[BF_ASHR53:%.*]] = ashr i32 [[BF_SHL52]], 1
// CHK-C-NEXT:    store i32 [[BF_ASHR53]], i32* [[ATMP34]], align 4
// CHK-C-NEXT:    [[CMP54:%.*]] = icmp eq i32 [[BF_ASHR53]], [[TMP17]]
// CHK-C-NEXT:    [[FROMBOOL55:%.*]] = zext i1 [[CMP54]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL55]], i8* [[ATMP40]], align 1
// CHK-C-NEXT:    br i1 [[CMP54]], label [[ATOMIC_CONT42]], label [[ATOMIC_EXIT56]]
// CHK-C:       atomic_exit56:
// CHK-C-NEXT:    [[TMP23:%.*]] = load i32, i32* [[ATMP34]], align 4
// CHK-C-NEXT:    [[TMP24:%.*]] = load i8, i8* [[ATMP40]], align 1
// CHK-C-NEXT:    [[TMP25:%.*]] = trunc i8 [[TMP24]] to i1
// CHK-C-NEXT:    br i1 [[TMP25]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-C:       atomic_capture:
// CHK-C-NEXT:    store i32 [[TMP23]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-C:       atomic_capture_cont:
// CHK-C-NEXT:    [[TMP26:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP27:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD57:%.*]] = load atomic i32, i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD57]], i32* [[ATOMIC_TEMP59]], align 4
// CHK-C-NEXT:    [[BF_LOAD60:%.*]] = load i32, i32* [[ATOMIC_TEMP59]], align 4
// CHK-C-NEXT:    [[BF_SHL61:%.*]] = shl i32 [[BF_LOAD60]], 1
// CHK-C-NEXT:    [[BF_ASHR62:%.*]] = ashr i32 [[BF_SHL61]], 1
// CHK-C-NEXT:    store i32 [[BF_ASHR62]], i32* [[ATMP58]], align 4
// CHK-C-NEXT:    [[CMP63:%.*]] = icmp eq i32 [[BF_ASHR62]], [[TMP27]]
// CHK-C-NEXT:    [[FROMBOOL65:%.*]] = zext i1 [[CMP63]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL65]], i8* [[ATMP64]], align 1
// CHK-C-NEXT:    br i1 [[CMP63]], label [[ATOMIC_CONT66:%.*]], label [[ATOMIC_EXIT79:%.*]]
// CHK-C:       atomic_cont66:
// CHK-C-NEXT:    [[TMP28:%.*]] = phi i32 [ [[ATOMIC_LOAD57]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP31:%.*]], [[ATOMIC_CMP72:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP28]], i32* [[ATOMIC_TEMP67]], align 4
// CHK-C-NEXT:    [[BF_LOAD68:%.*]] = load i32, i32* [[ATOMIC_TEMP67]], align 4
// CHK-C-NEXT:    [[BF_VALUE69:%.*]] = and i32 [[TMP26]], 2147483647
// CHK-C-NEXT:    [[BF_CLEAR70:%.*]] = and i32 [[BF_LOAD68]], -2147483648
// CHK-C-NEXT:    [[BF_SET71:%.*]] = or i32 [[BF_CLEAR70]], [[BF_VALUE69]]
// CHK-C-NEXT:    store i32 [[BF_SET71]], i32* [[ATOMIC_TEMP67]], align 4
// CHK-C-NEXT:    [[TMP29:%.*]] = load i32, i32* [[ATOMIC_TEMP67]], align 4
// CHK-C-NEXT:    [[TMP30:%.*]] = cmpxchg i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*), i32 [[TMP28]], i32 [[TMP29]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP31]] = extractvalue { i32, i1 } [[TMP30]], 0
// CHK-C-NEXT:    [[TMP32:%.*]] = extractvalue { i32, i1 } [[TMP30]], 1
// CHK-C-NEXT:    br i1 [[TMP32]], label [[ATOMIC_EXIT79]], label [[ATOMIC_CMP72]]
// CHK-C:       atomic_cmp72:
// CHK-C-NEXT:    store i32 [[TMP31]], i32* [[ATOMIC_TEMP73]], align 4
// CHK-C-NEXT:    [[BF_LOAD74:%.*]] = load i32, i32* [[ATOMIC_TEMP73]], align 4
// CHK-C-NEXT:    [[BF_SHL75:%.*]] = shl i32 [[BF_LOAD74]], 1
// CHK-C-NEXT:    [[BF_ASHR76:%.*]] = ashr i32 [[BF_SHL75]], 1
// CHK-C-NEXT:    store i32 [[BF_ASHR76]], i32* [[ATMP58]], align 4
// CHK-C-NEXT:    [[CMP77:%.*]] = icmp eq i32 [[BF_ASHR76]], [[TMP27]]
// CHK-C-NEXT:    [[FROMBOOL78:%.*]] = zext i1 [[CMP77]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL78]], i8* [[ATMP64]], align 1
// CHK-C-NEXT:    br i1 [[CMP77]], label [[ATOMIC_CONT66]], label [[ATOMIC_EXIT79]]
// CHK-C:       atomic_exit79:
// CHK-C-NEXT:    [[TMP33:%.*]] = load i32, i32* [[ATMP58]], align 4
// CHK-C-NEXT:    [[TMP34:%.*]] = load i8, i8* [[ATMP64]], align 1
// CHK-C-NEXT:    [[CONV:%.*]] = zext i8 [[TMP34]] to i32
// CHK-C-NEXT:    store i32 [[CONV]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP35:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP36:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD80:%.*]] = load atomic i32, i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD80]], i32* [[ATOMIC_TEMP82]], align 4
// CHK-C-NEXT:    [[BF_LOAD83:%.*]] = load i32, i32* [[ATOMIC_TEMP82]], align 4
// CHK-C-NEXT:    [[BF_SHL84:%.*]] = shl i32 [[BF_LOAD83]], 1
// CHK-C-NEXT:    [[BF_ASHR85:%.*]] = ashr i32 [[BF_SHL84]], 1
// CHK-C-NEXT:    store i32 [[BF_ASHR85]], i32* [[ATMP81]], align 4
// CHK-C-NEXT:    [[CMP86:%.*]] = icmp eq i32 [[BF_ASHR85]], [[TMP36]]
// CHK-C-NEXT:    [[FROMBOOL88:%.*]] = zext i1 [[CMP86]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL88]], i8* [[ATMP87]], align 1
// CHK-C-NEXT:    br i1 [[CMP86]], label [[ATOMIC_CONT89:%.*]], label [[ATOMIC_EXIT102:%.*]]
// CHK-C:       atomic_cont89:
// CHK-C-NEXT:    [[TMP37:%.*]] = phi i32 [ [[ATOMIC_LOAD80]], [[ATOMIC_EXIT79]] ], [ [[TMP40:%.*]], [[ATOMIC_CMP95:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP37]], i32* [[ATOMIC_TEMP90]], align 4
// CHK-C-NEXT:    [[BF_LOAD91:%.*]] = load i32, i32* [[ATOMIC_TEMP90]], align 4
// CHK-C-NEXT:    [[BF_VALUE92:%.*]] = and i32 [[TMP35]], 2147483647
// CHK-C-NEXT:    [[BF_CLEAR93:%.*]] = and i32 [[BF_LOAD91]], -2147483648
// CHK-C-NEXT:    [[BF_SET94:%.*]] = or i32 [[BF_CLEAR93]], [[BF_VALUE92]]
// CHK-C-NEXT:    store i32 [[BF_SET94]], i32* [[ATOMIC_TEMP90]], align 4
// CHK-C-NEXT:    [[TMP38:%.*]] = load i32, i32* [[ATOMIC_TEMP90]], align 4
// CHK-C-NEXT:    [[TMP39:%.*]] = cmpxchg i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*), i32 [[TMP37]], i32 [[TMP38]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP40]] = extractvalue { i32, i1 } [[TMP39]], 0
// CHK-C-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i1 } [[TMP39]], 1
// CHK-C-NEXT:    br i1 [[TMP41]], label [[ATOMIC_EXIT102]], label [[ATOMIC_CMP95]]
// CHK-C:       atomic_cmp95:
// CHK-C-NEXT:    store i32 [[TMP40]], i32* [[ATOMIC_TEMP96]], align 4
// CHK-C-NEXT:    [[BF_LOAD97:%.*]] = load i32, i32* [[ATOMIC_TEMP96]], align 4
// CHK-C-NEXT:    [[BF_SHL98:%.*]] = shl i32 [[BF_LOAD97]], 1
// CHK-C-NEXT:    [[BF_ASHR99:%.*]] = ashr i32 [[BF_SHL98]], 1
// CHK-C-NEXT:    store i32 [[BF_ASHR99]], i32* [[ATMP81]], align 4
// CHK-C-NEXT:    [[CMP100:%.*]] = icmp eq i32 [[BF_ASHR99]], [[TMP36]]
// CHK-C-NEXT:    [[FROMBOOL101:%.*]] = zext i1 [[CMP100]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL101]], i8* [[ATMP87]], align 1
// CHK-C-NEXT:    br i1 [[CMP100]], label [[ATOMIC_CONT89]], label [[ATOMIC_EXIT102]]
// CHK-C:       atomic_exit102:
// CHK-C-NEXT:    [[TMP42:%.*]] = load i32, i32* [[ATMP81]], align 4
// CHK-C-NEXT:    [[TMP43:%.*]] = load i8, i8* [[ATMP87]], align 1
// CHK-C-NEXT:    [[CONV103:%.*]] = zext i8 [[TMP43]] to i32
// CHK-C-NEXT:    store i32 [[CONV103]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP44:%.*]] = trunc i8 [[TMP43]] to i1
// CHK-C-NEXT:    br i1 [[TMP44]], label [[ATOMIC_CAPTURE_CONT105:%.*]], label [[ATOMIC_CAPTURE104:%.*]]
// CHK-C:       atomic_capture104:
// CHK-C-NEXT:    store i32 [[TMP42]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT105]]
// CHK-C:       atomic_capture_cont105:
// CHK-C-NEXT:    [[TMP45:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD106:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS2:%.*]], %struct.BitFields2* @bfx2, i32 0, i32 0) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD106]], i32* [[ATOMIC_TEMP108]], align 4
// CHK-C-NEXT:    [[BF_LOAD109:%.*]] = load i32, i32* [[ATOMIC_TEMP108]], align 4
// CHK-C-NEXT:    [[BF_ASHR110:%.*]] = ashr i32 [[BF_LOAD109]], 31
// CHK-C-NEXT:    store i32 [[BF_ASHR110]], i32* [[ATMP107]], align 4
// CHK-C-NEXT:    [[CMP111:%.*]] = icmp slt i32 [[BF_ASHR110]], [[TMP45]]
// CHK-C-NEXT:    [[FROMBOOL113:%.*]] = zext i1 [[CMP111]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL113]], i8* [[ATMP112]], align 1
// CHK-C-NEXT:    br i1 [[CMP111]], label [[ATOMIC_CONT114:%.*]], label [[ATOMIC_EXIT127:%.*]]
// CHK-C:       atomic_cont114:
// CHK-C-NEXT:    [[TMP46:%.*]] = phi i32 [ [[ATOMIC_LOAD106]], [[ATOMIC_CAPTURE_CONT105]] ], [ [[TMP49:%.*]], [[ATOMIC_CMP121:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP46]], i32* [[ATOMIC_TEMP115]], align 4
// CHK-C-NEXT:    [[BF_LOAD116:%.*]] = load i32, i32* [[ATOMIC_TEMP115]], align 4
// CHK-C-NEXT:    [[BF_VALUE117:%.*]] = and i32 [[TMP45]], 1
// CHK-C-NEXT:    [[BF_SHL118:%.*]] = shl i32 [[BF_VALUE117]], 31
// CHK-C-NEXT:    [[BF_CLEAR119:%.*]] = and i32 [[BF_LOAD116]], 2147483647
// CHK-C-NEXT:    [[BF_SET120:%.*]] = or i32 [[BF_CLEAR119]], [[BF_SHL118]]
// CHK-C-NEXT:    store i32 [[BF_SET120]], i32* [[ATOMIC_TEMP115]], align 4
// CHK-C-NEXT:    [[TMP47:%.*]] = load i32, i32* [[ATOMIC_TEMP115]], align 4
// CHK-C-NEXT:    [[TMP48:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0), i32 [[TMP46]], i32 [[TMP47]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP49]] = extractvalue { i32, i1 } [[TMP48]], 0
// CHK-C-NEXT:    [[TMP50:%.*]] = extractvalue { i32, i1 } [[TMP48]], 1
// CHK-C-NEXT:    br i1 [[TMP50]], label [[ATOMIC_EXIT127]], label [[ATOMIC_CMP121]]
// CHK-C:       atomic_cmp121:
// CHK-C-NEXT:    store i32 [[TMP49]], i32* [[ATOMIC_TEMP122]], align 4
// CHK-C-NEXT:    [[BF_LOAD123:%.*]] = load i32, i32* [[ATOMIC_TEMP122]], align 4
// CHK-C-NEXT:    [[BF_ASHR124:%.*]] = ashr i32 [[BF_LOAD123]], 31
// CHK-C-NEXT:    store i32 [[BF_ASHR124]], i32* [[ATMP107]], align 4
// CHK-C-NEXT:    [[CMP125:%.*]] = icmp slt i32 [[BF_ASHR124]], [[TMP45]]
// CHK-C-NEXT:    [[FROMBOOL126:%.*]] = zext i1 [[CMP125]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL126]], i8* [[ATMP112]], align 1
// CHK-C-NEXT:    br i1 [[CMP125]], label [[ATOMIC_CONT114]], label [[ATOMIC_EXIT127]]
// CHK-C:       atomic_exit127:
// CHK-C-NEXT:    [[TMP51:%.*]] = load i32, i32* [[ATMP107]], align 4
// CHK-C-NEXT:    [[TMP52:%.*]] = load i8, i8* [[ATMP112]], align 1
// CHK-C-NEXT:    store i32 [[TMP51]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP53:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD128:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD128]], i32* [[ATOMIC_TEMP130]], align 4
// CHK-C-NEXT:    [[BF_LOAD131:%.*]] = load i32, i32* [[ATOMIC_TEMP130]], align 4
// CHK-C-NEXT:    [[BF_ASHR132:%.*]] = ashr i32 [[BF_LOAD131]], 31
// CHK-C-NEXT:    store i32 [[BF_ASHR132]], i32* [[ATMP129]], align 4
// CHK-C-NEXT:    [[CMP133:%.*]] = icmp slt i32 [[BF_ASHR132]], [[TMP53]]
// CHK-C-NEXT:    [[FROMBOOL135:%.*]] = zext i1 [[CMP133]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL135]], i8* [[ATMP134]], align 1
// CHK-C-NEXT:    br i1 [[CMP133]], label [[ATOMIC_CONT136:%.*]], label [[ATOMIC_EXIT150:%.*]]
// CHK-C:       atomic_cont136:
// CHK-C-NEXT:    [[TMP54:%.*]] = phi i32 [ [[ATOMIC_LOAD128]], [[ATOMIC_EXIT127]] ], [ [[TMP57:%.*]], [[ATOMIC_CMP144:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP54]], i32* [[ATOMIC_TEMP137]], align 4
// CHK-C-NEXT:    [[BF_LOAD138:%.*]] = load i32, i32* [[ATOMIC_TEMP137]], align 4
// CHK-C-NEXT:    [[BF_VALUE139:%.*]] = and i32 [[TMP53]], 1
// CHK-C-NEXT:    [[BF_SHL140:%.*]] = shl i32 [[BF_VALUE139]], 31
// CHK-C-NEXT:    [[BF_CLEAR141:%.*]] = and i32 [[BF_LOAD138]], 2147483647
// CHK-C-NEXT:    [[BF_SET142:%.*]] = or i32 [[BF_CLEAR141]], [[BF_SHL140]]
// CHK-C-NEXT:    store i32 [[BF_SET142]], i32* [[ATOMIC_TEMP137]], align 4
// CHK-C-NEXT:    [[TMP55:%.*]] = load i32, i32* [[ATOMIC_TEMP137]], align 4
// CHK-C-NEXT:    [[TMP56:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0), i32 [[TMP54]], i32 [[TMP55]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP57]] = extractvalue { i32, i1 } [[TMP56]], 0
// CHK-C-NEXT:    [[TMP58:%.*]] = extractvalue { i32, i1 } [[TMP56]], 1
// CHK-C-NEXT:    br i1 [[TMP58]], label [[ATOMIC_UPD_EXIT143:%.*]], label [[ATOMIC_CMP144]]
// CHK-C:       atomic_upd_exit143:
// CHK-C-NEXT:    store i32 [[TMP53]], i32* [[ATMP129]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT150]]
// CHK-C:       atomic_cmp144:
// CHK-C-NEXT:    store i32 [[TMP57]], i32* [[ATOMIC_TEMP145]], align 4
// CHK-C-NEXT:    [[BF_LOAD146:%.*]] = load i32, i32* [[ATOMIC_TEMP145]], align 4
// CHK-C-NEXT:    [[BF_ASHR147:%.*]] = ashr i32 [[BF_LOAD146]], 31
// CHK-C-NEXT:    store i32 [[BF_ASHR147]], i32* [[ATMP129]], align 4
// CHK-C-NEXT:    [[CMP148:%.*]] = icmp slt i32 [[BF_ASHR147]], [[TMP53]]
// CHK-C-NEXT:    [[FROMBOOL149:%.*]] = zext i1 [[CMP148]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL149]], i8* [[ATMP134]], align 1
// CHK-C-NEXT:    br i1 [[CMP148]], label [[ATOMIC_CONT136]], label [[ATOMIC_EXIT150]]
// CHK-C:       atomic_exit150:
// CHK-C-NEXT:    [[TMP59:%.*]] = load i32, i32* [[ATMP129]], align 4
// CHK-C-NEXT:    [[TMP60:%.*]] = load i8, i8* [[ATMP134]], align 1
// CHK-C-NEXT:    store i32 [[TMP59]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP61:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP62:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD151:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD151]], i32* [[ATOMIC_TEMP153]], align 4
// CHK-C-NEXT:    [[BF_LOAD154:%.*]] = load i32, i32* [[ATOMIC_TEMP153]], align 4
// CHK-C-NEXT:    [[BF_ASHR155:%.*]] = ashr i32 [[BF_LOAD154]], 31
// CHK-C-NEXT:    store i32 [[BF_ASHR155]], i32* [[ATMP152]], align 4
// CHK-C-NEXT:    [[CMP156:%.*]] = icmp eq i32 [[BF_ASHR155]], [[TMP62]]
// CHK-C-NEXT:    [[FROMBOOL158:%.*]] = zext i1 [[CMP156]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL158]], i8* [[ATMP157]], align 1
// CHK-C-NEXT:    br i1 [[CMP156]], label [[ATOMIC_CONT159:%.*]], label [[ATOMIC_EXIT173:%.*]]
// CHK-C:       atomic_cont159:
// CHK-C-NEXT:    [[TMP63:%.*]] = phi i32 [ [[ATOMIC_LOAD151]], [[ATOMIC_EXIT150]] ], [ [[TMP66:%.*]], [[ATOMIC_CMP167:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP63]], i32* [[ATOMIC_TEMP160]], align 4
// CHK-C-NEXT:    [[BF_LOAD161:%.*]] = load i32, i32* [[ATOMIC_TEMP160]], align 4
// CHK-C-NEXT:    [[BF_VALUE162:%.*]] = and i32 [[TMP61]], 1
// CHK-C-NEXT:    [[BF_SHL163:%.*]] = shl i32 [[BF_VALUE162]], 31
// CHK-C-NEXT:    [[BF_CLEAR164:%.*]] = and i32 [[BF_LOAD161]], 2147483647
// CHK-C-NEXT:    [[BF_SET165:%.*]] = or i32 [[BF_CLEAR164]], [[BF_SHL163]]
// CHK-C-NEXT:    store i32 [[BF_SET165]], i32* [[ATOMIC_TEMP160]], align 4
// CHK-C-NEXT:    [[TMP64:%.*]] = load i32, i32* [[ATOMIC_TEMP160]], align 4
// CHK-C-NEXT:    [[TMP65:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0), i32 [[TMP63]], i32 [[TMP64]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP66]] = extractvalue { i32, i1 } [[TMP65]], 0
// CHK-C-NEXT:    [[TMP67:%.*]] = extractvalue { i32, i1 } [[TMP65]], 1
// CHK-C-NEXT:    br i1 [[TMP67]], label [[ATOMIC_UPD_EXIT166:%.*]], label [[ATOMIC_CMP167]]
// CHK-C:       atomic_upd_exit166:
// CHK-C-NEXT:    store i32 [[TMP61]], i32* [[ATMP152]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT173]]
// CHK-C:       atomic_cmp167:
// CHK-C-NEXT:    store i32 [[TMP66]], i32* [[ATOMIC_TEMP168]], align 4
// CHK-C-NEXT:    [[BF_LOAD169:%.*]] = load i32, i32* [[ATOMIC_TEMP168]], align 4
// CHK-C-NEXT:    [[BF_ASHR170:%.*]] = ashr i32 [[BF_LOAD169]], 31
// CHK-C-NEXT:    store i32 [[BF_ASHR170]], i32* [[ATMP152]], align 4
// CHK-C-NEXT:    [[CMP171:%.*]] = icmp eq i32 [[BF_ASHR170]], [[TMP62]]
// CHK-C-NEXT:    [[FROMBOOL172:%.*]] = zext i1 [[CMP171]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL172]], i8* [[ATMP157]], align 1
// CHK-C-NEXT:    br i1 [[CMP171]], label [[ATOMIC_CONT159]], label [[ATOMIC_EXIT173]]
// CHK-C:       atomic_exit173:
// CHK-C-NEXT:    [[TMP68:%.*]] = load i32, i32* [[ATMP152]], align 4
// CHK-C-NEXT:    [[TMP69:%.*]] = load i8, i8* [[ATMP157]], align 1
// CHK-C-NEXT:    [[TMP70:%.*]] = trunc i8 [[TMP69]] to i1
// CHK-C-NEXT:    br i1 [[TMP70]], label [[ATOMIC_CAPTURE_CONT175:%.*]], label [[ATOMIC_CAPTURE174:%.*]]
// CHK-C:       atomic_capture174:
// CHK-C-NEXT:    store i32 [[TMP68]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT175]]
// CHK-C:       atomic_capture_cont175:
// CHK-C-NEXT:    [[TMP71:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP72:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD176:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD176]], i32* [[ATOMIC_TEMP178]], align 4
// CHK-C-NEXT:    [[BF_LOAD179:%.*]] = load i32, i32* [[ATOMIC_TEMP178]], align 4
// CHK-C-NEXT:    [[BF_ASHR180:%.*]] = ashr i32 [[BF_LOAD179]], 31
// CHK-C-NEXT:    store i32 [[BF_ASHR180]], i32* [[ATMP177]], align 4
// CHK-C-NEXT:    [[CMP181:%.*]] = icmp eq i32 [[BF_ASHR180]], [[TMP72]]
// CHK-C-NEXT:    [[FROMBOOL183:%.*]] = zext i1 [[CMP181]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL183]], i8* [[ATMP182]], align 1
// CHK-C-NEXT:    br i1 [[CMP181]], label [[ATOMIC_CONT184:%.*]], label [[ATOMIC_EXIT197:%.*]]
// CHK-C:       atomic_cont184:
// CHK-C-NEXT:    [[TMP73:%.*]] = phi i32 [ [[ATOMIC_LOAD176]], [[ATOMIC_CAPTURE_CONT175]] ], [ [[TMP76:%.*]], [[ATOMIC_CMP191:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP73]], i32* [[ATOMIC_TEMP185]], align 4
// CHK-C-NEXT:    [[BF_LOAD186:%.*]] = load i32, i32* [[ATOMIC_TEMP185]], align 4
// CHK-C-NEXT:    [[BF_VALUE187:%.*]] = and i32 [[TMP71]], 1
// CHK-C-NEXT:    [[BF_SHL188:%.*]] = shl i32 [[BF_VALUE187]], 31
// CHK-C-NEXT:    [[BF_CLEAR189:%.*]] = and i32 [[BF_LOAD186]], 2147483647
// CHK-C-NEXT:    [[BF_SET190:%.*]] = or i32 [[BF_CLEAR189]], [[BF_SHL188]]
// CHK-C-NEXT:    store i32 [[BF_SET190]], i32* [[ATOMIC_TEMP185]], align 4
// CHK-C-NEXT:    [[TMP74:%.*]] = load i32, i32* [[ATOMIC_TEMP185]], align 4
// CHK-C-NEXT:    [[TMP75:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0), i32 [[TMP73]], i32 [[TMP74]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP76]] = extractvalue { i32, i1 } [[TMP75]], 0
// CHK-C-NEXT:    [[TMP77:%.*]] = extractvalue { i32, i1 } [[TMP75]], 1
// CHK-C-NEXT:    br i1 [[TMP77]], label [[ATOMIC_EXIT197]], label [[ATOMIC_CMP191]]
// CHK-C:       atomic_cmp191:
// CHK-C-NEXT:    store i32 [[TMP76]], i32* [[ATOMIC_TEMP192]], align 4
// CHK-C-NEXT:    [[BF_LOAD193:%.*]] = load i32, i32* [[ATOMIC_TEMP192]], align 4
// CHK-C-NEXT:    [[BF_ASHR194:%.*]] = ashr i32 [[BF_LOAD193]], 31
// CHK-C-NEXT:    store i32 [[BF_ASHR194]], i32* [[ATMP177]], align 4
// CHK-C-NEXT:    [[CMP195:%.*]] = icmp eq i32 [[BF_ASHR194]], [[TMP72]]
// CHK-C-NEXT:    [[FROMBOOL196:%.*]] = zext i1 [[CMP195]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL196]], i8* [[ATMP182]], align 1
// CHK-C-NEXT:    br i1 [[CMP195]], label [[ATOMIC_CONT184]], label [[ATOMIC_EXIT197]]
// CHK-C:       atomic_exit197:
// CHK-C-NEXT:    [[TMP78:%.*]] = load i32, i32* [[ATMP177]], align 4
// CHK-C-NEXT:    [[TMP79:%.*]] = load i8, i8* [[ATMP182]], align 1
// CHK-C-NEXT:    [[CONV198:%.*]] = zext i8 [[TMP79]] to i32
// CHK-C-NEXT:    store i32 [[CONV198]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP80:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP81:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD199:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD199]], i32* [[ATOMIC_TEMP201]], align 4
// CHK-C-NEXT:    [[BF_LOAD202:%.*]] = load i32, i32* [[ATOMIC_TEMP201]], align 4
// CHK-C-NEXT:    [[BF_ASHR203:%.*]] = ashr i32 [[BF_LOAD202]], 31
// CHK-C-NEXT:    store i32 [[BF_ASHR203]], i32* [[ATMP200]], align 4
// CHK-C-NEXT:    [[CMP204:%.*]] = icmp eq i32 [[BF_ASHR203]], [[TMP81]]
// CHK-C-NEXT:    [[FROMBOOL206:%.*]] = zext i1 [[CMP204]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL206]], i8* [[ATMP205]], align 1
// CHK-C-NEXT:    br i1 [[CMP204]], label [[ATOMIC_CONT207:%.*]], label [[ATOMIC_EXIT220:%.*]]
// CHK-C:       atomic_cont207:
// CHK-C-NEXT:    [[TMP82:%.*]] = phi i32 [ [[ATOMIC_LOAD199]], [[ATOMIC_EXIT197]] ], [ [[TMP85:%.*]], [[ATOMIC_CMP214:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP82]], i32* [[ATOMIC_TEMP208]], align 4
// CHK-C-NEXT:    [[BF_LOAD209:%.*]] = load i32, i32* [[ATOMIC_TEMP208]], align 4
// CHK-C-NEXT:    [[BF_VALUE210:%.*]] = and i32 [[TMP80]], 1
// CHK-C-NEXT:    [[BF_SHL211:%.*]] = shl i32 [[BF_VALUE210]], 31
// CHK-C-NEXT:    [[BF_CLEAR212:%.*]] = and i32 [[BF_LOAD209]], 2147483647
// CHK-C-NEXT:    [[BF_SET213:%.*]] = or i32 [[BF_CLEAR212]], [[BF_SHL211]]
// CHK-C-NEXT:    store i32 [[BF_SET213]], i32* [[ATOMIC_TEMP208]], align 4
// CHK-C-NEXT:    [[TMP83:%.*]] = load i32, i32* [[ATOMIC_TEMP208]], align 4
// CHK-C-NEXT:    [[TMP84:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0), i32 [[TMP82]], i32 [[TMP83]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP85]] = extractvalue { i32, i1 } [[TMP84]], 0
// CHK-C-NEXT:    [[TMP86:%.*]] = extractvalue { i32, i1 } [[TMP84]], 1
// CHK-C-NEXT:    br i1 [[TMP86]], label [[ATOMIC_EXIT220]], label [[ATOMIC_CMP214]]
// CHK-C:       atomic_cmp214:
// CHK-C-NEXT:    store i32 [[TMP85]], i32* [[ATOMIC_TEMP215]], align 4
// CHK-C-NEXT:    [[BF_LOAD216:%.*]] = load i32, i32* [[ATOMIC_TEMP215]], align 4
// CHK-C-NEXT:    [[BF_ASHR217:%.*]] = ashr i32 [[BF_LOAD216]], 31
// CHK-C-NEXT:    store i32 [[BF_ASHR217]], i32* [[ATMP200]], align 4
// CHK-C-NEXT:    [[CMP218:%.*]] = icmp eq i32 [[BF_ASHR217]], [[TMP81]]
// CHK-C-NEXT:    [[FROMBOOL219:%.*]] = zext i1 [[CMP218]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL219]], i8* [[ATMP205]], align 1
// CHK-C-NEXT:    br i1 [[CMP218]], label [[ATOMIC_CONT207]], label [[ATOMIC_EXIT220]]
// CHK-C:       atomic_exit220:
// CHK-C-NEXT:    [[TMP87:%.*]] = load i32, i32* [[ATMP200]], align 4
// CHK-C-NEXT:    [[TMP88:%.*]] = load i8, i8* [[ATMP205]], align 1
// CHK-C-NEXT:    [[CONV221:%.*]] = zext i8 [[TMP88]] to i32
// CHK-C-NEXT:    store i32 [[CONV221]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP89:%.*]] = trunc i8 [[TMP88]] to i1
// CHK-C-NEXT:    br i1 [[TMP89]], label [[ATOMIC_CAPTURE_CONT223:%.*]], label [[ATOMIC_CAPTURE222:%.*]]
// CHK-C:       atomic_capture222:
// CHK-C-NEXT:    store i32 [[TMP87]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT223]]
// CHK-C:       atomic_capture_cont223:
// CHK-C-NEXT:    [[TMP90:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD224:%.*]] = load atomic i8, i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3) monotonic, align 1
// CHK-C-NEXT:    [[TMP91:%.*]] = bitcast i32* [[ATOMIC_TEMP226]] to i8*
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD224]], i8* [[TMP91]], align 1
// CHK-C-NEXT:    [[BF_LOAD227:%.*]] = load i8, i8* [[TMP91]], align 1
// CHK-C-NEXT:    [[BF_ASHR228:%.*]] = ashr i8 [[BF_LOAD227]], 7
// CHK-C-NEXT:    [[BF_CAST:%.*]] = sext i8 [[BF_ASHR228]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST]], i32* [[ATMP225]], align 4
// CHK-C-NEXT:    [[CMP229:%.*]] = icmp slt i32 [[BF_CAST]], [[TMP90]]
// CHK-C-NEXT:    [[FROMBOOL231:%.*]] = zext i1 [[CMP229]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL231]], i8* [[ATMP230]], align 1
// CHK-C-NEXT:    br i1 [[CMP229]], label [[ATOMIC_CONT232:%.*]], label [[ATOMIC_EXIT246:%.*]]
// CHK-C:       atomic_cont232:
// CHK-C-NEXT:    [[TMP92:%.*]] = phi i8 [ [[ATOMIC_LOAD224]], [[ATOMIC_CAPTURE_CONT223]] ], [ [[TMP97:%.*]], [[ATOMIC_CMP239:%.*]] ]
// CHK-C-NEXT:    [[TMP93:%.*]] = bitcast i32* [[ATOMIC_TEMP233]] to i8*
// CHK-C-NEXT:    store i8 [[TMP92]], i8* [[TMP93]], align 1
// CHK-C-NEXT:    [[TMP94:%.*]] = trunc i32 [[TMP90]] to i8
// CHK-C-NEXT:    [[BF_LOAD234:%.*]] = load i8, i8* [[TMP93]], align 1
// CHK-C-NEXT:    [[BF_VALUE235:%.*]] = and i8 [[TMP94]], 1
// CHK-C-NEXT:    [[BF_SHL236:%.*]] = shl i8 [[BF_VALUE235]], 7
// CHK-C-NEXT:    [[BF_CLEAR237:%.*]] = and i8 [[BF_LOAD234]], 127
// CHK-C-NEXT:    [[BF_SET238:%.*]] = or i8 [[BF_CLEAR237]], [[BF_SHL236]]
// CHK-C-NEXT:    store i8 [[BF_SET238]], i8* [[TMP93]], align 1
// CHK-C-NEXT:    [[TMP95:%.*]] = load i8, i8* [[TMP93]], align 1
// CHK-C-NEXT:    [[TMP96:%.*]] = cmpxchg i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3), i8 [[TMP92]], i8 [[TMP95]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP97]] = extractvalue { i8, i1 } [[TMP96]], 0
// CHK-C-NEXT:    [[TMP98:%.*]] = extractvalue { i8, i1 } [[TMP96]], 1
// CHK-C-NEXT:    br i1 [[TMP98]], label [[ATOMIC_EXIT246]], label [[ATOMIC_CMP239]]
// CHK-C:       atomic_cmp239:
// CHK-C-NEXT:    [[TMP99:%.*]] = bitcast i32* [[ATOMIC_TEMP240]] to i8*
// CHK-C-NEXT:    store i8 [[TMP97]], i8* [[TMP99]], align 1
// CHK-C-NEXT:    [[BF_LOAD241:%.*]] = load i8, i8* [[TMP99]], align 1
// CHK-C-NEXT:    [[BF_ASHR242:%.*]] = ashr i8 [[BF_LOAD241]], 7
// CHK-C-NEXT:    [[BF_CAST243:%.*]] = sext i8 [[BF_ASHR242]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST243]], i32* [[ATMP225]], align 4
// CHK-C-NEXT:    [[CMP244:%.*]] = icmp slt i32 [[BF_CAST243]], [[TMP90]]
// CHK-C-NEXT:    [[FROMBOOL245:%.*]] = zext i1 [[CMP244]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL245]], i8* [[ATMP230]], align 1
// CHK-C-NEXT:    br i1 [[CMP244]], label [[ATOMIC_CONT232]], label [[ATOMIC_EXIT246]]
// CHK-C:       atomic_exit246:
// CHK-C-NEXT:    [[TMP100:%.*]] = load i32, i32* [[ATMP225]], align 4
// CHK-C-NEXT:    [[TMP101:%.*]] = load i8, i8* [[ATMP230]], align 1
// CHK-C-NEXT:    store i32 [[TMP100]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP102:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD247:%.*]] = load atomic i8, i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3) monotonic, align 1
// CHK-C-NEXT:    [[TMP103:%.*]] = bitcast i32* [[ATOMIC_TEMP249]] to i8*
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD247]], i8* [[TMP103]], align 1
// CHK-C-NEXT:    [[BF_LOAD250:%.*]] = load i8, i8* [[TMP103]], align 1
// CHK-C-NEXT:    [[BF_ASHR251:%.*]] = ashr i8 [[BF_LOAD250]], 7
// CHK-C-NEXT:    [[BF_CAST252:%.*]] = sext i8 [[BF_ASHR251]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST252]], i32* [[ATMP248]], align 4
// CHK-C-NEXT:    [[CMP253:%.*]] = icmp slt i32 [[BF_CAST252]], [[TMP102]]
// CHK-C-NEXT:    [[FROMBOOL255:%.*]] = zext i1 [[CMP253]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL255]], i8* [[ATMP254]], align 1
// CHK-C-NEXT:    br i1 [[CMP253]], label [[ATOMIC_CONT256:%.*]], label [[ATOMIC_EXIT271:%.*]]
// CHK-C:       atomic_cont256:
// CHK-C-NEXT:    [[TMP104:%.*]] = phi i8 [ [[ATOMIC_LOAD247]], [[ATOMIC_EXIT246]] ], [ [[TMP109:%.*]], [[ATOMIC_CMP264:%.*]] ]
// CHK-C-NEXT:    [[TMP105:%.*]] = bitcast i32* [[ATOMIC_TEMP257]] to i8*
// CHK-C-NEXT:    store i8 [[TMP104]], i8* [[TMP105]], align 1
// CHK-C-NEXT:    [[TMP106:%.*]] = trunc i32 [[TMP102]] to i8
// CHK-C-NEXT:    [[BF_LOAD258:%.*]] = load i8, i8* [[TMP105]], align 1
// CHK-C-NEXT:    [[BF_VALUE259:%.*]] = and i8 [[TMP106]], 1
// CHK-C-NEXT:    [[BF_SHL260:%.*]] = shl i8 [[BF_VALUE259]], 7
// CHK-C-NEXT:    [[BF_CLEAR261:%.*]] = and i8 [[BF_LOAD258]], 127
// CHK-C-NEXT:    [[BF_SET262:%.*]] = or i8 [[BF_CLEAR261]], [[BF_SHL260]]
// CHK-C-NEXT:    store i8 [[BF_SET262]], i8* [[TMP105]], align 1
// CHK-C-NEXT:    [[TMP107:%.*]] = load i8, i8* [[TMP105]], align 1
// CHK-C-NEXT:    [[TMP108:%.*]] = cmpxchg i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3), i8 [[TMP104]], i8 [[TMP107]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP109]] = extractvalue { i8, i1 } [[TMP108]], 0
// CHK-C-NEXT:    [[TMP110:%.*]] = extractvalue { i8, i1 } [[TMP108]], 1
// CHK-C-NEXT:    br i1 [[TMP110]], label [[ATOMIC_UPD_EXIT263:%.*]], label [[ATOMIC_CMP264]]
// CHK-C:       atomic_upd_exit263:
// CHK-C-NEXT:    store i32 [[TMP102]], i32* [[ATMP248]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT271]]
// CHK-C:       atomic_cmp264:
// CHK-C-NEXT:    [[TMP111:%.*]] = bitcast i32* [[ATOMIC_TEMP265]] to i8*
// CHK-C-NEXT:    store i8 [[TMP109]], i8* [[TMP111]], align 1
// CHK-C-NEXT:    [[BF_LOAD266:%.*]] = load i8, i8* [[TMP111]], align 1
// CHK-C-NEXT:    [[BF_ASHR267:%.*]] = ashr i8 [[BF_LOAD266]], 7
// CHK-C-NEXT:    [[BF_CAST268:%.*]] = sext i8 [[BF_ASHR267]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST268]], i32* [[ATMP248]], align 4
// CHK-C-NEXT:    [[CMP269:%.*]] = icmp slt i32 [[BF_CAST268]], [[TMP102]]
// CHK-C-NEXT:    [[FROMBOOL270:%.*]] = zext i1 [[CMP269]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL270]], i8* [[ATMP254]], align 1
// CHK-C-NEXT:    br i1 [[CMP269]], label [[ATOMIC_CONT256]], label [[ATOMIC_EXIT271]]
// CHK-C:       atomic_exit271:
// CHK-C-NEXT:    [[TMP112:%.*]] = load i32, i32* [[ATMP248]], align 4
// CHK-C-NEXT:    [[TMP113:%.*]] = load i8, i8* [[ATMP254]], align 1
// CHK-C-NEXT:    store i32 [[TMP112]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP114:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP115:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD272:%.*]] = load atomic i8, i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3) monotonic, align 1
// CHK-C-NEXT:    [[TMP116:%.*]] = bitcast i32* [[ATOMIC_TEMP274]] to i8*
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD272]], i8* [[TMP116]], align 1
// CHK-C-NEXT:    [[BF_LOAD275:%.*]] = load i8, i8* [[TMP116]], align 1
// CHK-C-NEXT:    [[BF_ASHR276:%.*]] = ashr i8 [[BF_LOAD275]], 7
// CHK-C-NEXT:    [[BF_CAST277:%.*]] = sext i8 [[BF_ASHR276]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST277]], i32* [[ATMP273]], align 4
// CHK-C-NEXT:    [[CMP278:%.*]] = icmp eq i32 [[BF_CAST277]], [[TMP115]]
// CHK-C-NEXT:    [[FROMBOOL280:%.*]] = zext i1 [[CMP278]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL280]], i8* [[ATMP279]], align 1
// CHK-C-NEXT:    br i1 [[CMP278]], label [[ATOMIC_CONT281:%.*]], label [[ATOMIC_EXIT296:%.*]]
// CHK-C:       atomic_cont281:
// CHK-C-NEXT:    [[TMP117:%.*]] = phi i8 [ [[ATOMIC_LOAD272]], [[ATOMIC_EXIT271]] ], [ [[TMP122:%.*]], [[ATOMIC_CMP289:%.*]] ]
// CHK-C-NEXT:    [[TMP118:%.*]] = bitcast i32* [[ATOMIC_TEMP282]] to i8*
// CHK-C-NEXT:    store i8 [[TMP117]], i8* [[TMP118]], align 1
// CHK-C-NEXT:    [[TMP119:%.*]] = trunc i32 [[TMP114]] to i8
// CHK-C-NEXT:    [[BF_LOAD283:%.*]] = load i8, i8* [[TMP118]], align 1
// CHK-C-NEXT:    [[BF_VALUE284:%.*]] = and i8 [[TMP119]], 1
// CHK-C-NEXT:    [[BF_SHL285:%.*]] = shl i8 [[BF_VALUE284]], 7
// CHK-C-NEXT:    [[BF_CLEAR286:%.*]] = and i8 [[BF_LOAD283]], 127
// CHK-C-NEXT:    [[BF_SET287:%.*]] = or i8 [[BF_CLEAR286]], [[BF_SHL285]]
// CHK-C-NEXT:    store i8 [[BF_SET287]], i8* [[TMP118]], align 1
// CHK-C-NEXT:    [[TMP120:%.*]] = load i8, i8* [[TMP118]], align 1
// CHK-C-NEXT:    [[TMP121:%.*]] = cmpxchg i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3), i8 [[TMP117]], i8 [[TMP120]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP122]] = extractvalue { i8, i1 } [[TMP121]], 0
// CHK-C-NEXT:    [[TMP123:%.*]] = extractvalue { i8, i1 } [[TMP121]], 1
// CHK-C-NEXT:    br i1 [[TMP123]], label [[ATOMIC_UPD_EXIT288:%.*]], label [[ATOMIC_CMP289]]
// CHK-C:       atomic_upd_exit288:
// CHK-C-NEXT:    store i32 [[TMP114]], i32* [[ATMP273]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT296]]
// CHK-C:       atomic_cmp289:
// CHK-C-NEXT:    [[TMP124:%.*]] = bitcast i32* [[ATOMIC_TEMP290]] to i8*
// CHK-C-NEXT:    store i8 [[TMP122]], i8* [[TMP124]], align 1
// CHK-C-NEXT:    [[BF_LOAD291:%.*]] = load i8, i8* [[TMP124]], align 1
// CHK-C-NEXT:    [[BF_ASHR292:%.*]] = ashr i8 [[BF_LOAD291]], 7
// CHK-C-NEXT:    [[BF_CAST293:%.*]] = sext i8 [[BF_ASHR292]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST293]], i32* [[ATMP273]], align 4
// CHK-C-NEXT:    [[CMP294:%.*]] = icmp eq i32 [[BF_CAST293]], [[TMP115]]
// CHK-C-NEXT:    [[FROMBOOL295:%.*]] = zext i1 [[CMP294]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL295]], i8* [[ATMP279]], align 1
// CHK-C-NEXT:    br i1 [[CMP294]], label [[ATOMIC_CONT281]], label [[ATOMIC_EXIT296]]
// CHK-C:       atomic_exit296:
// CHK-C-NEXT:    [[TMP125:%.*]] = load i32, i32* [[ATMP273]], align 4
// CHK-C-NEXT:    [[TMP126:%.*]] = load i8, i8* [[ATMP279]], align 1
// CHK-C-NEXT:    [[TMP127:%.*]] = trunc i8 [[TMP126]] to i1
// CHK-C-NEXT:    br i1 [[TMP127]], label [[ATOMIC_CAPTURE_CONT298:%.*]], label [[ATOMIC_CAPTURE297:%.*]]
// CHK-C:       atomic_capture297:
// CHK-C-NEXT:    store i32 [[TMP125]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT298]]
// CHK-C:       atomic_capture_cont298:
// CHK-C-NEXT:    [[TMP128:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP129:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD299:%.*]] = load atomic i8, i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3) monotonic, align 1
// CHK-C-NEXT:    [[TMP130:%.*]] = bitcast i32* [[ATOMIC_TEMP301]] to i8*
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD299]], i8* [[TMP130]], align 1
// CHK-C-NEXT:    [[BF_LOAD302:%.*]] = load i8, i8* [[TMP130]], align 1
// CHK-C-NEXT:    [[BF_ASHR303:%.*]] = ashr i8 [[BF_LOAD302]], 7
// CHK-C-NEXT:    [[BF_CAST304:%.*]] = sext i8 [[BF_ASHR303]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST304]], i32* [[ATMP300]], align 4
// CHK-C-NEXT:    [[CMP305:%.*]] = icmp eq i32 [[BF_CAST304]], [[TMP129]]
// CHK-C-NEXT:    [[FROMBOOL307:%.*]] = zext i1 [[CMP305]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL307]], i8* [[ATMP306]], align 1
// CHK-C-NEXT:    br i1 [[CMP305]], label [[ATOMIC_CONT308:%.*]], label [[ATOMIC_EXIT322:%.*]]
// CHK-C:       atomic_cont308:
// CHK-C-NEXT:    [[TMP131:%.*]] = phi i8 [ [[ATOMIC_LOAD299]], [[ATOMIC_CAPTURE_CONT298]] ], [ [[TMP136:%.*]], [[ATOMIC_CMP315:%.*]] ]
// CHK-C-NEXT:    [[TMP132:%.*]] = bitcast i32* [[ATOMIC_TEMP309]] to i8*
// CHK-C-NEXT:    store i8 [[TMP131]], i8* [[TMP132]], align 1
// CHK-C-NEXT:    [[TMP133:%.*]] = trunc i32 [[TMP128]] to i8
// CHK-C-NEXT:    [[BF_LOAD310:%.*]] = load i8, i8* [[TMP132]], align 1
// CHK-C-NEXT:    [[BF_VALUE311:%.*]] = and i8 [[TMP133]], 1
// CHK-C-NEXT:    [[BF_SHL312:%.*]] = shl i8 [[BF_VALUE311]], 7
// CHK-C-NEXT:    [[BF_CLEAR313:%.*]] = and i8 [[BF_LOAD310]], 127
// CHK-C-NEXT:    [[BF_SET314:%.*]] = or i8 [[BF_CLEAR313]], [[BF_SHL312]]
// CHK-C-NEXT:    store i8 [[BF_SET314]], i8* [[TMP132]], align 1
// CHK-C-NEXT:    [[TMP134:%.*]] = load i8, i8* [[TMP132]], align 1
// CHK-C-NEXT:    [[TMP135:%.*]] = cmpxchg i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3), i8 [[TMP131]], i8 [[TMP134]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP136]] = extractvalue { i8, i1 } [[TMP135]], 0
// CHK-C-NEXT:    [[TMP137:%.*]] = extractvalue { i8, i1 } [[TMP135]], 1
// CHK-C-NEXT:    br i1 [[TMP137]], label [[ATOMIC_EXIT322]], label [[ATOMIC_CMP315]]
// CHK-C:       atomic_cmp315:
// CHK-C-NEXT:    [[TMP138:%.*]] = bitcast i32* [[ATOMIC_TEMP316]] to i8*
// CHK-C-NEXT:    store i8 [[TMP136]], i8* [[TMP138]], align 1
// CHK-C-NEXT:    [[BF_LOAD317:%.*]] = load i8, i8* [[TMP138]], align 1
// CHK-C-NEXT:    [[BF_ASHR318:%.*]] = ashr i8 [[BF_LOAD317]], 7
// CHK-C-NEXT:    [[BF_CAST319:%.*]] = sext i8 [[BF_ASHR318]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST319]], i32* [[ATMP300]], align 4
// CHK-C-NEXT:    [[CMP320:%.*]] = icmp eq i32 [[BF_CAST319]], [[TMP129]]
// CHK-C-NEXT:    [[FROMBOOL321:%.*]] = zext i1 [[CMP320]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL321]], i8* [[ATMP306]], align 1
// CHK-C-NEXT:    br i1 [[CMP320]], label [[ATOMIC_CONT308]], label [[ATOMIC_EXIT322]]
// CHK-C:       atomic_exit322:
// CHK-C-NEXT:    [[TMP139:%.*]] = load i32, i32* [[ATMP300]], align 4
// CHK-C-NEXT:    [[TMP140:%.*]] = load i8, i8* [[ATMP306]], align 1
// CHK-C-NEXT:    [[CONV323:%.*]] = zext i8 [[TMP140]] to i32
// CHK-C-NEXT:    store i32 [[CONV323]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP141:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP142:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD324:%.*]] = load atomic i8, i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3) monotonic, align 1
// CHK-C-NEXT:    [[TMP143:%.*]] = bitcast i32* [[ATOMIC_TEMP326]] to i8*
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD324]], i8* [[TMP143]], align 1
// CHK-C-NEXT:    [[BF_LOAD327:%.*]] = load i8, i8* [[TMP143]], align 1
// CHK-C-NEXT:    [[BF_ASHR328:%.*]] = ashr i8 [[BF_LOAD327]], 7
// CHK-C-NEXT:    [[BF_CAST329:%.*]] = sext i8 [[BF_ASHR328]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST329]], i32* [[ATMP325]], align 4
// CHK-C-NEXT:    [[CMP330:%.*]] = icmp eq i32 [[BF_CAST329]], [[TMP142]]
// CHK-C-NEXT:    [[FROMBOOL332:%.*]] = zext i1 [[CMP330]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL332]], i8* [[ATMP331]], align 1
// CHK-C-NEXT:    br i1 [[CMP330]], label [[ATOMIC_CONT333:%.*]], label [[ATOMIC_EXIT347:%.*]]
// CHK-C:       atomic_cont333:
// CHK-C-NEXT:    [[TMP144:%.*]] = phi i8 [ [[ATOMIC_LOAD324]], [[ATOMIC_EXIT322]] ], [ [[TMP149:%.*]], [[ATOMIC_CMP340:%.*]] ]
// CHK-C-NEXT:    [[TMP145:%.*]] = bitcast i32* [[ATOMIC_TEMP334]] to i8*
// CHK-C-NEXT:    store i8 [[TMP144]], i8* [[TMP145]], align 1
// CHK-C-NEXT:    [[TMP146:%.*]] = trunc i32 [[TMP141]] to i8
// CHK-C-NEXT:    [[BF_LOAD335:%.*]] = load i8, i8* [[TMP145]], align 1
// CHK-C-NEXT:    [[BF_VALUE336:%.*]] = and i8 [[TMP146]], 1
// CHK-C-NEXT:    [[BF_SHL337:%.*]] = shl i8 [[BF_VALUE336]], 7
// CHK-C-NEXT:    [[BF_CLEAR338:%.*]] = and i8 [[BF_LOAD335]], 127
// CHK-C-NEXT:    [[BF_SET339:%.*]] = or i8 [[BF_CLEAR338]], [[BF_SHL337]]
// CHK-C-NEXT:    store i8 [[BF_SET339]], i8* [[TMP145]], align 1
// CHK-C-NEXT:    [[TMP147:%.*]] = load i8, i8* [[TMP145]], align 1
// CHK-C-NEXT:    [[TMP148:%.*]] = cmpxchg i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3), i8 [[TMP144]], i8 [[TMP147]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP149]] = extractvalue { i8, i1 } [[TMP148]], 0
// CHK-C-NEXT:    [[TMP150:%.*]] = extractvalue { i8, i1 } [[TMP148]], 1
// CHK-C-NEXT:    br i1 [[TMP150]], label [[ATOMIC_EXIT347]], label [[ATOMIC_CMP340]]
// CHK-C:       atomic_cmp340:
// CHK-C-NEXT:    [[TMP151:%.*]] = bitcast i32* [[ATOMIC_TEMP341]] to i8*
// CHK-C-NEXT:    store i8 [[TMP149]], i8* [[TMP151]], align 1
// CHK-C-NEXT:    [[BF_LOAD342:%.*]] = load i8, i8* [[TMP151]], align 1
// CHK-C-NEXT:    [[BF_ASHR343:%.*]] = ashr i8 [[BF_LOAD342]], 7
// CHK-C-NEXT:    [[BF_CAST344:%.*]] = sext i8 [[BF_ASHR343]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST344]], i32* [[ATMP325]], align 4
// CHK-C-NEXT:    [[CMP345:%.*]] = icmp eq i32 [[BF_CAST344]], [[TMP142]]
// CHK-C-NEXT:    [[FROMBOOL346:%.*]] = zext i1 [[CMP345]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL346]], i8* [[ATMP331]], align 1
// CHK-C-NEXT:    br i1 [[CMP345]], label [[ATOMIC_CONT333]], label [[ATOMIC_EXIT347]]
// CHK-C:       atomic_exit347:
// CHK-C-NEXT:    [[TMP152:%.*]] = load i32, i32* [[ATMP325]], align 4
// CHK-C-NEXT:    [[TMP153:%.*]] = load i8, i8* [[ATMP331]], align 1
// CHK-C-NEXT:    [[CONV348:%.*]] = zext i8 [[TMP153]] to i32
// CHK-C-NEXT:    store i32 [[CONV348]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP154:%.*]] = trunc i8 [[TMP153]] to i1
// CHK-C-NEXT:    br i1 [[TMP154]], label [[ATOMIC_CAPTURE_CONT350:%.*]], label [[ATOMIC_CAPTURE349:%.*]]
// CHK-C:       atomic_capture349:
// CHK-C-NEXT:    store i32 [[TMP152]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT350]]
// CHK-C:       atomic_capture_cont350:
// CHK-C-NEXT:    [[TMP155:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD351:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS3:%.*]], %struct.BitFields3* @bfx3, i32 0, i32 0) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD351]], i32* [[ATOMIC_TEMP353]], align 4
// CHK-C-NEXT:    [[BF_LOAD354:%.*]] = load i32, i32* [[ATOMIC_TEMP353]], align 4
// CHK-C-NEXT:    [[BF_SHL355:%.*]] = shl i32 [[BF_LOAD354]], 7
// CHK-C-NEXT:    [[BF_ASHR356:%.*]] = ashr i32 [[BF_SHL355]], 18
// CHK-C-NEXT:    store i32 [[BF_ASHR356]], i32* [[ATMP352]], align 4
// CHK-C-NEXT:    [[CMP357:%.*]] = icmp slt i32 [[BF_ASHR356]], [[TMP155]]
// CHK-C-NEXT:    [[FROMBOOL359:%.*]] = zext i1 [[CMP357]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL359]], i8* [[ATMP358]], align 1
// CHK-C-NEXT:    br i1 [[CMP357]], label [[ATOMIC_CONT360:%.*]], label [[ATOMIC_EXIT374:%.*]]
// CHK-C:       atomic_cont360:
// CHK-C-NEXT:    [[TMP156:%.*]] = phi i32 [ [[ATOMIC_LOAD351]], [[ATOMIC_CAPTURE_CONT350]] ], [ [[TMP159:%.*]], [[ATOMIC_CMP367:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP156]], i32* [[ATOMIC_TEMP361]], align 4
// CHK-C-NEXT:    [[BF_LOAD362:%.*]] = load i32, i32* [[ATOMIC_TEMP361]], align 4
// CHK-C-NEXT:    [[BF_VALUE363:%.*]] = and i32 [[TMP155]], 16383
// CHK-C-NEXT:    [[BF_SHL364:%.*]] = shl i32 [[BF_VALUE363]], 11
// CHK-C-NEXT:    [[BF_CLEAR365:%.*]] = and i32 [[BF_LOAD362]], -33552385
// CHK-C-NEXT:    [[BF_SET366:%.*]] = or i32 [[BF_CLEAR365]], [[BF_SHL364]]
// CHK-C-NEXT:    store i32 [[BF_SET366]], i32* [[ATOMIC_TEMP361]], align 4
// CHK-C-NEXT:    [[TMP157:%.*]] = load i32, i32* [[ATOMIC_TEMP361]], align 4
// CHK-C-NEXT:    [[TMP158:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0), i32 [[TMP156]], i32 [[TMP157]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP159]] = extractvalue { i32, i1 } [[TMP158]], 0
// CHK-C-NEXT:    [[TMP160:%.*]] = extractvalue { i32, i1 } [[TMP158]], 1
// CHK-C-NEXT:    br i1 [[TMP160]], label [[ATOMIC_EXIT374]], label [[ATOMIC_CMP367]]
// CHK-C:       atomic_cmp367:
// CHK-C-NEXT:    store i32 [[TMP159]], i32* [[ATOMIC_TEMP368]], align 4
// CHK-C-NEXT:    [[BF_LOAD369:%.*]] = load i32, i32* [[ATOMIC_TEMP368]], align 4
// CHK-C-NEXT:    [[BF_SHL370:%.*]] = shl i32 [[BF_LOAD369]], 7
// CHK-C-NEXT:    [[BF_ASHR371:%.*]] = ashr i32 [[BF_SHL370]], 18
// CHK-C-NEXT:    store i32 [[BF_ASHR371]], i32* [[ATMP352]], align 4
// CHK-C-NEXT:    [[CMP372:%.*]] = icmp slt i32 [[BF_ASHR371]], [[TMP155]]
// CHK-C-NEXT:    [[FROMBOOL373:%.*]] = zext i1 [[CMP372]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL373]], i8* [[ATMP358]], align 1
// CHK-C-NEXT:    br i1 [[CMP372]], label [[ATOMIC_CONT360]], label [[ATOMIC_EXIT374]]
// CHK-C:       atomic_exit374:
// CHK-C-NEXT:    [[TMP161:%.*]] = load i32, i32* [[ATMP352]], align 4
// CHK-C-NEXT:    [[TMP162:%.*]] = load i8, i8* [[ATMP358]], align 1
// CHK-C-NEXT:    store i32 [[TMP161]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP163:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD375:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD375]], i32* [[ATOMIC_TEMP377]], align 4
// CHK-C-NEXT:    [[BF_LOAD378:%.*]] = load i32, i32* [[ATOMIC_TEMP377]], align 4
// CHK-C-NEXT:    [[BF_SHL379:%.*]] = shl i32 [[BF_LOAD378]], 7
// CHK-C-NEXT:    [[BF_ASHR380:%.*]] = ashr i32 [[BF_SHL379]], 18
// CHK-C-NEXT:    store i32 [[BF_ASHR380]], i32* [[ATMP376]], align 4
// CHK-C-NEXT:    [[CMP381:%.*]] = icmp slt i32 [[BF_ASHR380]], [[TMP163]]
// CHK-C-NEXT:    [[FROMBOOL383:%.*]] = zext i1 [[CMP381]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL383]], i8* [[ATMP382]], align 1
// CHK-C-NEXT:    br i1 [[CMP381]], label [[ATOMIC_CONT384:%.*]], label [[ATOMIC_EXIT399:%.*]]
// CHK-C:       atomic_cont384:
// CHK-C-NEXT:    [[TMP164:%.*]] = phi i32 [ [[ATOMIC_LOAD375]], [[ATOMIC_EXIT374]] ], [ [[TMP167:%.*]], [[ATOMIC_CMP392:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP164]], i32* [[ATOMIC_TEMP385]], align 4
// CHK-C-NEXT:    [[BF_LOAD386:%.*]] = load i32, i32* [[ATOMIC_TEMP385]], align 4
// CHK-C-NEXT:    [[BF_VALUE387:%.*]] = and i32 [[TMP163]], 16383
// CHK-C-NEXT:    [[BF_SHL388:%.*]] = shl i32 [[BF_VALUE387]], 11
// CHK-C-NEXT:    [[BF_CLEAR389:%.*]] = and i32 [[BF_LOAD386]], -33552385
// CHK-C-NEXT:    [[BF_SET390:%.*]] = or i32 [[BF_CLEAR389]], [[BF_SHL388]]
// CHK-C-NEXT:    store i32 [[BF_SET390]], i32* [[ATOMIC_TEMP385]], align 4
// CHK-C-NEXT:    [[TMP165:%.*]] = load i32, i32* [[ATOMIC_TEMP385]], align 4
// CHK-C-NEXT:    [[TMP166:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0), i32 [[TMP164]], i32 [[TMP165]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP167]] = extractvalue { i32, i1 } [[TMP166]], 0
// CHK-C-NEXT:    [[TMP168:%.*]] = extractvalue { i32, i1 } [[TMP166]], 1
// CHK-C-NEXT:    br i1 [[TMP168]], label [[ATOMIC_UPD_EXIT391:%.*]], label [[ATOMIC_CMP392]]
// CHK-C:       atomic_upd_exit391:
// CHK-C-NEXT:    store i32 [[TMP163]], i32* [[ATMP376]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT399]]
// CHK-C:       atomic_cmp392:
// CHK-C-NEXT:    store i32 [[TMP167]], i32* [[ATOMIC_TEMP393]], align 4
// CHK-C-NEXT:    [[BF_LOAD394:%.*]] = load i32, i32* [[ATOMIC_TEMP393]], align 4
// CHK-C-NEXT:    [[BF_SHL395:%.*]] = shl i32 [[BF_LOAD394]], 7
// CHK-C-NEXT:    [[BF_ASHR396:%.*]] = ashr i32 [[BF_SHL395]], 18
// CHK-C-NEXT:    store i32 [[BF_ASHR396]], i32* [[ATMP376]], align 4
// CHK-C-NEXT:    [[CMP397:%.*]] = icmp slt i32 [[BF_ASHR396]], [[TMP163]]
// CHK-C-NEXT:    [[FROMBOOL398:%.*]] = zext i1 [[CMP397]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL398]], i8* [[ATMP382]], align 1
// CHK-C-NEXT:    br i1 [[CMP397]], label [[ATOMIC_CONT384]], label [[ATOMIC_EXIT399]]
// CHK-C:       atomic_exit399:
// CHK-C-NEXT:    [[TMP169:%.*]] = load i32, i32* [[ATMP376]], align 4
// CHK-C-NEXT:    [[TMP170:%.*]] = load i8, i8* [[ATMP382]], align 1
// CHK-C-NEXT:    store i32 [[TMP169]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP171:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP172:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD400:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD400]], i32* [[ATOMIC_TEMP402]], align 4
// CHK-C-NEXT:    [[BF_LOAD403:%.*]] = load i32, i32* [[ATOMIC_TEMP402]], align 4
// CHK-C-NEXT:    [[BF_SHL404:%.*]] = shl i32 [[BF_LOAD403]], 7
// CHK-C-NEXT:    [[BF_ASHR405:%.*]] = ashr i32 [[BF_SHL404]], 18
// CHK-C-NEXT:    store i32 [[BF_ASHR405]], i32* [[ATMP401]], align 4
// CHK-C-NEXT:    [[CMP406:%.*]] = icmp eq i32 [[BF_ASHR405]], [[TMP172]]
// CHK-C-NEXT:    [[FROMBOOL408:%.*]] = zext i1 [[CMP406]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL408]], i8* [[ATMP407]], align 1
// CHK-C-NEXT:    br i1 [[CMP406]], label [[ATOMIC_CONT409:%.*]], label [[ATOMIC_EXIT424:%.*]]
// CHK-C:       atomic_cont409:
// CHK-C-NEXT:    [[TMP173:%.*]] = phi i32 [ [[ATOMIC_LOAD400]], [[ATOMIC_EXIT399]] ], [ [[TMP176:%.*]], [[ATOMIC_CMP417:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP173]], i32* [[ATOMIC_TEMP410]], align 4
// CHK-C-NEXT:    [[BF_LOAD411:%.*]] = load i32, i32* [[ATOMIC_TEMP410]], align 4
// CHK-C-NEXT:    [[BF_VALUE412:%.*]] = and i32 [[TMP171]], 16383
// CHK-C-NEXT:    [[BF_SHL413:%.*]] = shl i32 [[BF_VALUE412]], 11
// CHK-C-NEXT:    [[BF_CLEAR414:%.*]] = and i32 [[BF_LOAD411]], -33552385
// CHK-C-NEXT:    [[BF_SET415:%.*]] = or i32 [[BF_CLEAR414]], [[BF_SHL413]]
// CHK-C-NEXT:    store i32 [[BF_SET415]], i32* [[ATOMIC_TEMP410]], align 4
// CHK-C-NEXT:    [[TMP174:%.*]] = load i32, i32* [[ATOMIC_TEMP410]], align 4
// CHK-C-NEXT:    [[TMP175:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0), i32 [[TMP173]], i32 [[TMP174]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP176]] = extractvalue { i32, i1 } [[TMP175]], 0
// CHK-C-NEXT:    [[TMP177:%.*]] = extractvalue { i32, i1 } [[TMP175]], 1
// CHK-C-NEXT:    br i1 [[TMP177]], label [[ATOMIC_UPD_EXIT416:%.*]], label [[ATOMIC_CMP417]]
// CHK-C:       atomic_upd_exit416:
// CHK-C-NEXT:    store i32 [[TMP171]], i32* [[ATMP401]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT424]]
// CHK-C:       atomic_cmp417:
// CHK-C-NEXT:    store i32 [[TMP176]], i32* [[ATOMIC_TEMP418]], align 4
// CHK-C-NEXT:    [[BF_LOAD419:%.*]] = load i32, i32* [[ATOMIC_TEMP418]], align 4
// CHK-C-NEXT:    [[BF_SHL420:%.*]] = shl i32 [[BF_LOAD419]], 7
// CHK-C-NEXT:    [[BF_ASHR421:%.*]] = ashr i32 [[BF_SHL420]], 18
// CHK-C-NEXT:    store i32 [[BF_ASHR421]], i32* [[ATMP401]], align 4
// CHK-C-NEXT:    [[CMP422:%.*]] = icmp eq i32 [[BF_ASHR421]], [[TMP172]]
// CHK-C-NEXT:    [[FROMBOOL423:%.*]] = zext i1 [[CMP422]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL423]], i8* [[ATMP407]], align 1
// CHK-C-NEXT:    br i1 [[CMP422]], label [[ATOMIC_CONT409]], label [[ATOMIC_EXIT424]]
// CHK-C:       atomic_exit424:
// CHK-C-NEXT:    [[TMP178:%.*]] = load i32, i32* [[ATMP401]], align 4
// CHK-C-NEXT:    [[TMP179:%.*]] = load i8, i8* [[ATMP407]], align 1
// CHK-C-NEXT:    [[TMP180:%.*]] = trunc i8 [[TMP179]] to i1
// CHK-C-NEXT:    br i1 [[TMP180]], label [[ATOMIC_CAPTURE_CONT426:%.*]], label [[ATOMIC_CAPTURE425:%.*]]
// CHK-C:       atomic_capture425:
// CHK-C-NEXT:    store i32 [[TMP178]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT426]]
// CHK-C:       atomic_capture_cont426:
// CHK-C-NEXT:    [[TMP181:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP182:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD427:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD427]], i32* [[ATOMIC_TEMP429]], align 4
// CHK-C-NEXT:    [[BF_LOAD430:%.*]] = load i32, i32* [[ATOMIC_TEMP429]], align 4
// CHK-C-NEXT:    [[BF_SHL431:%.*]] = shl i32 [[BF_LOAD430]], 7
// CHK-C-NEXT:    [[BF_ASHR432:%.*]] = ashr i32 [[BF_SHL431]], 18
// CHK-C-NEXT:    store i32 [[BF_ASHR432]], i32* [[ATMP428]], align 4
// CHK-C-NEXT:    [[CMP433:%.*]] = icmp eq i32 [[BF_ASHR432]], [[TMP182]]
// CHK-C-NEXT:    [[FROMBOOL435:%.*]] = zext i1 [[CMP433]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL435]], i8* [[ATMP434]], align 1
// CHK-C-NEXT:    br i1 [[CMP433]], label [[ATOMIC_CONT436:%.*]], label [[ATOMIC_EXIT450:%.*]]
// CHK-C:       atomic_cont436:
// CHK-C-NEXT:    [[TMP183:%.*]] = phi i32 [ [[ATOMIC_LOAD427]], [[ATOMIC_CAPTURE_CONT426]] ], [ [[TMP186:%.*]], [[ATOMIC_CMP443:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP183]], i32* [[ATOMIC_TEMP437]], align 4
// CHK-C-NEXT:    [[BF_LOAD438:%.*]] = load i32, i32* [[ATOMIC_TEMP437]], align 4
// CHK-C-NEXT:    [[BF_VALUE439:%.*]] = and i32 [[TMP181]], 16383
// CHK-C-NEXT:    [[BF_SHL440:%.*]] = shl i32 [[BF_VALUE439]], 11
// CHK-C-NEXT:    [[BF_CLEAR441:%.*]] = and i32 [[BF_LOAD438]], -33552385
// CHK-C-NEXT:    [[BF_SET442:%.*]] = or i32 [[BF_CLEAR441]], [[BF_SHL440]]
// CHK-C-NEXT:    store i32 [[BF_SET442]], i32* [[ATOMIC_TEMP437]], align 4
// CHK-C-NEXT:    [[TMP184:%.*]] = load i32, i32* [[ATOMIC_TEMP437]], align 4
// CHK-C-NEXT:    [[TMP185:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0), i32 [[TMP183]], i32 [[TMP184]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP186]] = extractvalue { i32, i1 } [[TMP185]], 0
// CHK-C-NEXT:    [[TMP187:%.*]] = extractvalue { i32, i1 } [[TMP185]], 1
// CHK-C-NEXT:    br i1 [[TMP187]], label [[ATOMIC_EXIT450]], label [[ATOMIC_CMP443]]
// CHK-C:       atomic_cmp443:
// CHK-C-NEXT:    store i32 [[TMP186]], i32* [[ATOMIC_TEMP444]], align 4
// CHK-C-NEXT:    [[BF_LOAD445:%.*]] = load i32, i32* [[ATOMIC_TEMP444]], align 4
// CHK-C-NEXT:    [[BF_SHL446:%.*]] = shl i32 [[BF_LOAD445]], 7
// CHK-C-NEXT:    [[BF_ASHR447:%.*]] = ashr i32 [[BF_SHL446]], 18
// CHK-C-NEXT:    store i32 [[BF_ASHR447]], i32* [[ATMP428]], align 4
// CHK-C-NEXT:    [[CMP448:%.*]] = icmp eq i32 [[BF_ASHR447]], [[TMP182]]
// CHK-C-NEXT:    [[FROMBOOL449:%.*]] = zext i1 [[CMP448]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL449]], i8* [[ATMP434]], align 1
// CHK-C-NEXT:    br i1 [[CMP448]], label [[ATOMIC_CONT436]], label [[ATOMIC_EXIT450]]
// CHK-C:       atomic_exit450:
// CHK-C-NEXT:    [[TMP188:%.*]] = load i32, i32* [[ATMP428]], align 4
// CHK-C-NEXT:    [[TMP189:%.*]] = load i8, i8* [[ATMP434]], align 1
// CHK-C-NEXT:    [[CONV451:%.*]] = zext i8 [[TMP189]] to i32
// CHK-C-NEXT:    store i32 [[CONV451]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP190:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP191:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD452:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0) monotonic, align 4
// CHK-C-NEXT:    store i32 [[ATOMIC_LOAD452]], i32* [[ATOMIC_TEMP454]], align 4
// CHK-C-NEXT:    [[BF_LOAD455:%.*]] = load i32, i32* [[ATOMIC_TEMP454]], align 4
// CHK-C-NEXT:    [[BF_SHL456:%.*]] = shl i32 [[BF_LOAD455]], 7
// CHK-C-NEXT:    [[BF_ASHR457:%.*]] = ashr i32 [[BF_SHL456]], 18
// CHK-C-NEXT:    store i32 [[BF_ASHR457]], i32* [[ATMP453]], align 4
// CHK-C-NEXT:    [[CMP458:%.*]] = icmp eq i32 [[BF_ASHR457]], [[TMP191]]
// CHK-C-NEXT:    [[FROMBOOL460:%.*]] = zext i1 [[CMP458]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL460]], i8* [[ATMP459]], align 1
// CHK-C-NEXT:    br i1 [[CMP458]], label [[ATOMIC_CONT461:%.*]], label [[ATOMIC_EXIT475:%.*]]
// CHK-C:       atomic_cont461:
// CHK-C-NEXT:    [[TMP192:%.*]] = phi i32 [ [[ATOMIC_LOAD452]], [[ATOMIC_EXIT450]] ], [ [[TMP195:%.*]], [[ATOMIC_CMP468:%.*]] ]
// CHK-C-NEXT:    store i32 [[TMP192]], i32* [[ATOMIC_TEMP462]], align 4
// CHK-C-NEXT:    [[BF_LOAD463:%.*]] = load i32, i32* [[ATOMIC_TEMP462]], align 4
// CHK-C-NEXT:    [[BF_VALUE464:%.*]] = and i32 [[TMP190]], 16383
// CHK-C-NEXT:    [[BF_SHL465:%.*]] = shl i32 [[BF_VALUE464]], 11
// CHK-C-NEXT:    [[BF_CLEAR466:%.*]] = and i32 [[BF_LOAD463]], -33552385
// CHK-C-NEXT:    [[BF_SET467:%.*]] = or i32 [[BF_CLEAR466]], [[BF_SHL465]]
// CHK-C-NEXT:    store i32 [[BF_SET467]], i32* [[ATOMIC_TEMP462]], align 4
// CHK-C-NEXT:    [[TMP193:%.*]] = load i32, i32* [[ATOMIC_TEMP462]], align 4
// CHK-C-NEXT:    [[TMP194:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0), i32 [[TMP192]], i32 [[TMP193]] monotonic monotonic, align 4
// CHK-C-NEXT:    [[TMP195]] = extractvalue { i32, i1 } [[TMP194]], 0
// CHK-C-NEXT:    [[TMP196:%.*]] = extractvalue { i32, i1 } [[TMP194]], 1
// CHK-C-NEXT:    br i1 [[TMP196]], label [[ATOMIC_EXIT475]], label [[ATOMIC_CMP468]]
// CHK-C:       atomic_cmp468:
// CHK-C-NEXT:    store i32 [[TMP195]], i32* [[ATOMIC_TEMP469]], align 4
// CHK-C-NEXT:    [[BF_LOAD470:%.*]] = load i32, i32* [[ATOMIC_TEMP469]], align 4
// CHK-C-NEXT:    [[BF_SHL471:%.*]] = shl i32 [[BF_LOAD470]], 7
// CHK-C-NEXT:    [[BF_ASHR472:%.*]] = ashr i32 [[BF_SHL471]], 18
// CHK-C-NEXT:    store i32 [[BF_ASHR472]], i32* [[ATMP453]], align 4
// CHK-C-NEXT:    [[CMP473:%.*]] = icmp eq i32 [[BF_ASHR472]], [[TMP191]]
// CHK-C-NEXT:    [[FROMBOOL474:%.*]] = zext i1 [[CMP473]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL474]], i8* [[ATMP459]], align 1
// CHK-C-NEXT:    br i1 [[CMP473]], label [[ATOMIC_CONT461]], label [[ATOMIC_EXIT475]]
// CHK-C:       atomic_exit475:
// CHK-C-NEXT:    [[TMP197:%.*]] = load i32, i32* [[ATMP453]], align 4
// CHK-C-NEXT:    [[TMP198:%.*]] = load i8, i8* [[ATMP459]], align 1
// CHK-C-NEXT:    [[CONV476:%.*]] = zext i8 [[TMP198]] to i32
// CHK-C-NEXT:    store i32 [[CONV476]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP199:%.*]] = trunc i8 [[TMP198]] to i1
// CHK-C-NEXT:    br i1 [[TMP199]], label [[ATOMIC_CAPTURE_CONT478:%.*]], label [[ATOMIC_CAPTURE477:%.*]]
// CHK-C:       atomic_capture477:
// CHK-C-NEXT:    store i32 [[TMP197]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT478]]
// CHK-C:       atomic_capture_cont478:
// CHK-C-NEXT:    [[TMP200:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD479:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD479]], i64* [[ATOMIC_TEMP481]], align 8
// CHK-C-NEXT:    [[BF_LOAD482:%.*]] = load i64, i64* [[ATOMIC_TEMP481]], align 8
// CHK-C-NEXT:    [[BF_SHL483:%.*]] = shl i64 [[BF_LOAD482]], 47
// CHK-C-NEXT:    [[BF_ASHR484:%.*]] = ashr i64 [[BF_SHL483]], 63
// CHK-C-NEXT:    [[BF_CAST485:%.*]] = trunc i64 [[BF_ASHR484]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST485]], i32* [[ATMP480]], align 4
// CHK-C-NEXT:    [[CMP486:%.*]] = icmp slt i32 [[BF_CAST485]], [[TMP200]]
// CHK-C-NEXT:    [[FROMBOOL488:%.*]] = zext i1 [[CMP486]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL488]], i8* [[ATMP487]], align 1
// CHK-C-NEXT:    br i1 [[CMP486]], label [[ATOMIC_CONT489:%.*]], label [[ATOMIC_EXIT504:%.*]]
// CHK-C:       atomic_cont489:
// CHK-C-NEXT:    [[TMP201:%.*]] = phi i64 [ [[ATOMIC_LOAD479]], [[ATOMIC_CAPTURE_CONT478]] ], [ [[TMP205:%.*]], [[ATOMIC_CMP496:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP201]], i64* [[ATOMIC_TEMP490]], align 8
// CHK-C-NEXT:    [[TMP202:%.*]] = zext i32 [[TMP200]] to i64
// CHK-C-NEXT:    [[BF_LOAD491:%.*]] = load i64, i64* [[ATOMIC_TEMP490]], align 8
// CHK-C-NEXT:    [[BF_VALUE492:%.*]] = and i64 [[TMP202]], 1
// CHK-C-NEXT:    [[BF_SHL493:%.*]] = shl i64 [[BF_VALUE492]], 16
// CHK-C-NEXT:    [[BF_CLEAR494:%.*]] = and i64 [[BF_LOAD491]], -65537
// CHK-C-NEXT:    [[BF_SET495:%.*]] = or i64 [[BF_CLEAR494]], [[BF_SHL493]]
// CHK-C-NEXT:    store i64 [[BF_SET495]], i64* [[ATOMIC_TEMP490]], align 8
// CHK-C-NEXT:    [[TMP203:%.*]] = load i64, i64* [[ATOMIC_TEMP490]], align 8
// CHK-C-NEXT:    [[TMP204:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP201]], i64 [[TMP203]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP205]] = extractvalue { i64, i1 } [[TMP204]], 0
// CHK-C-NEXT:    [[TMP206:%.*]] = extractvalue { i64, i1 } [[TMP204]], 1
// CHK-C-NEXT:    br i1 [[TMP206]], label [[ATOMIC_EXIT504]], label [[ATOMIC_CMP496]]
// CHK-C:       atomic_cmp496:
// CHK-C-NEXT:    store i64 [[TMP205]], i64* [[ATOMIC_TEMP497]], align 8
// CHK-C-NEXT:    [[BF_LOAD498:%.*]] = load i64, i64* [[ATOMIC_TEMP497]], align 8
// CHK-C-NEXT:    [[BF_SHL499:%.*]] = shl i64 [[BF_LOAD498]], 47
// CHK-C-NEXT:    [[BF_ASHR500:%.*]] = ashr i64 [[BF_SHL499]], 63
// CHK-C-NEXT:    [[BF_CAST501:%.*]] = trunc i64 [[BF_ASHR500]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST501]], i32* [[ATMP480]], align 4
// CHK-C-NEXT:    [[CMP502:%.*]] = icmp slt i32 [[BF_CAST501]], [[TMP200]]
// CHK-C-NEXT:    [[FROMBOOL503:%.*]] = zext i1 [[CMP502]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL503]], i8* [[ATMP487]], align 1
// CHK-C-NEXT:    br i1 [[CMP502]], label [[ATOMIC_CONT489]], label [[ATOMIC_EXIT504]]
// CHK-C:       atomic_exit504:
// CHK-C-NEXT:    [[TMP207:%.*]] = load i32, i32* [[ATMP480]], align 4
// CHK-C-NEXT:    [[TMP208:%.*]] = load i8, i8* [[ATMP487]], align 1
// CHK-C-NEXT:    store i32 [[TMP207]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP209:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD505:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD505]], i64* [[ATOMIC_TEMP507]], align 8
// CHK-C-NEXT:    [[BF_LOAD508:%.*]] = load i64, i64* [[ATOMIC_TEMP507]], align 8
// CHK-C-NEXT:    [[BF_SHL509:%.*]] = shl i64 [[BF_LOAD508]], 47
// CHK-C-NEXT:    [[BF_ASHR510:%.*]] = ashr i64 [[BF_SHL509]], 63
// CHK-C-NEXT:    [[BF_CAST511:%.*]] = trunc i64 [[BF_ASHR510]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST511]], i32* [[ATMP506]], align 4
// CHK-C-NEXT:    [[CMP512:%.*]] = icmp slt i32 [[BF_CAST511]], [[TMP209]]
// CHK-C-NEXT:    [[FROMBOOL514:%.*]] = zext i1 [[CMP512]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL514]], i8* [[ATMP513]], align 1
// CHK-C-NEXT:    br i1 [[CMP512]], label [[ATOMIC_CONT515:%.*]], label [[ATOMIC_EXIT531:%.*]]
// CHK-C:       atomic_cont515:
// CHK-C-NEXT:    [[TMP210:%.*]] = phi i64 [ [[ATOMIC_LOAD505]], [[ATOMIC_EXIT504]] ], [ [[TMP214:%.*]], [[ATOMIC_CMP523:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP210]], i64* [[ATOMIC_TEMP516]], align 8
// CHK-C-NEXT:    [[TMP211:%.*]] = zext i32 [[TMP209]] to i64
// CHK-C-NEXT:    [[BF_LOAD517:%.*]] = load i64, i64* [[ATOMIC_TEMP516]], align 8
// CHK-C-NEXT:    [[BF_VALUE518:%.*]] = and i64 [[TMP211]], 1
// CHK-C-NEXT:    [[BF_SHL519:%.*]] = shl i64 [[BF_VALUE518]], 16
// CHK-C-NEXT:    [[BF_CLEAR520:%.*]] = and i64 [[BF_LOAD517]], -65537
// CHK-C-NEXT:    [[BF_SET521:%.*]] = or i64 [[BF_CLEAR520]], [[BF_SHL519]]
// CHK-C-NEXT:    store i64 [[BF_SET521]], i64* [[ATOMIC_TEMP516]], align 8
// CHK-C-NEXT:    [[TMP212:%.*]] = load i64, i64* [[ATOMIC_TEMP516]], align 8
// CHK-C-NEXT:    [[TMP213:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP210]], i64 [[TMP212]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP214]] = extractvalue { i64, i1 } [[TMP213]], 0
// CHK-C-NEXT:    [[TMP215:%.*]] = extractvalue { i64, i1 } [[TMP213]], 1
// CHK-C-NEXT:    br i1 [[TMP215]], label [[ATOMIC_UPD_EXIT522:%.*]], label [[ATOMIC_CMP523]]
// CHK-C:       atomic_upd_exit522:
// CHK-C-NEXT:    store i32 [[TMP209]], i32* [[ATMP506]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT531]]
// CHK-C:       atomic_cmp523:
// CHK-C-NEXT:    store i64 [[TMP214]], i64* [[ATOMIC_TEMP524]], align 8
// CHK-C-NEXT:    [[BF_LOAD525:%.*]] = load i64, i64* [[ATOMIC_TEMP524]], align 8
// CHK-C-NEXT:    [[BF_SHL526:%.*]] = shl i64 [[BF_LOAD525]], 47
// CHK-C-NEXT:    [[BF_ASHR527:%.*]] = ashr i64 [[BF_SHL526]], 63
// CHK-C-NEXT:    [[BF_CAST528:%.*]] = trunc i64 [[BF_ASHR527]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST528]], i32* [[ATMP506]], align 4
// CHK-C-NEXT:    [[CMP529:%.*]] = icmp slt i32 [[BF_CAST528]], [[TMP209]]
// CHK-C-NEXT:    [[FROMBOOL530:%.*]] = zext i1 [[CMP529]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL530]], i8* [[ATMP513]], align 1
// CHK-C-NEXT:    br i1 [[CMP529]], label [[ATOMIC_CONT515]], label [[ATOMIC_EXIT531]]
// CHK-C:       atomic_exit531:
// CHK-C-NEXT:    [[TMP216:%.*]] = load i32, i32* [[ATMP506]], align 4
// CHK-C-NEXT:    [[TMP217:%.*]] = load i8, i8* [[ATMP513]], align 1
// CHK-C-NEXT:    store i32 [[TMP216]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP218:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP219:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD532:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD532]], i64* [[ATOMIC_TEMP534]], align 8
// CHK-C-NEXT:    [[BF_LOAD535:%.*]] = load i64, i64* [[ATOMIC_TEMP534]], align 8
// CHK-C-NEXT:    [[BF_SHL536:%.*]] = shl i64 [[BF_LOAD535]], 47
// CHK-C-NEXT:    [[BF_ASHR537:%.*]] = ashr i64 [[BF_SHL536]], 63
// CHK-C-NEXT:    [[BF_CAST538:%.*]] = trunc i64 [[BF_ASHR537]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST538]], i32* [[ATMP533]], align 4
// CHK-C-NEXT:    [[CMP539:%.*]] = icmp eq i32 [[BF_CAST538]], [[TMP219]]
// CHK-C-NEXT:    [[FROMBOOL541:%.*]] = zext i1 [[CMP539]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL541]], i8* [[ATMP540]], align 1
// CHK-C-NEXT:    br i1 [[CMP539]], label [[ATOMIC_CONT542:%.*]], label [[ATOMIC_EXIT558:%.*]]
// CHK-C:       atomic_cont542:
// CHK-C-NEXT:    [[TMP220:%.*]] = phi i64 [ [[ATOMIC_LOAD532]], [[ATOMIC_EXIT531]] ], [ [[TMP224:%.*]], [[ATOMIC_CMP550:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP220]], i64* [[ATOMIC_TEMP543]], align 8
// CHK-C-NEXT:    [[TMP221:%.*]] = zext i32 [[TMP218]] to i64
// CHK-C-NEXT:    [[BF_LOAD544:%.*]] = load i64, i64* [[ATOMIC_TEMP543]], align 8
// CHK-C-NEXT:    [[BF_VALUE545:%.*]] = and i64 [[TMP221]], 1
// CHK-C-NEXT:    [[BF_SHL546:%.*]] = shl i64 [[BF_VALUE545]], 16
// CHK-C-NEXT:    [[BF_CLEAR547:%.*]] = and i64 [[BF_LOAD544]], -65537
// CHK-C-NEXT:    [[BF_SET548:%.*]] = or i64 [[BF_CLEAR547]], [[BF_SHL546]]
// CHK-C-NEXT:    store i64 [[BF_SET548]], i64* [[ATOMIC_TEMP543]], align 8
// CHK-C-NEXT:    [[TMP222:%.*]] = load i64, i64* [[ATOMIC_TEMP543]], align 8
// CHK-C-NEXT:    [[TMP223:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP220]], i64 [[TMP222]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP224]] = extractvalue { i64, i1 } [[TMP223]], 0
// CHK-C-NEXT:    [[TMP225:%.*]] = extractvalue { i64, i1 } [[TMP223]], 1
// CHK-C-NEXT:    br i1 [[TMP225]], label [[ATOMIC_UPD_EXIT549:%.*]], label [[ATOMIC_CMP550]]
// CHK-C:       atomic_upd_exit549:
// CHK-C-NEXT:    store i32 [[TMP218]], i32* [[ATMP533]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT558]]
// CHK-C:       atomic_cmp550:
// CHK-C-NEXT:    store i64 [[TMP224]], i64* [[ATOMIC_TEMP551]], align 8
// CHK-C-NEXT:    [[BF_LOAD552:%.*]] = load i64, i64* [[ATOMIC_TEMP551]], align 8
// CHK-C-NEXT:    [[BF_SHL553:%.*]] = shl i64 [[BF_LOAD552]], 47
// CHK-C-NEXT:    [[BF_ASHR554:%.*]] = ashr i64 [[BF_SHL553]], 63
// CHK-C-NEXT:    [[BF_CAST555:%.*]] = trunc i64 [[BF_ASHR554]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST555]], i32* [[ATMP533]], align 4
// CHK-C-NEXT:    [[CMP556:%.*]] = icmp eq i32 [[BF_CAST555]], [[TMP219]]
// CHK-C-NEXT:    [[FROMBOOL557:%.*]] = zext i1 [[CMP556]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL557]], i8* [[ATMP540]], align 1
// CHK-C-NEXT:    br i1 [[CMP556]], label [[ATOMIC_CONT542]], label [[ATOMIC_EXIT558]]
// CHK-C:       atomic_exit558:
// CHK-C-NEXT:    [[TMP226:%.*]] = load i32, i32* [[ATMP533]], align 4
// CHK-C-NEXT:    [[TMP227:%.*]] = load i8, i8* [[ATMP540]], align 1
// CHK-C-NEXT:    [[TMP228:%.*]] = trunc i8 [[TMP227]] to i1
// CHK-C-NEXT:    br i1 [[TMP228]], label [[ATOMIC_CAPTURE_CONT560:%.*]], label [[ATOMIC_CAPTURE559:%.*]]
// CHK-C:       atomic_capture559:
// CHK-C-NEXT:    store i32 [[TMP226]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT560]]
// CHK-C:       atomic_capture_cont560:
// CHK-C-NEXT:    [[TMP229:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP230:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD561:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD561]], i64* [[ATOMIC_TEMP563]], align 8
// CHK-C-NEXT:    [[BF_LOAD564:%.*]] = load i64, i64* [[ATOMIC_TEMP563]], align 8
// CHK-C-NEXT:    [[BF_SHL565:%.*]] = shl i64 [[BF_LOAD564]], 47
// CHK-C-NEXT:    [[BF_ASHR566:%.*]] = ashr i64 [[BF_SHL565]], 63
// CHK-C-NEXT:    [[BF_CAST567:%.*]] = trunc i64 [[BF_ASHR566]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST567]], i32* [[ATMP562]], align 4
// CHK-C-NEXT:    [[CMP568:%.*]] = icmp eq i32 [[BF_CAST567]], [[TMP230]]
// CHK-C-NEXT:    [[FROMBOOL570:%.*]] = zext i1 [[CMP568]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL570]], i8* [[ATMP569]], align 1
// CHK-C-NEXT:    br i1 [[CMP568]], label [[ATOMIC_CONT571:%.*]], label [[ATOMIC_EXIT586:%.*]]
// CHK-C:       atomic_cont571:
// CHK-C-NEXT:    [[TMP231:%.*]] = phi i64 [ [[ATOMIC_LOAD561]], [[ATOMIC_CAPTURE_CONT560]] ], [ [[TMP235:%.*]], [[ATOMIC_CMP578:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP231]], i64* [[ATOMIC_TEMP572]], align 8
// CHK-C-NEXT:    [[TMP232:%.*]] = zext i32 [[TMP229]] to i64
// CHK-C-NEXT:    [[BF_LOAD573:%.*]] = load i64, i64* [[ATOMIC_TEMP572]], align 8
// CHK-C-NEXT:    [[BF_VALUE574:%.*]] = and i64 [[TMP232]], 1
// CHK-C-NEXT:    [[BF_SHL575:%.*]] = shl i64 [[BF_VALUE574]], 16
// CHK-C-NEXT:    [[BF_CLEAR576:%.*]] = and i64 [[BF_LOAD573]], -65537
// CHK-C-NEXT:    [[BF_SET577:%.*]] = or i64 [[BF_CLEAR576]], [[BF_SHL575]]
// CHK-C-NEXT:    store i64 [[BF_SET577]], i64* [[ATOMIC_TEMP572]], align 8
// CHK-C-NEXT:    [[TMP233:%.*]] = load i64, i64* [[ATOMIC_TEMP572]], align 8
// CHK-C-NEXT:    [[TMP234:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP231]], i64 [[TMP233]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP235]] = extractvalue { i64, i1 } [[TMP234]], 0
// CHK-C-NEXT:    [[TMP236:%.*]] = extractvalue { i64, i1 } [[TMP234]], 1
// CHK-C-NEXT:    br i1 [[TMP236]], label [[ATOMIC_EXIT586]], label [[ATOMIC_CMP578]]
// CHK-C:       atomic_cmp578:
// CHK-C-NEXT:    store i64 [[TMP235]], i64* [[ATOMIC_TEMP579]], align 8
// CHK-C-NEXT:    [[BF_LOAD580:%.*]] = load i64, i64* [[ATOMIC_TEMP579]], align 8
// CHK-C-NEXT:    [[BF_SHL581:%.*]] = shl i64 [[BF_LOAD580]], 47
// CHK-C-NEXT:    [[BF_ASHR582:%.*]] = ashr i64 [[BF_SHL581]], 63
// CHK-C-NEXT:    [[BF_CAST583:%.*]] = trunc i64 [[BF_ASHR582]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST583]], i32* [[ATMP562]], align 4
// CHK-C-NEXT:    [[CMP584:%.*]] = icmp eq i32 [[BF_CAST583]], [[TMP230]]
// CHK-C-NEXT:    [[FROMBOOL585:%.*]] = zext i1 [[CMP584]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL585]], i8* [[ATMP569]], align 1
// CHK-C-NEXT:    br i1 [[CMP584]], label [[ATOMIC_CONT571]], label [[ATOMIC_EXIT586]]
// CHK-C:       atomic_exit586:
// CHK-C-NEXT:    [[TMP237:%.*]] = load i32, i32* [[ATMP562]], align 4
// CHK-C-NEXT:    [[TMP238:%.*]] = load i8, i8* [[ATMP569]], align 1
// CHK-C-NEXT:    [[CONV587:%.*]] = zext i8 [[TMP238]] to i32
// CHK-C-NEXT:    store i32 [[CONV587]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP239:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP240:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD588:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD588]], i64* [[ATOMIC_TEMP590]], align 8
// CHK-C-NEXT:    [[BF_LOAD591:%.*]] = load i64, i64* [[ATOMIC_TEMP590]], align 8
// CHK-C-NEXT:    [[BF_SHL592:%.*]] = shl i64 [[BF_LOAD591]], 47
// CHK-C-NEXT:    [[BF_ASHR593:%.*]] = ashr i64 [[BF_SHL592]], 63
// CHK-C-NEXT:    [[BF_CAST594:%.*]] = trunc i64 [[BF_ASHR593]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST594]], i32* [[ATMP589]], align 4
// CHK-C-NEXT:    [[CMP595:%.*]] = icmp eq i32 [[BF_CAST594]], [[TMP240]]
// CHK-C-NEXT:    [[FROMBOOL597:%.*]] = zext i1 [[CMP595]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL597]], i8* [[ATMP596]], align 1
// CHK-C-NEXT:    br i1 [[CMP595]], label [[ATOMIC_CONT598:%.*]], label [[ATOMIC_EXIT613:%.*]]
// CHK-C:       atomic_cont598:
// CHK-C-NEXT:    [[TMP241:%.*]] = phi i64 [ [[ATOMIC_LOAD588]], [[ATOMIC_EXIT586]] ], [ [[TMP245:%.*]], [[ATOMIC_CMP605:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP241]], i64* [[ATOMIC_TEMP599]], align 8
// CHK-C-NEXT:    [[TMP242:%.*]] = zext i32 [[TMP239]] to i64
// CHK-C-NEXT:    [[BF_LOAD600:%.*]] = load i64, i64* [[ATOMIC_TEMP599]], align 8
// CHK-C-NEXT:    [[BF_VALUE601:%.*]] = and i64 [[TMP242]], 1
// CHK-C-NEXT:    [[BF_SHL602:%.*]] = shl i64 [[BF_VALUE601]], 16
// CHK-C-NEXT:    [[BF_CLEAR603:%.*]] = and i64 [[BF_LOAD600]], -65537
// CHK-C-NEXT:    [[BF_SET604:%.*]] = or i64 [[BF_CLEAR603]], [[BF_SHL602]]
// CHK-C-NEXT:    store i64 [[BF_SET604]], i64* [[ATOMIC_TEMP599]], align 8
// CHK-C-NEXT:    [[TMP243:%.*]] = load i64, i64* [[ATOMIC_TEMP599]], align 8
// CHK-C-NEXT:    [[TMP244:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP241]], i64 [[TMP243]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP245]] = extractvalue { i64, i1 } [[TMP244]], 0
// CHK-C-NEXT:    [[TMP246:%.*]] = extractvalue { i64, i1 } [[TMP244]], 1
// CHK-C-NEXT:    br i1 [[TMP246]], label [[ATOMIC_EXIT613]], label [[ATOMIC_CMP605]]
// CHK-C:       atomic_cmp605:
// CHK-C-NEXT:    store i64 [[TMP245]], i64* [[ATOMIC_TEMP606]], align 8
// CHK-C-NEXT:    [[BF_LOAD607:%.*]] = load i64, i64* [[ATOMIC_TEMP606]], align 8
// CHK-C-NEXT:    [[BF_SHL608:%.*]] = shl i64 [[BF_LOAD607]], 47
// CHK-C-NEXT:    [[BF_ASHR609:%.*]] = ashr i64 [[BF_SHL608]], 63
// CHK-C-NEXT:    [[BF_CAST610:%.*]] = trunc i64 [[BF_ASHR609]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST610]], i32* [[ATMP589]], align 4
// CHK-C-NEXT:    [[CMP611:%.*]] = icmp eq i32 [[BF_CAST610]], [[TMP240]]
// CHK-C-NEXT:    [[FROMBOOL612:%.*]] = zext i1 [[CMP611]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL612]], i8* [[ATMP596]], align 1
// CHK-C-NEXT:    br i1 [[CMP611]], label [[ATOMIC_CONT598]], label [[ATOMIC_EXIT613]]
// CHK-C:       atomic_exit613:
// CHK-C-NEXT:    [[TMP247:%.*]] = load i32, i32* [[ATMP589]], align 4
// CHK-C-NEXT:    [[TMP248:%.*]] = load i8, i8* [[ATMP596]], align 1
// CHK-C-NEXT:    [[CONV614:%.*]] = zext i8 [[TMP248]] to i32
// CHK-C-NEXT:    store i32 [[CONV614]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP249:%.*]] = trunc i8 [[TMP248]] to i1
// CHK-C-NEXT:    br i1 [[TMP249]], label [[ATOMIC_CAPTURE_CONT616:%.*]], label [[ATOMIC_CAPTURE615:%.*]]
// CHK-C:       atomic_capture615:
// CHK-C-NEXT:    store i32 [[TMP247]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT616]]
// CHK-C:       atomic_capture_cont616:
// CHK-C-NEXT:    [[TMP250:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[CONV617:%.*]] = sext i32 [[TMP250]] to i64
// CHK-C-NEXT:    [[ATOMIC_LOAD618:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD618]], i64* [[ATOMIC_TEMP620]], align 8
// CHK-C-NEXT:    [[BF_LOAD621:%.*]] = load i64, i64* [[ATOMIC_TEMP620]], align 8
// CHK-C-NEXT:    [[BF_SHL622:%.*]] = shl i64 [[BF_LOAD621]], 40
// CHK-C-NEXT:    [[BF_ASHR623:%.*]] = ashr i64 [[BF_SHL622]], 57
// CHK-C-NEXT:    store i64 [[BF_ASHR623]], i64* [[ATMP619]], align 8
// CHK-C-NEXT:    [[CMP624:%.*]] = icmp slt i64 [[BF_ASHR623]], [[CONV617]]
// CHK-C-NEXT:    [[FROMBOOL626:%.*]] = zext i1 [[CMP624]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL626]], i8* [[ATMP625]], align 1
// CHK-C-NEXT:    br i1 [[CMP624]], label [[ATOMIC_CONT627:%.*]], label [[ATOMIC_EXIT641:%.*]]
// CHK-C:       atomic_cont627:
// CHK-C-NEXT:    [[TMP251:%.*]] = phi i64 [ [[ATOMIC_LOAD618]], [[ATOMIC_CAPTURE_CONT616]] ], [ [[TMP254:%.*]], [[ATOMIC_CMP634:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP251]], i64* [[ATOMIC_TEMP628]], align 8
// CHK-C-NEXT:    [[BF_LOAD629:%.*]] = load i64, i64* [[ATOMIC_TEMP628]], align 8
// CHK-C-NEXT:    [[BF_VALUE630:%.*]] = and i64 [[CONV617]], 127
// CHK-C-NEXT:    [[BF_SHL631:%.*]] = shl i64 [[BF_VALUE630]], 17
// CHK-C-NEXT:    [[BF_CLEAR632:%.*]] = and i64 [[BF_LOAD629]], -16646145
// CHK-C-NEXT:    [[BF_SET633:%.*]] = or i64 [[BF_CLEAR632]], [[BF_SHL631]]
// CHK-C-NEXT:    store i64 [[BF_SET633]], i64* [[ATOMIC_TEMP628]], align 8
// CHK-C-NEXT:    [[TMP252:%.*]] = load i64, i64* [[ATOMIC_TEMP628]], align 8
// CHK-C-NEXT:    [[TMP253:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP251]], i64 [[TMP252]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP254]] = extractvalue { i64, i1 } [[TMP253]], 0
// CHK-C-NEXT:    [[TMP255:%.*]] = extractvalue { i64, i1 } [[TMP253]], 1
// CHK-C-NEXT:    br i1 [[TMP255]], label [[ATOMIC_EXIT641]], label [[ATOMIC_CMP634]]
// CHK-C:       atomic_cmp634:
// CHK-C-NEXT:    store i64 [[TMP254]], i64* [[ATOMIC_TEMP635]], align 8
// CHK-C-NEXT:    [[BF_LOAD636:%.*]] = load i64, i64* [[ATOMIC_TEMP635]], align 8
// CHK-C-NEXT:    [[BF_SHL637:%.*]] = shl i64 [[BF_LOAD636]], 40
// CHK-C-NEXT:    [[BF_ASHR638:%.*]] = ashr i64 [[BF_SHL637]], 57
// CHK-C-NEXT:    store i64 [[BF_ASHR638]], i64* [[ATMP619]], align 8
// CHK-C-NEXT:    [[CMP639:%.*]] = icmp slt i64 [[BF_ASHR638]], [[CONV617]]
// CHK-C-NEXT:    [[FROMBOOL640:%.*]] = zext i1 [[CMP639]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL640]], i8* [[ATMP625]], align 1
// CHK-C-NEXT:    br i1 [[CMP639]], label [[ATOMIC_CONT627]], label [[ATOMIC_EXIT641]]
// CHK-C:       atomic_exit641:
// CHK-C-NEXT:    [[TMP256:%.*]] = load i64, i64* [[ATMP619]], align 8
// CHK-C-NEXT:    [[TMP257:%.*]] = load i8, i8* [[ATMP625]], align 1
// CHK-C-NEXT:    [[CONV642:%.*]] = trunc i64 [[TMP256]] to i32
// CHK-C-NEXT:    store i32 [[CONV642]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP258:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[CONV643:%.*]] = sext i32 [[TMP258]] to i64
// CHK-C-NEXT:    [[ATOMIC_LOAD644:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD644]], i64* [[ATOMIC_TEMP646]], align 8
// CHK-C-NEXT:    [[BF_LOAD647:%.*]] = load i64, i64* [[ATOMIC_TEMP646]], align 8
// CHK-C-NEXT:    [[BF_SHL648:%.*]] = shl i64 [[BF_LOAD647]], 40
// CHK-C-NEXT:    [[BF_ASHR649:%.*]] = ashr i64 [[BF_SHL648]], 57
// CHK-C-NEXT:    store i64 [[BF_ASHR649]], i64* [[ATMP645]], align 8
// CHK-C-NEXT:    [[CMP650:%.*]] = icmp slt i64 [[BF_ASHR649]], [[CONV643]]
// CHK-C-NEXT:    [[FROMBOOL652:%.*]] = zext i1 [[CMP650]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL652]], i8* [[ATMP651]], align 1
// CHK-C-NEXT:    br i1 [[CMP650]], label [[ATOMIC_CONT653:%.*]], label [[ATOMIC_EXIT668:%.*]]
// CHK-C:       atomic_cont653:
// CHK-C-NEXT:    [[TMP259:%.*]] = phi i64 [ [[ATOMIC_LOAD644]], [[ATOMIC_EXIT641]] ], [ [[TMP262:%.*]], [[ATOMIC_CMP661:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP259]], i64* [[ATOMIC_TEMP654]], align 8
// CHK-C-NEXT:    [[BF_LOAD655:%.*]] = load i64, i64* [[ATOMIC_TEMP654]], align 8
// CHK-C-NEXT:    [[BF_VALUE656:%.*]] = and i64 [[CONV643]], 127
// CHK-C-NEXT:    [[BF_SHL657:%.*]] = shl i64 [[BF_VALUE656]], 17
// CHK-C-NEXT:    [[BF_CLEAR658:%.*]] = and i64 [[BF_LOAD655]], -16646145
// CHK-C-NEXT:    [[BF_SET659:%.*]] = or i64 [[BF_CLEAR658]], [[BF_SHL657]]
// CHK-C-NEXT:    store i64 [[BF_SET659]], i64* [[ATOMIC_TEMP654]], align 8
// CHK-C-NEXT:    [[TMP260:%.*]] = load i64, i64* [[ATOMIC_TEMP654]], align 8
// CHK-C-NEXT:    [[TMP261:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP259]], i64 [[TMP260]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP262]] = extractvalue { i64, i1 } [[TMP261]], 0
// CHK-C-NEXT:    [[TMP263:%.*]] = extractvalue { i64, i1 } [[TMP261]], 1
// CHK-C-NEXT:    br i1 [[TMP263]], label [[ATOMIC_UPD_EXIT660:%.*]], label [[ATOMIC_CMP661]]
// CHK-C:       atomic_upd_exit660:
// CHK-C-NEXT:    store i64 [[CONV643]], i64* [[ATMP645]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_EXIT668]]
// CHK-C:       atomic_cmp661:
// CHK-C-NEXT:    store i64 [[TMP262]], i64* [[ATOMIC_TEMP662]], align 8
// CHK-C-NEXT:    [[BF_LOAD663:%.*]] = load i64, i64* [[ATOMIC_TEMP662]], align 8
// CHK-C-NEXT:    [[BF_SHL664:%.*]] = shl i64 [[BF_LOAD663]], 40
// CHK-C-NEXT:    [[BF_ASHR665:%.*]] = ashr i64 [[BF_SHL664]], 57
// CHK-C-NEXT:    store i64 [[BF_ASHR665]], i64* [[ATMP645]], align 8
// CHK-C-NEXT:    [[CMP666:%.*]] = icmp slt i64 [[BF_ASHR665]], [[CONV643]]
// CHK-C-NEXT:    [[FROMBOOL667:%.*]] = zext i1 [[CMP666]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL667]], i8* [[ATMP651]], align 1
// CHK-C-NEXT:    br i1 [[CMP666]], label [[ATOMIC_CONT653]], label [[ATOMIC_EXIT668]]
// CHK-C:       atomic_exit668:
// CHK-C-NEXT:    [[TMP264:%.*]] = load i64, i64* [[ATMP645]], align 8
// CHK-C-NEXT:    [[TMP265:%.*]] = load i8, i8* [[ATMP651]], align 1
// CHK-C-NEXT:    [[CONV669:%.*]] = trunc i64 [[TMP264]] to i32
// CHK-C-NEXT:    store i32 [[CONV669]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP266:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[CONV670:%.*]] = sext i32 [[TMP266]] to i64
// CHK-C-NEXT:    [[TMP267:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[CONV671:%.*]] = sext i32 [[TMP267]] to i64
// CHK-C-NEXT:    [[ATOMIC_LOAD672:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD672]], i64* [[ATOMIC_TEMP674]], align 8
// CHK-C-NEXT:    [[BF_LOAD675:%.*]] = load i64, i64* [[ATOMIC_TEMP674]], align 8
// CHK-C-NEXT:    [[BF_SHL676:%.*]] = shl i64 [[BF_LOAD675]], 40
// CHK-C-NEXT:    [[BF_ASHR677:%.*]] = ashr i64 [[BF_SHL676]], 57
// CHK-C-NEXT:    store i64 [[BF_ASHR677]], i64* [[ATMP673]], align 8
// CHK-C-NEXT:    [[CMP678:%.*]] = icmp eq i64 [[BF_ASHR677]], [[CONV671]]
// CHK-C-NEXT:    [[FROMBOOL680:%.*]] = zext i1 [[CMP678]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL680]], i8* [[ATMP679]], align 1
// CHK-C-NEXT:    br i1 [[CMP678]], label [[ATOMIC_CONT681:%.*]], label [[ATOMIC_EXIT696:%.*]]
// CHK-C:       atomic_cont681:
// CHK-C-NEXT:    [[TMP268:%.*]] = phi i64 [ [[ATOMIC_LOAD672]], [[ATOMIC_EXIT668]] ], [ [[TMP271:%.*]], [[ATOMIC_CMP689:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP268]], i64* [[ATOMIC_TEMP682]], align 8
// CHK-C-NEXT:    [[BF_LOAD683:%.*]] = load i64, i64* [[ATOMIC_TEMP682]], align 8
// CHK-C-NEXT:    [[BF_VALUE684:%.*]] = and i64 [[CONV670]], 127
// CHK-C-NEXT:    [[BF_SHL685:%.*]] = shl i64 [[BF_VALUE684]], 17
// CHK-C-NEXT:    [[BF_CLEAR686:%.*]] = and i64 [[BF_LOAD683]], -16646145
// CHK-C-NEXT:    [[BF_SET687:%.*]] = or i64 [[BF_CLEAR686]], [[BF_SHL685]]
// CHK-C-NEXT:    store i64 [[BF_SET687]], i64* [[ATOMIC_TEMP682]], align 8
// CHK-C-NEXT:    [[TMP269:%.*]] = load i64, i64* [[ATOMIC_TEMP682]], align 8
// CHK-C-NEXT:    [[TMP270:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP268]], i64 [[TMP269]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP271]] = extractvalue { i64, i1 } [[TMP270]], 0
// CHK-C-NEXT:    [[TMP272:%.*]] = extractvalue { i64, i1 } [[TMP270]], 1
// CHK-C-NEXT:    br i1 [[TMP272]], label [[ATOMIC_UPD_EXIT688:%.*]], label [[ATOMIC_CMP689]]
// CHK-C:       atomic_upd_exit688:
// CHK-C-NEXT:    store i64 [[CONV670]], i64* [[ATMP673]], align 8
// CHK-C-NEXT:    br label [[ATOMIC_EXIT696]]
// CHK-C:       atomic_cmp689:
// CHK-C-NEXT:    store i64 [[TMP271]], i64* [[ATOMIC_TEMP690]], align 8
// CHK-C-NEXT:    [[BF_LOAD691:%.*]] = load i64, i64* [[ATOMIC_TEMP690]], align 8
// CHK-C-NEXT:    [[BF_SHL692:%.*]] = shl i64 [[BF_LOAD691]], 40
// CHK-C-NEXT:    [[BF_ASHR693:%.*]] = ashr i64 [[BF_SHL692]], 57
// CHK-C-NEXT:    store i64 [[BF_ASHR693]], i64* [[ATMP673]], align 8
// CHK-C-NEXT:    [[CMP694:%.*]] = icmp eq i64 [[BF_ASHR693]], [[CONV671]]
// CHK-C-NEXT:    [[FROMBOOL695:%.*]] = zext i1 [[CMP694]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL695]], i8* [[ATMP679]], align 1
// CHK-C-NEXT:    br i1 [[CMP694]], label [[ATOMIC_CONT681]], label [[ATOMIC_EXIT696]]
// CHK-C:       atomic_exit696:
// CHK-C-NEXT:    [[TMP273:%.*]] = load i64, i64* [[ATMP673]], align 8
// CHK-C-NEXT:    [[TMP274:%.*]] = load i8, i8* [[ATMP679]], align 1
// CHK-C-NEXT:    [[TMP275:%.*]] = trunc i8 [[TMP274]] to i1
// CHK-C-NEXT:    br i1 [[TMP275]], label [[ATOMIC_CAPTURE_CONT699:%.*]], label [[ATOMIC_CAPTURE697:%.*]]
// CHK-C:       atomic_capture697:
// CHK-C-NEXT:    [[CONV698:%.*]] = trunc i64 [[TMP273]] to i32
// CHK-C-NEXT:    store i32 [[CONV698]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT699]]
// CHK-C:       atomic_capture_cont699:
// CHK-C-NEXT:    [[TMP276:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[CONV700:%.*]] = sext i32 [[TMP276]] to i64
// CHK-C-NEXT:    [[TMP277:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[CONV701:%.*]] = sext i32 [[TMP277]] to i64
// CHK-C-NEXT:    [[ATOMIC_LOAD702:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD702]], i64* [[ATOMIC_TEMP704]], align 8
// CHK-C-NEXT:    [[BF_LOAD705:%.*]] = load i64, i64* [[ATOMIC_TEMP704]], align 8
// CHK-C-NEXT:    [[BF_SHL706:%.*]] = shl i64 [[BF_LOAD705]], 40
// CHK-C-NEXT:    [[BF_ASHR707:%.*]] = ashr i64 [[BF_SHL706]], 57
// CHK-C-NEXT:    store i64 [[BF_ASHR707]], i64* [[ATMP703]], align 8
// CHK-C-NEXT:    [[CMP708:%.*]] = icmp eq i64 [[BF_ASHR707]], [[CONV701]]
// CHK-C-NEXT:    [[FROMBOOL710:%.*]] = zext i1 [[CMP708]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL710]], i8* [[ATMP709]], align 1
// CHK-C-NEXT:    br i1 [[CMP708]], label [[ATOMIC_CONT711:%.*]], label [[ATOMIC_EXIT725:%.*]]
// CHK-C:       atomic_cont711:
// CHK-C-NEXT:    [[TMP278:%.*]] = phi i64 [ [[ATOMIC_LOAD702]], [[ATOMIC_CAPTURE_CONT699]] ], [ [[TMP281:%.*]], [[ATOMIC_CMP718:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP278]], i64* [[ATOMIC_TEMP712]], align 8
// CHK-C-NEXT:    [[BF_LOAD713:%.*]] = load i64, i64* [[ATOMIC_TEMP712]], align 8
// CHK-C-NEXT:    [[BF_VALUE714:%.*]] = and i64 [[CONV700]], 127
// CHK-C-NEXT:    [[BF_SHL715:%.*]] = shl i64 [[BF_VALUE714]], 17
// CHK-C-NEXT:    [[BF_CLEAR716:%.*]] = and i64 [[BF_LOAD713]], -16646145
// CHK-C-NEXT:    [[BF_SET717:%.*]] = or i64 [[BF_CLEAR716]], [[BF_SHL715]]
// CHK-C-NEXT:    store i64 [[BF_SET717]], i64* [[ATOMIC_TEMP712]], align 8
// CHK-C-NEXT:    [[TMP279:%.*]] = load i64, i64* [[ATOMIC_TEMP712]], align 8
// CHK-C-NEXT:    [[TMP280:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP278]], i64 [[TMP279]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP281]] = extractvalue { i64, i1 } [[TMP280]], 0
// CHK-C-NEXT:    [[TMP282:%.*]] = extractvalue { i64, i1 } [[TMP280]], 1
// CHK-C-NEXT:    br i1 [[TMP282]], label [[ATOMIC_EXIT725]], label [[ATOMIC_CMP718]]
// CHK-C:       atomic_cmp718:
// CHK-C-NEXT:    store i64 [[TMP281]], i64* [[ATOMIC_TEMP719]], align 8
// CHK-C-NEXT:    [[BF_LOAD720:%.*]] = load i64, i64* [[ATOMIC_TEMP719]], align 8
// CHK-C-NEXT:    [[BF_SHL721:%.*]] = shl i64 [[BF_LOAD720]], 40
// CHK-C-NEXT:    [[BF_ASHR722:%.*]] = ashr i64 [[BF_SHL721]], 57
// CHK-C-NEXT:    store i64 [[BF_ASHR722]], i64* [[ATMP703]], align 8
// CHK-C-NEXT:    [[CMP723:%.*]] = icmp eq i64 [[BF_ASHR722]], [[CONV701]]
// CHK-C-NEXT:    [[FROMBOOL724:%.*]] = zext i1 [[CMP723]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL724]], i8* [[ATMP709]], align 1
// CHK-C-NEXT:    br i1 [[CMP723]], label [[ATOMIC_CONT711]], label [[ATOMIC_EXIT725]]
// CHK-C:       atomic_exit725:
// CHK-C-NEXT:    [[TMP283:%.*]] = load i64, i64* [[ATMP703]], align 8
// CHK-C-NEXT:    [[TMP284:%.*]] = load i8, i8* [[ATMP709]], align 1
// CHK-C-NEXT:    [[CONV726:%.*]] = zext i8 [[TMP284]] to i32
// CHK-C-NEXT:    store i32 [[CONV726]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP285:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[CONV727:%.*]] = sext i32 [[TMP285]] to i64
// CHK-C-NEXT:    [[TMP286:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[CONV728:%.*]] = sext i32 [[TMP286]] to i64
// CHK-C-NEXT:    [[ATOMIC_LOAD729:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD729]], i64* [[ATOMIC_TEMP731]], align 8
// CHK-C-NEXT:    [[BF_LOAD732:%.*]] = load i64, i64* [[ATOMIC_TEMP731]], align 8
// CHK-C-NEXT:    [[BF_SHL733:%.*]] = shl i64 [[BF_LOAD732]], 40
// CHK-C-NEXT:    [[BF_ASHR734:%.*]] = ashr i64 [[BF_SHL733]], 57
// CHK-C-NEXT:    store i64 [[BF_ASHR734]], i64* [[ATMP730]], align 8
// CHK-C-NEXT:    [[CMP735:%.*]] = icmp eq i64 [[BF_ASHR734]], [[CONV728]]
// CHK-C-NEXT:    [[FROMBOOL737:%.*]] = zext i1 [[CMP735]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL737]], i8* [[ATMP736]], align 1
// CHK-C-NEXT:    br i1 [[CMP735]], label [[ATOMIC_CONT738:%.*]], label [[ATOMIC_EXIT752:%.*]]
// CHK-C:       atomic_cont738:
// CHK-C-NEXT:    [[TMP287:%.*]] = phi i64 [ [[ATOMIC_LOAD729]], [[ATOMIC_EXIT725]] ], [ [[TMP290:%.*]], [[ATOMIC_CMP745:%.*]] ]
// CHK-C-NEXT:    store i64 [[TMP287]], i64* [[ATOMIC_TEMP739]], align 8
// CHK-C-NEXT:    [[BF_LOAD740:%.*]] = load i64, i64* [[ATOMIC_TEMP739]], align 8
// CHK-C-NEXT:    [[BF_VALUE741:%.*]] = and i64 [[CONV727]], 127
// CHK-C-NEXT:    [[BF_SHL742:%.*]] = shl i64 [[BF_VALUE741]], 17
// CHK-C-NEXT:    [[BF_CLEAR743:%.*]] = and i64 [[BF_LOAD740]], -16646145
// CHK-C-NEXT:    [[BF_SET744:%.*]] = or i64 [[BF_CLEAR743]], [[BF_SHL742]]
// CHK-C-NEXT:    store i64 [[BF_SET744]], i64* [[ATOMIC_TEMP739]], align 8
// CHK-C-NEXT:    [[TMP288:%.*]] = load i64, i64* [[ATOMIC_TEMP739]], align 8
// CHK-C-NEXT:    [[TMP289:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP287]], i64 [[TMP288]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP290]] = extractvalue { i64, i1 } [[TMP289]], 0
// CHK-C-NEXT:    [[TMP291:%.*]] = extractvalue { i64, i1 } [[TMP289]], 1
// CHK-C-NEXT:    br i1 [[TMP291]], label [[ATOMIC_EXIT752]], label [[ATOMIC_CMP745]]
// CHK-C:       atomic_cmp745:
// CHK-C-NEXT:    store i64 [[TMP290]], i64* [[ATOMIC_TEMP746]], align 8
// CHK-C-NEXT:    [[BF_LOAD747:%.*]] = load i64, i64* [[ATOMIC_TEMP746]], align 8
// CHK-C-NEXT:    [[BF_SHL748:%.*]] = shl i64 [[BF_LOAD747]], 40
// CHK-C-NEXT:    [[BF_ASHR749:%.*]] = ashr i64 [[BF_SHL748]], 57
// CHK-C-NEXT:    store i64 [[BF_ASHR749]], i64* [[ATMP730]], align 8
// CHK-C-NEXT:    [[CMP750:%.*]] = icmp eq i64 [[BF_ASHR749]], [[CONV728]]
// CHK-C-NEXT:    [[FROMBOOL751:%.*]] = zext i1 [[CMP750]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL751]], i8* [[ATMP736]], align 1
// CHK-C-NEXT:    br i1 [[CMP750]], label [[ATOMIC_CONT738]], label [[ATOMIC_EXIT752]]
// CHK-C:       atomic_exit752:
// CHK-C-NEXT:    [[TMP292:%.*]] = load i64, i64* [[ATMP730]], align 8
// CHK-C-NEXT:    [[TMP293:%.*]] = load i8, i8* [[ATMP736]], align 1
// CHK-C-NEXT:    [[CONV753:%.*]] = zext i8 [[TMP293]] to i32
// CHK-C-NEXT:    store i32 [[CONV753]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP294:%.*]] = trunc i8 [[TMP293]] to i1
// CHK-C-NEXT:    br i1 [[TMP294]], label [[ATOMIC_CAPTURE_CONT756:%.*]], label [[ATOMIC_CAPTURE754:%.*]]
// CHK-C:       atomic_capture754:
// CHK-C-NEXT:    [[CONV755:%.*]] = trunc i64 [[TMP292]] to i32
// CHK-C-NEXT:    store i32 [[CONV755]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT756]]
// CHK-C:       atomic_capture_cont756:
// CHK-C-NEXT:    [[TMP295:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD757:%.*]] = load atomic i8, i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED:%.*]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2) monotonic, align 1
// CHK-C-NEXT:    [[TMP296:%.*]] = bitcast i32* [[ATOMIC_TEMP759]] to i8*
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD757]], i8* [[TMP296]], align 1
// CHK-C-NEXT:    [[BF_LOAD760:%.*]] = load i8, i8* [[TMP296]], align 1
// CHK-C-NEXT:    [[BF_SHL761:%.*]] = shl i8 [[BF_LOAD760]], 7
// CHK-C-NEXT:    [[BF_ASHR762:%.*]] = ashr i8 [[BF_SHL761]], 7
// CHK-C-NEXT:    [[BF_CAST763:%.*]] = sext i8 [[BF_ASHR762]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST763]], i32* [[ATMP758]], align 4
// CHK-C-NEXT:    [[CMP764:%.*]] = icmp slt i32 [[BF_CAST763]], [[TMP295]]
// CHK-C-NEXT:    [[FROMBOOL766:%.*]] = zext i1 [[CMP764]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL766]], i8* [[ATMP765]], align 1
// CHK-C-NEXT:    br i1 [[CMP764]], label [[ATOMIC_CONT767:%.*]], label [[ATOMIC_EXIT781:%.*]]
// CHK-C:       atomic_cont767:
// CHK-C-NEXT:    [[TMP297:%.*]] = phi i8 [ [[ATOMIC_LOAD757]], [[ATOMIC_CAPTURE_CONT756]] ], [ [[TMP302:%.*]], [[ATOMIC_CMP773:%.*]] ]
// CHK-C-NEXT:    [[TMP298:%.*]] = bitcast i32* [[ATOMIC_TEMP768]] to i8*
// CHK-C-NEXT:    store i8 [[TMP297]], i8* [[TMP298]], align 1
// CHK-C-NEXT:    [[TMP299:%.*]] = trunc i32 [[TMP295]] to i8
// CHK-C-NEXT:    [[BF_LOAD769:%.*]] = load i8, i8* [[TMP298]], align 1
// CHK-C-NEXT:    [[BF_VALUE770:%.*]] = and i8 [[TMP299]], 1
// CHK-C-NEXT:    [[BF_CLEAR771:%.*]] = and i8 [[BF_LOAD769]], -2
// CHK-C-NEXT:    [[BF_SET772:%.*]] = or i8 [[BF_CLEAR771]], [[BF_VALUE770]]
// CHK-C-NEXT:    store i8 [[BF_SET772]], i8* [[TMP298]], align 1
// CHK-C-NEXT:    [[TMP300:%.*]] = load i8, i8* [[TMP298]], align 1
// CHK-C-NEXT:    [[TMP301:%.*]] = cmpxchg i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2), i8 [[TMP297]], i8 [[TMP300]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP302]] = extractvalue { i8, i1 } [[TMP301]], 0
// CHK-C-NEXT:    [[TMP303:%.*]] = extractvalue { i8, i1 } [[TMP301]], 1
// CHK-C-NEXT:    br i1 [[TMP303]], label [[ATOMIC_EXIT781]], label [[ATOMIC_CMP773]]
// CHK-C:       atomic_cmp773:
// CHK-C-NEXT:    [[TMP304:%.*]] = bitcast i32* [[ATOMIC_TEMP774]] to i8*
// CHK-C-NEXT:    store i8 [[TMP302]], i8* [[TMP304]], align 1
// CHK-C-NEXT:    [[BF_LOAD775:%.*]] = load i8, i8* [[TMP304]], align 1
// CHK-C-NEXT:    [[BF_SHL776:%.*]] = shl i8 [[BF_LOAD775]], 7
// CHK-C-NEXT:    [[BF_ASHR777:%.*]] = ashr i8 [[BF_SHL776]], 7
// CHK-C-NEXT:    [[BF_CAST778:%.*]] = sext i8 [[BF_ASHR777]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST778]], i32* [[ATMP758]], align 4
// CHK-C-NEXT:    [[CMP779:%.*]] = icmp slt i32 [[BF_CAST778]], [[TMP295]]
// CHK-C-NEXT:    [[FROMBOOL780:%.*]] = zext i1 [[CMP779]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL780]], i8* [[ATMP765]], align 1
// CHK-C-NEXT:    br i1 [[CMP779]], label [[ATOMIC_CONT767]], label [[ATOMIC_EXIT781]]
// CHK-C:       atomic_exit781:
// CHK-C-NEXT:    [[TMP305:%.*]] = load i32, i32* [[ATMP758]], align 4
// CHK-C-NEXT:    [[TMP306:%.*]] = load i8, i8* [[ATMP765]], align 1
// CHK-C-NEXT:    store i32 [[TMP305]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP307:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD782:%.*]] = load atomic i8, i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2) monotonic, align 1
// CHK-C-NEXT:    [[TMP308:%.*]] = bitcast i32* [[ATOMIC_TEMP784]] to i8*
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD782]], i8* [[TMP308]], align 1
// CHK-C-NEXT:    [[BF_LOAD785:%.*]] = load i8, i8* [[TMP308]], align 1
// CHK-C-NEXT:    [[BF_SHL786:%.*]] = shl i8 [[BF_LOAD785]], 7
// CHK-C-NEXT:    [[BF_ASHR787:%.*]] = ashr i8 [[BF_SHL786]], 7
// CHK-C-NEXT:    [[BF_CAST788:%.*]] = sext i8 [[BF_ASHR787]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST788]], i32* [[ATMP783]], align 4
// CHK-C-NEXT:    [[CMP789:%.*]] = icmp slt i32 [[BF_CAST788]], [[TMP307]]
// CHK-C-NEXT:    [[FROMBOOL791:%.*]] = zext i1 [[CMP789]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL791]], i8* [[ATMP790]], align 1
// CHK-C-NEXT:    br i1 [[CMP789]], label [[ATOMIC_CONT792:%.*]], label [[ATOMIC_EXIT807:%.*]]
// CHK-C:       atomic_cont792:
// CHK-C-NEXT:    [[TMP309:%.*]] = phi i8 [ [[ATOMIC_LOAD782]], [[ATOMIC_EXIT781]] ], [ [[TMP314:%.*]], [[ATOMIC_CMP799:%.*]] ]
// CHK-C-NEXT:    [[TMP310:%.*]] = bitcast i32* [[ATOMIC_TEMP793]] to i8*
// CHK-C-NEXT:    store i8 [[TMP309]], i8* [[TMP310]], align 1
// CHK-C-NEXT:    [[TMP311:%.*]] = trunc i32 [[TMP307]] to i8
// CHK-C-NEXT:    [[BF_LOAD794:%.*]] = load i8, i8* [[TMP310]], align 1
// CHK-C-NEXT:    [[BF_VALUE795:%.*]] = and i8 [[TMP311]], 1
// CHK-C-NEXT:    [[BF_CLEAR796:%.*]] = and i8 [[BF_LOAD794]], -2
// CHK-C-NEXT:    [[BF_SET797:%.*]] = or i8 [[BF_CLEAR796]], [[BF_VALUE795]]
// CHK-C-NEXT:    store i8 [[BF_SET797]], i8* [[TMP310]], align 1
// CHK-C-NEXT:    [[TMP312:%.*]] = load i8, i8* [[TMP310]], align 1
// CHK-C-NEXT:    [[TMP313:%.*]] = cmpxchg i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2), i8 [[TMP309]], i8 [[TMP312]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP314]] = extractvalue { i8, i1 } [[TMP313]], 0
// CHK-C-NEXT:    [[TMP315:%.*]] = extractvalue { i8, i1 } [[TMP313]], 1
// CHK-C-NEXT:    br i1 [[TMP315]], label [[ATOMIC_UPD_EXIT798:%.*]], label [[ATOMIC_CMP799]]
// CHK-C:       atomic_upd_exit798:
// CHK-C-NEXT:    store i32 [[TMP307]], i32* [[ATMP783]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT807]]
// CHK-C:       atomic_cmp799:
// CHK-C-NEXT:    [[TMP316:%.*]] = bitcast i32* [[ATOMIC_TEMP800]] to i8*
// CHK-C-NEXT:    store i8 [[TMP314]], i8* [[TMP316]], align 1
// CHK-C-NEXT:    [[BF_LOAD801:%.*]] = load i8, i8* [[TMP316]], align 1
// CHK-C-NEXT:    [[BF_SHL802:%.*]] = shl i8 [[BF_LOAD801]], 7
// CHK-C-NEXT:    [[BF_ASHR803:%.*]] = ashr i8 [[BF_SHL802]], 7
// CHK-C-NEXT:    [[BF_CAST804:%.*]] = sext i8 [[BF_ASHR803]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST804]], i32* [[ATMP783]], align 4
// CHK-C-NEXT:    [[CMP805:%.*]] = icmp slt i32 [[BF_CAST804]], [[TMP307]]
// CHK-C-NEXT:    [[FROMBOOL806:%.*]] = zext i1 [[CMP805]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL806]], i8* [[ATMP790]], align 1
// CHK-C-NEXT:    br i1 [[CMP805]], label [[ATOMIC_CONT792]], label [[ATOMIC_EXIT807]]
// CHK-C:       atomic_exit807:
// CHK-C-NEXT:    [[TMP317:%.*]] = load i32, i32* [[ATMP783]], align 4
// CHK-C-NEXT:    [[TMP318:%.*]] = load i8, i8* [[ATMP790]], align 1
// CHK-C-NEXT:    store i32 [[TMP317]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP319:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP320:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD808:%.*]] = load atomic i8, i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2) monotonic, align 1
// CHK-C-NEXT:    [[TMP321:%.*]] = bitcast i32* [[ATOMIC_TEMP810]] to i8*
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD808]], i8* [[TMP321]], align 1
// CHK-C-NEXT:    [[BF_LOAD811:%.*]] = load i8, i8* [[TMP321]], align 1
// CHK-C-NEXT:    [[BF_SHL812:%.*]] = shl i8 [[BF_LOAD811]], 7
// CHK-C-NEXT:    [[BF_ASHR813:%.*]] = ashr i8 [[BF_SHL812]], 7
// CHK-C-NEXT:    [[BF_CAST814:%.*]] = sext i8 [[BF_ASHR813]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST814]], i32* [[ATMP809]], align 4
// CHK-C-NEXT:    [[CMP815:%.*]] = icmp eq i32 [[BF_CAST814]], [[TMP320]]
// CHK-C-NEXT:    [[FROMBOOL817:%.*]] = zext i1 [[CMP815]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL817]], i8* [[ATMP816]], align 1
// CHK-C-NEXT:    br i1 [[CMP815]], label [[ATOMIC_CONT818:%.*]], label [[ATOMIC_EXIT833:%.*]]
// CHK-C:       atomic_cont818:
// CHK-C-NEXT:    [[TMP322:%.*]] = phi i8 [ [[ATOMIC_LOAD808]], [[ATOMIC_EXIT807]] ], [ [[TMP327:%.*]], [[ATOMIC_CMP825:%.*]] ]
// CHK-C-NEXT:    [[TMP323:%.*]] = bitcast i32* [[ATOMIC_TEMP819]] to i8*
// CHK-C-NEXT:    store i8 [[TMP322]], i8* [[TMP323]], align 1
// CHK-C-NEXT:    [[TMP324:%.*]] = trunc i32 [[TMP319]] to i8
// CHK-C-NEXT:    [[BF_LOAD820:%.*]] = load i8, i8* [[TMP323]], align 1
// CHK-C-NEXT:    [[BF_VALUE821:%.*]] = and i8 [[TMP324]], 1
// CHK-C-NEXT:    [[BF_CLEAR822:%.*]] = and i8 [[BF_LOAD820]], -2
// CHK-C-NEXT:    [[BF_SET823:%.*]] = or i8 [[BF_CLEAR822]], [[BF_VALUE821]]
// CHK-C-NEXT:    store i8 [[BF_SET823]], i8* [[TMP323]], align 1
// CHK-C-NEXT:    [[TMP325:%.*]] = load i8, i8* [[TMP323]], align 1
// CHK-C-NEXT:    [[TMP326:%.*]] = cmpxchg i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2), i8 [[TMP322]], i8 [[TMP325]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP327]] = extractvalue { i8, i1 } [[TMP326]], 0
// CHK-C-NEXT:    [[TMP328:%.*]] = extractvalue { i8, i1 } [[TMP326]], 1
// CHK-C-NEXT:    br i1 [[TMP328]], label [[ATOMIC_UPD_EXIT824:%.*]], label [[ATOMIC_CMP825]]
// CHK-C:       atomic_upd_exit824:
// CHK-C-NEXT:    store i32 [[TMP319]], i32* [[ATMP809]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT833]]
// CHK-C:       atomic_cmp825:
// CHK-C-NEXT:    [[TMP329:%.*]] = bitcast i32* [[ATOMIC_TEMP826]] to i8*
// CHK-C-NEXT:    store i8 [[TMP327]], i8* [[TMP329]], align 1
// CHK-C-NEXT:    [[BF_LOAD827:%.*]] = load i8, i8* [[TMP329]], align 1
// CHK-C-NEXT:    [[BF_SHL828:%.*]] = shl i8 [[BF_LOAD827]], 7
// CHK-C-NEXT:    [[BF_ASHR829:%.*]] = ashr i8 [[BF_SHL828]], 7
// CHK-C-NEXT:    [[BF_CAST830:%.*]] = sext i8 [[BF_ASHR829]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST830]], i32* [[ATMP809]], align 4
// CHK-C-NEXT:    [[CMP831:%.*]] = icmp eq i32 [[BF_CAST830]], [[TMP320]]
// CHK-C-NEXT:    [[FROMBOOL832:%.*]] = zext i1 [[CMP831]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL832]], i8* [[ATMP816]], align 1
// CHK-C-NEXT:    br i1 [[CMP831]], label [[ATOMIC_CONT818]], label [[ATOMIC_EXIT833]]
// CHK-C:       atomic_exit833:
// CHK-C-NEXT:    [[TMP330:%.*]] = load i32, i32* [[ATMP809]], align 4
// CHK-C-NEXT:    [[TMP331:%.*]] = load i8, i8* [[ATMP816]], align 1
// CHK-C-NEXT:    [[TMP332:%.*]] = trunc i8 [[TMP331]] to i1
// CHK-C-NEXT:    br i1 [[TMP332]], label [[ATOMIC_CAPTURE_CONT835:%.*]], label [[ATOMIC_CAPTURE834:%.*]]
// CHK-C:       atomic_capture834:
// CHK-C-NEXT:    store i32 [[TMP330]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT835]]
// CHK-C:       atomic_capture_cont835:
// CHK-C-NEXT:    [[TMP333:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP334:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD836:%.*]] = load atomic i8, i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2) monotonic, align 1
// CHK-C-NEXT:    [[TMP335:%.*]] = bitcast i32* [[ATOMIC_TEMP838]] to i8*
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD836]], i8* [[TMP335]], align 1
// CHK-C-NEXT:    [[BF_LOAD839:%.*]] = load i8, i8* [[TMP335]], align 1
// CHK-C-NEXT:    [[BF_SHL840:%.*]] = shl i8 [[BF_LOAD839]], 7
// CHK-C-NEXT:    [[BF_ASHR841:%.*]] = ashr i8 [[BF_SHL840]], 7
// CHK-C-NEXT:    [[BF_CAST842:%.*]] = sext i8 [[BF_ASHR841]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST842]], i32* [[ATMP837]], align 4
// CHK-C-NEXT:    [[CMP843:%.*]] = icmp eq i32 [[BF_CAST842]], [[TMP334]]
// CHK-C-NEXT:    [[FROMBOOL845:%.*]] = zext i1 [[CMP843]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL845]], i8* [[ATMP844]], align 1
// CHK-C-NEXT:    br i1 [[CMP843]], label [[ATOMIC_CONT846:%.*]], label [[ATOMIC_EXIT860:%.*]]
// CHK-C:       atomic_cont846:
// CHK-C-NEXT:    [[TMP336:%.*]] = phi i8 [ [[ATOMIC_LOAD836]], [[ATOMIC_CAPTURE_CONT835]] ], [ [[TMP341:%.*]], [[ATOMIC_CMP852:%.*]] ]
// CHK-C-NEXT:    [[TMP337:%.*]] = bitcast i32* [[ATOMIC_TEMP847]] to i8*
// CHK-C-NEXT:    store i8 [[TMP336]], i8* [[TMP337]], align 1
// CHK-C-NEXT:    [[TMP338:%.*]] = trunc i32 [[TMP333]] to i8
// CHK-C-NEXT:    [[BF_LOAD848:%.*]] = load i8, i8* [[TMP337]], align 1
// CHK-C-NEXT:    [[BF_VALUE849:%.*]] = and i8 [[TMP338]], 1
// CHK-C-NEXT:    [[BF_CLEAR850:%.*]] = and i8 [[BF_LOAD848]], -2
// CHK-C-NEXT:    [[BF_SET851:%.*]] = or i8 [[BF_CLEAR850]], [[BF_VALUE849]]
// CHK-C-NEXT:    store i8 [[BF_SET851]], i8* [[TMP337]], align 1
// CHK-C-NEXT:    [[TMP339:%.*]] = load i8, i8* [[TMP337]], align 1
// CHK-C-NEXT:    [[TMP340:%.*]] = cmpxchg i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2), i8 [[TMP336]], i8 [[TMP339]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP341]] = extractvalue { i8, i1 } [[TMP340]], 0
// CHK-C-NEXT:    [[TMP342:%.*]] = extractvalue { i8, i1 } [[TMP340]], 1
// CHK-C-NEXT:    br i1 [[TMP342]], label [[ATOMIC_EXIT860]], label [[ATOMIC_CMP852]]
// CHK-C:       atomic_cmp852:
// CHK-C-NEXT:    [[TMP343:%.*]] = bitcast i32* [[ATOMIC_TEMP853]] to i8*
// CHK-C-NEXT:    store i8 [[TMP341]], i8* [[TMP343]], align 1
// CHK-C-NEXT:    [[BF_LOAD854:%.*]] = load i8, i8* [[TMP343]], align 1
// CHK-C-NEXT:    [[BF_SHL855:%.*]] = shl i8 [[BF_LOAD854]], 7
// CHK-C-NEXT:    [[BF_ASHR856:%.*]] = ashr i8 [[BF_SHL855]], 7
// CHK-C-NEXT:    [[BF_CAST857:%.*]] = sext i8 [[BF_ASHR856]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST857]], i32* [[ATMP837]], align 4
// CHK-C-NEXT:    [[CMP858:%.*]] = icmp eq i32 [[BF_CAST857]], [[TMP334]]
// CHK-C-NEXT:    [[FROMBOOL859:%.*]] = zext i1 [[CMP858]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL859]], i8* [[ATMP844]], align 1
// CHK-C-NEXT:    br i1 [[CMP858]], label [[ATOMIC_CONT846]], label [[ATOMIC_EXIT860]]
// CHK-C:       atomic_exit860:
// CHK-C-NEXT:    [[TMP344:%.*]] = load i32, i32* [[ATMP837]], align 4
// CHK-C-NEXT:    [[TMP345:%.*]] = load i8, i8* [[ATMP844]], align 1
// CHK-C-NEXT:    [[CONV861:%.*]] = zext i8 [[TMP345]] to i32
// CHK-C-NEXT:    store i32 [[CONV861]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP346:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[TMP347:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[ATOMIC_LOAD862:%.*]] = load atomic i8, i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2) monotonic, align 1
// CHK-C-NEXT:    [[TMP348:%.*]] = bitcast i32* [[ATOMIC_TEMP864]] to i8*
// CHK-C-NEXT:    store i8 [[ATOMIC_LOAD862]], i8* [[TMP348]], align 1
// CHK-C-NEXT:    [[BF_LOAD865:%.*]] = load i8, i8* [[TMP348]], align 1
// CHK-C-NEXT:    [[BF_SHL866:%.*]] = shl i8 [[BF_LOAD865]], 7
// CHK-C-NEXT:    [[BF_ASHR867:%.*]] = ashr i8 [[BF_SHL866]], 7
// CHK-C-NEXT:    [[BF_CAST868:%.*]] = sext i8 [[BF_ASHR867]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST868]], i32* [[ATMP863]], align 4
// CHK-C-NEXT:    [[CMP869:%.*]] = icmp eq i32 [[BF_CAST868]], [[TMP347]]
// CHK-C-NEXT:    [[FROMBOOL871:%.*]] = zext i1 [[CMP869]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL871]], i8* [[ATMP870]], align 1
// CHK-C-NEXT:    br i1 [[CMP869]], label [[ATOMIC_CONT872:%.*]], label [[ATOMIC_EXIT886:%.*]]
// CHK-C:       atomic_cont872:
// CHK-C-NEXT:    [[TMP349:%.*]] = phi i8 [ [[ATOMIC_LOAD862]], [[ATOMIC_EXIT860]] ], [ [[TMP354:%.*]], [[ATOMIC_CMP878:%.*]] ]
// CHK-C-NEXT:    [[TMP350:%.*]] = bitcast i32* [[ATOMIC_TEMP873]] to i8*
// CHK-C-NEXT:    store i8 [[TMP349]], i8* [[TMP350]], align 1
// CHK-C-NEXT:    [[TMP351:%.*]] = trunc i32 [[TMP346]] to i8
// CHK-C-NEXT:    [[BF_LOAD874:%.*]] = load i8, i8* [[TMP350]], align 1
// CHK-C-NEXT:    [[BF_VALUE875:%.*]] = and i8 [[TMP351]], 1
// CHK-C-NEXT:    [[BF_CLEAR876:%.*]] = and i8 [[BF_LOAD874]], -2
// CHK-C-NEXT:    [[BF_SET877:%.*]] = or i8 [[BF_CLEAR876]], [[BF_VALUE875]]
// CHK-C-NEXT:    store i8 [[BF_SET877]], i8* [[TMP350]], align 1
// CHK-C-NEXT:    [[TMP352:%.*]] = load i8, i8* [[TMP350]], align 1
// CHK-C-NEXT:    [[TMP353:%.*]] = cmpxchg i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2), i8 [[TMP349]], i8 [[TMP352]] monotonic monotonic, align 1
// CHK-C-NEXT:    [[TMP354]] = extractvalue { i8, i1 } [[TMP353]], 0
// CHK-C-NEXT:    [[TMP355:%.*]] = extractvalue { i8, i1 } [[TMP353]], 1
// CHK-C-NEXT:    br i1 [[TMP355]], label [[ATOMIC_EXIT886]], label [[ATOMIC_CMP878]]
// CHK-C:       atomic_cmp878:
// CHK-C-NEXT:    [[TMP356:%.*]] = bitcast i32* [[ATOMIC_TEMP879]] to i8*
// CHK-C-NEXT:    store i8 [[TMP354]], i8* [[TMP356]], align 1
// CHK-C-NEXT:    [[BF_LOAD880:%.*]] = load i8, i8* [[TMP356]], align 1
// CHK-C-NEXT:    [[BF_SHL881:%.*]] = shl i8 [[BF_LOAD880]], 7
// CHK-C-NEXT:    [[BF_ASHR882:%.*]] = ashr i8 [[BF_SHL881]], 7
// CHK-C-NEXT:    [[BF_CAST883:%.*]] = sext i8 [[BF_ASHR882]] to i32
// CHK-C-NEXT:    store i32 [[BF_CAST883]], i32* [[ATMP863]], align 4
// CHK-C-NEXT:    [[CMP884:%.*]] = icmp eq i32 [[BF_CAST883]], [[TMP347]]
// CHK-C-NEXT:    [[FROMBOOL885:%.*]] = zext i1 [[CMP884]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL885]], i8* [[ATMP870]], align 1
// CHK-C-NEXT:    br i1 [[CMP884]], label [[ATOMIC_CONT872]], label [[ATOMIC_EXIT886]]
// CHK-C:       atomic_exit886:
// CHK-C-NEXT:    [[TMP357:%.*]] = load i32, i32* [[ATMP863]], align 4
// CHK-C-NEXT:    [[TMP358:%.*]] = load i8, i8* [[ATMP870]], align 1
// CHK-C-NEXT:    [[CONV887:%.*]] = zext i8 [[TMP358]] to i32
// CHK-C-NEXT:    store i32 [[CONV887]], i32* [[R]], align 4
// CHK-C-NEXT:    [[TMP359:%.*]] = trunc i8 [[TMP358]] to i1
// CHK-C-NEXT:    br i1 [[TMP359]], label [[ATOMIC_CAPTURE_CONT889:%.*]], label [[ATOMIC_CAPTURE888:%.*]]
// CHK-C:       atomic_capture888:
// CHK-C-NEXT:    store i32 [[TMP357]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT889]]
// CHK-C:       atomic_capture_cont889:
// CHK-C-NEXT:    ret void
//
// CHK-CXX-LABEL: @_Z13test_bitfieldv(
// CHK-CXX-NEXT:  entry:
// CHK-CXX-NEXT:    [[EXPR:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[D:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[E:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[V:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[R:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[TMP:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP2:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP4:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP11:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP12:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP17:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP20:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP26:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP34:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP35:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP40:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP43:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP50:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP58:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP59:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP64:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP67:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP73:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP81:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP82:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP87:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP90:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP96:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP107:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP108:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP112:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP115:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP122:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP129:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP130:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP134:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP137:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP145:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP152:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP153:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP157:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP160:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP168:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP177:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP178:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP182:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP185:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP192:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP200:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP201:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP205:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP208:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP215:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP225:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP226:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP230:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP233:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP240:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP248:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP249:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP254:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP257:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP265:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP273:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP274:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP279:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP282:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP290:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP300:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP301:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP306:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP309:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP316:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP325:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP326:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP331:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP334:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP341:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP352:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP353:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP358:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP361:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP368:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP376:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP377:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP382:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP385:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP393:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP401:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP402:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP407:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP410:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP418:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP428:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP429:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP434:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP437:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP444:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP453:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP454:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP459:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP462:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP469:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATMP480:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP481:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP487:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP490:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP497:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP506:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP507:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP513:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP516:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP524:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP533:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP534:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP540:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP543:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP551:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP562:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP563:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP569:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP572:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP579:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP589:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP590:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP596:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP599:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP606:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP619:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP620:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP625:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP628:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP635:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP645:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP646:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP651:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP654:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP662:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP673:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP674:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP679:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP682:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP690:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP703:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP704:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP709:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP712:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP719:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP730:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP731:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP736:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP739:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP746:%.*]] = alloca i64, align 8
// CHK-CXX-NEXT:    [[ATMP758:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP759:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP765:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP768:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP774:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP783:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP784:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP790:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP793:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP800:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP809:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP810:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP816:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP819:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP826:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP837:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP838:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP844:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP847:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP853:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP863:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP864:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATMP870:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP873:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP879:%.*]] = alloca i32, align 1
// CHK-CXX-NEXT:    [[TMP0:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i32, i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD]], i32* [[ATOMIC_TEMP]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD:%.*]] = load i32, i32* [[ATOMIC_TEMP]], align 4
// CHK-CXX-NEXT:    [[BF_SHL:%.*]] = shl i32 [[BF_LOAD]], 1
// CHK-CXX-NEXT:    [[BF_ASHR:%.*]] = ashr i32 [[BF_SHL]], 1
// CHK-CXX-NEXT:    store i32 [[BF_ASHR]], i32* [[TMP]], align 4
// CHK-CXX-NEXT:    [[CMP:%.*]] = icmp slt i32 [[BF_ASHR]], [[TMP0]]
// CHK-CXX-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-CXX:       atomic_cont:
// CHK-CXX-NEXT:    [[TMP1:%.*]] = phi i32 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP4:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP1]], i32* [[ATOMIC_TEMP2]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD3:%.*]] = load i32, i32* [[ATOMIC_TEMP2]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE:%.*]] = and i32 [[TMP0]], 2147483647
// CHK-CXX-NEXT:    [[BF_CLEAR:%.*]] = and i32 [[BF_LOAD3]], -2147483648
// CHK-CXX-NEXT:    [[BF_SET:%.*]] = or i32 [[BF_CLEAR]], [[BF_VALUE]]
// CHK-CXX-NEXT:    store i32 [[BF_SET]], i32* [[ATOMIC_TEMP2]], align 4
// CHK-CXX-NEXT:    [[TMP2:%.*]] = load i32, i32* [[ATOMIC_TEMP2]], align 4
// CHK-CXX-NEXT:    [[TMP3:%.*]] = cmpxchg i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*), i32 [[TMP1]], i32 [[TMP2]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP4]] = extractvalue { i32, i1 } [[TMP3]], 0
// CHK-CXX-NEXT:    [[TMP5:%.*]] = extractvalue { i32, i1 } [[TMP3]], 1
// CHK-CXX-NEXT:    br i1 [[TMP5]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-CXX:       atomic_cmp:
// CHK-CXX-NEXT:    store i32 [[TMP4]], i32* [[ATOMIC_TEMP4]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD5:%.*]] = load i32, i32* [[ATOMIC_TEMP4]], align 4
// CHK-CXX-NEXT:    [[BF_SHL6:%.*]] = shl i32 [[BF_LOAD5]], 1
// CHK-CXX-NEXT:    [[BF_ASHR7:%.*]] = ashr i32 [[BF_SHL6]], 1
// CHK-CXX-NEXT:    store i32 [[BF_ASHR7]], i32* [[TMP]], align 4
// CHK-CXX-NEXT:    [[CMP8:%.*]] = icmp slt i32 [[BF_ASHR7]], [[TMP0]]
// CHK-CXX-NEXT:    [[FROMBOOL9:%.*]] = zext i1 [[CMP8]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL9]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP8]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-CXX:       atomic_exit:
// CHK-CXX-NEXT:    [[TMP6:%.*]] = load i32, i32* [[TMP]], align 4
// CHK-CXX-NEXT:    [[TMP7:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP6]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP8:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD10:%.*]] = load atomic i32, i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD10]], i32* [[ATOMIC_TEMP12]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD13:%.*]] = load i32, i32* [[ATOMIC_TEMP12]], align 4
// CHK-CXX-NEXT:    [[BF_SHL14:%.*]] = shl i32 [[BF_LOAD13]], 1
// CHK-CXX-NEXT:    [[BF_ASHR15:%.*]] = ashr i32 [[BF_SHL14]], 1
// CHK-CXX-NEXT:    store i32 [[BF_ASHR15]], i32* [[ATMP11]], align 4
// CHK-CXX-NEXT:    [[CMP16:%.*]] = icmp slt i32 [[BF_ASHR15]], [[TMP8]]
// CHK-CXX-NEXT:    [[FROMBOOL18:%.*]] = zext i1 [[CMP16]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL18]], i8* [[ATMP17]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP16]], label [[ATOMIC_CONT19:%.*]], label [[ATOMIC_EXIT32:%.*]]
// CHK-CXX:       atomic_cont19:
// CHK-CXX-NEXT:    [[TMP9:%.*]] = phi i32 [ [[ATOMIC_LOAD10]], [[ATOMIC_EXIT]] ], [ [[TMP12:%.*]], [[ATOMIC_CMP25:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP9]], i32* [[ATOMIC_TEMP20]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD21:%.*]] = load i32, i32* [[ATOMIC_TEMP20]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE22:%.*]] = and i32 [[TMP8]], 2147483647
// CHK-CXX-NEXT:    [[BF_CLEAR23:%.*]] = and i32 [[BF_LOAD21]], -2147483648
// CHK-CXX-NEXT:    [[BF_SET24:%.*]] = or i32 [[BF_CLEAR23]], [[BF_VALUE22]]
// CHK-CXX-NEXT:    store i32 [[BF_SET24]], i32* [[ATOMIC_TEMP20]], align 4
// CHK-CXX-NEXT:    [[TMP10:%.*]] = load i32, i32* [[ATOMIC_TEMP20]], align 4
// CHK-CXX-NEXT:    [[TMP11:%.*]] = cmpxchg i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*), i32 [[TMP9]], i32 [[TMP10]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP12]] = extractvalue { i32, i1 } [[TMP11]], 0
// CHK-CXX-NEXT:    [[TMP13:%.*]] = extractvalue { i32, i1 } [[TMP11]], 1
// CHK-CXX-NEXT:    br i1 [[TMP13]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP25]]
// CHK-CXX:       atomic_upd_exit:
// CHK-CXX-NEXT:    store i32 [[TMP8]], i32* [[ATMP11]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT32]]
// CHK-CXX:       atomic_cmp25:
// CHK-CXX-NEXT:    store i32 [[TMP12]], i32* [[ATOMIC_TEMP26]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD27:%.*]] = load i32, i32* [[ATOMIC_TEMP26]], align 4
// CHK-CXX-NEXT:    [[BF_SHL28:%.*]] = shl i32 [[BF_LOAD27]], 1
// CHK-CXX-NEXT:    [[BF_ASHR29:%.*]] = ashr i32 [[BF_SHL28]], 1
// CHK-CXX-NEXT:    store i32 [[BF_ASHR29]], i32* [[ATMP11]], align 4
// CHK-CXX-NEXT:    [[CMP30:%.*]] = icmp slt i32 [[BF_ASHR29]], [[TMP8]]
// CHK-CXX-NEXT:    [[FROMBOOL31:%.*]] = zext i1 [[CMP30]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL31]], i8* [[ATMP17]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP30]], label [[ATOMIC_CONT19]], label [[ATOMIC_EXIT32]]
// CHK-CXX:       atomic_exit32:
// CHK-CXX-NEXT:    [[TMP14:%.*]] = load i32, i32* [[ATMP11]], align 4
// CHK-CXX-NEXT:    [[TMP15:%.*]] = load i8, i8* [[ATMP17]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP14]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP16:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP17:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD33:%.*]] = load atomic i32, i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD33]], i32* [[ATOMIC_TEMP35]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD36:%.*]] = load i32, i32* [[ATOMIC_TEMP35]], align 4
// CHK-CXX-NEXT:    [[BF_SHL37:%.*]] = shl i32 [[BF_LOAD36]], 1
// CHK-CXX-NEXT:    [[BF_ASHR38:%.*]] = ashr i32 [[BF_SHL37]], 1
// CHK-CXX-NEXT:    store i32 [[BF_ASHR38]], i32* [[ATMP34]], align 4
// CHK-CXX-NEXT:    [[CMP39:%.*]] = icmp eq i32 [[BF_ASHR38]], [[TMP17]]
// CHK-CXX-NEXT:    [[FROMBOOL41:%.*]] = zext i1 [[CMP39]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL41]], i8* [[ATMP40]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP39]], label [[ATOMIC_CONT42:%.*]], label [[ATOMIC_EXIT56:%.*]]
// CHK-CXX:       atomic_cont42:
// CHK-CXX-NEXT:    [[TMP18:%.*]] = phi i32 [ [[ATOMIC_LOAD33]], [[ATOMIC_EXIT32]] ], [ [[TMP21:%.*]], [[ATOMIC_CMP49:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP18]], i32* [[ATOMIC_TEMP43]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD44:%.*]] = load i32, i32* [[ATOMIC_TEMP43]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE45:%.*]] = and i32 [[TMP16]], 2147483647
// CHK-CXX-NEXT:    [[BF_CLEAR46:%.*]] = and i32 [[BF_LOAD44]], -2147483648
// CHK-CXX-NEXT:    [[BF_SET47:%.*]] = or i32 [[BF_CLEAR46]], [[BF_VALUE45]]
// CHK-CXX-NEXT:    store i32 [[BF_SET47]], i32* [[ATOMIC_TEMP43]], align 4
// CHK-CXX-NEXT:    [[TMP19:%.*]] = load i32, i32* [[ATOMIC_TEMP43]], align 4
// CHK-CXX-NEXT:    [[TMP20:%.*]] = cmpxchg i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*), i32 [[TMP18]], i32 [[TMP19]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP21]] = extractvalue { i32, i1 } [[TMP20]], 0
// CHK-CXX-NEXT:    [[TMP22:%.*]] = extractvalue { i32, i1 } [[TMP20]], 1
// CHK-CXX-NEXT:    br i1 [[TMP22]], label [[ATOMIC_UPD_EXIT48:%.*]], label [[ATOMIC_CMP49]]
// CHK-CXX:       atomic_upd_exit48:
// CHK-CXX-NEXT:    store i32 [[TMP16]], i32* [[ATMP34]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT56]]
// CHK-CXX:       atomic_cmp49:
// CHK-CXX-NEXT:    store i32 [[TMP21]], i32* [[ATOMIC_TEMP50]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD51:%.*]] = load i32, i32* [[ATOMIC_TEMP50]], align 4
// CHK-CXX-NEXT:    [[BF_SHL52:%.*]] = shl i32 [[BF_LOAD51]], 1
// CHK-CXX-NEXT:    [[BF_ASHR53:%.*]] = ashr i32 [[BF_SHL52]], 1
// CHK-CXX-NEXT:    store i32 [[BF_ASHR53]], i32* [[ATMP34]], align 4
// CHK-CXX-NEXT:    [[CMP54:%.*]] = icmp eq i32 [[BF_ASHR53]], [[TMP17]]
// CHK-CXX-NEXT:    [[FROMBOOL55:%.*]] = zext i1 [[CMP54]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL55]], i8* [[ATMP40]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP54]], label [[ATOMIC_CONT42]], label [[ATOMIC_EXIT56]]
// CHK-CXX:       atomic_exit56:
// CHK-CXX-NEXT:    [[TMP23:%.*]] = load i32, i32* [[ATMP34]], align 4
// CHK-CXX-NEXT:    [[TMP24:%.*]] = load i8, i8* [[ATMP40]], align 1
// CHK-CXX-NEXT:    [[TMP25:%.*]] = trunc i8 [[TMP24]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP25]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-CXX:       atomic_capture:
// CHK-CXX-NEXT:    store i32 [[TMP23]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-CXX:       atomic_capture_cont:
// CHK-CXX-NEXT:    [[TMP26:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP27:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD57:%.*]] = load atomic i32, i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD57]], i32* [[ATOMIC_TEMP59]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD60:%.*]] = load i32, i32* [[ATOMIC_TEMP59]], align 4
// CHK-CXX-NEXT:    [[BF_SHL61:%.*]] = shl i32 [[BF_LOAD60]], 1
// CHK-CXX-NEXT:    [[BF_ASHR62:%.*]] = ashr i32 [[BF_SHL61]], 1
// CHK-CXX-NEXT:    store i32 [[BF_ASHR62]], i32* [[ATMP58]], align 4
// CHK-CXX-NEXT:    [[CMP63:%.*]] = icmp eq i32 [[BF_ASHR62]], [[TMP27]]
// CHK-CXX-NEXT:    [[FROMBOOL65:%.*]] = zext i1 [[CMP63]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL65]], i8* [[ATMP64]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP63]], label [[ATOMIC_CONT66:%.*]], label [[ATOMIC_EXIT79:%.*]]
// CHK-CXX:       atomic_cont66:
// CHK-CXX-NEXT:    [[TMP28:%.*]] = phi i32 [ [[ATOMIC_LOAD57]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP31:%.*]], [[ATOMIC_CMP72:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP28]], i32* [[ATOMIC_TEMP67]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD68:%.*]] = load i32, i32* [[ATOMIC_TEMP67]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE69:%.*]] = and i32 [[TMP26]], 2147483647
// CHK-CXX-NEXT:    [[BF_CLEAR70:%.*]] = and i32 [[BF_LOAD68]], -2147483648
// CHK-CXX-NEXT:    [[BF_SET71:%.*]] = or i32 [[BF_CLEAR70]], [[BF_VALUE69]]
// CHK-CXX-NEXT:    store i32 [[BF_SET71]], i32* [[ATOMIC_TEMP67]], align 4
// CHK-CXX-NEXT:    [[TMP29:%.*]] = load i32, i32* [[ATOMIC_TEMP67]], align 4
// CHK-CXX-NEXT:    [[TMP30:%.*]] = cmpxchg i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*), i32 [[TMP28]], i32 [[TMP29]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP31]] = extractvalue { i32, i1 } [[TMP30]], 0
// CHK-CXX-NEXT:    [[TMP32:%.*]] = extractvalue { i32, i1 } [[TMP30]], 1
// CHK-CXX-NEXT:    br i1 [[TMP32]], label [[ATOMIC_EXIT79]], label [[ATOMIC_CMP72]]
// CHK-CXX:       atomic_cmp72:
// CHK-CXX-NEXT:    store i32 [[TMP31]], i32* [[ATOMIC_TEMP73]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD74:%.*]] = load i32, i32* [[ATOMIC_TEMP73]], align 4
// CHK-CXX-NEXT:    [[BF_SHL75:%.*]] = shl i32 [[BF_LOAD74]], 1
// CHK-CXX-NEXT:    [[BF_ASHR76:%.*]] = ashr i32 [[BF_SHL75]], 1
// CHK-CXX-NEXT:    store i32 [[BF_ASHR76]], i32* [[ATMP58]], align 4
// CHK-CXX-NEXT:    [[CMP77:%.*]] = icmp eq i32 [[BF_ASHR76]], [[TMP27]]
// CHK-CXX-NEXT:    [[FROMBOOL78:%.*]] = zext i1 [[CMP77]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL78]], i8* [[ATMP64]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP77]], label [[ATOMIC_CONT66]], label [[ATOMIC_EXIT79]]
// CHK-CXX:       atomic_exit79:
// CHK-CXX-NEXT:    [[TMP33:%.*]] = load i32, i32* [[ATMP58]], align 4
// CHK-CXX-NEXT:    [[TMP34:%.*]] = load i8, i8* [[ATMP64]], align 1
// CHK-CXX-NEXT:    [[CONV:%.*]] = zext i8 [[TMP34]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP35:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP36:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD80:%.*]] = load atomic i32, i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD80]], i32* [[ATOMIC_TEMP82]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD83:%.*]] = load i32, i32* [[ATOMIC_TEMP82]], align 4
// CHK-CXX-NEXT:    [[BF_SHL84:%.*]] = shl i32 [[BF_LOAD83]], 1
// CHK-CXX-NEXT:    [[BF_ASHR85:%.*]] = ashr i32 [[BF_SHL84]], 1
// CHK-CXX-NEXT:    store i32 [[BF_ASHR85]], i32* [[ATMP81]], align 4
// CHK-CXX-NEXT:    [[CMP86:%.*]] = icmp eq i32 [[BF_ASHR85]], [[TMP36]]
// CHK-CXX-NEXT:    [[FROMBOOL88:%.*]] = zext i1 [[CMP86]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL88]], i8* [[ATMP87]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP86]], label [[ATOMIC_CONT89:%.*]], label [[ATOMIC_EXIT102:%.*]]
// CHK-CXX:       atomic_cont89:
// CHK-CXX-NEXT:    [[TMP37:%.*]] = phi i32 [ [[ATOMIC_LOAD80]], [[ATOMIC_EXIT79]] ], [ [[TMP40:%.*]], [[ATOMIC_CMP95:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP37]], i32* [[ATOMIC_TEMP90]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD91:%.*]] = load i32, i32* [[ATOMIC_TEMP90]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE92:%.*]] = and i32 [[TMP35]], 2147483647
// CHK-CXX-NEXT:    [[BF_CLEAR93:%.*]] = and i32 [[BF_LOAD91]], -2147483648
// CHK-CXX-NEXT:    [[BF_SET94:%.*]] = or i32 [[BF_CLEAR93]], [[BF_VALUE92]]
// CHK-CXX-NEXT:    store i32 [[BF_SET94]], i32* [[ATOMIC_TEMP90]], align 4
// CHK-CXX-NEXT:    [[TMP38:%.*]] = load i32, i32* [[ATOMIC_TEMP90]], align 4
// CHK-CXX-NEXT:    [[TMP39:%.*]] = cmpxchg i32* bitcast (i8* getelementptr (i8, i8* bitcast (%struct.BitFields* @bfx to i8*), i64 4) to i32*), i32 [[TMP37]], i32 [[TMP38]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP40]] = extractvalue { i32, i1 } [[TMP39]], 0
// CHK-CXX-NEXT:    [[TMP41:%.*]] = extractvalue { i32, i1 } [[TMP39]], 1
// CHK-CXX-NEXT:    br i1 [[TMP41]], label [[ATOMIC_EXIT102]], label [[ATOMIC_CMP95]]
// CHK-CXX:       atomic_cmp95:
// CHK-CXX-NEXT:    store i32 [[TMP40]], i32* [[ATOMIC_TEMP96]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD97:%.*]] = load i32, i32* [[ATOMIC_TEMP96]], align 4
// CHK-CXX-NEXT:    [[BF_SHL98:%.*]] = shl i32 [[BF_LOAD97]], 1
// CHK-CXX-NEXT:    [[BF_ASHR99:%.*]] = ashr i32 [[BF_SHL98]], 1
// CHK-CXX-NEXT:    store i32 [[BF_ASHR99]], i32* [[ATMP81]], align 4
// CHK-CXX-NEXT:    [[CMP100:%.*]] = icmp eq i32 [[BF_ASHR99]], [[TMP36]]
// CHK-CXX-NEXT:    [[FROMBOOL101:%.*]] = zext i1 [[CMP100]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL101]], i8* [[ATMP87]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP100]], label [[ATOMIC_CONT89]], label [[ATOMIC_EXIT102]]
// CHK-CXX:       atomic_exit102:
// CHK-CXX-NEXT:    [[TMP42:%.*]] = load i32, i32* [[ATMP81]], align 4
// CHK-CXX-NEXT:    [[TMP43:%.*]] = load i8, i8* [[ATMP87]], align 1
// CHK-CXX-NEXT:    [[CONV103:%.*]] = zext i8 [[TMP43]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV103]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP44:%.*]] = trunc i8 [[TMP43]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP44]], label [[ATOMIC_CAPTURE_CONT105:%.*]], label [[ATOMIC_CAPTURE104:%.*]]
// CHK-CXX:       atomic_capture104:
// CHK-CXX-NEXT:    store i32 [[TMP42]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT105]]
// CHK-CXX:       atomic_capture_cont105:
// CHK-CXX-NEXT:    [[TMP45:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD106:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS2:%.*]], %struct.BitFields2* @bfx2, i32 0, i32 0) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD106]], i32* [[ATOMIC_TEMP108]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD109:%.*]] = load i32, i32* [[ATOMIC_TEMP108]], align 4
// CHK-CXX-NEXT:    [[BF_ASHR110:%.*]] = ashr i32 [[BF_LOAD109]], 31
// CHK-CXX-NEXT:    store i32 [[BF_ASHR110]], i32* [[ATMP107]], align 4
// CHK-CXX-NEXT:    [[CMP111:%.*]] = icmp slt i32 [[BF_ASHR110]], [[TMP45]]
// CHK-CXX-NEXT:    [[FROMBOOL113:%.*]] = zext i1 [[CMP111]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL113]], i8* [[ATMP112]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP111]], label [[ATOMIC_CONT114:%.*]], label [[ATOMIC_EXIT127:%.*]]
// CHK-CXX:       atomic_cont114:
// CHK-CXX-NEXT:    [[TMP46:%.*]] = phi i32 [ [[ATOMIC_LOAD106]], [[ATOMIC_CAPTURE_CONT105]] ], [ [[TMP49:%.*]], [[ATOMIC_CMP121:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP46]], i32* [[ATOMIC_TEMP115]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD116:%.*]] = load i32, i32* [[ATOMIC_TEMP115]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE117:%.*]] = and i32 [[TMP45]], 1
// CHK-CXX-NEXT:    [[BF_SHL118:%.*]] = shl i32 [[BF_VALUE117]], 31
// CHK-CXX-NEXT:    [[BF_CLEAR119:%.*]] = and i32 [[BF_LOAD116]], 2147483647
// CHK-CXX-NEXT:    [[BF_SET120:%.*]] = or i32 [[BF_CLEAR119]], [[BF_SHL118]]
// CHK-CXX-NEXT:    store i32 [[BF_SET120]], i32* [[ATOMIC_TEMP115]], align 4
// CHK-CXX-NEXT:    [[TMP47:%.*]] = load i32, i32* [[ATOMIC_TEMP115]], align 4
// CHK-CXX-NEXT:    [[TMP48:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0), i32 [[TMP46]], i32 [[TMP47]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP49]] = extractvalue { i32, i1 } [[TMP48]], 0
// CHK-CXX-NEXT:    [[TMP50:%.*]] = extractvalue { i32, i1 } [[TMP48]], 1
// CHK-CXX-NEXT:    br i1 [[TMP50]], label [[ATOMIC_EXIT127]], label [[ATOMIC_CMP121]]
// CHK-CXX:       atomic_cmp121:
// CHK-CXX-NEXT:    store i32 [[TMP49]], i32* [[ATOMIC_TEMP122]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD123:%.*]] = load i32, i32* [[ATOMIC_TEMP122]], align 4
// CHK-CXX-NEXT:    [[BF_ASHR124:%.*]] = ashr i32 [[BF_LOAD123]], 31
// CHK-CXX-NEXT:    store i32 [[BF_ASHR124]], i32* [[ATMP107]], align 4
// CHK-CXX-NEXT:    [[CMP125:%.*]] = icmp slt i32 [[BF_ASHR124]], [[TMP45]]
// CHK-CXX-NEXT:    [[FROMBOOL126:%.*]] = zext i1 [[CMP125]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL126]], i8* [[ATMP112]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP125]], label [[ATOMIC_CONT114]], label [[ATOMIC_EXIT127]]
// CHK-CXX:       atomic_exit127:
// CHK-CXX-NEXT:    [[TMP51:%.*]] = load i32, i32* [[ATMP107]], align 4
// CHK-CXX-NEXT:    [[TMP52:%.*]] = load i8, i8* [[ATMP112]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP51]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP53:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD128:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD128]], i32* [[ATOMIC_TEMP130]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD131:%.*]] = load i32, i32* [[ATOMIC_TEMP130]], align 4
// CHK-CXX-NEXT:    [[BF_ASHR132:%.*]] = ashr i32 [[BF_LOAD131]], 31
// CHK-CXX-NEXT:    store i32 [[BF_ASHR132]], i32* [[ATMP129]], align 4
// CHK-CXX-NEXT:    [[CMP133:%.*]] = icmp slt i32 [[BF_ASHR132]], [[TMP53]]
// CHK-CXX-NEXT:    [[FROMBOOL135:%.*]] = zext i1 [[CMP133]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL135]], i8* [[ATMP134]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP133]], label [[ATOMIC_CONT136:%.*]], label [[ATOMIC_EXIT150:%.*]]
// CHK-CXX:       atomic_cont136:
// CHK-CXX-NEXT:    [[TMP54:%.*]] = phi i32 [ [[ATOMIC_LOAD128]], [[ATOMIC_EXIT127]] ], [ [[TMP57:%.*]], [[ATOMIC_CMP144:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP54]], i32* [[ATOMIC_TEMP137]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD138:%.*]] = load i32, i32* [[ATOMIC_TEMP137]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE139:%.*]] = and i32 [[TMP53]], 1
// CHK-CXX-NEXT:    [[BF_SHL140:%.*]] = shl i32 [[BF_VALUE139]], 31
// CHK-CXX-NEXT:    [[BF_CLEAR141:%.*]] = and i32 [[BF_LOAD138]], 2147483647
// CHK-CXX-NEXT:    [[BF_SET142:%.*]] = or i32 [[BF_CLEAR141]], [[BF_SHL140]]
// CHK-CXX-NEXT:    store i32 [[BF_SET142]], i32* [[ATOMIC_TEMP137]], align 4
// CHK-CXX-NEXT:    [[TMP55:%.*]] = load i32, i32* [[ATOMIC_TEMP137]], align 4
// CHK-CXX-NEXT:    [[TMP56:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0), i32 [[TMP54]], i32 [[TMP55]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP57]] = extractvalue { i32, i1 } [[TMP56]], 0
// CHK-CXX-NEXT:    [[TMP58:%.*]] = extractvalue { i32, i1 } [[TMP56]], 1
// CHK-CXX-NEXT:    br i1 [[TMP58]], label [[ATOMIC_UPD_EXIT143:%.*]], label [[ATOMIC_CMP144]]
// CHK-CXX:       atomic_upd_exit143:
// CHK-CXX-NEXT:    store i32 [[TMP53]], i32* [[ATMP129]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT150]]
// CHK-CXX:       atomic_cmp144:
// CHK-CXX-NEXT:    store i32 [[TMP57]], i32* [[ATOMIC_TEMP145]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD146:%.*]] = load i32, i32* [[ATOMIC_TEMP145]], align 4
// CHK-CXX-NEXT:    [[BF_ASHR147:%.*]] = ashr i32 [[BF_LOAD146]], 31
// CHK-CXX-NEXT:    store i32 [[BF_ASHR147]], i32* [[ATMP129]], align 4
// CHK-CXX-NEXT:    [[CMP148:%.*]] = icmp slt i32 [[BF_ASHR147]], [[TMP53]]
// CHK-CXX-NEXT:    [[FROMBOOL149:%.*]] = zext i1 [[CMP148]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL149]], i8* [[ATMP134]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP148]], label [[ATOMIC_CONT136]], label [[ATOMIC_EXIT150]]
// CHK-CXX:       atomic_exit150:
// CHK-CXX-NEXT:    [[TMP59:%.*]] = load i32, i32* [[ATMP129]], align 4
// CHK-CXX-NEXT:    [[TMP60:%.*]] = load i8, i8* [[ATMP134]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP59]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP61:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP62:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD151:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD151]], i32* [[ATOMIC_TEMP153]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD154:%.*]] = load i32, i32* [[ATOMIC_TEMP153]], align 4
// CHK-CXX-NEXT:    [[BF_ASHR155:%.*]] = ashr i32 [[BF_LOAD154]], 31
// CHK-CXX-NEXT:    store i32 [[BF_ASHR155]], i32* [[ATMP152]], align 4
// CHK-CXX-NEXT:    [[CMP156:%.*]] = icmp eq i32 [[BF_ASHR155]], [[TMP62]]
// CHK-CXX-NEXT:    [[FROMBOOL158:%.*]] = zext i1 [[CMP156]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL158]], i8* [[ATMP157]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP156]], label [[ATOMIC_CONT159:%.*]], label [[ATOMIC_EXIT173:%.*]]
// CHK-CXX:       atomic_cont159:
// CHK-CXX-NEXT:    [[TMP63:%.*]] = phi i32 [ [[ATOMIC_LOAD151]], [[ATOMIC_EXIT150]] ], [ [[TMP66:%.*]], [[ATOMIC_CMP167:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP63]], i32* [[ATOMIC_TEMP160]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD161:%.*]] = load i32, i32* [[ATOMIC_TEMP160]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE162:%.*]] = and i32 [[TMP61]], 1
// CHK-CXX-NEXT:    [[BF_SHL163:%.*]] = shl i32 [[BF_VALUE162]], 31
// CHK-CXX-NEXT:    [[BF_CLEAR164:%.*]] = and i32 [[BF_LOAD161]], 2147483647
// CHK-CXX-NEXT:    [[BF_SET165:%.*]] = or i32 [[BF_CLEAR164]], [[BF_SHL163]]
// CHK-CXX-NEXT:    store i32 [[BF_SET165]], i32* [[ATOMIC_TEMP160]], align 4
// CHK-CXX-NEXT:    [[TMP64:%.*]] = load i32, i32* [[ATOMIC_TEMP160]], align 4
// CHK-CXX-NEXT:    [[TMP65:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0), i32 [[TMP63]], i32 [[TMP64]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP66]] = extractvalue { i32, i1 } [[TMP65]], 0
// CHK-CXX-NEXT:    [[TMP67:%.*]] = extractvalue { i32, i1 } [[TMP65]], 1
// CHK-CXX-NEXT:    br i1 [[TMP67]], label [[ATOMIC_UPD_EXIT166:%.*]], label [[ATOMIC_CMP167]]
// CHK-CXX:       atomic_upd_exit166:
// CHK-CXX-NEXT:    store i32 [[TMP61]], i32* [[ATMP152]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT173]]
// CHK-CXX:       atomic_cmp167:
// CHK-CXX-NEXT:    store i32 [[TMP66]], i32* [[ATOMIC_TEMP168]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD169:%.*]] = load i32, i32* [[ATOMIC_TEMP168]], align 4
// CHK-CXX-NEXT:    [[BF_ASHR170:%.*]] = ashr i32 [[BF_LOAD169]], 31
// CHK-CXX-NEXT:    store i32 [[BF_ASHR170]], i32* [[ATMP152]], align 4
// CHK-CXX-NEXT:    [[CMP171:%.*]] = icmp eq i32 [[BF_ASHR170]], [[TMP62]]
// CHK-CXX-NEXT:    [[FROMBOOL172:%.*]] = zext i1 [[CMP171]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL172]], i8* [[ATMP157]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP171]], label [[ATOMIC_CONT159]], label [[ATOMIC_EXIT173]]
// CHK-CXX:       atomic_exit173:
// CHK-CXX-NEXT:    [[TMP68:%.*]] = load i32, i32* [[ATMP152]], align 4
// CHK-CXX-NEXT:    [[TMP69:%.*]] = load i8, i8* [[ATMP157]], align 1
// CHK-CXX-NEXT:    [[TMP70:%.*]] = trunc i8 [[TMP69]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP70]], label [[ATOMIC_CAPTURE_CONT175:%.*]], label [[ATOMIC_CAPTURE174:%.*]]
// CHK-CXX:       atomic_capture174:
// CHK-CXX-NEXT:    store i32 [[TMP68]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT175]]
// CHK-CXX:       atomic_capture_cont175:
// CHK-CXX-NEXT:    [[TMP71:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP72:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD176:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD176]], i32* [[ATOMIC_TEMP178]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD179:%.*]] = load i32, i32* [[ATOMIC_TEMP178]], align 4
// CHK-CXX-NEXT:    [[BF_ASHR180:%.*]] = ashr i32 [[BF_LOAD179]], 31
// CHK-CXX-NEXT:    store i32 [[BF_ASHR180]], i32* [[ATMP177]], align 4
// CHK-CXX-NEXT:    [[CMP181:%.*]] = icmp eq i32 [[BF_ASHR180]], [[TMP72]]
// CHK-CXX-NEXT:    [[FROMBOOL183:%.*]] = zext i1 [[CMP181]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL183]], i8* [[ATMP182]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP181]], label [[ATOMIC_CONT184:%.*]], label [[ATOMIC_EXIT197:%.*]]
// CHK-CXX:       atomic_cont184:
// CHK-CXX-NEXT:    [[TMP73:%.*]] = phi i32 [ [[ATOMIC_LOAD176]], [[ATOMIC_CAPTURE_CONT175]] ], [ [[TMP76:%.*]], [[ATOMIC_CMP191:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP73]], i32* [[ATOMIC_TEMP185]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD186:%.*]] = load i32, i32* [[ATOMIC_TEMP185]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE187:%.*]] = and i32 [[TMP71]], 1
// CHK-CXX-NEXT:    [[BF_SHL188:%.*]] = shl i32 [[BF_VALUE187]], 31
// CHK-CXX-NEXT:    [[BF_CLEAR189:%.*]] = and i32 [[BF_LOAD186]], 2147483647
// CHK-CXX-NEXT:    [[BF_SET190:%.*]] = or i32 [[BF_CLEAR189]], [[BF_SHL188]]
// CHK-CXX-NEXT:    store i32 [[BF_SET190]], i32* [[ATOMIC_TEMP185]], align 4
// CHK-CXX-NEXT:    [[TMP74:%.*]] = load i32, i32* [[ATOMIC_TEMP185]], align 4
// CHK-CXX-NEXT:    [[TMP75:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0), i32 [[TMP73]], i32 [[TMP74]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP76]] = extractvalue { i32, i1 } [[TMP75]], 0
// CHK-CXX-NEXT:    [[TMP77:%.*]] = extractvalue { i32, i1 } [[TMP75]], 1
// CHK-CXX-NEXT:    br i1 [[TMP77]], label [[ATOMIC_EXIT197]], label [[ATOMIC_CMP191]]
// CHK-CXX:       atomic_cmp191:
// CHK-CXX-NEXT:    store i32 [[TMP76]], i32* [[ATOMIC_TEMP192]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD193:%.*]] = load i32, i32* [[ATOMIC_TEMP192]], align 4
// CHK-CXX-NEXT:    [[BF_ASHR194:%.*]] = ashr i32 [[BF_LOAD193]], 31
// CHK-CXX-NEXT:    store i32 [[BF_ASHR194]], i32* [[ATMP177]], align 4
// CHK-CXX-NEXT:    [[CMP195:%.*]] = icmp eq i32 [[BF_ASHR194]], [[TMP72]]
// CHK-CXX-NEXT:    [[FROMBOOL196:%.*]] = zext i1 [[CMP195]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL196]], i8* [[ATMP182]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP195]], label [[ATOMIC_CONT184]], label [[ATOMIC_EXIT197]]
// CHK-CXX:       atomic_exit197:
// CHK-CXX-NEXT:    [[TMP78:%.*]] = load i32, i32* [[ATMP177]], align 4
// CHK-CXX-NEXT:    [[TMP79:%.*]] = load i8, i8* [[ATMP182]], align 1
// CHK-CXX-NEXT:    [[CONV198:%.*]] = zext i8 [[TMP79]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV198]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP80:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP81:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD199:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD199]], i32* [[ATOMIC_TEMP201]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD202:%.*]] = load i32, i32* [[ATOMIC_TEMP201]], align 4
// CHK-CXX-NEXT:    [[BF_ASHR203:%.*]] = ashr i32 [[BF_LOAD202]], 31
// CHK-CXX-NEXT:    store i32 [[BF_ASHR203]], i32* [[ATMP200]], align 4
// CHK-CXX-NEXT:    [[CMP204:%.*]] = icmp eq i32 [[BF_ASHR203]], [[TMP81]]
// CHK-CXX-NEXT:    [[FROMBOOL206:%.*]] = zext i1 [[CMP204]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL206]], i8* [[ATMP205]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP204]], label [[ATOMIC_CONT207:%.*]], label [[ATOMIC_EXIT220:%.*]]
// CHK-CXX:       atomic_cont207:
// CHK-CXX-NEXT:    [[TMP82:%.*]] = phi i32 [ [[ATOMIC_LOAD199]], [[ATOMIC_EXIT197]] ], [ [[TMP85:%.*]], [[ATOMIC_CMP214:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP82]], i32* [[ATOMIC_TEMP208]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD209:%.*]] = load i32, i32* [[ATOMIC_TEMP208]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE210:%.*]] = and i32 [[TMP80]], 1
// CHK-CXX-NEXT:    [[BF_SHL211:%.*]] = shl i32 [[BF_VALUE210]], 31
// CHK-CXX-NEXT:    [[BF_CLEAR212:%.*]] = and i32 [[BF_LOAD209]], 2147483647
// CHK-CXX-NEXT:    [[BF_SET213:%.*]] = or i32 [[BF_CLEAR212]], [[BF_SHL211]]
// CHK-CXX-NEXT:    store i32 [[BF_SET213]], i32* [[ATOMIC_TEMP208]], align 4
// CHK-CXX-NEXT:    [[TMP83:%.*]] = load i32, i32* [[ATOMIC_TEMP208]], align 4
// CHK-CXX-NEXT:    [[TMP84:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS2]], %struct.BitFields2* @bfx2, i32 0, i32 0), i32 [[TMP82]], i32 [[TMP83]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP85]] = extractvalue { i32, i1 } [[TMP84]], 0
// CHK-CXX-NEXT:    [[TMP86:%.*]] = extractvalue { i32, i1 } [[TMP84]], 1
// CHK-CXX-NEXT:    br i1 [[TMP86]], label [[ATOMIC_EXIT220]], label [[ATOMIC_CMP214]]
// CHK-CXX:       atomic_cmp214:
// CHK-CXX-NEXT:    store i32 [[TMP85]], i32* [[ATOMIC_TEMP215]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD216:%.*]] = load i32, i32* [[ATOMIC_TEMP215]], align 4
// CHK-CXX-NEXT:    [[BF_ASHR217:%.*]] = ashr i32 [[BF_LOAD216]], 31
// CHK-CXX-NEXT:    store i32 [[BF_ASHR217]], i32* [[ATMP200]], align 4
// CHK-CXX-NEXT:    [[CMP218:%.*]] = icmp eq i32 [[BF_ASHR217]], [[TMP81]]
// CHK-CXX-NEXT:    [[FROMBOOL219:%.*]] = zext i1 [[CMP218]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL219]], i8* [[ATMP205]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP218]], label [[ATOMIC_CONT207]], label [[ATOMIC_EXIT220]]
// CHK-CXX:       atomic_exit220:
// CHK-CXX-NEXT:    [[TMP87:%.*]] = load i32, i32* [[ATMP200]], align 4
// CHK-CXX-NEXT:    [[TMP88:%.*]] = load i8, i8* [[ATMP205]], align 1
// CHK-CXX-NEXT:    [[CONV221:%.*]] = zext i8 [[TMP88]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV221]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP89:%.*]] = trunc i8 [[TMP88]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP89]], label [[ATOMIC_CAPTURE_CONT223:%.*]], label [[ATOMIC_CAPTURE222:%.*]]
// CHK-CXX:       atomic_capture222:
// CHK-CXX-NEXT:    store i32 [[TMP87]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT223]]
// CHK-CXX:       atomic_capture_cont223:
// CHK-CXX-NEXT:    [[TMP90:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD224:%.*]] = load atomic i8, i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3) monotonic, align 1
// CHK-CXX-NEXT:    [[TMP91:%.*]] = bitcast i32* [[ATOMIC_TEMP226]] to i8*
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD224]], i8* [[TMP91]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD227:%.*]] = load i8, i8* [[TMP91]], align 1
// CHK-CXX-NEXT:    [[BF_ASHR228:%.*]] = ashr i8 [[BF_LOAD227]], 7
// CHK-CXX-NEXT:    [[BF_CAST:%.*]] = sext i8 [[BF_ASHR228]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST]], i32* [[ATMP225]], align 4
// CHK-CXX-NEXT:    [[CMP229:%.*]] = icmp slt i32 [[BF_CAST]], [[TMP90]]
// CHK-CXX-NEXT:    [[FROMBOOL231:%.*]] = zext i1 [[CMP229]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL231]], i8* [[ATMP230]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP229]], label [[ATOMIC_CONT232:%.*]], label [[ATOMIC_EXIT246:%.*]]
// CHK-CXX:       atomic_cont232:
// CHK-CXX-NEXT:    [[TMP92:%.*]] = phi i8 [ [[ATOMIC_LOAD224]], [[ATOMIC_CAPTURE_CONT223]] ], [ [[TMP97:%.*]], [[ATOMIC_CMP239:%.*]] ]
// CHK-CXX-NEXT:    [[TMP93:%.*]] = bitcast i32* [[ATOMIC_TEMP233]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP92]], i8* [[TMP93]], align 1
// CHK-CXX-NEXT:    [[TMP94:%.*]] = trunc i32 [[TMP90]] to i8
// CHK-CXX-NEXT:    [[BF_LOAD234:%.*]] = load i8, i8* [[TMP93]], align 1
// CHK-CXX-NEXT:    [[BF_VALUE235:%.*]] = and i8 [[TMP94]], 1
// CHK-CXX-NEXT:    [[BF_SHL236:%.*]] = shl i8 [[BF_VALUE235]], 7
// CHK-CXX-NEXT:    [[BF_CLEAR237:%.*]] = and i8 [[BF_LOAD234]], 127
// CHK-CXX-NEXT:    [[BF_SET238:%.*]] = or i8 [[BF_CLEAR237]], [[BF_SHL236]]
// CHK-CXX-NEXT:    store i8 [[BF_SET238]], i8* [[TMP93]], align 1
// CHK-CXX-NEXT:    [[TMP95:%.*]] = load i8, i8* [[TMP93]], align 1
// CHK-CXX-NEXT:    [[TMP96:%.*]] = cmpxchg i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3), i8 [[TMP92]], i8 [[TMP95]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP97]] = extractvalue { i8, i1 } [[TMP96]], 0
// CHK-CXX-NEXT:    [[TMP98:%.*]] = extractvalue { i8, i1 } [[TMP96]], 1
// CHK-CXX-NEXT:    br i1 [[TMP98]], label [[ATOMIC_EXIT246]], label [[ATOMIC_CMP239]]
// CHK-CXX:       atomic_cmp239:
// CHK-CXX-NEXT:    [[TMP99:%.*]] = bitcast i32* [[ATOMIC_TEMP240]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP97]], i8* [[TMP99]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD241:%.*]] = load i8, i8* [[TMP99]], align 1
// CHK-CXX-NEXT:    [[BF_ASHR242:%.*]] = ashr i8 [[BF_LOAD241]], 7
// CHK-CXX-NEXT:    [[BF_CAST243:%.*]] = sext i8 [[BF_ASHR242]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST243]], i32* [[ATMP225]], align 4
// CHK-CXX-NEXT:    [[CMP244:%.*]] = icmp slt i32 [[BF_CAST243]], [[TMP90]]
// CHK-CXX-NEXT:    [[FROMBOOL245:%.*]] = zext i1 [[CMP244]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL245]], i8* [[ATMP230]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP244]], label [[ATOMIC_CONT232]], label [[ATOMIC_EXIT246]]
// CHK-CXX:       atomic_exit246:
// CHK-CXX-NEXT:    [[TMP100:%.*]] = load i32, i32* [[ATMP225]], align 4
// CHK-CXX-NEXT:    [[TMP101:%.*]] = load i8, i8* [[ATMP230]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP100]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP102:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD247:%.*]] = load atomic i8, i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3) monotonic, align 1
// CHK-CXX-NEXT:    [[TMP103:%.*]] = bitcast i32* [[ATOMIC_TEMP249]] to i8*
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD247]], i8* [[TMP103]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD250:%.*]] = load i8, i8* [[TMP103]], align 1
// CHK-CXX-NEXT:    [[BF_ASHR251:%.*]] = ashr i8 [[BF_LOAD250]], 7
// CHK-CXX-NEXT:    [[BF_CAST252:%.*]] = sext i8 [[BF_ASHR251]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST252]], i32* [[ATMP248]], align 4
// CHK-CXX-NEXT:    [[CMP253:%.*]] = icmp slt i32 [[BF_CAST252]], [[TMP102]]
// CHK-CXX-NEXT:    [[FROMBOOL255:%.*]] = zext i1 [[CMP253]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL255]], i8* [[ATMP254]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP253]], label [[ATOMIC_CONT256:%.*]], label [[ATOMIC_EXIT271:%.*]]
// CHK-CXX:       atomic_cont256:
// CHK-CXX-NEXT:    [[TMP104:%.*]] = phi i8 [ [[ATOMIC_LOAD247]], [[ATOMIC_EXIT246]] ], [ [[TMP109:%.*]], [[ATOMIC_CMP264:%.*]] ]
// CHK-CXX-NEXT:    [[TMP105:%.*]] = bitcast i32* [[ATOMIC_TEMP257]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP104]], i8* [[TMP105]], align 1
// CHK-CXX-NEXT:    [[TMP106:%.*]] = trunc i32 [[TMP102]] to i8
// CHK-CXX-NEXT:    [[BF_LOAD258:%.*]] = load i8, i8* [[TMP105]], align 1
// CHK-CXX-NEXT:    [[BF_VALUE259:%.*]] = and i8 [[TMP106]], 1
// CHK-CXX-NEXT:    [[BF_SHL260:%.*]] = shl i8 [[BF_VALUE259]], 7
// CHK-CXX-NEXT:    [[BF_CLEAR261:%.*]] = and i8 [[BF_LOAD258]], 127
// CHK-CXX-NEXT:    [[BF_SET262:%.*]] = or i8 [[BF_CLEAR261]], [[BF_SHL260]]
// CHK-CXX-NEXT:    store i8 [[BF_SET262]], i8* [[TMP105]], align 1
// CHK-CXX-NEXT:    [[TMP107:%.*]] = load i8, i8* [[TMP105]], align 1
// CHK-CXX-NEXT:    [[TMP108:%.*]] = cmpxchg i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3), i8 [[TMP104]], i8 [[TMP107]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP109]] = extractvalue { i8, i1 } [[TMP108]], 0
// CHK-CXX-NEXT:    [[TMP110:%.*]] = extractvalue { i8, i1 } [[TMP108]], 1
// CHK-CXX-NEXT:    br i1 [[TMP110]], label [[ATOMIC_UPD_EXIT263:%.*]], label [[ATOMIC_CMP264]]
// CHK-CXX:       atomic_upd_exit263:
// CHK-CXX-NEXT:    store i32 [[TMP102]], i32* [[ATMP248]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT271]]
// CHK-CXX:       atomic_cmp264:
// CHK-CXX-NEXT:    [[TMP111:%.*]] = bitcast i32* [[ATOMIC_TEMP265]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP109]], i8* [[TMP111]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD266:%.*]] = load i8, i8* [[TMP111]], align 1
// CHK-CXX-NEXT:    [[BF_ASHR267:%.*]] = ashr i8 [[BF_LOAD266]], 7
// CHK-CXX-NEXT:    [[BF_CAST268:%.*]] = sext i8 [[BF_ASHR267]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST268]], i32* [[ATMP248]], align 4
// CHK-CXX-NEXT:    [[CMP269:%.*]] = icmp slt i32 [[BF_CAST268]], [[TMP102]]
// CHK-CXX-NEXT:    [[FROMBOOL270:%.*]] = zext i1 [[CMP269]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL270]], i8* [[ATMP254]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP269]], label [[ATOMIC_CONT256]], label [[ATOMIC_EXIT271]]
// CHK-CXX:       atomic_exit271:
// CHK-CXX-NEXT:    [[TMP112:%.*]] = load i32, i32* [[ATMP248]], align 4
// CHK-CXX-NEXT:    [[TMP113:%.*]] = load i8, i8* [[ATMP254]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP112]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP114:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP115:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD272:%.*]] = load atomic i8, i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3) monotonic, align 1
// CHK-CXX-NEXT:    [[TMP116:%.*]] = bitcast i32* [[ATOMIC_TEMP274]] to i8*
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD272]], i8* [[TMP116]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD275:%.*]] = load i8, i8* [[TMP116]], align 1
// CHK-CXX-NEXT:    [[BF_ASHR276:%.*]] = ashr i8 [[BF_LOAD275]], 7
// CHK-CXX-NEXT:    [[BF_CAST277:%.*]] = sext i8 [[BF_ASHR276]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST277]], i32* [[ATMP273]], align 4
// CHK-CXX-NEXT:    [[CMP278:%.*]] = icmp eq i32 [[BF_CAST277]], [[TMP115]]
// CHK-CXX-NEXT:    [[FROMBOOL280:%.*]] = zext i1 [[CMP278]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL280]], i8* [[ATMP279]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP278]], label [[ATOMIC_CONT281:%.*]], label [[ATOMIC_EXIT296:%.*]]
// CHK-CXX:       atomic_cont281:
// CHK-CXX-NEXT:    [[TMP117:%.*]] = phi i8 [ [[ATOMIC_LOAD272]], [[ATOMIC_EXIT271]] ], [ [[TMP122:%.*]], [[ATOMIC_CMP289:%.*]] ]
// CHK-CXX-NEXT:    [[TMP118:%.*]] = bitcast i32* [[ATOMIC_TEMP282]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP117]], i8* [[TMP118]], align 1
// CHK-CXX-NEXT:    [[TMP119:%.*]] = trunc i32 [[TMP114]] to i8
// CHK-CXX-NEXT:    [[BF_LOAD283:%.*]] = load i8, i8* [[TMP118]], align 1
// CHK-CXX-NEXT:    [[BF_VALUE284:%.*]] = and i8 [[TMP119]], 1
// CHK-CXX-NEXT:    [[BF_SHL285:%.*]] = shl i8 [[BF_VALUE284]], 7
// CHK-CXX-NEXT:    [[BF_CLEAR286:%.*]] = and i8 [[BF_LOAD283]], 127
// CHK-CXX-NEXT:    [[BF_SET287:%.*]] = or i8 [[BF_CLEAR286]], [[BF_SHL285]]
// CHK-CXX-NEXT:    store i8 [[BF_SET287]], i8* [[TMP118]], align 1
// CHK-CXX-NEXT:    [[TMP120:%.*]] = load i8, i8* [[TMP118]], align 1
// CHK-CXX-NEXT:    [[TMP121:%.*]] = cmpxchg i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3), i8 [[TMP117]], i8 [[TMP120]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP122]] = extractvalue { i8, i1 } [[TMP121]], 0
// CHK-CXX-NEXT:    [[TMP123:%.*]] = extractvalue { i8, i1 } [[TMP121]], 1
// CHK-CXX-NEXT:    br i1 [[TMP123]], label [[ATOMIC_UPD_EXIT288:%.*]], label [[ATOMIC_CMP289]]
// CHK-CXX:       atomic_upd_exit288:
// CHK-CXX-NEXT:    store i32 [[TMP114]], i32* [[ATMP273]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT296]]
// CHK-CXX:       atomic_cmp289:
// CHK-CXX-NEXT:    [[TMP124:%.*]] = bitcast i32* [[ATOMIC_TEMP290]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP122]], i8* [[TMP124]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD291:%.*]] = load i8, i8* [[TMP124]], align 1
// CHK-CXX-NEXT:    [[BF_ASHR292:%.*]] = ashr i8 [[BF_LOAD291]], 7
// CHK-CXX-NEXT:    [[BF_CAST293:%.*]] = sext i8 [[BF_ASHR292]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST293]], i32* [[ATMP273]], align 4
// CHK-CXX-NEXT:    [[CMP294:%.*]] = icmp eq i32 [[BF_CAST293]], [[TMP115]]
// CHK-CXX-NEXT:    [[FROMBOOL295:%.*]] = zext i1 [[CMP294]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL295]], i8* [[ATMP279]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP294]], label [[ATOMIC_CONT281]], label [[ATOMIC_EXIT296]]
// CHK-CXX:       atomic_exit296:
// CHK-CXX-NEXT:    [[TMP125:%.*]] = load i32, i32* [[ATMP273]], align 4
// CHK-CXX-NEXT:    [[TMP126:%.*]] = load i8, i8* [[ATMP279]], align 1
// CHK-CXX-NEXT:    [[TMP127:%.*]] = trunc i8 [[TMP126]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP127]], label [[ATOMIC_CAPTURE_CONT298:%.*]], label [[ATOMIC_CAPTURE297:%.*]]
// CHK-CXX:       atomic_capture297:
// CHK-CXX-NEXT:    store i32 [[TMP125]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT298]]
// CHK-CXX:       atomic_capture_cont298:
// CHK-CXX-NEXT:    [[TMP128:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP129:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD299:%.*]] = load atomic i8, i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3) monotonic, align 1
// CHK-CXX-NEXT:    [[TMP130:%.*]] = bitcast i32* [[ATOMIC_TEMP301]] to i8*
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD299]], i8* [[TMP130]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD302:%.*]] = load i8, i8* [[TMP130]], align 1
// CHK-CXX-NEXT:    [[BF_ASHR303:%.*]] = ashr i8 [[BF_LOAD302]], 7
// CHK-CXX-NEXT:    [[BF_CAST304:%.*]] = sext i8 [[BF_ASHR303]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST304]], i32* [[ATMP300]], align 4
// CHK-CXX-NEXT:    [[CMP305:%.*]] = icmp eq i32 [[BF_CAST304]], [[TMP129]]
// CHK-CXX-NEXT:    [[FROMBOOL307:%.*]] = zext i1 [[CMP305]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL307]], i8* [[ATMP306]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP305]], label [[ATOMIC_CONT308:%.*]], label [[ATOMIC_EXIT322:%.*]]
// CHK-CXX:       atomic_cont308:
// CHK-CXX-NEXT:    [[TMP131:%.*]] = phi i8 [ [[ATOMIC_LOAD299]], [[ATOMIC_CAPTURE_CONT298]] ], [ [[TMP136:%.*]], [[ATOMIC_CMP315:%.*]] ]
// CHK-CXX-NEXT:    [[TMP132:%.*]] = bitcast i32* [[ATOMIC_TEMP309]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP131]], i8* [[TMP132]], align 1
// CHK-CXX-NEXT:    [[TMP133:%.*]] = trunc i32 [[TMP128]] to i8
// CHK-CXX-NEXT:    [[BF_LOAD310:%.*]] = load i8, i8* [[TMP132]], align 1
// CHK-CXX-NEXT:    [[BF_VALUE311:%.*]] = and i8 [[TMP133]], 1
// CHK-CXX-NEXT:    [[BF_SHL312:%.*]] = shl i8 [[BF_VALUE311]], 7
// CHK-CXX-NEXT:    [[BF_CLEAR313:%.*]] = and i8 [[BF_LOAD310]], 127
// CHK-CXX-NEXT:    [[BF_SET314:%.*]] = or i8 [[BF_CLEAR313]], [[BF_SHL312]]
// CHK-CXX-NEXT:    store i8 [[BF_SET314]], i8* [[TMP132]], align 1
// CHK-CXX-NEXT:    [[TMP134:%.*]] = load i8, i8* [[TMP132]], align 1
// CHK-CXX-NEXT:    [[TMP135:%.*]] = cmpxchg i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3), i8 [[TMP131]], i8 [[TMP134]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP136]] = extractvalue { i8, i1 } [[TMP135]], 0
// CHK-CXX-NEXT:    [[TMP137:%.*]] = extractvalue { i8, i1 } [[TMP135]], 1
// CHK-CXX-NEXT:    br i1 [[TMP137]], label [[ATOMIC_EXIT322]], label [[ATOMIC_CMP315]]
// CHK-CXX:       atomic_cmp315:
// CHK-CXX-NEXT:    [[TMP138:%.*]] = bitcast i32* [[ATOMIC_TEMP316]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP136]], i8* [[TMP138]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD317:%.*]] = load i8, i8* [[TMP138]], align 1
// CHK-CXX-NEXT:    [[BF_ASHR318:%.*]] = ashr i8 [[BF_LOAD317]], 7
// CHK-CXX-NEXT:    [[BF_CAST319:%.*]] = sext i8 [[BF_ASHR318]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST319]], i32* [[ATMP300]], align 4
// CHK-CXX-NEXT:    [[CMP320:%.*]] = icmp eq i32 [[BF_CAST319]], [[TMP129]]
// CHK-CXX-NEXT:    [[FROMBOOL321:%.*]] = zext i1 [[CMP320]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL321]], i8* [[ATMP306]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP320]], label [[ATOMIC_CONT308]], label [[ATOMIC_EXIT322]]
// CHK-CXX:       atomic_exit322:
// CHK-CXX-NEXT:    [[TMP139:%.*]] = load i32, i32* [[ATMP300]], align 4
// CHK-CXX-NEXT:    [[TMP140:%.*]] = load i8, i8* [[ATMP306]], align 1
// CHK-CXX-NEXT:    [[CONV323:%.*]] = zext i8 [[TMP140]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV323]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP141:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP142:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD324:%.*]] = load atomic i8, i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3) monotonic, align 1
// CHK-CXX-NEXT:    [[TMP143:%.*]] = bitcast i32* [[ATOMIC_TEMP326]] to i8*
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD324]], i8* [[TMP143]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD327:%.*]] = load i8, i8* [[TMP143]], align 1
// CHK-CXX-NEXT:    [[BF_ASHR328:%.*]] = ashr i8 [[BF_LOAD327]], 7
// CHK-CXX-NEXT:    [[BF_CAST329:%.*]] = sext i8 [[BF_ASHR328]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST329]], i32* [[ATMP325]], align 4
// CHK-CXX-NEXT:    [[CMP330:%.*]] = icmp eq i32 [[BF_CAST329]], [[TMP142]]
// CHK-CXX-NEXT:    [[FROMBOOL332:%.*]] = zext i1 [[CMP330]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL332]], i8* [[ATMP331]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP330]], label [[ATOMIC_CONT333:%.*]], label [[ATOMIC_EXIT347:%.*]]
// CHK-CXX:       atomic_cont333:
// CHK-CXX-NEXT:    [[TMP144:%.*]] = phi i8 [ [[ATOMIC_LOAD324]], [[ATOMIC_EXIT322]] ], [ [[TMP149:%.*]], [[ATOMIC_CMP340:%.*]] ]
// CHK-CXX-NEXT:    [[TMP145:%.*]] = bitcast i32* [[ATOMIC_TEMP334]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP144]], i8* [[TMP145]], align 1
// CHK-CXX-NEXT:    [[TMP146:%.*]] = trunc i32 [[TMP141]] to i8
// CHK-CXX-NEXT:    [[BF_LOAD335:%.*]] = load i8, i8* [[TMP145]], align 1
// CHK-CXX-NEXT:    [[BF_VALUE336:%.*]] = and i8 [[TMP146]], 1
// CHK-CXX-NEXT:    [[BF_SHL337:%.*]] = shl i8 [[BF_VALUE336]], 7
// CHK-CXX-NEXT:    [[BF_CLEAR338:%.*]] = and i8 [[BF_LOAD335]], 127
// CHK-CXX-NEXT:    [[BF_SET339:%.*]] = or i8 [[BF_CLEAR338]], [[BF_SHL337]]
// CHK-CXX-NEXT:    store i8 [[BF_SET339]], i8* [[TMP145]], align 1
// CHK-CXX-NEXT:    [[TMP147:%.*]] = load i8, i8* [[TMP145]], align 1
// CHK-CXX-NEXT:    [[TMP148:%.*]] = cmpxchg i8* getelementptr (i8, i8* bitcast (%struct.BitFields2_packed* @bfx2_packed to i8*), i64 3), i8 [[TMP144]], i8 [[TMP147]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP149]] = extractvalue { i8, i1 } [[TMP148]], 0
// CHK-CXX-NEXT:    [[TMP150:%.*]] = extractvalue { i8, i1 } [[TMP148]], 1
// CHK-CXX-NEXT:    br i1 [[TMP150]], label [[ATOMIC_EXIT347]], label [[ATOMIC_CMP340]]
// CHK-CXX:       atomic_cmp340:
// CHK-CXX-NEXT:    [[TMP151:%.*]] = bitcast i32* [[ATOMIC_TEMP341]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP149]], i8* [[TMP151]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD342:%.*]] = load i8, i8* [[TMP151]], align 1
// CHK-CXX-NEXT:    [[BF_ASHR343:%.*]] = ashr i8 [[BF_LOAD342]], 7
// CHK-CXX-NEXT:    [[BF_CAST344:%.*]] = sext i8 [[BF_ASHR343]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST344]], i32* [[ATMP325]], align 4
// CHK-CXX-NEXT:    [[CMP345:%.*]] = icmp eq i32 [[BF_CAST344]], [[TMP142]]
// CHK-CXX-NEXT:    [[FROMBOOL346:%.*]] = zext i1 [[CMP345]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL346]], i8* [[ATMP331]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP345]], label [[ATOMIC_CONT333]], label [[ATOMIC_EXIT347]]
// CHK-CXX:       atomic_exit347:
// CHK-CXX-NEXT:    [[TMP152:%.*]] = load i32, i32* [[ATMP325]], align 4
// CHK-CXX-NEXT:    [[TMP153:%.*]] = load i8, i8* [[ATMP331]], align 1
// CHK-CXX-NEXT:    [[CONV348:%.*]] = zext i8 [[TMP153]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV348]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP154:%.*]] = trunc i8 [[TMP153]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP154]], label [[ATOMIC_CAPTURE_CONT350:%.*]], label [[ATOMIC_CAPTURE349:%.*]]
// CHK-CXX:       atomic_capture349:
// CHK-CXX-NEXT:    store i32 [[TMP152]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT350]]
// CHK-CXX:       atomic_capture_cont350:
// CHK-CXX-NEXT:    [[TMP155:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD351:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS3:%.*]], %struct.BitFields3* @bfx3, i32 0, i32 0) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD351]], i32* [[ATOMIC_TEMP353]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD354:%.*]] = load i32, i32* [[ATOMIC_TEMP353]], align 4
// CHK-CXX-NEXT:    [[BF_SHL355:%.*]] = shl i32 [[BF_LOAD354]], 7
// CHK-CXX-NEXT:    [[BF_ASHR356:%.*]] = ashr i32 [[BF_SHL355]], 18
// CHK-CXX-NEXT:    store i32 [[BF_ASHR356]], i32* [[ATMP352]], align 4
// CHK-CXX-NEXT:    [[CMP357:%.*]] = icmp slt i32 [[BF_ASHR356]], [[TMP155]]
// CHK-CXX-NEXT:    [[FROMBOOL359:%.*]] = zext i1 [[CMP357]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL359]], i8* [[ATMP358]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP357]], label [[ATOMIC_CONT360:%.*]], label [[ATOMIC_EXIT374:%.*]]
// CHK-CXX:       atomic_cont360:
// CHK-CXX-NEXT:    [[TMP156:%.*]] = phi i32 [ [[ATOMIC_LOAD351]], [[ATOMIC_CAPTURE_CONT350]] ], [ [[TMP159:%.*]], [[ATOMIC_CMP367:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP156]], i32* [[ATOMIC_TEMP361]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD362:%.*]] = load i32, i32* [[ATOMIC_TEMP361]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE363:%.*]] = and i32 [[TMP155]], 16383
// CHK-CXX-NEXT:    [[BF_SHL364:%.*]] = shl i32 [[BF_VALUE363]], 11
// CHK-CXX-NEXT:    [[BF_CLEAR365:%.*]] = and i32 [[BF_LOAD362]], -33552385
// CHK-CXX-NEXT:    [[BF_SET366:%.*]] = or i32 [[BF_CLEAR365]], [[BF_SHL364]]
// CHK-CXX-NEXT:    store i32 [[BF_SET366]], i32* [[ATOMIC_TEMP361]], align 4
// CHK-CXX-NEXT:    [[TMP157:%.*]] = load i32, i32* [[ATOMIC_TEMP361]], align 4
// CHK-CXX-NEXT:    [[TMP158:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0), i32 [[TMP156]], i32 [[TMP157]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP159]] = extractvalue { i32, i1 } [[TMP158]], 0
// CHK-CXX-NEXT:    [[TMP160:%.*]] = extractvalue { i32, i1 } [[TMP158]], 1
// CHK-CXX-NEXT:    br i1 [[TMP160]], label [[ATOMIC_EXIT374]], label [[ATOMIC_CMP367]]
// CHK-CXX:       atomic_cmp367:
// CHK-CXX-NEXT:    store i32 [[TMP159]], i32* [[ATOMIC_TEMP368]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD369:%.*]] = load i32, i32* [[ATOMIC_TEMP368]], align 4
// CHK-CXX-NEXT:    [[BF_SHL370:%.*]] = shl i32 [[BF_LOAD369]], 7
// CHK-CXX-NEXT:    [[BF_ASHR371:%.*]] = ashr i32 [[BF_SHL370]], 18
// CHK-CXX-NEXT:    store i32 [[BF_ASHR371]], i32* [[ATMP352]], align 4
// CHK-CXX-NEXT:    [[CMP372:%.*]] = icmp slt i32 [[BF_ASHR371]], [[TMP155]]
// CHK-CXX-NEXT:    [[FROMBOOL373:%.*]] = zext i1 [[CMP372]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL373]], i8* [[ATMP358]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP372]], label [[ATOMIC_CONT360]], label [[ATOMIC_EXIT374]]
// CHK-CXX:       atomic_exit374:
// CHK-CXX-NEXT:    [[TMP161:%.*]] = load i32, i32* [[ATMP352]], align 4
// CHK-CXX-NEXT:    [[TMP162:%.*]] = load i8, i8* [[ATMP358]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP161]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP163:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD375:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD375]], i32* [[ATOMIC_TEMP377]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD378:%.*]] = load i32, i32* [[ATOMIC_TEMP377]], align 4
// CHK-CXX-NEXT:    [[BF_SHL379:%.*]] = shl i32 [[BF_LOAD378]], 7
// CHK-CXX-NEXT:    [[BF_ASHR380:%.*]] = ashr i32 [[BF_SHL379]], 18
// CHK-CXX-NEXT:    store i32 [[BF_ASHR380]], i32* [[ATMP376]], align 4
// CHK-CXX-NEXT:    [[CMP381:%.*]] = icmp slt i32 [[BF_ASHR380]], [[TMP163]]
// CHK-CXX-NEXT:    [[FROMBOOL383:%.*]] = zext i1 [[CMP381]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL383]], i8* [[ATMP382]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP381]], label [[ATOMIC_CONT384:%.*]], label [[ATOMIC_EXIT399:%.*]]
// CHK-CXX:       atomic_cont384:
// CHK-CXX-NEXT:    [[TMP164:%.*]] = phi i32 [ [[ATOMIC_LOAD375]], [[ATOMIC_EXIT374]] ], [ [[TMP167:%.*]], [[ATOMIC_CMP392:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP164]], i32* [[ATOMIC_TEMP385]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD386:%.*]] = load i32, i32* [[ATOMIC_TEMP385]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE387:%.*]] = and i32 [[TMP163]], 16383
// CHK-CXX-NEXT:    [[BF_SHL388:%.*]] = shl i32 [[BF_VALUE387]], 11
// CHK-CXX-NEXT:    [[BF_CLEAR389:%.*]] = and i32 [[BF_LOAD386]], -33552385
// CHK-CXX-NEXT:    [[BF_SET390:%.*]] = or i32 [[BF_CLEAR389]], [[BF_SHL388]]
// CHK-CXX-NEXT:    store i32 [[BF_SET390]], i32* [[ATOMIC_TEMP385]], align 4
// CHK-CXX-NEXT:    [[TMP165:%.*]] = load i32, i32* [[ATOMIC_TEMP385]], align 4
// CHK-CXX-NEXT:    [[TMP166:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0), i32 [[TMP164]], i32 [[TMP165]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP167]] = extractvalue { i32, i1 } [[TMP166]], 0
// CHK-CXX-NEXT:    [[TMP168:%.*]] = extractvalue { i32, i1 } [[TMP166]], 1
// CHK-CXX-NEXT:    br i1 [[TMP168]], label [[ATOMIC_UPD_EXIT391:%.*]], label [[ATOMIC_CMP392]]
// CHK-CXX:       atomic_upd_exit391:
// CHK-CXX-NEXT:    store i32 [[TMP163]], i32* [[ATMP376]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT399]]
// CHK-CXX:       atomic_cmp392:
// CHK-CXX-NEXT:    store i32 [[TMP167]], i32* [[ATOMIC_TEMP393]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD394:%.*]] = load i32, i32* [[ATOMIC_TEMP393]], align 4
// CHK-CXX-NEXT:    [[BF_SHL395:%.*]] = shl i32 [[BF_LOAD394]], 7
// CHK-CXX-NEXT:    [[BF_ASHR396:%.*]] = ashr i32 [[BF_SHL395]], 18
// CHK-CXX-NEXT:    store i32 [[BF_ASHR396]], i32* [[ATMP376]], align 4
// CHK-CXX-NEXT:    [[CMP397:%.*]] = icmp slt i32 [[BF_ASHR396]], [[TMP163]]
// CHK-CXX-NEXT:    [[FROMBOOL398:%.*]] = zext i1 [[CMP397]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL398]], i8* [[ATMP382]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP397]], label [[ATOMIC_CONT384]], label [[ATOMIC_EXIT399]]
// CHK-CXX:       atomic_exit399:
// CHK-CXX-NEXT:    [[TMP169:%.*]] = load i32, i32* [[ATMP376]], align 4
// CHK-CXX-NEXT:    [[TMP170:%.*]] = load i8, i8* [[ATMP382]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP169]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP171:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP172:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD400:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD400]], i32* [[ATOMIC_TEMP402]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD403:%.*]] = load i32, i32* [[ATOMIC_TEMP402]], align 4
// CHK-CXX-NEXT:    [[BF_SHL404:%.*]] = shl i32 [[BF_LOAD403]], 7
// CHK-CXX-NEXT:    [[BF_ASHR405:%.*]] = ashr i32 [[BF_SHL404]], 18
// CHK-CXX-NEXT:    store i32 [[BF_ASHR405]], i32* [[ATMP401]], align 4
// CHK-CXX-NEXT:    [[CMP406:%.*]] = icmp eq i32 [[BF_ASHR405]], [[TMP172]]
// CHK-CXX-NEXT:    [[FROMBOOL408:%.*]] = zext i1 [[CMP406]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL408]], i8* [[ATMP407]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP406]], label [[ATOMIC_CONT409:%.*]], label [[ATOMIC_EXIT424:%.*]]
// CHK-CXX:       atomic_cont409:
// CHK-CXX-NEXT:    [[TMP173:%.*]] = phi i32 [ [[ATOMIC_LOAD400]], [[ATOMIC_EXIT399]] ], [ [[TMP176:%.*]], [[ATOMIC_CMP417:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP173]], i32* [[ATOMIC_TEMP410]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD411:%.*]] = load i32, i32* [[ATOMIC_TEMP410]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE412:%.*]] = and i32 [[TMP171]], 16383
// CHK-CXX-NEXT:    [[BF_SHL413:%.*]] = shl i32 [[BF_VALUE412]], 11
// CHK-CXX-NEXT:    [[BF_CLEAR414:%.*]] = and i32 [[BF_LOAD411]], -33552385
// CHK-CXX-NEXT:    [[BF_SET415:%.*]] = or i32 [[BF_CLEAR414]], [[BF_SHL413]]
// CHK-CXX-NEXT:    store i32 [[BF_SET415]], i32* [[ATOMIC_TEMP410]], align 4
// CHK-CXX-NEXT:    [[TMP174:%.*]] = load i32, i32* [[ATOMIC_TEMP410]], align 4
// CHK-CXX-NEXT:    [[TMP175:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0), i32 [[TMP173]], i32 [[TMP174]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP176]] = extractvalue { i32, i1 } [[TMP175]], 0
// CHK-CXX-NEXT:    [[TMP177:%.*]] = extractvalue { i32, i1 } [[TMP175]], 1
// CHK-CXX-NEXT:    br i1 [[TMP177]], label [[ATOMIC_UPD_EXIT416:%.*]], label [[ATOMIC_CMP417]]
// CHK-CXX:       atomic_upd_exit416:
// CHK-CXX-NEXT:    store i32 [[TMP171]], i32* [[ATMP401]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT424]]
// CHK-CXX:       atomic_cmp417:
// CHK-CXX-NEXT:    store i32 [[TMP176]], i32* [[ATOMIC_TEMP418]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD419:%.*]] = load i32, i32* [[ATOMIC_TEMP418]], align 4
// CHK-CXX-NEXT:    [[BF_SHL420:%.*]] = shl i32 [[BF_LOAD419]], 7
// CHK-CXX-NEXT:    [[BF_ASHR421:%.*]] = ashr i32 [[BF_SHL420]], 18
// CHK-CXX-NEXT:    store i32 [[BF_ASHR421]], i32* [[ATMP401]], align 4
// CHK-CXX-NEXT:    [[CMP422:%.*]] = icmp eq i32 [[BF_ASHR421]], [[TMP172]]
// CHK-CXX-NEXT:    [[FROMBOOL423:%.*]] = zext i1 [[CMP422]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL423]], i8* [[ATMP407]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP422]], label [[ATOMIC_CONT409]], label [[ATOMIC_EXIT424]]
// CHK-CXX:       atomic_exit424:
// CHK-CXX-NEXT:    [[TMP178:%.*]] = load i32, i32* [[ATMP401]], align 4
// CHK-CXX-NEXT:    [[TMP179:%.*]] = load i8, i8* [[ATMP407]], align 1
// CHK-CXX-NEXT:    [[TMP180:%.*]] = trunc i8 [[TMP179]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP180]], label [[ATOMIC_CAPTURE_CONT426:%.*]], label [[ATOMIC_CAPTURE425:%.*]]
// CHK-CXX:       atomic_capture425:
// CHK-CXX-NEXT:    store i32 [[TMP178]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT426]]
// CHK-CXX:       atomic_capture_cont426:
// CHK-CXX-NEXT:    [[TMP181:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP182:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD427:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD427]], i32* [[ATOMIC_TEMP429]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD430:%.*]] = load i32, i32* [[ATOMIC_TEMP429]], align 4
// CHK-CXX-NEXT:    [[BF_SHL431:%.*]] = shl i32 [[BF_LOAD430]], 7
// CHK-CXX-NEXT:    [[BF_ASHR432:%.*]] = ashr i32 [[BF_SHL431]], 18
// CHK-CXX-NEXT:    store i32 [[BF_ASHR432]], i32* [[ATMP428]], align 4
// CHK-CXX-NEXT:    [[CMP433:%.*]] = icmp eq i32 [[BF_ASHR432]], [[TMP182]]
// CHK-CXX-NEXT:    [[FROMBOOL435:%.*]] = zext i1 [[CMP433]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL435]], i8* [[ATMP434]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP433]], label [[ATOMIC_CONT436:%.*]], label [[ATOMIC_EXIT450:%.*]]
// CHK-CXX:       atomic_cont436:
// CHK-CXX-NEXT:    [[TMP183:%.*]] = phi i32 [ [[ATOMIC_LOAD427]], [[ATOMIC_CAPTURE_CONT426]] ], [ [[TMP186:%.*]], [[ATOMIC_CMP443:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP183]], i32* [[ATOMIC_TEMP437]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD438:%.*]] = load i32, i32* [[ATOMIC_TEMP437]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE439:%.*]] = and i32 [[TMP181]], 16383
// CHK-CXX-NEXT:    [[BF_SHL440:%.*]] = shl i32 [[BF_VALUE439]], 11
// CHK-CXX-NEXT:    [[BF_CLEAR441:%.*]] = and i32 [[BF_LOAD438]], -33552385
// CHK-CXX-NEXT:    [[BF_SET442:%.*]] = or i32 [[BF_CLEAR441]], [[BF_SHL440]]
// CHK-CXX-NEXT:    store i32 [[BF_SET442]], i32* [[ATOMIC_TEMP437]], align 4
// CHK-CXX-NEXT:    [[TMP184:%.*]] = load i32, i32* [[ATOMIC_TEMP437]], align 4
// CHK-CXX-NEXT:    [[TMP185:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0), i32 [[TMP183]], i32 [[TMP184]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP186]] = extractvalue { i32, i1 } [[TMP185]], 0
// CHK-CXX-NEXT:    [[TMP187:%.*]] = extractvalue { i32, i1 } [[TMP185]], 1
// CHK-CXX-NEXT:    br i1 [[TMP187]], label [[ATOMIC_EXIT450]], label [[ATOMIC_CMP443]]
// CHK-CXX:       atomic_cmp443:
// CHK-CXX-NEXT:    store i32 [[TMP186]], i32* [[ATOMIC_TEMP444]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD445:%.*]] = load i32, i32* [[ATOMIC_TEMP444]], align 4
// CHK-CXX-NEXT:    [[BF_SHL446:%.*]] = shl i32 [[BF_LOAD445]], 7
// CHK-CXX-NEXT:    [[BF_ASHR447:%.*]] = ashr i32 [[BF_SHL446]], 18
// CHK-CXX-NEXT:    store i32 [[BF_ASHR447]], i32* [[ATMP428]], align 4
// CHK-CXX-NEXT:    [[CMP448:%.*]] = icmp eq i32 [[BF_ASHR447]], [[TMP182]]
// CHK-CXX-NEXT:    [[FROMBOOL449:%.*]] = zext i1 [[CMP448]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL449]], i8* [[ATMP434]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP448]], label [[ATOMIC_CONT436]], label [[ATOMIC_EXIT450]]
// CHK-CXX:       atomic_exit450:
// CHK-CXX-NEXT:    [[TMP188:%.*]] = load i32, i32* [[ATMP428]], align 4
// CHK-CXX-NEXT:    [[TMP189:%.*]] = load i8, i8* [[ATMP434]], align 1
// CHK-CXX-NEXT:    [[CONV451:%.*]] = zext i8 [[TMP189]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV451]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP190:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP191:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD452:%.*]] = load atomic i32, i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0) monotonic, align 4
// CHK-CXX-NEXT:    store i32 [[ATOMIC_LOAD452]], i32* [[ATOMIC_TEMP454]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD455:%.*]] = load i32, i32* [[ATOMIC_TEMP454]], align 4
// CHK-CXX-NEXT:    [[BF_SHL456:%.*]] = shl i32 [[BF_LOAD455]], 7
// CHK-CXX-NEXT:    [[BF_ASHR457:%.*]] = ashr i32 [[BF_SHL456]], 18
// CHK-CXX-NEXT:    store i32 [[BF_ASHR457]], i32* [[ATMP453]], align 4
// CHK-CXX-NEXT:    [[CMP458:%.*]] = icmp eq i32 [[BF_ASHR457]], [[TMP191]]
// CHK-CXX-NEXT:    [[FROMBOOL460:%.*]] = zext i1 [[CMP458]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL460]], i8* [[ATMP459]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP458]], label [[ATOMIC_CONT461:%.*]], label [[ATOMIC_EXIT475:%.*]]
// CHK-CXX:       atomic_cont461:
// CHK-CXX-NEXT:    [[TMP192:%.*]] = phi i32 [ [[ATOMIC_LOAD452]], [[ATOMIC_EXIT450]] ], [ [[TMP195:%.*]], [[ATOMIC_CMP468:%.*]] ]
// CHK-CXX-NEXT:    store i32 [[TMP192]], i32* [[ATOMIC_TEMP462]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD463:%.*]] = load i32, i32* [[ATOMIC_TEMP462]], align 4
// CHK-CXX-NEXT:    [[BF_VALUE464:%.*]] = and i32 [[TMP190]], 16383
// CHK-CXX-NEXT:    [[BF_SHL465:%.*]] = shl i32 [[BF_VALUE464]], 11
// CHK-CXX-NEXT:    [[BF_CLEAR466:%.*]] = and i32 [[BF_LOAD463]], -33552385
// CHK-CXX-NEXT:    [[BF_SET467:%.*]] = or i32 [[BF_CLEAR466]], [[BF_SHL465]]
// CHK-CXX-NEXT:    store i32 [[BF_SET467]], i32* [[ATOMIC_TEMP462]], align 4
// CHK-CXX-NEXT:    [[TMP193:%.*]] = load i32, i32* [[ATOMIC_TEMP462]], align 4
// CHK-CXX-NEXT:    [[TMP194:%.*]] = cmpxchg i32* getelementptr inbounds ([[STRUCT_BITFIELDS3]], %struct.BitFields3* @bfx3, i32 0, i32 0), i32 [[TMP192]], i32 [[TMP193]] monotonic monotonic, align 4
// CHK-CXX-NEXT:    [[TMP195]] = extractvalue { i32, i1 } [[TMP194]], 0
// CHK-CXX-NEXT:    [[TMP196:%.*]] = extractvalue { i32, i1 } [[TMP194]], 1
// CHK-CXX-NEXT:    br i1 [[TMP196]], label [[ATOMIC_EXIT475]], label [[ATOMIC_CMP468]]
// CHK-CXX:       atomic_cmp468:
// CHK-CXX-NEXT:    store i32 [[TMP195]], i32* [[ATOMIC_TEMP469]], align 4
// CHK-CXX-NEXT:    [[BF_LOAD470:%.*]] = load i32, i32* [[ATOMIC_TEMP469]], align 4
// CHK-CXX-NEXT:    [[BF_SHL471:%.*]] = shl i32 [[BF_LOAD470]], 7
// CHK-CXX-NEXT:    [[BF_ASHR472:%.*]] = ashr i32 [[BF_SHL471]], 18
// CHK-CXX-NEXT:    store i32 [[BF_ASHR472]], i32* [[ATMP453]], align 4
// CHK-CXX-NEXT:    [[CMP473:%.*]] = icmp eq i32 [[BF_ASHR472]], [[TMP191]]
// CHK-CXX-NEXT:    [[FROMBOOL474:%.*]] = zext i1 [[CMP473]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL474]], i8* [[ATMP459]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP473]], label [[ATOMIC_CONT461]], label [[ATOMIC_EXIT475]]
// CHK-CXX:       atomic_exit475:
// CHK-CXX-NEXT:    [[TMP197:%.*]] = load i32, i32* [[ATMP453]], align 4
// CHK-CXX-NEXT:    [[TMP198:%.*]] = load i8, i8* [[ATMP459]], align 1
// CHK-CXX-NEXT:    [[CONV476:%.*]] = zext i8 [[TMP198]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV476]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP199:%.*]] = trunc i8 [[TMP198]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP199]], label [[ATOMIC_CAPTURE_CONT478:%.*]], label [[ATOMIC_CAPTURE477:%.*]]
// CHK-CXX:       atomic_capture477:
// CHK-CXX-NEXT:    store i32 [[TMP197]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT478]]
// CHK-CXX:       atomic_capture_cont478:
// CHK-CXX-NEXT:    [[TMP200:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD479:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD479]], i64* [[ATOMIC_TEMP481]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD482:%.*]] = load i64, i64* [[ATOMIC_TEMP481]], align 8
// CHK-CXX-NEXT:    [[BF_SHL483:%.*]] = shl i64 [[BF_LOAD482]], 47
// CHK-CXX-NEXT:    [[BF_ASHR484:%.*]] = ashr i64 [[BF_SHL483]], 63
// CHK-CXX-NEXT:    [[BF_CAST485:%.*]] = trunc i64 [[BF_ASHR484]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST485]], i32* [[ATMP480]], align 4
// CHK-CXX-NEXT:    [[CMP486:%.*]] = icmp slt i32 [[BF_CAST485]], [[TMP200]]
// CHK-CXX-NEXT:    [[FROMBOOL488:%.*]] = zext i1 [[CMP486]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL488]], i8* [[ATMP487]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP486]], label [[ATOMIC_CONT489:%.*]], label [[ATOMIC_EXIT504:%.*]]
// CHK-CXX:       atomic_cont489:
// CHK-CXX-NEXT:    [[TMP201:%.*]] = phi i64 [ [[ATOMIC_LOAD479]], [[ATOMIC_CAPTURE_CONT478]] ], [ [[TMP205:%.*]], [[ATOMIC_CMP496:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP201]], i64* [[ATOMIC_TEMP490]], align 8
// CHK-CXX-NEXT:    [[TMP202:%.*]] = zext i32 [[TMP200]] to i64
// CHK-CXX-NEXT:    [[BF_LOAD491:%.*]] = load i64, i64* [[ATOMIC_TEMP490]], align 8
// CHK-CXX-NEXT:    [[BF_VALUE492:%.*]] = and i64 [[TMP202]], 1
// CHK-CXX-NEXT:    [[BF_SHL493:%.*]] = shl i64 [[BF_VALUE492]], 16
// CHK-CXX-NEXT:    [[BF_CLEAR494:%.*]] = and i64 [[BF_LOAD491]], -65537
// CHK-CXX-NEXT:    [[BF_SET495:%.*]] = or i64 [[BF_CLEAR494]], [[BF_SHL493]]
// CHK-CXX-NEXT:    store i64 [[BF_SET495]], i64* [[ATOMIC_TEMP490]], align 8
// CHK-CXX-NEXT:    [[TMP203:%.*]] = load i64, i64* [[ATOMIC_TEMP490]], align 8
// CHK-CXX-NEXT:    [[TMP204:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP201]], i64 [[TMP203]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP205]] = extractvalue { i64, i1 } [[TMP204]], 0
// CHK-CXX-NEXT:    [[TMP206:%.*]] = extractvalue { i64, i1 } [[TMP204]], 1
// CHK-CXX-NEXT:    br i1 [[TMP206]], label [[ATOMIC_EXIT504]], label [[ATOMIC_CMP496]]
// CHK-CXX:       atomic_cmp496:
// CHK-CXX-NEXT:    store i64 [[TMP205]], i64* [[ATOMIC_TEMP497]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD498:%.*]] = load i64, i64* [[ATOMIC_TEMP497]], align 8
// CHK-CXX-NEXT:    [[BF_SHL499:%.*]] = shl i64 [[BF_LOAD498]], 47
// CHK-CXX-NEXT:    [[BF_ASHR500:%.*]] = ashr i64 [[BF_SHL499]], 63
// CHK-CXX-NEXT:    [[BF_CAST501:%.*]] = trunc i64 [[BF_ASHR500]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST501]], i32* [[ATMP480]], align 4
// CHK-CXX-NEXT:    [[CMP502:%.*]] = icmp slt i32 [[BF_CAST501]], [[TMP200]]
// CHK-CXX-NEXT:    [[FROMBOOL503:%.*]] = zext i1 [[CMP502]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL503]], i8* [[ATMP487]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP502]], label [[ATOMIC_CONT489]], label [[ATOMIC_EXIT504]]
// CHK-CXX:       atomic_exit504:
// CHK-CXX-NEXT:    [[TMP207:%.*]] = load i32, i32* [[ATMP480]], align 4
// CHK-CXX-NEXT:    [[TMP208:%.*]] = load i8, i8* [[ATMP487]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP207]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP209:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD505:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD505]], i64* [[ATOMIC_TEMP507]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD508:%.*]] = load i64, i64* [[ATOMIC_TEMP507]], align 8
// CHK-CXX-NEXT:    [[BF_SHL509:%.*]] = shl i64 [[BF_LOAD508]], 47
// CHK-CXX-NEXT:    [[BF_ASHR510:%.*]] = ashr i64 [[BF_SHL509]], 63
// CHK-CXX-NEXT:    [[BF_CAST511:%.*]] = trunc i64 [[BF_ASHR510]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST511]], i32* [[ATMP506]], align 4
// CHK-CXX-NEXT:    [[CMP512:%.*]] = icmp slt i32 [[BF_CAST511]], [[TMP209]]
// CHK-CXX-NEXT:    [[FROMBOOL514:%.*]] = zext i1 [[CMP512]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL514]], i8* [[ATMP513]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP512]], label [[ATOMIC_CONT515:%.*]], label [[ATOMIC_EXIT531:%.*]]
// CHK-CXX:       atomic_cont515:
// CHK-CXX-NEXT:    [[TMP210:%.*]] = phi i64 [ [[ATOMIC_LOAD505]], [[ATOMIC_EXIT504]] ], [ [[TMP214:%.*]], [[ATOMIC_CMP523:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP210]], i64* [[ATOMIC_TEMP516]], align 8
// CHK-CXX-NEXT:    [[TMP211:%.*]] = zext i32 [[TMP209]] to i64
// CHK-CXX-NEXT:    [[BF_LOAD517:%.*]] = load i64, i64* [[ATOMIC_TEMP516]], align 8
// CHK-CXX-NEXT:    [[BF_VALUE518:%.*]] = and i64 [[TMP211]], 1
// CHK-CXX-NEXT:    [[BF_SHL519:%.*]] = shl i64 [[BF_VALUE518]], 16
// CHK-CXX-NEXT:    [[BF_CLEAR520:%.*]] = and i64 [[BF_LOAD517]], -65537
// CHK-CXX-NEXT:    [[BF_SET521:%.*]] = or i64 [[BF_CLEAR520]], [[BF_SHL519]]
// CHK-CXX-NEXT:    store i64 [[BF_SET521]], i64* [[ATOMIC_TEMP516]], align 8
// CHK-CXX-NEXT:    [[TMP212:%.*]] = load i64, i64* [[ATOMIC_TEMP516]], align 8
// CHK-CXX-NEXT:    [[TMP213:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP210]], i64 [[TMP212]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP214]] = extractvalue { i64, i1 } [[TMP213]], 0
// CHK-CXX-NEXT:    [[TMP215:%.*]] = extractvalue { i64, i1 } [[TMP213]], 1
// CHK-CXX-NEXT:    br i1 [[TMP215]], label [[ATOMIC_UPD_EXIT522:%.*]], label [[ATOMIC_CMP523]]
// CHK-CXX:       atomic_upd_exit522:
// CHK-CXX-NEXT:    store i32 [[TMP209]], i32* [[ATMP506]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT531]]
// CHK-CXX:       atomic_cmp523:
// CHK-CXX-NEXT:    store i64 [[TMP214]], i64* [[ATOMIC_TEMP524]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD525:%.*]] = load i64, i64* [[ATOMIC_TEMP524]], align 8
// CHK-CXX-NEXT:    [[BF_SHL526:%.*]] = shl i64 [[BF_LOAD525]], 47
// CHK-CXX-NEXT:    [[BF_ASHR527:%.*]] = ashr i64 [[BF_SHL526]], 63
// CHK-CXX-NEXT:    [[BF_CAST528:%.*]] = trunc i64 [[BF_ASHR527]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST528]], i32* [[ATMP506]], align 4
// CHK-CXX-NEXT:    [[CMP529:%.*]] = icmp slt i32 [[BF_CAST528]], [[TMP209]]
// CHK-CXX-NEXT:    [[FROMBOOL530:%.*]] = zext i1 [[CMP529]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL530]], i8* [[ATMP513]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP529]], label [[ATOMIC_CONT515]], label [[ATOMIC_EXIT531]]
// CHK-CXX:       atomic_exit531:
// CHK-CXX-NEXT:    [[TMP216:%.*]] = load i32, i32* [[ATMP506]], align 4
// CHK-CXX-NEXT:    [[TMP217:%.*]] = load i8, i8* [[ATMP513]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP216]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP218:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP219:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD532:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD532]], i64* [[ATOMIC_TEMP534]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD535:%.*]] = load i64, i64* [[ATOMIC_TEMP534]], align 8
// CHK-CXX-NEXT:    [[BF_SHL536:%.*]] = shl i64 [[BF_LOAD535]], 47
// CHK-CXX-NEXT:    [[BF_ASHR537:%.*]] = ashr i64 [[BF_SHL536]], 63
// CHK-CXX-NEXT:    [[BF_CAST538:%.*]] = trunc i64 [[BF_ASHR537]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST538]], i32* [[ATMP533]], align 4
// CHK-CXX-NEXT:    [[CMP539:%.*]] = icmp eq i32 [[BF_CAST538]], [[TMP219]]
// CHK-CXX-NEXT:    [[FROMBOOL541:%.*]] = zext i1 [[CMP539]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL541]], i8* [[ATMP540]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP539]], label [[ATOMIC_CONT542:%.*]], label [[ATOMIC_EXIT558:%.*]]
// CHK-CXX:       atomic_cont542:
// CHK-CXX-NEXT:    [[TMP220:%.*]] = phi i64 [ [[ATOMIC_LOAD532]], [[ATOMIC_EXIT531]] ], [ [[TMP224:%.*]], [[ATOMIC_CMP550:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP220]], i64* [[ATOMIC_TEMP543]], align 8
// CHK-CXX-NEXT:    [[TMP221:%.*]] = zext i32 [[TMP218]] to i64
// CHK-CXX-NEXT:    [[BF_LOAD544:%.*]] = load i64, i64* [[ATOMIC_TEMP543]], align 8
// CHK-CXX-NEXT:    [[BF_VALUE545:%.*]] = and i64 [[TMP221]], 1
// CHK-CXX-NEXT:    [[BF_SHL546:%.*]] = shl i64 [[BF_VALUE545]], 16
// CHK-CXX-NEXT:    [[BF_CLEAR547:%.*]] = and i64 [[BF_LOAD544]], -65537
// CHK-CXX-NEXT:    [[BF_SET548:%.*]] = or i64 [[BF_CLEAR547]], [[BF_SHL546]]
// CHK-CXX-NEXT:    store i64 [[BF_SET548]], i64* [[ATOMIC_TEMP543]], align 8
// CHK-CXX-NEXT:    [[TMP222:%.*]] = load i64, i64* [[ATOMIC_TEMP543]], align 8
// CHK-CXX-NEXT:    [[TMP223:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP220]], i64 [[TMP222]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP224]] = extractvalue { i64, i1 } [[TMP223]], 0
// CHK-CXX-NEXT:    [[TMP225:%.*]] = extractvalue { i64, i1 } [[TMP223]], 1
// CHK-CXX-NEXT:    br i1 [[TMP225]], label [[ATOMIC_UPD_EXIT549:%.*]], label [[ATOMIC_CMP550]]
// CHK-CXX:       atomic_upd_exit549:
// CHK-CXX-NEXT:    store i32 [[TMP218]], i32* [[ATMP533]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT558]]
// CHK-CXX:       atomic_cmp550:
// CHK-CXX-NEXT:    store i64 [[TMP224]], i64* [[ATOMIC_TEMP551]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD552:%.*]] = load i64, i64* [[ATOMIC_TEMP551]], align 8
// CHK-CXX-NEXT:    [[BF_SHL553:%.*]] = shl i64 [[BF_LOAD552]], 47
// CHK-CXX-NEXT:    [[BF_ASHR554:%.*]] = ashr i64 [[BF_SHL553]], 63
// CHK-CXX-NEXT:    [[BF_CAST555:%.*]] = trunc i64 [[BF_ASHR554]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST555]], i32* [[ATMP533]], align 4
// CHK-CXX-NEXT:    [[CMP556:%.*]] = icmp eq i32 [[BF_CAST555]], [[TMP219]]
// CHK-CXX-NEXT:    [[FROMBOOL557:%.*]] = zext i1 [[CMP556]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL557]], i8* [[ATMP540]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP556]], label [[ATOMIC_CONT542]], label [[ATOMIC_EXIT558]]
// CHK-CXX:       atomic_exit558:
// CHK-CXX-NEXT:    [[TMP226:%.*]] = load i32, i32* [[ATMP533]], align 4
// CHK-CXX-NEXT:    [[TMP227:%.*]] = load i8, i8* [[ATMP540]], align 1
// CHK-CXX-NEXT:    [[TMP228:%.*]] = trunc i8 [[TMP227]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP228]], label [[ATOMIC_CAPTURE_CONT560:%.*]], label [[ATOMIC_CAPTURE559:%.*]]
// CHK-CXX:       atomic_capture559:
// CHK-CXX-NEXT:    store i32 [[TMP226]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT560]]
// CHK-CXX:       atomic_capture_cont560:
// CHK-CXX-NEXT:    [[TMP229:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP230:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD561:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD561]], i64* [[ATOMIC_TEMP563]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD564:%.*]] = load i64, i64* [[ATOMIC_TEMP563]], align 8
// CHK-CXX-NEXT:    [[BF_SHL565:%.*]] = shl i64 [[BF_LOAD564]], 47
// CHK-CXX-NEXT:    [[BF_ASHR566:%.*]] = ashr i64 [[BF_SHL565]], 63
// CHK-CXX-NEXT:    [[BF_CAST567:%.*]] = trunc i64 [[BF_ASHR566]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST567]], i32* [[ATMP562]], align 4
// CHK-CXX-NEXT:    [[CMP568:%.*]] = icmp eq i32 [[BF_CAST567]], [[TMP230]]
// CHK-CXX-NEXT:    [[FROMBOOL570:%.*]] = zext i1 [[CMP568]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL570]], i8* [[ATMP569]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP568]], label [[ATOMIC_CONT571:%.*]], label [[ATOMIC_EXIT586:%.*]]
// CHK-CXX:       atomic_cont571:
// CHK-CXX-NEXT:    [[TMP231:%.*]] = phi i64 [ [[ATOMIC_LOAD561]], [[ATOMIC_CAPTURE_CONT560]] ], [ [[TMP235:%.*]], [[ATOMIC_CMP578:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP231]], i64* [[ATOMIC_TEMP572]], align 8
// CHK-CXX-NEXT:    [[TMP232:%.*]] = zext i32 [[TMP229]] to i64
// CHK-CXX-NEXT:    [[BF_LOAD573:%.*]] = load i64, i64* [[ATOMIC_TEMP572]], align 8
// CHK-CXX-NEXT:    [[BF_VALUE574:%.*]] = and i64 [[TMP232]], 1
// CHK-CXX-NEXT:    [[BF_SHL575:%.*]] = shl i64 [[BF_VALUE574]], 16
// CHK-CXX-NEXT:    [[BF_CLEAR576:%.*]] = and i64 [[BF_LOAD573]], -65537
// CHK-CXX-NEXT:    [[BF_SET577:%.*]] = or i64 [[BF_CLEAR576]], [[BF_SHL575]]
// CHK-CXX-NEXT:    store i64 [[BF_SET577]], i64* [[ATOMIC_TEMP572]], align 8
// CHK-CXX-NEXT:    [[TMP233:%.*]] = load i64, i64* [[ATOMIC_TEMP572]], align 8
// CHK-CXX-NEXT:    [[TMP234:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP231]], i64 [[TMP233]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP235]] = extractvalue { i64, i1 } [[TMP234]], 0
// CHK-CXX-NEXT:    [[TMP236:%.*]] = extractvalue { i64, i1 } [[TMP234]], 1
// CHK-CXX-NEXT:    br i1 [[TMP236]], label [[ATOMIC_EXIT586]], label [[ATOMIC_CMP578]]
// CHK-CXX:       atomic_cmp578:
// CHK-CXX-NEXT:    store i64 [[TMP235]], i64* [[ATOMIC_TEMP579]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD580:%.*]] = load i64, i64* [[ATOMIC_TEMP579]], align 8
// CHK-CXX-NEXT:    [[BF_SHL581:%.*]] = shl i64 [[BF_LOAD580]], 47
// CHK-CXX-NEXT:    [[BF_ASHR582:%.*]] = ashr i64 [[BF_SHL581]], 63
// CHK-CXX-NEXT:    [[BF_CAST583:%.*]] = trunc i64 [[BF_ASHR582]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST583]], i32* [[ATMP562]], align 4
// CHK-CXX-NEXT:    [[CMP584:%.*]] = icmp eq i32 [[BF_CAST583]], [[TMP230]]
// CHK-CXX-NEXT:    [[FROMBOOL585:%.*]] = zext i1 [[CMP584]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL585]], i8* [[ATMP569]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP584]], label [[ATOMIC_CONT571]], label [[ATOMIC_EXIT586]]
// CHK-CXX:       atomic_exit586:
// CHK-CXX-NEXT:    [[TMP237:%.*]] = load i32, i32* [[ATMP562]], align 4
// CHK-CXX-NEXT:    [[TMP238:%.*]] = load i8, i8* [[ATMP569]], align 1
// CHK-CXX-NEXT:    [[CONV587:%.*]] = zext i8 [[TMP238]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV587]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP239:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP240:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD588:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD588]], i64* [[ATOMIC_TEMP590]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD591:%.*]] = load i64, i64* [[ATOMIC_TEMP590]], align 8
// CHK-CXX-NEXT:    [[BF_SHL592:%.*]] = shl i64 [[BF_LOAD591]], 47
// CHK-CXX-NEXT:    [[BF_ASHR593:%.*]] = ashr i64 [[BF_SHL592]], 63
// CHK-CXX-NEXT:    [[BF_CAST594:%.*]] = trunc i64 [[BF_ASHR593]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST594]], i32* [[ATMP589]], align 4
// CHK-CXX-NEXT:    [[CMP595:%.*]] = icmp eq i32 [[BF_CAST594]], [[TMP240]]
// CHK-CXX-NEXT:    [[FROMBOOL597:%.*]] = zext i1 [[CMP595]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL597]], i8* [[ATMP596]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP595]], label [[ATOMIC_CONT598:%.*]], label [[ATOMIC_EXIT613:%.*]]
// CHK-CXX:       atomic_cont598:
// CHK-CXX-NEXT:    [[TMP241:%.*]] = phi i64 [ [[ATOMIC_LOAD588]], [[ATOMIC_EXIT586]] ], [ [[TMP245:%.*]], [[ATOMIC_CMP605:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP241]], i64* [[ATOMIC_TEMP599]], align 8
// CHK-CXX-NEXT:    [[TMP242:%.*]] = zext i32 [[TMP239]] to i64
// CHK-CXX-NEXT:    [[BF_LOAD600:%.*]] = load i64, i64* [[ATOMIC_TEMP599]], align 8
// CHK-CXX-NEXT:    [[BF_VALUE601:%.*]] = and i64 [[TMP242]], 1
// CHK-CXX-NEXT:    [[BF_SHL602:%.*]] = shl i64 [[BF_VALUE601]], 16
// CHK-CXX-NEXT:    [[BF_CLEAR603:%.*]] = and i64 [[BF_LOAD600]], -65537
// CHK-CXX-NEXT:    [[BF_SET604:%.*]] = or i64 [[BF_CLEAR603]], [[BF_SHL602]]
// CHK-CXX-NEXT:    store i64 [[BF_SET604]], i64* [[ATOMIC_TEMP599]], align 8
// CHK-CXX-NEXT:    [[TMP243:%.*]] = load i64, i64* [[ATOMIC_TEMP599]], align 8
// CHK-CXX-NEXT:    [[TMP244:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP241]], i64 [[TMP243]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP245]] = extractvalue { i64, i1 } [[TMP244]], 0
// CHK-CXX-NEXT:    [[TMP246:%.*]] = extractvalue { i64, i1 } [[TMP244]], 1
// CHK-CXX-NEXT:    br i1 [[TMP246]], label [[ATOMIC_EXIT613]], label [[ATOMIC_CMP605]]
// CHK-CXX:       atomic_cmp605:
// CHK-CXX-NEXT:    store i64 [[TMP245]], i64* [[ATOMIC_TEMP606]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD607:%.*]] = load i64, i64* [[ATOMIC_TEMP606]], align 8
// CHK-CXX-NEXT:    [[BF_SHL608:%.*]] = shl i64 [[BF_LOAD607]], 47
// CHK-CXX-NEXT:    [[BF_ASHR609:%.*]] = ashr i64 [[BF_SHL608]], 63
// CHK-CXX-NEXT:    [[BF_CAST610:%.*]] = trunc i64 [[BF_ASHR609]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST610]], i32* [[ATMP589]], align 4
// CHK-CXX-NEXT:    [[CMP611:%.*]] = icmp eq i32 [[BF_CAST610]], [[TMP240]]
// CHK-CXX-NEXT:    [[FROMBOOL612:%.*]] = zext i1 [[CMP611]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL612]], i8* [[ATMP596]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP611]], label [[ATOMIC_CONT598]], label [[ATOMIC_EXIT613]]
// CHK-CXX:       atomic_exit613:
// CHK-CXX-NEXT:    [[TMP247:%.*]] = load i32, i32* [[ATMP589]], align 4
// CHK-CXX-NEXT:    [[TMP248:%.*]] = load i8, i8* [[ATMP596]], align 1
// CHK-CXX-NEXT:    [[CONV614:%.*]] = zext i8 [[TMP248]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV614]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP249:%.*]] = trunc i8 [[TMP248]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP249]], label [[ATOMIC_CAPTURE_CONT616:%.*]], label [[ATOMIC_CAPTURE615:%.*]]
// CHK-CXX:       atomic_capture615:
// CHK-CXX-NEXT:    store i32 [[TMP247]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT616]]
// CHK-CXX:       atomic_capture_cont616:
// CHK-CXX-NEXT:    [[TMP250:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[CONV617:%.*]] = sext i32 [[TMP250]] to i64
// CHK-CXX-NEXT:    [[ATOMIC_LOAD618:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD618]], i64* [[ATOMIC_TEMP620]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD621:%.*]] = load i64, i64* [[ATOMIC_TEMP620]], align 8
// CHK-CXX-NEXT:    [[BF_SHL622:%.*]] = shl i64 [[BF_LOAD621]], 40
// CHK-CXX-NEXT:    [[BF_ASHR623:%.*]] = ashr i64 [[BF_SHL622]], 57
// CHK-CXX-NEXT:    store i64 [[BF_ASHR623]], i64* [[ATMP619]], align 8
// CHK-CXX-NEXT:    [[CMP624:%.*]] = icmp slt i64 [[BF_ASHR623]], [[CONV617]]
// CHK-CXX-NEXT:    [[FROMBOOL626:%.*]] = zext i1 [[CMP624]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL626]], i8* [[ATMP625]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP624]], label [[ATOMIC_CONT627:%.*]], label [[ATOMIC_EXIT641:%.*]]
// CHK-CXX:       atomic_cont627:
// CHK-CXX-NEXT:    [[TMP251:%.*]] = phi i64 [ [[ATOMIC_LOAD618]], [[ATOMIC_CAPTURE_CONT616]] ], [ [[TMP254:%.*]], [[ATOMIC_CMP634:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP251]], i64* [[ATOMIC_TEMP628]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD629:%.*]] = load i64, i64* [[ATOMIC_TEMP628]], align 8
// CHK-CXX-NEXT:    [[BF_VALUE630:%.*]] = and i64 [[CONV617]], 127
// CHK-CXX-NEXT:    [[BF_SHL631:%.*]] = shl i64 [[BF_VALUE630]], 17
// CHK-CXX-NEXT:    [[BF_CLEAR632:%.*]] = and i64 [[BF_LOAD629]], -16646145
// CHK-CXX-NEXT:    [[BF_SET633:%.*]] = or i64 [[BF_CLEAR632]], [[BF_SHL631]]
// CHK-CXX-NEXT:    store i64 [[BF_SET633]], i64* [[ATOMIC_TEMP628]], align 8
// CHK-CXX-NEXT:    [[TMP252:%.*]] = load i64, i64* [[ATOMIC_TEMP628]], align 8
// CHK-CXX-NEXT:    [[TMP253:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP251]], i64 [[TMP252]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP254]] = extractvalue { i64, i1 } [[TMP253]], 0
// CHK-CXX-NEXT:    [[TMP255:%.*]] = extractvalue { i64, i1 } [[TMP253]], 1
// CHK-CXX-NEXT:    br i1 [[TMP255]], label [[ATOMIC_EXIT641]], label [[ATOMIC_CMP634]]
// CHK-CXX:       atomic_cmp634:
// CHK-CXX-NEXT:    store i64 [[TMP254]], i64* [[ATOMIC_TEMP635]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD636:%.*]] = load i64, i64* [[ATOMIC_TEMP635]], align 8
// CHK-CXX-NEXT:    [[BF_SHL637:%.*]] = shl i64 [[BF_LOAD636]], 40
// CHK-CXX-NEXT:    [[BF_ASHR638:%.*]] = ashr i64 [[BF_SHL637]], 57
// CHK-CXX-NEXT:    store i64 [[BF_ASHR638]], i64* [[ATMP619]], align 8
// CHK-CXX-NEXT:    [[CMP639:%.*]] = icmp slt i64 [[BF_ASHR638]], [[CONV617]]
// CHK-CXX-NEXT:    [[FROMBOOL640:%.*]] = zext i1 [[CMP639]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL640]], i8* [[ATMP625]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP639]], label [[ATOMIC_CONT627]], label [[ATOMIC_EXIT641]]
// CHK-CXX:       atomic_exit641:
// CHK-CXX-NEXT:    [[TMP256:%.*]] = load i64, i64* [[ATMP619]], align 8
// CHK-CXX-NEXT:    [[TMP257:%.*]] = load i8, i8* [[ATMP625]], align 1
// CHK-CXX-NEXT:    [[CONV642:%.*]] = trunc i64 [[TMP256]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV642]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP258:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[CONV643:%.*]] = sext i32 [[TMP258]] to i64
// CHK-CXX-NEXT:    [[ATOMIC_LOAD644:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD644]], i64* [[ATOMIC_TEMP646]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD647:%.*]] = load i64, i64* [[ATOMIC_TEMP646]], align 8
// CHK-CXX-NEXT:    [[BF_SHL648:%.*]] = shl i64 [[BF_LOAD647]], 40
// CHK-CXX-NEXT:    [[BF_ASHR649:%.*]] = ashr i64 [[BF_SHL648]], 57
// CHK-CXX-NEXT:    store i64 [[BF_ASHR649]], i64* [[ATMP645]], align 8
// CHK-CXX-NEXT:    [[CMP650:%.*]] = icmp slt i64 [[BF_ASHR649]], [[CONV643]]
// CHK-CXX-NEXT:    [[FROMBOOL652:%.*]] = zext i1 [[CMP650]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL652]], i8* [[ATMP651]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP650]], label [[ATOMIC_CONT653:%.*]], label [[ATOMIC_EXIT668:%.*]]
// CHK-CXX:       atomic_cont653:
// CHK-CXX-NEXT:    [[TMP259:%.*]] = phi i64 [ [[ATOMIC_LOAD644]], [[ATOMIC_EXIT641]] ], [ [[TMP262:%.*]], [[ATOMIC_CMP661:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP259]], i64* [[ATOMIC_TEMP654]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD655:%.*]] = load i64, i64* [[ATOMIC_TEMP654]], align 8
// CHK-CXX-NEXT:    [[BF_VALUE656:%.*]] = and i64 [[CONV643]], 127
// CHK-CXX-NEXT:    [[BF_SHL657:%.*]] = shl i64 [[BF_VALUE656]], 17
// CHK-CXX-NEXT:    [[BF_CLEAR658:%.*]] = and i64 [[BF_LOAD655]], -16646145
// CHK-CXX-NEXT:    [[BF_SET659:%.*]] = or i64 [[BF_CLEAR658]], [[BF_SHL657]]
// CHK-CXX-NEXT:    store i64 [[BF_SET659]], i64* [[ATOMIC_TEMP654]], align 8
// CHK-CXX-NEXT:    [[TMP260:%.*]] = load i64, i64* [[ATOMIC_TEMP654]], align 8
// CHK-CXX-NEXT:    [[TMP261:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP259]], i64 [[TMP260]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP262]] = extractvalue { i64, i1 } [[TMP261]], 0
// CHK-CXX-NEXT:    [[TMP263:%.*]] = extractvalue { i64, i1 } [[TMP261]], 1
// CHK-CXX-NEXT:    br i1 [[TMP263]], label [[ATOMIC_UPD_EXIT660:%.*]], label [[ATOMIC_CMP661]]
// CHK-CXX:       atomic_upd_exit660:
// CHK-CXX-NEXT:    store i64 [[CONV643]], i64* [[ATMP645]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT668]]
// CHK-CXX:       atomic_cmp661:
// CHK-CXX-NEXT:    store i64 [[TMP262]], i64* [[ATOMIC_TEMP662]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD663:%.*]] = load i64, i64* [[ATOMIC_TEMP662]], align 8
// CHK-CXX-NEXT:    [[BF_SHL664:%.*]] = shl i64 [[BF_LOAD663]], 40
// CHK-CXX-NEXT:    [[BF_ASHR665:%.*]] = ashr i64 [[BF_SHL664]], 57
// CHK-CXX-NEXT:    store i64 [[BF_ASHR665]], i64* [[ATMP645]], align 8
// CHK-CXX-NEXT:    [[CMP666:%.*]] = icmp slt i64 [[BF_ASHR665]], [[CONV643]]
// CHK-CXX-NEXT:    [[FROMBOOL667:%.*]] = zext i1 [[CMP666]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL667]], i8* [[ATMP651]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP666]], label [[ATOMIC_CONT653]], label [[ATOMIC_EXIT668]]
// CHK-CXX:       atomic_exit668:
// CHK-CXX-NEXT:    [[TMP264:%.*]] = load i64, i64* [[ATMP645]], align 8
// CHK-CXX-NEXT:    [[TMP265:%.*]] = load i8, i8* [[ATMP651]], align 1
// CHK-CXX-NEXT:    [[CONV669:%.*]] = trunc i64 [[TMP264]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV669]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP266:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[CONV670:%.*]] = sext i32 [[TMP266]] to i64
// CHK-CXX-NEXT:    [[TMP267:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[CONV671:%.*]] = sext i32 [[TMP267]] to i64
// CHK-CXX-NEXT:    [[ATOMIC_LOAD672:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD672]], i64* [[ATOMIC_TEMP674]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD675:%.*]] = load i64, i64* [[ATOMIC_TEMP674]], align 8
// CHK-CXX-NEXT:    [[BF_SHL676:%.*]] = shl i64 [[BF_LOAD675]], 40
// CHK-CXX-NEXT:    [[BF_ASHR677:%.*]] = ashr i64 [[BF_SHL676]], 57
// CHK-CXX-NEXT:    store i64 [[BF_ASHR677]], i64* [[ATMP673]], align 8
// CHK-CXX-NEXT:    [[CMP678:%.*]] = icmp eq i64 [[BF_ASHR677]], [[CONV671]]
// CHK-CXX-NEXT:    [[FROMBOOL680:%.*]] = zext i1 [[CMP678]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL680]], i8* [[ATMP679]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP678]], label [[ATOMIC_CONT681:%.*]], label [[ATOMIC_EXIT696:%.*]]
// CHK-CXX:       atomic_cont681:
// CHK-CXX-NEXT:    [[TMP268:%.*]] = phi i64 [ [[ATOMIC_LOAD672]], [[ATOMIC_EXIT668]] ], [ [[TMP271:%.*]], [[ATOMIC_CMP689:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP268]], i64* [[ATOMIC_TEMP682]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD683:%.*]] = load i64, i64* [[ATOMIC_TEMP682]], align 8
// CHK-CXX-NEXT:    [[BF_VALUE684:%.*]] = and i64 [[CONV670]], 127
// CHK-CXX-NEXT:    [[BF_SHL685:%.*]] = shl i64 [[BF_VALUE684]], 17
// CHK-CXX-NEXT:    [[BF_CLEAR686:%.*]] = and i64 [[BF_LOAD683]], -16646145
// CHK-CXX-NEXT:    [[BF_SET687:%.*]] = or i64 [[BF_CLEAR686]], [[BF_SHL685]]
// CHK-CXX-NEXT:    store i64 [[BF_SET687]], i64* [[ATOMIC_TEMP682]], align 8
// CHK-CXX-NEXT:    [[TMP269:%.*]] = load i64, i64* [[ATOMIC_TEMP682]], align 8
// CHK-CXX-NEXT:    [[TMP270:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP268]], i64 [[TMP269]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP271]] = extractvalue { i64, i1 } [[TMP270]], 0
// CHK-CXX-NEXT:    [[TMP272:%.*]] = extractvalue { i64, i1 } [[TMP270]], 1
// CHK-CXX-NEXT:    br i1 [[TMP272]], label [[ATOMIC_UPD_EXIT688:%.*]], label [[ATOMIC_CMP689]]
// CHK-CXX:       atomic_upd_exit688:
// CHK-CXX-NEXT:    store i64 [[CONV670]], i64* [[ATMP673]], align 8
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT696]]
// CHK-CXX:       atomic_cmp689:
// CHK-CXX-NEXT:    store i64 [[TMP271]], i64* [[ATOMIC_TEMP690]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD691:%.*]] = load i64, i64* [[ATOMIC_TEMP690]], align 8
// CHK-CXX-NEXT:    [[BF_SHL692:%.*]] = shl i64 [[BF_LOAD691]], 40
// CHK-CXX-NEXT:    [[BF_ASHR693:%.*]] = ashr i64 [[BF_SHL692]], 57
// CHK-CXX-NEXT:    store i64 [[BF_ASHR693]], i64* [[ATMP673]], align 8
// CHK-CXX-NEXT:    [[CMP694:%.*]] = icmp eq i64 [[BF_ASHR693]], [[CONV671]]
// CHK-CXX-NEXT:    [[FROMBOOL695:%.*]] = zext i1 [[CMP694]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL695]], i8* [[ATMP679]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP694]], label [[ATOMIC_CONT681]], label [[ATOMIC_EXIT696]]
// CHK-CXX:       atomic_exit696:
// CHK-CXX-NEXT:    [[TMP273:%.*]] = load i64, i64* [[ATMP673]], align 8
// CHK-CXX-NEXT:    [[TMP274:%.*]] = load i8, i8* [[ATMP679]], align 1
// CHK-CXX-NEXT:    [[TMP275:%.*]] = trunc i8 [[TMP274]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP275]], label [[ATOMIC_CAPTURE_CONT699:%.*]], label [[ATOMIC_CAPTURE697:%.*]]
// CHK-CXX:       atomic_capture697:
// CHK-CXX-NEXT:    [[CONV698:%.*]] = trunc i64 [[TMP273]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV698]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT699]]
// CHK-CXX:       atomic_capture_cont699:
// CHK-CXX-NEXT:    [[TMP276:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[CONV700:%.*]] = sext i32 [[TMP276]] to i64
// CHK-CXX-NEXT:    [[TMP277:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[CONV701:%.*]] = sext i32 [[TMP277]] to i64
// CHK-CXX-NEXT:    [[ATOMIC_LOAD702:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD702]], i64* [[ATOMIC_TEMP704]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD705:%.*]] = load i64, i64* [[ATOMIC_TEMP704]], align 8
// CHK-CXX-NEXT:    [[BF_SHL706:%.*]] = shl i64 [[BF_LOAD705]], 40
// CHK-CXX-NEXT:    [[BF_ASHR707:%.*]] = ashr i64 [[BF_SHL706]], 57
// CHK-CXX-NEXT:    store i64 [[BF_ASHR707]], i64* [[ATMP703]], align 8
// CHK-CXX-NEXT:    [[CMP708:%.*]] = icmp eq i64 [[BF_ASHR707]], [[CONV701]]
// CHK-CXX-NEXT:    [[FROMBOOL710:%.*]] = zext i1 [[CMP708]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL710]], i8* [[ATMP709]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP708]], label [[ATOMIC_CONT711:%.*]], label [[ATOMIC_EXIT725:%.*]]
// CHK-CXX:       atomic_cont711:
// CHK-CXX-NEXT:    [[TMP278:%.*]] = phi i64 [ [[ATOMIC_LOAD702]], [[ATOMIC_CAPTURE_CONT699]] ], [ [[TMP281:%.*]], [[ATOMIC_CMP718:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP278]], i64* [[ATOMIC_TEMP712]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD713:%.*]] = load i64, i64* [[ATOMIC_TEMP712]], align 8
// CHK-CXX-NEXT:    [[BF_VALUE714:%.*]] = and i64 [[CONV700]], 127
// CHK-CXX-NEXT:    [[BF_SHL715:%.*]] = shl i64 [[BF_VALUE714]], 17
// CHK-CXX-NEXT:    [[BF_CLEAR716:%.*]] = and i64 [[BF_LOAD713]], -16646145
// CHK-CXX-NEXT:    [[BF_SET717:%.*]] = or i64 [[BF_CLEAR716]], [[BF_SHL715]]
// CHK-CXX-NEXT:    store i64 [[BF_SET717]], i64* [[ATOMIC_TEMP712]], align 8
// CHK-CXX-NEXT:    [[TMP279:%.*]] = load i64, i64* [[ATOMIC_TEMP712]], align 8
// CHK-CXX-NEXT:    [[TMP280:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP278]], i64 [[TMP279]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP281]] = extractvalue { i64, i1 } [[TMP280]], 0
// CHK-CXX-NEXT:    [[TMP282:%.*]] = extractvalue { i64, i1 } [[TMP280]], 1
// CHK-CXX-NEXT:    br i1 [[TMP282]], label [[ATOMIC_EXIT725]], label [[ATOMIC_CMP718]]
// CHK-CXX:       atomic_cmp718:
// CHK-CXX-NEXT:    store i64 [[TMP281]], i64* [[ATOMIC_TEMP719]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD720:%.*]] = load i64, i64* [[ATOMIC_TEMP719]], align 8
// CHK-CXX-NEXT:    [[BF_SHL721:%.*]] = shl i64 [[BF_LOAD720]], 40
// CHK-CXX-NEXT:    [[BF_ASHR722:%.*]] = ashr i64 [[BF_SHL721]], 57
// CHK-CXX-NEXT:    store i64 [[BF_ASHR722]], i64* [[ATMP703]], align 8
// CHK-CXX-NEXT:    [[CMP723:%.*]] = icmp eq i64 [[BF_ASHR722]], [[CONV701]]
// CHK-CXX-NEXT:    [[FROMBOOL724:%.*]] = zext i1 [[CMP723]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL724]], i8* [[ATMP709]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP723]], label [[ATOMIC_CONT711]], label [[ATOMIC_EXIT725]]
// CHK-CXX:       atomic_exit725:
// CHK-CXX-NEXT:    [[TMP283:%.*]] = load i64, i64* [[ATMP703]], align 8
// CHK-CXX-NEXT:    [[TMP284:%.*]] = load i8, i8* [[ATMP709]], align 1
// CHK-CXX-NEXT:    [[CONV726:%.*]] = zext i8 [[TMP284]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV726]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP285:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[CONV727:%.*]] = sext i32 [[TMP285]] to i64
// CHK-CXX-NEXT:    [[TMP286:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[CONV728:%.*]] = sext i32 [[TMP286]] to i64
// CHK-CXX-NEXT:    [[ATOMIC_LOAD729:%.*]] = load atomic i64, i64* bitcast (%struct.BitFields4* @bfx4 to i64*) monotonic, align 8
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD729]], i64* [[ATOMIC_TEMP731]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD732:%.*]] = load i64, i64* [[ATOMIC_TEMP731]], align 8
// CHK-CXX-NEXT:    [[BF_SHL733:%.*]] = shl i64 [[BF_LOAD732]], 40
// CHK-CXX-NEXT:    [[BF_ASHR734:%.*]] = ashr i64 [[BF_SHL733]], 57
// CHK-CXX-NEXT:    store i64 [[BF_ASHR734]], i64* [[ATMP730]], align 8
// CHK-CXX-NEXT:    [[CMP735:%.*]] = icmp eq i64 [[BF_ASHR734]], [[CONV728]]
// CHK-CXX-NEXT:    [[FROMBOOL737:%.*]] = zext i1 [[CMP735]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL737]], i8* [[ATMP736]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP735]], label [[ATOMIC_CONT738:%.*]], label [[ATOMIC_EXIT752:%.*]]
// CHK-CXX:       atomic_cont738:
// CHK-CXX-NEXT:    [[TMP287:%.*]] = phi i64 [ [[ATOMIC_LOAD729]], [[ATOMIC_EXIT725]] ], [ [[TMP290:%.*]], [[ATOMIC_CMP745:%.*]] ]
// CHK-CXX-NEXT:    store i64 [[TMP287]], i64* [[ATOMIC_TEMP739]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD740:%.*]] = load i64, i64* [[ATOMIC_TEMP739]], align 8
// CHK-CXX-NEXT:    [[BF_VALUE741:%.*]] = and i64 [[CONV727]], 127
// CHK-CXX-NEXT:    [[BF_SHL742:%.*]] = shl i64 [[BF_VALUE741]], 17
// CHK-CXX-NEXT:    [[BF_CLEAR743:%.*]] = and i64 [[BF_LOAD740]], -16646145
// CHK-CXX-NEXT:    [[BF_SET744:%.*]] = or i64 [[BF_CLEAR743]], [[BF_SHL742]]
// CHK-CXX-NEXT:    store i64 [[BF_SET744]], i64* [[ATOMIC_TEMP739]], align 8
// CHK-CXX-NEXT:    [[TMP288:%.*]] = load i64, i64* [[ATOMIC_TEMP739]], align 8
// CHK-CXX-NEXT:    [[TMP289:%.*]] = cmpxchg i64* bitcast (%struct.BitFields4* @bfx4 to i64*), i64 [[TMP287]], i64 [[TMP288]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP290]] = extractvalue { i64, i1 } [[TMP289]], 0
// CHK-CXX-NEXT:    [[TMP291:%.*]] = extractvalue { i64, i1 } [[TMP289]], 1
// CHK-CXX-NEXT:    br i1 [[TMP291]], label [[ATOMIC_EXIT752]], label [[ATOMIC_CMP745]]
// CHK-CXX:       atomic_cmp745:
// CHK-CXX-NEXT:    store i64 [[TMP290]], i64* [[ATOMIC_TEMP746]], align 8
// CHK-CXX-NEXT:    [[BF_LOAD747:%.*]] = load i64, i64* [[ATOMIC_TEMP746]], align 8
// CHK-CXX-NEXT:    [[BF_SHL748:%.*]] = shl i64 [[BF_LOAD747]], 40
// CHK-CXX-NEXT:    [[BF_ASHR749:%.*]] = ashr i64 [[BF_SHL748]], 57
// CHK-CXX-NEXT:    store i64 [[BF_ASHR749]], i64* [[ATMP730]], align 8
// CHK-CXX-NEXT:    [[CMP750:%.*]] = icmp eq i64 [[BF_ASHR749]], [[CONV728]]
// CHK-CXX-NEXT:    [[FROMBOOL751:%.*]] = zext i1 [[CMP750]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL751]], i8* [[ATMP736]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP750]], label [[ATOMIC_CONT738]], label [[ATOMIC_EXIT752]]
// CHK-CXX:       atomic_exit752:
// CHK-CXX-NEXT:    [[TMP292:%.*]] = load i64, i64* [[ATMP730]], align 8
// CHK-CXX-NEXT:    [[TMP293:%.*]] = load i8, i8* [[ATMP736]], align 1
// CHK-CXX-NEXT:    [[CONV753:%.*]] = zext i8 [[TMP293]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV753]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP294:%.*]] = trunc i8 [[TMP293]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP294]], label [[ATOMIC_CAPTURE_CONT756:%.*]], label [[ATOMIC_CAPTURE754:%.*]]
// CHK-CXX:       atomic_capture754:
// CHK-CXX-NEXT:    [[CONV755:%.*]] = trunc i64 [[TMP292]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV755]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT756]]
// CHK-CXX:       atomic_capture_cont756:
// CHK-CXX-NEXT:    [[TMP295:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD757:%.*]] = load atomic i8, i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED:%.*]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2) monotonic, align 1
// CHK-CXX-NEXT:    [[TMP296:%.*]] = bitcast i32* [[ATOMIC_TEMP759]] to i8*
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD757]], i8* [[TMP296]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD760:%.*]] = load i8, i8* [[TMP296]], align 1
// CHK-CXX-NEXT:    [[BF_SHL761:%.*]] = shl i8 [[BF_LOAD760]], 7
// CHK-CXX-NEXT:    [[BF_ASHR762:%.*]] = ashr i8 [[BF_SHL761]], 7
// CHK-CXX-NEXT:    [[BF_CAST763:%.*]] = sext i8 [[BF_ASHR762]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST763]], i32* [[ATMP758]], align 4
// CHK-CXX-NEXT:    [[CMP764:%.*]] = icmp slt i32 [[BF_CAST763]], [[TMP295]]
// CHK-CXX-NEXT:    [[FROMBOOL766:%.*]] = zext i1 [[CMP764]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL766]], i8* [[ATMP765]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP764]], label [[ATOMIC_CONT767:%.*]], label [[ATOMIC_EXIT781:%.*]]
// CHK-CXX:       atomic_cont767:
// CHK-CXX-NEXT:    [[TMP297:%.*]] = phi i8 [ [[ATOMIC_LOAD757]], [[ATOMIC_CAPTURE_CONT756]] ], [ [[TMP302:%.*]], [[ATOMIC_CMP773:%.*]] ]
// CHK-CXX-NEXT:    [[TMP298:%.*]] = bitcast i32* [[ATOMIC_TEMP768]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP297]], i8* [[TMP298]], align 1
// CHK-CXX-NEXT:    [[TMP299:%.*]] = trunc i32 [[TMP295]] to i8
// CHK-CXX-NEXT:    [[BF_LOAD769:%.*]] = load i8, i8* [[TMP298]], align 1
// CHK-CXX-NEXT:    [[BF_VALUE770:%.*]] = and i8 [[TMP299]], 1
// CHK-CXX-NEXT:    [[BF_CLEAR771:%.*]] = and i8 [[BF_LOAD769]], -2
// CHK-CXX-NEXT:    [[BF_SET772:%.*]] = or i8 [[BF_CLEAR771]], [[BF_VALUE770]]
// CHK-CXX-NEXT:    store i8 [[BF_SET772]], i8* [[TMP298]], align 1
// CHK-CXX-NEXT:    [[TMP300:%.*]] = load i8, i8* [[TMP298]], align 1
// CHK-CXX-NEXT:    [[TMP301:%.*]] = cmpxchg i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2), i8 [[TMP297]], i8 [[TMP300]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP302]] = extractvalue { i8, i1 } [[TMP301]], 0
// CHK-CXX-NEXT:    [[TMP303:%.*]] = extractvalue { i8, i1 } [[TMP301]], 1
// CHK-CXX-NEXT:    br i1 [[TMP303]], label [[ATOMIC_EXIT781]], label [[ATOMIC_CMP773]]
// CHK-CXX:       atomic_cmp773:
// CHK-CXX-NEXT:    [[TMP304:%.*]] = bitcast i32* [[ATOMIC_TEMP774]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP302]], i8* [[TMP304]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD775:%.*]] = load i8, i8* [[TMP304]], align 1
// CHK-CXX-NEXT:    [[BF_SHL776:%.*]] = shl i8 [[BF_LOAD775]], 7
// CHK-CXX-NEXT:    [[BF_ASHR777:%.*]] = ashr i8 [[BF_SHL776]], 7
// CHK-CXX-NEXT:    [[BF_CAST778:%.*]] = sext i8 [[BF_ASHR777]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST778]], i32* [[ATMP758]], align 4
// CHK-CXX-NEXT:    [[CMP779:%.*]] = icmp slt i32 [[BF_CAST778]], [[TMP295]]
// CHK-CXX-NEXT:    [[FROMBOOL780:%.*]] = zext i1 [[CMP779]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL780]], i8* [[ATMP765]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP779]], label [[ATOMIC_CONT767]], label [[ATOMIC_EXIT781]]
// CHK-CXX:       atomic_exit781:
// CHK-CXX-NEXT:    [[TMP305:%.*]] = load i32, i32* [[ATMP758]], align 4
// CHK-CXX-NEXT:    [[TMP306:%.*]] = load i8, i8* [[ATMP765]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP305]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP307:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD782:%.*]] = load atomic i8, i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2) monotonic, align 1
// CHK-CXX-NEXT:    [[TMP308:%.*]] = bitcast i32* [[ATOMIC_TEMP784]] to i8*
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD782]], i8* [[TMP308]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD785:%.*]] = load i8, i8* [[TMP308]], align 1
// CHK-CXX-NEXT:    [[BF_SHL786:%.*]] = shl i8 [[BF_LOAD785]], 7
// CHK-CXX-NEXT:    [[BF_ASHR787:%.*]] = ashr i8 [[BF_SHL786]], 7
// CHK-CXX-NEXT:    [[BF_CAST788:%.*]] = sext i8 [[BF_ASHR787]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST788]], i32* [[ATMP783]], align 4
// CHK-CXX-NEXT:    [[CMP789:%.*]] = icmp slt i32 [[BF_CAST788]], [[TMP307]]
// CHK-CXX-NEXT:    [[FROMBOOL791:%.*]] = zext i1 [[CMP789]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL791]], i8* [[ATMP790]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP789]], label [[ATOMIC_CONT792:%.*]], label [[ATOMIC_EXIT807:%.*]]
// CHK-CXX:       atomic_cont792:
// CHK-CXX-NEXT:    [[TMP309:%.*]] = phi i8 [ [[ATOMIC_LOAD782]], [[ATOMIC_EXIT781]] ], [ [[TMP314:%.*]], [[ATOMIC_CMP799:%.*]] ]
// CHK-CXX-NEXT:    [[TMP310:%.*]] = bitcast i32* [[ATOMIC_TEMP793]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP309]], i8* [[TMP310]], align 1
// CHK-CXX-NEXT:    [[TMP311:%.*]] = trunc i32 [[TMP307]] to i8
// CHK-CXX-NEXT:    [[BF_LOAD794:%.*]] = load i8, i8* [[TMP310]], align 1
// CHK-CXX-NEXT:    [[BF_VALUE795:%.*]] = and i8 [[TMP311]], 1
// CHK-CXX-NEXT:    [[BF_CLEAR796:%.*]] = and i8 [[BF_LOAD794]], -2
// CHK-CXX-NEXT:    [[BF_SET797:%.*]] = or i8 [[BF_CLEAR796]], [[BF_VALUE795]]
// CHK-CXX-NEXT:    store i8 [[BF_SET797]], i8* [[TMP310]], align 1
// CHK-CXX-NEXT:    [[TMP312:%.*]] = load i8, i8* [[TMP310]], align 1
// CHK-CXX-NEXT:    [[TMP313:%.*]] = cmpxchg i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2), i8 [[TMP309]], i8 [[TMP312]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP314]] = extractvalue { i8, i1 } [[TMP313]], 0
// CHK-CXX-NEXT:    [[TMP315:%.*]] = extractvalue { i8, i1 } [[TMP313]], 1
// CHK-CXX-NEXT:    br i1 [[TMP315]], label [[ATOMIC_UPD_EXIT798:%.*]], label [[ATOMIC_CMP799]]
// CHK-CXX:       atomic_upd_exit798:
// CHK-CXX-NEXT:    store i32 [[TMP307]], i32* [[ATMP783]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT807]]
// CHK-CXX:       atomic_cmp799:
// CHK-CXX-NEXT:    [[TMP316:%.*]] = bitcast i32* [[ATOMIC_TEMP800]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP314]], i8* [[TMP316]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD801:%.*]] = load i8, i8* [[TMP316]], align 1
// CHK-CXX-NEXT:    [[BF_SHL802:%.*]] = shl i8 [[BF_LOAD801]], 7
// CHK-CXX-NEXT:    [[BF_ASHR803:%.*]] = ashr i8 [[BF_SHL802]], 7
// CHK-CXX-NEXT:    [[BF_CAST804:%.*]] = sext i8 [[BF_ASHR803]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST804]], i32* [[ATMP783]], align 4
// CHK-CXX-NEXT:    [[CMP805:%.*]] = icmp slt i32 [[BF_CAST804]], [[TMP307]]
// CHK-CXX-NEXT:    [[FROMBOOL806:%.*]] = zext i1 [[CMP805]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL806]], i8* [[ATMP790]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP805]], label [[ATOMIC_CONT792]], label [[ATOMIC_EXIT807]]
// CHK-CXX:       atomic_exit807:
// CHK-CXX-NEXT:    [[TMP317:%.*]] = load i32, i32* [[ATMP783]], align 4
// CHK-CXX-NEXT:    [[TMP318:%.*]] = load i8, i8* [[ATMP790]], align 1
// CHK-CXX-NEXT:    store i32 [[TMP317]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP319:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP320:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD808:%.*]] = load atomic i8, i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2) monotonic, align 1
// CHK-CXX-NEXT:    [[TMP321:%.*]] = bitcast i32* [[ATOMIC_TEMP810]] to i8*
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD808]], i8* [[TMP321]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD811:%.*]] = load i8, i8* [[TMP321]], align 1
// CHK-CXX-NEXT:    [[BF_SHL812:%.*]] = shl i8 [[BF_LOAD811]], 7
// CHK-CXX-NEXT:    [[BF_ASHR813:%.*]] = ashr i8 [[BF_SHL812]], 7
// CHK-CXX-NEXT:    [[BF_CAST814:%.*]] = sext i8 [[BF_ASHR813]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST814]], i32* [[ATMP809]], align 4
// CHK-CXX-NEXT:    [[CMP815:%.*]] = icmp eq i32 [[BF_CAST814]], [[TMP320]]
// CHK-CXX-NEXT:    [[FROMBOOL817:%.*]] = zext i1 [[CMP815]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL817]], i8* [[ATMP816]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP815]], label [[ATOMIC_CONT818:%.*]], label [[ATOMIC_EXIT833:%.*]]
// CHK-CXX:       atomic_cont818:
// CHK-CXX-NEXT:    [[TMP322:%.*]] = phi i8 [ [[ATOMIC_LOAD808]], [[ATOMIC_EXIT807]] ], [ [[TMP327:%.*]], [[ATOMIC_CMP825:%.*]] ]
// CHK-CXX-NEXT:    [[TMP323:%.*]] = bitcast i32* [[ATOMIC_TEMP819]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP322]], i8* [[TMP323]], align 1
// CHK-CXX-NEXT:    [[TMP324:%.*]] = trunc i32 [[TMP319]] to i8
// CHK-CXX-NEXT:    [[BF_LOAD820:%.*]] = load i8, i8* [[TMP323]], align 1
// CHK-CXX-NEXT:    [[BF_VALUE821:%.*]] = and i8 [[TMP324]], 1
// CHK-CXX-NEXT:    [[BF_CLEAR822:%.*]] = and i8 [[BF_LOAD820]], -2
// CHK-CXX-NEXT:    [[BF_SET823:%.*]] = or i8 [[BF_CLEAR822]], [[BF_VALUE821]]
// CHK-CXX-NEXT:    store i8 [[BF_SET823]], i8* [[TMP323]], align 1
// CHK-CXX-NEXT:    [[TMP325:%.*]] = load i8, i8* [[TMP323]], align 1
// CHK-CXX-NEXT:    [[TMP326:%.*]] = cmpxchg i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2), i8 [[TMP322]], i8 [[TMP325]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP327]] = extractvalue { i8, i1 } [[TMP326]], 0
// CHK-CXX-NEXT:    [[TMP328:%.*]] = extractvalue { i8, i1 } [[TMP326]], 1
// CHK-CXX-NEXT:    br i1 [[TMP328]], label [[ATOMIC_UPD_EXIT824:%.*]], label [[ATOMIC_CMP825]]
// CHK-CXX:       atomic_upd_exit824:
// CHK-CXX-NEXT:    store i32 [[TMP319]], i32* [[ATMP809]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT833]]
// CHK-CXX:       atomic_cmp825:
// CHK-CXX-NEXT:    [[TMP329:%.*]] = bitcast i32* [[ATOMIC_TEMP826]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP327]], i8* [[TMP329]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD827:%.*]] = load i8, i8* [[TMP329]], align 1
// CHK-CXX-NEXT:    [[BF_SHL828:%.*]] = shl i8 [[BF_LOAD827]], 7
// CHK-CXX-NEXT:    [[BF_ASHR829:%.*]] = ashr i8 [[BF_SHL828]], 7
// CHK-CXX-NEXT:    [[BF_CAST830:%.*]] = sext i8 [[BF_ASHR829]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST830]], i32* [[ATMP809]], align 4
// CHK-CXX-NEXT:    [[CMP831:%.*]] = icmp eq i32 [[BF_CAST830]], [[TMP320]]
// CHK-CXX-NEXT:    [[FROMBOOL832:%.*]] = zext i1 [[CMP831]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL832]], i8* [[ATMP816]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP831]], label [[ATOMIC_CONT818]], label [[ATOMIC_EXIT833]]
// CHK-CXX:       atomic_exit833:
// CHK-CXX-NEXT:    [[TMP330:%.*]] = load i32, i32* [[ATMP809]], align 4
// CHK-CXX-NEXT:    [[TMP331:%.*]] = load i8, i8* [[ATMP816]], align 1
// CHK-CXX-NEXT:    [[TMP332:%.*]] = trunc i8 [[TMP331]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP332]], label [[ATOMIC_CAPTURE_CONT835:%.*]], label [[ATOMIC_CAPTURE834:%.*]]
// CHK-CXX:       atomic_capture834:
// CHK-CXX-NEXT:    store i32 [[TMP330]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT835]]
// CHK-CXX:       atomic_capture_cont835:
// CHK-CXX-NEXT:    [[TMP333:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP334:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD836:%.*]] = load atomic i8, i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2) monotonic, align 1
// CHK-CXX-NEXT:    [[TMP335:%.*]] = bitcast i32* [[ATOMIC_TEMP838]] to i8*
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD836]], i8* [[TMP335]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD839:%.*]] = load i8, i8* [[TMP335]], align 1
// CHK-CXX-NEXT:    [[BF_SHL840:%.*]] = shl i8 [[BF_LOAD839]], 7
// CHK-CXX-NEXT:    [[BF_ASHR841:%.*]] = ashr i8 [[BF_SHL840]], 7
// CHK-CXX-NEXT:    [[BF_CAST842:%.*]] = sext i8 [[BF_ASHR841]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST842]], i32* [[ATMP837]], align 4
// CHK-CXX-NEXT:    [[CMP843:%.*]] = icmp eq i32 [[BF_CAST842]], [[TMP334]]
// CHK-CXX-NEXT:    [[FROMBOOL845:%.*]] = zext i1 [[CMP843]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL845]], i8* [[ATMP844]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP843]], label [[ATOMIC_CONT846:%.*]], label [[ATOMIC_EXIT860:%.*]]
// CHK-CXX:       atomic_cont846:
// CHK-CXX-NEXT:    [[TMP336:%.*]] = phi i8 [ [[ATOMIC_LOAD836]], [[ATOMIC_CAPTURE_CONT835]] ], [ [[TMP341:%.*]], [[ATOMIC_CMP852:%.*]] ]
// CHK-CXX-NEXT:    [[TMP337:%.*]] = bitcast i32* [[ATOMIC_TEMP847]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP336]], i8* [[TMP337]], align 1
// CHK-CXX-NEXT:    [[TMP338:%.*]] = trunc i32 [[TMP333]] to i8
// CHK-CXX-NEXT:    [[BF_LOAD848:%.*]] = load i8, i8* [[TMP337]], align 1
// CHK-CXX-NEXT:    [[BF_VALUE849:%.*]] = and i8 [[TMP338]], 1
// CHK-CXX-NEXT:    [[BF_CLEAR850:%.*]] = and i8 [[BF_LOAD848]], -2
// CHK-CXX-NEXT:    [[BF_SET851:%.*]] = or i8 [[BF_CLEAR850]], [[BF_VALUE849]]
// CHK-CXX-NEXT:    store i8 [[BF_SET851]], i8* [[TMP337]], align 1
// CHK-CXX-NEXT:    [[TMP339:%.*]] = load i8, i8* [[TMP337]], align 1
// CHK-CXX-NEXT:    [[TMP340:%.*]] = cmpxchg i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2), i8 [[TMP336]], i8 [[TMP339]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP341]] = extractvalue { i8, i1 } [[TMP340]], 0
// CHK-CXX-NEXT:    [[TMP342:%.*]] = extractvalue { i8, i1 } [[TMP340]], 1
// CHK-CXX-NEXT:    br i1 [[TMP342]], label [[ATOMIC_EXIT860]], label [[ATOMIC_CMP852]]
// CHK-CXX:       atomic_cmp852:
// CHK-CXX-NEXT:    [[TMP343:%.*]] = bitcast i32* [[ATOMIC_TEMP853]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP341]], i8* [[TMP343]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD854:%.*]] = load i8, i8* [[TMP343]], align 1
// CHK-CXX-NEXT:    [[BF_SHL855:%.*]] = shl i8 [[BF_LOAD854]], 7
// CHK-CXX-NEXT:    [[BF_ASHR856:%.*]] = ashr i8 [[BF_SHL855]], 7
// CHK-CXX-NEXT:    [[BF_CAST857:%.*]] = sext i8 [[BF_ASHR856]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST857]], i32* [[ATMP837]], align 4
// CHK-CXX-NEXT:    [[CMP858:%.*]] = icmp eq i32 [[BF_CAST857]], [[TMP334]]
// CHK-CXX-NEXT:    [[FROMBOOL859:%.*]] = zext i1 [[CMP858]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL859]], i8* [[ATMP844]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP858]], label [[ATOMIC_CONT846]], label [[ATOMIC_EXIT860]]
// CHK-CXX:       atomic_exit860:
// CHK-CXX-NEXT:    [[TMP344:%.*]] = load i32, i32* [[ATMP837]], align 4
// CHK-CXX-NEXT:    [[TMP345:%.*]] = load i8, i8* [[ATMP844]], align 1
// CHK-CXX-NEXT:    [[CONV861:%.*]] = zext i8 [[TMP345]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV861]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP346:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[TMP347:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[ATOMIC_LOAD862:%.*]] = load atomic i8, i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2) monotonic, align 1
// CHK-CXX-NEXT:    [[TMP348:%.*]] = bitcast i32* [[ATOMIC_TEMP864]] to i8*
// CHK-CXX-NEXT:    store i8 [[ATOMIC_LOAD862]], i8* [[TMP348]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD865:%.*]] = load i8, i8* [[TMP348]], align 1
// CHK-CXX-NEXT:    [[BF_SHL866:%.*]] = shl i8 [[BF_LOAD865]], 7
// CHK-CXX-NEXT:    [[BF_ASHR867:%.*]] = ashr i8 [[BF_SHL866]], 7
// CHK-CXX-NEXT:    [[BF_CAST868:%.*]] = sext i8 [[BF_ASHR867]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST868]], i32* [[ATMP863]], align 4
// CHK-CXX-NEXT:    [[CMP869:%.*]] = icmp eq i32 [[BF_CAST868]], [[TMP347]]
// CHK-CXX-NEXT:    [[FROMBOOL871:%.*]] = zext i1 [[CMP869]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL871]], i8* [[ATMP870]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP869]], label [[ATOMIC_CONT872:%.*]], label [[ATOMIC_EXIT886:%.*]]
// CHK-CXX:       atomic_cont872:
// CHK-CXX-NEXT:    [[TMP349:%.*]] = phi i8 [ [[ATOMIC_LOAD862]], [[ATOMIC_EXIT860]] ], [ [[TMP354:%.*]], [[ATOMIC_CMP878:%.*]] ]
// CHK-CXX-NEXT:    [[TMP350:%.*]] = bitcast i32* [[ATOMIC_TEMP873]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP349]], i8* [[TMP350]], align 1
// CHK-CXX-NEXT:    [[TMP351:%.*]] = trunc i32 [[TMP346]] to i8
// CHK-CXX-NEXT:    [[BF_LOAD874:%.*]] = load i8, i8* [[TMP350]], align 1
// CHK-CXX-NEXT:    [[BF_VALUE875:%.*]] = and i8 [[TMP351]], 1
// CHK-CXX-NEXT:    [[BF_CLEAR876:%.*]] = and i8 [[BF_LOAD874]], -2
// CHK-CXX-NEXT:    [[BF_SET877:%.*]] = or i8 [[BF_CLEAR876]], [[BF_VALUE875]]
// CHK-CXX-NEXT:    store i8 [[BF_SET877]], i8* [[TMP350]], align 1
// CHK-CXX-NEXT:    [[TMP352:%.*]] = load i8, i8* [[TMP350]], align 1
// CHK-CXX-NEXT:    [[TMP353:%.*]] = cmpxchg i8* getelementptr inbounds ([[STRUCT_BITFIELDS4_PACKED]], %struct.BitFields4_packed* @bfx4_packed, i32 0, i32 0, i64 2), i8 [[TMP349]], i8 [[TMP352]] monotonic monotonic, align 1
// CHK-CXX-NEXT:    [[TMP354]] = extractvalue { i8, i1 } [[TMP353]], 0
// CHK-CXX-NEXT:    [[TMP355:%.*]] = extractvalue { i8, i1 } [[TMP353]], 1
// CHK-CXX-NEXT:    br i1 [[TMP355]], label [[ATOMIC_EXIT886]], label [[ATOMIC_CMP878]]
// CHK-CXX:       atomic_cmp878:
// CHK-CXX-NEXT:    [[TMP356:%.*]] = bitcast i32* [[ATOMIC_TEMP879]] to i8*
// CHK-CXX-NEXT:    store i8 [[TMP354]], i8* [[TMP356]], align 1
// CHK-CXX-NEXT:    [[BF_LOAD880:%.*]] = load i8, i8* [[TMP356]], align 1
// CHK-CXX-NEXT:    [[BF_SHL881:%.*]] = shl i8 [[BF_LOAD880]], 7
// CHK-CXX-NEXT:    [[BF_ASHR882:%.*]] = ashr i8 [[BF_SHL881]], 7
// CHK-CXX-NEXT:    [[BF_CAST883:%.*]] = sext i8 [[BF_ASHR882]] to i32
// CHK-CXX-NEXT:    store i32 [[BF_CAST883]], i32* [[ATMP863]], align 4
// CHK-CXX-NEXT:    [[CMP884:%.*]] = icmp eq i32 [[BF_CAST883]], [[TMP347]]
// CHK-CXX-NEXT:    [[FROMBOOL885:%.*]] = zext i1 [[CMP884]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL885]], i8* [[ATMP870]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP884]], label [[ATOMIC_CONT872]], label [[ATOMIC_EXIT886]]
// CHK-CXX:       atomic_exit886:
// CHK-CXX-NEXT:    [[TMP357:%.*]] = load i32, i32* [[ATMP863]], align 4
// CHK-CXX-NEXT:    [[TMP358:%.*]] = load i8, i8* [[ATMP870]], align 1
// CHK-CXX-NEXT:    [[CONV887:%.*]] = zext i8 [[TMP358]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV887]], i32* [[R]], align 4
// CHK-CXX-NEXT:    [[TMP359:%.*]] = trunc i8 [[TMP358]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP359]], label [[ATOMIC_CAPTURE_CONT889:%.*]], label [[ATOMIC_CAPTURE888:%.*]]
// CHK-CXX:       atomic_capture888:
// CHK-CXX-NEXT:    store i32 [[TMP357]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT889]]
// CHK-CXX:       atomic_capture_cont889:
// CHK-CXX-NEXT:    ret void
//
void test_bitfield()
{
  int expr, d, e, v, r;

  #pragma omp atomic compare capture
  { v = bfx.a; if (bfx.a < expr) { bfx.a = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (bfx.a < expr) { bfx.a = expr; } v = bfx.a; } // MAX

  #pragma omp atomic compare capture
  if (bfx.a == e) { bfx.a = d; } else { v = bfx.a; }

  #pragma omp atomic compare capture
  { r =  bfx.a == e; if(r) {  bfx.a = d; } }

  #pragma omp atomic compare capture
  { r =  bfx.a == e; if(r) {  bfx.a = d; } else { v =  bfx.a; } }

#ifdef LIBCALLS
  #pragma omp atomic compare capture
  { v = bfx_packed.a; if (bfx_packed.a < expr) { bfx_packed.a = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (bfx_packed.a < expr) { bfx_packed.a = expr; } v = bfx_packed.a; } // MAX

  #pragma omp atomic compare capture
  if (bfx_packed.a == e) { bfx_packed.a = d; } else { v = bfx_packed.a; }

  #pragma omp atomic compare capture
  { r = bfx_packed.a == e; if(r) { bfx_packed.a = d; } }

  #pragma omp atomic compare capture
  { r = bfx_packed.a == e; if(r) { bfx_packed.a = d; } else { v = bfx_packed.a; } }
#endif

  #pragma omp atomic compare capture
  { v = bfx2.a; if (bfx2.a < expr) { bfx2.a = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (bfx2.a < expr) { bfx2.a = expr; } v = bfx2.a; } // MAX

  #pragma omp atomic compare capture
  if (bfx2.a == e) { bfx2.a = d; } else { v = bfx2.a; }

  #pragma omp atomic compare capture
  { r = bfx2.a == e; if(r) { bfx2.a = d; } }

  #pragma omp atomic compare capture
  { r = bfx2.a == e; if(r) { bfx2.a = d; } else { v = bfx2.a; } }

  #pragma omp atomic compare capture
  { v = bfx2_packed.a;
    if (bfx2_packed.a < expr) { bfx2_packed.a = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (bfx2_packed.a < expr) { bfx2_packed.a = expr; }
    v =  bfx2_packed.a; } // MAX

  #pragma omp atomic compare capture
  if (bfx2_packed.a == e) { bfx2_packed.a = d; } else { v = bfx2_packed.a; }

  #pragma omp atomic compare capture
  { r = bfx2_packed.a == e; if(r) { bfx2_packed.a = d; } }

  #pragma omp atomic compare capture
  { r = bfx2_packed.a == e;
    if(r) { bfx2_packed.a = d; } else { v = bfx2_packed.a; } }

  #pragma omp atomic compare capture
  { v = bfx3.a; if (bfx3.a < expr) { bfx3.a = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (bfx3.a < expr) { bfx3.a = expr; } v = bfx3.a; } // MAX

  #pragma omp atomic compare capture
  if (bfx3.a == e) { bfx3.a = d; } else { v = bfx3.a; }

  #pragma omp atomic compare capture
  { r = bfx3.a == e; if(r) { bfx3.a = d; } }

  #pragma omp atomic compare capture
  { r = bfx3.a == e; if(r) { bfx3.a = d; } else { v = bfx3.a; } }

#ifdef LIBCALLS
  #pragma omp atomic compare capture
  { v = bfx3_packed.a;
    if (bfx3_packed.a < expr) { bfx3_packed.a = expr; } }// MAX
  #pragma omp atomic compare capture
  { if (bfx3_packed.a < expr) { bfx3_packed.a = expr; }
    v = bfx3_packed.a; }// MAX

  #pragma omp atomic compare capture
  if (bfx3_packed.a == e) { bfx3_packed.a = d; } else { v = bfx3_packed.a; }

  #pragma omp atomic compare capture
  { r = bfx3_packed.a == e; if(r) { bfx3_packed.a = d; } }

  #pragma omp atomic compare capture
  { r = bfx3_packed.a == e;
    if(r) { bfx3_packed.a = d; } else { v = bfx3_packed.a; } }
#endif

  #pragma omp atomic compare capture
  { v = bfx4.a; if (bfx4.a < expr) { bfx4.a = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (bfx4.a < expr) { bfx4.a = expr; } v = bfx4.a; } // MAX

  #pragma omp atomic compare capture
  if (bfx4.a == e) { bfx4.a = d; } else { v = bfx4.a; }

  #pragma omp atomic compare capture
  { r = bfx4.a == e; if(r) { bfx4.a = d; } }

  #pragma omp atomic compare capture
  { r = bfx4.a == e; if(r) { bfx4.a = d; } else { v = bfx4.a; } }

  #pragma omp atomic compare capture
  { v = bfx4.b; if (bfx4.b < expr) { bfx4.b = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (bfx4.b < expr) { bfx4.b = expr; }  v = bfx4.b; } // MAX

  #pragma omp atomic compare capture
  if (bfx4.b == e) { bfx4.b = d; } else { v = bfx4.b; }

  #pragma omp atomic compare capture
  { r = bfx4.b == e; if(r) { bfx4.b = d; } }

  #pragma omp atomic compare capture
  { r = bfx4.b == e; if(r) { bfx4.b = d; } else { v = bfx4.b; } }

  #pragma omp atomic compare capture
  { v = bfx4_packed.a;
    if (bfx4_packed.a < expr) { bfx4_packed.a = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (bfx4_packed.a < expr) { bfx4_packed.a = expr; }
    v = bfx4_packed.a; } // MAX

  #pragma omp atomic compare capture
  if (bfx4_packed.a == e) { bfx4_packed.a = d; } else { v = bfx4_packed.a; }

  #pragma omp atomic compare capture
  { r = bfx4_packed.a == e; if(r) { bfx4_packed.a = d; } }

  #pragma omp atomic compare capture
  { r = bfx4_packed.a == e;
    if(r) { bfx4_packed.a = d; } else { v = bfx4_packed.a; } }
}

// CHK-C-LABEL: @test_ext_vector(
// CHK-C-NEXT:  entry:
// CHK-C-NEXT:    [[FLOAT2X:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[EXPR:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[D:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[E:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[V:%.*]] = alloca i32, align 4
// CHK-C-NEXT:    [[R:%.*]] = alloca i16, align 2
// CHK-C-NEXT:    [[TMP:%.*]] = alloca float, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP2:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP3:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATMP10:%.*]] = alloca float, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP11:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATMP14:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP17:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP19:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATMP28:%.*]] = alloca float, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP29:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP31:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP33:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATMP36:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP39:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP42:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP44:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP46:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATMP55:%.*]] = alloca float, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP56:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP58:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP60:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATMP63:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP66:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP68:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP70:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP72:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATMP81:%.*]] = alloca float, align 4
// CHK-C-NEXT:    [[ATOMIC_TEMP82:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP84:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP86:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATMP89:%.*]] = alloca i8, align 1
// CHK-C-NEXT:    [[ATOMIC_TEMP92:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP94:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP96:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[ATOMIC_TEMP98:%.*]] = alloca <2 x float>, align 8
// CHK-C-NEXT:    [[TMP0:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[CONV:%.*]] = sitofp i32 [[TMP0]] to float
// CHK-C-NEXT:    [[TMP1:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i64, i64* [[TMP1]] monotonic, align 8
// CHK-C-NEXT:    [[STORETMP:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP]] to i64*
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD]], i64* [[STORETMP]], align 8
// CHK-C-NEXT:    [[TMP2:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP]], align 8
// CHK-C-NEXT:    [[TMP3:%.*]] = extractelement <2 x float> [[TMP2]], i64 0
// CHK-C-NEXT:    store float [[TMP3]], float* [[TMP]], align 4
// CHK-C-NEXT:    [[CMP:%.*]] = fcmp olt float [[TMP3]], [[CONV]]
// CHK-C-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-C:       atomic_cont:
// CHK-C-NEXT:    [[TMP4:%.*]] = phi i64 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP11:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-C-NEXT:    [[TMP5:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP2]] to i64*
// CHK-C-NEXT:    store i64 [[TMP4]], i64* [[TMP5]], align 8
// CHK-C-NEXT:    [[TMP6:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP2]], align 8
// CHK-C-NEXT:    [[TMP7:%.*]] = insertelement <2 x float> [[TMP6]], float [[CONV]], i64 0
// CHK-C-NEXT:    store <2 x float> [[TMP7]], <2 x float>* [[ATOMIC_TEMP2]], align 8
// CHK-C-NEXT:    [[TMP8:%.*]] = load i64, i64* [[TMP5]], align 8
// CHK-C-NEXT:    [[TMP9:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-C-NEXT:    [[TMP10:%.*]] = cmpxchg i64* [[TMP9]], i64 [[TMP4]], i64 [[TMP8]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP11]] = extractvalue { i64, i1 } [[TMP10]], 0
// CHK-C-NEXT:    [[TMP12:%.*]] = extractvalue { i64, i1 } [[TMP10]], 1
// CHK-C-NEXT:    br i1 [[TMP12]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-C:       atomic_cmp:
// CHK-C-NEXT:    [[STORETMP4:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP3]] to i64*
// CHK-C-NEXT:    store i64 [[TMP11]], i64* [[STORETMP4]], align 8
// CHK-C-NEXT:    [[TMP13:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP3]], align 8
// CHK-C-NEXT:    [[TMP14:%.*]] = extractelement <2 x float> [[TMP13]], i64 0
// CHK-C-NEXT:    store float [[TMP14]], float* [[TMP]], align 4
// CHK-C-NEXT:    [[CMP5:%.*]] = fcmp olt float [[TMP14]], [[CONV]]
// CHK-C-NEXT:    [[FROMBOOL6:%.*]] = zext i1 [[CMP5]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL6]], i8* [[ATMP1]], align 1
// CHK-C-NEXT:    br i1 [[CMP5]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-C:       atomic_exit:
// CHK-C-NEXT:    [[TMP15:%.*]] = load float, float* [[TMP]], align 4
// CHK-C-NEXT:    [[TMP16:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-C-NEXT:    [[CONV7:%.*]] = fptosi float [[TMP15]] to i32
// CHK-C-NEXT:    store i32 [[CONV7]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP17:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-C-NEXT:    [[CONV8:%.*]] = sitofp i32 [[TMP17]] to float
// CHK-C-NEXT:    [[TMP18:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD9:%.*]] = load atomic i64, i64* [[TMP18]] monotonic, align 8
// CHK-C-NEXT:    [[STORETMP12:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP11]] to i64*
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD9]], i64* [[STORETMP12]], align 8
// CHK-C-NEXT:    [[TMP19:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP11]], align 8
// CHK-C-NEXT:    [[TMP20:%.*]] = extractelement <2 x float> [[TMP19]], i64 0
// CHK-C-NEXT:    store float [[TMP20]], float* [[ATMP10]], align 4
// CHK-C-NEXT:    [[CMP13:%.*]] = fcmp olt float [[TMP20]], [[CONV8]]
// CHK-C-NEXT:    [[FROMBOOL15:%.*]] = zext i1 [[CMP13]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL15]], i8* [[ATMP14]], align 1
// CHK-C-NEXT:    br i1 [[CMP13]], label [[ATOMIC_CONT16:%.*]], label [[ATOMIC_EXIT23:%.*]]
// CHK-C:       atomic_cont16:
// CHK-C-NEXT:    [[TMP21:%.*]] = phi i64 [ [[ATOMIC_LOAD9]], [[ATOMIC_EXIT]] ], [ [[TMP28:%.*]], [[ATOMIC_CMP18:%.*]] ]
// CHK-C-NEXT:    [[TMP22:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP17]] to i64*
// CHK-C-NEXT:    store i64 [[TMP21]], i64* [[TMP22]], align 8
// CHK-C-NEXT:    [[TMP23:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP17]], align 8
// CHK-C-NEXT:    [[TMP24:%.*]] = insertelement <2 x float> [[TMP23]], float [[CONV8]], i64 0
// CHK-C-NEXT:    store <2 x float> [[TMP24]], <2 x float>* [[ATOMIC_TEMP17]], align 8
// CHK-C-NEXT:    [[TMP25:%.*]] = load i64, i64* [[TMP22]], align 8
// CHK-C-NEXT:    [[TMP26:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-C-NEXT:    [[TMP27:%.*]] = cmpxchg i64* [[TMP26]], i64 [[TMP21]], i64 [[TMP25]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP28]] = extractvalue { i64, i1 } [[TMP27]], 0
// CHK-C-NEXT:    [[TMP29:%.*]] = extractvalue { i64, i1 } [[TMP27]], 1
// CHK-C-NEXT:    br i1 [[TMP29]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP18]]
// CHK-C:       atomic_upd_exit:
// CHK-C-NEXT:    store float [[CONV8]], float* [[ATMP10]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT23]]
// CHK-C:       atomic_cmp18:
// CHK-C-NEXT:    [[STORETMP20:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP19]] to i64*
// CHK-C-NEXT:    store i64 [[TMP28]], i64* [[STORETMP20]], align 8
// CHK-C-NEXT:    [[TMP30:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP19]], align 8
// CHK-C-NEXT:    [[TMP31:%.*]] = extractelement <2 x float> [[TMP30]], i64 0
// CHK-C-NEXT:    store float [[TMP31]], float* [[ATMP10]], align 4
// CHK-C-NEXT:    [[CMP21:%.*]] = fcmp olt float [[TMP31]], [[CONV8]]
// CHK-C-NEXT:    [[FROMBOOL22:%.*]] = zext i1 [[CMP21]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL22]], i8* [[ATMP14]], align 1
// CHK-C-NEXT:    br i1 [[CMP21]], label [[ATOMIC_CONT16]], label [[ATOMIC_EXIT23]]
// CHK-C:       atomic_exit23:
// CHK-C-NEXT:    [[TMP32:%.*]] = load float, float* [[ATMP10]], align 4
// CHK-C-NEXT:    [[TMP33:%.*]] = load i8, i8* [[ATMP14]], align 1
// CHK-C-NEXT:    [[CONV24:%.*]] = fptosi float [[TMP32]] to i32
// CHK-C-NEXT:    store i32 [[CONV24]], i32* [[V]], align 4
// CHK-C-NEXT:    [[TMP34:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[CONV25:%.*]] = sitofp i32 [[TMP34]] to float
// CHK-C-NEXT:    [[TMP35:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[CONV26:%.*]] = sitofp i32 [[TMP35]] to float
// CHK-C-NEXT:    [[TMP36:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD27:%.*]] = load atomic i64, i64* [[TMP36]] monotonic, align 8
// CHK-C-NEXT:    [[STORETMP30:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP29]] to i64*
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD27]], i64* [[STORETMP30]], align 8
// CHK-C-NEXT:    [[TMP37:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP29]], align 8
// CHK-C-NEXT:    [[TMP38:%.*]] = extractelement <2 x float> [[TMP37]], i64 0
// CHK-C-NEXT:    store float [[TMP38]], float* [[ATMP28]], align 4
// CHK-C-NEXT:    [[STORETMP32:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP31]] to float*
// CHK-C-NEXT:    store float [[TMP38]], float* [[STORETMP32]], align 8
// CHK-C-NEXT:    [[TMP39:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP31]] to i64*
// CHK-C-NEXT:    [[TMP40:%.*]] = load i64, i64* [[TMP39]], align 8
// CHK-C-NEXT:    [[STORETMP34:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP33]] to float*
// CHK-C-NEXT:    store float [[CONV26]], float* [[STORETMP34]], align 8
// CHK-C-NEXT:    [[TMP41:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP33]] to i64*
// CHK-C-NEXT:    [[TMP42:%.*]] = load i64, i64* [[TMP41]], align 8
// CHK-C-NEXT:    [[CMP35:%.*]] = icmp eq i64 [[TMP40]], [[TMP42]]
// CHK-C-NEXT:    [[FROMBOOL37:%.*]] = zext i1 [[CMP35]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL37]], i8* [[ATMP36]], align 1
// CHK-C-NEXT:    br i1 [[CMP35]], label [[ATOMIC_CONT38:%.*]], label [[ATOMIC_EXIT50:%.*]]
// CHK-C:       atomic_cont38:
// CHK-C-NEXT:    [[TMP43:%.*]] = phi i64 [ [[ATOMIC_LOAD27]], [[ATOMIC_EXIT23]] ], [ [[TMP50:%.*]], [[ATOMIC_CMP41:%.*]] ]
// CHK-C-NEXT:    [[TMP44:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP39]] to i64*
// CHK-C-NEXT:    store i64 [[TMP43]], i64* [[TMP44]], align 8
// CHK-C-NEXT:    [[TMP45:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP39]], align 8
// CHK-C-NEXT:    [[TMP46:%.*]] = insertelement <2 x float> [[TMP45]], float [[CONV25]], i64 0
// CHK-C-NEXT:    store <2 x float> [[TMP46]], <2 x float>* [[ATOMIC_TEMP39]], align 8
// CHK-C-NEXT:    [[TMP47:%.*]] = load i64, i64* [[TMP44]], align 8
// CHK-C-NEXT:    [[TMP48:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-C-NEXT:    [[TMP49:%.*]] = cmpxchg i64* [[TMP48]], i64 [[TMP43]], i64 [[TMP47]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP50]] = extractvalue { i64, i1 } [[TMP49]], 0
// CHK-C-NEXT:    [[TMP51:%.*]] = extractvalue { i64, i1 } [[TMP49]], 1
// CHK-C-NEXT:    br i1 [[TMP51]], label [[ATOMIC_UPD_EXIT40:%.*]], label [[ATOMIC_CMP41]]
// CHK-C:       atomic_upd_exit40:
// CHK-C-NEXT:    store float [[CONV25]], float* [[ATMP28]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_EXIT50]]
// CHK-C:       atomic_cmp41:
// CHK-C-NEXT:    [[STORETMP43:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP42]] to i64*
// CHK-C-NEXT:    store i64 [[TMP50]], i64* [[STORETMP43]], align 8
// CHK-C-NEXT:    [[TMP52:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP42]], align 8
// CHK-C-NEXT:    [[TMP53:%.*]] = extractelement <2 x float> [[TMP52]], i64 0
// CHK-C-NEXT:    store float [[TMP53]], float* [[ATMP28]], align 4
// CHK-C-NEXT:    [[STORETMP45:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP44]] to float*
// CHK-C-NEXT:    store float [[TMP53]], float* [[STORETMP45]], align 8
// CHK-C-NEXT:    [[TMP54:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP44]] to i64*
// CHK-C-NEXT:    [[TMP55:%.*]] = load i64, i64* [[TMP54]], align 8
// CHK-C-NEXT:    [[STORETMP47:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP46]] to float*
// CHK-C-NEXT:    store float [[CONV26]], float* [[STORETMP47]], align 8
// CHK-C-NEXT:    [[TMP56:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP46]] to i64*
// CHK-C-NEXT:    [[TMP57:%.*]] = load i64, i64* [[TMP56]], align 8
// CHK-C-NEXT:    [[CMP48:%.*]] = icmp eq i64 [[TMP55]], [[TMP57]]
// CHK-C-NEXT:    [[FROMBOOL49:%.*]] = zext i1 [[CMP48]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL49]], i8* [[ATMP36]], align 1
// CHK-C-NEXT:    br i1 [[CMP48]], label [[ATOMIC_CONT38]], label [[ATOMIC_EXIT50]]
// CHK-C:       atomic_exit50:
// CHK-C-NEXT:    [[TMP58:%.*]] = load float, float* [[ATMP28]], align 4
// CHK-C-NEXT:    [[TMP59:%.*]] = load i8, i8* [[ATMP36]], align 1
// CHK-C-NEXT:    [[TMP60:%.*]] = trunc i8 [[TMP59]] to i1
// CHK-C-NEXT:    br i1 [[TMP60]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-C:       atomic_capture:
// CHK-C-NEXT:    [[CONV51:%.*]] = fptosi float [[TMP58]] to i32
// CHK-C-NEXT:    store i32 [[CONV51]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-C:       atomic_capture_cont:
// CHK-C-NEXT:    [[TMP61:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[CONV52:%.*]] = sitofp i32 [[TMP61]] to float
// CHK-C-NEXT:    [[TMP62:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[CONV53:%.*]] = sitofp i32 [[TMP62]] to float
// CHK-C-NEXT:    [[TMP63:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD54:%.*]] = load atomic i64, i64* [[TMP63]] monotonic, align 8
// CHK-C-NEXT:    [[STORETMP57:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP56]] to i64*
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD54]], i64* [[STORETMP57]], align 8
// CHK-C-NEXT:    [[TMP64:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP56]], align 8
// CHK-C-NEXT:    [[TMP65:%.*]] = extractelement <2 x float> [[TMP64]], i64 0
// CHK-C-NEXT:    store float [[TMP65]], float* [[ATMP55]], align 4
// CHK-C-NEXT:    [[STORETMP59:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP58]] to float*
// CHK-C-NEXT:    store float [[TMP65]], float* [[STORETMP59]], align 8
// CHK-C-NEXT:    [[TMP66:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP58]] to i64*
// CHK-C-NEXT:    [[TMP67:%.*]] = load i64, i64* [[TMP66]], align 8
// CHK-C-NEXT:    [[STORETMP61:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP60]] to float*
// CHK-C-NEXT:    store float [[CONV53]], float* [[STORETMP61]], align 8
// CHK-C-NEXT:    [[TMP68:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP60]] to i64*
// CHK-C-NEXT:    [[TMP69:%.*]] = load i64, i64* [[TMP68]], align 8
// CHK-C-NEXT:    [[CMP62:%.*]] = icmp eq i64 [[TMP67]], [[TMP69]]
// CHK-C-NEXT:    [[FROMBOOL64:%.*]] = zext i1 [[CMP62]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL64]], i8* [[ATMP63]], align 1
// CHK-C-NEXT:    br i1 [[CMP62]], label [[ATOMIC_CONT65:%.*]], label [[ATOMIC_EXIT76:%.*]]
// CHK-C:       atomic_cont65:
// CHK-C-NEXT:    [[TMP70:%.*]] = phi i64 [ [[ATOMIC_LOAD54]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP77:%.*]], [[ATOMIC_CMP67:%.*]] ]
// CHK-C-NEXT:    [[TMP71:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP66]] to i64*
// CHK-C-NEXT:    store i64 [[TMP70]], i64* [[TMP71]], align 8
// CHK-C-NEXT:    [[TMP72:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP66]], align 8
// CHK-C-NEXT:    [[TMP73:%.*]] = insertelement <2 x float> [[TMP72]], float [[CONV52]], i64 0
// CHK-C-NEXT:    store <2 x float> [[TMP73]], <2 x float>* [[ATOMIC_TEMP66]], align 8
// CHK-C-NEXT:    [[TMP74:%.*]] = load i64, i64* [[TMP71]], align 8
// CHK-C-NEXT:    [[TMP75:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-C-NEXT:    [[TMP76:%.*]] = cmpxchg i64* [[TMP75]], i64 [[TMP70]], i64 [[TMP74]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP77]] = extractvalue { i64, i1 } [[TMP76]], 0
// CHK-C-NEXT:    [[TMP78:%.*]] = extractvalue { i64, i1 } [[TMP76]], 1
// CHK-C-NEXT:    br i1 [[TMP78]], label [[ATOMIC_EXIT76]], label [[ATOMIC_CMP67]]
// CHK-C:       atomic_cmp67:
// CHK-C-NEXT:    [[STORETMP69:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP68]] to i64*
// CHK-C-NEXT:    store i64 [[TMP77]], i64* [[STORETMP69]], align 8
// CHK-C-NEXT:    [[TMP79:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP68]], align 8
// CHK-C-NEXT:    [[TMP80:%.*]] = extractelement <2 x float> [[TMP79]], i64 0
// CHK-C-NEXT:    store float [[TMP80]], float* [[ATMP55]], align 4
// CHK-C-NEXT:    [[STORETMP71:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP70]] to float*
// CHK-C-NEXT:    store float [[TMP80]], float* [[STORETMP71]], align 8
// CHK-C-NEXT:    [[TMP81:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP70]] to i64*
// CHK-C-NEXT:    [[TMP82:%.*]] = load i64, i64* [[TMP81]], align 8
// CHK-C-NEXT:    [[STORETMP73:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP72]] to float*
// CHK-C-NEXT:    store float [[CONV53]], float* [[STORETMP73]], align 8
// CHK-C-NEXT:    [[TMP83:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP72]] to i64*
// CHK-C-NEXT:    [[TMP84:%.*]] = load i64, i64* [[TMP83]], align 8
// CHK-C-NEXT:    [[CMP74:%.*]] = icmp eq i64 [[TMP82]], [[TMP84]]
// CHK-C-NEXT:    [[FROMBOOL75:%.*]] = zext i1 [[CMP74]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL75]], i8* [[ATMP63]], align 1
// CHK-C-NEXT:    br i1 [[CMP74]], label [[ATOMIC_CONT65]], label [[ATOMIC_EXIT76]]
// CHK-C:       atomic_exit76:
// CHK-C-NEXT:    [[TMP85:%.*]] = load float, float* [[ATMP55]], align 4
// CHK-C-NEXT:    [[TMP86:%.*]] = load i8, i8* [[ATMP63]], align 1
// CHK-C-NEXT:    [[CONV77:%.*]] = zext i8 [[TMP86]] to i16
// CHK-C-NEXT:    store i16 [[CONV77]], i16* [[R]], align 2
// CHK-C-NEXT:    [[TMP87:%.*]] = load i32, i32* [[D]], align 4
// CHK-C-NEXT:    [[CONV78:%.*]] = sitofp i32 [[TMP87]] to float
// CHK-C-NEXT:    [[TMP88:%.*]] = load i32, i32* [[E]], align 4
// CHK-C-NEXT:    [[CONV79:%.*]] = sitofp i32 [[TMP88]] to float
// CHK-C-NEXT:    [[TMP89:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-C-NEXT:    [[ATOMIC_LOAD80:%.*]] = load atomic i64, i64* [[TMP89]] monotonic, align 8
// CHK-C-NEXT:    [[STORETMP83:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP82]] to i64*
// CHK-C-NEXT:    store i64 [[ATOMIC_LOAD80]], i64* [[STORETMP83]], align 8
// CHK-C-NEXT:    [[TMP90:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP82]], align 8
// CHK-C-NEXT:    [[TMP91:%.*]] = extractelement <2 x float> [[TMP90]], i64 0
// CHK-C-NEXT:    store float [[TMP91]], float* [[ATMP81]], align 4
// CHK-C-NEXT:    [[STORETMP85:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP84]] to float*
// CHK-C-NEXT:    store float [[TMP91]], float* [[STORETMP85]], align 8
// CHK-C-NEXT:    [[TMP92:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP84]] to i64*
// CHK-C-NEXT:    [[TMP93:%.*]] = load i64, i64* [[TMP92]], align 8
// CHK-C-NEXT:    [[STORETMP87:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP86]] to float*
// CHK-C-NEXT:    store float [[CONV79]], float* [[STORETMP87]], align 8
// CHK-C-NEXT:    [[TMP94:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP86]] to i64*
// CHK-C-NEXT:    [[TMP95:%.*]] = load i64, i64* [[TMP94]], align 8
// CHK-C-NEXT:    [[CMP88:%.*]] = icmp eq i64 [[TMP93]], [[TMP95]]
// CHK-C-NEXT:    [[FROMBOOL90:%.*]] = zext i1 [[CMP88]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL90]], i8* [[ATMP89]], align 1
// CHK-C-NEXT:    br i1 [[CMP88]], label [[ATOMIC_CONT91:%.*]], label [[ATOMIC_EXIT102:%.*]]
// CHK-C:       atomic_cont91:
// CHK-C-NEXT:    [[TMP96:%.*]] = phi i64 [ [[ATOMIC_LOAD80]], [[ATOMIC_EXIT76]] ], [ [[TMP103:%.*]], [[ATOMIC_CMP93:%.*]] ]
// CHK-C-NEXT:    [[TMP97:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP92]] to i64*
// CHK-C-NEXT:    store i64 [[TMP96]], i64* [[TMP97]], align 8
// CHK-C-NEXT:    [[TMP98:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP92]], align 8
// CHK-C-NEXT:    [[TMP99:%.*]] = insertelement <2 x float> [[TMP98]], float [[CONV78]], i64 0
// CHK-C-NEXT:    store <2 x float> [[TMP99]], <2 x float>* [[ATOMIC_TEMP92]], align 8
// CHK-C-NEXT:    [[TMP100:%.*]] = load i64, i64* [[TMP97]], align 8
// CHK-C-NEXT:    [[TMP101:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-C-NEXT:    [[TMP102:%.*]] = cmpxchg i64* [[TMP101]], i64 [[TMP96]], i64 [[TMP100]] monotonic monotonic, align 8
// CHK-C-NEXT:    [[TMP103]] = extractvalue { i64, i1 } [[TMP102]], 0
// CHK-C-NEXT:    [[TMP104:%.*]] = extractvalue { i64, i1 } [[TMP102]], 1
// CHK-C-NEXT:    br i1 [[TMP104]], label [[ATOMIC_EXIT102]], label [[ATOMIC_CMP93]]
// CHK-C:       atomic_cmp93:
// CHK-C-NEXT:    [[STORETMP95:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP94]] to i64*
// CHK-C-NEXT:    store i64 [[TMP103]], i64* [[STORETMP95]], align 8
// CHK-C-NEXT:    [[TMP105:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP94]], align 8
// CHK-C-NEXT:    [[TMP106:%.*]] = extractelement <2 x float> [[TMP105]], i64 0
// CHK-C-NEXT:    store float [[TMP106]], float* [[ATMP81]], align 4
// CHK-C-NEXT:    [[STORETMP97:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP96]] to float*
// CHK-C-NEXT:    store float [[TMP106]], float* [[STORETMP97]], align 8
// CHK-C-NEXT:    [[TMP107:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP96]] to i64*
// CHK-C-NEXT:    [[TMP108:%.*]] = load i64, i64* [[TMP107]], align 8
// CHK-C-NEXT:    [[STORETMP99:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP98]] to float*
// CHK-C-NEXT:    store float [[CONV79]], float* [[STORETMP99]], align 8
// CHK-C-NEXT:    [[TMP109:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP98]] to i64*
// CHK-C-NEXT:    [[TMP110:%.*]] = load i64, i64* [[TMP109]], align 8
// CHK-C-NEXT:    [[CMP100:%.*]] = icmp eq i64 [[TMP108]], [[TMP110]]
// CHK-C-NEXT:    [[FROMBOOL101:%.*]] = zext i1 [[CMP100]] to i8
// CHK-C-NEXT:    store i8 [[FROMBOOL101]], i8* [[ATMP89]], align 1
// CHK-C-NEXT:    br i1 [[CMP100]], label [[ATOMIC_CONT91]], label [[ATOMIC_EXIT102]]
// CHK-C:       atomic_exit102:
// CHK-C-NEXT:    [[TMP111:%.*]] = load float, float* [[ATMP81]], align 4
// CHK-C-NEXT:    [[TMP112:%.*]] = load i8, i8* [[ATMP89]], align 1
// CHK-C-NEXT:    [[CONV103:%.*]] = zext i8 [[TMP112]] to i16
// CHK-C-NEXT:    store i16 [[CONV103]], i16* [[R]], align 2
// CHK-C-NEXT:    [[TMP113:%.*]] = trunc i8 [[TMP112]] to i1
// CHK-C-NEXT:    br i1 [[TMP113]], label [[ATOMIC_CAPTURE_CONT106:%.*]], label [[ATOMIC_CAPTURE104:%.*]]
// CHK-C:       atomic_capture104:
// CHK-C-NEXT:    [[CONV105:%.*]] = fptosi float [[TMP111]] to i32
// CHK-C-NEXT:    store i32 [[CONV105]], i32* [[V]], align 4
// CHK-C-NEXT:    br label [[ATOMIC_CAPTURE_CONT106]]
// CHK-C:       atomic_capture_cont106:
// CHK-C-NEXT:    ret void
//
// CHK-CXX-LABEL: @_Z15test_ext_vectorv(
// CHK-CXX-NEXT:  entry:
// CHK-CXX-NEXT:    [[FLOAT2X:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[EXPR:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[D:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[E:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[V:%.*]] = alloca i32, align 4
// CHK-CXX-NEXT:    [[R:%.*]] = alloca i16, align 2
// CHK-CXX-NEXT:    [[TMP:%.*]] = alloca float, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATMP1:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP2:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP3:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATMP10:%.*]] = alloca float, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP11:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATMP14:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP17:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP19:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATMP28:%.*]] = alloca float, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP29:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP31:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP33:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATMP36:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP39:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP42:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP44:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP46:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATMP55:%.*]] = alloca float, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP56:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP58:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP60:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATMP63:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP66:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP68:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP70:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP72:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATMP81:%.*]] = alloca float, align 4
// CHK-CXX-NEXT:    [[ATOMIC_TEMP82:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP84:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP86:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATMP89:%.*]] = alloca i8, align 1
// CHK-CXX-NEXT:    [[ATOMIC_TEMP92:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP94:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP96:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[ATOMIC_TEMP98:%.*]] = alloca <2 x float>, align 8
// CHK-CXX-NEXT:    [[TMP0:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[CONV:%.*]] = sitofp i32 [[TMP0]] to float
// CHK-CXX-NEXT:    [[TMP1:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i64, i64* [[TMP1]] monotonic, align 8
// CHK-CXX-NEXT:    [[STORETMP:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP]] to i64*
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD]], i64* [[STORETMP]], align 8
// CHK-CXX-NEXT:    [[TMP2:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP]], align 8
// CHK-CXX-NEXT:    [[TMP3:%.*]] = extractelement <2 x float> [[TMP2]], i64 0
// CHK-CXX-NEXT:    store float [[TMP3]], float* [[TMP]], align 4
// CHK-CXX-NEXT:    [[CMP:%.*]] = fcmp olt float [[TMP3]], [[CONV]]
// CHK-CXX-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP]], label [[ATOMIC_CONT:%.*]], label [[ATOMIC_EXIT:%.*]]
// CHK-CXX:       atomic_cont:
// CHK-CXX-NEXT:    [[TMP4:%.*]] = phi i64 [ [[ATOMIC_LOAD]], [[ENTRY:%.*]] ], [ [[TMP11:%.*]], [[ATOMIC_CMP:%.*]] ]
// CHK-CXX-NEXT:    [[TMP5:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP2]] to i64*
// CHK-CXX-NEXT:    store i64 [[TMP4]], i64* [[TMP5]], align 8
// CHK-CXX-NEXT:    [[TMP6:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP2]], align 8
// CHK-CXX-NEXT:    [[TMP7:%.*]] = insertelement <2 x float> [[TMP6]], float [[CONV]], i64 0
// CHK-CXX-NEXT:    store <2 x float> [[TMP7]], <2 x float>* [[ATOMIC_TEMP2]], align 8
// CHK-CXX-NEXT:    [[TMP8:%.*]] = load i64, i64* [[TMP5]], align 8
// CHK-CXX-NEXT:    [[TMP9:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-CXX-NEXT:    [[TMP10:%.*]] = cmpxchg i64* [[TMP9]], i64 [[TMP4]], i64 [[TMP8]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP11]] = extractvalue { i64, i1 } [[TMP10]], 0
// CHK-CXX-NEXT:    [[TMP12:%.*]] = extractvalue { i64, i1 } [[TMP10]], 1
// CHK-CXX-NEXT:    br i1 [[TMP12]], label [[ATOMIC_EXIT]], label [[ATOMIC_CMP]]
// CHK-CXX:       atomic_cmp:
// CHK-CXX-NEXT:    [[STORETMP4:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP3]] to i64*
// CHK-CXX-NEXT:    store i64 [[TMP11]], i64* [[STORETMP4]], align 8
// CHK-CXX-NEXT:    [[TMP13:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP3]], align 8
// CHK-CXX-NEXT:    [[TMP14:%.*]] = extractelement <2 x float> [[TMP13]], i64 0
// CHK-CXX-NEXT:    store float [[TMP14]], float* [[TMP]], align 4
// CHK-CXX-NEXT:    [[CMP5:%.*]] = fcmp olt float [[TMP14]], [[CONV]]
// CHK-CXX-NEXT:    [[FROMBOOL6:%.*]] = zext i1 [[CMP5]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL6]], i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP5]], label [[ATOMIC_CONT]], label [[ATOMIC_EXIT]]
// CHK-CXX:       atomic_exit:
// CHK-CXX-NEXT:    [[TMP15:%.*]] = load float, float* [[TMP]], align 4
// CHK-CXX-NEXT:    [[TMP16:%.*]] = load i8, i8* [[ATMP1]], align 1
// CHK-CXX-NEXT:    [[CONV7:%.*]] = fptosi float [[TMP15]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV7]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP17:%.*]] = load i32, i32* [[EXPR]], align 4
// CHK-CXX-NEXT:    [[CONV8:%.*]] = sitofp i32 [[TMP17]] to float
// CHK-CXX-NEXT:    [[TMP18:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD9:%.*]] = load atomic i64, i64* [[TMP18]] monotonic, align 8
// CHK-CXX-NEXT:    [[STORETMP12:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP11]] to i64*
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD9]], i64* [[STORETMP12]], align 8
// CHK-CXX-NEXT:    [[TMP19:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP11]], align 8
// CHK-CXX-NEXT:    [[TMP20:%.*]] = extractelement <2 x float> [[TMP19]], i64 0
// CHK-CXX-NEXT:    store float [[TMP20]], float* [[ATMP10]], align 4
// CHK-CXX-NEXT:    [[CMP13:%.*]] = fcmp olt float [[TMP20]], [[CONV8]]
// CHK-CXX-NEXT:    [[FROMBOOL15:%.*]] = zext i1 [[CMP13]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL15]], i8* [[ATMP14]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP13]], label [[ATOMIC_CONT16:%.*]], label [[ATOMIC_EXIT23:%.*]]
// CHK-CXX:       atomic_cont16:
// CHK-CXX-NEXT:    [[TMP21:%.*]] = phi i64 [ [[ATOMIC_LOAD9]], [[ATOMIC_EXIT]] ], [ [[TMP28:%.*]], [[ATOMIC_CMP18:%.*]] ]
// CHK-CXX-NEXT:    [[TMP22:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP17]] to i64*
// CHK-CXX-NEXT:    store i64 [[TMP21]], i64* [[TMP22]], align 8
// CHK-CXX-NEXT:    [[TMP23:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP17]], align 8
// CHK-CXX-NEXT:    [[TMP24:%.*]] = insertelement <2 x float> [[TMP23]], float [[CONV8]], i64 0
// CHK-CXX-NEXT:    store <2 x float> [[TMP24]], <2 x float>* [[ATOMIC_TEMP17]], align 8
// CHK-CXX-NEXT:    [[TMP25:%.*]] = load i64, i64* [[TMP22]], align 8
// CHK-CXX-NEXT:    [[TMP26:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-CXX-NEXT:    [[TMP27:%.*]] = cmpxchg i64* [[TMP26]], i64 [[TMP21]], i64 [[TMP25]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP28]] = extractvalue { i64, i1 } [[TMP27]], 0
// CHK-CXX-NEXT:    [[TMP29:%.*]] = extractvalue { i64, i1 } [[TMP27]], 1
// CHK-CXX-NEXT:    br i1 [[TMP29]], label [[ATOMIC_UPD_EXIT:%.*]], label [[ATOMIC_CMP18]]
// CHK-CXX:       atomic_upd_exit:
// CHK-CXX-NEXT:    store float [[CONV8]], float* [[ATMP10]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT23]]
// CHK-CXX:       atomic_cmp18:
// CHK-CXX-NEXT:    [[STORETMP20:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP19]] to i64*
// CHK-CXX-NEXT:    store i64 [[TMP28]], i64* [[STORETMP20]], align 8
// CHK-CXX-NEXT:    [[TMP30:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP19]], align 8
// CHK-CXX-NEXT:    [[TMP31:%.*]] = extractelement <2 x float> [[TMP30]], i64 0
// CHK-CXX-NEXT:    store float [[TMP31]], float* [[ATMP10]], align 4
// CHK-CXX-NEXT:    [[CMP21:%.*]] = fcmp olt float [[TMP31]], [[CONV8]]
// CHK-CXX-NEXT:    [[FROMBOOL22:%.*]] = zext i1 [[CMP21]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL22]], i8* [[ATMP14]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP21]], label [[ATOMIC_CONT16]], label [[ATOMIC_EXIT23]]
// CHK-CXX:       atomic_exit23:
// CHK-CXX-NEXT:    [[TMP32:%.*]] = load float, float* [[ATMP10]], align 4
// CHK-CXX-NEXT:    [[TMP33:%.*]] = load i8, i8* [[ATMP14]], align 1
// CHK-CXX-NEXT:    [[CONV24:%.*]] = fptosi float [[TMP32]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV24]], i32* [[V]], align 4
// CHK-CXX-NEXT:    [[TMP34:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[CONV25:%.*]] = sitofp i32 [[TMP34]] to float
// CHK-CXX-NEXT:    [[TMP35:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[CONV26:%.*]] = sitofp i32 [[TMP35]] to float
// CHK-CXX-NEXT:    [[TMP36:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD27:%.*]] = load atomic i64, i64* [[TMP36]] monotonic, align 8
// CHK-CXX-NEXT:    [[STORETMP30:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP29]] to i64*
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD27]], i64* [[STORETMP30]], align 8
// CHK-CXX-NEXT:    [[TMP37:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP29]], align 8
// CHK-CXX-NEXT:    [[TMP38:%.*]] = extractelement <2 x float> [[TMP37]], i64 0
// CHK-CXX-NEXT:    store float [[TMP38]], float* [[ATMP28]], align 4
// CHK-CXX-NEXT:    [[STORETMP32:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP31]] to float*
// CHK-CXX-NEXT:    store float [[TMP38]], float* [[STORETMP32]], align 8
// CHK-CXX-NEXT:    [[TMP39:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP31]] to i64*
// CHK-CXX-NEXT:    [[TMP40:%.*]] = load i64, i64* [[TMP39]], align 8
// CHK-CXX-NEXT:    [[STORETMP34:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP33]] to float*
// CHK-CXX-NEXT:    store float [[CONV26]], float* [[STORETMP34]], align 8
// CHK-CXX-NEXT:    [[TMP41:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP33]] to i64*
// CHK-CXX-NEXT:    [[TMP42:%.*]] = load i64, i64* [[TMP41]], align 8
// CHK-CXX-NEXT:    [[CMP35:%.*]] = icmp eq i64 [[TMP40]], [[TMP42]]
// CHK-CXX-NEXT:    [[FROMBOOL37:%.*]] = zext i1 [[CMP35]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL37]], i8* [[ATMP36]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP35]], label [[ATOMIC_CONT38:%.*]], label [[ATOMIC_EXIT50:%.*]]
// CHK-CXX:       atomic_cont38:
// CHK-CXX-NEXT:    [[TMP43:%.*]] = phi i64 [ [[ATOMIC_LOAD27]], [[ATOMIC_EXIT23]] ], [ [[TMP50:%.*]], [[ATOMIC_CMP41:%.*]] ]
// CHK-CXX-NEXT:    [[TMP44:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP39]] to i64*
// CHK-CXX-NEXT:    store i64 [[TMP43]], i64* [[TMP44]], align 8
// CHK-CXX-NEXT:    [[TMP45:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP39]], align 8
// CHK-CXX-NEXT:    [[TMP46:%.*]] = insertelement <2 x float> [[TMP45]], float [[CONV25]], i64 0
// CHK-CXX-NEXT:    store <2 x float> [[TMP46]], <2 x float>* [[ATOMIC_TEMP39]], align 8
// CHK-CXX-NEXT:    [[TMP47:%.*]] = load i64, i64* [[TMP44]], align 8
// CHK-CXX-NEXT:    [[TMP48:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-CXX-NEXT:    [[TMP49:%.*]] = cmpxchg i64* [[TMP48]], i64 [[TMP43]], i64 [[TMP47]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP50]] = extractvalue { i64, i1 } [[TMP49]], 0
// CHK-CXX-NEXT:    [[TMP51:%.*]] = extractvalue { i64, i1 } [[TMP49]], 1
// CHK-CXX-NEXT:    br i1 [[TMP51]], label [[ATOMIC_UPD_EXIT40:%.*]], label [[ATOMIC_CMP41]]
// CHK-CXX:       atomic_upd_exit40:
// CHK-CXX-NEXT:    store float [[CONV25]], float* [[ATMP28]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_EXIT50]]
// CHK-CXX:       atomic_cmp41:
// CHK-CXX-NEXT:    [[STORETMP43:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP42]] to i64*
// CHK-CXX-NEXT:    store i64 [[TMP50]], i64* [[STORETMP43]], align 8
// CHK-CXX-NEXT:    [[TMP52:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP42]], align 8
// CHK-CXX-NEXT:    [[TMP53:%.*]] = extractelement <2 x float> [[TMP52]], i64 0
// CHK-CXX-NEXT:    store float [[TMP53]], float* [[ATMP28]], align 4
// CHK-CXX-NEXT:    [[STORETMP45:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP44]] to float*
// CHK-CXX-NEXT:    store float [[TMP53]], float* [[STORETMP45]], align 8
// CHK-CXX-NEXT:    [[TMP54:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP44]] to i64*
// CHK-CXX-NEXT:    [[TMP55:%.*]] = load i64, i64* [[TMP54]], align 8
// CHK-CXX-NEXT:    [[STORETMP47:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP46]] to float*
// CHK-CXX-NEXT:    store float [[CONV26]], float* [[STORETMP47]], align 8
// CHK-CXX-NEXT:    [[TMP56:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP46]] to i64*
// CHK-CXX-NEXT:    [[TMP57:%.*]] = load i64, i64* [[TMP56]], align 8
// CHK-CXX-NEXT:    [[CMP48:%.*]] = icmp eq i64 [[TMP55]], [[TMP57]]
// CHK-CXX-NEXT:    [[FROMBOOL49:%.*]] = zext i1 [[CMP48]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL49]], i8* [[ATMP36]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP48]], label [[ATOMIC_CONT38]], label [[ATOMIC_EXIT50]]
// CHK-CXX:       atomic_exit50:
// CHK-CXX-NEXT:    [[TMP58:%.*]] = load float, float* [[ATMP28]], align 4
// CHK-CXX-NEXT:    [[TMP59:%.*]] = load i8, i8* [[ATMP36]], align 1
// CHK-CXX-NEXT:    [[TMP60:%.*]] = trunc i8 [[TMP59]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP60]], label [[ATOMIC_CAPTURE_CONT:%.*]], label [[ATOMIC_CAPTURE:%.*]]
// CHK-CXX:       atomic_capture:
// CHK-CXX-NEXT:    [[CONV51:%.*]] = fptosi float [[TMP58]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV51]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT]]
// CHK-CXX:       atomic_capture_cont:
// CHK-CXX-NEXT:    [[TMP61:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[CONV52:%.*]] = sitofp i32 [[TMP61]] to float
// CHK-CXX-NEXT:    [[TMP62:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[CONV53:%.*]] = sitofp i32 [[TMP62]] to float
// CHK-CXX-NEXT:    [[TMP63:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD54:%.*]] = load atomic i64, i64* [[TMP63]] monotonic, align 8
// CHK-CXX-NEXT:    [[STORETMP57:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP56]] to i64*
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD54]], i64* [[STORETMP57]], align 8
// CHK-CXX-NEXT:    [[TMP64:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP56]], align 8
// CHK-CXX-NEXT:    [[TMP65:%.*]] = extractelement <2 x float> [[TMP64]], i64 0
// CHK-CXX-NEXT:    store float [[TMP65]], float* [[ATMP55]], align 4
// CHK-CXX-NEXT:    [[STORETMP59:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP58]] to float*
// CHK-CXX-NEXT:    store float [[TMP65]], float* [[STORETMP59]], align 8
// CHK-CXX-NEXT:    [[TMP66:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP58]] to i64*
// CHK-CXX-NEXT:    [[TMP67:%.*]] = load i64, i64* [[TMP66]], align 8
// CHK-CXX-NEXT:    [[STORETMP61:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP60]] to float*
// CHK-CXX-NEXT:    store float [[CONV53]], float* [[STORETMP61]], align 8
// CHK-CXX-NEXT:    [[TMP68:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP60]] to i64*
// CHK-CXX-NEXT:    [[TMP69:%.*]] = load i64, i64* [[TMP68]], align 8
// CHK-CXX-NEXT:    [[CMP62:%.*]] = icmp eq i64 [[TMP67]], [[TMP69]]
// CHK-CXX-NEXT:    [[FROMBOOL64:%.*]] = zext i1 [[CMP62]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL64]], i8* [[ATMP63]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP62]], label [[ATOMIC_CONT65:%.*]], label [[ATOMIC_EXIT76:%.*]]
// CHK-CXX:       atomic_cont65:
// CHK-CXX-NEXT:    [[TMP70:%.*]] = phi i64 [ [[ATOMIC_LOAD54]], [[ATOMIC_CAPTURE_CONT]] ], [ [[TMP77:%.*]], [[ATOMIC_CMP67:%.*]] ]
// CHK-CXX-NEXT:    [[TMP71:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP66]] to i64*
// CHK-CXX-NEXT:    store i64 [[TMP70]], i64* [[TMP71]], align 8
// CHK-CXX-NEXT:    [[TMP72:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP66]], align 8
// CHK-CXX-NEXT:    [[TMP73:%.*]] = insertelement <2 x float> [[TMP72]], float [[CONV52]], i64 0
// CHK-CXX-NEXT:    store <2 x float> [[TMP73]], <2 x float>* [[ATOMIC_TEMP66]], align 8
// CHK-CXX-NEXT:    [[TMP74:%.*]] = load i64, i64* [[TMP71]], align 8
// CHK-CXX-NEXT:    [[TMP75:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-CXX-NEXT:    [[TMP76:%.*]] = cmpxchg i64* [[TMP75]], i64 [[TMP70]], i64 [[TMP74]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP77]] = extractvalue { i64, i1 } [[TMP76]], 0
// CHK-CXX-NEXT:    [[TMP78:%.*]] = extractvalue { i64, i1 } [[TMP76]], 1
// CHK-CXX-NEXT:    br i1 [[TMP78]], label [[ATOMIC_EXIT76]], label [[ATOMIC_CMP67]]
// CHK-CXX:       atomic_cmp67:
// CHK-CXX-NEXT:    [[STORETMP69:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP68]] to i64*
// CHK-CXX-NEXT:    store i64 [[TMP77]], i64* [[STORETMP69]], align 8
// CHK-CXX-NEXT:    [[TMP79:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP68]], align 8
// CHK-CXX-NEXT:    [[TMP80:%.*]] = extractelement <2 x float> [[TMP79]], i64 0
// CHK-CXX-NEXT:    store float [[TMP80]], float* [[ATMP55]], align 4
// CHK-CXX-NEXT:    [[STORETMP71:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP70]] to float*
// CHK-CXX-NEXT:    store float [[TMP80]], float* [[STORETMP71]], align 8
// CHK-CXX-NEXT:    [[TMP81:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP70]] to i64*
// CHK-CXX-NEXT:    [[TMP82:%.*]] = load i64, i64* [[TMP81]], align 8
// CHK-CXX-NEXT:    [[STORETMP73:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP72]] to float*
// CHK-CXX-NEXT:    store float [[CONV53]], float* [[STORETMP73]], align 8
// CHK-CXX-NEXT:    [[TMP83:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP72]] to i64*
// CHK-CXX-NEXT:    [[TMP84:%.*]] = load i64, i64* [[TMP83]], align 8
// CHK-CXX-NEXT:    [[CMP74:%.*]] = icmp eq i64 [[TMP82]], [[TMP84]]
// CHK-CXX-NEXT:    [[FROMBOOL75:%.*]] = zext i1 [[CMP74]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL75]], i8* [[ATMP63]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP74]], label [[ATOMIC_CONT65]], label [[ATOMIC_EXIT76]]
// CHK-CXX:       atomic_exit76:
// CHK-CXX-NEXT:    [[TMP85:%.*]] = load float, float* [[ATMP55]], align 4
// CHK-CXX-NEXT:    [[TMP86:%.*]] = load i8, i8* [[ATMP63]], align 1
// CHK-CXX-NEXT:    [[CONV77:%.*]] = zext i8 [[TMP86]] to i16
// CHK-CXX-NEXT:    store i16 [[CONV77]], i16* [[R]], align 2
// CHK-CXX-NEXT:    [[TMP87:%.*]] = load i32, i32* [[D]], align 4
// CHK-CXX-NEXT:    [[CONV78:%.*]] = sitofp i32 [[TMP87]] to float
// CHK-CXX-NEXT:    [[TMP88:%.*]] = load i32, i32* [[E]], align 4
// CHK-CXX-NEXT:    [[CONV79:%.*]] = sitofp i32 [[TMP88]] to float
// CHK-CXX-NEXT:    [[TMP89:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-CXX-NEXT:    [[ATOMIC_LOAD80:%.*]] = load atomic i64, i64* [[TMP89]] monotonic, align 8
// CHK-CXX-NEXT:    [[STORETMP83:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP82]] to i64*
// CHK-CXX-NEXT:    store i64 [[ATOMIC_LOAD80]], i64* [[STORETMP83]], align 8
// CHK-CXX-NEXT:    [[TMP90:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP82]], align 8
// CHK-CXX-NEXT:    [[TMP91:%.*]] = extractelement <2 x float> [[TMP90]], i64 0
// CHK-CXX-NEXT:    store float [[TMP91]], float* [[ATMP81]], align 4
// CHK-CXX-NEXT:    [[STORETMP85:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP84]] to float*
// CHK-CXX-NEXT:    store float [[TMP91]], float* [[STORETMP85]], align 8
// CHK-CXX-NEXT:    [[TMP92:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP84]] to i64*
// CHK-CXX-NEXT:    [[TMP93:%.*]] = load i64, i64* [[TMP92]], align 8
// CHK-CXX-NEXT:    [[STORETMP87:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP86]] to float*
// CHK-CXX-NEXT:    store float [[CONV79]], float* [[STORETMP87]], align 8
// CHK-CXX-NEXT:    [[TMP94:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP86]] to i64*
// CHK-CXX-NEXT:    [[TMP95:%.*]] = load i64, i64* [[TMP94]], align 8
// CHK-CXX-NEXT:    [[CMP88:%.*]] = icmp eq i64 [[TMP93]], [[TMP95]]
// CHK-CXX-NEXT:    [[FROMBOOL90:%.*]] = zext i1 [[CMP88]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL90]], i8* [[ATMP89]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP88]], label [[ATOMIC_CONT91:%.*]], label [[ATOMIC_EXIT102:%.*]]
// CHK-CXX:       atomic_cont91:
// CHK-CXX-NEXT:    [[TMP96:%.*]] = phi i64 [ [[ATOMIC_LOAD80]], [[ATOMIC_EXIT76]] ], [ [[TMP103:%.*]], [[ATOMIC_CMP93:%.*]] ]
// CHK-CXX-NEXT:    [[TMP97:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP92]] to i64*
// CHK-CXX-NEXT:    store i64 [[TMP96]], i64* [[TMP97]], align 8
// CHK-CXX-NEXT:    [[TMP98:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP92]], align 8
// CHK-CXX-NEXT:    [[TMP99:%.*]] = insertelement <2 x float> [[TMP98]], float [[CONV78]], i64 0
// CHK-CXX-NEXT:    store <2 x float> [[TMP99]], <2 x float>* [[ATOMIC_TEMP92]], align 8
// CHK-CXX-NEXT:    [[TMP100:%.*]] = load i64, i64* [[TMP97]], align 8
// CHK-CXX-NEXT:    [[TMP101:%.*]] = bitcast <2 x float>* [[FLOAT2X]] to i64*
// CHK-CXX-NEXT:    [[TMP102:%.*]] = cmpxchg i64* [[TMP101]], i64 [[TMP96]], i64 [[TMP100]] monotonic monotonic, align 8
// CHK-CXX-NEXT:    [[TMP103]] = extractvalue { i64, i1 } [[TMP102]], 0
// CHK-CXX-NEXT:    [[TMP104:%.*]] = extractvalue { i64, i1 } [[TMP102]], 1
// CHK-CXX-NEXT:    br i1 [[TMP104]], label [[ATOMIC_EXIT102]], label [[ATOMIC_CMP93]]
// CHK-CXX:       atomic_cmp93:
// CHK-CXX-NEXT:    [[STORETMP95:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP94]] to i64*
// CHK-CXX-NEXT:    store i64 [[TMP103]], i64* [[STORETMP95]], align 8
// CHK-CXX-NEXT:    [[TMP105:%.*]] = load <2 x float>, <2 x float>* [[ATOMIC_TEMP94]], align 8
// CHK-CXX-NEXT:    [[TMP106:%.*]] = extractelement <2 x float> [[TMP105]], i64 0
// CHK-CXX-NEXT:    store float [[TMP106]], float* [[ATMP81]], align 4
// CHK-CXX-NEXT:    [[STORETMP97:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP96]] to float*
// CHK-CXX-NEXT:    store float [[TMP106]], float* [[STORETMP97]], align 8
// CHK-CXX-NEXT:    [[TMP107:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP96]] to i64*
// CHK-CXX-NEXT:    [[TMP108:%.*]] = load i64, i64* [[TMP107]], align 8
// CHK-CXX-NEXT:    [[STORETMP99:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP98]] to float*
// CHK-CXX-NEXT:    store float [[CONV79]], float* [[STORETMP99]], align 8
// CHK-CXX-NEXT:    [[TMP109:%.*]] = bitcast <2 x float>* [[ATOMIC_TEMP98]] to i64*
// CHK-CXX-NEXT:    [[TMP110:%.*]] = load i64, i64* [[TMP109]], align 8
// CHK-CXX-NEXT:    [[CMP100:%.*]] = icmp eq i64 [[TMP108]], [[TMP110]]
// CHK-CXX-NEXT:    [[FROMBOOL101:%.*]] = zext i1 [[CMP100]] to i8
// CHK-CXX-NEXT:    store i8 [[FROMBOOL101]], i8* [[ATMP89]], align 1
// CHK-CXX-NEXT:    br i1 [[CMP100]], label [[ATOMIC_CONT91]], label [[ATOMIC_EXIT102]]
// CHK-CXX:       atomic_exit102:
// CHK-CXX-NEXT:    [[TMP111:%.*]] = load float, float* [[ATMP81]], align 4
// CHK-CXX-NEXT:    [[TMP112:%.*]] = load i8, i8* [[ATMP89]], align 1
// CHK-CXX-NEXT:    [[CONV103:%.*]] = zext i8 [[TMP112]] to i16
// CHK-CXX-NEXT:    store i16 [[CONV103]], i16* [[R]], align 2
// CHK-CXX-NEXT:    [[TMP113:%.*]] = trunc i8 [[TMP112]] to i1
// CHK-CXX-NEXT:    br i1 [[TMP113]], label [[ATOMIC_CAPTURE_CONT106:%.*]], label [[ATOMIC_CAPTURE104:%.*]]
// CHK-CXX:       atomic_capture104:
// CHK-CXX-NEXT:    [[CONV105:%.*]] = fptosi float [[TMP111]] to i32
// CHK-CXX-NEXT:    store i32 [[CONV105]], i32* [[V]], align 4
// CHK-CXX-NEXT:    br label [[ATOMIC_CAPTURE_CONT106]]
// CHK-CXX:       atomic_capture_cont106:
// CHK-CXX-NEXT:    ret void
//
void test_ext_vector() {
  typedef float float2 __attribute__((ext_vector_type(2)));
  float2 float2x;

  int expr, d, e, v;
  short r;

  #pragma omp atomic compare capture
  { v = float2x.x; if (float2x.x < expr) { float2x.x = expr; } } // MAX

  #pragma omp atomic compare capture
  { if (float2x.x < expr) { float2x.x = expr; } v = float2x.x; } // MAX

  #pragma omp atomic compare capture
  if (float2x.x == e) { float2x.x = d; } else { v = float2x.x; }

  #pragma omp atomic compare capture
  { r = float2x.x == e; if(r) { float2x.x = d; } }

  #pragma omp atomic compare capture
  { r = float2x.x == e; if(r) { float2x.x = d; } else { v = float2x.x; } }
}

#endif // HEADER
// end INTEL_COLLAB
