// INTEL_COLLAB
// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -no-opaque-pointers -emit-llvm -o - -fopenmp \
// RUN:  -fopenmp-late-outline -fopenmp-typed-clauses \
// RUN:  -triple i386-unknown-unknown %s \
// RUN:  | FileCheck %s --check-prefix=CHECK-32
//
// RUN: %clang_cc1 -no-opaque-pointers -emit-llvm -o - -fopenmp \
// RUN:  -fopenmp-late-outline -fopenmp-typed-clauses \
// RUN:  -triple x86_64-unknown-linux-gnu %s | FileCheck %s
//
// RUN: %clang_cc1 -no-opaque-pointers -emit-llvm -o - -fopenmp \
// RUN:  -fopenmp-late-outline \
// RUN:  -triple x86_64-unknown-linux-gnu %s | FileCheck %s

// RUN: %clang_cc1 -no-opaque-pointers -emit-llvm -o - -fopenmp \
// RUN:  -fopenmp-late-outline -DMULTI_DATA \
// RUN:  -triple x86_64-unknown-linux-gnu %s | FileCheck %s
//
// RUN: %clang_cc1 -no-opaque-pointers -fopenmp -fopenmp-late-outline \
// RUN:  -fopenmp-typed-clauses \
// RUN:  -triple x86_64-unknown-linux-gnu -emit-pch %s -o %t

// RUN: %clang_cc1 -no-opaque-pointers -fopenmp -fopenmp-late-outline \
// RUN:  -fopenmp-typed-clauses \
// RUN:  -triple x86_64-unknown-linux-gnu -include-pch %t \
// RUN:  -emit-llvm %s -o - | FileCheck %s
//
// expected-no-diagnostics
#ifndef HEADER
#define HEADER

struct foobar {
  int i;
  double d[10];
  double d2[10][10];

  void check();
};

// CHECK-32-LABEL: @_ZN6foobar5checkEv(
// CHECK-32-NEXT:  entry:
// CHECK-32-NEXT:    [[THIS_ADDR:%.*]] = alloca %struct.foobar*, align 4
// CHECK-32-NEXT:    store %struct.foobar* [[THIS:%.*]], %struct.foobar** [[THIS_ADDR]], align 4
// CHECK-32-NEXT:    [[THIS1:%.*]] = load %struct.foobar*, %struct.foobar** [[THIS_ADDR]], align 4
// CHECK-32-NEXT:    [[D:%.*]] = getelementptr inbounds [[STRUCT_FOOBAR:%.*]], %struct.foobar* [[THIS1]], i32 0, i32 1
// CHECK-32-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [10 x double], [10 x double]* [[D]], i32 0, i32 1
// CHECK-32-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* [[ARRAYIDX]], double 0.000000e+00, i32 2, i32 4) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[D2:%.*]] = getelementptr inbounds [[STRUCT_FOOBAR]], %struct.foobar* [[THIS1]], i32 0, i32 1
// CHECK-32-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds [10 x double], [10 x double]* [[D2]], i32 0, i32 5
// CHECK-32-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* [[ARRAYIDX3]], double 0.000000e+00, i32 1, i32 3) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[D24:%.*]] = getelementptr inbounds [[STRUCT_FOOBAR]], %struct.foobar* [[THIS1]], i32 0, i32 2
// CHECK-32-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds [10 x [10 x double]], [10 x [10 x double]]* [[D24]], i32 0, i32 1
// CHECK-32-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [10 x double], [10 x double]* [[ARRAYIDX5]], i32 0, i32 0
// CHECK-32-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds double, double* [[ARRAYDECAY]], i32 0
// CHECK-32-NEXT:    [[TMP2:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* [[ARRAYIDX6]], double 0.000000e+00, i32 20, i32 4) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP2]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[D27:%.*]] = getelementptr inbounds [[STRUCT_FOOBAR]], %struct.foobar* [[THIS1]], i32 0, i32 2
// CHECK-32-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds [10 x [10 x double]], [10 x [10 x double]]* [[D27]], i32 0, i32 6
// CHECK-32-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds [10 x double], [10 x double]* [[ARRAYIDX8]], i32 0, i32 8
// CHECK-32-NEXT:    [[TMP3:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* [[ARRAYIDX9]], double 0.000000e+00, i32 1, i32 4) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP3]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    ret void
//
// CHECK-LABEL: @_ZN6foobar5checkEv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca %struct.foobar*, align 8
// CHECK-NEXT:    store %struct.foobar* [[THIS:%.*]], %struct.foobar** [[THIS_ADDR]], align 8
// CHECK-NEXT:    [[THIS1:%.*]] = load %struct.foobar*, %struct.foobar** [[THIS_ADDR]], align 8
// CHECK-NEXT:    [[D:%.*]] = getelementptr inbounds [[STRUCT_FOOBAR:%.*]], %struct.foobar* [[THIS1]], i32 0, i32 1
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [10 x double], [10 x double]* [[D]], i64 0, i64 1
// CHECK-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* [[ARRAYIDX]], double 0.000000e+00, i64 2, i32 4) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[D2:%.*]] = getelementptr inbounds [[STRUCT_FOOBAR]], %struct.foobar* [[THIS1]], i32 0, i32 1
// CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds [10 x double], [10 x double]* [[D2]], i64 0, i64 5
// CHECK-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* [[ARRAYIDX3]], double 0.000000e+00, i64 1, i32 3) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[D24:%.*]] = getelementptr inbounds [[STRUCT_FOOBAR]], %struct.foobar* [[THIS1]], i32 0, i32 2
// CHECK-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds [10 x [10 x double]], [10 x [10 x double]]* [[D24]], i64 0, i64 1
// CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [10 x double], [10 x double]* [[ARRAYIDX5]], i64 0, i64 0
// CHECK-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds double, double* [[ARRAYDECAY]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* [[ARRAYIDX6]], double 0.000000e+00, i64 20, i32 4) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP2]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[D27:%.*]] = getelementptr inbounds [[STRUCT_FOOBAR]], %struct.foobar* [[THIS1]], i32 0, i32 2
// CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds [10 x [10 x double]], [10 x [10 x double]]* [[D27]], i64 0, i64 6
// CHECK-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds [10 x double], [10 x double]* [[ARRAYIDX8]], i64 0, i64 8
// CHECK-NEXT:    [[TMP3:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* [[ARRAYIDX9]], double 0.000000e+00, i64 1, i32 4) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP3]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    ret void
//
void foobar::check() {
    //fields
    #pragma ompx prefetch data(4:d[1:2])
    #pragma ompx prefetch data(3:d[5])
    #pragma ompx prefetch data(4:d2[1:2][:])
    #pragma ompx prefetch data(4:d2[6][8])
}

foobar bar;

// CHECK-32-LABEL: @_Z13test_prefetchm(
// CHECK-32-NEXT:  entry:
// CHECK-32-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// CHECK-32-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-32-NEXT:    [[A:%.*]] = alloca i32, align 4
// CHECK-32-NEXT:    [[B:%.*]] = alloca i32, align 4
// CHECK-32-NEXT:    [[FOO1:%.*]] = alloca [10 x i32], align 4
// CHECK-32-NEXT:    [[FOO2:%.*]] = alloca [10 x [10 x i32]], align 4
// CHECK-32-NEXT:    [[P:%.*]] = alloca i32*, align 4
// CHECK-32-NEXT:    [[SAVED_STACK:%.*]] = alloca i8*, align 4
// CHECK-32-NEXT:    [[__VLA_EXPR0:%.*]] = alloca i32, align 4
// CHECK-32-NEXT:    [[PTR_BASE:%.*]] = alloca i32*, align 4
// CHECK-32-NEXT:    [[PBREF:%.*]] = alloca i32**, align 4
// CHECK-32-NEXT:    store i32 [[N:%.*]], i32* [[N_ADDR]], align 4
// CHECK-32-NEXT:    store i32 1, i32* [[I]], align 4
// CHECK-32-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i32 0, i32 0
// CHECK-32-NEXT:    store i32* [[ARRAYDECAY]], i32** [[P]], align 4
// CHECK-32-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i32 0, i32 0
// CHECK-32-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX]], i32 0, i32 1, i32 0) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i32 0, i32 1
// CHECK-32-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX1]], i32 0, i32 1, i32 0) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i32 0, i32 0
// CHECK-32-NEXT:    [[TMP2:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX2]], i32 0, i32 2, i32 1) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP2]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i32 0, i32 0
// CHECK-32-NEXT:    [[TMP3:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX3]], i32 0, i32 9, i32 2) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP3]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i32 0, i32 4
// CHECK-32-NEXT:    [[TMP4:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX4]], i32 0, i32 8, i32 3) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP4]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[TMP5:%.*]] = load i32, i32* [[I]], align 4
// CHECK-32-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i32 0, i32 3
// CHECK-32-NEXT:    [[TMP6:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX5]], i32 0, i32 [[TMP5]], i32 4) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP6]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i32 0, i32 0
// CHECK-32-NEXT:    [[TMP7:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX6]], i32 0, i32 10, i32 5) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP7]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[TMP8:%.*]] = load i32, i32* [[I]], align 4
// CHECK-32-NEXT:    [[TMP9:%.*]] = load i32, i32* [[I]], align 4
// CHECK-32-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i32 0, i32 [[TMP9]]
// CHECK-32-NEXT:    [[TMP10:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX7]], i32 0, i32 5, i32 6) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP10]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i32 0, i32 1
// CHECK-32-NEXT:    [[TMP11:%.*]] = load i32, i32* [[A]], align 4
// CHECK-32-NEXT:    [[TMP12:%.*]] = load i32, i32* [[B]], align 4
// CHECK-32-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP11]], [[TMP12]]
// CHECK-32-NEXT:    [[TMP13:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX8]], i32 0, i32 2, i32 1), "QUAL.OMP.IF"(i1 [[CMP]]) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP13]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[TMP14:%.*]] = load i32, i32* [[A]], align 4
// CHECK-32-NEXT:    [[CMP9:%.*]] = icmp eq i32 [[TMP14]], 0
// CHECK-32-NEXT:    [[TMP15:%.*]] = load i32, i32* [[I]], align 4
// CHECK-32-NEXT:    [[TMP16:%.*]] = load i32, i32* [[I]], align 4
// CHECK-32-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i32 0, i32 [[TMP16]]
// CHECK-32-NEXT:    [[TMP17:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.IF"(i1 [[CMP9]]), "QUAL.OMP.DATA"(i32* [[ARRAYIDX10]], i32 0, i32 3, i32 1) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP17]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[ARRAYIDX11:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i32 0, i32 0
// CHECK-32-NEXT:    [[ARRAYIDX12:%.*]] = getelementptr inbounds [10 x [10 x i32]], [10 x [10 x i32]]* [[FOO2]], i32 0, i32 0
// CHECK-32-NEXT:    [[ARRAYDECAY13:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[ARRAYIDX12]], i32 0, i32 0
// CHECK-32-NEXT:    [[ARRAYIDX14:%.*]] = getelementptr inbounds i32, i32* [[ARRAYDECAY13]], i32 0
// CHECK-32-NEXT:    [[TMP18:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX11]], i32 0, i32 1, i32 1), "QUAL.OMP.DATA"(i32* [[ARRAYIDX14]], i32 0, i32 50, i32 1) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP18]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[ARRAYIDX15:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i32 0, i32 1
// CHECK-32-NEXT:    [[TMP19:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX15]], i32 0, i32 1, i32 3) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP19]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[ARRAYIDX16:%.*]] = getelementptr inbounds [10 x [10 x i32]], [10 x [10 x i32]]* [[FOO2]], i32 0, i32 2
// CHECK-32-NEXT:    [[ARRAYIDX17:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[ARRAYIDX16]], i32 0, i32 3
// CHECK-32-NEXT:    [[TMP20:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX17]], i32 0, i32 1, i32 0) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP20]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[TMP21:%.*]] = load i32, i32* [[N_ADDR]], align 4
// CHECK-32-NEXT:    [[TMP22:%.*]] = call i8* @llvm.stacksave.p0i8()
// CHECK-32-NEXT:    store i8* [[TMP22]], i8** [[SAVED_STACK]], align 4
// CHECK-32-NEXT:    [[TMP23:%.*]] = mul nuw i32 1000, [[TMP21]]
// CHECK-32-NEXT:    [[VLA:%.*]] = alloca i16, i32 [[TMP23]], align 2
// CHECK-32-NEXT:    store i32 [[TMP21]], i32* [[__VLA_EXPR0]], align 4
// CHECK-32-NEXT:    [[TMP24:%.*]] = mul nuw i32 10, [[TMP21]]
// CHECK-32-NEXT:    [[TMP25:%.*]] = mul nsw i32 50, [[TMP24]]
// CHECK-32-NEXT:    [[ARRAYIDX18:%.*]] = getelementptr inbounds i16, i16* [[VLA]], i32 [[TMP25]]
// CHECK-32-NEXT:    [[TMP26:%.*]] = mul nsw i32 5, [[TMP21]]
// CHECK-32-NEXT:    [[ARRAYIDX19:%.*]] = getelementptr inbounds i16, i16* [[ARRAYIDX18]], i32 [[TMP26]]
// CHECK-32-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr inbounds i16, i16* [[ARRAYIDX19]], i32 0
// CHECK-32-NEXT:    [[SEC_LOWER_CAST:%.*]] = ptrtoint i16* [[ARRAYIDX20]] to i32
// CHECK-32-NEXT:    [[TMP27:%.*]] = load i32, i32* [[N_ADDR]], align 4
// CHECK-32-NEXT:    [[LB_ADD_LEN:%.*]] = add nsw i32 -1, [[TMP27]]
// CHECK-32-NEXT:    [[TMP28:%.*]] = mul nuw i32 10, [[TMP21]]
// CHECK-32-NEXT:    [[TMP29:%.*]] = mul nsw i32 50, [[TMP28]]
// CHECK-32-NEXT:    [[ARRAYIDX21:%.*]] = getelementptr inbounds i16, i16* [[VLA]], i32 [[TMP29]]
// CHECK-32-NEXT:    [[TMP30:%.*]] = mul nsw i32 7, [[TMP21]]
// CHECK-32-NEXT:    [[ARRAYIDX22:%.*]] = getelementptr inbounds i16, i16* [[ARRAYIDX21]], i32 [[TMP30]]
// CHECK-32-NEXT:    [[ARRAYIDX23:%.*]] = getelementptr inbounds i16, i16* [[ARRAYIDX22]], i32 [[LB_ADD_LEN]]
// CHECK-32-NEXT:    [[SEC_UPPER_CAST:%.*]] = ptrtoint i16* [[ARRAYIDX23]] to i32
// CHECK-32-NEXT:    [[TMP31:%.*]] = sub i32 [[SEC_UPPER_CAST]], [[SEC_LOWER_CAST]]
// CHECK-32-NEXT:    [[TMP32:%.*]] = sdiv exact i32 [[TMP31]], 2
// CHECK-32-NEXT:    [[SEC_NUMBER_OF_ELEMENTS:%.*]] = add i32 [[TMP32]], 1
// CHECK-32-NEXT:    [[TMP33:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i16* [[ARRAYIDX20]], i16 0, i32 [[SEC_NUMBER_OF_ELEMENTS]], i32 0) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP33]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    store i32** [[PTR_BASE]], i32*** [[PBREF]], align 4
// CHECK-32-NEXT:    [[TMP34:%.*]] = load i32*, i32** [[PTR_BASE]], align 4
// CHECK-32-NEXT:    [[ARRAYIDX24:%.*]] = getelementptr inbounds i32, i32* [[TMP34]], i32 3
// CHECK-32-NEXT:    [[TMP35:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX24]], i32 0, i32 10, i32 0) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP35]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[TMP36:%.*]] = load i32**, i32*** [[PBREF]], align 4
// CHECK-32-NEXT:    [[TMP37:%.*]] = load i32*, i32** [[TMP36]], align 4
// CHECK-32-NEXT:    [[ARRAYIDX25:%.*]] = getelementptr inbounds i32, i32* [[TMP37]], i32 3
// CHECK-32-NEXT:    [[TMP38:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX25]], i32 0, i32 10, i32 0) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP38]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    call void @_ZN6foobar5checkEv(%struct.foobar* noundef nonnull align 4 dereferenceable(884) @bar)
// CHECK-32-NEXT:    [[TMP39:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* getelementptr inbounds ([[STRUCT_FOOBAR:%.*]], %struct.foobar* @bar, i32 0, i32 1, i32 1), double 0.000000e+00, i32 2, i32 4) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP39]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[TMP40:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* getelementptr inbounds ([[STRUCT_FOOBAR]], %struct.foobar* @bar, i32 0, i32 1, i32 5), double 0.000000e+00, i32 1, i32 3) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP40]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[TMP41:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* getelementptr inbounds ([[STRUCT_FOOBAR]], %struct.foobar* @bar, i32 0, i32 2, i32 1, i32 0), double 0.000000e+00, i32 20, i32 4) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP41]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[TMP42:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* getelementptr inbounds ([[STRUCT_FOOBAR]], %struct.foobar* @bar, i32 0, i32 2, i32 6, i32 8), double 0.000000e+00, i32 1, i32 4) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP42]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[TMP43:%.*]] = load i8*, i8** [[SAVED_STACK]], align 4
// CHECK-32-NEXT:    call void @llvm.stackrestore.p0i8(i8* [[TMP43]])
// CHECK-32-NEXT:    ret void
//
// CHECK-LABEL: @_Z13test_prefetchm(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[N_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[FOO1:%.*]] = alloca [10 x i32], align 16
// CHECK-NEXT:    [[FOO2:%.*]] = alloca [10 x [10 x i32]], align 16
// CHECK-NEXT:    [[P:%.*]] = alloca i32*, align 8
// CHECK-NEXT:    [[SAVED_STACK:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[__VLA_EXPR0:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[PTR_BASE:%.*]] = alloca i32*, align 8
// CHECK-NEXT:    [[PBREF:%.*]] = alloca i32**, align 8
// CHECK-NEXT:    store i64 [[N:%.*]], i64* [[N_ADDR]], align 8
// CHECK-NEXT:    store i32 1, i32* [[I]], align 4
// CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i64 0, i64 0
// CHECK-NEXT:    store i32* [[ARRAYDECAY]], i32** [[P]], align 8
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i64 0, i64 0
// CHECK-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX]], i32 0, i64 1, i32 0) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i64 0, i64 1
// CHECK-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX1]], i32 0, i64 1, i32 0) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i64 0, i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX2]], i32 0, i64 2, i32 1) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP2]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i64 0, i64 0
// CHECK-NEXT:    [[TMP3:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX3]], i32 0, i64 9, i32 2) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP3]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i64 0, i64 4
// CHECK-NEXT:    [[TMP4:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX4]], i32 0, i64 8, i32 3) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP4]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, i32* [[I]], align 4
// CHECK-NEXT:    [[CONV:%.*]] = sext i32 [[TMP5]] to i64
// CHECK-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i64 0, i64 3
// CHECK-NEXT:    [[TMP6:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX5]], i32 0, i64 [[CONV]], i32 4) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP6]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i64 0, i64 0
// CHECK-NEXT:    [[TMP7:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX6]], i32 0, i64 10, i32 5) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP7]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, i32* [[I]], align 4
// CHECK-NEXT:    [[CONV7:%.*]] = sext i32 [[TMP8]] to i64
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, i32* [[I]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = sext i32 [[TMP9]] to i64
// CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i64 0, i64 [[TMP10]]
// CHECK-NEXT:    [[TMP11:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX8]], i32 0, i64 5, i32 6) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP11]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i64 0, i64 1
// CHECK-NEXT:    [[TMP12:%.*]] = load i32, i32* [[A]], align 4
// CHECK-NEXT:    [[TMP13:%.*]] = load i32, i32* [[B]], align 4
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP12]], [[TMP13]]
// CHECK-NEXT:    [[TMP14:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX9]], i32 0, i64 2, i32 1), "QUAL.OMP.IF"(i1 [[CMP]]) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP14]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[TMP15:%.*]] = load i32, i32* [[A]], align 4
// CHECK-NEXT:    [[CMP10:%.*]] = icmp eq i32 [[TMP15]], 0
// CHECK-NEXT:    [[TMP16:%.*]] = load i32, i32* [[I]], align 4
// CHECK-NEXT:    [[CONV11:%.*]] = sext i32 [[TMP16]] to i64
// CHECK-NEXT:    [[TMP17:%.*]] = load i32, i32* [[I]], align 4
// CHECK-NEXT:    [[TMP18:%.*]] = sext i32 [[TMP17]] to i64
// CHECK-NEXT:    [[ARRAYIDX12:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i64 0, i64 [[TMP18]]
// CHECK-NEXT:    [[TMP19:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.IF"(i1 [[CMP10]]), "QUAL.OMP.DATA"(i32* [[ARRAYIDX12]], i32 0, i64 3, i32 1) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP19]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[ARRAYIDX13:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i64 0, i64 0
// CHECK-NEXT:    [[ARRAYIDX14:%.*]] = getelementptr inbounds [10 x [10 x i32]], [10 x [10 x i32]]* [[FOO2]], i64 0, i64 0
// CHECK-NEXT:    [[ARRAYDECAY15:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[ARRAYIDX14]], i64 0, i64 0
// CHECK-NEXT:    [[ARRAYIDX16:%.*]] = getelementptr inbounds i32, i32* [[ARRAYDECAY15]], i64 0
// CHECK-NEXT:    [[TMP20:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX13]], i32 0, i64 1, i32 1), "QUAL.OMP.DATA"(i32* [[ARRAYIDX16]], i32 0, i64 50, i32 1) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP20]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[ARRAYIDX17:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[FOO1]], i64 0, i64 1
// CHECK-NEXT:    [[TMP21:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX17]], i32 0, i64 1, i32 3) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP21]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[ARRAYIDX18:%.*]] = getelementptr inbounds [10 x [10 x i32]], [10 x [10 x i32]]* [[FOO2]], i64 0, i64 2
// CHECK-NEXT:    [[ARRAYIDX19:%.*]] = getelementptr inbounds [10 x i32], [10 x i32]* [[ARRAYIDX18]], i64 0, i64 3
// CHECK-NEXT:    [[TMP22:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX19]], i32 0, i64 1, i32 0) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP22]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[TMP23:%.*]] = load i64, i64* [[N_ADDR]], align 8
// CHECK-NEXT:    [[TMP24:%.*]] = call i8* @llvm.stacksave.p0i8()
// CHECK-NEXT:    store i8* [[TMP24]], i8** [[SAVED_STACK]], align 8
// CHECK-NEXT:    [[TMP25:%.*]] = mul nuw i64 1000, [[TMP23]]
// CHECK-NEXT:    [[VLA:%.*]] = alloca i16, i64 [[TMP25]], align 16
// CHECK-NEXT:    store i64 [[TMP23]], i64* [[__VLA_EXPR0]], align 8
// CHECK-NEXT:    [[TMP26:%.*]] = mul nuw i64 10, [[TMP23]]
// CHECK-NEXT:    [[TMP27:%.*]] = mul nsw i64 50, [[TMP26]]
// CHECK-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr inbounds i16, i16* [[VLA]], i64 [[TMP27]]
// CHECK-NEXT:    [[TMP28:%.*]] = mul nsw i64 5, [[TMP23]]
// CHECK-NEXT:    [[ARRAYIDX21:%.*]] = getelementptr inbounds i16, i16* [[ARRAYIDX20]], i64 [[TMP28]]
// CHECK-NEXT:    [[ARRAYIDX22:%.*]] = getelementptr inbounds i16, i16* [[ARRAYIDX21]], i64 0
// CHECK-NEXT:    [[SEC_LOWER_CAST:%.*]] = ptrtoint i16* [[ARRAYIDX22]] to i64
// CHECK-NEXT:    [[TMP29:%.*]] = load i64, i64* [[N_ADDR]], align 8
// CHECK-NEXT:    [[LB_ADD_LEN:%.*]] = add nsw i64 -1, [[TMP29]]
// CHECK-NEXT:    [[TMP30:%.*]] = mul nuw i64 10, [[TMP23]]
// CHECK-NEXT:    [[TMP31:%.*]] = mul nsw i64 50, [[TMP30]]
// CHECK-NEXT:    [[ARRAYIDX23:%.*]] = getelementptr inbounds i16, i16* [[VLA]], i64 [[TMP31]]
// CHECK-NEXT:    [[TMP32:%.*]] = mul nsw i64 7, [[TMP23]]
// CHECK-NEXT:    [[ARRAYIDX24:%.*]] = getelementptr inbounds i16, i16* [[ARRAYIDX23]], i64 [[TMP32]]
// CHECK-NEXT:    [[ARRAYIDX25:%.*]] = getelementptr inbounds i16, i16* [[ARRAYIDX24]], i64 [[LB_ADD_LEN]]
// CHECK-NEXT:    [[SEC_UPPER_CAST:%.*]] = ptrtoint i16* [[ARRAYIDX25]] to i64
// CHECK-NEXT:    [[TMP33:%.*]] = sub i64 [[SEC_UPPER_CAST]], [[SEC_LOWER_CAST]]
// CHECK-NEXT:    [[TMP34:%.*]] = sdiv exact i64 [[TMP33]], 2
// CHECK-NEXT:    [[SEC_NUMBER_OF_ELEMENTS:%.*]] = add i64 [[TMP34]], 1
// CHECK-NEXT:    [[TMP35:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i16* [[ARRAYIDX22]], i16 0, i64 [[SEC_NUMBER_OF_ELEMENTS]], i32 0) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP35]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    store i32** [[PTR_BASE]], i32*** [[PBREF]], align 8
// CHECK-NEXT:    [[TMP36:%.*]] = load i32*, i32** [[PTR_BASE]], align 8
// CHECK-NEXT:    [[ARRAYIDX26:%.*]] = getelementptr inbounds i32, i32* [[TMP36]], i64 3
// CHECK-NEXT:    [[TMP37:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX26]], i32 0, i64 10, i32 0) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP37]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[TMP38:%.*]] = load i32**, i32*** [[PBREF]], align 8
// CHECK-NEXT:    [[TMP39:%.*]] = load i32*, i32** [[TMP38]], align 8
// CHECK-NEXT:    [[ARRAYIDX27:%.*]] = getelementptr inbounds i32, i32* [[TMP39]], i64 3
// CHECK-NEXT:    [[TMP40:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(i32* [[ARRAYIDX27]], i32 0, i64 10, i32 0) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP40]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    call void @_ZN6foobar5checkEv(%struct.foobar* noundef nonnull align 8 dereferenceable(888) @bar)
// CHECK-NEXT:    [[TMP41:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* getelementptr inbounds ([[STRUCT_FOOBAR:%.*]], %struct.foobar* @bar, i32 0, i32 1, i64 1), double 0.000000e+00, i64 2, i32 4) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP41]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[TMP42:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* getelementptr inbounds ([[STRUCT_FOOBAR]], %struct.foobar* @bar, i32 0, i32 1, i64 5), double 0.000000e+00, i64 1, i32 3) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP42]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[TMP43:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* getelementptr inbounds ([[STRUCT_FOOBAR]], %struct.foobar* @bar, i32 0, i32 2, i64 1, i64 0), double 0.000000e+00, i64 20, i32 4) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP43]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[TMP44:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(double* getelementptr inbounds ([[STRUCT_FOOBAR]], %struct.foobar* @bar, i32 0, i32 2, i64 6, i64 8), double 0.000000e+00, i64 1, i32 4) ]
// CHECK-NEXT:    call void @llvm.directive.region.exit(token [[TMP44]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-NEXT:    [[TMP45:%.*]] = load i8*, i8** [[SAVED_STACK]], align 8
// CHECK-NEXT:    call void @llvm.stackrestore.p0i8(i8* [[TMP45]])
// CHECK-NEXT:    ret void
//
void test_prefetch(unsigned long n) {
  int i = 1;
  int a;
  int b;
  int foo1[10];
  int foo2[10][10];
  int *p = foo1;

  //sections
  #pragma ompx prefetch data(foo1[:1])
  #pragma ompx prefetch data(0:foo1[1:1])
  #pragma ompx prefetch data(1:foo1[:2])
  #pragma ompx prefetch data(2:foo1[:9])
  #pragma ompx prefetch data(3:foo1[4:8])
  #pragma ompx prefetch data(4:foo1[3:i])
  #pragma ompx prefetch data(5:foo1[:])
  #pragma ompx prefetch data(6:foo1[i:5])

  // if clause
  #pragma ompx prefetch data(1:foo1[1:2]) if (a < b)
  #pragma ompx prefetch if (a == 0) data(1:foo1[i:3])

  // One data clause with two prefetch expressions should generate same IR
  // as prefetch with two data clauses and same expressions.
#ifndef MULTI_DATA
  #pragma ompx prefetch data(1:foo1[:1], foo2[:5][:])
#else
  #pragma ompx prefetch data(1:foo1[:1]) data(1:foo2[:5][:])
#endif

  //subscripts
  #pragma ompx prefetch data(3:foo1[1])
  #pragma ompx prefetch data(foo2[2][3])

  // vlas
  short vla[100][10][n];
  #pragma ompx prefetch data(vla[50][5:3][0:n])

  // pointers
  int *ptr_base;
  int *(&pbref) = ptr_base;
  #pragma ompx prefetch data(ptr_base[3:10])
  #pragma ompx prefetch data(pbref[3:10])

  // fields
  bar.check();
  #pragma ompx prefetch data(4:bar.d[1:2])
  #pragma ompx prefetch data(3:bar.d[5])
  #pragma ompx prefetch data(4:bar.d2[1:2][:])
  #pragma ompx prefetch data(4:bar.d2[6][8])
}

float mathfunc(float);
// CHECK-32-LABEL: @_Z14test_with_simdPfS_(
// CHECK-32-NEXT:  entry:
// CHECK-32-NEXT:    [[PTR_ADDR:%.*]] = alloca float*, align 4
// CHECK-32-NEXT:    [[A_ADDR:%.*]] = alloca float*, align 4
// CHECK-32-NEXT:    [[TMP:%.*]] = alloca i32, align 4
// CHECK-32-NEXT:    [[DOTOMP_IV:%.*]] = alloca i32, align 4
// CHECK-32-NEXT:    [[DOTOMP_LB:%.*]] = alloca i32, align 4
// CHECK-32-NEXT:    [[DOTOMP_UB:%.*]] = alloca i32, align 4
// CHECK-32-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-32-NEXT:    store float* [[PTR:%.*]], float** [[PTR_ADDR]], align 4
// CHECK-32-NEXT:    store float* [[A:%.*]], float** [[A_ADDR]], align 4
// CHECK-32-NEXT:    store i32 0, i32* [[DOTOMP_LB]], align 4
// CHECK-32-NEXT:    store i32 31, i32* [[DOTOMP_UB]], align 4
// CHECK-32-NEXT:    [[TMP0:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PARALLEL.LOOP"(), "QUAL.OMP.SHARED:TYPED"(float** [[PTR_ADDR]], float* null, i32 1), "QUAL.OMP.SHARED:TYPED"(float** [[A_ADDR]], float* null, i32 1), "QUAL.OMP.NORMALIZED.IV:TYPED"(i32* [[DOTOMP_IV]], i32 0), "QUAL.OMP.FIRSTPRIVATE:TYPED"(i32* [[DOTOMP_LB]], i32 0, i32 1), "QUAL.OMP.NORMALIZED.UB:TYPED"(i32* [[DOTOMP_UB]], i32 0), "QUAL.OMP.PRIVATE:TYPED"(i32* [[I]], i32 0, i32 1) ]
// CHECK-32-NEXT:    [[TMP1:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.SIMD"(), "QUAL.OMP.LINEAR:IV.TYPED"(i32* [[I]], i32 0, i32 1, i32 1) ]
// CHECK-32-NEXT:    [[TMP2:%.*]] = load i32, i32* [[DOTOMP_LB]], align 4
// CHECK-32-NEXT:    store i32 [[TMP2]], i32* [[DOTOMP_IV]], align 4
// CHECK-32-NEXT:    br label [[OMP_INNER_FOR_COND:%.*]]
// CHECK-32:       omp.inner.for.cond:
// CHECK-32-NEXT:    [[TMP3:%.*]] = load i32, i32* [[DOTOMP_IV]], align 4
// CHECK-32-NEXT:    [[TMP4:%.*]] = load i32, i32* [[DOTOMP_UB]], align 4
// CHECK-32-NEXT:    [[CMP:%.*]] = icmp sle i32 [[TMP3]], [[TMP4]]
// CHECK-32-NEXT:    br i1 [[CMP]], label [[OMP_INNER_FOR_BODY:%.*]], label [[OMP_INNER_FOR_END:%.*]]
// CHECK-32:       omp.inner.for.body:
// CHECK-32-NEXT:    [[TMP5:%.*]] = load i32, i32* [[DOTOMP_IV]], align 4
// CHECK-32-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP5]], 1
// CHECK-32-NEXT:    [[ADD:%.*]] = add nsw i32 0, [[MUL]]
// CHECK-32-NEXT:    store i32 [[ADD]], i32* [[I]], align 4
// CHECK-32-NEXT:    [[TMP6:%.*]] = load i32, i32* [[I]], align 4
// CHECK-32-NEXT:    [[TMP7:%.*]] = load i32, i32* [[I]], align 4
// CHECK-32-NEXT:    [[TMP8:%.*]] = load float*, float** [[A_ADDR]], align 4
// CHECK-32-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, float* [[TMP8]], i32 [[TMP7]]
// CHECK-32-NEXT:    [[TMP9:%.*]] = call token @llvm.directive.region.entry() [ "DIR.OMP.PREFETCH"(), "QUAL.OMP.DATA"(float* [[ARRAYIDX]], float 0.000000e+00, i32 32, i32 0) ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP9]]) [ "DIR.OMP.END.PREFETCH"() ]
// CHECK-32-NEXT:    [[TMP10:%.*]] = load float*, float** [[A_ADDR]], align 4
// CHECK-32-NEXT:    [[TMP11:%.*]] = load i32, i32* [[I]], align 4
// CHECK-32-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds float, float* [[TMP10]], i32 [[TMP11]]
// CHECK-32-NEXT:    [[TMP12:%.*]] = load float, float* [[ARRAYIDX1]], align 4
// CHECK-32-NEXT:    [[CALL:%.*]] = call noundef float @_Z8mathfuncf(float noundef [[TMP12]]) #[[ATTR1:[0-9]+]]
// CHECK-32-NEXT:    [[TMP13:%.*]] = load float*, float** [[PTR_ADDR]], align 4
// CHECK-32-NEXT:    [[TMP14:%.*]] = load i32, i32* [[I]], align 4
// CHECK-32-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds float, float* [[TMP13]], i32 [[TMP14]]
// CHECK-32-NEXT:    store float [[CALL]], float* [[ARRAYIDX2]], align 4
// CHECK-32-NEXT:    br label [[OMP_BODY_CONTINUE:%.*]]
// CHECK-32:       omp.body.continue:
// CHECK-32-NEXT:    br label [[OMP_INNER_FOR_INC:%.*]]
// CHECK-32:       omp.inner.for.inc:
// CHECK-32-NEXT:    [[TMP15:%.*]] = load i32, i32* [[DOTOMP_IV]], align 4
// CHECK-32-NEXT:    [[ADD3:%.*]] = add nsw i32 [[TMP15]], 1
// CHECK-32-NEXT:    store i32 [[ADD3]], i32* [[DOTOMP_IV]], align 4
// CHECK-32-NEXT:    br label [[OMP_INNER_FOR_COND]], !llvm.loop [[LOOP4:![0-9]+]]
// CHECK-32:       omp.inner.for.end:
// CHECK-32-NEXT:    br label [[OMP_LOOP_EXIT:%.*]]
// CHECK-32:       omp.loop.exit:
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP1]]) [ "DIR.OMP.END.SIMD"() ]
// CHECK-32-NEXT:    call void @llvm.directive.region.exit(token [[TMP0]]) [ "DIR.OMP.END.PARALLEL.LOOP"() ]
// CHECK-32-NEXT:    ret void
//
void test_with_simd(float *ptr, float a[]) {
  #pragma omp parallel for simd
  for (int i = 0; i < 32; ++i) {
    #pragma ompx prefetch data(a[i:32])
    ptr[i] = mathfunc(a[i]);
  }
}
#endif
// end INTEL_COLLAB
