; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -passes='gvn-hoist' -S | FileCheck %s
; Check that GVNHoist ignore unreachable successors for anticipability

define float @foo(float %a, float %b, i8 %c) {
; CHECK-LABEL: define float @foo
; CHECK-SAME: (float [[A:%.*]], float [[B:%.*]], i8 [[C:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[D:%.*]] = fsub float [[B]], [[A]]
; CHECK-NEXT:    [[E:%.*]] = fadd float [[D]], [[A]]
; CHECK-NEXT:    [[F:%.*]] = fdiv float [[E]], [[A]]
; CHECK-NEXT:    [[G:%.*]] = fmul float [[F]], [[A]]
; CHECK-NEXT:    switch i8 [[C]], label [[DEFAULT:%.*]] [
; CHECK-NEXT:    i8 1, label [[BB1:%.*]]
; CHECK-NEXT:    i8 2, label [[BB2:%.*]]
; CHECK-NEXT:    ]
; CHECK:       bb1:
; CHECK-NEXT:    ret float [[G]]
; CHECK:       bb2:
; CHECK-NEXT:    ret float [[G]]
; CHECK:       default:
; CHECK-NEXT:    unreachable
;
entry:
  switch i8 %c, label %default [
  i8 1, label %bb1
  i8 2, label %bb2
  ]

bb1:
  %d = fsub float %b, %a
  %e = fadd float %d, %a
  %f = fdiv float %e, %a
  %g = fmul float %f, %a
  ret float %g

bb2:
  %h = fsub float %b, %a
  %i = fadd float %h, %a
  %j = fdiv float %i, %a
  %k = fmul float %j, %a
  ret float %k

default:
  unreachable
}
