; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -opaque-pointers=0 < %s -passes=LowerWGScope -S | FileCheck %s

%struct.snork = type { i32 }
%struct.eggs = type { i8 }
%struct.snork.0 = type { %struct.widget, %struct.widget, %struct.widget, %struct.ham }
%struct.widget = type { %struct.wibble }
%struct.wibble = type { [3 x i64] }
%struct.ham = type { %struct.wibble }

@global = internal addrspace(3) global [12 x %struct.snork] zeroinitializer, align 4

; CHECK: @[[WG_NEXT:[a-zA-Z0-9_.]+]] = internal unnamed_addr addrspace(3) global ptr addrspace(4) undef, align 8
; CHECK: @[[WG_DONE:[a-zA-Z0-9_.]+]] = internal unnamed_addr addrspace(3) global i1 undef, align 1

define internal spir_func void @spam(ptr addrspace(4) %arg, ptr byval(%struct.snork.0) align 8 %arg1) align 2 !work_group_scope !0 {
; CHECK:       arrayctor.loop:
; CHECK-NEXT:    [[ARRAYCTOR_CUR:%.*]] = phi ptr addrspace(4) [ addrspacecast (ptr addrspace(3) @global to ptr addrspace(4)), [[WG_CF:%.*]] ], [ [[WG_VAL_ARRAYCTOR_NEXT:%.*]], [[WG_CF2:%.*]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr addrspace(1) @__spirv_BuiltInLocalInvocationIndex, align 4
; CHECK-NEXT:    call void @_Z22__spirv_ControlBarrierjjj(i32 2, i32 2, i32 272)
; CHECK-NEXT:    [[CMPZ3:%.*]] = icmp eq i64 [[TMP4]], 0
; CHECK-NEXT:    br i1 [[CMPZ3]], label [[WG_LEADER1:%.*]], label [[WG_CF2]]
; CHECK:       wg_leader1:
; CHECK-NEXT:    call spir_func void @bar(ptr addrspace(4) [[ARRAYCTOR_CUR]])
; CHECK-NEXT:    [[ARRAYCTOR_NEXT:%.*]] = getelementptr inbounds [[STRUCT_SNORK:%.*]], ptr addrspace(4) [[ARRAYCTOR_CUR]], i64 1
; CHECK-NEXT:    store ptr addrspace(4) [[ARRAYCTOR_NEXT]], ptr addrspace(3) @[[WG_NEXT]], align 8
; CHECK-NEXT:    [[ARRAYCTOR_DONE:%.*]] = icmp eq ptr addrspace(4) [[ARRAYCTOR_NEXT]], getelementptr inbounds (%struct.snork, ptr addrspace(4) addrspacecast (ptr addrspace(3) @global to ptr addrspace(4)), i64 12)
; CHECK-NEXT:    store i1 [[ARRAYCTOR_DONE]], ptr addrspace(3) @[[WG_DONE]], align 1
; CHECK-NEXT:    br label [[WG_CF2]]
; CHECK:       wg_cf2:
; CHECK-NEXT:    call void @_Z22__spirv_ControlBarrierjjj(i32 2, i32 2, i32 272) #0
; CHECK-NEXT:    [[WG_VAL_ARRAYCTOR_DONE:%.*]] = load i1, ptr addrspace(3) @[[WG_DONE]], align 1
; CHECK-NEXT:    [[WG_VAL_ARRAYCTOR_NEXT]] = load ptr addrspace(4), ptr addrspace(3) @[[WG_NEXT]], align 8
; CHECK-NEXT:    br i1 [[WG_VAL_ARRAYCTOR_DONE]], label [[ARRAYCTOR_CONT:%.*]], label [[ARRAYCTOR_LOOP:%.*]]
; CHECK:       arrayctor.cont:
; CHECK-NEXT:    ret void
;
entry:
  %tmp = alloca ptr addrspace(4), align 8
  store ptr addrspace(4) %arg, ptr %tmp, align 8
  %tmp2 = load ptr addrspace(4), ptr %tmp, align 8
  br label %arrayctor.loop

arrayctor.loop:                                              ; preds = %arrayctor.loop, %entry
  %arrayctor.cur = phi ptr addrspace(4) [ addrspacecast (ptr addrspace(3) @global to ptr addrspace(4)), %entry ], [ %arrayctor.next, %arrayctor.loop ]
  call spir_func void @bar(ptr addrspace(4) %arrayctor.cur)
  %arrayctor.next = getelementptr inbounds %struct.snork, ptr addrspace(4) %arrayctor.cur, i64 1
  %arrayctor.done = icmp eq ptr addrspace(4) %arrayctor.next, getelementptr inbounds (%struct.snork, ptr addrspace(4) addrspacecast (ptr addrspace(3) @global to ptr addrspace(4)), i64 12)
  br i1 %arrayctor.done, label %arrayctor.cont, label %arrayctor.loop

arrayctor.cont:                                   ; preds = %arrayctor.loop
  ret void
}

define linkonce_odr dso_local spir_func void @bar(ptr addrspace(4) %arg) unnamed_addr align 2 {
bb:
  %tmp = alloca ptr addrspace(4), align 8
  store ptr addrspace(4) %arg, ptr %tmp, align 8
  %tmp1 = load ptr addrspace(4), ptr %tmp, align 8
  store i32 0, ptr addrspace(4) %tmp1, align 4
  ret void
}

!0 = !{}
