; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O3 -disable-peephole -verify-machineinstrs -mcpu=alderlake -mtriple=x86_64-unknown-unknown < %s | FileCheck %s --check-prefixes=ALL,ADL
; RUN: llc -O3 -disable-peephole -verify-machineinstrs -mcpu=sapphirerapids -mtriple=x86_64-unknown-unknown < %s | FileCheck %s --check-prefixes=ALL,SPR

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-unknown"

define <8 x i32> @permd(<8 x i32> %a0, <8 x i32> %a1) {
; ADL-LABEL: permd:
; ADL:       # %bb.0:
; ADL-NEXT:    vmovups %ymm1, {{[-0-9]+}}(%r{{[sb]}}p) # 32-byte Spill
; ADL-NEXT:    vmovups %ymm0, {{[-0-9]+}}(%r{{[sb]}}p) # 32-byte Spill
; ADL-NEXT:    #APP
; ADL-NEXT:    nop
; ADL-NEXT:    #NO_APP
; ADL-NEXT:    vmovdqu {{[-0-9]+}}(%r{{[sb]}}p), %ymm1 # 32-byte Reload
; ADL-NEXT:    vmovdqu {{[-0-9]+}}(%r{{[sb]}}p), %ymm2 # 32-byte Reload
; ADL-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; ADL-NEXT:    vpermd %ymm2, %ymm1, %ymm0
; ADL-NEXT:    vpaddd %ymm1, %ymm2, %ymm1
; ADL-NEXT:    vpaddd %ymm1, %ymm0, %ymm0
; ADL-NEXT:    retq
;
; SPR-LABEL: permd:
; SPR:       # %bb.0:
; SPR-NEXT:    vmovdqa64 %ymm1, %ymm16
; SPR-NEXT:    vmovdqa64 %ymm0, %ymm17
; SPR-NEXT:    #APP
; SPR-NEXT:    nop
; SPR-NEXT:    #NO_APP
; SPR-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; SPR-NEXT:    vpermd %ymm17, %ymm16, %ymm0
; SPR-NEXT:    vpaddd %ymm16, %ymm17, %ymm1
; SPR-NEXT:    vpaddd %ymm1, %ymm0, %ymm0
; SPR-NEXT:    retq
  %1 = tail call <2 x i64> asm sideeffect "nop", "=x,~{xmm1},~{xmm2},~{xmm3},~{xmm4},~{xmm5},~{xmm6},~{xmm7},~{xmm8},~{xmm9},~{xmm10},~{xmm11},~{xmm12},~{xmm13},~{xmm14},~{xmm15},~{flags}"()
  %2 = call <8 x i32> @llvm.x86.avx2.permd(<8 x i32> %a0, <8 x i32> %a1)
  %3 = add <8 x i32> %a0, %a1
  %res = add <8 x i32> %2, %3
  ret <8 x i32> %res
}

define <8 x i32> @permd_mem(<8 x i32>* %p0, <8 x i32> %a1) {
; ADL-LABEL: permd_mem:
; ADL:       # %bb.0:
; ADL-NEXT:    vmovups %ymm0, {{[-0-9]+}}(%r{{[sb]}}p) # 32-byte Spill
; ADL-NEXT:    #APP
; ADL-NEXT:    nop
; ADL-NEXT:    #NO_APP
; ADL-NEXT:    vmovdqu {{[-0-9]+}}(%r{{[sb]}}p), %ymm1 # 32-byte Reload
; ADL-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; ADL-NEXT:    vpermd (%rdi), %ymm1, %ymm0
; ADL-NEXT:    vpaddd %ymm1, %ymm0, %ymm0
; ADL-NEXT:    retq
;
; SPR-LABEL: permd_mem:
; SPR:       # %bb.0:
; SPR-NEXT:    vmovdqa64 %ymm0, %ymm16
; SPR-NEXT:    #APP
; SPR-NEXT:    nop
; SPR-NEXT:    #NO_APP
; SPR-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; SPR-NEXT:    vpermd (%rdi), %ymm16, %ymm0
; SPR-NEXT:    vpaddd %ymm16, %ymm0, %ymm0
; SPR-NEXT:    retq
  %1 = tail call <2 x i64> asm sideeffect "nop", "=x,~{xmm1},~{xmm2},~{xmm3},~{xmm4},~{xmm5},~{xmm6},~{xmm7},~{xmm8},~{xmm9},~{xmm10},~{xmm11},~{xmm12},~{xmm13},~{xmm14},~{xmm15},~{flags}"()
  %a0 = load <8 x i32>, <8 x i32>* %p0, align 64
  %2 = call <8 x i32> @llvm.x86.avx2.permd(<8 x i32> %a0, <8 x i32> %a1)
  %res = add <8 x i32> %2, %a1
  ret <8 x i32> %res
}

declare <8 x i32> @llvm.x86.avx2.permd(<8 x i32>, <8 x i32>) nounwind readonly

define <4 x i64> @permq(<4 x i64> %a0) {
; ALL-LABEL: permq:
; ALL:       # %bb.0:
; ALL-NEXT:    #APP
; ALL-NEXT:    nop
; ALL-NEXT:    #NO_APP
; ALL-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; ALL-NEXT:    vpermq {{.*#+}} ymm1 = ymm0[1,2,1,0]
; ALL-NEXT:    vpaddq %ymm0, %ymm1, %ymm0
; ALL-NEXT:    retq
  %1 = tail call <2 x i64> asm sideeffect "nop", "=x,~{xmm2},~{xmm3},~{xmm4},~{xmm5},~{xmm6},~{xmm7},~{xmm8},~{xmm9},~{xmm10},~{xmm11},~{xmm12},~{xmm13},~{xmm14},~{xmm15},~{flags}"()
  %2 = shufflevector <4 x i64> %a0, <4 x i64> undef, <4 x i32> <i32 1, i32 2, i32 1, i32 0>
  %res = add <4 x i64> %2, %a0
  ret <4 x i64> %res
}

define <4 x i64> @permq_mem(<4 x i64>* %p0) {
; ALL-LABEL: permq_mem:
; ALL:       # %bb.0:
; ALL-NEXT:    #APP
; ALL-NEXT:    nop
; ALL-NEXT:    #NO_APP
; ALL-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; ALL-NEXT:    vpermpd {{.*#+}} ymm0 = mem[1,2,1,0]
; ALL-NEXT:    retq
  %1 = tail call <2 x i64> asm sideeffect "nop", "=x,~{xmm1},~{xmm2},~{xmm3},~{xmm4},~{xmm5},~{xmm6},~{xmm7},~{xmm8},~{xmm9},~{xmm10},~{xmm11},~{xmm12},~{xmm13},~{xmm14},~{xmm15},~{flags}"()
  %a0 = load <4 x i64>, <4 x i64>* %p0, align 64
  %2 = shufflevector <4 x i64> %a0, <4 x i64> undef, <4 x i32> <i32 1, i32 2, i32 1, i32 0>
  ret <4 x i64> %2
}

define <8 x float> @permps(<8 x float> %a0, <8 x i32> %a1) {
; ADL-LABEL: permps:
; ADL:       # %bb.0:
; ADL-NEXT:    vmovups %ymm0, {{[-0-9]+}}(%r{{[sb]}}p) # 32-byte Spill
; ADL-NEXT:    #APP
; ADL-NEXT:    nop
; ADL-NEXT:    #NO_APP
; ADL-NEXT:    vmovups {{[-0-9]+}}(%r{{[sb]}}p), %ymm2 # 32-byte Reload
; ADL-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; ADL-NEXT:    vpermps %ymm2, %ymm0, %ymm1
; ADL-NEXT:    vcvtdq2ps %ymm0, %ymm0
; ADL-NEXT:    vaddps %ymm2, %ymm0, %ymm0
; ADL-NEXT:    vaddps %ymm0, %ymm1, %ymm0
; ADL-NEXT:    retq
;
; SPR-LABEL: permps:
; SPR:       # %bb.0:
; SPR-NEXT:    vmovaps %ymm0, %ymm16
; SPR-NEXT:    #APP
; SPR-NEXT:    nop
; SPR-NEXT:    #NO_APP
; SPR-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; SPR-NEXT:    vpermps %ymm16, %ymm0, %ymm1
; SPR-NEXT:    vcvtdq2ps %ymm0, %ymm0
; SPR-NEXT:    vaddps %ymm16, %ymm0, %ymm0
; SPR-NEXT:    vaddps %ymm0, %ymm1, %ymm0
; SPR-NEXT:    retq
  %1 = tail call <8 x i32> asm sideeffect "nop", "=x,~{xmm1},~{xmm2},~{xmm3},~{xmm4},~{xmm5},~{xmm6},~{xmm7},~{xmm8},~{xmm9},~{xmm10},~{xmm11},~{xmm12},~{xmm13},~{xmm14},~{xmm15},~{flags}"()
  %2 = call <8 x float> @llvm.x86.avx2.permps(<8 x float> %a0, <8 x i32> %1)
  %t = sitofp <8 x i32> %1 to <8 x float>
  %3 = fadd <8 x float> %t, %a0
  %res = fadd <8 x float> %2, %3
  ret <8 x float> %res
}

define <8 x float> @permps_mem(<8 x float>* %p0, <8 x i32> %a1) {
; ALL-LABEL: permps_mem:
; ALL:       # %bb.0:
; ALL-NEXT:    #APP
; ALL-NEXT:    nop
; ALL-NEXT:    #NO_APP
; ALL-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; ALL-NEXT:    vpermps (%rdi), %ymm0, %ymm1
; ALL-NEXT:    vcvtdq2ps %ymm0, %ymm0
; ALL-NEXT:    vaddps %ymm0, %ymm1, %ymm0
; ALL-NEXT:    retq
  %1 = tail call <2 x i64> asm sideeffect "nop", "=x,~{xmm2},~{xmm3},~{xmm4},~{xmm5},~{xmm6},~{xmm7},~{xmm8},~{xmm9},~{xmm10},~{xmm11},~{xmm12},~{xmm13},~{xmm14},~{xmm15},~{flags}"()
  %a0 = load <8 x float>, <8 x float>* %p0, align 64
  %2 = call <8 x float> @llvm.x86.avx2.permps(<8 x float> %a0, <8 x i32> %a1)
  %t = sitofp <8 x i32> %a1 to <8 x float>
  %res = fadd <8 x float> %2, %t
  ret <8 x float> %res
}

declare <8 x float> @llvm.x86.avx2.permps(<8 x float>, <8 x i32>) nounwind readonly

define <4 x double> @permpd(<4 x double> %a0) {
; ALL-LABEL: permpd:
; ALL:       # %bb.0:
; ALL-NEXT:    #APP
; ALL-NEXT:    nop
; ALL-NEXT:    #NO_APP
; ALL-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; ALL-NEXT:    vpermpd {{.*#+}} ymm1 = ymm0[1,2,1,0]
; ALL-NEXT:    vaddpd %ymm0, %ymm1, %ymm0
; ALL-NEXT:    retq
  %1 = tail call <2 x i64> asm sideeffect "nop", "=x,~{xmm2},~{xmm3},~{xmm4},~{xmm5},~{xmm6},~{xmm7},~{xmm8},~{xmm9},~{xmm10},~{xmm11},~{xmm12},~{xmm13},~{xmm14},~{xmm15},~{flags}"()
  %2 = shufflevector <4 x double> %a0, <4 x double> undef, <4 x i32> <i32 1, i32 2, i32 1, i32 0>
  %res = fadd <4 x double> %2, %a0
  ret <4 x double> %res
}

define <4 x double> @permpd_mem(<4 x double>* %p0) {
; ALL-LABEL: permpd_mem:
; ALL:       # %bb.0:
; ALL-NEXT:    #APP
; ALL-NEXT:    nop
; ALL-NEXT:    #NO_APP
; ALL-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; ALL-NEXT:    vpermpd {{.*#+}} ymm0 = mem[1,2,1,0]
; ALL-NEXT:    retq
  %1 = tail call <2 x i64> asm sideeffect "nop", "=x,~{xmm1},~{xmm2},~{xmm3},~{xmm4},~{xmm5},~{xmm6},~{xmm7},~{xmm8},~{xmm9},~{xmm10},~{xmm11},~{xmm12},~{xmm13},~{xmm14},~{xmm15},~{flags}"()
  %a0 = load <4 x double>, <4 x double>* %p0, align 64
  %2 = shufflevector <4 x double> %a0, <4 x double> undef, <4 x i32> <i32 1, i32 2, i32 1, i32 0>
  ret <4 x double> %2
}
