//==----- Passes.h - SYCL Kernel transforms pass headers -------*- C++ -*-===//
//
// Copyright (C) 2020 Intel Corporation. All rights reserved.
//
// The information and source code contained herein is the exclusive property
// of Intel Corporation and may not be disclosed, examined or reproduced in
// whole or in part without explicit written authorization from the company.
//
// ===--------------------------------------------------------------------=== //
#ifndef LLVM_TRANSFORMS_SYCLTRANSFORMS_PASSES_H
#define LLVM_TRANSFORMS_SYCLTRANSFORMS_PASSES_H

#include "llvm/Transforms/SYCLTransforms/AddFastMath.h"
#include "llvm/Transforms/SYCLTransforms/AddFunctionAttrs.h"
#include "llvm/Transforms/SYCLTransforms/AddImplicitArgs.h"
#include "llvm/Transforms/SYCLTransforms/AddNTAttr.h"
#include "llvm/Transforms/SYCLTransforms/AddTLSGlobals.h"
#include "llvm/Transforms/SYCLTransforms/AutorunReplicator.h"
#include "llvm/Transforms/SYCLTransforms/BarrierInFunctionPass.h"
#include "llvm/Transforms/SYCLTransforms/BarrierPass.h"
#include "llvm/Transforms/SYCLTransforms/BuiltinCallToInst.h"
#include "llvm/Transforms/SYCLTransforms/BuiltinImport.h"
#include "llvm/Transforms/SYCLTransforms/BuiltinLICM.h"
#include "llvm/Transforms/SYCLTransforms/BuiltinLibInfoAnalysis.h"
#include "llvm/Transforms/SYCLTransforms/ChannelPipeTransformation.h"
#include "llvm/Transforms/SYCLTransforms/CleanupWrappedKernel.h"
#include "llvm/Transforms/SYCLTransforms/CoerceTypes.h"
#include "llvm/Transforms/SYCLTransforms/CoerceWin64Types.h"
#include "llvm/Transforms/SYCLTransforms/DataPerBarrierPass.h"
#include "llvm/Transforms/SYCLTransforms/DataPerValuePass.h"
#include "llvm/Transforms/SYCLTransforms/DeduceMaxWGDim.h"
#include "llvm/Transforms/SYCLTransforms/DetectRecursion.h"
#include "llvm/Transforms/SYCLTransforms/DuplicateCalledKernelsPass.h"
#include "llvm/Transforms/SYCLTransforms/ExternalizeGlobalVariables.h"
#include "llvm/Transforms/SYCLTransforms/GroupBuiltinPass.h"
#include "llvm/Transforms/SYCLTransforms/ImplicitGID.h"
#include "llvm/Transforms/SYCLTransforms/InferArgumentAlias.h"
#include "llvm/Transforms/SYCLTransforms/InfiniteLoopCreator.h"
#include "llvm/Transforms/SYCLTransforms/InstToFuncCall.h"
#include "llvm/Transforms/SYCLTransforms/InternalizeGlobalVariables.h"
#include "llvm/Transforms/SYCLTransforms/InternalizeNonKernelFunc.h"
#include "llvm/Transforms/SYCLTransforms/KernelTargetExtTypeLower.h"
#include "llvm/Transforms/SYCLTransforms/LinearIdResolver.h"
#include "llvm/Transforms/SYCLTransforms/LocalBuffers.h"
#include "llvm/Transforms/SYCLTransforms/LoopStridedCodeMotion.h"
#include "llvm/Transforms/SYCLTransforms/LoopWIAnalysis.h"
#include "llvm/Transforms/SYCLTransforms/MathFuncSelect.h"
#include "llvm/Transforms/SYCLTransforms/OptimizeIDivAndIRem.h"
#include "llvm/Transforms/SYCLTransforms/PatchCallbackArgs.h"
#include "llvm/Transforms/SYCLTransforms/PhiCanonicalization.h"
#include "llvm/Transforms/SYCLTransforms/PipeIOTransformation.h"
#include "llvm/Transforms/SYCLTransforms/PipeOrdering.h"
#include "llvm/Transforms/SYCLTransforms/PipeSupport.h"
#include "llvm/Transforms/SYCLTransforms/PrepareKernelArgs.h"
#include "llvm/Transforms/SYCLTransforms/PreventDivCrashes.h"
#include "llvm/Transforms/SYCLTransforms/ProfilingInfo.h"
#include "llvm/Transforms/SYCLTransforms/ReduceCrossBarrierValues.h"
#include "llvm/Transforms/SYCLTransforms/RedundantPhiNodePass.h"
#include "llvm/Transforms/SYCLTransforms/RelaxedMath.h"
#include "llvm/Transforms/SYCLTransforms/RemoveAtexit.h"
#include "llvm/Transforms/SYCLTransforms/RemoveDeviceLibAssertFallback.h"
#include "llvm/Transforms/SYCLTransforms/RemoveDuplicatedBarrier.h"
#include "llvm/Transforms/SYCLTransforms/ReplaceScalarWithMask.h"
#include "llvm/Transforms/SYCLTransforms/ReqdSubGroupSize.h"
#include "llvm/Transforms/SYCLTransforms/ResolveSubGroupWICall.h"
#include "llvm/Transforms/SYCLTransforms/ResolveVarTIDCall.h"
#include "llvm/Transforms/SYCLTransforms/ResolveWICall.h"
#include "llvm/Transforms/SYCLTransforms/SGRemapWICall.h"
#include "llvm/Transforms/SYCLTransforms/SYCLAliasAnalysis.h"
#include "llvm/Transforms/SYCLTransforms/SYCLEqualizer.h"
#include "llvm/Transforms/SYCLTransforms/SYCLKernelAnalysis.h"
#include "llvm/Transforms/SYCLTransforms/SYCLKernelWGLoopCreator.h"
#include "llvm/Transforms/SYCLTransforms/SYCLPreprocessSPIRVFriendlyIR.h"
#include "llvm/Transforms/SYCLTransforms/SYCLRewritePipes.h"
#include "llvm/Transforms/SYCLTransforms/SetPreferVectorWidth.h"
#include "llvm/Transforms/SYCLTransforms/SetVectorizationFactor.h"
#include "llvm/Transforms/SYCLTransforms/SoaAllocaAnalysis.h"
#include "llvm/Transforms/SYCLTransforms/SpecializeConstant.h"
#include "llvm/Transforms/SYCLTransforms/SplitBBonBarrierPass.h"
#include "llvm/Transforms/SYCLTransforms/SubgroupEmulation/SGBarrierPropagate.h"
#include "llvm/Transforms/SYCLTransforms/SubgroupEmulation/SGBarrierSimplify.h"
#include "llvm/Transforms/SYCLTransforms/SubgroupEmulation/SGBuiltin.h"
#include "llvm/Transforms/SYCLTransforms/SubgroupEmulation/SGLoopConstruct.h"
#include "llvm/Transforms/SYCLTransforms/SubgroupEmulation/SGSizeAnalysis.h"
#include "llvm/Transforms/SYCLTransforms/SubgroupEmulation/SGValueWiden.h"
#include "llvm/Transforms/SYCLTransforms/VFAnalysis.h"
#include "llvm/Transforms/SYCLTransforms/WGLoopBoundaries.h"
#include "llvm/Transforms/SYCLTransforms/WeightedInstCount.h"
#include "llvm/Transforms/SYCLTransforms/WorkItemAnalysis.h"

#if INTEL_CUSTOMIZATION
#include "llvm/Transforms/SYCLTransforms/Intel_HandleVPlanMask.h"
#include "llvm/Transforms/SYCLTransforms/Intel_ResolveMatrixFill.h"
#include "llvm/Transforms/SYCLTransforms/Intel_ResolveMatrixLayout.h"
#include "llvm/Transforms/SYCLTransforms/Intel_ResolveMatrixWISlice.h"
#include "llvm/Transforms/SYCLTransforms/Intel_SYCLKernelPostVec.h"
#include "llvm/Transforms/SYCLTransforms/Intel_SYCLKernelVecClone.h"
#include "llvm/Transforms/SYCLTransforms/Intel_SYCLPrepareKernelForVecClone.h"
#include "llvm/Transforms/SYCLTransforms/Intel_SinCosFold.h"
#include "llvm/Transforms/SYCLTransforms/Intel_TaskSeqAsyncHandling.h"
#include "llvm/Transforms/SYCLTransforms/Intel_VectorKernelElimination.h"
#include "llvm/Transforms/SYCLTransforms/Intel_VectorVariant/CreateSimdVariantPropagation.h"
#include "llvm/Transforms/SYCLTransforms/Intel_VectorVariant/IndirectCallLowering.h"
#include "llvm/Transforms/SYCLTransforms/Intel_VectorVariant/SGSizeCollector.h"
#include "llvm/Transforms/SYCLTransforms/Intel_VectorVariant/SGSizeCollectorIndirect.h"
#include "llvm/Transforms/SYCLTransforms/Intel_VectorVariant/UpdateCallAttrs.h"
#include "llvm/Transforms/SYCLTransforms/Intel_VectorVariant/VectorVariantFillIn.h"
#include "llvm/Transforms/SYCLTransforms/Intel_VectorVariant/VectorVariantLowering.h"
#include "llvm/Transforms/SYCLTransforms/Intel_VectorizationDimensionAnalysis.h"
#endif // INTEL_CUSTOMIZATION

#endif // LLVM_TRANSFORMS_SYCLTRANSFORMS_PASSES_H
