; RUN: SATest -BUILD --config=%s.cfg -tsize=0 | FileCheck %s -check-prefix=CHECK-LOG
; RUN: SATest -BUILD --config=%s.cfg -tsize=0 -llvm-option=-print-before=dpcpp-kernel-builtin-import 2>&1 | FileCheck %s

; CHECK-LOG: Test program was successfully built.

; CHECK: call {{.*}}@_Z11atomic_initPU3AS4VU7_Atomicii
; CHECK: call {{.*}}@_Z11atomic_initPU3AS4VU7_Atomicjj
; CHECK: call {{.*}}@_Z11atomic_initPU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z11atomic_initPU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z11atomic_initPU3AS4VU7_Atomicff
; CHECK: call {{.*}}@_Z11atomic_initPU3AS4VU7_Atomicdd
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storePU3AS4VU7_Atomicii
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS4VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS4VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storePU3AS4VU7_Atomicjj
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS4VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS4VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storePU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storePU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storePU3AS4VU7_Atomicff
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS4VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS4VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storePU3AS4VU7_Atomicdd
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS4VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS4VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadPU3AS4VU7_Atomici
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS4VU7_Atomici12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS4VU7_Atomici12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadPU3AS4VU7_Atomicj
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS4VU7_Atomicj12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS4VU7_Atomicj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadPU3AS4VU7_Atomicl
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS4VU7_Atomicl12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS4VU7_Atomicl12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadPU3AS4VU7_Atomicm
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS4VU7_Atomicm12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS4VU7_Atomicm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadPU3AS4VU7_Atomicf
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS4VU7_Atomicf12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS4VU7_Atomicf12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadPU3AS4VU7_Atomicd
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS4VU7_Atomicd12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS4VU7_Atomicd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangePU3AS4VU7_Atomicii
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS4VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS4VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangePU3AS4VU7_Atomicjj
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS4VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS4VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangePU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangePU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangePU3AS4VU7_Atomicff
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS4VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS4VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangePU3AS4VU7_Atomicdd
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS4VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS4VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addPU3AS4VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addPU3AS4VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addPU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addPU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS3VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS3VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS3VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS3VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_subPU3AS4VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS4VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS4VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_subPU3AS4VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS4VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS4VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_subPU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_subPU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orPU3AS4VU7_Atomicii
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS4VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS4VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orPU3AS4VU7_Atomicjj
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS4VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS4VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orPU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orPU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorPU3AS4VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS4VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS4VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorPU3AS4VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS4VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS4VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorPU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorPU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andPU3AS4VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS4VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS4VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andPU3AS4VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS4VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS4VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andPU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andPU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minPU3AS4VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minPU3AS4VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minPU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minPU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS3VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS3VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS3VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS3VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxPU3AS4VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxPU3AS4VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxPU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxPU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addPU3AS4VU7_Atomicml
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicml12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS4VU7_Atomicml12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_subPU3AS4VU7_Atomicml
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS4VU7_Atomicml12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS4VU7_Atomicml12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orPU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orPU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andPU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andPU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxPU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxPU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS4VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS3VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS3VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS3VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS3VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minPU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minPU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorPU3AS4VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS4VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS4VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorPU3AS4VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS4VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS4VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z24atomic_flag_test_and_setPU3AS4VU7_Atomici
; CHECK: call {{.*}}@_Z33atomic_flag_test_and_set_explicitPU3AS4VU7_Atomici12memory_order
; CHECK: call {{.*}}@_Z33atomic_flag_test_and_set_explicitPU3AS4VU7_Atomici12memory_order12memory_scope
; CHECK: call {{.*}}@_Z17atomic_flag_clearPU3AS4VU7_Atomici
; CHECK: call {{.*}}@_Z26atomic_flag_clear_explicitPU3AS4VU7_Atomici12memory_order
; CHECK: call {{.*}}@_Z26atomic_flag_clear_explicitPU3AS4VU7_Atomici12memory_order12memory_scope
