; RUN: SATest -BUILD --config=%s.cfg -tsize=0 | FileCheck %s -check-prefix=CHECK-LOG
; RUN: SATest -BUILD --config=%s.cfg -tsize=0 -llvm-option=-print-before=dpcpp-kernel-analysis 2>&1 | FileCheck %s

; CHECK-LOG: Test program was successfully built.

; CHECK: call {{.*}}@_Z11atomic_initPU3AS1VU7_Atomicii
; CHECK: call {{.*}}@_Z11atomic_initPU3AS1VU7_Atomicjj
; CHECK: call {{.*}}@_Z11atomic_initPU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z11atomic_initPU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z11atomic_initPU3AS1VU7_Atomicff
; CHECK: call {{.*}}@_Z11atomic_initPU3AS1VU7_Atomicdd
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomiciPii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiciPii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiciPii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomiciPU3AS1ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiciPU3AS1ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiciPU3AS1ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomiciPU3AS3ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiciPU3AS3ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiciPU3AS3ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomiciPii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiciPii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiciPii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicjPjj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicjPjj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicjPjj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicjPU3AS1jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicjPU3AS1jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicjPU3AS1jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicjPU3AS3jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicjPU3AS3jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicjPU3AS3jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicjPjj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicjPjj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicjPjj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomiclPll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiclPll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiclPll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomiclPU3AS1ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiclPU3AS1ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiclPU3AS1ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomiclPU3AS3ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiclPU3AS3ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiclPU3AS3ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomiclPll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiclPll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomiclPll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicmPmm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicmPmm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicmPmm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicmPU3AS1mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicmPU3AS1mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicmPU3AS1mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicmPU3AS3mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicmPU3AS3mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicmPU3AS3mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicmPmm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicmPmm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicmPmm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicfPff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicfPff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicfPff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicfPU3AS1ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicfPU3AS1ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicfPU3AS1ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicfPU3AS3ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicfPU3AS3ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicfPU3AS3ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicfPff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicfPff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicfPff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicdPdd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicdPdd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicdPdd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicdPU3AS1dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicdPU3AS1dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicdPU3AS1dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicdPU3AS3dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicdPU3AS3dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicdPU3AS3dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS1VU7_AtomicdPdd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicdPdd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS1VU7_AtomicdPdd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomiciPii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiciPii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiciPii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomiciPU3AS1ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiciPU3AS1ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiciPU3AS1ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomiciPU3AS3ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiciPU3AS3ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiciPU3AS3ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomiciPii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiciPii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiciPii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicjPjj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicjPjj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicjPjj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicjPU3AS1jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicjPU3AS1jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicjPU3AS1jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicjPU3AS3jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicjPU3AS3jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicjPU3AS3jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicjPjj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicjPjj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicjPjj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomiclPll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiclPll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiclPll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomiclPU3AS1ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiclPU3AS1ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiclPU3AS1ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomiclPU3AS3ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiclPU3AS3ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiclPU3AS3ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomiclPll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiclPll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomiclPll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicmPmm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicmPmm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicmPmm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicmPU3AS1mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicmPU3AS1mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicmPU3AS1mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicmPU3AS3mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicmPU3AS3mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicmPU3AS3mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicmPmm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicmPmm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicmPmm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicfPff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicfPff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicfPff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicfPU3AS1ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicfPU3AS1ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicfPU3AS1ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicfPU3AS3ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicfPU3AS3ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicfPU3AS3ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicfPff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicfPff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicfPff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicdPdd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicdPdd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicdPdd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicdPU3AS1dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicdPU3AS1dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicdPU3AS1dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicdPU3AS3dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicdPU3AS3dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicdPU3AS3dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS1VU7_AtomicdPdd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicdPdd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS1VU7_AtomicdPdd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storePU3AS1VU7_Atomicii
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS1VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS1VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storePU3AS1VU7_Atomicjj
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS1VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS1VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storePU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storePU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storePU3AS1VU7_Atomicff
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS1VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS1VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storePU3AS1VU7_Atomicdd
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS1VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitPU3AS1VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadPU3AS1VU7_Atomici
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS1VU7_Atomici12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS1VU7_Atomici12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadPU3AS1VU7_Atomicj
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS1VU7_Atomicj12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS1VU7_Atomicj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadPU3AS1VU7_Atomicl
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS1VU7_Atomicl12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS1VU7_Atomicl12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadPU3AS1VU7_Atomicm
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS1VU7_Atomicm12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS1VU7_Atomicm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadPU3AS1VU7_Atomicf
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS1VU7_Atomicf12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS1VU7_Atomicf12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadPU3AS1VU7_Atomicd
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS1VU7_Atomicd12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitPU3AS1VU7_Atomicd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangePU3AS1VU7_Atomicii
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS1VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS1VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangePU3AS1VU7_Atomicjj
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS1VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS1VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangePU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangePU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangePU3AS1VU7_Atomicff
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS1VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS1VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangePU3AS1VU7_Atomicdd
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS1VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitPU3AS1VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addPU3AS1VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addPU3AS1VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addPU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addPU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope

; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicdd12memory_order12memory_scope

; Generic address space will be translated to global address space
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicdd12memory_order12memory_scope

; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS3VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS3VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS3VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS3VU7_Atomicdd12memory_order12memory_scope

; CHECK: call {{.*}}@_Z16atomic_fetch_subPU3AS1VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS1VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS1VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_subPU3AS1VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS1VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS1VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_subPU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_subPU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orPU3AS1VU7_Atomicii
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS1VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS1VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orPU3AS1VU7_Atomicjj
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS1VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS1VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orPU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orPU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorPU3AS1VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS1VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS1VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorPU3AS1VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS1VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS1VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorPU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorPU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andPU3AS1VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS1VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS1VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andPU3AS1VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS1VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS1VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andPU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andPU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minPU3AS1VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minPU3AS1VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minPU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minPU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope

; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicdd12memory_order12memory_scope

; Generic address space will be translated to global address space
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicdd12memory_order12memory_scope

; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS3VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS3VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS3VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS3VU7_Atomicdd12memory_order12memory_scope


; CHECK: call {{.*}}@_Z16atomic_fetch_maxPU3AS1VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxPU3AS1VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxPU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxPU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addPU3AS1VU7_Atomicml
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicml12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitPU3AS1VU7_Atomicml12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_subPU3AS1VU7_Atomicml
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS1VU7_Atomicml12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitPU3AS1VU7_Atomicml12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orPU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orPU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andPU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andPU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxPU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxPU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope

; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicdd12memory_order12memory_scope

; Generic address space will be translated to global address space
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS1VU7_Atomicdd12memory_order12memory_scope

; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS3VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS3VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS3VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitPU3AS3VU7_Atomicdd12memory_order12memory_scope


; CHECK: call {{.*}}@_Z16atomic_fetch_minPU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minPU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorPU3AS1VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS1VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS1VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorPU3AS1VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS1VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitPU3AS1VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z24atomic_flag_test_and_setPU3AS1VU7_Atomici
; CHECK: call {{.*}}@_Z33atomic_flag_test_and_set_explicitPU3AS1VU7_Atomici12memory_order
; CHECK: call {{.*}}@_Z33atomic_flag_test_and_set_explicitPU3AS1VU7_Atomici12memory_order12memory_scope
; CHECK: call {{.*}}@_Z17atomic_flag_clearPU3AS1VU7_Atomici
; CHECK: call {{.*}}@_Z26atomic_flag_clear_explicitPU3AS1VU7_Atomici12memory_order
; CHECK: call {{.*}}@_Z26atomic_flag_clear_explicitPU3AS1VU7_Atomici12memory_order12memory_scope
