#include "stdafx.h"
#include "MemoryAllocator/MemoryObjectFactory.h"
#include "MemoryAllocator/SingleUnifiedBuffer.h"
#include "MemoryAllocator/SingleUnifiedImage2D.h"
#include "MemoryAllocator/SingleUnifiedImage3D.h"
#include "MemoryAllocator/SingleUnifiedImage2DArray.h"
#if defined (_WIN32)
#include "gl_sharing/gl_buffer.h"
#include "gl_sharing/gl_texture2D.h"
#include "gl_sharing/gl_texture3D.h"
#include "gl_sharing/gl_render_buffer.h"
#if defined (DX9_SHARING)
#include "d3d9_sharing/d3d9_resource.h"
#include "CL/cl_d3d9.h"
#endif
#endif

using namespace Intel::OpenCL::Framework;

REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_NONE, CL_MEM_OBJECT_BUFFER, SingleUnifiedBuffer)
REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_NONE, CL_MEM_OBJECT_IMAGE2D, SingleUnifiedImage2D)
REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_NONE, CL_MEM_OBJECT_IMAGE3D, SingleUnifiedImage3D)
REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_NONE, CL_MEM_OBJECT_IMAGE2D_ARRAY, SingleUnifiedImage2DArray)

#if defined (_WIN32)
REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_GL, CL_GL_OBJECT_BUFFER, GLBuffer)
REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_GL, CL_GL_OBJECT_TEXTURE2D, GLTexture2D)
REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_GL, CL_GL_OBJECT_TEXTURE3D, GLTexture3D)
REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_GL, CL_GL_OBJECT_RENDERBUFFER, GLRenderBuffer)

#if defined (DX9_SHARING)
REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_DX9, CL_D3D9_OBJECT_VERTEX_BUFFER, D3D9VertexBuffer);
REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_DX9, CL_D3D9_OBJECT_INDEX_BUFFER, D3D9IndexBuffer);
REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_DX9, CL_D3D9_OBJECT_SURFACE, D3D9Surface);
REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_DX9, CL_D3D9_OBJECT_TEXTURE, D3D9Texture);
REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_DX9, CL_D3D9_OBJECT_CUBE_TEXTURE, D3D9CubeTexture);
REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_CPU, CL_MEMOBJ_GFX_SHARE_DX9, CL_D3D9_OBJECT_VOLUME_TEXTURE, D3D9VolumeTexture);
#endif
#endif

#if defined (INCLUDE_ACCELERATOR_SUPPORT)
    #include "MemoryAllocator/GenericMemObj.h"

    REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_ACCELERATOR, CL_MEMOBJ_GFX_SHARE_NONE, CL_MEM_OBJECT_BUFFER, GenericMemObject)
    //REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_ACCELERATOR, CL_MEMOBJ_GFX_SHARE_NONE, CL_MEM_OBJECT_IMAGE2D, GenericMemObject)
    //REGISTER_MEMORY_OBJECT_CREATOR(CL_DEVICE_TYPE_ACCELERATOR, CL_MEMOBJ_GFX_SHARE_NONE, CL_MEM_OBJECT_IMAGE3D, GenericMemObject)
#endif

