; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; Check IMF precision attribute is handled correctly, and make sure medium
; accuracy is used in fast math by default, scalarizarion is used in non-fast-math.

; RUN: opt -bugpoint-enable-legacy-pm -mtriple=x86_64-unknown-linux-gnu -vector-library=SVML -S -iml-trans < %s 2>&1 | FileCheck %s --check-prefixes=CHECK,HAS-REF
; RUN: opt -bugpoint-enable-legacy-pm -mtriple=i386-unknown-linux-gnu -mattr=+sse2 -vector-library=SVML -S -iml-trans < %s 2>&1 | FileCheck %s --check-prefixes=CHECK,NO-REF
; RUN: opt -bugpoint-enable-legacy-pm -mtriple=x86_64-pc-windows-coff -vector-library=SVML -S -iml-trans < %s 2>&1 | FileCheck %s --check-prefixes=CHECK,NO-REF
; RUN: opt -bugpoint-enable-legacy-pm -mtriple=i386-pc-windows-coff -mattr=+sse2 -vector-library=SVML -S -iml-trans < %s 2>&1 | FileCheck %s --check-prefixes=CHECK,NO-REF

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

define void @default_accuracy_no_fastmath(double %c) {
; CHECK-LABEL: define {{[^@]+}}@default_accuracy_no_fastmath(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[ARG:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = call double @exp(double [[ARG]])
; CHECK-NEXT:    [[ARG1:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = call double @exp(double [[ARG1]])
; CHECK-NEXT:    [[ARG2:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = call double @exp(double [[ARG2]])
; CHECK-NEXT:    [[ARG3:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = call double @exp(double [[ARG3]])
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x double> undef, double [[TMP1]], i32 0
; CHECK-NEXT:    [[INS4:%.*]] = insertelement <4 x double> [[INS]], double [[TMP2]], i32 1
; CHECK-NEXT:    [[INS5:%.*]] = insertelement <4 x double> [[INS4]], double [[TMP3]], i32 2
; CHECK-NEXT:    [[INS6:%.*]] = insertelement <4 x double> [[INS5]], double [[TMP4]], i32 3
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #1
  ret void
}

define void @default_accuracy_fastmath(double %c) {
; CHECK-LABEL: define {{[^@]+}}@default_accuracy_fastmath(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_0_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[VCALL:%.*]] = call fast svml_cc <2 x double> @__svml_exp2(<2 x double> [[BROADCAST_SPLAT_PART_0_OF_2_]])
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_1_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[VCALL1:%.*]] = call fast svml_cc <2 x double> @__svml_exp2(<2 x double> [[BROADCAST_SPLAT_PART_1_OF_2_]])
; CHECK-NEXT:    [[SHUFFLE_COMB:%.*]] = shufflevector <2 x double> [[VCALL]], <2 x double> [[VCALL1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call fast svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #1
  ret void
}

define void @low_accuracy_no_fastmath(double %c) {
; CHECK-LABEL: define {{[^@]+}}@low_accuracy_no_fastmath(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[ARG:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = call double @exp(double [[ARG]])
; CHECK-NEXT:    [[ARG1:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = call double @exp(double [[ARG1]])
; CHECK-NEXT:    [[ARG2:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = call double @exp(double [[ARG2]])
; CHECK-NEXT:    [[ARG3:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = call double @exp(double [[ARG3]])
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x double> undef, double [[TMP1]], i32 0
; CHECK-NEXT:    [[INS4:%.*]] = insertelement <4 x double> [[INS]], double [[TMP2]], i32 1
; CHECK-NEXT:    [[INS5:%.*]] = insertelement <4 x double> [[INS4]], double [[TMP3]], i32 2
; CHECK-NEXT:    [[INS6:%.*]] = insertelement <4 x double> [[INS5]], double [[TMP4]], i32 3
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #2
  ret void
}

define void @low_accuracy_fastmath(double %c) {
; CHECK-LABEL: define {{[^@]+}}@low_accuracy_fastmath(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_0_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[VCALL:%.*]] = call fast svml_cc <2 x double> @__svml_exp2_ep(<2 x double> [[BROADCAST_SPLAT_PART_0_OF_2_]])
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_1_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[VCALL1:%.*]] = call fast svml_cc <2 x double> @__svml_exp2_ep(<2 x double> [[BROADCAST_SPLAT_PART_1_OF_2_]])
; CHECK-NEXT:    [[SHUFFLE_COMB:%.*]] = shufflevector <2 x double> [[VCALL]], <2 x double> [[VCALL1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call fast svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #2
  ret void
}

define void @medium_accuracy_no_fastmath(double %c) {
; CHECK-LABEL: define {{[^@]+}}@medium_accuracy_no_fastmath(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[ARG:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = call double @exp(double [[ARG]])
; CHECK-NEXT:    [[ARG1:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = call double @exp(double [[ARG1]])
; CHECK-NEXT:    [[ARG2:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = call double @exp(double [[ARG2]])
; CHECK-NEXT:    [[ARG3:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = call double @exp(double [[ARG3]])
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x double> undef, double [[TMP1]], i32 0
; CHECK-NEXT:    [[INS4:%.*]] = insertelement <4 x double> [[INS]], double [[TMP2]], i32 1
; CHECK-NEXT:    [[INS5:%.*]] = insertelement <4 x double> [[INS4]], double [[TMP3]], i32 2
; CHECK-NEXT:    [[INS6:%.*]] = insertelement <4 x double> [[INS5]], double [[TMP4]], i32 3
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #3
  ret void
}

define void @medium_accuracy_fastmath(double %c) {
; CHECK-LABEL: define {{[^@]+}}@medium_accuracy_fastmath(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_0_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[VCALL:%.*]] = call fast svml_cc <2 x double> @__svml_exp2(<2 x double> [[BROADCAST_SPLAT_PART_0_OF_2_]])
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_1_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[VCALL1:%.*]] = call fast svml_cc <2 x double> @__svml_exp2(<2 x double> [[BROADCAST_SPLAT_PART_1_OF_2_]])
; CHECK-NEXT:    [[SHUFFLE_COMB:%.*]] = shufflevector <2 x double> [[VCALL]], <2 x double> [[VCALL1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call fast svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #3
  ret void
}

define void @high_accuracy_no_fastmath(double %c) {
; CHECK-LABEL: define {{[^@]+}}@high_accuracy_no_fastmath(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[ARG:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = call double @exp(double [[ARG]])
; CHECK-NEXT:    [[ARG1:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = call double @exp(double [[ARG1]])
; CHECK-NEXT:    [[ARG2:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = call double @exp(double [[ARG2]])
; CHECK-NEXT:    [[ARG3:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = call double @exp(double [[ARG3]])
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x double> undef, double [[TMP1]], i32 0
; CHECK-NEXT:    [[INS4:%.*]] = insertelement <4 x double> [[INS]], double [[TMP2]], i32 1
; CHECK-NEXT:    [[INS5:%.*]] = insertelement <4 x double> [[INS4]], double [[TMP3]], i32 2
; CHECK-NEXT:    [[INS6:%.*]] = insertelement <4 x double> [[INS5]], double [[TMP4]], i32 3
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #4
  ret void
}

define void @high_accuracy_fastmath(double %c) {
; CHECK-LABEL: define {{[^@]+}}@high_accuracy_fastmath(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_0_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[VCALL:%.*]] = call fast svml_cc <2 x double> @__svml_exp2_ha(<2 x double> [[BROADCAST_SPLAT_PART_0_OF_2_]])
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_1_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[VCALL1:%.*]] = call fast svml_cc <2 x double> @__svml_exp2_ha(<2 x double> [[BROADCAST_SPLAT_PART_1_OF_2_]])
; CHECK-NEXT:    [[SHUFFLE_COMB:%.*]] = shufflevector <2 x double> [[VCALL]], <2 x double> [[VCALL1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call fast svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #4
  ret void
}

define void @reference_accuracy_no_fastmath(double %c) {
; CHECK-LABEL: define {{[^@]+}}@reference_accuracy_no_fastmath(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[ARG:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = call double @exp(double [[ARG]])
; CHECK-NEXT:    [[ARG1:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = call double @exp(double [[ARG1]])
; CHECK-NEXT:    [[ARG2:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = call double @exp(double [[ARG2]])
; CHECK-NEXT:    [[ARG3:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = call double @exp(double [[ARG3]])
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x double> undef, double [[TMP1]], i32 0
; CHECK-NEXT:    [[INS4:%.*]] = insertelement <4 x double> [[INS]], double [[TMP2]], i32 1
; CHECK-NEXT:    [[INS5:%.*]] = insertelement <4 x double> [[INS4]], double [[TMP3]], i32 2
; CHECK-NEXT:    [[INS6:%.*]] = insertelement <4 x double> [[INS5]], double [[TMP4]], i32 3
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #5
  ret void
}

define void @reference_accuracy_fastmath(double %c) {
; HAS-REF-LABEL: define {{[^@]+}}@reference_accuracy_fastmath(
; HAS-REF-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; HAS-REF-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; HAS-REF-NEXT:    [[BROADCAST_SPLAT_PART_0_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 0, i32 1>
; HAS-REF-NEXT:    [[VCALL:%.*]] = call fast svml_cc <2 x double> @__svml_exp2_rf_ex(<2 x double> [[BROADCAST_SPLAT_PART_0_OF_2_]])
; HAS-REF-NEXT:    [[BROADCAST_SPLAT_PART_1_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 2, i32 3>
; HAS-REF-NEXT:    [[VCALL1:%.*]] = call fast svml_cc <2 x double> @__svml_exp2_rf_ex(<2 x double> [[BROADCAST_SPLAT_PART_1_OF_2_]])
; HAS-REF-NEXT:    [[SHUFFLE_COMB:%.*]] = shufflevector <2 x double> [[VCALL]], <2 x double> [[VCALL1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; HAS-REF-NEXT:    ret void
;
; NO-REF-LABEL: define {{[^@]+}}@reference_accuracy_fastmath(
; NO-REF-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; NO-REF-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; NO-REF-NEXT:    [[BROADCAST_SPLAT_PART_0_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 0, i32 1>
; NO-REF-NEXT:    [[VCALL:%.*]] = call fast svml_cc <2 x double> @__svml_exp2_ha(<2 x double> [[BROADCAST_SPLAT_PART_0_OF_2_]])
; NO-REF-NEXT:    [[BROADCAST_SPLAT_PART_1_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 2, i32 3>
; NO-REF-NEXT:    [[VCALL1:%.*]] = call fast svml_cc <2 x double> @__svml_exp2_ha(<2 x double> [[BROADCAST_SPLAT_PART_1_OF_2_]])
; NO-REF-NEXT:    [[SHUFFLE_COMB:%.*]] = shufflevector <2 x double> [[VCALL]], <2 x double> [[VCALL1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; NO-REF-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call fast svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #5
  ret void
}

define void @default_accuracy_afn(double %c) {
; CHECK-LABEL: define {{[^@]+}}@default_accuracy_afn(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_0_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[VCALL:%.*]] = call afn svml_cc <2 x double> @__svml_exp2(<2 x double> [[BROADCAST_SPLAT_PART_0_OF_2_]])
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_1_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[VCALL1:%.*]] = call afn svml_cc <2 x double> @__svml_exp2(<2 x double> [[BROADCAST_SPLAT_PART_1_OF_2_]])
; CHECK-NEXT:    [[SHUFFLE_COMB:%.*]] = shufflevector <2 x double> [[VCALL]], <2 x double> [[VCALL1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call afn svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #1
  ret void
}

define void @low_accuracy_afn(double %c) {
; CHECK-LABEL: define {{[^@]+}}@low_accuracy_afn(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_0_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[VCALL:%.*]] = call afn svml_cc <2 x double> @__svml_exp2_ep(<2 x double> [[BROADCAST_SPLAT_PART_0_OF_2_]])
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_1_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[VCALL1:%.*]] = call afn svml_cc <2 x double> @__svml_exp2_ep(<2 x double> [[BROADCAST_SPLAT_PART_1_OF_2_]])
; CHECK-NEXT:    [[SHUFFLE_COMB:%.*]] = shufflevector <2 x double> [[VCALL]], <2 x double> [[VCALL1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call afn svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #2
  ret void
}

define void @medium_accuracy_afn(double %c) {
; CHECK-LABEL: define {{[^@]+}}@medium_accuracy_afn(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_0_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[VCALL:%.*]] = call afn svml_cc <2 x double> @__svml_exp2(<2 x double> [[BROADCAST_SPLAT_PART_0_OF_2_]])
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_1_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[VCALL1:%.*]] = call afn svml_cc <2 x double> @__svml_exp2(<2 x double> [[BROADCAST_SPLAT_PART_1_OF_2_]])
; CHECK-NEXT:    [[SHUFFLE_COMB:%.*]] = shufflevector <2 x double> [[VCALL]], <2 x double> [[VCALL1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call afn svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #3
  ret void
}

define void @high_accuracy_afn(double %c) {
; CHECK-LABEL: define {{[^@]+}}@high_accuracy_afn(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_0_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[VCALL:%.*]] = call afn svml_cc <2 x double> @__svml_exp2_ha(<2 x double> [[BROADCAST_SPLAT_PART_0_OF_2_]])
; CHECK-NEXT:    [[BROADCAST_SPLAT_PART_1_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[VCALL1:%.*]] = call afn svml_cc <2 x double> @__svml_exp2_ha(<2 x double> [[BROADCAST_SPLAT_PART_1_OF_2_]])
; CHECK-NEXT:    [[SHUFFLE_COMB:%.*]] = shufflevector <2 x double> [[VCALL]], <2 x double> [[VCALL1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call afn svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #4
  ret void
}

define void @reference_accuracy_afn(double %c) {
; HAS-REF-LABEL: define {{[^@]+}}@reference_accuracy_afn(
; HAS-REF-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; HAS-REF-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; HAS-REF-NEXT:    [[BROADCAST_SPLAT_PART_0_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 0, i32 1>
; HAS-REF-NEXT:    [[VCALL:%.*]] = call afn svml_cc <2 x double> @__svml_exp2_rf_ex(<2 x double> [[BROADCAST_SPLAT_PART_0_OF_2_]])
; HAS-REF-NEXT:    [[BROADCAST_SPLAT_PART_1_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 2, i32 3>
; HAS-REF-NEXT:    [[VCALL1:%.*]] = call afn svml_cc <2 x double> @__svml_exp2_rf_ex(<2 x double> [[BROADCAST_SPLAT_PART_1_OF_2_]])
; HAS-REF-NEXT:    [[SHUFFLE_COMB:%.*]] = shufflevector <2 x double> [[VCALL]], <2 x double> [[VCALL1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; HAS-REF-NEXT:    ret void
;
; NO-REF-LABEL: define {{[^@]+}}@reference_accuracy_afn(
; NO-REF-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; NO-REF-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; NO-REF-NEXT:    [[BROADCAST_SPLAT_PART_0_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 0, i32 1>
; NO-REF-NEXT:    [[VCALL:%.*]] = call afn svml_cc <2 x double> @__svml_exp2_ha(<2 x double> [[BROADCAST_SPLAT_PART_0_OF_2_]])
; NO-REF-NEXT:    [[BROADCAST_SPLAT_PART_1_OF_2_:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLAT]], <4 x double> undef, <2 x i32> <i32 2, i32 3>
; NO-REF-NEXT:    [[VCALL1:%.*]] = call afn svml_cc <2 x double> @__svml_exp2_ha(<2 x double> [[BROADCAST_SPLAT_PART_1_OF_2_]])
; NO-REF-NEXT:    [[SHUFFLE_COMB:%.*]] = shufflevector <2 x double> [[VCALL]], <2 x double> [[VCALL1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; NO-REF-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call afn svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #5
  ret void
}

define void @default_accuracy_noafn(double %c) {
; CHECK-LABEL: define {{[^@]+}}@default_accuracy_noafn(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[ARG:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG]])
; CHECK-NEXT:    [[ARG1:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG1]])
; CHECK-NEXT:    [[ARG2:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG2]])
; CHECK-NEXT:    [[ARG3:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG3]])
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x double> undef, double [[TMP1]], i32 0
; CHECK-NEXT:    [[INS4:%.*]] = insertelement <4 x double> [[INS]], double [[TMP2]], i32 1
; CHECK-NEXT:    [[INS5:%.*]] = insertelement <4 x double> [[INS4]], double [[TMP3]], i32 2
; CHECK-NEXT:    [[INS6:%.*]] = insertelement <4 x double> [[INS5]], double [[TMP4]], i32 3
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call reassoc nnan ninf nsz arcp contract svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #1
  ret void
}

define void @low_accuracy_noafn(double %c) {
; CHECK-LABEL: define {{[^@]+}}@low_accuracy_noafn(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[ARG:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG]])
; CHECK-NEXT:    [[ARG1:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG1]])
; CHECK-NEXT:    [[ARG2:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG2]])
; CHECK-NEXT:    [[ARG3:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG3]])
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x double> undef, double [[TMP1]], i32 0
; CHECK-NEXT:    [[INS4:%.*]] = insertelement <4 x double> [[INS]], double [[TMP2]], i32 1
; CHECK-NEXT:    [[INS5:%.*]] = insertelement <4 x double> [[INS4]], double [[TMP3]], i32 2
; CHECK-NEXT:    [[INS6:%.*]] = insertelement <4 x double> [[INS5]], double [[TMP4]], i32 3
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call reassoc nnan ninf nsz arcp contract svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #2
  ret void
}

define void @medium_accuracy_noafn(double %c) {
; CHECK-LABEL: define {{[^@]+}}@medium_accuracy_noafn(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[ARG:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG]])
; CHECK-NEXT:    [[ARG1:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG1]])
; CHECK-NEXT:    [[ARG2:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG2]])
; CHECK-NEXT:    [[ARG3:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG3]])
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x double> undef, double [[TMP1]], i32 0
; CHECK-NEXT:    [[INS4:%.*]] = insertelement <4 x double> [[INS]], double [[TMP2]], i32 1
; CHECK-NEXT:    [[INS5:%.*]] = insertelement <4 x double> [[INS4]], double [[TMP3]], i32 2
; CHECK-NEXT:    [[INS6:%.*]] = insertelement <4 x double> [[INS5]], double [[TMP4]], i32 3
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call reassoc nnan ninf nsz arcp contract svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #3
  ret void
}

define void @high_accuracy_noafn(double %c) {
; CHECK-LABEL: define {{[^@]+}}@high_accuracy_noafn(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[ARG:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG]])
; CHECK-NEXT:    [[ARG1:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG1]])
; CHECK-NEXT:    [[ARG2:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG2]])
; CHECK-NEXT:    [[ARG3:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG3]])
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x double> undef, double [[TMP1]], i32 0
; CHECK-NEXT:    [[INS4:%.*]] = insertelement <4 x double> [[INS]], double [[TMP2]], i32 1
; CHECK-NEXT:    [[INS5:%.*]] = insertelement <4 x double> [[INS4]], double [[TMP3]], i32 2
; CHECK-NEXT:    [[INS6:%.*]] = insertelement <4 x double> [[INS5]], double [[TMP4]], i32 3
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call reassoc nnan ninf nsz arcp contract svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #4
  ret void
}

define void @reference_accuracy_noafn(double %c) {
; CHECK-LABEL: define {{[^@]+}}@reference_accuracy_noafn(
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x double> undef, double [[C:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x double> [[BROADCAST_SPLATINSERT]], <4 x double> undef, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[ARG:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG]])
; CHECK-NEXT:    [[ARG1:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 1
; CHECK-NEXT:    [[TMP2:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG1]])
; CHECK-NEXT:    [[ARG2:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG2]])
; CHECK-NEXT:    [[ARG3:%.*]] = extractelement <4 x double> [[BROADCAST_SPLAT]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = call reassoc nnan ninf nsz arcp contract double @exp(double [[ARG3]])
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x double> undef, double [[TMP1]], i32 0
; CHECK-NEXT:    [[INS4:%.*]] = insertelement <4 x double> [[INS]], double [[TMP2]], i32 1
; CHECK-NEXT:    [[INS5:%.*]] = insertelement <4 x double> [[INS4]], double [[TMP3]], i32 2
; CHECK-NEXT:    [[INS6:%.*]] = insertelement <4 x double> [[INS5]], double [[TMP4]], i32 3
; CHECK-NEXT:    ret void
;
  %broadcast.splatinsert = insertelement <4 x double> undef, double %c, i32 0
  %broadcast.splat = shufflevector <4 x double> %broadcast.splatinsert, <4 x double> undef, <4 x i32> zeroinitializer
  %vec_call = call reassoc nnan ninf nsz arcp contract svml_cc <4 x double> @__svml_exp4(<4 x double> %broadcast.splat) #5
  ret void
}

declare <4 x double> @__svml_exp4(<4 x double>)

attributes #1 = { nounwind }
attributes #2 = { nounwind "imf-precision"="low" }
attributes #3 = { nounwind "imf-precision"="medium" }
attributes #4 = { nounwind "imf-precision"="high" }
attributes #5 = { nounwind "imf-precision"="reference" }
