; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; Check illegal mask argument for non-512 svml is widen
; RUN: opt -bugpoint-enable-legacy-pm -vector-library=SVML -iml-trans -S < %s | FileCheck %s

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define <4 x double> @test_cexp2_mask_split_to_avx2(<4 x double> %A, <2 x i64> %0) #0 {
; CHECK-LABEL: define <4 x double> @test_cexp2_mask_split_to_avx2
; CHECK-SAME: (<4 x double> [[A:%.*]], <2 x i64> [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[MASK_WIDEN_REPLICATE:%.*]] = shufflevector <2 x i64> [[TMP0]], <2 x i64> undef, <4 x i32> <i32 0, i32 0, i32 1, i32 1>
; CHECK-NEXT:    [[VCALL:%.*]] = call fast svml_avx_cc <4 x double> @__svml_cexp2_mask_e9(<4 x double> [[A]], <4 x i64> [[MASK_WIDEN_REPLICATE]])
; CHECK-NEXT:    ret <4 x double> [[VCALL]]
;
entry:
  %1 = tail call fast svml_cc <4 x double> @__svml_cexp2_mask(<4 x double> %A, <2 x i64> %0)
  ret <4 x double> %1
}

define <8 x float> @test_cexpf4_mask_split_to_avx2(<8 x float> %A, <4 x i32> %0) #0 {
; CHECK-LABEL: define <8 x float> @test_cexpf4_mask_split_to_avx2
; CHECK-SAME: (<8 x float> [[A:%.*]], <4 x i32> [[TMP0:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[MASK_WIDEN_REPLICATE:%.*]] = shufflevector <4 x i32> [[TMP0]], <4 x i32> undef, <8 x i32> <i32 0, i32 0, i32 1, i32 1, i32 2, i32 2, i32 3, i32 3>
; CHECK-NEXT:    [[VCALL:%.*]] = call fast svml_avx_cc <8 x float> @__svml_cexpf4_mask_e9(<8 x float> [[A]], <8 x i32> [[MASK_WIDEN_REPLICATE]])
; CHECK-NEXT:    ret <8 x float> [[VCALL]]
;
entry:
  %1 = tail call fast svml_cc <8 x float> @__svml_cexpf4_mask(<8 x float> %A, <4 x i32> %0)
  ret <8 x float> %1
}

declare svml_cc <4 x double> @__svml_cexp2_mask(<4 x double>, <2 x i64>)
declare svml_cc <8 x float> @__svml_cexpf4_mask(<8 x float>, <4 x i32>)

attributes #0 = { uwtable "disable-tail-calls"="false" "less-precise-fpmad"="false" "min-legal-vector-width"="512" "prefer-vector-width"="256" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="skylake-avx512" "target-features"="+adx,+aes,+avx,+avx2,+avx512bw,+avx512cd,+avx512dq,+avx512f,+avx512vl,+bmi,+bmi2,+clflushopt,+clwb,+cx16,+cx8,+f16c,+fma,+fsgsbase,+fxsr,+invpcid,+lzcnt,+mmx,+movbe,+pclmul,+pku,+popcnt,+prfchw,+rdrnd,+rdseed,+sahf,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+ssse3,+x87,+xsave,+xsavec,+xsaveopt,+xsaves" "unsafe-fp-math"="false" "use-soft-float"="false" }
