; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; Check SVML calls absent in the library falls back to scalarized calls with "f16" suffix.
; RUN: opt -bugpoint-enable-legacy-pm -vector-library=SVML -iml-trans -S < %s | FileCheck %s

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define <4 x half> @test_frexp(<4 x half> %A) #0 {
; CHECK-LABEL: define {{[^@]+}}@test_frexp(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARG:%.*]] = extractelement <4 x half> [[A:%.*]], i32 0
; CHECK-NEXT:    [[TMP0:%.*]] = call fast half @frexpf16(half [[ARG]])
; CHECK-NEXT:    [[ARG1:%.*]] = extractelement <4 x half> [[A]], i32 1
; CHECK-NEXT:    [[TMP1:%.*]] = call fast half @frexpf16(half [[ARG1]])
; CHECK-NEXT:    [[ARG2:%.*]] = extractelement <4 x half> [[A]], i32 2
; CHECK-NEXT:    [[TMP2:%.*]] = call fast half @frexpf16(half [[ARG2]])
; CHECK-NEXT:    [[ARG3:%.*]] = extractelement <4 x half> [[A]], i32 3
; CHECK-NEXT:    [[TMP3:%.*]] = call fast half @frexpf16(half [[ARG3]])
; CHECK-NEXT:    [[INS:%.*]] = insertelement <4 x half> undef, half [[TMP0]], i32 0
; CHECK-NEXT:    [[INS4:%.*]] = insertelement <4 x half> [[INS]], half [[TMP1]], i32 1
; CHECK-NEXT:    [[INS5:%.*]] = insertelement <4 x half> [[INS4]], half [[TMP2]], i32 2
; CHECK-NEXT:    [[INS6:%.*]] = insertelement <4 x half> [[INS5]], half [[TMP3]], i32 3
; CHECK-NEXT:    ret <4 x half> [[INS6]]
;
entry:
  %0 = tail call fast svml_cc <4 x half> @__svml_frexps4(<4 x half> %A)
  ret <4 x half> %0
}

declare <4 x half> @__svml_frexps4(<4 x half>)

attributes #0 = { uwtable "disable-tail-calls"="false" "less-precise-fpmad"="false" "min-legal-vector-width"="256" "prefer-vector-width"="256" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="skylake-avx512" "target-features"="+adx,+aes,+avx,+avx2,+avx512bw,+avx512cd,+avx512dq,+avx512f,+avx512vl,+avx512fp16,+bmi,+bmi2,+clflushopt,+clwb,+cx16,+cx8,+f16c,+fma,+fsgsbase,+fxsr,+invpcid,+lzcnt,+mmx,+movbe,+mpx,+pclmul,+pku,+popcnt,+prfchw,+rdrnd,+rdseed,+sahf,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+ssse3,+x87,+xsave,+xsavec,+xsaveopt,+xsaves" "unsafe-fp-math"="false" "use-soft-float"="false" }
