; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; int rayobject_bb_intersect_test(
; float *pt1x, float *pt1y, float *pt1z,
; float *pt2x, float *pt2y, float *pt2z, str *dist
;)
;{
;  float t1x = *pt1x; float t1y = *pt1y; float t1z = *pt1z;
;  float t2x = *pt2x; float t2y = *pt2y; float t2z = *pt2z;
;  if (t1x > t2y  || t2x < t1y  || t1x > t2z ||
;      t2x < t1z || t1y > t2z || t2y < t1z) return 0;
;  if (t2x < 0.0f || t2y < 0.0f || t2z < 0.0f) return 0;
;  if (t1x > dist->b || t1y > dist->b || t1z > dist->b) return 0;
;  return 1;
;}
;
; =>
;
;  if (t2x < 0.0f | t2y < 0.0f | t2z < 0.0f) return 0;  // "|" => select-cmp
;  if (t1x > dist->b || t1y > dist->b || t1z > dist->b) return 0;
;  if (t1x > t2y  || t2x < t1y  || t1x > t2z ||
;      t2x < t1z || t1y > t2z || t2y < t1z) return 0;
;
; The || patterns form a "ladder" of 12 blocks. The false branches go the
; the next ladder block, and the true branch goes to an exit block.
; All the blocks can be reordered w.r.t each other.

; RUN: opt -passes="simplifycfg" < %s -S | FileCheck %s

; Updating note: most of the allocas and temp loads/stores in the first block
; can be cut off. Only T1/2, RETVAL, DIST_ADDR, CLEANUP_DEST_SLOT need defs.

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"


%struct.str = type { float, float }

@.str = private unnamed_addr constant [22 x i8] c"%f %f %f %f %f %f %d\0A\00", align 1

; Function Attrs: noinline nounwind uwtable
define dso_local i32 @rayobject_bb_intersect_test(ptr %pt1x, ptr %pt1y, ptr %pt1z, ptr %pt2x, ptr %pt2y, ptr %pt2z, ptr %dist) #0 {
; CHECK-LABEL: @rayobject_bb_intersect_test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[PT1X_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    [[PT1Y_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    [[PT1Z_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    [[PT2X_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    [[PT2Y_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    [[PT2Z_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    [[DIST_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    [[T1X:%.*]] = alloca float, align 4
; CHECK-NEXT:    [[T1Y:%.*]] = alloca float, align 4
; CHECK-NEXT:    [[T1Z:%.*]] = alloca float, align 4
; CHECK-NEXT:    [[T2X:%.*]] = alloca float, align 4
; CHECK-NEXT:    [[T2Y:%.*]] = alloca float, align 4
; CHECK-NEXT:    [[T2Z:%.*]] = alloca float, align 4
; CHECK-NEXT:    [[CLEANUP_DEST_SLOT:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store ptr [[PT1X:%.*]], ptr [[PT1X_ADDR]], align 8
; CHECK-NEXT:    store ptr [[PT1Y:%.*]], ptr [[PT1Y_ADDR]], align 8
; CHECK-NEXT:    store ptr [[PT1Z:%.*]], ptr [[PT1Z_ADDR]], align 8
; CHECK-NEXT:    store ptr [[PT2X:%.*]], ptr [[PT2X_ADDR]], align 8
; CHECK-NEXT:    store ptr [[PT2Y:%.*]], ptr [[PT2Y_ADDR]], align 8
; CHECK-NEXT:    store ptr [[PT2Z:%.*]], ptr [[PT2Z_ADDR]], align 8
; CHECK-NEXT:    store ptr [[DIST:%.*]], ptr [[DIST_ADDR]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[T1X]])
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[PT1X_ADDR]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[TMP0]], align 4
; CHECK-NEXT:    store float [[TMP1]], ptr [[T1X]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[T1Y]])
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[PT1Y_ADDR]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = load float, ptr [[TMP2]], align 4
; CHECK-NEXT:    store float [[TMP3]], ptr [[T1Y]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[T1Z]])
; CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[PT1Z_ADDR]], align 8
; CHECK-NEXT:    [[TMP5:%.*]] = load float, ptr [[TMP4]], align 4
; CHECK-NEXT:    store float [[TMP5]], ptr [[T1Z]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[T2X]])
; CHECK-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[PT2X_ADDR]], align 8
; CHECK-NEXT:    [[TMP7:%.*]] = load float, ptr [[TMP6]], align 4
; CHECK-NEXT:    store float [[TMP7]], ptr [[T2X]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[T2Y]])
; CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[PT2Y_ADDR]], align 8
; CHECK-NEXT:    [[TMP9:%.*]] = load float, ptr [[TMP8]], align 4
; CHECK-NEXT:    store float [[TMP9]], ptr [[T2Y]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[T2Z]])
; CHECK-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[PT2Z_ADDR]], align 8
; CHECK-NEXT:    [[TMP11:%.*]] = load float, ptr [[TMP10]], align 4
; CHECK-NEXT:    store float [[TMP11]], ptr [[T2Z]], align 4
; CHECK-NEXT:    [[TMP12:%.*]] = load float, ptr [[T2X]], align 4
; CHECK-NEXT:    [[CMP10:%.*]] = fcmp fast olt float [[TMP12]], 0.000000e+00
; CHECK-NEXT:    [[TMP13:%.*]] = load float, ptr [[T2Y]], align 4
; CHECK-NEXT:    [[CMP12:%.*]] = fcmp fast olt float [[TMP13]], 0.000000e+00
; CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[CMP10]], i1 true, i1 [[CMP12]]
; CHECK-NEXT:    [[TMP14:%.*]] = load float, ptr [[T2Z]], align 4
; CHECK-NEXT:    [[CMP14:%.*]] = fcmp fast olt float [[TMP14]], 0.000000e+00
; CHECK-NEXT:    [[OR_COND1:%.*]] = select i1 [[OR_COND]], i1 true, i1 [[CMP14]]
; CHECK-NEXT:    br i1 [[OR_COND1]], label [[IF_THEN15:%.*]], label [[IF_END16:%.*]]
; CHECK:       if.end16:
; CHECK-NEXT:    [[TMP15:%.*]] = load float, ptr [[T1X]], align 4
; CHECK-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[DIST_ADDR]], align 8
; CHECK-NEXT:    [[B:%.*]] = getelementptr inbounds [[STRUCT_STR:%.*]], ptr [[TMP16]], i32 0, i32 1
; CHECK-NEXT:    [[TMP17:%.*]] = load float, ptr [[B]], align 4
; CHECK-NEXT:    [[CMP17:%.*]] = fcmp fast ogt float [[TMP15]], [[TMP17]]
; CHECK-NEXT:    br i1 [[CMP17]], label [[IF_THEN24:%.*]], label [[LOR_LHS_FALSE18:%.*]]
; CHECK:       lor.lhs.false18:
; CHECK-NEXT:    [[TMP18:%.*]] = load float, ptr [[T1Y]], align 4
; CHECK-NEXT:    [[TMP19:%.*]] = load ptr, ptr [[DIST_ADDR]], align 8
; CHECK-NEXT:    [[B19:%.*]] = getelementptr inbounds [[STRUCT_STR]], ptr [[TMP19]], i32 0, i32 1
; CHECK-NEXT:    [[TMP20:%.*]] = load float, ptr [[B19]], align 4
; CHECK-NEXT:    [[CMP20:%.*]] = fcmp fast ogt float [[TMP18]], [[TMP20]]
; CHECK-NEXT:    br i1 [[CMP20]], label [[IF_THEN24]], label [[LOR_LHS_FALSE21:%.*]]
; CHECK:       lor.lhs.false21:
; CHECK-NEXT:    [[TMP21:%.*]] = load float, ptr [[T1Z]], align 4
; CHECK-NEXT:    [[TMP22:%.*]] = load ptr, ptr [[DIST_ADDR]], align 8
; CHECK-NEXT:    [[B22:%.*]] = getelementptr inbounds [[STRUCT_STR]], ptr [[TMP22]], i32 0, i32 1
; CHECK-NEXT:    [[TMP23:%.*]] = load float, ptr [[B22]], align 4
; CHECK-NEXT:    [[CMP23:%.*]] = fcmp fast ogt float [[TMP21]], [[TMP23]]
; CHECK-NEXT:    br i1 [[CMP23]], label [[IF_THEN24]], label [[LADDER:%.*]]
; CHECK:       ladder:
; CHECK-NEXT:    [[TMP24:%.*]] = load float, ptr [[T1X]], align 4
; CHECK-NEXT:    [[TMP25:%.*]] = load float, ptr [[T2Y]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp fast ogt float [[TMP24]], [[TMP25]]
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[LOR_LHS_FALSE:%.*]]
; CHECK:       lor.lhs.false:
; CHECK-NEXT:    [[TMP26:%.*]] = load float, ptr [[T2X]], align 4
; CHECK-NEXT:    [[TMP27:%.*]] = load float, ptr [[T1Y]], align 4
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp fast olt float [[TMP26]], [[TMP27]]
; CHECK-NEXT:    br i1 [[CMP1]], label [[IF_THEN]], label [[LOR_LHS_FALSE2:%.*]]
; CHECK:       lor.lhs.false2:
; CHECK-NEXT:    [[TMP28:%.*]] = load float, ptr [[T1X]], align 4
; CHECK-NEXT:    [[TMP29:%.*]] = load float, ptr [[T2Z]], align 4
; CHECK-NEXT:    [[CMP3:%.*]] = fcmp fast ogt float [[TMP28]], [[TMP29]]
; CHECK-NEXT:    br i1 [[CMP3]], label [[IF_THEN]], label [[LOR_LHS_FALSE4:%.*]]
; CHECK:       lor.lhs.false4:
; CHECK-NEXT:    [[TMP30:%.*]] = load float, ptr [[T2X]], align 4
; CHECK-NEXT:    [[TMP31:%.*]] = load float, ptr [[T1Z]], align 4
; CHECK-NEXT:    [[CMP5:%.*]] = fcmp fast olt float [[TMP30]], [[TMP31]]
; CHECK-NEXT:    br i1 [[CMP5]], label [[IF_THEN]], label [[LOR_LHS_FALSE6:%.*]]
; CHECK:       lor.lhs.false6:
; CHECK-NEXT:    [[TMP32:%.*]] = load float, ptr [[T1Y]], align 4
; CHECK-NEXT:    [[TMP33:%.*]] = load float, ptr [[T2Z]], align 4
; CHECK-NEXT:    [[CMP7:%.*]] = fcmp fast ogt float [[TMP32]], [[TMP33]]
; CHECK-NEXT:    br i1 [[CMP7]], label [[IF_THEN]], label [[LOR_LHS_FALSE8:%.*]]
; CHECK:       lor.lhs.false8:
; CHECK-NEXT:    [[TMP34:%.*]] = load float, ptr [[T2Y]], align 4
; CHECK-NEXT:    [[TMP35:%.*]] = load float, ptr [[T1Z]], align 4
; CHECK-NEXT:    [[CMP9:%.*]] = fcmp fast olt float [[TMP34]], [[TMP35]]
; CHECK-NEXT:    br i1 [[CMP9]], label [[IF_THEN]], label [[IF_END25:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    store i32 0, ptr [[RETVAL]], align 4
; CHECK-NEXT:    store i32 1, ptr [[CLEANUP_DEST_SLOT]], align 4
; CHECK-NEXT:    br label [[CLEANUP:%.*]]
; CHECK:       if.then15:
; CHECK-NEXT:    store i32 0, ptr [[RETVAL]], align 4
; CHECK-NEXT:    store i32 1, ptr [[CLEANUP_DEST_SLOT]], align 4
; CHECK-NEXT:    br label [[CLEANUP]]
; CHECK:       if.then24:
; CHECK-NEXT:    store i32 0, ptr [[RETVAL]], align 4
; CHECK-NEXT:    store i32 1, ptr [[CLEANUP_DEST_SLOT]], align 4
; CHECK-NEXT:    br label [[CLEANUP]]
; CHECK:       if.end25:
; CHECK-NEXT:    store i32 1, ptr [[RETVAL]], align 4
; CHECK-NEXT:    store i32 1, ptr [[CLEANUP_DEST_SLOT]], align 4
; CHECK-NEXT:    br label [[CLEANUP]]
; CHECK:       cleanup:
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[T2Z]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[T2Y]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[T2X]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[T1Z]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[T1Y]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[T1X]])
; CHECK-NEXT:    [[TMP36:%.*]] = load i32, ptr [[RETVAL]], align 4
; CHECK-NEXT:    ret i32 [[TMP36]]
;
entry:
  %retval = alloca i32, align 4
  %pt1x.addr = alloca ptr, align 8
  %pt1y.addr = alloca ptr, align 8
  %pt1z.addr = alloca ptr, align 8
  %pt2x.addr = alloca ptr, align 8
  %pt2y.addr = alloca ptr, align 8
  %pt2z.addr = alloca ptr, align 8
  %dist.addr = alloca ptr, align 8
  %t1x = alloca float, align 4
  %t1y = alloca float, align 4
  %t1z = alloca float, align 4
  %t2x = alloca float, align 4
  %t2y = alloca float, align 4
  %t2z = alloca float, align 4
  %cleanup.dest.slot = alloca i32, align 4
  store ptr %pt1x, ptr %pt1x.addr, align 8
  store ptr %pt1y, ptr %pt1y.addr, align 8
  store ptr %pt1z, ptr %pt1z.addr, align 8
  store ptr %pt2x, ptr %pt2x.addr, align 8
  store ptr %pt2y, ptr %pt2y.addr, align 8
  store ptr %pt2z, ptr %pt2z.addr, align 8
  store ptr %dist, ptr %dist.addr, align 8
  call void @llvm.lifetime.start.p0(i64 4, ptr %t1x) #4
  %0 = load ptr, ptr %pt1x.addr, align 8
  %1 = load float, ptr %0, align 4
  store float %1, ptr %t1x, align 4
  call void @llvm.lifetime.start.p0(i64 4, ptr %t1y) #4
  %2 = load ptr, ptr %pt1y.addr, align 8
  %3 = load float, ptr %2, align 4
  store float %3, ptr %t1y, align 4
  call void @llvm.lifetime.start.p0(i64 4, ptr %t1z) #4
  %4 = load ptr, ptr %pt1z.addr, align 8
  %5 = load float, ptr %4, align 4
  store float %5, ptr %t1z, align 4
  call void @llvm.lifetime.start.p0(i64 4, ptr %t2x) #4
  %6 = load ptr, ptr %pt2x.addr, align 8
  %7 = load float, ptr %6, align 4
  store float %7, ptr %t2x, align 4
  call void @llvm.lifetime.start.p0(i64 4, ptr %t2y) #4
  %8 = load ptr, ptr %pt2y.addr, align 8
  %9 = load float, ptr %8, align 4
  store float %9, ptr %t2y, align 4
  call void @llvm.lifetime.start.p0(i64 4, ptr %t2z) #4
  %10 = load ptr, ptr %pt2z.addr, align 8
  %11 = load float, ptr %10, align 4
  store float %11, ptr %t2z, align 4
  %12 = load float, ptr %t1x, align 4
  %13 = load float, ptr %t2y, align 4
  %cmp = fcmp fast ogt float %12, %13
  br i1 %cmp, label %if.then, label %lor.lhs.false

lor.lhs.false:                                    ; preds = %entry
  %14 = load float, ptr %t2x, align 4
  %15 = load float, ptr %t1y, align 4
  %cmp1 = fcmp fast olt float %14, %15
  br i1 %cmp1, label %if.then, label %lor.lhs.false2

lor.lhs.false2:                                   ; preds = %lor.lhs.false
  %16 = load float, ptr %t1x, align 4
  %17 = load float, ptr %t2z, align 4
  %cmp3 = fcmp fast ogt float %16, %17
  br i1 %cmp3, label %if.then, label %lor.lhs.false4

lor.lhs.false4:                                   ; preds = %lor.lhs.false2
  %18 = load float, ptr %t2x, align 4
  %19 = load float, ptr %t1z, align 4
  %cmp5 = fcmp fast olt float %18, %19
  br i1 %cmp5, label %if.then, label %lor.lhs.false6

lor.lhs.false6:                                   ; preds = %lor.lhs.false4
  %20 = load float, ptr %t1y, align 4
  %21 = load float, ptr %t2z, align 4
  %cmp7 = fcmp fast ogt float %20, %21
  br i1 %cmp7, label %if.then, label %lor.lhs.false8

lor.lhs.false8:                                   ; preds = %lor.lhs.false6
  %22 = load float, ptr %t2y, align 4
  %23 = load float, ptr %t1z, align 4
  %cmp9 = fcmp fast olt float %22, %23
  br i1 %cmp9, label %if.then, label %if.end

if.then:                                          ; preds = %lor.lhs.false8, %lor.lhs.false6, %lor.lhs.false4, %lor.lhs.false2, %lor.lhs.false, %entry
  store i32 0, ptr %retval, align 4
  store i32 1, ptr %cleanup.dest.slot, align 4
  br label %cleanup

if.end:                                           ; preds = %lor.lhs.false8
  %24 = load float, ptr %t2x, align 4
  %cmp10 = fcmp fast olt float %24, 0.000000e+00
  br i1 %cmp10, label %if.then15, label %lor.lhs.false11

lor.lhs.false11:                                  ; preds = %if.end
  %25 = load float, ptr %t2y, align 4
  %cmp12 = fcmp fast olt float %25, 0.000000e+00
  br i1 %cmp12, label %if.then15, label %lor.lhs.false13

lor.lhs.false13:                                  ; preds = %lor.lhs.false11
  %26 = load float, ptr %t2z, align 4
  %cmp14 = fcmp fast olt float %26, 0.000000e+00
  br i1 %cmp14, label %if.then15, label %if.end16

if.then15:                                        ; preds = %lor.lhs.false13, %lor.lhs.false11, %if.end
  store i32 0, ptr %retval, align 4
  store i32 1, ptr %cleanup.dest.slot, align 4
  br label %cleanup

if.end16:                                         ; preds = %lor.lhs.false13
  %27 = load float, ptr %t1x, align 4
  %28 = load ptr, ptr %dist.addr, align 8
  %b = getelementptr inbounds %struct.str, ptr %28, i32 0, i32 1
  %29 = load float, ptr %b, align 4
  %cmp17 = fcmp fast ogt float %27, %29
  br i1 %cmp17, label %if.then24, label %lor.lhs.false18

lor.lhs.false18:                                  ; preds = %if.end16
  %30 = load float, ptr %t1y, align 4
  %31 = load ptr, ptr %dist.addr, align 8
  %b19 = getelementptr inbounds %struct.str, ptr %31, i32 0, i32 1
  %32 = load float, ptr %b19, align 4
  %cmp20 = fcmp fast ogt float %30, %32
  br i1 %cmp20, label %if.then24, label %lor.lhs.false21

lor.lhs.false21:                                  ; preds = %lor.lhs.false18
  %33 = load float, ptr %t1z, align 4
  %34 = load ptr, ptr %dist.addr, align 8
  %b22 = getelementptr inbounds %struct.str, ptr %34, i32 0, i32 1
  %35 = load float, ptr %b22, align 4
  %cmp23 = fcmp fast ogt float %33, %35
  br i1 %cmp23, label %if.then24, label %if.end25

if.then24:                                        ; preds = %lor.lhs.false21, %lor.lhs.false18, %if.end16
  store i32 0, ptr %retval, align 4
  store i32 1, ptr %cleanup.dest.slot, align 4
  br label %cleanup

if.end25:                                         ; preds = %lor.lhs.false21
  store i32 1, ptr %retval, align 4
  store i32 1, ptr %cleanup.dest.slot, align 4
  br label %cleanup

cleanup:                                          ; preds = %if.end25, %if.then24, %if.then15, %if.then
  call void @llvm.lifetime.end.p0(i64 4, ptr %t2z) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %t2y) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %t2x) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %t1z) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %t1y) #4
  call void @llvm.lifetime.end.p0(i64 4, ptr %t1x) #4
  %36 = load i32, ptr %retval, align 4
  ret i32 %36
}

; Function Attrs: argmemonly nounwind willreturn
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #1

; Function Attrs: argmemonly nounwind willreturn
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #1
