; RUN: SATest -REF -config=%s.cfg -neat=1
; RUN: NEATChecker -r %s -a %s.neat -t 0
; XFAIL: *
;CHECKNEAT: ACCURATE 3
;CHECKNEAT: ACCURATE 3
;CHECKNEAT: ACCURATE 3
;CHECKNEAT: ACCURATE 3
;CHECKNEAT: ACCURATE 3
