; RUN: SATest -REF -config=%s.cfg -neat=1
; RUN: NEATChecker -r %s -a %s.neat -t 0
;CHECKNEAT: ACCURATE 41
;CHECKNEAT: ACCURATE 1 
;CHECKNEAT: ACCURATE 11
;CHECKNEAT: ACCURATE 21
;CHECKNEAT: ACCURATE 31
;CHECKNEAT: ACCURATE 82
;CHECKNEAT: ACCURATE 2 
;CHECKNEAT: ACCURATE 22
;CHECKNEAT: ACCURATE 42
;CHECKNEAT: ACCURATE 62
; XFAIL: *
