; RUN: SATest -REF -config=%s.cfg -neat=1
; RUN: NEATChecker -r %s -a %s.neat -t 0
;CHECKNEAT: ACCURATE -31 ACCURATE -30 ACCURATE -30 ACCURATE -4
;CHECKNEAT: ACCURATE 11 ACCURATE 12 ACCURATE 12 ACCURATE -4
;CHECKNEAT: ACCURATE -1 ACCURATE 0 ACCURATE 0 ACCURATE -4
;CHECKNEAT: ACCURATE -11 ACCURATE -10 ACCURATE -10 ACCURATE -4
;CHECKNEAT: ACCURATE 10 ACCURATE 11 ACCURATE 11 ACCURATE -4
; XFAIL: *
