; RUN: SATest -REF -config=%s.cfg -neat=1
; RUN: NEATChecker -r %s -a %s.neat -t 0
;CHECKNEAT: ACCURATE 51 ACCURATE 52 ACCURATE 52 ACCURATE 4
;CHECKNEAT: ACCURATE 51 ACCURATE 52 ACCURATE 52 ACCURATE 4
;CHECKNEAT: ACCURATE 51 ACCURATE 52 ACCURATE 52 ACCURATE 4
;CHECKNEAT: ACCURATE 51 ACCURATE 52 ACCURATE 52 ACCURATE 4
;CHECKNEAT: ACCURATE 51 ACCURATE 52 ACCURATE 52 ACCURATE 4
; XFAIL: *
