// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: intel_feature_isa_avx512_dotprod_int8
// RUN: %clang_cc1 -flax-vector-conversions=none -ffreestanding %s -triple=x86_64-unknown-unknown -target-feature +avx512vl -target-feature +avx512dotprodint8 -emit-llvm -o - -Wall -Werror | FileCheck %s

#include <immintrin.h>

__m128i test_mm_mask_vpdpbssd_epi32(__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_mask_vpdpbssd_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssd.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_mask_vpdpbssd_epi32(__W, __U, __A, __B);
}

__m128i test_mm_maskz_vpdpbssd_epi32(__mmask8 __U, __m128i __W, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_maskz_vpdpbssd_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssd.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_maskz_vpdpbssd_epi32(__U, __W, __A, __B);
}

__m128i test_mm_mask_vpdpbssds_epi32(__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_mask_vpdpbssds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssds.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_mask_vpdpbssds_epi32(__W, __U, __A, __B);
}

__m128i test_mm_maskz_vpdpbssds_epi32(__mmask8 __U, __m128i __W, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_maskz_vpdpbssds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssds.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_maskz_vpdpbssds_epi32(__U, __W, __A, __B);
}

__m128i test_mm_mask_vpdpbsud_epi32(__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_mask_vpdpbsud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsud.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_mask_vpdpbsud_epi32(__W, __U, __A, __B);
}

__m128i test_mm_maskz_vpdpbsud_epi32(__mmask8 __U, __m128i __W, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_maskz_vpdpbsud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsud.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_maskz_vpdpbsud_epi32(__U, __W, __A, __B);
}

__m128i test_mm_mask_vpdpbsuds_epi32(__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_mask_vpdpbsuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsuds.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_mask_vpdpbsuds_epi32(__W, __U, __A, __B);
}

__m128i test_mm_maskz_vpdpbsuds_epi32(__mmask8 __U, __m128i __W, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_maskz_vpdpbsuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsuds.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_maskz_vpdpbsuds_epi32(__U, __W, __A, __B);
}

__m128i test_mm_mask_vpdpbuud_epi32(__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_mask_vpdpbuud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuud.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_mask_vpdpbuud_epi32(__W, __U, __A, __B);
}

__m128i test_mm_maskz_vpdpbuud_epi32(__mmask8 __U, __m128i __W, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_maskz_vpdpbuud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuud.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_maskz_vpdpbuud_epi32(__U, __W, __A, __B);
}

__m128i test_mm_mask_vpdpbuuds_epi32(__m128i __W, __mmask8 __U, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_mask_vpdpbuuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuuds.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_mask_vpdpbuuds_epi32(__W, __U, __A, __B);
}

__m128i test_mm_maskz_vpdpbuuds_epi32(__mmask8 __U, __m128i __W, __m128i __A, __m128i __B) {
  // CHECK-LABEL: @test_mm_maskz_vpdpbuuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuuds.128
  // CHECK: select <4 x i1> %{{.*}}, <4 x i32> %{{.*}}, <4 x i32> %{{.*}}
  return _mm_maskz_vpdpbuuds_epi32(__U, __W, __A, __B);
}

__m256i test_mm256_mask_vpdpbssd_epi32(__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_mask_vpdpbssd_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssd.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_mask_vpdpbssd_epi32(__W, __U, __A, __B);
}

__m256i test_mm256_maskz_vpdpbssd_epi32(__mmask8 __U, __m256i __W, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_maskz_vpdpbssd_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssd.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_maskz_vpdpbssd_epi32(__U, __W, __A, __B);
}

__m256i test_mm256_mask_vpdpbssds_epi32(__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_mask_vpdpbssds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssds.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_mask_vpdpbssds_epi32(__W, __U, __A, __B);
}

__m256i test_mm256_maskz_vpdpbssds_epi32(__mmask8 __U, __m256i __W, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_maskz_vpdpbssds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbssds.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_maskz_vpdpbssds_epi32(__U, __W, __A, __B);
}

__m256i test_mm256_mask_vpdpbsud_epi32(__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_mask_vpdpbsud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsud.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_mask_vpdpbsud_epi32(__W, __U, __A, __B);
}

__m256i test_mm256_maskz_vpdpbsud_epi32(__mmask8 __U, __m256i __W, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_maskz_vpdpbsud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsud.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_maskz_vpdpbsud_epi32(__U, __W, __A, __B);
}

__m256i test_mm256_mask_vpdpbsuds_epi32(__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_mask_vpdpbsuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsuds.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_mask_vpdpbsuds_epi32(__W, __U, __A, __B);
}

__m256i test_mm256_maskz_vpdpbsuds_epi32(__mmask8 __U, __m256i __W, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_maskz_vpdpbsuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbsuds.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_maskz_vpdpbsuds_epi32(__U, __W, __A, __B);
}

__m256i test_mm256_mask_vpdpbuud_epi32(__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_mask_vpdpbuud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuud.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_mask_vpdpbuud_epi32(__W, __U, __A, __B);
}

__m256i test_mm256_maskz_vpdpbuud_epi32(__mmask8 __U, __m256i __W, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_maskz_vpdpbuud_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuud.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_maskz_vpdpbuud_epi32(__U, __W, __A, __B);
}

__m256i test_mm256_mask_vpdpbuuds_epi32(__m256i __W, __mmask8 __U, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_mask_vpdpbuuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuuds.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_mask_vpdpbuuds_epi32(__W, __U, __A, __B);
}

__m256i test_mm256_maskz_vpdpbuuds_epi32(__mmask8 __U, __m256i __W, __m256i __A, __m256i __B) {
  // CHECK-LABEL: @test_mm256_maskz_vpdpbuuds_epi32
  // CHECK: @llvm.x86.avx2.vpdpbuuds.256
  // CHECK: select <8 x i1> %{{.*}}, <8 x i32> %{{.*}}, <8 x i32> %{{.*}}
  return _mm256_maskz_vpdpbuuds_epi32(__U, __W, __A, __B);
}
