; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=x86_64-pc-linux -mattr=+avx -interleaved-access -S | FileCheck %s --check-prefix=AVX2
; RUN: opt < %s -mtriple=x86_64-pc-linux -mattr=+avx2 -interleaved-access -S | FileCheck %s --check-prefix=AVX2
; RUN: opt < %s -mtriple=x86_64-pc-linux -mattr=+avx512f -mattr=+avx512bw -mattr=+avx512vl -interleaved-access -S | FileCheck %s --check-prefix=AVX2

; We created a seperate file under Intel to test if these interleaved accesses get
; optimized by OptVLS. These tests pass if OptVLS successfully generates the optimized
; seuqence and lowerInterleavedLoad/Store as a client successfully communicates with OptVLS.

define void @interleaved_store_vf8_i32_undefs(<32 x i32> %a0,ptr %ptr){
; AVX2-LABEL: @interleaved_store_vf8_i32_undefs(
; AVX2-NEXT:    [[INTERLEAVE_VEC:%.*]] = shufflevector <32 x i32> [[A0:%.*]], <32 x i32> undef, <32 x i32> <i32 0, i32 8, i32 16, i32 24, i32 poison, i32 poison, i32 poison, i32 poison, i32 2, i32 10, i32 18, i32 26, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 7, i32 15, i32 23, i32 31>
; AVX2-NEXT:    store <32 x i32> [[INTERLEAVE_VEC]], ptr [[PTR:%.*]], align 16
; AVX2-NEXT:    ret void
;
  %interleave.vec = shufflevector <32 x i32> %a0, <32 x i32> undef, <32 x i32> <i32 0, i32 8, i32 16, i32 24, i32 poison, i32 poison, i32 poison, i32 poison, i32 2, i32 10, i32 18, i32 26, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 7, i32 15, i32 23, i32 31>
  store <32 x i32> %interleave.vec, ptr %ptr, align 16
  ret void
}

define void @interleaved_store_vf4_i32_undefs(<16 x i32> %a0,ptr %ptr){
; AVX2-LABEL: @interleaved_store_vf4_i32_undefs(
; AVX2-NEXT:    [[INTERLEAVE_VEC:%.*]] = shufflevector <16 x i32> [[A0:%.*]], <16 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
; AVX2-NEXT:    store <16 x i32> [[INTERLEAVE_VEC]], ptr [[PTR:%.*]], align 16
; AVX2-NEXT:    ret void
;
  %interleave.vec = shufflevector <16 x i32> %a0, <16 x i32> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  store <16 x i32> %interleave.vec, ptr %ptr, align 16
  ret void
}

define <4 x double> @load_factorf64_4(ptr %ptr) {
; AVX2-LABEL: @load_factorf64_4(
; AVX2-NEXT:    [[WIDE_VEC:%.*]] = load <8 x double>, ptr [[PTR:%.*]], align 16
; AVX2-NEXT:    [[STRIDED_V1:%.*]] = shufflevector <8 x double> [[WIDE_VEC]], <8 x double> undef, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
; AVX2-NEXT:    [[STRIDED_V2:%.*]] = shufflevector <8 x double> [[WIDE_VEC]], <8 x double> undef, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
; AVX2-NEXT:    [[ADD1:%.*]] = fadd <4 x double> [[STRIDED_V1]], [[STRIDED_V2]]
; AVX2-NEXT:    ret <4 x double> [[ADD1]]
;

  %wide.vec = load <8 x double>, ptr %ptr, align 16
  %strided.v1 = shufflevector <8 x double> %wide.vec, <8 x double> undef, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %strided.v2 = shufflevector <8 x double> %wide.vec, <8 x double> undef, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  %add1 = fadd <4 x double> %strided.v1, %strided.v2
  ret <4 x double> %add1
}

define <8 x i32> @interleaved_load_vf8_i32_stride4(ptr %ptr){
; AVX2-LABEL: @interleaved_load_vf8_i32_stride4(
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR:%.*]], i32 0
; AVX2-NEXT: [[LOAD0:%.*]] = load <4 x i32>, ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 1
; AVX2-NEXT: [[LOAD1:%.*]] = load <4 x i32>, ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 2
; AVX2-NEXT: [[LOAD2:%.*]] = load <4 x i32>, ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 3
; AVX2-NEXT: [[LOAD3:%.*]] = load <4 x i32>, ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 4
; AVX2-NEXT: [[LOAD4:%.*]] = load <4 x i32>, ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 5
; AVX2-NEXT: [[LOAD5:%.*]] = load <4 x i32>, ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 6
; AVX2-NEXT: [[LOAD6:%.*]] = load <4 x i32>, ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 7
; AVX2-NEXT: [[LOAD7:%.*]] = load <4 x i32>, ptr [[GEP]], align 16

; AVX2:      [[TEMP1:%.*]] = shufflevector <4 x i32> [[LOAD0]], <4 x i32> [[LOAD4]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; AVX2-NEXT: [[TEMP2:%.*]] = shufflevector <4 x i32> [[LOAD1]], <4 x i32> [[LOAD5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; AVX2-NEXT: [[TEMP3:%.*]] = shufflevector <4 x i32> [[LOAD2]], <4 x i32> [[LOAD6]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; AVX2-NEXT: [[TEMP4:%.*]] = shufflevector <4 x i32> [[LOAD3]], <4 x i32> [[LOAD7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>

; AVX2-NEXT: [[TEMP5:%.*]] = shufflevector <8 x i32> [[TEMP1]], <8 x i32> [[TEMP2]], <8 x i32> <i32 0, i32 1, i32 9, i32 8, i32 4, i32 5, i32 13, i32 12>
; AVX2-NEXT: [[TEMP6:%.*]] = shufflevector <8 x i32> [[TEMP4]], <8 x i32> [[TEMP3]], <8 x i32> <i32 1, i32 0, i32 8, i32 9, i32 5, i32 4, i32 12, i32 13>
; AVX2-NEXT: [[RES0:%.*]] = shufflevector <8 x i32> [[TEMP5]], <8 x i32> [[TEMP6]], <8 x i32> <i32 0, i32 3, i32 10, i32 9, i32 4, i32 7, i32 14, i32 13>
; AVX2-NEXT: [[RES1:%.*]] = shufflevector <8 x i32> [[TEMP5]], <8 x i32> [[TEMP6]], <8 x i32> <i32 1, i32 2, i32 11, i32 8, i32 5, i32 6, i32 15, i32 12>

; AVX2-NEXT: [[TEMP9:%.*]] = shufflevector <8 x i32> [[TEMP1]], <8 x i32> [[TEMP2]], <8 x i32> <i32 2, i32 3, i32 11, i32 10, i32 6, i32 7, i32 15, i32 14>
; AVX2-NEXT: [[TEMP10:%.*]] = shufflevector <8 x i32> [[TEMP4]], <8 x i32> [[TEMP3]], <8 x i32> <i32 3, i32 2, i32 10, i32 11, i32 7, i32 6, i32 14, i32 15>
; AVX2-NEXT: [[RES2:%.*]] = shufflevector <8 x i32> [[TEMP9]], <8 x i32> [[TEMP10]], <8 x i32> <i32 0, i32 3, i32 10, i32 9, i32 4, i32 7, i32 14, i32 13>
; AVX2-NEXT: [[RES3:%.*]] = shufflevector <8 x i32> [[TEMP9]], <8 x i32> [[TEMP10]], <8 x i32> <i32 1, i32 2, i32 11, i32 8, i32 5, i32 6, i32 15, i32 12>

; AVX2-NEXT: [[ADD0:%.*]] = add <8 x i32> [[RES0]], [[RES1]]
; AVX2-NEXT: [[ADD1:%.*]] = add <8 x i32> [[RES2]], [[RES3]]
; AVX2-NEXT: [[RET0:%.*]] = add <8 x i32> [[ADD0]], [[ADD1]]
; AVX2-NEXT:ret <8 x i32> [[RET0]]

  %wide.vec = load <32 x i32>, ptr %ptr, align 16
  %v1 = shufflevector <32 x i32> %wide.vec, <32 x i32> undef, <8 x i32> <i32 0, i32 4,  i32 8,  i32 12, i32 16, i32 20, i32 24, i32 28>
  %v2 = shufflevector <32 x i32> %wide.vec, <32 x i32> undef, <8 x i32> <i32 1, i32 5,  i32 9,  i32 13, i32 17, i32 21, i32 25, i32 29>
  %v3 = shufflevector <32 x i32> %wide.vec, <32 x i32> undef, <8 x i32> <i32 2, i32 6,  i32 10, i32 14, i32 18, i32 22, i32 26, i32 30>
  %v4 = shufflevector <32 x i32> %wide.vec, <32 x i32> undef, <8 x i32> <i32 3, i32 7, i32 11, i32 15, i32 19, i32 23, i32 27, i32 31>
  %add1 = add <8 x i32> %v1, %v2
  %add2 = add <8 x i32> %v3, %v4
  %add3 = add <8 x i32> %add1, %add2
  ret <8 x i32> %add3
}

define void @interleaved_store_vf8_i32_stride4(<8 x i32> %a0,<8 x i32> %b0,<8 x i32> %c0,<8 x i32> %d0,ptr %ptr){
; AVX2-LABEL: @interleaved_store_vf8_i32_stride4(

; AVX2: [[STOREDATA0:%.*]] = shufflevector <8 x i32> [[DATA0:%.*]], <8 x i32> [[DATA1:%.*]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; AVX2-NEXT: [[STOREDATA1:%.*]] = shufflevector <8 x i32> [[DATA2:%.*]], <8 x i32> [[DATA3:%.*]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>

; AVX2: [[TEMP0:%.*]] = shufflevector <16 x i32> [[STOREDATA0]], <16 x i32> [[STOREDATA1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; AVX2-NEXT: [[TEMP1:%.*]] = shufflevector <16 x i32> [[STOREDATA0]], <16 x i32> [[STOREDATA1]], <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; AVX2-NEXT: [[TEMP4:%.*]] = shufflevector <8 x i32> [[TEMP0]], <8 x i32> [[TEMP1]], <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 4, i32 12, i32 5, i32 13>

; AVX2-NEXT: [[TEMP2:%.*]] = shufflevector <16 x i32> [[STOREDATA0]], <16 x i32> [[STOREDATA1]], <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
; AVX2-NEXT: [[TEMP3:%.*]] = shufflevector <16 x i32> [[STOREDATA0]], <16 x i32> [[STOREDATA1]], <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; AVX2-NEXT: [[TEMP5:%.*]] = shufflevector <8 x i32> [[TEMP2]], <8 x i32> [[TEMP3]], <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 4, i32 12, i32 5, i32 13>

; AVX2-NEXT: [[RES0:%.*]] = shufflevector <8 x i32> [[TEMP4]], <8 x i32> [[TEMP5]], <8 x i32> <i32 0, i32 1, i32 8, i32 9, i32 4, i32 5, i32 12, i32 13>
; AVX2-NEXT: [[RES1:%.*]] = shufflevector <8 x i32> [[TEMP4]], <8 x i32> [[TEMP5]], <8 x i32> <i32 2, i32 3, i32 10, i32 11, i32 6, i32 7, i32 14, i32 15>

; AVX2-NEXT: [[TEMP8:%.*]] = shufflevector <8 x i32> [[TEMP0]], <8 x i32> [[TEMP1]], <8 x i32> <i32 2, i32 10, i32 3, i32 11, i32 6, i32 14, i32 7, i32 15>
; AVX2-NEXT: [[TEMP9:%.*]] = shufflevector <8 x i32> [[TEMP2]], <8 x i32> [[TEMP3]], <8 x i32> <i32 2, i32 10, i32 3, i32 11, i32 6, i32 14, i32 7, i32 15>
; AVX2-NEXT: [[RES2:%.*]] = shufflevector <8 x i32> [[TEMP8]], <8 x i32> [[TEMP9]], <8 x i32> <i32 0, i32 1, i32 8, i32 9, i32 4, i32 5, i32 12, i32 13>
; AVX2-NEXT: [[RES3:%.*]] = shufflevector <8 x i32> [[TEMP8]], <8 x i32> [[TEMP9]], <8 x i32> <i32 2, i32 3, i32 10, i32 11, i32 6, i32 7, i32 14, i32 15>

; AVX2-NEXT: [[STORE0:%.*]] = shufflevector <8 x i32> [[RES0]], <8 x i32> [[RES0]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; AVX2-NEXT: [[STORE1:%.*]] = shufflevector <8 x i32> [[RES1]], <8 x i32> [[RES1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; AVX2-NEXT: [[STORE2:%.*]] = shufflevector <8 x i32> [[RES2]], <8 x i32> [[RES2]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; AVX2-NEXT: [[STORE3:%.*]] = shufflevector <8 x i32> [[RES3]], <8 x i32> [[RES3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; AVX2-NEXT: [[STORE4:%.*]] = shufflevector <8 x i32> [[RES0]], <8 x i32> [[RES0]], <4 x i32> <i32 4, i32 5, i32 6, i32 7>
; AVX2-NEXT: [[STORE5:%.*]] = shufflevector <8 x i32> [[RES1]], <8 x i32> [[RES1]], <4 x i32> <i32 4, i32 5, i32 6, i32 7>
; AVX2-NEXT: [[STORE6:%.*]] = shufflevector <8 x i32> [[RES2]], <8 x i32> [[RES2]], <4 x i32> <i32 4, i32 5, i32 6, i32 7>
; AVX2-NEXT: [[STORE7:%.*]] = shufflevector <8 x i32> [[RES3]], <8 x i32> [[RES3]], <4 x i32> <i32 4, i32 5, i32 6, i32 7>

; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR:%.*]], i32 0
; AVX2-NEXT: store <4 x i32> [[STORE0]], ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 1
; AVX2-NEXT: store <4 x i32> [[STORE1]], ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 2
; AVX2-NEXT: store <4 x i32> [[STORE2]], ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 3
; AVX2-NEXT: store <4 x i32> [[STORE3]], ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 4
; AVX2-NEXT: store <4 x i32> [[STORE4]], ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 5
; AVX2-NEXT: store <4 x i32> [[STORE5]], ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 6
; AVX2-NEXT: store <4 x i32> [[STORE6]], ptr [[GEP]], align 16
; AVX2-NEXT: [[GEP:%.*]] = getelementptr inbounds <4 x i32>, ptr [[PTR]], i32 7
; AVX2-NEXT: store <4 x i32> [[STORE7]], ptr [[GEP]], align 16
; AVX2-NEXT: ret void

  %store.data0 = shufflevector <8 x i32> %a0, <8 x i32> %b0, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %store.data1 = shufflevector <8 x i32> %c0, <8 x i32> %d0, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %interleave.vec = shufflevector <16 x i32> %store.data0, <16 x i32> %store.data1, <32 x i32> <i32 0, i32 8, i32 16, i32 24, i32 1, i32 9, i32 17, i32 25, i32 2, i32 10, i32 18, i32 26, i32 3, i32 11, i32 19, i32 27, i32 4, i32 12, i32 20, i32 28, i32 5, i32 13, i32 21, i32 29, i32 6, i32 14, i32 22, i32 30, i32 7, i32 15, i32 23, i32 31>
  store <32 x i32> %interleave.vec, ptr %ptr, align 16
  ret void
}

define <8 x i16> @interleaved_load_vf8_i16_stride8(ptr %ptr){
; AVX2-LABEL: @interleaved_load_vf8_i16_stride8(
; AVX2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[PTR:%.*]], i32 0
; AVX2-NEXT:    [[TMP3:%.*]] = load <8 x i16>, ptr [[TMP2]], align 16
; AVX2-NEXT:    [[TMP5:%.*]] = getelementptr inbounds <8 x i16>, ptr [[PTR]], i32 1
; AVX2-NEXT:    [[TMP6:%.*]] = load <8 x i16>, ptr [[TMP5]], align 16
; AVX2-NEXT:    [[TMP8:%.*]] = getelementptr inbounds <8 x i16>, ptr [[PTR]], i32 2
; AVX2-NEXT:    [[TMP9:%.*]] = load <8 x i16>, ptr [[TMP8]], align 16
; AVX2-NEXT:    [[TMP11:%.*]] = getelementptr inbounds <8 x i16>, ptr [[PTR]], i32 3
; AVX2-NEXT:    [[TMP12:%.*]] = load <8 x i16>, ptr [[TMP11]], align 16
; AVX2-NEXT:    [[TMP14:%.*]] = getelementptr inbounds <8 x i16>, ptr [[PTR]], i32 4
; AVX2-NEXT:    [[TMP15:%.*]] = load <8 x i16>, ptr [[TMP14]], align 16
; AVX2-NEXT:    [[TMP17:%.*]] = getelementptr inbounds <8 x i16>, ptr [[PTR]], i32 5
; AVX2-NEXT:    [[TMP18:%.*]] = load <8 x i16>, ptr [[TMP17]], align 16
; AVX2-NEXT:    [[TMP20:%.*]] = getelementptr inbounds <8 x i16>, ptr [[PTR]], i32 6
; AVX2-NEXT:    [[TMP21:%.*]] = load <8 x i16>, ptr [[TMP20]], align 16
; AVX2-NEXT:    [[TMP23:%.*]] = getelementptr inbounds <8 x i16>, ptr [[PTR]], i32 7
; AVX2-NEXT:    [[TMP24:%.*]] = load <8 x i16>, ptr [[TMP23]], align 16
; AVX2-NEXT:    [[TMP25:%.*]] = shufflevector <8 x i16> [[TMP3]], <8 x i16> [[TMP6]], <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>
; AVX2-NEXT:    [[TMP26:%.*]] = shufflevector <8 x i16> [[TMP3]], <8 x i16> [[TMP6]], <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>
; AVX2-NEXT:    [[TMP27:%.*]] = shufflevector <8 x i16> [[TMP9]], <8 x i16> [[TMP12]], <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>
; AVX2-NEXT:    [[TMP28:%.*]] = shufflevector <8 x i16> [[TMP9]], <8 x i16> [[TMP12]], <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>
; AVX2-NEXT:    [[TMP29:%.*]] = shufflevector <8 x i16> [[TMP15]], <8 x i16> [[TMP18]], <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>
; AVX2-NEXT:    [[TMP30:%.*]] = shufflevector <8 x i16> [[TMP15]], <8 x i16> [[TMP18]], <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>
; AVX2-NEXT:    [[TMP31:%.*]] = shufflevector <8 x i16> [[TMP21]], <8 x i16> [[TMP24]], <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>
; AVX2-NEXT:    [[TMP32:%.*]] = shufflevector <8 x i16> [[TMP21]], <8 x i16> [[TMP24]], <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>
; AVX2-NEXT:    [[TMP33:%.*]] = shufflevector <8 x i16> [[TMP25]], <8 x i16> [[TMP27]], <8 x i32> <i32 0, i32 1, i32 8, i32 9, i32 2, i32 3, i32 10, i32 11>
; AVX2-NEXT:    [[TMP34:%.*]] = shufflevector <8 x i16> [[TMP25]], <8 x i16> [[TMP27]], <8 x i32> <i32 4, i32 5, i32 12, i32 13, i32 6, i32 7, i32 14, i32 15>
; AVX2-NEXT:    [[TMP35:%.*]] = shufflevector <8 x i16> [[TMP29]], <8 x i16> [[TMP31]], <8 x i32> <i32 0, i32 1, i32 8, i32 9, i32 2, i32 3, i32 10, i32 11>
; AVX2-NEXT:    [[TMP36:%.*]] = shufflevector <8 x i16> [[TMP29]], <8 x i16> [[TMP31]], <8 x i32> <i32 4, i32 5, i32 12, i32 13, i32 6, i32 7, i32 14, i32 15>
; AVX2-NEXT:    [[TMP37:%.*]] = shufflevector <8 x i16> [[TMP26]], <8 x i16> [[TMP28]], <8 x i32> <i32 0, i32 1, i32 8, i32 9, i32 2, i32 3, i32 10, i32 11>
; AVX2-NEXT:    [[TMP38:%.*]] = shufflevector <8 x i16> [[TMP26]], <8 x i16> [[TMP28]], <8 x i32> <i32 4, i32 5, i32 12, i32 13, i32 6, i32 7, i32 14, i32 15>
; AVX2-NEXT:    [[TMP39:%.*]] = shufflevector <8 x i16> [[TMP30]], <8 x i16> [[TMP32]], <8 x i32> <i32 0, i32 1, i32 8, i32 9, i32 2, i32 3, i32 10, i32 11>
; AVX2-NEXT:    [[TMP40:%.*]] = shufflevector <8 x i16> [[TMP30]], <8 x i16> [[TMP32]], <8 x i32> <i32 4, i32 5, i32 12, i32 13, i32 6, i32 7, i32 14, i32 15>
; AVX2-NEXT:    [[TMP41:%.*]] = shufflevector <8 x i16> [[TMP33]], <8 x i16> [[TMP35]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
; AVX2-NEXT:    [[TMP42:%.*]] = shufflevector <8 x i16> [[TMP33]], <8 x i16> [[TMP35]], <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 12, i32 13, i32 14, i32 15>
; AVX2-NEXT:    [[TMP43:%.*]] = shufflevector <8 x i16> [[TMP34]], <8 x i16> [[TMP36]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
; AVX2-NEXT:    [[TMP44:%.*]] = shufflevector <8 x i16> [[TMP34]], <8 x i16> [[TMP36]], <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 12, i32 13, i32 14, i32 15>
; AVX2-NEXT:    [[TMP45:%.*]] = shufflevector <8 x i16> [[TMP37]], <8 x i16> [[TMP39]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
; AVX2-NEXT:    [[TMP46:%.*]] = shufflevector <8 x i16> [[TMP37]], <8 x i16> [[TMP39]], <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 12, i32 13, i32 14, i32 15>
; AVX2-NEXT:    [[TMP47:%.*]] = shufflevector <8 x i16> [[TMP38]], <8 x i16> [[TMP40]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 10, i32 11>
; AVX2-NEXT:    [[TMP48:%.*]] = shufflevector <8 x i16> [[TMP38]], <8 x i16> [[TMP40]], <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 12, i32 13, i32 14, i32 15>
; AVX2-NEXT:    [[ADD1:%.*]] = add <8 x i16> [[TMP41]], [[TMP42]]
; AVX2-NEXT:    [[ADD2:%.*]] = add <8 x i16> [[TMP43]], [[TMP44]]
; AVX2-NEXT:    [[ADD3:%.*]] = add <8 x i16> [[TMP45]], [[TMP46]]
; AVX2-NEXT:    [[ADD4:%.*]] = add <8 x i16> [[TMP47]], [[TMP48]]
; AVX2-NEXT:    [[ADD5:%.*]] = add <8 x i16> [[ADD1]], [[ADD2]]
; AVX2-NEXT:    [[ADD6:%.*]] = add <8 x i16> [[ADD3]], [[ADD4]]
; AVX2-NEXT:    [[ADD7:%.*]] = add <8 x i16> [[ADD5]], [[ADD6]]
; AVX2-NEXT:    ret <8 x i16> [[ADD7]]
;
  %wide.vec = load <64 x i16>, ptr %ptr, align 16
  %v0 = shufflevector <64 x i16> %wide.vec, <64 x i16> undef, <8 x i32> <i32 0, i32 8, i32 16, i32 24, i32 32, i32 40, i32 48, i32 56>
  %v7 = shufflevector <64 x i16> %wide.vec, <64 x i16> undef, <8 x i32> <i32 7, i32 15, i32 23, i32 31, i32 39, i32 47, i32 55, i32 63>
  %v1 = shufflevector <64 x i16> %wide.vec, <64 x i16> undef, <8 x i32> <i32 1, i32 9, i32 17, i32 25, i32 33, i32 41, i32 49, i32 57>
  %v6 = shufflevector <64 x i16> %wide.vec, <64 x i16> undef, <8 x i32> <i32 6, i32 14, i32 22, i32 30, i32 38, i32 46, i32 54, i32 62>
  %v2 = shufflevector <64 x i16> %wide.vec, <64 x i16> undef, <8 x i32> <i32 2, i32 10, i32 18, i32 26, i32 34, i32 42, i32 50, i32 58>
  %v5 = shufflevector <64 x i16> %wide.vec, <64 x i16> undef, <8 x i32> <i32 5, i32 13, i32 21, i32 29, i32 37, i32 45, i32 53, i32 61>
  %v3 = shufflevector <64 x i16> %wide.vec, <64 x i16> undef, <8 x i32> <i32 3, i32 11, i32 19, i32 27, i32 35, i32 43, i32 51, i32 59>
  %v4 = shufflevector <64 x i16> %wide.vec, <64 x i16> undef, <8 x i32> <i32 4, i32 12, i32 20, i32 28, i32 36, i32 44, i32 52, i32 60>

  %add1 = add <8 x i16> %v0, %v1
  %add2 = add <8 x i16> %v2, %v3
  %add3 = add <8 x i16> %v4, %v5
  %add4 = add <8 x i16> %v6, %v7
  %add5 = add <8 x i16> %add1, %add2
  %add6 = add <8 x i16> %add3, %add4
  %add7 = add <8 x i16> %add5, %add6
  ret <8 x i16> %add7
}


