; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: intel_feature_isa_avx_vnni
; RUN: llc < %s -mtriple=i686-unknown-unknown -mattr=+avxvnni --show-mc-encoding | FileCheck %s --check-prefixes=CHECK,AVX-X86
; RUN: llc < %s -mtriple=i686-unknown-unknown -mattr=+avx512vnni,+avx512vl,+avxvnni --show-mc-encoding | FileCheck %s --check-prefixes=CHECK,AVX512-X86
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avxvnni --show-mc-encoding | FileCheck %s --check-prefixes=CHECK,AVX-X64
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512vnni,+avx512vl,+avxvnni --show-mc-encoding | FileCheck %s --check-prefixes=CHECK,AVX512-X64

declare <8 x i32> @llvm.x86.avx.vpdpbusd.256(<8 x i32>, <8 x i32>, <8 x i32>)

define <8 x i32>@test_int_x86_avx_vpdpbusd_256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx_vpdpbusd_256:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpbusd %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x50,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx_vpdpbusd_256:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpbusd %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x50,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx_vpdpbusd_256:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpbusd %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x50,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx_vpdpbusd_256:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpbusd %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x50,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <8 x i32> @llvm.x86.avx.vpdpbusd.256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2)
  ret <8 x i32> %res
}

declare <4 x i32> @llvm.x86.avx.vpdpbusd.128(<4 x i32>, <4 x i32>, <4 x i32>)

define <4 x i32>@test_int_x86_avx_vpdpbusd_128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx_vpdpbusd_128:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpbusd %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x50,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx_vpdpbusd_128:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpbusd %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x50,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx_vpdpbusd_128:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpbusd %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x50,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx_vpdpbusd_128:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpbusd %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x50,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <4 x i32> @llvm.x86.avx.vpdpbusd.128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2)
  ret <4 x i32> %res
}

declare <8 x i32> @llvm.x86.avx.vpdpbusds.256(<8 x i32>, <8 x i32>, <8 x i32>)

define <8 x i32>@test_int_x86_avx_vpdpbusds_256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx_vpdpbusds_256:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpbusds %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x51,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx_vpdpbusds_256:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpbusds %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x51,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx_vpdpbusds_256:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpbusds %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x51,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx_vpdpbusds_256:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpbusds %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x51,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <8 x i32> @llvm.x86.avx.vpdpbusds.256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2)
  ret <8 x i32> %res
}

declare <4 x i32> @llvm.x86.avx.vpdpbusds.128(<4 x i32>, <4 x i32>, <4 x i32>)

define <4 x i32>@test_int_x86_avx_vpdpbusds_128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx_vpdpbusds_128:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpbusds %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x51,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx_vpdpbusds_128:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpbusds %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x51,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx_vpdpbusds_128:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpbusds %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x51,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx_vpdpbusds_128:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpbusds %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x51,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <4 x i32> @llvm.x86.avx.vpdpbusds.128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2)
  ret <4 x i32> %res
}

declare <8 x i32> @llvm.x86.avx.vpdpwssd.256(<8 x i32>, <8 x i32>, <8 x i32>)

define <8 x i32>@test_int_x86_avx_vpdpwssd_256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx_vpdpwssd_256:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpwssd %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x52,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx_vpdpwssd_256:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpwssd %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x52,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx_vpdpwssd_256:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpwssd %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x52,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx_vpdpwssd_256:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpwssd %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x52,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <8 x i32> @llvm.x86.avx.vpdpwssd.256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2)
  ret <8 x i32> %res
}

declare <4 x i32> @llvm.x86.avx.vpdpwssd.128(<4 x i32>, <4 x i32>, <4 x i32>)

define <4 x i32>@test_int_x86_avx_vpdpwssd_128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx_vpdpwssd_128:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpwssd %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x52,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx_vpdpwssd_128:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpwssd %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x52,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx_vpdpwssd_128:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpwssd %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x52,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx_vpdpwssd_128:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpwssd %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x52,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <4 x i32> @llvm.x86.avx.vpdpwssd.128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2)
  ret <4 x i32> %res
}

declare <8 x i32> @llvm.x86.avx.vpdpwssds.256(<8 x i32>, <8 x i32>, <8 x i32>)

define <8 x i32>@test_int_x86_avx_vpdpwssds_256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx_vpdpwssds_256:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpwssds %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x53,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx_vpdpwssds_256:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpwssds %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x53,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx_vpdpwssds_256:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpwssds %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x53,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx_vpdpwssds_256:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpwssds %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x53,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <8 x i32> @llvm.x86.avx.vpdpwssds.256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2)
  ret <8 x i32> %res
}

declare <4 x i32> @llvm.x86.avx.vpdpwssds.128(<4 x i32>, <4 x i32>, <4 x i32>)

define <4 x i32>@test_int_x86_avx_vpdpwssds_128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx_vpdpwssds_128:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpwssds %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x53,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx_vpdpwssds_128:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpwssds %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x53,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx_vpdpwssds_128:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpwssds %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x53,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx_vpdpwssds_128:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpwssds %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x53,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <4 x i32> @llvm.x86.avx.vpdpwssds.128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2)
  ret <4 x i32> %res
}

declare <8 x i32> @llvm.x86.avx512.vpdpbusd.256(<8 x i32>, <8 x i32>, <8 x i32>)

define <8 x i32>@test_int_x86_avx512_vpdpbusd_256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx512_vpdpbusd_256:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpbusd %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x50,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx512_vpdpbusd_256:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpbusd %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x50,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx512_vpdpbusd_256:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpbusd %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x50,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx512_vpdpbusd_256:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpbusd %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x50,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <8 x i32> @llvm.x86.avx512.vpdpbusd.256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2)
  ret <8 x i32> %res
}

declare <4 x i32> @llvm.x86.avx512.vpdpbusd.128(<4 x i32>, <4 x i32>, <4 x i32>)

define <4 x i32>@test_int_x86_avx512_vpdpbusd_128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx512_vpdpbusd_128:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpbusd %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x50,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx512_vpdpbusd_128:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpbusd %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x50,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx512_vpdpbusd_128:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpbusd %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x50,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx512_vpdpbusd_128:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpbusd %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x50,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <4 x i32> @llvm.x86.avx512.vpdpbusd.128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2)
  ret <4 x i32> %res
}

declare <8 x i32> @llvm.x86.avx512.vpdpbusds.256(<8 x i32>, <8 x i32>, <8 x i32>)

define <8 x i32>@test_int_x86_avx512_vpdpbusds_256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx512_vpdpbusds_256:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpbusds %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x51,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx512_vpdpbusds_256:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpbusds %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x51,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx512_vpdpbusds_256:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpbusds %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x51,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx512_vpdpbusds_256:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpbusds %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x51,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <8 x i32> @llvm.x86.avx512.vpdpbusds.256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2)
  ret <8 x i32> %res
}

declare <4 x i32> @llvm.x86.avx512.vpdpbusds.128(<4 x i32>, <4 x i32>, <4 x i32>)

define <4 x i32>@test_int_x86_avx512_vpdpbusds_128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx512_vpdpbusds_128:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpbusds %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x51,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx512_vpdpbusds_128:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpbusds %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x51,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx512_vpdpbusds_128:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpbusds %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x51,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx512_vpdpbusds_128:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpbusds %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x51,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <4 x i32> @llvm.x86.avx512.vpdpbusds.128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2)
  ret <4 x i32> %res
}

declare <8 x i32> @llvm.x86.avx512.vpdpwssd.256(<8 x i32>, <8 x i32>, <8 x i32>)

define <8 x i32>@test_int_x86_avx512_vpdpwssd_256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx512_vpdpwssd_256:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpwssd %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x52,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx512_vpdpwssd_256:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpwssd %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x52,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx512_vpdpwssd_256:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpwssd %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x52,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx512_vpdpwssd_256:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpwssd %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x52,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <8 x i32> @llvm.x86.avx512.vpdpwssd.256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2)
  ret <8 x i32> %res
}

declare <4 x i32> @llvm.x86.avx512.vpdpwssd.128(<4 x i32>, <4 x i32>, <4 x i32>)

define <4 x i32>@test_int_x86_avx512_vpdpwssd_128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx512_vpdpwssd_128:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpwssd %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x52,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx512_vpdpwssd_128:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpwssd %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x52,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx512_vpdpwssd_128:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpwssd %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x52,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx512_vpdpwssd_128:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpwssd %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x52,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <4 x i32> @llvm.x86.avx512.vpdpwssd.128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2)
  ret <4 x i32> %res
}

declare <8 x i32> @llvm.x86.avx512.vpdpwssds.256(<8 x i32>, <8 x i32>, <8 x i32>)

define <8 x i32>@test_int_x86_avx512_vpdpwssds_256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx512_vpdpwssds_256:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpwssds %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x53,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx512_vpdpwssds_256:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpwssds %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x53,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx512_vpdpwssds_256:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpwssds %ymm2, %ymm1, %ymm0 # encoding: [0xc4,0xe2,0x75,0x53,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx512_vpdpwssds_256:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpwssds %ymm2, %ymm1, %ymm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x75,0x53,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <8 x i32> @llvm.x86.avx512.vpdpwssds.256(<8 x i32> %x0, <8 x i32> %x1, <8 x i32> %x2)
  ret <8 x i32> %res
}

declare <4 x i32> @llvm.x86.avx512.vpdpwssds.128(<4 x i32>, <4 x i32>, <4 x i32>)

define <4 x i32>@test_int_x86_avx512_vpdpwssds_128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2) {
; AVX-X86-LABEL: test_int_x86_avx512_vpdpwssds_128:
; AVX-X86:       # %bb.0:
; AVX-X86-NEXT:    {vex} vpdpwssds %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x53,0xc2]
; AVX-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX512-X86-LABEL: test_int_x86_avx512_vpdpwssds_128:
; AVX512-X86:       # %bb.0:
; AVX512-X86-NEXT:    {vex} vpdpwssds %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x53,0xc2]
; AVX512-X86-NEXT:    retl # encoding: [0xc3]
;
; AVX-X64-LABEL: test_int_x86_avx512_vpdpwssds_128:
; AVX-X64:       # %bb.0:
; AVX-X64-NEXT:    {vex} vpdpwssds %xmm2, %xmm1, %xmm0 # encoding: [0xc4,0xe2,0x71,0x53,0xc2]
; AVX-X64-NEXT:    retq # encoding: [0xc3]
;
; AVX512-X64-LABEL: test_int_x86_avx512_vpdpwssds_128:
; AVX512-X64:       # %bb.0:
; AVX512-X64-NEXT:    {vex} vpdpwssds %xmm2, %xmm1, %xmm0 # EVEX TO VEX Compression encoding: [0xc4,0xe2,0x71,0x53,0xc2]
; AVX512-X64-NEXT:    retq # encoding: [0xc3]
  %res = call <4 x i32> @llvm.x86.avx512.vpdpwssds.128(<4 x i32> %x0, <4 x i32> %x1, <4 x i32> %x2)
  ret <4 x i32> %res
}
