; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -bugpoint-enable-legacy-pm -S -mtriple=x86_64-unknown-unknown -float128-expand -intel-libirc-allowed | FileCheck %s

define dso_local i32 @test1(fp128 %x) local_unnamed_addr #0 {
; CHECK-LABEL: @test1(
; CHECK-NEXT:  A:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP3]], align 16
; CHECK-NEXT:    br label [[B:%.*]]
; CHECK:       B:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP2]], ptr [[TMP3]], ptr [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    br i1 undef, label [[C:%.*]], label [[D:%.*]]
; CHECK:       C:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP0]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP0]], ptr [[TMP3]], ptr [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = load fp128, ptr [[TMP0]], align 16
; CHECK-NEXT:    br label [[B]]
; CHECK:       D:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP1]], ptr [[TMP3]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    [[TMP6:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret i32 0
;
A:
  br label %B
B:
  %xx2 = fadd fp128 %x, %x
  br i1 undef, label %C, label %D
C:
  %xx3 = fadd fp128 %x, %x
  br label %B
D:
  %xx4 = fadd fp128 %x, %x
  ret i32 0
}

define dso_local i32 @test2(fp128 %x) local_unnamed_addr #0 {
; CHECK-LABEL: @test2(
; CHECK-NEXT:  A:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP3]], align 16
; CHECK-NEXT:    br label [[B:%.*]]
; CHECK:       B:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP2]], ptr [[TMP3]], ptr [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    br i1 undef, label [[C:%.*]], label [[D:%.*]]
; CHECK:       C:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP0]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP0]], ptr [[TMP3]], ptr [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = load fp128, ptr [[TMP0]], align 16
; CHECK-NEXT:    br i1 undef, label [[B]], label [[E:%.*]]
; CHECK:       D:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP1]], ptr [[TMP3]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    [[TMP6:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret i32 0
; CHECK:       E:
; CHECK-NEXT:    ret i32 1
;
A:
  br label %B
B:
  %xx2 = fadd fp128 %x, %x
  br i1 undef, label %C, label %D
C:
  %xx3 = fadd fp128 %x, %x
  br i1 undef, label %B, label %E
D:
  %xx4 = fadd fp128 %x, %x
  ret i32 0
E:
  ret i32 1
}

define dso_local i32 @test3(fp128 %x) local_unnamed_addr #0 {
; CHECK-LABEL: @test3(
; CHECK-NEXT:  A:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP3]], align 16
; CHECK-NEXT:    br label [[B:%.*]]
; CHECK:       B:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP2]], ptr [[TMP3]], ptr [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    br i1 undef, label [[C:%.*]], label [[D:%.*]]
; CHECK:       C:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP0]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP0]], ptr [[TMP3]], ptr [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = load fp128, ptr [[TMP0]], align 16
; CHECK-NEXT:    br i1 undef, label [[B]], label [[E:%.*]]
; CHECK:       D:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP1]], ptr [[TMP3]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    [[TMP6:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    br label [[E]]
; CHECK:       E:
; CHECK-NEXT:    ret i32 1
;
A:
  br label %B
B:
  %xx2 = fadd fp128 %x, %x
  br i1 undef, label %C, label %D
C:
  %xx3 = fadd fp128 %x, %x
  br i1 undef, label %B, label %E
D:
  %xx4 = fadd fp128 %x, %x
  br label %E
E:
  ret i32 1
}

define dso_local i32 @test4(fp128 %x) local_unnamed_addr #0 {
; CHECK-LABEL: @test4(
; CHECK-NEXT:  A:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    br label [[B:%.*]]
; CHECK:       B:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP1]], ptr [[TMP2]], ptr [[TMP2]])
; CHECK-NEXT:    [[TMP3:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    br i1 undef, label [[C:%.*]], label [[D:%.*]]
; CHECK:       C:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP0]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP0]], ptr [[TMP2]], ptr [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP0]], align 16
; CHECK-NEXT:    br label [[B]]
; CHECK:       D:
; CHECK-NEXT:    ret i32 0
;
A:
  br label %B
B:
  %xx2 = fadd fp128 %x, %x
  br i1 undef, label %C, label %D
C:
  %xx3 = fadd fp128 %x, %x
  br label %B
D:
  ret i32 0
}

; Function Attrs: nofree noreturn nounwind uwtable
define dso_local i32 @test5(fp128 %x) local_unnamed_addr #0 {
; CHECK-LABEL: @test5(
; CHECK-NEXT:  A:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    br label [[B:%.*]]
; CHECK:       B:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP1]], ptr [[TMP2]], ptr [[TMP2]])
; CHECK-NEXT:    [[TMP3:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    br i1 undef, label [[C:%.*]], label [[D:%.*]]
; CHECK:       C:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP0]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP0]], ptr [[TMP2]], ptr [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP0]], align 16
; CHECK-NEXT:    br label [[B]]
; CHECK:       D:
; CHECK-NEXT:    ret i32 0
;
A:
  br label %B
B:
  %xx2 = fadd fp128 %x, %x
  br i1 undef, label %C, label %D
C:
  %xx3 = fadd fp128 %x, %x
  br label %B
D:
  ret i32 0
}

define dso_local i32 @test6(fp128 %y) local_unnamed_addr #0 {
; CHECK-LABEL: @test6(
; CHECK-NEXT:  A:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP3]], align 16
; CHECK-NEXT:    br label [[B:%.*]]
; CHECK:       B:
; CHECK-NEXT:    call void @__addq(ptr [[TMP2]], ptr [[TMP3]], ptr [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    br i1 undef, label [[C:%.*]], label [[D:%.*]]
; CHECK:       C:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP0]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP0]], ptr [[TMP2]], ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = load fp128, ptr [[TMP0]], align 16
; CHECK-NEXT:    br label [[B]]
; CHECK:       D:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP1]], ptr [[TMP2]], ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP6:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret i32 0
;
A:
  br label %B
B:
  %x = fadd fp128 %y, %y
  br i1 undef, label %C, label %D
C:
  %xx2 = fadd fp128 %x, %x
  br label %B
D:
  %xx3 = fadd fp128 %x, %x
  ret i32 0
}

define dso_local i32 @test7(fp128 %y) local_unnamed_addr #0 {
; CHECK-LABEL: @test7(
; CHECK-NEXT:  A:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP0]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP0]], ptr [[TMP1]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP2:%.*]] = load fp128, ptr [[TMP0]], align 16
; CHECK-NEXT:    br i1 undef, label [[B:%.*]], label [[C:%.*]]
; CHECK:       B:
; CHECK-NEXT:    [[TMP3:%.*]] = phi fp128 [ [[TMP2]], [[A:%.*]] ], [ [[TMP4:%.*]], [[C]] ]
; CHECK-NEXT:    br i1 undef, label [[C]], label [[D:%.*]]
; CHECK:       C:
; CHECK-NEXT:    [[TMP4]] = phi fp128 [ [[TMP2]], [[A]] ], [ [[TMP3]], [[B]] ]
; CHECK-NEXT:    br label [[B]]
; CHECK:       D:
; CHECK-NEXT:    ret i32 0
;
A:
  %0 = fadd fp128 %y, %y
  br i1 undef, label %B, label %C
B:
  %1 = phi fp128 [%0, %A], [%2, %C]
  br i1 undef, label %C, label %D
C:
  %2 = phi fp128 [%0, %A], [%1, %B]
  br label %B
D:
  ret i32 0
}
