; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -bugpoint-enable-legacy-pm -S -mtriple=x86_64-unknown-unknown -float128-expand -intel-libirc-allowed | FileCheck %s

define <2 x fp128> @test_fadd(<2 x fp128> %x, <2 x fp128> %y) {
; CHECK-LABEL: @test_fadd(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP6:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <2 x fp128> [[Y:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP6]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP5]])
; CHECK-NEXT:    store fp128 [[TMP7]], ptr [[TMP5]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    store fp128 [[TMP8]], ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @__addq(ptr [[TMP6]], ptr [[TMP5]], ptr [[TMP4]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP5]])
; CHECK-NEXT:    [[TMP9:%.*]] = load fp128, ptr [[TMP6]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP6]])
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP9]], i64 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <2 x fp128> [[Y]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP11]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP12]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @__addq(ptr [[TMP3]], ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP13:%.*]] = load fp128, ptr [[TMP3]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <2 x fp128> [[TMP10]], fp128 [[TMP13]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fadd <2 x fp128> [[X]], [[Y]]
; CHECK-NEXT:    ret <2 x fp128> [[TMP14]]
;
  %a = fadd <2 x fp128> %x, %y
  ret <2 x fp128> %a
}

define <2 x fp128> @test_fsub(<2 x fp128> %x, <2 x fp128> %y) {
; CHECK-LABEL: @test_fsub(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP6:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <2 x fp128> [[Y:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP6]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP5]])
; CHECK-NEXT:    store fp128 [[TMP7]], ptr [[TMP5]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    store fp128 [[TMP8]], ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @__subq(ptr [[TMP6]], ptr [[TMP5]], ptr [[TMP4]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP5]])
; CHECK-NEXT:    [[TMP9:%.*]] = load fp128, ptr [[TMP6]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP6]])
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP9]], i64 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <2 x fp128> [[Y]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP11]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP12]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @__subq(ptr [[TMP3]], ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP13:%.*]] = load fp128, ptr [[TMP3]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <2 x fp128> [[TMP10]], fp128 [[TMP13]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fsub <2 x fp128> [[X]], [[Y]]
; CHECK-NEXT:    ret <2 x fp128> [[TMP14]]
;
  %a = fsub <2 x fp128> %x, %y
  ret <2 x fp128> %a
}

define <2 x fp128> @test_fmul(<2 x fp128> %x, <2 x fp128> %y) {
; CHECK-LABEL: @test_fmul(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP6:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <2 x fp128> [[Y:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP6]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP5]])
; CHECK-NEXT:    store fp128 [[TMP7]], ptr [[TMP5]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    store fp128 [[TMP8]], ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @__mulq(ptr [[TMP6]], ptr [[TMP5]], ptr [[TMP4]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP5]])
; CHECK-NEXT:    [[TMP9:%.*]] = load fp128, ptr [[TMP6]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP6]])
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP9]], i64 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <2 x fp128> [[Y]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP11]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP12]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @__mulq(ptr [[TMP3]], ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP13:%.*]] = load fp128, ptr [[TMP3]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <2 x fp128> [[TMP10]], fp128 [[TMP13]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fmul <2 x fp128> [[X]], [[Y]]
; CHECK-NEXT:    ret <2 x fp128> [[TMP14]]
;
  %a = fmul <2 x fp128> %x, %y
  ret <2 x fp128> %a
}

define <2 x fp128> @test_fneg(<2 x fp128> %x) {
; CHECK-LABEL: @test_fneg(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[TMP5]], ptr [[TMP3]], align 16
; CHECK-NEXT:    call void @__negq(ptr [[TMP4]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    [[TMP6:%.*]] = load fp128, ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP6]], i64 0
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP8]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @__negq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP9:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x fp128> [[TMP7]], fp128 [[TMP9]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fneg <2 x fp128> [[X]]
; CHECK-NEXT:    ret <2 x fp128> [[TMP10]]
;
  %a = fneg <2 x fp128> %x
  ret <2 x fp128> %a
}

define <2 x fp128> @test_fneg_idiom(<2 x fp128> %x) {
; CHECK-LABEL: @test_fneg_idiom(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[TMP5]], ptr [[TMP3]], align 16
; CHECK-NEXT:    call void @__negq(ptr [[TMP4]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    [[TMP6:%.*]] = load fp128, ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP6]], i64 0
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP8]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @__negq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP9:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x fp128> [[TMP7]], fp128 [[TMP9]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fsub <2 x fp128> <fp128 0xL00000000000000008000000000000000, fp128 0xL00000000000000008000000000000000>, [[X]]
; CHECK-NEXT:    ret <2 x fp128> [[TMP10]]
;
  %a = fsub <2 x fp128> <fp128 0xL00000000000000008000000000000000, fp128 0xL00000000000000008000000000000000>, %x
  ret <2 x fp128> %a
}

define <2 x float> @test_fptrunc_float(<2 x fp128> %x) {
; CHECK-LABEL: @test_fptrunc_float(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = call float @__qtof(ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x float> undef, float [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call float @__qtof(ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x float> [[TMP5]], float [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fptrunc <2 x fp128> [[X]] to <2 x float>
; CHECK-NEXT:    ret <2 x float> [[TMP8]]
;
  %a = fptrunc <2 x fp128> %x to <2 x float>
  ret <2 x float> %a
}

define <2 x double> @test_fptrunc_double(<2 x fp128> %x) {
; CHECK-LABEL: @test_fptrunc_double(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = call double @__qtod(ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x double> undef, double [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call double @__qtod(ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x double> [[TMP5]], double [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fptrunc <2 x fp128> [[X]] to <2 x double>
; CHECK-NEXT:    ret <2 x double> [[TMP8]]
;
  %a = fptrunc <2 x fp128> %x to <2 x double>
  ret <2 x double> %a
}

define <2 x x86_fp80> @test_fptrunc_fp80(<2 x fp128> %x) {
; CHECK-LABEL: @test_fptrunc_fp80(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = call x86_fp80 @__qtol(ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x x86_fp80> undef, x86_fp80 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call x86_fp80 @__qtol(ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x x86_fp80> [[TMP5]], x86_fp80 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fptrunc <2 x fp128> [[X]] to <2 x x86_fp80>
; CHECK-NEXT:    ret <2 x x86_fp80> [[TMP8]]
;
  %a = fptrunc <2 x fp128> %x to <2 x x86_fp80>
  ret <2 x x86_fp80> %a
}

define <2 x fp128> @test_fpext_float(<2 x float> %x) {
; CHECK-LABEL: @test_fpext_float(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x float> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__ftoq(ptr [[TMP2]], float [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x float> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__ftoq(ptr [[TMP1]], float [[TMP6]])
; CHECK-NEXT:    [[TMP7:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x fp128> [[TMP5]], fp128 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fpext <2 x float> [[X]] to <2 x fp128>
; CHECK-NEXT:    ret <2 x fp128> [[TMP8]]
;
  %a = fpext <2 x float> %x to <2 x fp128>
  ret <2 x fp128> %a
}

define <2 x fp128> @test_fpext_double(<2 x double> %x) {
; CHECK-LABEL: @test_fpext_double(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x double> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__dtoq(ptr [[TMP2]], double [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x double> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__dtoq(ptr [[TMP1]], double [[TMP6]])
; CHECK-NEXT:    [[TMP7:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x fp128> [[TMP5]], fp128 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fpext <2 x double> [[X]] to <2 x fp128>
; CHECK-NEXT:    ret <2 x fp128> [[TMP8]]
;
  %a = fpext <2 x double> %x to <2 x fp128>
  ret <2 x fp128> %a
}

define <2 x fp128> @test_fpext_fp80(<2 x x86_fp80> %x) {
; CHECK-LABEL: @test_fpext_fp80(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x x86_fp80> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__ltoq(ptr [[TMP2]], x86_fp80 [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x x86_fp80> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__ltoq(ptr [[TMP1]], x86_fp80 [[TMP6]])
; CHECK-NEXT:    [[TMP7:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x fp128> [[TMP5]], fp128 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fpext <2 x x86_fp80> [[X]] to <2 x fp128>
; CHECK-NEXT:    ret <2 x fp128> [[TMP8]]
;
  %a = fpext <2 x x86_fp80> %x to <2 x fp128>
  ret <2 x fp128> %a
}

define <2 x fp128> @test_sitofp_i8(<2 x i8> %x) {
; CHECK-LABEL: @test_sitofp_i8(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i8> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP4:%.*]] = sext i8 [[TMP3]] to i32
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__itoq(ptr [[TMP2]], i32 [[TMP4]])
; CHECK-NEXT:    [[TMP5:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP5]], i64 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x i8> [[X]], i64 1
; CHECK-NEXT:    [[TMP8:%.*]] = sext i8 [[TMP7]] to i32
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__itoq(ptr [[TMP1]], i32 [[TMP8]])
; CHECK-NEXT:    [[TMP9:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x fp128> [[TMP6]], fp128 [[TMP9]], i64 1
; CHECK-NEXT:    [[A:%.*]] = sitofp <2 x i8> [[X]] to <2 x fp128>
; CHECK-NEXT:    ret <2 x fp128> [[TMP10]]
;
  %a = sitofp <2 x i8> %x to <2 x fp128>
  ret <2 x fp128> %a
}

define <2 x fp128> @test_sitofp_i16(<2 x i16> %x) {
; CHECK-LABEL: @test_sitofp_i16(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i16> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP4:%.*]] = sext i16 [[TMP3]] to i32
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__itoq(ptr [[TMP2]], i32 [[TMP4]])
; CHECK-NEXT:    [[TMP5:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP5]], i64 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x i16> [[X]], i64 1
; CHECK-NEXT:    [[TMP8:%.*]] = sext i16 [[TMP7]] to i32
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__itoq(ptr [[TMP1]], i32 [[TMP8]])
; CHECK-NEXT:    [[TMP9:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x fp128> [[TMP6]], fp128 [[TMP9]], i64 1
; CHECK-NEXT:    [[A:%.*]] = sitofp <2 x i16> [[X]] to <2 x fp128>
; CHECK-NEXT:    ret <2 x fp128> [[TMP10]]
;
  %a = sitofp <2 x i16> %x to <2 x fp128>
  ret <2 x fp128> %a
}

define <2 x fp128> @test_sitofp_i32(<2 x i32> %x) {
; CHECK-LABEL: @test_sitofp_i32(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i32> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__itoq(ptr [[TMP2]], i32 [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x i32> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__itoq(ptr [[TMP1]], i32 [[TMP6]])
; CHECK-NEXT:    [[TMP7:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x fp128> [[TMP5]], fp128 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = sitofp <2 x i32> [[X]] to <2 x fp128>
; CHECK-NEXT:    ret <2 x fp128> [[TMP8]]
;
  %a = sitofp <2 x i32> %x to <2 x fp128>
  ret <2 x fp128> %a
}

define <2 x fp128> @test_sitofp_i64(<2 x i64> %x) {
; CHECK-LABEL: @test_sitofp_i64(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i64> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__jtoq(ptr [[TMP2]], i64 [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x i64> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__jtoq(ptr [[TMP1]], i64 [[TMP6]])
; CHECK-NEXT:    [[TMP7:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x fp128> [[TMP5]], fp128 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = sitofp <2 x i64> [[X]] to <2 x fp128>
; CHECK-NEXT:    ret <2 x fp128> [[TMP8]]
;
  %a = sitofp <2 x i64> %x to <2 x fp128>
  ret <2 x fp128> %a
}

define <2 x fp128> @test_sitofp_i128(<2 x i128> %x) {
; CHECK-LABEL: @test_sitofp_i128(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__mtoq(ptr [[TMP2]], i128 [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x i128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__mtoq(ptr [[TMP1]], i128 [[TMP6]])
; CHECK-NEXT:    [[TMP7:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x fp128> [[TMP5]], fp128 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = sitofp <2 x i128> [[X]] to <2 x fp128>
; CHECK-NEXT:    ret <2 x fp128> [[TMP8]]
;
  %a = sitofp <2 x i128> %x to <2 x fp128>
  ret <2 x fp128> %a
}

define <2 x fp128> @test_uitofp_i8(<2 x i8> %x) {
; CHECK-LABEL: @test_uitofp_i8(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i8> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP4:%.*]] = zext i8 [[TMP3]] to i32
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__utoq(ptr [[TMP2]], i32 [[TMP4]])
; CHECK-NEXT:    [[TMP5:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP5]], i64 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x i8> [[X]], i64 1
; CHECK-NEXT:    [[TMP8:%.*]] = zext i8 [[TMP7]] to i32
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__utoq(ptr [[TMP1]], i32 [[TMP8]])
; CHECK-NEXT:    [[TMP9:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x fp128> [[TMP6]], fp128 [[TMP9]], i64 1
; CHECK-NEXT:    [[A:%.*]] = uitofp <2 x i8> [[X]] to <2 x fp128>
; CHECK-NEXT:    ret <2 x fp128> [[TMP10]]
;
  %a = uitofp <2 x i8> %x to <2 x fp128>
  ret <2 x fp128> %a
}

define <2 x fp128> @test_uitofp_i16(<2 x i16> %x) {
; CHECK-LABEL: @test_uitofp_i16(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i16> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP4:%.*]] = zext i16 [[TMP3]] to i32
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__utoq(ptr [[TMP2]], i32 [[TMP4]])
; CHECK-NEXT:    [[TMP5:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP5]], i64 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x i16> [[X]], i64 1
; CHECK-NEXT:    [[TMP8:%.*]] = zext i16 [[TMP7]] to i32
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__utoq(ptr [[TMP1]], i32 [[TMP8]])
; CHECK-NEXT:    [[TMP9:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x fp128> [[TMP6]], fp128 [[TMP9]], i64 1
; CHECK-NEXT:    [[A:%.*]] = uitofp <2 x i16> [[X]] to <2 x fp128>
; CHECK-NEXT:    ret <2 x fp128> [[TMP10]]
;
  %a = uitofp <2 x i16> %x to <2 x fp128>
  ret <2 x fp128> %a
}

define <2 x fp128> @test_uitofp_i32(<2 x i32> %x) {
; CHECK-LABEL: @test_uitofp_i32(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i32> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__utoq(ptr [[TMP2]], i32 [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x i32> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__utoq(ptr [[TMP1]], i32 [[TMP6]])
; CHECK-NEXT:    [[TMP7:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x fp128> [[TMP5]], fp128 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = uitofp <2 x i32> [[X]] to <2 x fp128>
; CHECK-NEXT:    ret <2 x fp128> [[TMP8]]
;
  %a = uitofp <2 x i32> %x to <2 x fp128>
  ret <2 x fp128> %a
}

define <2 x fp128> @test_uitofp_i64(<2 x i64> %x) {
; CHECK-LABEL: @test_uitofp_i64(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i64> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__ktoq(ptr [[TMP2]], i64 [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x i64> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__ktoq(ptr [[TMP1]], i64 [[TMP6]])
; CHECK-NEXT:    [[TMP7:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x fp128> [[TMP5]], fp128 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = uitofp <2 x i64> [[X]] to <2 x fp128>
; CHECK-NEXT:    ret <2 x fp128> [[TMP8]]
;
  %a = uitofp <2 x i64> %x to <2 x fp128>
  ret <2 x fp128> %a
}

define <2 x fp128> @test_uitofp_i128(<2 x i128> %x) {
; CHECK-LABEL: @test_uitofp_i128(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @__ntoq(ptr [[TMP2]], i128 [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x fp128> undef, fp128 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x i128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__ntoq(ptr [[TMP1]], i128 [[TMP6]])
; CHECK-NEXT:    [[TMP7:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x fp128> [[TMP5]], fp128 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = uitofp <2 x i128> [[X]] to <2 x fp128>
; CHECK-NEXT:    ret <2 x fp128> [[TMP8]]
;
  %a = uitofp <2 x i128> %x to <2 x fp128>
  ret <2 x fp128> %a
}

define <2 x i8> @test_fptosi_i8(<2 x fp128> %x) {
; CHECK-LABEL: @test_fptosi_i8(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @__qtoi(ptr [[TMP2]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i8
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x i8> undef, i8 [[TMP5]], i64 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP7]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP8:%.*]] = call i32 @__qtoi(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[TMP8]] to i8
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x i8> [[TMP6]], i8 [[TMP9]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fptosi <2 x fp128> [[X]] to <2 x i8>
; CHECK-NEXT:    ret <2 x i8> [[TMP10]]
;
  %a = fptosi <2 x fp128> %x to <2 x i8>
  ret <2 x i8> %a
}

define <2 x i16> @test_fptosi_i16(<2 x fp128> %x) {
; CHECK-LABEL: @test_fptosi_i16(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @__qtoi(ptr [[TMP2]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i16
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x i16> undef, i16 [[TMP5]], i64 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP7]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP8:%.*]] = call i32 @__qtoi(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[TMP8]] to i16
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x i16> [[TMP6]], i16 [[TMP9]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fptosi <2 x fp128> [[X]] to <2 x i16>
; CHECK-NEXT:    ret <2 x i16> [[TMP10]]
;
  %a = fptosi <2 x fp128> %x to <2 x i16>
  ret <2 x i16> %a
}

define <2 x i32> @test_fptosi_i32(<2 x fp128> %x) {
; CHECK-LABEL: @test_fptosi_i32(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @__qtoi(ptr [[TMP2]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i32> undef, i32 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__qtoi(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x i32> [[TMP5]], i32 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fptosi <2 x fp128> [[X]] to <2 x i32>
; CHECK-NEXT:    ret <2 x i32> [[TMP8]]
;
  %a = fptosi <2 x fp128> %x to <2 x i32>
  ret <2 x i32> %a
}

define <2 x i32> @test_fptosi_i32_const() {
; CHECK-LABEL: @test_fptosi_i32_const(
; CHECK-NEXT:    [[A:%.*]] = fptosi <2 x fp128> <fp128 0xL00000000000000003FFEE66666000000, fp128 0xL00000000000000003FFEE66666000000> to <2 x i32>
; CHECK-NEXT:    ret <2 x i32> zeroinitializer
;
  %a = fptosi <2 x fp128> <fp128 0xL00000000000000003FFEE66666000000, fp128 0xL00000000000000003FFEE66666000000> to <2 x i32>
  ret <2 x i32> %a
}

define <2 x i64> @test_fptosi_i64(<2 x fp128> %x) {
; CHECK-LABEL: @test_fptosi_i64(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @__qtoj(ptr [[TMP2]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i64> undef, i64 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i64 @__qtoj(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x i64> [[TMP5]], i64 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fptosi <2 x fp128> [[X]] to <2 x i64>
; CHECK-NEXT:    ret <2 x i64> [[TMP8]]
;
  %a = fptosi <2 x fp128> %x to <2 x i64>
  ret <2 x i64> %a
}

define <2 x i128> @test_fptosi_i128(<2 x fp128> %x) {
; CHECK-LABEL: @test_fptosi_i128(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = call i128 @__qtom(ptr [[TMP2]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i128> undef, i128 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i128 @__qtom(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x i128> [[TMP5]], i128 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fptosi <2 x fp128> [[X]] to <2 x i128>
; CHECK-NEXT:    ret <2 x i128> [[TMP8]]
;
  %a = fptosi <2 x fp128> %x to <2 x i128>
  ret <2 x i128> %a
}

define <2 x i8> @test_fptoui_i8(<2 x fp128> %x) {
; CHECK-LABEL: @test_fptoui_i8(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @__qtou(ptr [[TMP2]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i8
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x i8> undef, i8 [[TMP5]], i64 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP7]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP8:%.*]] = call i32 @__qtou(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[TMP8]] to i8
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x i8> [[TMP6]], i8 [[TMP9]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fptoui <2 x fp128> [[X]] to <2 x i8>
; CHECK-NEXT:    ret <2 x i8> [[TMP10]]
;
  %a = fptoui <2 x fp128> %x to <2 x i8>
  ret <2 x i8> %a
}

define <2 x i16> @test_fptoui_i16(<2 x fp128> %x) {
; CHECK-LABEL: @test_fptoui_i16(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @__qtou(ptr [[TMP2]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i32 [[TMP4]] to i16
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x i16> undef, i16 [[TMP5]], i64 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP7]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP8:%.*]] = call i32 @__qtou(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[TMP8]] to i16
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x i16> [[TMP6]], i16 [[TMP9]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fptoui <2 x fp128> [[X]] to <2 x i16>
; CHECK-NEXT:    ret <2 x i16> [[TMP10]]
;
  %a = fptoui <2 x fp128> %x to <2 x i16>
  ret <2 x i16> %a
}

define <2 x i32> @test_fptoui_i32(<2 x fp128> %x) {
; CHECK-LABEL: @test_fptoui_i32(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @__qtou(ptr [[TMP2]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i32> undef, i32 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__qtou(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x i32> [[TMP5]], i32 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fptoui <2 x fp128> [[X]] to <2 x i32>
; CHECK-NEXT:    ret <2 x i32> [[TMP8]]
;
  %a = fptoui <2 x fp128> %x to <2 x i32>
  ret <2 x i32> %a
}

define <2 x i64> @test_fptoui_i64(<2 x fp128> %x) {
; CHECK-LABEL: @test_fptoui_i64(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @__qtok(ptr [[TMP2]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i64> undef, i64 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i64 @__qtok(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x i64> [[TMP5]], i64 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fptoui <2 x fp128> [[X]] to <2 x i64>
; CHECK-NEXT:    ret <2 x i64> [[TMP8]]
;
  %a = fptoui <2 x fp128> %x to <2 x i64>
  ret <2 x i64> %a
}

define <2 x i128> @test_fptoui_i128(<2 x fp128> %x) {
; CHECK-LABEL: @test_fptoui_i128(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = call i128 @__qton(ptr [[TMP2]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i128> undef, i128 [[TMP4]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i128 @__qton(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x i128> [[TMP5]], i128 [[TMP7]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fptoui <2 x fp128> [[X]] to <2 x i128>
; CHECK-NEXT:    ret <2 x i128> [[TMP8]]
;
  %a = fptoui <2 x fp128> %x to <2 x i128>
  ret <2 x i128> %a
}

define <2 x i1> @test_fcmp_oeq(<2 x fp128> %x, <2 x fp128> %y) {
; CHECK-LABEL: @test_fcmp_oeq(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[Y:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    store fp128 [[TMP5]], ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP3]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__eqq(ptr [[TMP4]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i1
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x i1> undef, i1 [[TMP8]], i64 0
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x fp128> [[Y]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP10]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP11]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP12:%.*]] = call i32 @__eqq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i1
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <2 x i1> [[TMP9]], i1 [[TMP13]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fcmp oeq <2 x fp128> [[X]], [[Y]]
; CHECK-NEXT:    ret <2 x i1> [[TMP14]]
;
  %a = fcmp oeq <2 x fp128> %x, %y
  ret <2 x i1> %a
}

define <2 x i1> @test_fcmp_une(<2 x fp128> %x, <2 x fp128> %y) {
; CHECK-LABEL: @test_fcmp_une(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[Y:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    store fp128 [[TMP5]], ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP3]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__neq(ptr [[TMP4]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i1
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x i1> undef, i1 [[TMP8]], i64 0
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x fp128> [[Y]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP10]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP11]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP12:%.*]] = call i32 @__neq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i1
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <2 x i1> [[TMP9]], i1 [[TMP13]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fcmp une <2 x fp128> [[X]], [[Y]]
; CHECK-NEXT:    ret <2 x i1> [[TMP14]]
;
  %a = fcmp une <2 x fp128> %x, %y
  ret <2 x i1> %a
}

define <2 x i1> @test_fcmp_olt(<2 x fp128> %x, <2 x fp128> %y) {
; CHECK-LABEL: @test_fcmp_olt(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[Y:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    store fp128 [[TMP5]], ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP3]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__ltq(ptr [[TMP4]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i1
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x i1> undef, i1 [[TMP8]], i64 0
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x fp128> [[Y]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP10]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP11]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP12:%.*]] = call i32 @__ltq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i1
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <2 x i1> [[TMP9]], i1 [[TMP13]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fcmp olt <2 x fp128> [[X]], [[Y]]
; CHECK-NEXT:    ret <2 x i1> [[TMP14]]
;
  %a = fcmp olt <2 x fp128> %x, %y
  ret <2 x i1> %a
}

define <2 x i1> @test_fcmp_ogt(<2 x fp128> %x, <2 x fp128> %y) {
; CHECK-LABEL: @test_fcmp_ogt(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[Y:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    store fp128 [[TMP5]], ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP3]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__gtq(ptr [[TMP4]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i1
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x i1> undef, i1 [[TMP8]], i64 0
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x fp128> [[Y]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP10]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP11]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP12:%.*]] = call i32 @__gtq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i1
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <2 x i1> [[TMP9]], i1 [[TMP13]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fcmp ogt <2 x fp128> [[X]], [[Y]]
; CHECK-NEXT:    ret <2 x i1> [[TMP14]]
;
  %a = fcmp ogt <2 x fp128> %x, %y
  ret <2 x i1> %a
}

define <2 x i1> @test_fcmp_ole(<2 x fp128> %x, <2 x fp128> %y) {
; CHECK-LABEL: @test_fcmp_ole(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[Y:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    store fp128 [[TMP5]], ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP3]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__leq(ptr [[TMP4]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i1
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x i1> undef, i1 [[TMP8]], i64 0
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x fp128> [[Y]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP10]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP11]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP12:%.*]] = call i32 @__leq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i1
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <2 x i1> [[TMP9]], i1 [[TMP13]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fcmp ole <2 x fp128> [[X]], [[Y]]
; CHECK-NEXT:    ret <2 x i1> [[TMP14]]
;
  %a = fcmp ole <2 x fp128> %x, %y
  ret <2 x i1> %a
}

define <2 x i1> @test_fcmp_oge(<2 x fp128> %x, <2 x fp128> %y) {
; CHECK-LABEL: @test_fcmp_oge(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[Y:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    store fp128 [[TMP5]], ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP3]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__geq(ptr [[TMP4]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i1
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x i1> undef, i1 [[TMP8]], i64 0
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x fp128> [[Y]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP10]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP11]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP12:%.*]] = call i32 @__geq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP13:%.*]] = trunc i32 [[TMP12]] to i1
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <2 x i1> [[TMP9]], i1 [[TMP13]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fcmp oge <2 x fp128> [[X]], [[Y]]
; CHECK-NEXT:    ret <2 x i1> [[TMP14]]
;
  %a = fcmp oge <2 x fp128> %x, %y
  ret <2 x i1> %a
}

define <2 x i1> @test_fcmp_ult(<2 x fp128> %x, <2 x fp128> %y) {
; CHECK-LABEL: @test_fcmp_ult(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[Y:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    store fp128 [[TMP5]], ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP3]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__geq(ptr [[TMP4]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i1
; CHECK-NEXT:    [[TMP9:%.*]] = xor i1 [[TMP8]], true
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x i1> undef, i1 [[TMP9]], i64 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <2 x fp128> [[Y]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP11]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP12]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP13:%.*]] = call i32 @__geq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[TMP13]] to i1
; CHECK-NEXT:    [[TMP15:%.*]] = xor i1 [[TMP14]], true
; CHECK-NEXT:    [[TMP16:%.*]] = insertelement <2 x i1> [[TMP10]], i1 [[TMP15]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fcmp ult <2 x fp128> [[X]], [[Y]]
; CHECK-NEXT:    ret <2 x i1> [[TMP16]]
;
  %a = fcmp ult <2 x fp128> %x, %y
  ret <2 x i1> %a
}

define <2 x i1> @test_fcmp_ugt(<2 x fp128> %x, <2 x fp128> %y) {
; CHECK-LABEL: @test_fcmp_ugt(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[Y:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    store fp128 [[TMP5]], ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP3]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__leq(ptr [[TMP4]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i1
; CHECK-NEXT:    [[TMP9:%.*]] = xor i1 [[TMP8]], true
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x i1> undef, i1 [[TMP9]], i64 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <2 x fp128> [[Y]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP11]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP12]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP13:%.*]] = call i32 @__leq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[TMP13]] to i1
; CHECK-NEXT:    [[TMP15:%.*]] = xor i1 [[TMP14]], true
; CHECK-NEXT:    [[TMP16:%.*]] = insertelement <2 x i1> [[TMP10]], i1 [[TMP15]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fcmp ugt <2 x fp128> [[X]], [[Y]]
; CHECK-NEXT:    ret <2 x i1> [[TMP16]]
;
  %a = fcmp ugt <2 x fp128> %x, %y
  ret <2 x i1> %a
}

define <2 x i1> @test_fcmp_ule(<2 x fp128> %x, <2 x fp128> %y) {
; CHECK-LABEL: @test_fcmp_ule(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[Y:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    store fp128 [[TMP5]], ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP3]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__gtq(ptr [[TMP4]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i1
; CHECK-NEXT:    [[TMP9:%.*]] = xor i1 [[TMP8]], true
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x i1> undef, i1 [[TMP9]], i64 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <2 x fp128> [[Y]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP11]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP12]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP13:%.*]] = call i32 @__gtq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[TMP13]] to i1
; CHECK-NEXT:    [[TMP15:%.*]] = xor i1 [[TMP14]], true
; CHECK-NEXT:    [[TMP16:%.*]] = insertelement <2 x i1> [[TMP10]], i1 [[TMP15]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fcmp ule <2 x fp128> [[X]], [[Y]]
; CHECK-NEXT:    ret <2 x i1> [[TMP16]]
;
  %a = fcmp ule <2 x fp128> %x, %y
  ret <2 x i1> %a
}

define <2 x i1> @test_fcmp_uge(<2 x fp128> %x, <2 x fp128> %y) {
; CHECK-LABEL: @test_fcmp_uge(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP4:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x fp128> [[X:%.*]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x fp128> [[Y:%.*]], i64 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    store fp128 [[TMP5]], ptr [[TMP4]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[TMP6]], ptr [[TMP3]], align 16
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__ltq(ptr [[TMP4]], ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP4]])
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i1
; CHECK-NEXT:    [[TMP9:%.*]] = xor i1 [[TMP8]], true
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <2 x i1> undef, i1 [[TMP9]], i64 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <2 x fp128> [[X]], i64 1
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <2 x fp128> [[Y]], i64 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[TMP11]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[TMP12]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP13:%.*]] = call i32 @__ltq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[TMP13]] to i1
; CHECK-NEXT:    [[TMP15:%.*]] = xor i1 [[TMP14]], true
; CHECK-NEXT:    [[TMP16:%.*]] = insertelement <2 x i1> [[TMP10]], i1 [[TMP15]], i64 1
; CHECK-NEXT:    [[A:%.*]] = fcmp uge <2 x fp128> [[X]], [[Y]]
; CHECK-NEXT:    ret <2 x i1> [[TMP16]]
;
  %a = fcmp uge <2 x fp128> %x, %y
  ret <2 x i1> %a
}
