; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -bugpoint-enable-legacy-pm -S -mtriple=x86_64-unknown-unknown -float128-expand -intel-libirc-allowed | FileCheck %s

; Function Attrs: nofree noreturn nounwind uwtable
define dso_local i32 @main1(fp128 %x) local_unnamed_addr #0 {
; CHECK-LABEL: @main1(
; CHECK-NEXT:  bb1:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i32 1, 0
; CHECK-NEXT:    br i1 undef, label [[BB2:%.*]], label [[BB3:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP0]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP0]], ptr [[TMP2]], ptr [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP0]], align 16
; CHECK-NEXT:    [[TMP5:%.*]] = call i32 @__eqq(ptr [[TMP0]], ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP0]])
; CHECK-NEXT:    [[TMP6:%.*]] = trunc i32 [[TMP5]] to i1
; CHECK-NEXT:    br label [[BB4:%.*]]
; CHECK:       bb3:
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @__eqq(ptr [[TMP2]], ptr [[TMP2]])
; CHECK-NEXT:    [[TMP8:%.*]] = trunc i32 [[TMP7]] to i1
; CHECK-NEXT:    br label [[BB4]]
; CHECK:       bb4:
; CHECK-NEXT:    [[TMP9:%.*]] = phi i32 [ 1, [[BB3]] ], [ 2, [[BB2]] ]
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__itoq(ptr [[TMP1]], i32 [[TMP9]])
; CHECK-NEXT:    [[TMP10:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP11:%.*]] = call i32 @__eqq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP12:%.*]] = trunc i32 [[TMP11]] to i1
; CHECK-NEXT:    [[TMP13:%.*]] = zext i1 [[TMP12]] to i32
; CHECK-NEXT:    ret i32 [[TMP13]]
;
bb1:
  %0 = icmp eq i32 1, 0
  br i1 undef, label %bb2, label %bb3
bb2:
  %1 = fadd fp128 %x, %x
  %2 = fcmp oeq fp128 %1, %x
  br label %bb4
bb3:
  %3 = fcmp oeq fp128 %x, %x
  br label %bb4
bb4:
  %4 = phi i32 [1, %bb3], [2, %bb2]
  %5 = sitofp i32 %4 to fp128
  %6 = fcmp oeq fp128 %x, %5
  %7 = zext i1 %6 to i32
  ret i32 %7
}
