; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -bugpoint-enable-legacy-pm -S -mtriple=x86_64-unknown-unknown -float128-expand -intel-libirc-allowed | FileCheck %s

define fp128 @test_fadd(fp128 %x, fp128 %y) {
; CHECK-LABEL: @test_fadd(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP3]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP1]], ptr [[TMP3]], ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP4]]
;
  %a = fadd fp128 %x, %y
  ret fp128 %a
}

define fp128 @test_fsub(fp128 %x, fp128 %y) {
; CHECK-LABEL: @test_fsub(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP3]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__subq(ptr [[TMP1]], ptr [[TMP3]], ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP4]]
;
  %a = fsub fp128 %x, %y
  ret fp128 %a
}

define fp128 @test_fmul(fp128 %x, fp128 %y) {
; CHECK-LABEL: @test_fmul(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP3:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP3]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__mulq(ptr [[TMP1]], ptr [[TMP3]], ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP4]]
;
  %a = fmul fp128 %x, %y
  ret fp128 %a
}

define fp128 @test_fneg(fp128 %x) {
; CHECK-LABEL: @test_fneg(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__negq(ptr [[TMP1]], ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP3:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP3]]
;
  %a = fneg fp128 %x
  ret fp128 %a
}

define fp128 @test_fneg_idiom(fp128 %x) {
; CHECK-LABEL: @test_fneg_idiom(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__negq(ptr [[TMP1]], ptr [[TMP2]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP3:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP3]]
;
  %a = fsub fp128 0xL00000000000000008000000000000000, %x
  ret fp128 %a
}

define float @test_fptrunc_float(fp128 %x) {
; CHECK-LABEL: @test_fptrunc_float(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call float @__qtof(ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret float [[TMP2]]
;
  %a = fptrunc fp128 %x to float
  ret float %a
}

define double @test_fptrunc_double(fp128 %x) {
; CHECK-LABEL: @test_fptrunc_double(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call double @__qtod(ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret double [[TMP2]]
;
  %a = fptrunc fp128 %x to double
  ret double %a
}

define x86_fp80 @test_fptrunc_fp80(fp128 %x) {
; CHECK-LABEL: @test_fptrunc_fp80(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call x86_fp80 @__qtol(ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret x86_fp80 [[TMP2]]
;
  %a = fptrunc fp128 %x to x86_fp80
  ret x86_fp80 %a
}

define fp128 @test_fpext_float(float %x) {
; CHECK-LABEL: @test_fpext_float(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__ftoq(ptr [[TMP1]], float [[X:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP2]]
;
  %a = fpext float %x to fp128
  ret fp128 %a
}

define fp128 @test_fpext_double(double %x) {
; CHECK-LABEL: @test_fpext_double(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__dtoq(ptr [[TMP1]], double [[X:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP2]]
;
  %a = fpext double %x to fp128
  ret fp128 %a
}

define fp128 @test_fpext_fp80(x86_fp80 %x) {
; CHECK-LABEL: @test_fpext_fp80(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__ltoq(ptr [[TMP1]], x86_fp80 [[X:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP2]]
;
  %a = fpext x86_fp80 %x to fp128
  ret fp128 %a
}

define fp128 @test_sitofp_i8(i8 %x) {
; CHECK-LABEL: @test_sitofp_i8(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = sext i8 [[X:%.*]] to i32
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__itoq(ptr [[TMP1]], i32 [[TMP2]])
; CHECK-NEXT:    [[TMP3:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP3]]
;
  %a = sitofp i8 %x to fp128
  ret fp128 %a
}

define fp128 @test_sitofp_i16(i16 %x) {
; CHECK-LABEL: @test_sitofp_i16(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = sext i16 [[X:%.*]] to i32
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__itoq(ptr [[TMP1]], i32 [[TMP2]])
; CHECK-NEXT:    [[TMP3:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP3]]
;
  %a = sitofp i16 %x to fp128
  ret fp128 %a
}

define fp128 @test_sitofp_i32(i32 %x) {
; CHECK-LABEL: @test_sitofp_i32(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__itoq(ptr [[TMP1]], i32 [[X:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP2]]
;
  %a = sitofp i32 %x to fp128
  ret fp128 %a
}

define fp128 @test_sitofp_i64(i64 %x) {
; CHECK-LABEL: @test_sitofp_i64(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__jtoq(ptr [[TMP1]], i64 [[X:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP2]]
;
  %a = sitofp i64 %x to fp128
  ret fp128 %a
}

define fp128 @test_sitofp_i128(i128 %x) {
; CHECK-LABEL: @test_sitofp_i128(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__mtoq(ptr [[TMP1]], i128 [[X:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP2]]
;
  %a = sitofp i128 %x to fp128
  ret fp128 %a
}

define fp128 @test_uitofp_i8(i8 %x) {
; CHECK-LABEL: @test_uitofp_i8(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = zext i8 [[X:%.*]] to i32
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__utoq(ptr [[TMP1]], i32 [[TMP2]])
; CHECK-NEXT:    [[TMP3:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP3]]
;
  %a = uitofp i8 %x to fp128
  ret fp128 %a
}

define fp128 @test_uitofp_i16(i16 %x) {
; CHECK-LABEL: @test_uitofp_i16(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = zext i16 [[X:%.*]] to i32
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__utoq(ptr [[TMP1]], i32 [[TMP2]])
; CHECK-NEXT:    [[TMP3:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP3]]
;
  %a = uitofp i16 %x to fp128
  ret fp128 %a
}

define fp128 @test_uitofp_i32(i32 %x) {
; CHECK-LABEL: @test_uitofp_i32(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__utoq(ptr [[TMP1]], i32 [[X:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP2]]
;
  %a = uitofp i32 %x to fp128
  ret fp128 %a
}

define fp128 @test_uitofp_i64(i64 %x) {
; CHECK-LABEL: @test_uitofp_i64(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__ktoq(ptr [[TMP1]], i64 [[X:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP2]]
;
  %a = uitofp i64 %x to fp128
  ret fp128 %a
}

define fp128 @test_uitofp_i128(i128 %x) {
; CHECK-LABEL: @test_uitofp_i128(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @__ntoq(ptr [[TMP1]], i128 [[X:%.*]])
; CHECK-NEXT:    [[TMP2:%.*]] = load fp128, ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret fp128 [[TMP2]]
;
  %a = uitofp i128 %x to fp128
  ret fp128 %a
}

define i8 @test_fptosi_i8(fp128 %x) {
; CHECK-LABEL: @test_fptosi_i8(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @__qtoi(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP2]] to i8
; CHECK-NEXT:    ret i8 [[TMP3]]
;
  %a = fptosi fp128 %x to i8
  ret i8 %a
}

define i16 @test_fptosi_i16(fp128 %x) {
; CHECK-LABEL: @test_fptosi_i16(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @__qtoi(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP2]] to i16
; CHECK-NEXT:    ret i16 [[TMP3]]
;
  %a = fptosi fp128 %x to i16
  ret i16 %a
}

define i32 @test_fptosi_i32(fp128 %x) {
; CHECK-LABEL: @test_fptosi_i32(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @__qtoi(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret i32 [[TMP2]]
;
  %a = fptosi fp128 %x to i32
  ret i32 %a
}

define i32 @test_fptosi_i32_const() {
; CHECK-LABEL: @test_fptosi_i32_const(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 0xL00000000000000003FFEE66666000000, ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @__qtoi(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret i32 [[TMP2]]
;
  %a = fptosi fp128 0xL00000000000000003FFEE66666000000 to i32
  ret i32 %a
}

define i64 @test_fptosi_i64(fp128 %x) {
; CHECK-LABEL: @test_fptosi_i64(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @__qtoj(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret i64 [[TMP2]]
;
  %a = fptosi fp128 %x to i64
  ret i64 %a
}

define i128 @test_fptosi_i128(fp128 %x) {
; CHECK-LABEL: @test_fptosi_i128(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call i128 @__qtom(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret i128 [[TMP2]]
;
  %a = fptosi fp128 %x to i128
  ret i128 %a
}

define i8 @test_fptoui_i8(fp128 %x) {
; CHECK-LABEL: @test_fptoui_i8(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @__qtou(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP2]] to i8
; CHECK-NEXT:    ret i8 [[TMP3]]
;
  %a = fptoui fp128 %x to i8
  ret i8 %a
}

define i16 @test_fptoui_i16(fp128 %x) {
; CHECK-LABEL: @test_fptoui_i16(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @__qtou(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP2]] to i16
; CHECK-NEXT:    ret i16 [[TMP3]]
;
  %a = fptoui fp128 %x to i16
  ret i16 %a
}

define i32 @test_fptoui_i32(fp128 %x) {
; CHECK-LABEL: @test_fptoui_i32(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @__qtou(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret i32 [[TMP2]]
;
  %a = fptoui fp128 %x to i32
  ret i32 %a
}

define i64 @test_fptoui_i64(fp128 %x) {
; CHECK-LABEL: @test_fptoui_i64(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @__qtok(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret i64 [[TMP2]]
;
  %a = fptoui fp128 %x to i64
  ret i64 %a
}

define i128 @test_fptoui_i128(fp128 %x) {
; CHECK-LABEL: @test_fptoui_i128(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call i128 @__qton(ptr [[TMP1]], i32 0)
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    ret i128 [[TMP2]]
;
  %a = fptoui fp128 %x to i128
  ret i128 %a
}

define i1 @test_fcmp_oeq(fp128 %x, fp128 %y) {
; CHECK-LABEL: @test_fcmp_oeq(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @__eqq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i1
; CHECK-NEXT:    ret i1 [[TMP4]]
;
  %a = fcmp oeq fp128 %x, %y
  ret i1 %a
}

define i1 @test_fcmp_une(fp128 %x, fp128 %y) {
; CHECK-LABEL: @test_fcmp_une(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @__neq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i1
; CHECK-NEXT:    ret i1 [[TMP4]]
;
  %a = fcmp une fp128 %x, %y
  ret i1 %a
}

define i1 @test_fcmp_olt(fp128 %x, fp128 %y) {
; CHECK-LABEL: @test_fcmp_olt(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @__ltq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i1
; CHECK-NEXT:    ret i1 [[TMP4]]
;
  %a = fcmp olt fp128 %x, %y
  ret i1 %a
}

define i1 @test_fcmp_ogt(fp128 %x, fp128 %y) {
; CHECK-LABEL: @test_fcmp_ogt(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @__gtq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i1
; CHECK-NEXT:    ret i1 [[TMP4]]
;
  %a = fcmp ogt fp128 %x, %y
  ret i1 %a
}

define i1 @test_fcmp_ole(fp128 %x, fp128 %y) {
; CHECK-LABEL: @test_fcmp_ole(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @__leq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i1
; CHECK-NEXT:    ret i1 [[TMP4]]
;
  %a = fcmp ole fp128 %x, %y
  ret i1 %a
}

define i1 @test_fcmp_oge(fp128 %x, fp128 %y) {
; CHECK-LABEL: @test_fcmp_oge(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @__geq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i1
; CHECK-NEXT:    ret i1 [[TMP4]]
;
  %a = fcmp oge fp128 %x, %y
  ret i1 %a
}

define i1 @test_fcmp_ult(fp128 %x, fp128 %y) {
; CHECK-LABEL: @test_fcmp_ult(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @__geq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i1
; CHECK-NEXT:    [[TMP5:%.*]] = xor i1 [[TMP4]], true
; CHECK-NEXT:    ret i1 [[TMP5]]
;
  %a = fcmp ult fp128 %x, %y
  ret i1 %a
}

define i1 @test_fcmp_ugt(fp128 %x, fp128 %y) {
; CHECK-LABEL: @test_fcmp_ugt(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @__leq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i1
; CHECK-NEXT:    [[TMP5:%.*]] = xor i1 [[TMP4]], true
; CHECK-NEXT:    ret i1 [[TMP5]]
;
  %a = fcmp ugt fp128 %x, %y
  ret i1 %a
}

define i1 @test_fcmp_ule(fp128 %x, fp128 %y) {
; CHECK-LABEL: @test_fcmp_ule(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @__gtq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i1
; CHECK-NEXT:    [[TMP5:%.*]] = xor i1 [[TMP4]], true
; CHECK-NEXT:    ret i1 [[TMP5]]
;
  %a = fcmp ule fp128 %x, %y
  ret i1 %a
}

define i1 @test_fcmp_uge(fp128 %x, fp128 %y) {
; CHECK-LABEL: @test_fcmp_uge(
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP2:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[Y:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @__ltq(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i1
; CHECK-NEXT:    [[TMP5:%.*]] = xor i1 [[TMP4]], true
; CHECK-NEXT:    ret i1 [[TMP5]]
;
  %a = fcmp uge fp128 %x, %y
  ret i1 %a
}
