; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -bugpoint-enable-legacy-pm -S -mtriple=x86_64-unknown-unknown -float128-expand -intel-libirc-allowed | FileCheck %s

; Function Attrs: nofree noreturn nounwind uwtable
define dso_local i32 @main2(fp128 %x) local_unnamed_addr #0 {
; CHECK-LABEL: @main2(
; CHECK-NEXT:  bb1:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = alloca fp128, align 16
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP1]])
; CHECK-NEXT:    store fp128 [[X:%.*]], ptr [[TMP1]], align 16
; CHECK-NEXT:    br i1 undef, label [[BB2:%.*]], label [[BB3:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[TMP0]])
; CHECK-NEXT:    call void @__addq(ptr [[TMP0]], ptr [[TMP1]], ptr [[TMP1]])
; CHECK-NEXT:    [[TMP2:%.*]] = load fp128, ptr [[TMP0]], align 16
; CHECK-NEXT:    br label [[BB4:%.*]]
; CHECK:       bb3:
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @__eqq(ptr [[TMP1]], ptr [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i1
; CHECK-NEXT:    br label [[BB4]]
; CHECK:       bb4:
; CHECK-NEXT:    [[TMP5:%.*]] = phi fp128 [ [[X]], [[BB3]] ], [ [[TMP2]], [[BB2]] ]
; CHECK-NEXT:    ret i32 1
;
; To make the whole thing as simple as possible, we won't create LifetimeMarkers
; for fp128ptr whose value is related to PHI. Thus, although we could have created
; LifetimeEnd for TMP0 and TMP1, but we won't do that.
bb1:
  br i1 undef, label %bb2, label %bb3
bb2:
  %0 = fadd fp128 %x, %x
  br label %bb4
bb3:
  %1 = fcmp oeq fp128 %x, %x
  br label %bb4
bb4:
  %2 = phi fp128 [%x, %bb3], [%0, %bb2]
  ret i32 1
}
