; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: intel_feature_isa_avx256p
; RUN: llc < %s -mattr=+avx256p | FileCheck %s --check-prefixes=CHECK

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct = type { ptr, ptr, ptr, i64, i16, i8, i8, i32, ptr, ptr, i32, i32, ptr, ptr }

@PL_compiling = external dso_local global %struct, align 8

; Function Attrs: nocallback nofree nounwind willreturn memory(argmem: readwrite)
declare void @llvm.memcpy.p0.p0.i64(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i64, i1 immarg) #0

define dso_local fastcc void @S_fold_constants() unnamed_addr  {                                  ; preds = %entry
; CHECK-LABEL: S_fold_constants:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovups PL_compiling+48(%rip), %ymm0
; CHECK-NEXT:    vmovups %ymm0, (%rax)
; CHECK-NEXT:    vmovups PL_compiling+32(%rip), %ymm0
; CHECK-NEXT:    vmovups %ymm0, (%rax)
; CHECK-NEXT:    vmovups PL_compiling(%rip), %ymm0
; CHECK-NEXT:    vmovups %ymm0, (%rax)
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(80) poison, ptr noundef nonnull align 8 dereferenceable(80) @PL_compiling, i64 80, i1 false)
  ret void
}

attributes #0 = { nocallback nofree nounwind willreturn memory(argmem: readwrite) }

