; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: intel_feature_isa_avx256p
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu common-avx256 | FileCheck %s
; Testing instructions came solely from FeatureAVX512 (without any additional extensions).

define void @truncated_load_v16i16(ptr %src, ptr %dst) {
; CHECK-LABEL: truncated_load_v16i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovdqa (%rdi), %ymm0
; CHECK-NEXT:    vpmovwb %ymm0, %xmm0
; CHECK-NEXT:    vpshufd {{.*#+}} xmm1 = xmm0[2,3,2,3]
; CHECK-NEXT:    vpmovsxbd %xmm1, %ymm1
; CHECK-NEXT:    vpmovsxbd %xmm0, %ymm0
; CHECK-NEXT:    vmovdqa %ymm0, (%rsi)
; CHECK-NEXT:    vmovdqa %ymm1, 32(%rsi)
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %1 = load <32 x i8>, ptr %src
  %2 = shufflevector <32 x i8> %1, <32 x i8> poison, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
  %3 = sext <16 x i8> %2 to <16 x i32>
  store <16 x i32> %3, ptr %dst
  ret void
}
