; RUN: SATest -BUILD --config=%s.cfg -tsize=0 -llvm-option=-print-before=sycl-kernel-analysis 2>&1 | FileCheck %s

; CHECK: call {{.*}}@_Z11atomic_initP{{.*}}VU7_Atomicii
; CHECK: call {{.*}}@_Z11atomic_initP{{.*}}VU7_Atomicjj
; CHECK: call {{.*}}@_Z11atomic_initP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z11atomic_initP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z11atomic_initP{{.*}}VU7_Atomicff
; CHECK: call {{.*}}@_Z11atomic_initP{{.*}}VU7_Atomicdd
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storeP{{.*}}VU7_Atomicii
; CHECK: call {{.*}}@_Z21atomic_store_explicitP{{.*}}VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitP{{.*}}VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storeP{{.*}}VU7_Atomicjj
; CHECK: call {{.*}}@_Z21atomic_store_explicitP{{.*}}VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitP{{.*}}VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storeP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z21atomic_store_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storeP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z21atomic_store_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storeP{{.*}}VU7_Atomicff
; CHECK: call {{.*}}@_Z21atomic_store_explicitP{{.*}}VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitP{{.*}}VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z12atomic_storeP{{.*}}VU7_Atomicdd
; CHECK: call {{.*}}@_Z21atomic_store_explicitP{{.*}}VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z21atomic_store_explicitP{{.*}}VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadP{{.*}}VU7_Atomici
; CHECK: call {{.*}}@_Z20atomic_load_explicitP{{.*}}VU7_Atomici12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitP{{.*}}VU7_Atomici12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadP{{.*}}VU7_Atomicj
; CHECK: call {{.*}}@_Z20atomic_load_explicitP{{.*}}VU7_Atomicj12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitP{{.*}}VU7_Atomicj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadP{{.*}}VU7_Atomicl
; CHECK: call {{.*}}@_Z20atomic_load_explicitP{{.*}}VU7_Atomicl12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitP{{.*}}VU7_Atomicl12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadP{{.*}}VU7_Atomicm
; CHECK: call {{.*}}@_Z20atomic_load_explicitP{{.*}}VU7_Atomicm12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitP{{.*}}VU7_Atomicm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadP{{.*}}VU7_Atomicf
; CHECK: call {{.*}}@_Z20atomic_load_explicitP{{.*}}VU7_Atomicf12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitP{{.*}}VU7_Atomicf12memory_order12memory_scope
; CHECK: call {{.*}}@_Z11atomic_loadP{{.*}}VU7_Atomicd
; CHECK: call {{.*}}@_Z20atomic_load_explicitP{{.*}}VU7_Atomicd12memory_order
; CHECK: call {{.*}}@_Z20atomic_load_explicitP{{.*}}VU7_Atomicd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangeP{{.*}}VU7_Atomicii
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitP{{.*}}VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitP{{.*}}VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangeP{{.*}}VU7_Atomicjj
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitP{{.*}}VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitP{{.*}}VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangeP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangeP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangeP{{.*}}VU7_Atomicff
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitP{{.*}}VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitP{{.*}}VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_exchangeP{{.*}}VU7_Atomicdd
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitP{{.*}}VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z24atomic_exchange_explicitP{{.*}}VU7_Atomicdd12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addP{{.*}}VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addP{{.*}}VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope

; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicdd12memory_order12memory_scope

; Generic address space will be translated to global address space
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicdd12memory_order12memory_scope

; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicdd12memory_order12memory_scope

; CHECK: call {{.*}}@_Z16atomic_fetch_subP{{.*}}VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitP{{.*}}VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitP{{.*}}VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_subP{{.*}}VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitP{{.*}}VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitP{{.*}}VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_subP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_subP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orP{{.*}}VU7_Atomicii
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitP{{.*}}VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitP{{.*}}VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orP{{.*}}VU7_Atomicjj
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitP{{.*}}VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitP{{.*}}VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorP{{.*}}VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitP{{.*}}VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitP{{.*}}VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorP{{.*}}VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitP{{.*}}VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitP{{.*}}VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andP{{.*}}VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitP{{.*}}VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitP{{.*}}VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andP{{.*}}VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitP{{.*}}VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitP{{.*}}VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minP{{.*}}VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minP{{.*}}VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope

; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicdd12memory_order12memory_scope

; Generic address space will be translated to global address space
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicdd12memory_order12memory_scope

; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicdd12memory_order12memory_scope


; CHECK: call {{.*}}@_Z16atomic_fetch_maxP{{.*}}VU7_Atomicii
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicii12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicii12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxP{{.*}}VU7_Atomicjj
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicjj12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicjj12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_addP{{.*}}VU7_Atomicml
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicml12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_add_explicitP{{.*}}VU7_Atomicml12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_subP{{.*}}VU7_Atomicml
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitP{{.*}}VU7_Atomicml12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_sub_explicitP{{.*}}VU7_Atomicml12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z15atomic_fetch_orP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z24atomic_fetch_or_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_andP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_and_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_maxP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope

; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicdd12memory_order12memory_scope

; Generic address space will be translated to global address space
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicdd12memory_order12memory_scope

; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicff12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicff12memory_order12memory_scope
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicdd12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_max_explicitP{{.*}}VU7_Atomicdd12memory_order12memory_scope


; CHECK: call {{.*}}@_Z16atomic_fetch_minP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_minP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_min_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorP{{.*}}VU7_Atomicll
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitP{{.*}}VU7_Atomicll12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitP{{.*}}VU7_Atomicll12memory_order12memory_scope
; CHECK: call {{.*}}@_Z16atomic_fetch_xorP{{.*}}VU7_Atomicmm
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitP{{.*}}VU7_Atomicmm12memory_order
; CHECK: call {{.*}}@_Z25atomic_fetch_xor_explicitP{{.*}}VU7_Atomicmm12memory_order12memory_scope
; CHECK: call {{.*}}@_Z24atomic_flag_test_and_setP{{.*}}VU7_Atomici
; CHECK: call {{.*}}@_Z33atomic_flag_test_and_set_explicitP{{.*}}VU7_Atomici12memory_order
; CHECK: call {{.*}}@_Z33atomic_flag_test_and_set_explicitP{{.*}}VU7_Atomici12memory_order12memory_scope
; CHECK: call {{.*}}@_Z17atomic_flag_clearP{{.*}}VU7_Atomici
; CHECK: call {{.*}}@_Z26atomic_flag_clear_explicitP{{.*}}VU7_Atomici12memory_order
; CHECK: call {{.*}}@_Z26atomic_flag_clear_explicitP{{.*}}VU7_Atomici12memory_order12memory_scope

; CHECK: Test program was successfully built.
