; Check that v32 and v64(expand from v32) builtins are used.

; RUN: SATest -BUILD --config=%s.cfg -tsize=32 -cpuarch=skx -llvm-option=-print-after=dpcpp-kernel-relaxed-math 2>&1 | FileCheck %s -check-prefix=CHECK32
; RUN: SATest -BUILD --config=%s.cfg -tsize=64 -cpuarch=skx -llvm-option=-print-after=dpcpp-kernel-relaxed-math 2>&1 | FileCheck %s -check-prefix=CHECK64
; RUN: SATest -BUILD --config=%s.cfg -tsize=32 -cpuarch=skx --dump-llvm-file - | FileCheck %s -check-prefix=CHECK32-SVML
; RUN: SATest -BUILD --config=%s.cfg -tsize=64 -cpuarch=skx --dump-llvm-file - | FileCheck %s -check-prefix=CHECK64-SVML

; RUN: SATest -BUILD --config=%s.cfg -tsize=32 -cpuarch=core-avx2 -llvm-option=-print-after=dpcpp-kernel-relaxed-math 2>&1 | FileCheck %s -check-prefix=CHECK32
; RUN: SATest -BUILD --config=%s.cfg -tsize=64 -cpuarch=core-avx2 -llvm-option=-print-after=dpcpp-kernel-relaxed-math 2>&1 | FileCheck %s -check-prefix=CHECK64

; CHECK32: call{{.*}} <32 x float> @_Z6cos_rmDv32_f(<32 x float> {{.*}})
; CHECK32: call{{.*}} <32 x float> @_Z6exp_rmDv32_f(<32 x float> {{.*}})
; CHECK32: call{{.*}} <32 x float> @_Z7exp2_rmDv32_f(<32 x float> {{.*}})
; CHECK32: call{{.*}} <32 x float> @_Z8exp10_rmDv32_f(<32 x float> {{.*}})
; CHECK32: call{{.*}} <32 x float> @_Z6log_rmDv32_f(<32 x float> {{.*}})
; CHECK32: call{{.*}} <32 x float> @_Z7log2_rmDv32_f(<32 x float> {{.*}})
; CHECK32: call{{.*}} <32 x float> @_Z6pow_rmDv32_fS_(<32 x float> {{.*}})
; CHECK32: call{{.*}} <32 x float> @_Z6sin_rmDv32_f(<32 x float> {{.*}})
; CHECK32: call{{.*}} <32 x float> @_Z6tan_rmDv32_f(<32 x float> {{.*}})
; CHECK32: call{{.*}} <32 x float> @_Z9sincos_rmDv32_fPf(<32 x float> {{.*}}, float* {{.*}})
; CHECK32: call{{.*}} float @_Z6cos_rmf(float {{.*}})
; CHECK32: call{{.*}} float @_Z6exp_rmf(float {{.*}})
; CHECK32: call{{.*}} float @_Z7exp2_rmf(float {{.*}})
; CHECK32: call{{.*}} float @_Z8exp10_rmf(float {{.*}})
; CHECK32: call{{.*}} float @_Z6log_rmf(float {{.*}})
; CHECK32: call{{.*}} float @_Z7log2_rmf(float {{.*}})
; CHECK32: call{{.*}} float @_Z6pow_rmff(float {{.*}}, float {{.*}})
; CHECK32: call{{.*}} float @_Z6sin_rmf(float {{.*}})
; CHECK32: call{{.*}} float @_Z6tan_rmf(float {{.*}})
; CHECK32: call{{.*}} float @_Z9sincos_rmfPf(float {{.*}}, float* {{.*}})

; CHECK64: call{{.*}} <64 x float> @_Z6cos_rmDv64_f(<64 x float> {{.*}})
; CHECK64: call{{.*}} <64 x float> @_Z6exp_rmDv64_f(<64 x float> {{.*}})
; CHECK64: call{{.*}} <64 x float> @_Z7exp2_rmDv64_f(<64 x float> {{.*}})
; CHECK64: call{{.*}} <64 x float> @_Z8exp10_rmDv64_f(<64 x float> {{.*}})
; CHECK64: call{{.*}} <64 x float> @_Z6log_rmDv64_f(<64 x float> {{.*}})
; CHECK64: call{{.*}} <64 x float> @_Z7log2_rmDv64_f(<64 x float> {{.*}})
; CHECK64: call{{.*}} <64 x float> @_Z6pow_rmDv64_fS_(<64 x float> {{.*}}, <64 x float> {{.*}})
; CHECK64: call{{.*}} <64 x float> @_Z6sin_rmDv64_f(<64 x float> {{.*}})
; CHECK64: call{{.*}} <64 x float> @_Z6tan_rmDv64_f(<64 x float> {{.*}})
; CHECK64: call{{.*}} <64 x float> @_Z9sincos_rmDv64_fPf(<64 x float> {{.*}}, float* {{.*}})
; CHECK64: call{{.*}} float @_Z6cos_rmf(float {{.*}})
; CHECK64: call{{.*}} float @_Z6exp_rmf(float {{.*}})
; CHECK64: call{{.*}} float @_Z7exp2_rmf(float {{.*}})
; CHECK64: call{{.*}} float @_Z8exp10_rmf(float {{.*}})
; CHECK64: call{{.*}} float @_Z6log_rmf(float {{.*}})
; CHECK64: call{{.*}} float @_Z7log2_rmf(float {{.*}})
; CHECK64: call{{.*}} float @_Z6pow_rmff(float {{.*}}, float {{.*}})
; CHECK64: call{{.*}} float @_Z6sin_rmf(float {{.*}})
; CHECK64: call{{.*}} float @_Z6tan_rmf(float {{.*}})
; CHECK64: call{{.*}} float @_Z9sincos_rmfPf(float {{.*}}, float* {{.*}})

; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_cosf32_rm(<32 x float> {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_expf32_rm(<32 x float> {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_exp2f32_rm(<32 x float> {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_exp10f32_rm(<32 x float> {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_logf32_rm(<32 x float> {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_log2f32_rm(<32 x float> {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_powf32_rm(<32 x float> {{.*}}, <32 x float> {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_sinf32_rm(<32 x float> {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_tanf32_rm(<32 x float> {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_sincosf32_rm(<32 x float> {{.*}}, <32 x float> {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_cosf1_rm(float {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_expf1_rm(float {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_exp2f1_rm(float {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_exp10f1_rm(float {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_logf1_rm(float {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_log2f1_rm(float {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_powf1_rm(float {{.*}}, float {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_sinf1_rm(float {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_tanf1_rm(float {{.*}})
; CHECK32-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_sincosf1_rm(float {{.*}}, float {{.*}})

; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_cosf32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_cosf32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_expf32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_expf32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_exp2f32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_exp2f32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_exp10f32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_exp10f32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_logf32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_logf32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_log2f32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_log2f32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_powf32_rm(<32 x float> {{.*}}, <32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_powf32_rm(<32 x float> {{.*}}, <32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_sinf32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_sinf32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_tanf32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_tanf32_rm(<32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_sincosf32_rm(<32 x float> {{.*}}, <32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 <32 x float> @__ocl_svml_z0_sincosf32_rm(<32 x float> {{.*}}, <32 x float> {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_cosf1_rm(float {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_expf1_rm(float {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_exp2f1_rm(float {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_exp10f1_rm(float {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_logf1_rm(float {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_log2f1_rm(float {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_powf1_rm(float {{.*}}, float {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_sinf1_rm(float {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_tanf1_rm(float {{.*}})
; CHECK64-SVML: call{{.*}} intel_ocl_bicc_avx512 float @__ocl_svml_z0_sincosf1_rm(float {{.*}}, float {{.*}})
