; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; Test to check vectorizer CG support for a loop with debug information. Debug intrinsic calls
; inside the loop are ignored by CG.

; RUN: opt -passes=vplan-vec -S < %s | FileCheck %s

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@.str = private unnamed_addr constant [8 x i8] c"x = %f\0A\00", align 1

; Function Attrs: nounwind uwtable
define float @foo(ptr nocapture %a) #0 {
; CHECK-LABEL: @foo(
; CHECK:       vector.body:
; CHECK-NEXT:    [[UNI_PHI1:%.*]] = phi i64 [ 0, [[VECTOR_PH:%.*]] ], [ [[TMP7:%.*]], [[VECTOR_BODY:%.*]] ], !dbg [[DBG24:![0-9]+]]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i64> [ <i64 0, i64 1, i64 2, i64 3>, [[VECTOR_PH]] ], [ [[TMP6:%.*]], [[VECTOR_BODY]] ], !dbg [[DBG24]]
; CHECK-NEXT:    [[VEC_PHI3:%.*]] = phi <4 x float> [ <float -0.000000e+00, float -0.000000e+00, float -0.000000e+00, float -0.000000e+00>, [[VECTOR_PH]] ], [ [[TMP5:%.*]], [[VECTOR_BODY]] ], !dbg [[DBG31:![0-9]+]]
; CHECK-NEXT:    [[TMP0:%.*]] = trunc <4 x i64> [[VEC_PHI]] to <4 x i32>, !dbg [[DBG27:![0-9]+]]
; CHECK-NEXT:    [[TMP1:%.*]] = sitofp <4 x i32> [[TMP0]] to <4 x double>, !dbg [[DBG27]]
; CHECK-NEXT:    [[TMP2:%.*]] = fmul <4 x double> [[TMP1]], <double 1.800000e+00, double 1.800000e+00, double 1.800000e+00, double 1.800000e+00>, !dbg [[DBG28:![0-9]+]]
; CHECK-NEXT:    [[TMP3:%.*]] = fptrunc <4 x double> [[TMP2]] to <4 x float>, !dbg [[DBG27]]
; CHECK-NEXT:    [[SCALAR_GEP:%.*]] = getelementptr inbounds float, ptr [[A:%.*]], i64 [[UNI_PHI1]], !dbg [[DBG29:![0-9]+]]
; CHECK-NEXT:    store <4 x float> [[TMP3]], ptr [[SCALAR_GEP]], align 4, !dbg [[DBG30:![0-9]+]]
; CHECK-NEXT:    [[TMP5]] = fadd <4 x float> [[TMP3]], [[VEC_PHI3]], !dbg [[DBG31]]
; CHECK-NEXT:    [[TMP6]] = add nuw nsw <4 x i64> [[VEC_PHI]], <i64 4, i64 4, i64 4, i64 4>, !dbg [[DBG23:![0-9]+]]
; CHECK-NEXT:    [[TMP7]] = add nuw nsw i64 [[UNI_PHI1]], 4, !dbg [[DBG23]]
; CHECK-NEXT:    [[TMP8:%.*]] = icmp uge i64 [[TMP7]], 1000, !dbg [[DBG23]]
; CHECK-NEXT:    br i1 [[TMP8]], label [[VPLANNEDBB4:%.*]], label [[VECTOR_BODY]], !dbg [[DBG23]], !llvm.loop [[LOOP32:![0-9]+]]
;
entry:
  %x = alloca float, align 4
  tail call void @llvm.dbg.value(metadata ptr %a, i64 0, metadata !13, metadata !14), !dbg !15
  tail call void @llvm.dbg.value(metadata float 0.000000e+00, i64 0, metadata !16, metadata !14), !dbg !17
  store float 0.000000e+00, ptr %x, align 4, !dbg !17
  br label %entry.split

entry.split:
  %tok =  call token @llvm.directive.region.entry() [ "DIR.OMP.SIMD"(), "QUAL.OMP.REDUCTION.ADD:TYPED"(ptr %x, float zeroinitializer, i32 1) ], !dbg !18
  br label %DIR.QUAL.LIST.END.2

DIR.QUAL.LIST.END.2:
  call void @llvm.dbg.value(metadata i32 0, i64 0, metadata !19, metadata !14), !dbg !21
  %x.promoted = load float, ptr %x, align 4, !dbg !22
  br label %for.body, !dbg !26

for.body:                                         ; preds = %for.body, %DIR.QUAL.LIST.END.2
  %indvars.iv = phi i64 [ 0, %DIR.QUAL.LIST.END.2 ], [ %indvars.iv.next, %for.body ], !dbg !27
  %add7 = phi float [ %x.promoted, %DIR.QUAL.LIST.END.2 ], [ %add, %for.body ], !dbg !27
  %0 = trunc i64 %indvars.iv to i32, !dbg !30
  %conv2 = sitofp i32 %0 to double, !dbg !30
  %mul = fmul double %conv2, 1.800000e+00, !dbg !31
  %conv3 = fptrunc double %mul to float, !dbg !30
  %arrayidx = getelementptr inbounds float, ptr %a, i64 %indvars.iv, !dbg !32
  store float %conv3, ptr %arrayidx, align 4, !dbg !33
  call void @llvm.dbg.value(metadata ptr %x, i64 0, metadata !16, metadata !14), !dbg !17
  %add = fadd float %conv3, %add7, !dbg !34
  call void @llvm.dbg.value(metadata float %add, i64 0, metadata !16, metadata !14), !dbg !17
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1, !dbg !26
  %exitcond = icmp eq i64 %indvars.iv.next, 1000, !dbg !26
  br i1 %exitcond, label %for.end, label %for.body, !dbg !26

for.end:                                          ; preds = %for.body
  %add.lcssa = phi float [ %add, %for.body ], !dbg !34
  store float %add.lcssa, ptr %x, align 4, !dbg !22
  br label %DIR.OMP.END.SIMD.2

DIR.OMP.END.SIMD.2:
  call void @llvm.directive.region.exit(token %tok) [ "DIR.OMP.END.SIMD"() ]
  br label %DIR.QUAL.LIST.END.3

DIR.QUAL.LIST.END.3:
  call void @llvm.dbg.value(metadata ptr %x, i64 0, metadata !16, metadata !14), !dbg !17
  %conv6 = fpext float %add.lcssa to double, !dbg !36
  %call = call i32 (ptr, ...) @printf(ptr nonnull @.str, double %conv6) #4, !dbg !37
  call void @llvm.dbg.value(metadata ptr %x, i64 0, metadata !16, metadata !14), !dbg !17
  %1 = load float, ptr %x, align 4, !dbg !38
  ret float %1, !dbg !39
}

; Function Attrs: nounwind
declare token @llvm.directive.region.entry() #4

; Function Attrs: nounwind
declare void @llvm.directive.region.exit(token) #4

; Function Attrs: nounwind
declare i32 @printf(ptr nocapture readonly, ...) #2

; Function Attrs: nounwind readnone
declare void @llvm.dbg.value(metadata, i64, metadata, metadata) #3

attributes #0 = { nounwind uwtable "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { nounwind argmemonly }
attributes #2 = { nounwind "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #3 = { nounwind readnone }
attributes #4 = { nounwind }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!9, !10}
!llvm.dbg.intel.emit_class_debug_always = !{!11}
!llvm.ident = !{!12}

!0 = distinct !DICompileUnit(language: DW_LANG_C89, file: !1, producer: "clang version 3.8.0 (branches/vpo 1936)", isOptimized: false, runtimeVersion: 0, emissionKind: 1, enums: !2)
!1 = !DIFile(filename: "simdloop.c", directory: "/export/iusers/xtian/llvm_temp")
!2 = !{}
!3 = !{!4}
!4 = distinct !DISubprogram(unit: !0, name: "foo", scope: !1, file: !1, line: 2, type: !5, isLocal: false, isDefinition: true, scopeLine: 3, flags: DIFlagPrototyped, isOptimized: false)
!5 = !DISubroutineType(types: !6)
!6 = !{!7, !8}
!7 = !DIBasicType(name: "float", size: 32, align: 32, encoding: DW_ATE_float)
!8 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7, size: 64, align: 64)
!9 = !{i32 2, !"Dwarf Version", i32 4}
!10 = !{i32 2, !"Debug Info Version", i32 3}
!11 = !{!"true"}
!12 = !{!"clang version 3.8.0 (branches/vpo 1936)"}
!13 = !DILocalVariable(name: "a", arg: 1, scope: !4, file: !1, line: 2, type: !8)
!14 = !DIExpression()
!15 = !DILocation(line: 2, column: 18, scope: !4)
!16 = !DILocalVariable(name: "x", scope: !4, file: !1, line: 5, type: !7)
!17 = !DILocation(line: 5, column: 9, scope: !4)
!18 = !DILocation(line: 7, column: 9, scope: !4)
!19 = !DILocalVariable(name: "k", scope: !4, file: !1, line: 4, type: !20)
!20 = !DIBasicType(name: "int", size: 32, align: 32, encoding: DW_ATE_signed)
!21 = !DILocation(line: 4, column: 9, scope: !4)
!22 = !DILocation(line: 10, column: 7, scope: !23)
!23 = distinct !DILexicalBlock(scope: !24, file: !1, line: 8, column: 28)
!24 = distinct !DILexicalBlock(scope: !25, file: !1, line: 8, column: 3)
!25 = distinct !DILexicalBlock(scope: !4, file: !1, line: 8, column: 3)
!26 = !DILocation(line: 8, column: 3, scope: !25)
!27 = !DILocation(line: 8, column: 13, scope: !28)
!28 = !DILexicalBlockFile(scope: !29, file: !1, discriminator: 2)
!29 = !DILexicalBlockFile(scope: !24, file: !1, discriminator: 1)
!30 = !DILocation(line: 9, column: 13, scope: !23)
!31 = !DILocation(line: 9, column: 15, scope: !23)
!32 = !DILocation(line: 9, column: 5, scope: !23)
!33 = !DILocation(line: 9, column: 11, scope: !23)
!34 = !DILocation(line: 10, column: 11, scope: !23)
!35 = !DILocation(line: 11, column: 3, scope: !25)
!36 = !DILocation(line: 12, column: 21, scope: !4)
!37 = !DILocation(line: 12, column: 2, scope: !4)
!38 = !DILocation(line: 13, column: 9, scope: !4)
!39 = !DILocation(line: 13, column: 2, scope: !4)

