; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -VPlanDriver -S -enable-vp-value-codegen=false %s | FileCheck %s --check-prefix=CHECK-LLVM

; CHECK-LLVM-LABEL: @reduction_min(
; CHECK-LLVM:       entry:
; CHECK-LLVM:         [[MIN_VEC:%.*]] = alloca <8 x i32>, align 4
; CHECK-LLVM:       vector.ph:
; CHECK-LLVM-NEXT:    [[MININITVAL:%.*]] = load i32, i32* [[MIN:%.*]]
; CHECK-LLVM-NEXT:    [[MININITVALINITVEC_SPLATINSERT:%.*]] = insertelement <8 x i32> undef, i32 [[MININITVAL]], i32 0
; CHECK-LLVM-NEXT:    [[MININITVALINITVEC_SPLAT:%.*]] = shufflevector <8 x i32> [[MININITVALINITVEC_SPLATINSERT]], <8 x i32> undef, <8 x i32> zeroinitializer
; CHECK-LLVM-NEXT:    store <8 x i32> [[MININITVALINITVEC_SPLAT]], <8 x i32>* [[MIN_VEC]]
; CHECK-LLVM-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK-LLVM:       vector.body:
; CHECK-LLVM:         [[SCALAR_GEP_:%.*]] = getelementptr inbounds [19 x i32], [19 x i32]* [[A:%.*]], i64 0, i64 [[INDEX:%.*]]
; CHECK-LLVM-NEXT:    [[TMP3:%.*]] = bitcast i32* [[SCALAR_GEP_]] to <8 x i32>*
; CHECK-LLVM-NEXT:    [[WIDE_LOAD:%.*]] = load <8 x i32>, <8 x i32>* [[TMP3]], align 4
; CHECK-LLVM-NEXT:    [[WIDE_LOAD1:%.*]] = load <8 x i32>, <8 x i32>* [[MIN_VEC]], align 4
; CHECK-LLVM-NEXT:    [[TMP4:%.*]] = icmp slt <8 x i32> [[WIDE_LOAD]], [[WIDE_LOAD1]]
; CHECK-LLVM-NEXT:    call void @llvm.masked.store.v8i32.p0v8i32(<8 x i32> [[WIDE_LOAD]], <8 x i32>* [[MIN_VEC]], i32 4, <8 x i1> [[TMP4]])
; CHECK-LLVM:       VPlannedBB:
; CHECK-LLVM-NEXT:    br label [[MIDDLE_BLOCK:%.*]]
; CHECK-LLVM:       middle.block:
; CHECK-LLVM-NEXT:    [[RED_VEC:%.*]] = load <8 x i32>, <8 x i32>* [[MIN_VEC]]
; CHECK-LLVM-NEXT:    [[RDX_SHUF:%.*]] = shufflevector <8 x i32> [[RED_VEC]], <8 x i32> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 undef, i32 undef, i32 undef, i32 undef>
; CHECK-LLVM-NEXT:    [[RDX_MINMAX_CMP:%.*]] = icmp slt <8 x i32> [[RED_VEC]], [[RDX_SHUF]]
; CHECK-LLVM-NEXT:    [[RDX_MINMAX_SELECT:%.*]] = select <8 x i1> [[RDX_MINMAX_CMP]], <8 x i32> [[RED_VEC]], <8 x i32> [[RDX_SHUF]]
; CHECK-LLVM-NEXT:    [[RDX_SHUF2:%.*]] = shufflevector <8 x i32> [[RDX_MINMAX_SELECT]], <8 x i32> undef, <8 x i32> <i32 2, i32 3, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
; CHECK-LLVM-NEXT:    [[RDX_MINMAX_CMP3:%.*]] = icmp slt <8 x i32> [[RDX_MINMAX_SELECT]], [[RDX_SHUF2]]
; CHECK-LLVM-NEXT:    [[RDX_MINMAX_SELECT4:%.*]] = select <8 x i1> [[RDX_MINMAX_CMP3]], <8 x i32> [[RDX_MINMAX_SELECT]], <8 x i32> [[RDX_SHUF2]]
; CHECK-LLVM-NEXT:    [[RDX_SHUF5:%.*]] = shufflevector <8 x i32> [[RDX_MINMAX_SELECT4]], <8 x i32> undef, <8 x i32> <i32 1, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
; CHECK-LLVM-NEXT:    [[RDX_MINMAX_CMP6:%.*]] = icmp slt <8 x i32> [[RDX_MINMAX_SELECT4]], [[RDX_SHUF5]]
; CHECK-LLVM-NEXT:    [[RDX_MINMAX_SELECT7:%.*]] = select <8 x i1> [[RDX_MINMAX_CMP6]], <8 x i32> [[RDX_MINMAX_SELECT4]], <8 x i32> [[RDX_SHUF5]]
; CHECK-LLVM-NEXT:    [[TMP9:%.*]] = extractelement <8 x i32> [[RDX_MINMAX_SELECT7]], i32 0
; CHECK-LLVM-NEXT:    store i32 [[TMP9]], i32* [[MIN]]


target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"
@.str = private unnamed_addr addrspace(2) constant [10 x i8] c"Min = %d\0A\00", align 1

define void @reduction_min(i32 %thread_id_from_which_to_print_message) #0 {
entry:
  %A = alloca [19 x i32], align 4
  %Min = alloca i32, align 4
  %call = tail call i64 @_Z13get_global_idj(i32 0) #5
  %conv = trunc i64 %call to i32
  %cmp = icmp eq i32 %conv, %thread_id_from_which_to_print_message
  br i1 %cmp, label %for.body.preheader, label %if.end18

for.body.preheader:                               ; preds = %entry
  br label %for.body

for.body:                                         ; preds = %for.body.preheader, %for.body
  %indvars.iv4 = phi i64 [ 0, %for.body.preheader ], [ %indvars.iv.next5, %for.body ]
  %i.03 = phi i32 [ %add, %for.body ], [ 0, %for.body.preheader ]
  %0 = trunc i64 %indvars.iv4 to i32
  %rem1 = and i32 %0, 1
  %tobool = icmp ne i32 %rem1, 0
  %indvars.iv.next5 = add nuw nsw i64 %indvars.iv4, 1
  %add = add nuw nsw i32 %i.03, 1
  %1 = sub nsw i64 9, %indvars.iv4
  %2 = trunc i64 %1 to i32
  %cond = select i1 %tobool, i32 %add, i32 %2
  %arrayidx = getelementptr inbounds [19 x i32], [19 x i32]* %A, i64 0, i64 %indvars.iv4
  store i32 %cond, i32* %arrayidx, align 4
  %exitcond7 = icmp ne i64 %indvars.iv.next5, 19
  br i1 %exitcond7, label %for.body, label %DIR.OMP.SIMD.2

DIR.OMP.SIMD.2:                                   ; preds = %for.body
  store i32 0, i32* %Min, align 4
  br label %DIR.OMP.SIMD.28

DIR.OMP.SIMD.28:                                  ; preds = %DIR.OMP.SIMD.2
  %tok = call token @llvm.directive.region.entry() [ "DIR.OMP.SIMD"(), "QUAL.OMP.SIMDLEN"(i32 8), "QUAL.OMP.REDUCTION.MIN"(i32* %Min) ]
  br label %omp.inner.for.body

omp.inner.for.body:                               ; preds = %DIR.OMP.SIMD.28, %omp.inner.for.inc
  %indvars.iv = phi i64 [ 0, %DIR.OMP.SIMD.28 ], [ %indvars.iv.next, %omp.inner.for.inc ]
  %arrayidx10 = getelementptr inbounds [19 x i32], [19 x i32]* %A, i64 0, i64 %indvars.iv
  %3 = load i32, i32* %arrayidx10, align 4
  %4 = load i32, i32* %Min, align 4
  %cmp11 = icmp slt i32 %3, %4
  br i1 %cmp11, label %if.then13, label %omp.inner.for.inc

if.then13:                                        ; preds = %omp.inner.for.body
  store i32 %3, i32* %Min, align 4
  br label %omp.inner.for.inc

omp.inner.for.inc:                                ; preds = %if.then13, %omp.inner.for.body
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond = icmp ne i64 %indvars.iv.next, 19
  br i1 %exitcond, label %omp.inner.for.body, label %omp.loop.exit

omp.loop.exit:                                    ; preds = %omp.inner.for.inc
  call void @llvm.directive.region.exit(token %tok) [ "DIR.OMP.END.SIMD"() ]
  br label %DIR.QUAL.LIST.END.1

DIR.QUAL.LIST.END.1:                              ; preds = %omp.loop.exit
  %5 = load i32, i32* %Min, align 4
  %call17 = call i32 (i8 addrspace(2)*, ...) @printf(i8 addrspace(2)* nonnull getelementptr inbounds ([10 x i8], [10 x i8] addrspace(2)* @.str, i64 0, i64 0), i32 %5) #2
  br label %if.end18

if.end18:                                         ; preds = %DIR.QUAL.LIST.END.1, %entry
  ret void
}

; Function Attrs: argmemonly nounwind
declare token @llvm.directive.region.entry() #1

; Function Attrs: argmemonly nounwind
declare void @llvm.directive.region.exit(token) #1

; Function Attrs: nounwind
declare i32 @printf(i8 addrspace(2)*, ...)
declare i64 @_Z13get_global_idj(i32)


