; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes="vplan-vec" -S %s | FileCheck %s

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @foo(ptr nocapture readonly %p) {
; CHECK-LABEL: @foo(
; CHECK:       vector.body:
; CHECK-NEXT:    [[UNI_PHI1:%.*]] = phi i64 [ 0, [[VECTOR_PH:%.*]] ], [ [[TMP6:%.*]], [[VECTOR_BODY:%.*]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i64> [ <i64 0, i64 1, i64 2, i64 3>, [[VECTOR_PH]] ], [ [[TMP5:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[SCALAR_GEP:%.*]] = getelementptr inbounds <2 x float>, ptr [[P:%.*]], i64 [[UNI_PHI1]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <8 x float>, ptr [[SCALAR_GEP]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = fadd <8 x float> [[WIDE_LOAD]], [[WIDE_LOAD]]
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x float> [[WIDE_LOAD]], <8 x float> [[TMP1]], <12 x i32> <i32 0, i32 8, i32 9, i32 2, i32 10, i32 11, i32 4, i32 12, i32 13, i32 6, i32 14, i32 15>
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x float> [[WIDE_LOAD]], <8 x float> [[TMP1]], <12 x i32> <i32 0, i32 poison, i32 9, i32 2, i32 poison, i32 11, i32 4, i32 poison, i32 13, i32 6, i32 poison, i32 15>
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x float> [[WIDE_LOAD]], <8 x float> [[TMP1]], <12 x i32> <i32 0, i32 poison, i32 9, i32 2, i32 poison, i32 11, i32 4, i32 poison, i32 13, i32 6, i32 poison, i32 15>
; CHECK-NEXT:    [[TMP5]] = add nuw nsw <4 x i64> [[VEC_PHI]], <i64 4, i64 4, i64 4, i64 4>
; CHECK-NEXT:    [[TMP6]] = add nuw nsw i64 [[UNI_PHI1]], 4
; CHECK-NEXT:    [[TMP7:%.*]] = icmp uge i64 [[TMP6]], 1024
; CHECK-NEXT:    br i1 [[TMP7]], label [[VPLANNEDBB:%.*]], label [[VECTOR_BODY]], [[LOOP0:!llvm.loop !.*]]
;
entry:
  %entry.region = call token @llvm.directive.region.entry() [ "DIR.OMP.SIMD"(), "QUAL.OMP.SIMDLEN"(i32 4) ]
  br label %header

header:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %header ]
  %gep = getelementptr inbounds <2 x float>, ptr %p, i64 %iv
  %ld = load <2 x float>, ptr %gep
  %add = fadd <2 x float> %ld, %ld
  %shuffle = shufflevector <2 x float> %ld, <2 x float> %add, <3 x i32> <i32 0, i32 2, i32 3>
  %undef.shuffle = shufflevector <2 x float> %ld, <2 x float> %add, <3 x i32> <i32 0, i32 undef, i32 3>
  ; For some reason poison gets transformed into undef before it reaches VPlan.
  %poison.shuffle = shufflevector <2 x float> %ld, <2 x float> %add, <3 x i32> <i32 0, i32 poison, i32 3>
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond = icmp eq i64 %iv.next, 1024
  br i1 %exitcond, label %exit, label %header

exit:
  call void @llvm.directive.region.exit(token %entry.region) [ "DIR.OMP.END.SIMD"() ]
  ret void
}

declare token @llvm.directive.region.entry()
declare void @llvm.directive.region.exit(token)
