; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; ModuleID = 's4.c'
; void baz1(long);
;
; void foo() {
;   long index;
;
; #pragma omp simd simdlen(2)
;   for (index = 0; index < 1024; index++) {
;       baz1(index);
;   }
; }
; RUN: opt -passes=vplan-vec  -S %s | FileCheck %s
;
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: nounwind uwtable
define void @foo() {
; CHECK-LABEL: @foo(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[VPLANNEDBB:%.*]]
; CHECK:       VPlannedBB:
; CHECK-NEXT:    br label [[VPLANNEDBB1:%.*]]
; CHECK:       VPlannedBB1:
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[UNI_PHI:%.*]] = phi i64 [ 0, [[VPLANNEDBB1]] ], [ [[TMP1:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <2 x i64> [ <i64 0, i64 1>, [[VPLANNEDBB1]] ], [ [[TMP0:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI_EXTRACT_1_:%.*]] = extractelement <2 x i64> [[VEC_PHI]], i32 1
; CHECK-NEXT:    tail call void @baz1(i64 [[UNI_PHI]]) #[[ATTR0:[0-9]+]]
; CHECK-NEXT:    tail call void @baz1(i64 [[VEC_PHI_EXTRACT_1_]]) #[[ATTR0]]
; CHECK-NEXT:    [[TMP0]] = add nuw nsw <2 x i64> [[VEC_PHI]], <i64 2, i64 2>
; CHECK-NEXT:    [[TMP1]] = add nuw nsw i64 [[UNI_PHI]], 2
; CHECK-NEXT:    [[TMP2:%.*]] = icmp uge i64 [[TMP1]], 1024
; CHECK-NEXT:    br i1 [[TMP2]], label [[VPLANNEDBB3:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP1:![0-9]+]]
; CHECK:       VPlannedBB3:
; CHECK-NEXT:    br label [[VPLANNEDBB4:%.*]]
; CHECK:       VPlannedBB4:
; CHECK-NEXT:    br label [[FINAL_MERGE:%.*]]
; CHECK:       final.merge:
; CHECK-NEXT:    [[UNI_PHI5:%.*]] = phi i64 [ 1024, [[VPLANNEDBB4]] ]
; CHECK-NEXT:    br label [[OMP_LOOP_EXIT:%.*]]
; CHECK:       omp.inner.for.body:
; CHECK-NEXT:    [[DOTOMP_IV_06:%.*]] = phi i64 [ [[ADD1:%.*]], [[OMP_INNER_FOR_BODY:%.*]] ]
; CHECK-NEXT:    tail call void @baz1(i64 [[DOTOMP_IV_06]]) #[[ATTR0]]
; CHECK-NEXT:    [[ADD1]] = add nuw nsw i64 [[DOTOMP_IV_06]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[ADD1]], 1024
; CHECK-NEXT:    br label [[OMP_INNER_FOR_BODY]]
; CHECK:       omp.loop.exit:
; CHECK-NEXT:    ret void
;
entry:
  %tok = call token @llvm.directive.region.entry() [ "DIR.OMP.SIMD"(), "QUAL.OMP.SIMDLEN"(i32 2) ]
  br label %omp.inner.for.body

omp.inner.for.body:                               ; preds = %omp.inner.for.body, %entry
  %.omp.iv.06 = phi i64 [ 0, %entry ], [ %add1, %omp.inner.for.body ]
  tail call void @baz1(i64 %.omp.iv.06) #3
  %add1 = add nuw nsw i64 %.omp.iv.06, 1
  %exitcond = icmp eq i64 %add1, 1024
  br i1 %exitcond, label %omp.loop.exit, label %omp.inner.for.body

omp.loop.exit:                                    ; preds = %omp.inner.for.body
  call void @llvm.directive.region.exit(token %tok) [ "DIR.OMP.END.SIMD"() ]
  ret void
}

declare void @baz1(i64)

; Function Attrs: argmemonly nounwind
declare token @llvm.directive.region.entry() #2

; Function Attrs: argmemonly nounwind
declare void @llvm.directive.region.exit(token) #2

attributes #0 = { nounwind uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #2 = { argmemonly nounwind }
attributes #3 = { nounwind }

!llvm.ident = !{!0}

!0 = !{!"clang version 4.0.0 (branches/vpo 21478)"}
