; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -S -vplan-pragma-omp-ordered-simd-extract -vpo-cfg-restructuring -VPlanDriver -vplan-force-vf=2 -VPODirectiveCleanup -always-inline 2>&1 | FileCheck %s

; The Code Extractor might add the output values of the call in the entry block.
; Here, we test if the output values are treated as privates.

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @var_tripcount(i32* %ip, i32 %n, i32* %x) local_unnamed_addr {
; CHECK-LABEL: @var_tripcount(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[VAL_LOC:%.*]] = alloca i32, align 4
; CHECK-NEXT:    br label [[DIR_OMP_SIMD_1:%.*]]
; CHECK:       DIR.OMP.SIMD.1:
; CHECK-NEXT:    br label [[DIR_QUAL_LIST_END_2:%.*]]
; CHECK:       DIR.QUAL.LIST.END.2:
; CHECK-NEXT:    [[CMP5:%.*]] = icmp sgt i32 [[N:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP5]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[N]] to i64
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[WIDE_TRIP_COUNT]], 2
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], [[N_MOD_VF]]
; CHECK-NEXT:    [[CMP_ZERO:%.*]] = icmp eq i64 [[N_VEC]], 0
; CHECK-NEXT:    br i1 [[CMP_ZERO]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <2 x i32*> undef, i32* [[IP:%.*]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <2 x i32*> [[BROADCAST_SPLATINSERT]], <2 x i32*> undef, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT3:%.*]] = insertelement <2 x i32*> undef, i32* [[VAL_LOC]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT4:%.*]] = shufflevector <2 x i32*> [[BROADCAST_SPLATINSERT3]], <2 x i32*> undef, <2 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[UNI_PHI:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[TMP4:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[UNI_PHI2:%.*]] = phi i64 [ [[TMP3:%.*]], [[VECTOR_BODY]] ], [ 0, [[VECTOR_PH]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <2 x i64> [ [[TMP2:%.*]], [[VECTOR_BODY]] ], [ <i64 0, i64 1>, [[VECTOR_PH]] ]
; CHECK-NEXT:    [[MM_VECTORGEP:%.*]] = getelementptr inbounds i32, <2 x i32*> [[BROADCAST_SPLAT]], <2 x i64> [[VEC_PHI]]
; CHECK-NEXT:    [[MM_VECTORGEP_EXTRACT_1_:%.*]] = extractelement <2 x i32*> [[MM_VECTORGEP]], i32 1
; CHECK-NEXT:    [[MM_VECTORGEP_EXTRACT_0_:%.*]] = extractelement <2 x i32*> [[MM_VECTORGEP]], i32 0
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32*> [[BROADCAST_SPLAT4]] to <2 x i8*>
; CHECK-NEXT:    [[DOTEXTRACT_0_:%.*]] = extractelement <2 x i8*> [[TMP0]], i32 0
; CHECK-NEXT:    call void @llvm.lifetime.start.p0i8(i64 -1, i8* [[DOTEXTRACT_0_]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0i8(i64 -1, i8* [[DOTEXTRACT_0_]])
; CHECK-NEXT:    [[VAL_I:%.*]] = load i32, i32* [[MM_VECTORGEP_EXTRACT_0_]], align 4
; CHECK-NEXT:    store i32 [[VAL_I]], i32* [[VAL_LOC]], align 4
; CHECK-NEXT:    [[VAL_I6:%.*]] = load i32, i32* [[MM_VECTORGEP_EXTRACT_1_]], align 4
; CHECK-NEXT:    store i32 [[VAL_I6]], i32* [[VAL_LOC]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, i32* [[VAL_LOC]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.end.p0i8(i64 -1, i8* [[DOTEXTRACT_0_]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0i8(i64 -1, i8* [[DOTEXTRACT_0_]])
; CHECK-NEXT:    store i32 [[TMP1]], i32* [[MM_VECTORGEP_EXTRACT_0_]], align 4
; CHECK-NEXT:    store i32 [[TMP1]], i32* [[MM_VECTORGEP_EXTRACT_1_]], align 4
; CHECK-NEXT:    [[TMP2]] = add nuw nsw <2 x i64> [[VEC_PHI]], <i64 2, i64 2>
; CHECK-NEXT:    [[TMP3]] = add nuw nsw i64 [[UNI_PHI2]], 2
; CHECK-NEXT:    [[TMP4]] = add i64 [[UNI_PHI]], 2
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[TMP4]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP5]], label [[VPLANNEDBB:%.*]], label [[VECTOR_BODY]], [[LOOP0:!llvm.loop !.*]]
; CHECK:       VPlannedBB:
; CHECK-NEXT:    [[TMP6:%.*]] = mul i64 1, [[N_VEC]]
; CHECK-NEXT:    [[TMP7:%.*]] = add i64 0, [[TMP6]]
; CHECK-NEXT:    br label [[MIDDLE_BLOCK:%.*]]
;
entry:
  %entry.region = call token @llvm.directive.region.entry() [ "DIR.OMP.SIMD"() ]
  br label %DIR.QUAL.LIST.END.2

DIR.QUAL.LIST.END.2:
  %cmp5 = icmp sgt i32 %n, 0
  br i1 %cmp5, label %for.body.preheader, label %for.cond.cleanup

for.body.preheader:
  %wide.trip.count = zext i32 %n to i64
  br label %for.body

for.body:
  %indvars.iv = phi i64 [ %indvars.iv.next, %latch ], [ 0, %for.body.preheader ]
  %arrayidx = getelementptr inbounds i32, i32* %ip, i64 %indvars.iv
  br label %ordered.entry.1

ordered.entry.1:
  %tok.ordered.1 = call token @llvm.directive.region.entry() [ "DIR.OMP.ORDERED"(), "QUAL.OMP.ORDERED.SIMD"() ]
  br label %ordered.1

ordered.1:
  %val = load i32, i32* %arrayidx
  br label %ordered.exit.1

ordered.exit.1:
  call void @llvm.directive.region.exit(token %tok.ordered.1) [ "DIR.OMP.END.ORDERED"() ]
  br label %ordered.entry.2

ordered.entry.2:
  %tok.ordered.2 = call token @llvm.directive.region.entry() [ "DIR.OMP.ORDERED"(), "QUAL.OMP.ORDERED.SIMD"() ]
  br label %ordered.2

ordered.2:
  store i32 %val, i32* %arrayidx, align 4
  br label %ordered.exit.2

ordered.exit.2:
  call void @llvm.directive.region.exit(token %tok.ordered.2) [ "DIR.OMP.END.ORDERED"() ]
  br label %latch

latch:
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond = icmp eq i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond, label %for.end, label %for.body

for.end:
  br label %for.cond.cleanup

for.cond.cleanup:
  call void @llvm.directive.region.exit(token %entry.region) [ "DIR.OMP.END.SIMD"() ]
  br label %DIR.QUAL.LIST.END.3

DIR.QUAL.LIST.END.3:
  ret void
}

declare token @llvm.directive.region.entry() nounwind
declare void @llvm.directive.region.exit(token) nounwind
