; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; This test checks that the operands of the 'select' instructions are correctly widened.

;RUN: opt -passes="vplan-vec" -vplan-force-vf=2 -S -print-after=vplan-vec -vplan-vec-scenario="s1;v2;m2" -vplan-enable-peeling %s | FileCheck %s

; Check that peel count and checks are generated correctly for i32 loop induction variable.

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: nounwind uwtable
define dso_local float @getElement(i32 %idx) {
; CHECK-LABEL: @getElement(
; CHECK-NEXT:  omp.inner.for.body.lr.ph:
; CHECK-NEXT:    br label [[DIR_OMP_SIMD_1:%.*]]
; CHECK:       DIR.OMP.SIMD.1:
; CHECK-NEXT:    br label [[DIR_OMP_SIMD_2:%.*]]
; CHECK:       DIR.OMP.SIMD.2:
; CHECK-NEXT:    [[REM:%.*]] = and i32 [[IDX:%.*]], 3
; CHECK-NEXT:    [[REM_F:%.*]] = sitofp i32 [[REM]] to float
; CHECK-NEXT:    br label [[PEEL_CHECKZ21:%.*]]
; CHECK:       peel.checkz21:
; CHECK-NEXT:    br label [[PEEL_CHECKV22:%.*]]
; CHECK:       peel.checkv22:
; CHECK-NEXT:    br i1 false, label [[MERGE_BLK17:%.*]], label [[PEELBLK13:%.*]]
; CHECK:       PeelBlk13:
; CHECK-NEXT:    br label [[OMP_INNER_FOR_BODY:%.*]]
; CHECK:       VPlannedBB:
; CHECK-NEXT:    br label [[MERGE_BLK19:%.*]]
; CHECK:       merge.blk19:
; CHECK-NEXT:    [[UNI_PHI:%.*]] = phi float [ [[ADD2:%.*]], [[VPLANNEDBB:%.*]] ]
; CHECK-NEXT:    [[UNI_PHI1:%.*]] = phi i32 [ [[ADD3:%.*]], [[VPLANNEDBB]] ]
; CHECK-NEXT:    br label [[VPLANNEDBB2:%.*]]
; CHECK:       VPlannedBB2:
; CHECK-NEXT:    br i1 false, label [[MERGE_BLK17]], label [[VPLANNEDBB3:%.*]]
; CHECK:       VPlannedBB3:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <2 x float> poison, float [[REM_F]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <2 x float> [[BROADCAST_SPLATINSERT]], <2 x float> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VPLANNEDBB4:%.*]]
; CHECK:       VPlannedBB4:
; CHECK-NEXT:    [[UNI_PHI1IND_START_BCAST_SPLATINSERT:%.*]] = insertelement <2 x i32> poison, i32 [[UNI_PHI1]], i64 0
; CHECK-NEXT:    [[UNI_PHI1IND_START_BCAST_SPLAT:%.*]] = shufflevector <2 x i32> [[UNI_PHI1IND_START_BCAST_SPLATINSERT]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP0:%.*]] = add <2 x i32> [[UNI_PHI1IND_START_BCAST_SPLAT]], <i32 0, i32 1>
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[UNI_PHI6:%.*]] = phi i32 [ [[UNI_PHI1]], [[VPLANNEDBB4]] ], [ [[TMP3:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <2 x i32> [ [[TMP0]], [[VPLANNEDBB4]] ], [ [[TMP2:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI7:%.*]] = phi <2 x float> [ <float -0.000000e+00, float -0.000000e+00>, [[VPLANNEDBB4]] ], [ [[TMP1:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP1]] = fadd <2 x float> [[VEC_PHI7]], [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP2]] = add nuw nsw <2 x i32> [[VEC_PHI]], <i32 2, i32 2>
; CHECK-NEXT:    [[TMP3]] = add nuw nsw i32 [[UNI_PHI6]], 2
; CHECK-NEXT:    [[TMP4:%.*]] = icmp uge i32 [[TMP3]], 4095
; CHECK-NEXT:    br i1 [[TMP4]], label [[VPLANNEDBB8:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       VPlannedBB8:
; CHECK-NEXT:    [[TMP5:%.*]] = call float @llvm.vector.reduce.fadd.v2f32(float [[UNI_PHI]], <2 x float> [[TMP1]])
; CHECK-NEXT:    br label [[VPLANNEDBB9:%.*]]
; CHECK:       VPlannedBB9:
; CHECK-NEXT:    br label [[VPLANNEDBB10:%.*]]
; CHECK:       VPlannedBB10:
; CHECK-NEXT:    br i1 false, label [[FINAL_MERGE:%.*]], label [[MERGE_BLK17]]
; CHECK:       merge.blk17:
; CHECK-NEXT:    [[UNI_PHI11:%.*]] = phi float [ [[TMP5]], [[VPLANNEDBB10]] ], [ 0.000000e+00, [[PEEL_CHECKV22]] ], [ [[UNI_PHI]], [[VPLANNEDBB2]] ]
; CHECK-NEXT:    [[UNI_PHI12:%.*]] = phi i32 [ 4095, [[VPLANNEDBB10]] ], [ 0, [[PEEL_CHECKV22]] ], [ [[UNI_PHI1]], [[VPLANNEDBB2]] ]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT19:%.*]] = insertelement <2 x i32> poison, i32 [[UNI_PHI12]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT20:%.*]] = shufflevector <2 x i32> [[BROADCAST_SPLATINSERT19]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VPLANNEDBB13:%.*]]
; CHECK:       VPlannedBB13:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT24:%.*]] = insertelement <2 x float> poison, float [[REM_F]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT25:%.*]] = shufflevector <2 x float> [[BROADCAST_SPLATINSERT24]], <2 x float> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VPLANNEDBB14:%.*]]
; CHECK:       VPlannedBB14:
; CHECK-NEXT:    [[TMP6:%.*]] = sub i32 4096, [[UNI_PHI12]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT21:%.*]] = insertelement <2 x i32> poison, i32 [[TMP6]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT22:%.*]] = shufflevector <2 x i32> [[BROADCAST_SPLATINSERT21]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VPLANNEDBB15:%.*]]
; CHECK:       VPlannedBB15:
; CHECK-NEXT:    [[UNI_PHI16:%.*]] = phi i32 [ 0, [[VPLANNEDBB14]] ], [ [[TMP11:%.*]], [[NEW_LATCH:%.*]] ]
; CHECK-NEXT:    [[VEC_PHI17:%.*]] = phi <2 x i32> [ <i32 0, i32 1>, [[VPLANNEDBB14]] ], [ [[TMP10:%.*]], [[NEW_LATCH]] ]
; CHECK-NEXT:    [[VEC_PHI18:%.*]] = phi <2 x float> [ <float -0.000000e+00, float -0.000000e+00>, [[VPLANNEDBB14]] ], [ [[PREDBLEND:%.*]], [[NEW_LATCH]] ]
; CHECK-NEXT:    [[TMP7:%.*]] = add nuw nsw <2 x i32> [[VEC_PHI17]], [[BROADCAST_SPLAT20]]
; CHECK-NEXT:    [[TMP8:%.*]] = icmp ult <2 x i32> [[VEC_PHI17]], [[BROADCAST_SPLAT22]]
; CHECK-NEXT:    br label [[VPLANNEDBB23:%.*]]
; CHECK:       VPlannedBB23:
; CHECK-NEXT:    [[TMP9:%.*]] = fadd <2 x float> [[VEC_PHI18]], [[BROADCAST_SPLAT25]]
; CHECK-NEXT:    br label [[NEW_LATCH]]
; CHECK:       new_latch:
; CHECK-NEXT:    [[PREDBLEND]] = select <2 x i1> [[TMP8]], <2 x float> [[TMP9]], <2 x float> [[VEC_PHI18]]
; CHECK-NEXT:    [[TMP10]] = add nuw nsw <2 x i32> [[VEC_PHI17]], <i32 2, i32 2>
; CHECK-NEXT:    [[TMP11]] = add nuw nsw i32 [[UNI_PHI16]], 2
; CHECK-NEXT:    [[TMP12:%.*]] = icmp ult <2 x i32> [[TMP10]], [[BROADCAST_SPLAT22]]
; CHECK-NEXT:    [[TMP13:%.*]] = bitcast <2 x i1> [[TMP12]] to i2
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i2 [[TMP13]], 0
; CHECK-NEXT:    br i1 [[TMP14]], label [[VPLANNEDBB26:%.*]], label [[VPLANNEDBB15]]
; CHECK:       VPlannedBB26:
; CHECK-NEXT:    [[TMP15:%.*]] = call float @llvm.vector.reduce.fadd.v2f32(float [[UNI_PHI11]], <2 x float> [[PREDBLEND]])
; CHECK-NEXT:    br label [[VPLANNEDBB27:%.*]]
; CHECK:       VPlannedBB27:
; CHECK-NEXT:    br label [[FINAL_MERGE]]
; CHECK:       final.merge:
; CHECK-NEXT:    [[UNI_PHI28:%.*]] = phi float [ [[TMP15]], [[VPLANNEDBB27]] ], [ [[TMP5]], [[VPLANNEDBB10]] ]
; CHECK-NEXT:    [[UNI_PHI29:%.*]] = phi i32 [ 4096, [[VPLANNEDBB27]] ], [ 4095, [[VPLANNEDBB10]] ]
; CHECK-NEXT:    br label [[DIR_OMP_END_SIMD_4:%.*]]
; CHECK:       omp.inner.for.body:
; CHECK-NEXT:    [[DOTOMP_IV_LOCAL_0:%.*]] = phi i32 [ 0, [[PEELBLK13]] ], [ [[ADD3]], [[OMP_INNER_FOR_BODY]] ]
; CHECK-NEXT:    [[RETVAL_015:%.*]] = phi float [ 0.000000e+00, [[PEELBLK13]] ], [ [[ADD2]], [[OMP_INNER_FOR_BODY]] ]
; CHECK-NEXT:    [[ADD2]] = fadd float [[RETVAL_015]], [[REM_F]]
; CHECK-NEXT:    [[ADD3]] = add nuw nsw i32 [[DOTOMP_IV_LOCAL_0]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[ADD3]], 1
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[VPLANNEDBB]], label [[OMP_INNER_FOR_BODY]], !llvm.loop [[LOOP2:![0-9]+]]
; CHECK:       DIR.OMP.END.SIMD.4:
; CHECK-NEXT:    [[ADD2_LCSSA:%.*]] = phi float [ [[UNI_PHI28]], [[FINAL_MERGE]] ]
; CHECK-NEXT:    br label [[DIR_OMP_END_SIMD_3:%.*]]
; CHECK:       DIR.OMP.END.SIMD.3:
; CHECK-NEXT:    br label [[DIR_OMP_END_SIMD_419:%.*]]
; CHECK:       DIR.OMP.END.SIMD.419:
; CHECK-NEXT:    ret float [[ADD2_LCSSA]]
;
omp.inner.for.body.lr.ph:
  br label %DIR.OMP.SIMD.1

DIR.OMP.SIMD.1:                                   ; preds = %omp.inner.for.body.lr.ph
  %0 = call token @llvm.directive.region.entry() [ "DIR.OMP.SIMD"(), "QUAL.OMP.NORMALIZED.IV"(ptr null), "QUAL.OMP.NORMALIZED.UB"(ptr null) ]
  br label %DIR.OMP.SIMD.2

DIR.OMP.SIMD.2:                                   ; preds = %DIR.OMP.SIMD.1
  %rem = and i32 %idx, 3
  %rem.f = sitofp i32 %rem to float
  br label %omp.inner.for.body

omp.inner.for.body:                               ; preds = %omp.inner.for.body, %DIR.OMP.SIMD.2
  %.omp.iv.local.0 = phi i32 [ 0, %DIR.OMP.SIMD.2 ], [ %add3, %omp.inner.for.body ]
  %retVal.015 = phi float [ 0.000000e+00, %DIR.OMP.SIMD.2 ], [ %add2, %omp.inner.for.body ]
  %add2 = fadd float %retVal.015, %rem.f
  %add3 = add nuw nsw i32 %.omp.iv.local.0, 1
  %exitcond = icmp eq i32 %add3, 4096
  br i1 %exitcond, label %DIR.OMP.END.SIMD.4, label %omp.inner.for.body

DIR.OMP.END.SIMD.4:                               ; preds = %omp.inner.for.body
  %add2.lcssa = phi float [ %add2, %omp.inner.for.body ]
  br label %DIR.OMP.END.SIMD.3

DIR.OMP.END.SIMD.3:                               ; preds = %DIR.OMP.END.SIMD.4
  call void @llvm.directive.region.exit(token %0) [ "DIR.OMP.END.SIMD"() ]
  br label %DIR.OMP.END.SIMD.419

DIR.OMP.END.SIMD.419:                             ; preds = %DIR.OMP.END.SIMD.3
  ret float %add2.lcssa
}

; Function Attrs: nounwind
declare token @llvm.directive.region.entry()

; Function Attrs: nounwind
declare void @llvm.directive.region.exit(token %0)
