; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes="vplan-vec" -vplan-vec-scenario="n0;v4;m2" -S < %s 2>&1 | FileCheck %s

;; This test is meant as a baseline to demonstrate the changes that would
;; be performed by exclusive scan loop transformation. The future
;; transformation would exchange input and scan phases of inscan reduction.
;; The code generation in the test is valid only if the transformation above
;; has been performed.

;; float foo(float *A, float *B) {
;;   float x = 1.0f;
;; #pragma omp simd reduction(inscan, + : x)
;; #pragma nounroll
;;   for (int i=0; i<1024; i++) {
;;     B[i] = x;
;; #pragma omp scan exclusive(x)
;;     x += A[i];
;;   }
;;   return x;
;; }

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define float @_Z3fooPfS_(ptr %A, ptr %B) {
; CHECK-LABEL: @_Z3fooPfS_(
; CHECK-NEXT:  DIR.OMP.SIMD.1:
; CHECK-NEXT:    [[X_RED:%.*]] = alloca float, align 4
; CHECK:         store float 1.000000e+00, ptr [[X_RED]], align 4
; CHECK:         [[X_RED_VEC:%.*]] = alloca <4 x float>, align 16
; CHECK:         [[DOTVEC31:%.*]] = alloca <2 x float>, align 8
; CHECK:         br label [[DIR_OMP_SIMD_126:%.*]]
; CHECK:       VPlannedBB30:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 8, ptr [[DOTVEC_BASE_ADDR_EXTRACT_0_:%.*]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 8, ptr [[DOTVEC31_BASE_ADDR_EXTRACT_0_:%.*]])
; CHECK-NEXT:    [[TMP25:%.*]] = load float, ptr [[X_RED]], align 1
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT83:%.*]] = insertelement <2 x float> poison, float [[TMP25]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT84:%.*]] = shufflevector <2 x float> [[BROADCAST_SPLATINSERT83]], <2 x float> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP26:%.*]] = load float, ptr [[X_RED]], align 1
; CHECK-NEXT:    [[TMP27:%.*]] = load i32, ptr [[I_LINEAR_IV:%.*]], align 1
; CHECK-NEXT:    [[TMP28:%.*]] = load i32, ptr [[I_LINEAR_IV]], align 1
; CHECK-NEXT:    [[IND_START_BCAST_SPLATINSERT32:%.*]] = insertelement <2 x i32> poison, i32 [[TMP27]], i64 0
; CHECK-NEXT:    [[IND_START_BCAST_SPLAT33:%.*]] = shufflevector <2 x i32> [[IND_START_BCAST_SPLATINSERT32]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP29:%.*]] = add <2 x i32> [[IND_START_BCAST_SPLAT33]], <i32 0, i32 1>
; CHECK-NEXT:    store <2 x i32> [[TMP29]], ptr [[DOTVEC:%.*]], align 1
; CHECK-NEXT:    [[TMP30:%.*]] = sub i64 1024, [[UNI_PHI28:%.*]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT42:%.*]] = insertelement <2 x i64> poison, i64 [[TMP30]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT43:%.*]] = shufflevector <2 x i64> [[BROADCAST_SPLATINSERT42]], <2 x i64> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VPLANNEDBB34:%.*]]
; CHECK:       VPlannedBB34:
; CHECK-NEXT:    [[UNI_PHI35:%.*]] = phi i64 [ 0, [[VPLANNEDBB30:%.*]] ], [ [[TMP49:%.*]], [[NEW_LATCH67:%.*]] ]
; CHECK-NEXT:    [[VEC_PHI36:%.*]] = phi <2 x i64> [ <i64 0, i64 1>, [[VPLANNEDBB30]] ], [ [[TMP48:%.*]], [[NEW_LATCH67]] ]
; CHECK-NEXT:    [[VEC_PHI37:%.*]] = phi <2 x float> [ [[BROADCAST_SPLAT84]], [[VPLANNEDBB30]] ], [ [[PREDBLEND73:%.*]], [[NEW_LATCH67]] ]
; CHECK-NEXT:    [[UNI_PHI38:%.*]] = phi i32 [ [[TMP27]], [[VPLANNEDBB30]] ], [ [[PREDBLEND70_EXTRACT_0_:%.*]], [[NEW_LATCH67]] ]
; CHECK-NEXT:    [[VEC_PHI39:%.*]] = phi <2 x i32> [ [[TMP29]], [[VPLANNEDBB30]] ], [ [[PREDBLEND70:%.*]], [[NEW_LATCH67]] ]
; CHECK-NEXT:    [[TMP31:%.*]] = add nuw nsw  <2 x i64> [[VEC_PHI36]], [[BROADCAST_SPLAT41:%.*]]
; CHECK-NEXT:    [[DOTEXTRACT_0_:%.*]] = extractelement <2 x i64> [[TMP31]], i32 0
; CHECK-NEXT:    store <2 x float> zeroinitializer, ptr [[DOTVEC31]], align 1
; CHECK-NEXT:    [[TMP32:%.*]] = icmp ult i64 [[UNI_PHI35]], [[TMP30]]
; CHECK-NEXT:    [[TMP33:%.*]] = icmp ult <2 x i64> [[VEC_PHI36]], [[BROADCAST_SPLAT43]]
; CHECK-NEXT:    br label [[VPLANNEDBB44:%.*]]
; CHECK:       VPlannedBB44:
; CHECK-NEXT:    call void @llvm.masked.store.v2i32.p0(<2 x i32> [[VEC_PHI39]], ptr [[DOTVEC]], i32 1, <2 x i1> [[TMP33]])
; CHECK-NEXT:    br label [[VPLANNEDBB45:%.*]]
; CHECK:       VPlannedBB45:
; CHECK-NEXT:    br label [[VPLANNEDBB46:%.*]]
; CHECK:       VPlannedBB46:
; CHECK-NEXT:    [[TMP34:%.*]] = trunc <2 x i64> [[TMP31]] to <2 x i32>
; CHECK-NEXT:    call void @llvm.masked.store.v2i32.p0(<2 x i32> [[TMP34]], ptr [[DOTVEC]], i32 4, <2 x i1> [[TMP33]])
; CHECK-NEXT:    br label [[VPLANNEDBB47:%.*]]
; CHECK:       VPlannedBB47:
; CHECK-NEXT:    br label [[VPLANNEDBB48:%.*]]
; CHECK:       VPlannedBB48:
; CHECK-NEXT:    [[WIDE_LOAD49:%.*]] = load <2 x i32>, ptr [[DOTVEC]], align 4
; CHECK-NEXT:    [[TMP35:%.*]] = sext <2 x i32> [[WIDE_LOAD49]] to <2 x i64>
; CHECK-NEXT:    [[TMP35_EXTRACT_0:%.*]] = extractelement <2 x i64> [[TMP35]], i32 0
; CHECK-NEXT:    [[SCALAR_GEP:%.*]] = getelementptr inbounds float, ptr [[A0:%.*]], i64 [[TMP35_EXTRACT_0]]
; CHECK-NEXT:    [[WIDE_LOAD52:%.*]] = call <2 x float> @llvm.masked.load.v2f32.p0(ptr [[SCALAR_GEP]], i32 4, <2 x i1> [[TMP33]], <2 x float> poison)
; CHECK-NEXT:    [[WIDE_LOAD54:%.*]] = load <2 x float>, ptr [[DOTVEC31]], align 4
; CHECK-NEXT:    [[TMP36:%.*]] = fadd fast <2 x float> [[WIDE_LOAD54]], [[WIDE_LOAD52]]
; CHECK-NEXT:    call void @llvm.masked.store.v2f32.p0(<2 x float> [[TMP36]], ptr [[DOTVEC31]], i32 4, <2 x i1> [[TMP33]])
; CHECK-NEXT:    br label [[VPLANNEDBB53:%.*]]
; CHECK:       VPlannedBB53:
; CHECK-NEXT:    br label [[VPLANNEDBB54:%.*]]
; CHECK:       VPlannedBB54:
; CHECK-NEXT:    [[TMP37:%.*]] = add <2 x i32> [[VEC_PHI39]], <i32 2, i32 2>
; CHECK-NEXT:    [[TMP38:%.*]] = add i32 [[UNI_PHI38]], 2
; CHECK-NEXT:    br label [[VPLANNEDBB55:%.*]]
; CHECK:       VPlannedBB55:
; CHECK-NEXT:    br label [[VPLANNEDBB56:%.*]]
; CHECK:       VPlannedBB56:
; CHECK-NEXT:    [[WIDE_LOAD59:%.*]] = load <2 x float>, ptr [[DOTVEC31]], align 1
; CHECK-NEXT:    [[TMP39:%.*]] = shufflevector <2 x float> [[WIDE_LOAD59]], <2 x float> zeroinitializer, <2 x i32> <i32 2, i32 0>
; CHECK-NEXT:    [[TMP40:%.*]] = fadd fast <2 x float> [[WIDE_LOAD59]], [[TMP39]]
; CHECK-NEXT:    [[TMP41:%.*]] = shufflevector <2 x float> [[TMP40]], <2 x float> zeroinitializer, <2 x i32> <i32 2, i32 0>
; CHECK-NEXT:    [[TMP42:%.*]] = fadd fast <2 x float> [[TMP41]], [[VEC_PHI37]]
; CHECK-NEXT:    call void @llvm.masked.store.v2f32.p0(<2 x float> [[TMP42]], ptr [[DOTVEC31]], i32 1, <2 x i1> [[TMP33]])
; CHECK-NEXT:    [[TMP43:%.*]] = bitcast <2 x i1> [[TMP33]] to i2
; CHECK-NEXT:    [[CTLZ:%.*]] = call i2 @llvm.ctlz.i2(i2 [[TMP43]], i1 true)
; CHECK-NEXT:    [[TMP44:%.*]] = sub i2 1, [[CTLZ]]
; CHECK-NEXT:    [[LAST_ACTIVE_LANE:%.*]] = extractelement <2 x float> [[TMP42]], i2 [[TMP44]]
; CHECK-NEXT:    [[TMP45:%.*]] = bitcast <2 x i1> [[TMP33]] to i2
; CHECK-NEXT:    [[CTLZ60:%.*]] = call i2 @llvm.ctlz.i2(i2 [[TMP45]], i1 true)
; CHECK-NEXT:    [[TMP46:%.*]] = sub i2 1, [[CTLZ60]]
; CHECK-NEXT:    [[LAST_ACTIVE_LANE61:%.*]] = extractelement <2 x float> [[WIDE_LOAD59]], i2 [[TMP46]]
; CHECK-NEXT:    [[TMP47:%.*]] = fadd float [[LAST_ACTIVE_LANE]], [[LAST_ACTIVE_LANE61]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT71:%.*]] = insertelement <2 x float> poison, float [[TMP47]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT72:%.*]] = shufflevector <2 x float> [[BROADCAST_SPLATINSERT71]], <2 x float> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VPLANNEDBB60:%.*]]
; CHECK:       VPlannedBB60:
; CHECK-NEXT:    br label [[VPLANNEDBB61:%.*]]
; CHECK:       VPlannedBB61:
; CHECK-NEXT:    [[WIDE_LOAD64:%.*]] = load <2 x float>, ptr [[DOTVEC31]], align 4
; CHECK-NEXT:    [[SCALAR_GEP65:%.*]] = getelementptr inbounds float, ptr [[B:%.*]], i64 [[DOTEXTRACT_0_]]
; CHECK-NEXT:    call void @llvm.masked.store.v2f32.p0(<2 x float> [[WIDE_LOAD64]], ptr [[SCALAR_GEP65]], i32 4, <2 x i1> [[TMP33]])
; CHECK-NEXT:    br label [[VPLANNEDBB65:%.*]]
; CHECK:       VPlannedBB65:
; CHECK-NEXT:    br label [[NEW_LATCH32:%.*]]
; CHECK:       new_latch32:
; CHECK-NEXT:    br label [[NEW_LATCH66:%.*]]
; CHECK:       new_latch66:
; CHECK-NEXT:    [[PREDBLEND:%.*]] = select <2 x i1> [[TMP33]], <2 x float> [[TMP36]], <2 x float> [[BROADCAST_SPLAT69:%.*]]
; CHECK-NEXT:    [[PREDBLEND70]] = select <2 x i1> [[TMP33]], <2 x i32> [[TMP37]], <2 x i32> [[VEC_PHI39]]
; CHECK-NEXT:    [[PREDBLEND70_EXTRACT_0_]] = extractelement <2 x i32> [[PREDBLEND70]], i32 0
; CHECK-NEXT:    [[PREDBLEND73]] = select <2 x i1> [[TMP33]], <2 x float> [[BROADCAST_SPLAT72]], <2 x float> [[VEC_PHI37]]
; CHECK-NEXT:    [[PREDBLEND73_EXTRACT_0_:%.*]] = extractelement <2 x float> [[PREDBLEND73]], i32 0
; CHECK-NEXT:    [[TMP48]] = add nuw nsw <2 x i64> [[VEC_PHI36]], <i64 2, i64 2>
; CHECK-NEXT:    [[TMP49]] = add nuw nsw i64 [[UNI_PHI35]], 2
; CHECK-NEXT:    [[TMP50:%.*]] = icmp ult <2 x i64> [[TMP48]], [[BROADCAST_SPLAT43]]
; CHECK-NEXT:    [[TMP51:%.*]] = bitcast <2 x i1> [[TMP50]] to i2
; CHECK-NEXT:    [[TMP52:%.*]] = icmp eq i2 [[TMP51]], 0
; CHECK-NEXT:    br i1 [[TMP52]], label [[VPLANNEDBB73:%.*]], label [[VPLANNEDBB34]]
; CHECK:       VPlannedBB73:
; CHECK-NEXT:    store float [[PREDBLEND73_EXTRACT_0_]], ptr [[X_RED]], align 1
;
DIR.OMP.SIMD.1:
  %x.red = alloca float, align 4
  %i.linear.iv = alloca i32, align 4
  store float 1.000000e+00, ptr %x.red, align 4
  br label %DIR.OMP.SIMD.126

DIR.OMP.SIMD.126:                                 ; preds = %DIR.OMP.SIMD.1
  %0 = call token @llvm.directive.region.entry() [ "DIR.OMP.SIMD"(), "QUAL.OMP.REDUCTION.ADD:INSCAN.TYPED"(ptr %x.red, float 0.000000e+00, i32 1, i64 1), "QUAL.OMP.NORMALIZED.IV:TYPED"(ptr null, i32 0), "QUAL.OMP.NORMALIZED.UB:TYPED"(ptr null, i32 0), "QUAL.OMP.LINEAR:IV.TYPED"(ptr %i.linear.iv, i32 0, i32 1, i32 1) ]
  br label %DIR.OMP.END.SCAN.2

DIR.OMP.END.SCAN.2:                               ; preds = %DIR.OMP.SIMD.126, %DIR.VPO.END.GUARD.MEM.MOTION.4
  %indvars.iv = phi i64 [ 0, %DIR.OMP.SIMD.126 ], [ %indvars.iv.next, %DIR.VPO.END.GUARD.MEM.MOTION.4 ]
  br label %DIR.VPO.GUARD.MEM.MOTION.2

DIR.VPO.GUARD.MEM.MOTION.2:                       ; preds = DIR.OMP.END.SCAN.2
  %guard.start1 = call token @llvm.directive.region.entry() [ "DIR.VPO.GUARD.MEM.MOTION"(), "QUAL.OMP.LIVEIN"(ptr %x.red) ]
  br label %DIR.OMP.SIMD.139

DIR.OMP.SIMD.139:                                 ; preds = %DIR.VPO.GUARD.MEM.MOTION.2
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %i.linear.iv)
  %1 = trunc i64 %indvars.iv to i32
  store i32 %1, ptr %i.linear.iv, align 4
  %2 = load float, ptr %x.red, align 4
  %arrayidx = getelementptr inbounds float, ptr %B, i64 %indvars.iv
  store float %2, ptr %arrayidx, align 4
  br label %DIR.VPO.END.GUARD.MEM.MOTION.6

DIR.VPO.END.GUARD.MEM.MOTION.6:                   ; preds = %DIR.OMP.SIMD.139
  call void @llvm.directive.region.exit(token %guard.start1) [ "DIR.VPO.END.GUARD.MEM.MOTION"() ]
  br label %DIR.OMP.SCAN.2

DIR.OMP.SCAN.2:                                   ; preds = %DIR.VPO.END.GUARD.MEM.MOTION.6
  %3 = call token @llvm.directive.region.entry() [ "DIR.OMP.SCAN"(), "QUAL.OMP.EXCLUSIVE:TYPED"(ptr %x.red, float 0.000000e+00, i32 1, i64 1) ]
  br label %DIR.OMP.SCAN.1

DIR.OMP.SCAN.1:                                   ; preds = %DIR.OMP.SCAN.2
  fence acq_rel
  br label %DIR.OMP.END.SCAN.4

DIR.OMP.END.SCAN.4:                               ; preds = %DIR.OMP.SCAN.1
  call void @llvm.directive.region.exit(token %3) [ "DIR.OMP.END.SCAN"() ]
  br label %DIR.OMP.END.SCAN.9.split

DIR.OMP.END.SCAN.9.split:                         ; preds = %DIR.OMP.END.SCAN.4
  %guard.start2 = call token @llvm.directive.region.entry() [ "DIR.VPO.GUARD.MEM.MOTION"(), "QUAL.OMP.LIVEIN"(ptr %x.red) ]
  br label %DIR.OMP.END.SCAN.228

DIR.OMP.END.SCAN.228:                             ; preds = %DIR.OMP.END.SCAN.9.split
  %4 = load i32, ptr %i.linear.iv, align 4
  %idxprom1 = sext i32 %4 to i64
  %arrayidx2 = getelementptr inbounds float, ptr %A, i64 %idxprom1
  %5 = load float, ptr %arrayidx2, align 4
  %6 = load float, ptr %x.red, align 4
  %add3 = fadd fast float %6, %5
  store float %add3, ptr %x.red, align 4
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %i.linear.iv)
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  br label %DIR.VPO.END.GUARD.MEM.MOTION.8

DIR.VPO.END.GUARD.MEM.MOTION.8:                   ; preds = DIR.OMP.END.SCAN.228
  call void @llvm.directive.region.exit(token %guard.start2) [ "DIR.VPO.END.GUARD.MEM.MOTION"() ]
  br label %DIR.VPO.END.GUARD.MEM.MOTION.4

DIR.VPO.END.GUARD.MEM.MOTION.4:                   ; preds = %DIR.VPO.END.GUARD.MEM.MOTION.8
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %DIR.OMP.END.SIMD.6, label %DIR.OMP.END.SCAN.2

DIR.OMP.END.SIMD.6:                               ; preds = %DIR.VPO.END.GUARD.MEM.MOTION.4
  %add3.lcssa = phi float [ %add3, %DIR.VPO.END.GUARD.MEM.MOTION.4 ]
  br label %DIR.OMP.END.SIMD.1

DIR.OMP.END.SIMD.1:                               ; preds = %DIR.OMP.END.SIMD.6
  call void @llvm.directive.region.exit(token %0) [ "DIR.OMP.END.SIMD"() ]
  br label %DIR.OMP.END.SIMD.3

DIR.OMP.END.SIMD.3:                               ; preds = %DIR.OMP.END.SIMD.1
  ret float %add3.lcssa
}

declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)

declare token @llvm.directive.region.entry()

declare void @llvm.directive.region.exit(token)

declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)
