; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes="instcombine" %s -S | FileCheck %s

; We should infer nuw for the mul.
define i8 @test1(i8 %x) {
; CHECK-LABEL: @test1(
; CHECK-NEXT:    [[A:%.*]] = and i8 [[X:%.*]], 127
; CHECK-NEXT:    [[B:%.*]] = mul nuw nsw i8 [[A]], 3
; CHECK-NEXT:    ret i8 [[B]]
;
  %a = and i8 %x, 127
  %b = mul nsw i8 %a, 3
  ret i8 %b
}

; Negative test we should not infer nuw.
define i8 @test2(i8 %x) {
; CHECK-LABEL: @test2(
; CHECK-NEXT:    [[A:%.*]] = and i8 [[X:%.*]], 127
; CHECK-NEXT:    [[B:%.*]] = mul nsw i8 [[A]], -3
; CHECK-NEXT:    ret i8 [[B]]
;
  %a = and i8 %x, 127
  %b = mul nsw i8 %a, -3
  ret i8 %b
}

; Negative test we should not infer nuw.
define i8 @test3(i8 %x) {
; CHECK-LABEL: @test3(
; CHECK-NEXT:    [[A:%.*]] = or i8 [[X:%.*]], -128
; CHECK-NEXT:    [[B:%.*]] = mul nsw i8 [[A]], 3
; CHECK-NEXT:    ret i8 [[B]]
;
  %a = or i8 %x, 128
  %b = mul nsw i8 %a, 3
  ret i8 %b
}
