; INTEL_FEATURE_SW_ADVANCED
; REQUIRES: intel_feature_sw_advanced
; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -opaque-pointers=0 < %s -enable-intel-advanced-opts=true -passes=instcombine -S | FileCheck %s

; Checks that min/max intrinsic recognition is disabled when:
; 1) AVX2 advanced opts are enabled, and AVX512 is disabled
; 2) AVX512 is enabled, and loopopt has not run yet.

target triple = "i686-pc-linux-gnu"

; AVX512 before loopopt
define void @avx512prehir(i32* %x, i32* %y) #0 {
; CHECK-LABEL: @avx512prehir(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP_1_I:%.*]] = load i32, i32* [[Y:%.*]], align 4
; CHECK-NEXT:    [[TMP_3_I:%.*]] = load i32, i32* [[X:%.*]], align 4
; CHECK-NEXT:    [[TMP_4_I:%.*]] = icmp slt i32 [[TMP_1_I]], [[TMP_3_I]]
; CHECK-NEXT:    [[TMP_4:%.*]] = select i1 [[TMP_4_I]], i32 [[TMP_1_I]], i32 [[TMP_3_I]]
; CHECK-NEXT:    store i32 [[TMP_4]], i32* [[X]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %tmp.1.i = load i32, i32* %y         ; <i32> [#uses=1]
  %tmp.3.i = load i32, i32* %x         ; <i32> [#uses=1]
  %tmp.4.i = icmp slt i32 %tmp.1.i, %tmp.3.i              ; <i1> [#uses=1]
  %retval.i = select i1 %tmp.4.i, i32* %y, i32* %x                ; <i32*> [#uses=1]
  %tmp.4 = load i32, i32* %retval.i            ; <i32> [#uses=1]
  store i32 %tmp.4, i32* %x
  ret void
}

; AVX2 (only) enabled, before loopopt
define void @avx2prehir(i32* %x, i32* %y) #1 {
; CHECK-LABEL: @avx2prehir(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP_2:%.*]] = load i32, i32* [[X:%.*]], align 4
; CHECK-NEXT:    [[TMP_3_I:%.*]] = load i32, i32* [[Y:%.*]], align 4
; CHECK-NEXT:    [[TMP_4_I:%.*]] = icmp slt i32 [[TMP_2]], [[TMP_3_I]]
; CHECK-NEXT:    [[TMP_6:%.*]] = select i1 [[TMP_4_I]], i32 [[TMP_3_I]], i32 [[TMP_2]]
; CHECK-NEXT:    store i32 [[TMP_6]], i32* [[Y]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %tmp.0 = alloca i32             ; <i32*> [#uses=2]
  %tmp.2 = load i32, i32* %x           ; <i32> [#uses=2]
  store i32 %tmp.2, i32* %tmp.0
  %tmp.3.i = load i32, i32* %y         ; <i32> [#uses=1]
  %tmp.4.i = icmp slt i32 %tmp.2, %tmp.3.i                ; <i1> [#uses=1]
  %retval.i = select i1 %tmp.4.i, i32* %y, i32* %tmp.0            ; <i32*> [#uses=1]
  %tmp.6 = load i32, i32* %retval.i            ; <i32> [#uses=1]
  store i32 %tmp.6, i32* %y
  ret void
}

; AVX2 (only) enabled, after loopopt
define void @avx2posthir(i32* %x, i32* %y) #2 {
; CHECK-LABEL: @avx2posthir(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP_2:%.*]] = load i32, i32* [[X:%.*]], align 4
; CHECK-NEXT:    [[TMP_3_I:%.*]] = load i32, i32* [[Y:%.*]], align 4
; CHECK-NEXT:    [[TMP_4_I:%.*]] = icmp slt i32 [[TMP_2]], [[TMP_3_I]]
; CHECK-NEXT:    [[TMP_6:%.*]] = select i1 [[TMP_4_I]], i32 [[TMP_3_I]], i32 [[TMP_2]]
; CHECK-NEXT:    store i32 [[TMP_6]], i32* [[Y]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %tmp.0 = alloca i32             ; <i32*> [#uses=2]
  %tmp.2 = load i32, i32* %x           ; <i32> [#uses=2]
  store i32 %tmp.2, i32* %tmp.0
  %tmp.3.i = load i32, i32* %y         ; <i32> [#uses=1]
  %tmp.4.i = icmp slt i32 %tmp.2, %tmp.3.i                ; <i1> [#uses=1]
  %retval.i = select i1 %tmp.4.i, i32* %y, i32* %tmp.0            ; <i32*> [#uses=1]
  %tmp.6 = load i32, i32* %retval.i            ; <i32> [#uses=1]
  store i32 %tmp.6, i32* %y
  ret void
}

; AVX512, after loopopt
define void @avx512posthir(i32* %x, i32* %y) #3 {
; CHECK-LABEL: @avx512posthir(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP_1_I:%.*]] = load i32, i32* [[Y:%.*]], align 4
; CHECK-NEXT:    [[TMP_3_I:%.*]] = load i32, i32* [[X:%.*]], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.smin.i32(i32 [[TMP_1_I]], i32 [[TMP_3_I]])
; CHECK-NEXT:    store i32 [[TMP0]], i32* [[X]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %tmp.1.i = load i32, i32* %y         ; <i32> [#uses=1]
  %tmp.3.i = load i32, i32* %x         ; <i32> [#uses=1]
  %tmp.4.i = icmp slt i32 %tmp.1.i, %tmp.3.i              ; <i1> [#uses=1]
  %retval.i = select i1 %tmp.4.i, i32* %y, i32* %x                ; <i32*> [#uses=1]
  %tmp.4 = load i32, i32* %retval.i            ; <i32> [#uses=1]
  store i32 %tmp.4, i32* %x
  ret void
}

attributes #0 = { "pre_loopopt" "target-cpu"="skylake-avx512" "target-features"="+avx512f,+avx512vl,+avx512dq"}
attributes #1 = { "pre_loopopt" "target-cpu"="haswell" "target-features"="+adx,+aes,+avx,+avx2"}
attributes #2 = { "target-cpu"="haswell" "target-features"="+adx,+aes,+avx,+avx2"}
attributes #3 = { "target-cpu"="skylake-avx512" "target-features"="+avx512f,+avx512vl,+avx512dq"}
; end INTEL_FEATURE_SW_ADVANCED
