; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -opaque-pointers=0 < %s -mtriple=x86_64-unknown-unknown -enable-intel-advanced-opts -O3 -mattr=+sse4.2 -S | FileCheck %s

%struct.VBVHNode = type { [6 x float], %struct.VBVHNode*, %struct.VBVHNode* }

define dso_local <3 x float*> @GEP_Splat_0(%struct.VBVHNode* nocapture readonly %node, i64 %index) {
; CHECK-LABEL: @GEP_Splat_0(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[INDEX0:%.*]] = insertelement <3 x i64> undef, i64 [[INDEX:%.*]], i64 0
; CHECK-NEXT:    [[INDEX2:%.*]] = shufflevector <3 x i64> [[INDEX0]], <3 x i64> poison, <3 x i32> zeroinitializer
; CHECK-NEXT:    [[RET:%.*]] = getelementptr inbounds [[STRUCT_VBVHNODE:%.*]], %struct.VBVHNode* [[NODE:%.*]], i64 0, i32 0, <3 x i64> [[INDEX2]]
; CHECK-NEXT:    ret <3 x float*> [[RET]]
;
entry:
  %n0 = insertelement <3 x %struct.VBVHNode*> undef, %struct.VBVHNode* %node, i32 0
  %n1 = insertelement <3 x %struct.VBVHNode*> %n0, %struct.VBVHNode* %node, i32 1
  %n2 = insertelement <3 x %struct.VBVHNode*> %n1, %struct.VBVHNode* %node, i32 2

  %index0 = insertelement <3 x i64> undef, i64 %index, i32 0
  %index1 = insertelement <3 x i64> %index0, i64 %index, i32 1
  %index2 = insertelement <3 x i64> %index1, i64 %index, i32 2

  %ret = getelementptr inbounds %struct.VBVHNode, <3 x %struct.VBVHNode*> %n2, <3 x i64> zeroinitializer, <3 x i32> zeroinitializer, <3 x i64> %index2
  ret <3 x float*> %ret
}

define dso_local <3 x float*> @GEP_Splat_1(%struct.VBVHNode* nocapture readonly %node, <3 x i64>* %index_ptr) {
; CHECK-LABEL: @GEP_Splat_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[INDEX:%.*]] = load <3 x i64>, <3 x i64>* [[INDEX_PTR:%.*]], align 32
; CHECK-NEXT:    [[RET:%.*]] = getelementptr inbounds [[STRUCT_VBVHNODE:%.*]], %struct.VBVHNode* [[NODE:%.*]], i64 0, i32 0, <3 x i64> [[INDEX]]
; CHECK-NEXT:    ret <3 x float*> [[RET]]
;
entry:
  %n0 = insertelement <3 x %struct.VBVHNode*> undef, %struct.VBVHNode* %node, i32 0
  %n1 = insertelement <3 x %struct.VBVHNode*> %n0, %struct.VBVHNode* %node, i32 1
  %n2 = insertelement <3 x %struct.VBVHNode*> %n1, %struct.VBVHNode* %node, i32 2
  %index = load <3 x i64>, <3 x i64>* %index_ptr
  %ret = getelementptr inbounds %struct.VBVHNode, <3 x %struct.VBVHNode*> %n2, <3 x i64> zeroinitializer, <3 x i32> zeroinitializer, <3 x i64> %index
  ret <3 x float*> %ret
}
