; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: intel_feature_isa_avx_compress
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avxcompress -verify-machineinstrs --show-mc-encoding | FileCheck %s --check-prefixes=CHECK

declare <2 x i64> @llvm.fshr.v2i64(<2 x i64>, <2 x i64>, <2 x i64>)
declare <4 x i32> @llvm.fshr.v4i32(<4 x i32>, <4 x i32>, <4 x i32>)
declare <8 x i16> @llvm.fshr.v8i16(<8 x i16>, <8 x i16>, <8 x i16>)


define <2 x i64> @var_funnnel_v2i64(<2 x i64> %x, <2 x i64> %y, <2 x i64> %amt) nounwind {
; CHECK-LABEL: var_funnnel_v2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpshrdvq %xmm2, %xmm0, %xmm1 # encoding: [0xc4,0xe2,0xf9,0x73,0xca]
; CHECK-NEXT:    vmovdqa %xmm1, %xmm0 # encoding: [0xc5,0xf9,0x6f,0xc1]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %res = call <2 x i64> @llvm.fshr.v2i64(<2 x i64> %x, <2 x i64> %y, <2 x i64> %amt)
  ret <2 x i64> %res
}

define <4 x i32> @var_funnnel_v4i32(<4 x i32> %x, <4 x i32> %y, <4 x i32> %amt) nounwind {
; CHECK-LABEL: var_funnnel_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpshrdvd %xmm2, %xmm0, %xmm1 # encoding: [0xc4,0xe2,0x79,0x73,0xca]
; CHECK-NEXT:    vmovdqa %xmm1, %xmm0 # encoding: [0xc5,0xf9,0x6f,0xc1]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %res = call <4 x i32> @llvm.fshr.v4i32(<4 x i32> %x, <4 x i32> %y, <4 x i32> %amt)
  ret <4 x i32> %res
}

define <8 x i16> @var_funnnel_v8i16(<8 x i16> %x, <8 x i16> %y, <8 x i16> %amt) nounwind {
; CHECK-LABEL: var_funnnel_v8i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpshrdvw %xmm2, %xmm0, %xmm1 # encoding: [0xc4,0xe2,0xf9,0x72,0xca]
; CHECK-NEXT:    vmovdqa %xmm1, %xmm0 # encoding: [0xc5,0xf9,0x6f,0xc1]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %res = call <8 x i16> @llvm.fshr.v8i16(<8 x i16> %x, <8 x i16> %y, <8 x i16> %amt)
  ret <8 x i16> %res
}

define <2 x i64> @splatvar_funnnel_v2i64(<2 x i64> %x, <2 x i64> %y, <2 x i64> %amt) nounwind {
; CHECK-LABEL: splatvar_funnnel_v2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpbroadcastq %xmm2, %xmm2 # encoding: [0xc4,0xe2,0x79,0x59,0xd2]
; CHECK-NEXT:    vpshrdvq %xmm2, %xmm0, %xmm1 # encoding: [0xc4,0xe2,0xf9,0x73,0xca]
; CHECK-NEXT:    vmovdqa %xmm1, %xmm0 # encoding: [0xc5,0xf9,0x6f,0xc1]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %splat = shufflevector <2 x i64> %amt, <2 x i64> undef, <2 x i32> zeroinitializer
  %res = call <2 x i64> @llvm.fshr.v2i64(<2 x i64> %x, <2 x i64> %y, <2 x i64> %splat)
  ret <2 x i64> %res
}

define <4 x i32> @splatvar_funnnel_v4i32(<4 x i32> %x, <4 x i32> %y, <4 x i32> %amt) nounwind {
; CHECK-LABEL: splatvar_funnnel_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpbroadcastd %xmm2, %xmm2 # encoding: [0xc4,0xe2,0x79,0x58,0xd2]
; CHECK-NEXT:    vpshrdvd %xmm2, %xmm0, %xmm1 # encoding: [0xc4,0xe2,0x79,0x73,0xca]
; CHECK-NEXT:    vmovdqa %xmm1, %xmm0 # encoding: [0xc5,0xf9,0x6f,0xc1]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %splat = shufflevector <4 x i32> %amt, <4 x i32> undef, <4 x i32> zeroinitializer
  %res = call <4 x i32> @llvm.fshr.v4i32(<4 x i32> %x, <4 x i32> %y, <4 x i32> %splat)
  ret <4 x i32> %res
}

define <8 x i16> @splatvar_funnnel_v8i16(<8 x i16> %x, <8 x i16> %y, <8 x i16> %amt) nounwind {
; CHECK-LABEL: splatvar_funnnel_v8i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpbroadcastw %xmm2, %xmm2 # encoding: [0xc4,0xe2,0x79,0x79,0xd2]
; CHECK-NEXT:    vpshrdvw %xmm2, %xmm0, %xmm1 # encoding: [0xc4,0xe2,0xf9,0x72,0xca]
; CHECK-NEXT:    vmovdqa %xmm1, %xmm0 # encoding: [0xc5,0xf9,0x6f,0xc1]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %splat = shufflevector <8 x i16> %amt, <8 x i16> undef, <8 x i32> zeroinitializer
  %res = call <8 x i16> @llvm.fshr.v8i16(<8 x i16> %x, <8 x i16> %y, <8 x i16> %splat)
  ret <8 x i16> %res
}

define <2 x i64> @constant_funnnel_v2i64(<2 x i64> %x, <2 x i64> %y) nounwind {
; CHECK-LABEL: constant_funnnel_v2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpshrdvq {{.*}}(%rip), %xmm0, %xmm1 # encoding: [0xc4,0xe2,0xf9,0x73,0x0d,A,A,A,A]
; CHECK-NEXT:    # fixup A - offset: 5, value: {{\.LCPI.*}}-4, kind: reloc_riprel_4byte
; CHECK-NEXT:    vmovdqa %xmm1, %xmm0 # encoding: [0xc5,0xf9,0x6f,0xc1]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %res = call <2 x i64> @llvm.fshr.v2i64(<2 x i64> %x, <2 x i64> %y, <2 x i64> <i64 4, i64 14>)
  ret <2 x i64> %res
}

define <4 x i32> @constant_funnnel_v4i32(<4 x i32> %x, <4 x i32> %y) nounwind {
; CHECK-LABEL: constant_funnnel_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpshrdvd {{.*}}(%rip), %xmm0, %xmm1 # encoding: [0xc4,0xe2,0x79,0x73,0x0d,A,A,A,A]
; CHECK-NEXT:    # fixup A - offset: 5, value: {{\.LCPI.*}}-4, kind: reloc_riprel_4byte
; CHECK-NEXT:    vmovdqa %xmm1, %xmm0 # encoding: [0xc5,0xf9,0x6f,0xc1]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %res = call <4 x i32> @llvm.fshr.v4i32(<4 x i32> %x, <4 x i32> %y, <4 x i32> <i32 4, i32 5, i32 6, i32 7>)
  ret <4 x i32> %res
}

define <8 x i16> @constant_funnnel_v8i16(<8 x i16> %x, <8 x i16> %y) nounwind {
; CHECK-LABEL: constant_funnnel_v8i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpshrdvw {{.*}}(%rip), %xmm0, %xmm1 # encoding: [0xc4,0xe2,0xf9,0x72,0x0d,A,A,A,A]
; CHECK-NEXT:    # fixup A - offset: 5, value: {{\.LCPI.*}}-4, kind: reloc_riprel_4byte
; CHECK-NEXT:    vmovdqa %xmm1, %xmm0 # encoding: [0xc5,0xf9,0x6f,0xc1]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %res = call <8 x i16> @llvm.fshr.v8i16(<8 x i16> %x, <8 x i16> %y, <8 x i16> <i16 0, i16 1, i16 2, i16 3, i16 4, i16 5, i16 6, i16 7>)
  ret <8 x i16> %res
}

define <2 x i64> @splatconstant_funnnel_v2i64(<2 x i64> %x, <2 x i64> %y) nounwind {
; CHECK-LABEL: splatconstant_funnnel_v2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpshrdq $14, %xmm0, %xmm1, %xmm0 # encoding: [0xc4,0xe3,0xf1,0x73,0xc0,0x0e]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %res = call <2 x i64> @llvm.fshr.v2i64(<2 x i64> %x, <2 x i64> %y, <2 x i64> <i64 14, i64 14>)
  ret <2 x i64> %res
}

define <4 x i32> @splatconstant_funnnel_v4i32(<4 x i32> %x, <4 x i32> %y) nounwind {
; CHECK-LABEL: splatconstant_funnnel_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpshrdd $4, %xmm0, %xmm1, %xmm0 # encoding: [0xc4,0xe3,0x71,0x73,0xc0,0x04]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %res = call <4 x i32> @llvm.fshr.v4i32(<4 x i32> %x, <4 x i32> %y, <4 x i32> <i32 4, i32 4, i32 4, i32 4>)
  ret <4 x i32> %res
}

define <8 x i16> @splatconstant_funnnel_v8i16(<8 x i16> %x, <8 x i16> %y) nounwind {
; CHECK-LABEL: splatconstant_funnnel_v8i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpshrdw $7, %xmm0, %xmm1, %xmm0 # encoding: [0xc4,0xe3,0xf1,0x72,0xc0,0x07]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %res = call <8 x i16> @llvm.fshr.v8i16(<8 x i16> %x, <8 x i16> %y, <8 x i16> <i16 7, i16 7, i16 7, i16 7, i16 7, i16 7, i16 7, i16 7>)
  ret <8 x i16> %res
}

