# Basics
CC		= icpc
CPP     = icc
LD		= icc
CXX     = icc

MICROOT=../../../bin/Serial/knf

BINDIR=../../../bin/Serial/knf

COMMON_OBJS = main.o \
			 Option.o \
			 OptionParser.o \
			 Timer.o \
			 ResultDatabase.o \
                         ProgressBar.o\
			 InvalidArgValue.o\
			 CommonCUDAStencilFactory.o\
			 CUDAStencilKernel.o\
			 CUDAStencilFactory.o\
			 CUDAStencil.o

BENCH_OBJS = Stencil2Dmain.o

BENCHMARKPROG = $(patsubst %.o,$(BINDIR)/%,$(BENCH_OBJS))

# MKL paths
MKLROOT=/opt/intel/composerxe_mic/mkl
KNF_MKL_LIB_PATH=/opt/intel/composerxe_mic/mkl/lib/mic

# Flags to include KNF MKL library
KNF_MKL_LIBS=-lmkl_core

CFLAGS          =  -g -O2 -offload-build -openmp -intel-extensions  -I$(MKLROOT)/include -opt-report-phase:offload -openmp-report -DLROWS=16 -DLCOLS=16

LDFLAGS = -offload-build -offload-ldopts:"-L$(KNF_MKL_LIB_PATH) $(KNF_MKL_LIBS) -openmp" \
	      -L$(MKLROOT)/lib/intel64 -Wl,--start-group -openmp\
          -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -Wl,--end-group

%.o: %.cpp
	$(CC) -c $< $(CFLAGS) $(CXXFLAGS)

$(BINDIR)/%: %.o 
	$(CC) -o $@ $(CFLAGS) $(CXXFLAGS) $(LDFLAGS) $(COMMON_OBJS) $< $(LIBS) 

all : $(BENCHMARKPROG)

$(BENCHMARKPROG) : $(COMMON_OBJS)

clean :
	rm *.o *.out *.xnlog
	rm ./bin/*.o
	rm ./bin/*.out
	rm ../*.o

# individual targets

stencil2d : $(BINDIR)/Stencil2D

$(BINDIR)/Stencil2D : $(COMMON_OBJS)

