//===--- DiagnosticIntel.td - Intel Diagnostics ---------------------------===//
//
// Copyright (C) 2017 Intel Corporation. All rights reserved.
//
// The information and source code contained herein is the exclusive
// property of Intel Corporation and may not be disclosed, examined
// or reproduced in whole or in part without explicit written authorization
// from the company.
//
//===----------------------------------------------------------------------===//

include "../Basic/intel/DiagnosticIntelCommonKinds.td"
include "../Basic/intel/DiagnosticIntelDriverKinds.td"
include "../Basic/intel/DiagnosticIntelParseKinds.td"
include "../Basic/intel/DiagnosticIntelSemaKinds.td"
include "../Basic/intel/DiagnosticIntelLexKinds.td"
