//      Copyright  (C) 2009-2014 Intel Corporation.
//      All rights reserved.
//
//        INTEL CORPORATION PROPRIETARY INFORMATION
//
// This software is supplied under the terms of a license
// agreement or nondisclosure agreement with Intel Corp.
// and may not be copied or disclosed except in accordance
// with the terms of that agreement.
//
// cvs_id[] = "$Id: iml_library_description.c 242914 2013-11-05 06:47:55Z akolesov $"
//

//++
//  LIBM library description table.
//
//  AUTHORS: Nikita Astafiev, Andrey Kolesov
//
//  CREATION DATE: 26-Nov-2013
//
//  MODIFICATION HISTORY:
//      26-Nov-2013, initial version. AK
//      17-Apr-2014, Added __rcpf and __rcpd. SC

    { "__cdivd",            "z" },
    { "__cdivf",            "c" },
    { "__divd",             "d" },
    { "__divf",             "s" },
    { "__divl",             "l" },
    { "__rcpd",             "d" },
    { "__rcpf",             "s" },
    { "__svml_div8",        "d" },
    { "__svml_div8_mask",   "d" },
    { "__svml_divf16",      "s" },
    { "__svml_divf16_mask", "s" },
    { "__svml_rcp8",        "d" },
    { "__svml_rcp8_mask",   "d" },
    { "__svml_rcpf16",      "s" },
    { "__svml_rcpf16_mask", "s" },
