; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: intel_feature_isa_avx256p
; RUN: llc < %s -mtriple=x86_64-- -mattr=+avx256p  | FileCheck %s

; This should do a single load into the fp stack for the return, not diddle with xmm registers.

define half @fcmp_select_fp_constants_olt(half %x) nounwind readnone {
; CHECK-LABEL: fcmp_select_fp_constants_olt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovsh {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    vcmpltsh {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %k1
; CHECK-NEXT:    vmovsh {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    vmovsh %xmm1, %xmm0, %xmm0 {%k1}
; CHECK-NEXT:    retq
  %c = fcmp olt half %x, -4.0
  %r = select i1 %c, half 42.0, half 23.0
  ret half %r
}

define half @fcmp_select_fp_constants_ogt(half %x) nounwind readnone {
; CHECK-LABEL: fcmp_select_fp_constants_ogt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovsh {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    vcmpgtsh {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %k1
; CHECK-NEXT:    vmovsh {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    vmovsh %xmm1, %xmm0, %xmm0 {%k1}
; CHECK-NEXT:    retq
  %c = fcmp ogt half %x, -4.0
  %r = select i1 %c, half 42.0, half 23.0
  ret half %r
}

