; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=scalarize-masked-mem-intrin -mtriple=x86_64-unknown-unknown -mattr=+avx2 < %s | FileCheck %s

define <16 x i16> @test_gather(ptr %0, ptr %map) {
; CHECK-LABEL: @test_gather(
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i16, ptr [[TMP0:%.*]], i32 0
; CHECK-NEXT:    [[TMP4:%.*]] = load i16, ptr [[TMP3]], align 2
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i16, ptr [[TMP0]], i32 1
; CHECK-NEXT:    [[TMP7:%.*]] = load i16, ptr [[TMP6]], align 2
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i16, ptr [[TMP0]], i32 2
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[TMP9]], align 2
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i16, ptr [[TMP0]], i32 3
; CHECK-NEXT:    [[TMP13:%.*]] = load i16, ptr [[TMP12]], align 2
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i16, ptr [[TMP0]], i32 4
; CHECK-NEXT:    [[TMP16:%.*]] = load i16, ptr [[TMP15]], align 2
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr i16, ptr [[TMP0]], i32 5
; CHECK-NEXT:    [[TMP19:%.*]] = load i16, ptr [[TMP18]], align 2
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr i16, ptr [[TMP0]], i32 6
; CHECK-NEXT:    [[TMP22:%.*]] = load i16, ptr [[TMP21]], align 2
; CHECK-NEXT:    [[TMP24:%.*]] = getelementptr i16, ptr [[TMP0]], i32 7
; CHECK-NEXT:    [[TMP25:%.*]] = load i16, ptr [[TMP24]], align 2
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr i16, ptr [[TMP0]], i32 8
; CHECK-NEXT:    [[TMP28:%.*]] = load i16, ptr [[TMP27]], align 2
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr i16, ptr [[TMP0]], i32 9
; CHECK-NEXT:    [[TMP31:%.*]] = load i16, ptr [[TMP30]], align 2
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr i16, ptr [[TMP0]], i32 10
; CHECK-NEXT:    [[TMP34:%.*]] = load i16, ptr [[TMP33]], align 2
; CHECK-NEXT:    [[TMP36:%.*]] = getelementptr i16, ptr [[TMP0]], i32 11
; CHECK-NEXT:    [[TMP37:%.*]] = load i16, ptr [[TMP36]], align 2
; CHECK-NEXT:    [[TMP39:%.*]] = getelementptr i16, ptr [[TMP0]], i32 12
; CHECK-NEXT:    [[TMP40:%.*]] = load i16, ptr [[TMP39]], align 2
; CHECK-NEXT:    [[TMP42:%.*]] = getelementptr i16, ptr [[TMP0]], i32 13
; CHECK-NEXT:    [[TMP43:%.*]] = load i16, ptr [[TMP42]], align 2
; CHECK-NEXT:    [[TMP45:%.*]] = getelementptr i16, ptr [[TMP0]], i32 14
; CHECK-NEXT:    [[TMP46:%.*]] = load i16, ptr [[TMP45]], align 2
; CHECK-NEXT:    [[TMP48:%.*]] = getelementptr i16, ptr [[TMP0]], i32 15
; CHECK-NEXT:    [[TMP49:%.*]] = load i16, ptr [[TMP48]], align 2
; CHECK-NEXT:    [[TMP50:%.*]] = sext i16 [[TMP4]] to i64
; CHECK-NEXT:    [[TMP51:%.*]] = add i64 [[TMP50]], 32768
; CHECK-NEXT:    [[PTR0:%.*]] = getelementptr i16, ptr [[MAP:%.*]], i64 [[TMP51]]
; CHECK-NEXT:    [[LOAD0:%.*]] = load i16, ptr [[PTR0]], align 2
; CHECK-NEXT:    [[RES0:%.*]] = insertelement <16 x i16> undef, i16 [[LOAD0]], i64 0
; CHECK-NEXT:    [[TMP52:%.*]] = sext i16 [[TMP7]] to i64
; CHECK-NEXT:    [[TMP53:%.*]] = add i64 [[TMP52]], 32768
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP53]]
; CHECK-NEXT:    [[LOAD1:%.*]] = load i16, ptr [[PTR1]], align 2
; CHECK-NEXT:    [[RES1:%.*]] = insertelement <16 x i16> [[RES0]], i16 [[LOAD1]], i64 1
; CHECK-NEXT:    [[TMP54:%.*]] = sext i16 [[TMP10]] to i64
; CHECK-NEXT:    [[TMP55:%.*]] = add i64 [[TMP54]], 32768
; CHECK-NEXT:    [[PTR2:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP55]]
; CHECK-NEXT:    [[LOAD2:%.*]] = load i16, ptr [[PTR2]], align 2
; CHECK-NEXT:    [[RES2:%.*]] = insertelement <16 x i16> [[RES1]], i16 [[LOAD2]], i64 2
; CHECK-NEXT:    [[TMP56:%.*]] = sext i16 [[TMP13]] to i64
; CHECK-NEXT:    [[TMP57:%.*]] = add i64 [[TMP56]], 32768
; CHECK-NEXT:    [[PTR3:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP57]]
; CHECK-NEXT:    [[LOAD3:%.*]] = load i16, ptr [[PTR3]], align 2
; CHECK-NEXT:    [[RES3:%.*]] = insertelement <16 x i16> [[RES2]], i16 [[LOAD3]], i64 3
; CHECK-NEXT:    [[TMP58:%.*]] = sext i16 [[TMP16]] to i64
; CHECK-NEXT:    [[TMP59:%.*]] = add i64 [[TMP58]], 32768
; CHECK-NEXT:    [[PTR4:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP59]]
; CHECK-NEXT:    [[LOAD4:%.*]] = load i16, ptr [[PTR4]], align 2
; CHECK-NEXT:    [[RES4:%.*]] = insertelement <16 x i16> [[RES3]], i16 [[LOAD4]], i64 4
; CHECK-NEXT:    [[TMP60:%.*]] = sext i16 [[TMP19]] to i64
; CHECK-NEXT:    [[TMP61:%.*]] = add i64 [[TMP60]], 32768
; CHECK-NEXT:    [[PTR5:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP61]]
; CHECK-NEXT:    [[LOAD5:%.*]] = load i16, ptr [[PTR5]], align 2
; CHECK-NEXT:    [[RES5:%.*]] = insertelement <16 x i16> [[RES4]], i16 [[LOAD5]], i64 5
; CHECK-NEXT:    [[TMP62:%.*]] = sext i16 [[TMP22]] to i64
; CHECK-NEXT:    [[TMP63:%.*]] = add i64 [[TMP62]], 32768
; CHECK-NEXT:    [[PTR6:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP63]]
; CHECK-NEXT:    [[LOAD6:%.*]] = load i16, ptr [[PTR6]], align 2
; CHECK-NEXT:    [[RES6:%.*]] = insertelement <16 x i16> [[RES5]], i16 [[LOAD6]], i64 6
; CHECK-NEXT:    [[TMP64:%.*]] = sext i16 [[TMP25]] to i64
; CHECK-NEXT:    [[TMP65:%.*]] = add i64 [[TMP64]], 32768
; CHECK-NEXT:    [[PTR7:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP65]]
; CHECK-NEXT:    [[LOAD7:%.*]] = load i16, ptr [[PTR7]], align 2
; CHECK-NEXT:    [[RES7:%.*]] = insertelement <16 x i16> [[RES6]], i16 [[LOAD7]], i64 7
; CHECK-NEXT:    [[TMP66:%.*]] = sext i16 [[TMP28]] to i64
; CHECK-NEXT:    [[TMP67:%.*]] = add i64 [[TMP66]], 32768
; CHECK-NEXT:    [[PTR8:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP67]]
; CHECK-NEXT:    [[LOAD8:%.*]] = load i16, ptr [[PTR8]], align 2
; CHECK-NEXT:    [[RES8:%.*]] = insertelement <16 x i16> [[RES7]], i16 [[LOAD8]], i64 8
; CHECK-NEXT:    [[TMP68:%.*]] = sext i16 [[TMP31]] to i64
; CHECK-NEXT:    [[TMP69:%.*]] = add i64 [[TMP68]], 32768
; CHECK-NEXT:    [[PTR9:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP69]]
; CHECK-NEXT:    [[LOAD9:%.*]] = load i16, ptr [[PTR9]], align 2
; CHECK-NEXT:    [[RES9:%.*]] = insertelement <16 x i16> [[RES8]], i16 [[LOAD9]], i64 9
; CHECK-NEXT:    [[TMP70:%.*]] = sext i16 [[TMP34]] to i64
; CHECK-NEXT:    [[TMP71:%.*]] = add i64 [[TMP70]], 32768
; CHECK-NEXT:    [[PTR10:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP71]]
; CHECK-NEXT:    [[LOAD10:%.*]] = load i16, ptr [[PTR10]], align 2
; CHECK-NEXT:    [[RES10:%.*]] = insertelement <16 x i16> [[RES9]], i16 [[LOAD10]], i64 10
; CHECK-NEXT:    [[TMP72:%.*]] = sext i16 [[TMP37]] to i64
; CHECK-NEXT:    [[TMP73:%.*]] = add i64 [[TMP72]], 32768
; CHECK-NEXT:    [[PTR11:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP73]]
; CHECK-NEXT:    [[LOAD11:%.*]] = load i16, ptr [[PTR11]], align 2
; CHECK-NEXT:    [[RES11:%.*]] = insertelement <16 x i16> [[RES10]], i16 [[LOAD11]], i64 11
; CHECK-NEXT:    [[TMP74:%.*]] = sext i16 [[TMP40]] to i64
; CHECK-NEXT:    [[TMP75:%.*]] = add i64 [[TMP74]], 32768
; CHECK-NEXT:    [[PTR12:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP75]]
; CHECK-NEXT:    [[LOAD12:%.*]] = load i16, ptr [[PTR12]], align 2
; CHECK-NEXT:    [[RES12:%.*]] = insertelement <16 x i16> [[RES11]], i16 [[LOAD12]], i64 12
; CHECK-NEXT:    [[TMP76:%.*]] = sext i16 [[TMP43]] to i64
; CHECK-NEXT:    [[TMP77:%.*]] = add i64 [[TMP76]], 32768
; CHECK-NEXT:    [[PTR13:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP77]]
; CHECK-NEXT:    [[LOAD13:%.*]] = load i16, ptr [[PTR13]], align 2
; CHECK-NEXT:    [[RES13:%.*]] = insertelement <16 x i16> [[RES12]], i16 [[LOAD13]], i64 13
; CHECK-NEXT:    [[TMP78:%.*]] = sext i16 [[TMP46]] to i64
; CHECK-NEXT:    [[TMP79:%.*]] = add i64 [[TMP78]], 32768
; CHECK-NEXT:    [[PTR14:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP79]]
; CHECK-NEXT:    [[LOAD14:%.*]] = load i16, ptr [[PTR14]], align 2
; CHECK-NEXT:    [[RES14:%.*]] = insertelement <16 x i16> [[RES13]], i16 [[LOAD14]], i64 14
; CHECK-NEXT:    [[TMP80:%.*]] = sext i16 [[TMP49]] to i64
; CHECK-NEXT:    [[TMP81:%.*]] = add i64 [[TMP80]], 32768
; CHECK-NEXT:    [[PTR15:%.*]] = getelementptr i16, ptr [[MAP]], i64 [[TMP81]]
; CHECK-NEXT:    [[LOAD15:%.*]] = load i16, ptr [[PTR15]], align 2
; CHECK-NEXT:    [[RES15:%.*]] = insertelement <16 x i16> [[RES14]], i16 [[LOAD15]], i64 15
; CHECK-NEXT:    ret <16 x i16> [[RES15]]
;
  %.splatinsert46 = insertelement <16 x ptr> poison, ptr %map, i32 0
  %.splat47 = shufflevector <16 x ptr> %.splatinsert46, <16 x ptr> poison, <16 x i32> zeroinitializer
  %ld = load <16 x i16>, ptr %0, align 2
  %2 = sext <16 x i16> %ld to <16 x i64>
  %3 = add nsw <16 x i64> %2, <i64 32768, i64 32768, i64 32768, i64 32768, i64 32768, i64 32768, i64 32768, i64 32768, i64 32768, i64 32768, i64 32768, i64 32768, i64 32768, i64 32768, i64 32768, i64 32768>
  %4 = getelementptr inbounds i16, <16 x ptr> %.splat47, <16 x i64> %3
  %5 = call <16 x i16> @llvm.masked.gather.v16i16.v16p0(<16 x ptr> %4, i32 2, <16 x i1> <i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true, i1 true>, <16 x i16> undef)
  ret <16 x i16> %5
}

; Function Attrs: nofree nosync nounwind readonly willreturn
declare <16 x i16> @llvm.masked.gather.v16i16.v16p0(<16 x ptr>, i32, <16 x i1>, <16 x i16>)
