; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: intel_feature_isa_avx_rao_int
; RUN: llc < %s -O0 -verify-machineinstrs -mtriple=x86_64-unknown-unknown --show-mc-encoding -mattr=+avx2,+avxraoint | FileCheck %s --check-prefixes=X64
; RUN: llc < %s -O0 -verify-machineinstrs -mtriple=i686-unknown-unknown --show-mc-encoding -mattr=+avx2,+avxraoint | FileCheck %s --check-prefixes=X86

define void @test_int_x86_vpaaddd128(i8* %A, <4 x i32> %B) {
; X64-LABEL: test_int_x86_vpaaddd128:
; X64:       # %bb.0:
; X64-NEXT:    vpaaddd %xmm0, (%rdi) # encoding: [0xc4,0xe2,0x78,0xfc,0x07]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaaddd128:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaaddd %xmm0, (%eax) # encoding: [0xc4,0xe2,0x78,0xfc,0x00]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaaddd128(i8* %A, <4 x i32> %B)
  ret  void
}
declare void @llvm.x86.vpaaddd128(i8* %A, <4 x i32> %B)

define void @test_int_x86_vpaaddd256(i8* %A, <8 x i32> %B) {
; X64-LABEL: test_int_x86_vpaaddd256:
; X64:       # %bb.0:
; X64-NEXT:    vpaaddd %ymm0, (%rdi) # encoding: [0xc4,0xe2,0x7c,0xfc,0x07]
; X64-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaaddd256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaaddd %ymm0, (%eax) # encoding: [0xc4,0xe2,0x7c,0xfc,0x00]
; X86-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaaddd256(i8* %A, <8 x i32> %B)
  ret  void
}
declare void @llvm.x86.vpaaddd256(i8* %A, <8 x i32> %B)

define void @test_int_x86_vpaaddq128(i8* %A, <2 x i64> %B) {
; X64-LABEL: test_int_x86_vpaaddq128:
; X64:       # %bb.0:
; X64-NEXT:    vpaaddq %xmm0, (%rdi) # encoding: [0xc4,0xe2,0xf8,0xfc,0x07]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaaddq128:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaaddq %xmm0, (%eax) # encoding: [0xc4,0xe2,0xf8,0xfc,0x00]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaaddq128(i8* %A, <2 x i64> %B)
  ret  void
}
declare void @llvm.x86.vpaaddq128(i8* %A, <2 x i64> %B)

define void @test_int_x86_vpaaddq256(i8* %A, <4 x i64> %B) {
; X64-LABEL: test_int_x86_vpaaddq256:
; X64:       # %bb.0:
; X64-NEXT:    vpaaddq %ymm0, (%rdi) # encoding: [0xc4,0xe2,0xfc,0xfc,0x07]
; X64-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaaddq256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaaddq %ymm0, (%eax) # encoding: [0xc4,0xe2,0xfc,0xfc,0x00]
; X86-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaaddq256(i8* %A, <4 x i64> %B)
  ret  void
}
declare void @llvm.x86.vpaaddq256(i8* %A, <4 x i64> %B)

define void @test_int_x86_vpaandd128(i8* %A, <4 x i32> %B) {
; X64-LABEL: test_int_x86_vpaandd128:
; X64:       # %bb.0:
; X64-NEXT:    vpaandd %xmm0, (%rdi) # encoding: [0xc4,0xe2,0x79,0xfc,0x07]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaandd128:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaandd %xmm0, (%eax) # encoding: [0xc4,0xe2,0x79,0xfc,0x00]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaandd128(i8* %A, <4 x i32> %B)
  ret  void
}
declare void @llvm.x86.vpaandd128(i8* %A, <4 x i32> %B)

define void @test_int_x86_vpaandd256(i8* %A, <8 x i32> %B) {
; X64-LABEL: test_int_x86_vpaandd256:
; X64:       # %bb.0:
; X64-NEXT:    vpaandd %ymm0, (%rdi) # encoding: [0xc4,0xe2,0x7d,0xfc,0x07]
; X64-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaandd256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaandd %ymm0, (%eax) # encoding: [0xc4,0xe2,0x7d,0xfc,0x00]
; X86-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaandd256(i8* %A, <8 x i32> %B)
  ret  void
}
declare void @llvm.x86.vpaandd256(i8* %A, <8 x i32> %B)

define void @test_int_x86_vpaandq128(i8* %A, <2 x i64> %B) {
; X64-LABEL: test_int_x86_vpaandq128:
; X64:       # %bb.0:
; X64-NEXT:    vpaandq %xmm0, (%rdi) # encoding: [0xc4,0xe2,0xf9,0xfc,0x07]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaandq128:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaandq %xmm0, (%eax) # encoding: [0xc4,0xe2,0xf9,0xfc,0x00]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaandq128(i8* %A, <2 x i64> %B)
  ret  void
}
declare void @llvm.x86.vpaandq128(i8* %A, <2 x i64> %B)

define void @test_int_x86_vpaandq256(i8* %A, <4 x i64> %B) {
; X64-LABEL: test_int_x86_vpaandq256:
; X64:       # %bb.0:
; X64-NEXT:    vpaandq %ymm0, (%rdi) # encoding: [0xc4,0xe2,0xfd,0xfc,0x07]
; X64-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaandq256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaandq %ymm0, (%eax) # encoding: [0xc4,0xe2,0xfd,0xfc,0x00]
; X86-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaandq256(i8* %A, <4 x i64> %B)
  ret  void
}
declare void @llvm.x86.vpaandq256(i8* %A, <4 x i64> %B)

define void @test_int_x86_vpaord128(i8* %A, <4 x i32> %B) {
; X64-LABEL: test_int_x86_vpaord128:
; X64:       # %bb.0:
; X64-NEXT:    vpaord %xmm0, (%rdi) # encoding: [0xc4,0xe2,0x7b,0xfc,0x07]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaord128:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaord %xmm0, (%eax) # encoding: [0xc4,0xe2,0x7b,0xfc,0x00]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaord128(i8* %A, <4 x i32> %B)
  ret  void
}
declare void @llvm.x86.vpaord128(i8* %A, <4 x i32> %B)

define void @test_int_x86_vpaord256(i8* %A, <8 x i32> %B) {
; X64-LABEL: test_int_x86_vpaord256:
; X64:       # %bb.0:
; X64-NEXT:    vpaord %ymm0, (%rdi) # encoding: [0xc4,0xe2,0x7f,0xfc,0x07]
; X64-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaord256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaord %ymm0, (%eax) # encoding: [0xc4,0xe2,0x7f,0xfc,0x00]
; X86-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaord256(i8* %A, <8 x i32> %B)
  ret  void
}
declare void @llvm.x86.vpaord256(i8* %A, <8 x i32> %B)

define void @test_int_x86_vpaorq128(i8* %A, <2 x i64> %B) {
; X64-LABEL: test_int_x86_vpaorq128:
; X64:       # %bb.0:
; X64-NEXT:    vpaorq %xmm0, (%rdi) # encoding: [0xc4,0xe2,0xfb,0xfc,0x07]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaorq128:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaorq %xmm0, (%eax) # encoding: [0xc4,0xe2,0xfb,0xfc,0x00]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaorq128(i8* %A, <2 x i64> %B)
  ret  void
}
declare void @llvm.x86.vpaorq128(i8* %A, <2 x i64> %B)

define void @test_int_x86_vpaorq256(i8* %A, <4 x i64> %B) {
; X64-LABEL: test_int_x86_vpaorq256:
; X64:       # %bb.0:
; X64-NEXT:    vpaorq %ymm0, (%rdi) # encoding: [0xc4,0xe2,0xff,0xfc,0x07]
; X64-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaorq256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaorq %ymm0, (%eax) # encoding: [0xc4,0xe2,0xff,0xfc,0x00]
; X86-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaorq256(i8* %A, <4 x i64> %B)
  ret  void
}
declare void @llvm.x86.vpaorq256(i8* %A, <4 x i64> %B)

define void @test_int_x86_vpaxord128(i8* %A, <4 x i32> %B) {
; X64-LABEL: test_int_x86_vpaxord128:
; X64:       # %bb.0:
; X64-NEXT:    vpaxord %xmm0, (%rdi) # encoding: [0xc4,0xe2,0x7a,0xfc,0x07]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaxord128:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaxord %xmm0, (%eax) # encoding: [0xc4,0xe2,0x7a,0xfc,0x00]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaxord128(i8* %A, <4 x i32> %B)
  ret  void
}
declare void @llvm.x86.vpaxord128(i8* %A, <4 x i32> %B)

define void @test_int_x86_vpaxord256(i8* %A, <8 x i32> %B) {
; X64-LABEL: test_int_x86_vpaxord256:
; X64:       # %bb.0:
; X64-NEXT:    vpaxord %ymm0, (%rdi) # encoding: [0xc4,0xe2,0x7e,0xfc,0x07]
; X64-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaxord256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaxord %ymm0, (%eax) # encoding: [0xc4,0xe2,0x7e,0xfc,0x00]
; X86-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaxord256(i8* %A, <8 x i32> %B)
  ret  void
}
declare void @llvm.x86.vpaxord256(i8* %A, <8 x i32> %B)

define void @test_int_x86_vpaxorq128(i8* %A, <2 x i64> %B) {
; X64-LABEL: test_int_x86_vpaxorq128:
; X64:       # %bb.0:
; X64-NEXT:    vpaxorq %xmm0, (%rdi) # encoding: [0xc4,0xe2,0xfa,0xfc,0x07]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaxorq128:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaxorq %xmm0, (%eax) # encoding: [0xc4,0xe2,0xfa,0xfc,0x00]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaxorq128(i8* %A, <2 x i64> %B)
  ret  void
}
declare void @llvm.x86.vpaxorq128(i8* %A, <2 x i64> %B)

define void @test_int_x86_vpaxorq256(i8* %A, <4 x i64> %B) {
; X64-LABEL: test_int_x86_vpaxorq256:
; X64:       # %bb.0:
; X64-NEXT:    vpaxorq %ymm0, (%rdi) # encoding: [0xc4,0xe2,0xfe,0xfc,0x07]
; X64-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X64-NEXT:    retq # encoding: [0xc3]
;
; X86-LABEL: test_int_x86_vpaxorq256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vpaxorq %ymm0, (%eax) # encoding: [0xc4,0xe2,0xfe,0xfc,0x00]
; X86-NEXT:    vzeroupper # encoding: [0xc5,0xf8,0x77]
; X86-NEXT:    retl # encoding: [0xc3]
  call void @llvm.x86.vpaxorq256(i8* %A, <4 x i64> %B)
  ret  void
}
declare void @llvm.x86.vpaxorq256(i8* %A, <4 x i64> %B)

