; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: intel_feature_isa_avx256
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

define <2 x double> @addpd128(<2 x double> %y, <2 x double> %x) #0 {
; CHECK-LABEL: addpd128:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vaddpd %xmm0, %xmm1, %xmm0
; CHECK-NEXT:    retq
entry:
  %add.i = fadd <2 x double> %x, %y
  ret <2 x double> %add.i
}

define <4 x double> @addpd256(<4 x double> %y, <4 x double> %x) #0 {
; CHECK-LABEL: addpd256:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vaddpd %ymm0, %ymm1, %ymm0
; CHECK-NEXT:    retq
entry:
  %add.i = fadd <4 x double> %x, %y
  ret <4 x double> %add.i
}

define <8 x double> @addpd512(<8 x double> %y, <8 x double> %x) #0 {
; CHECK-LABEL: addpd512:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vaddpd %ymm0, %ymm2, %ymm0
; CHECK-NEXT:    vaddpd %ymm1, %ymm3, %ymm1
; CHECK-NEXT:    retq
entry:
  %add.i = fadd <8 x double> %x, %y
  ret <8 x double> %add.i
}

attributes #0 = { "target-cpu"="common-avx256" }
