; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;REQUIRES: intel_feature_isa_amx_complex

; RUN: llc < %s -O0 -mtriple=x86_64-unknown-unknown -mattr=+amx-tile,+amx-complex --show-mc-encoding | FileCheck %s

define void @test_tcmmimfp16ps() {
; CHECK-LABEL: test_tcmmimfp16ps:
; CHECK:       # %bb.0:
; CHECK-NEXT:    tcmmimfp16ps %tmm3, %tmm2, %tmm1 # encoding: [0xc4,0xe2,0x61,0x6c,0xca]
; CHECK-NEXT:    retq # encoding: [0xc3]
  call void @llvm.x86.tcmmimfp16ps(i8 1, i8 2, i8 3)
  ret void
}
declare void @llvm.x86.tcmmimfp16ps(i8 %A, i8 %B, i8 %C)

define void @test_tcmmrlfp16ps() {
; CHECK-LABEL: test_tcmmrlfp16ps:
; CHECK:       # %bb.0:
; CHECK-NEXT:    tcmmrlfp16ps %tmm3, %tmm2, %tmm1 # encoding: [0xc4,0xe2,0x60,0x6c,0xca]
; CHECK-NEXT:    retq # encoding: [0xc3]
  call void @llvm.x86.tcmmrlfp16ps(i8 1, i8 2, i8 3)
  ret void
}
declare void @llvm.x86.tcmmrlfp16ps(i8 %A, i8 %B, i8 %C)

define void @test_tconjtcmmimfp16ps() {
; CHECK-LABEL: test_tconjtcmmimfp16ps:
; CHECK:       # %bb.0:
; CHECK-NEXT:    tconjtcmmimfp16ps %tmm3, %tmm2, %tmm1 # encoding: [0xc4,0xe2,0x60,0x6b,0xca]
; CHECK-NEXT:    retq # encoding: [0xc3]
  call void @llvm.x86.tconjtcmmimfp16ps(i8 1, i8 2, i8 3)
  ret void
}
declare void @llvm.x86.tconjtcmmimfp16ps(i8 %A, i8 %B, i8 %C)

define void @test_tconjtfp16() {
; CHECK-LABEL: test_tconjtfp16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    tconjtfp16 %tmm2, %tmm1 # encoding: [0xc4,0xe2,0x79,0x6b,0xca]
; CHECK-NEXT:    retq # encoding: [0xc3]
  call void @llvm.x86.tconjtfp16(i8 1, i8 2)
  ret void
}
declare void @llvm.x86.tconjtfp16(i8 %A, i8 %B)

define void @test_ttcmmimfp16ps() {
; CHECK-LABEL: test_ttcmmimfp16ps:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ttcmmimfp16ps %tmm3, %tmm2, %tmm1 # encoding: [0xc4,0xe2,0x63,0x6b,0xca]
; CHECK-NEXT:    retq # encoding: [0xc3]
  call void @llvm.x86.ttcmmimfp16ps(i8 1, i8 2, i8 3)
  ret void
}
declare void @llvm.x86.ttcmmimfp16ps(i8 %A, i8 %B, i8 %C)

define void @test_ttcmmrlfp16ps() {
; CHECK-LABEL: test_ttcmmrlfp16ps:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ttcmmrlfp16ps %tmm3, %tmm2, %tmm1 # encoding: [0xc4,0xe2,0x62,0x6b,0xca]
; CHECK-NEXT:    retq # encoding: [0xc3]
  call void @llvm.x86.ttcmmrlfp16ps(i8 1, i8 2, i8 3)
  ret void
}
declare void @llvm.x86.ttcmmrlfp16ps(i8 %A, i8 %B, i8 %C)

