; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -S -passes=slp-vectorizer -mattr=+avx2 -mtriple=i386 -slp-threshold=-100 | FileCheck %s

define void @f(i64 %i) {
; CHECK-LABEL: @f(
; CHECK-NEXT:  bb2:
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x i64> <i64 2, i64 poison>, i64 [[I:%.*]], i32 1
; CHECK-NEXT:    br i1 false, label [[BB7:%.*]], label [[BB3:%.*]]
; CHECK:       bb3:
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i64> [[TMP0]], <2 x i64> <i64 0, i64 poison>, <2 x i32> <i32 2, i32 1>
; CHECK-NEXT:    br i1 false, label [[BB7]], label [[BB4:%.*]]
; CHECK:       bb4:
; CHECK-NEXT:    br i1 false, label [[BB7]], label [[BB5:%.*]]
; CHECK:       bb5:
; CHECK-NEXT:    br i1 false, label [[BB7]], label [[BB6:%.*]]
; CHECK:       bb6:
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <2 x i64> [[TMP1]], <2 x i64> <i64 6, i64 poison>, <2 x i32> <i32 2, i32 1>
; CHECK-NEXT:    br label [[BB7]]
; CHECK:       bb7:
; CHECK-NEXT:    [[TMP3:%.*]] = phi <2 x i64> [ [[TMP1]], [[BB5]] ], [ [[TMP1]], [[BB4]] ], [ [[TMP1]], [[BB3]] ], [ [[TMP2]], [[BB6]] ], [ [[TMP0]], [[BB2:%.*]] ]
; CHECK-NEXT:    store <2 x i64> [[TMP3]], ptr null, align 4
; CHECK-NEXT:    ret void
;
bb2:
  br i1 false, label %bb7, label %bb3
bb3:
  br i1 false, label %bb7, label %bb4
bb4:
  br i1 false, label %bb7, label %bb5
bb5:
  br i1 false, label %bb7, label %bb6
bb6:
  br label %bb7
bb7:
  %i8 = phi i64 [ 0, %bb5 ], [ 0, %bb4 ], [ 0, %bb3 ], [ 6, %bb6 ], [ 2, %bb2 ]
  %i9 = phi i64 [ %i, %bb5 ], [ %i, %bb4 ], [ %i, %bb3 ], [ %i, %bb6 ], [ %i, %bb2 ]
  store i64 %i8, ptr null
  store i64 %i9, ptr getelementptr ([1 x i64], ptr null, i32 1)
  ret void
}
