; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=slp-vectorizer -enable-intel-advanced-opts -slp-multinode -mtriple=x86_64 -mattr=+avx2 -slp-threshold=-10 -S < %s | FileCheck %s

%class.B = type { %class.A, %class.A }
%class.A = type { [3 x i32] }

define void @foo(ptr nocapture readonly %this, ptr nocapture dereferenceable(4) %dir) {
; CHECK-LABEL: define {{[^@]+}}@foo(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr inbounds [[CLASS_B:%.*]], ptr [[THIS:%.*]], i64 0, i32 1, i32 0, i64 0
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX_I]], align 4
; CHECK-NEXT:    [[SUB:%.*]] = add i32 [[TMP0]], 1
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [[CLASS_B]], ptr [[THIS]], i64 0, i32 1, i32 0, i64 1
; CHECK-NEXT:    [[GEPLOAD:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i32>, ptr [[THIS]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <2 x i32> poison, i32 [[SUB]], i32 0
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <2 x i32> [[TMP2]], i32 [[GEPLOAD]], i32 1
; CHECK-NEXT:    [[TMP4:%.*]] = sub <2 x i32> [[TMP3]], [[TMP1]]
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x i32> [[TMP4]], i32 1
; CHECK-NEXT:    [[TMP6:%.*]] = add i32 [[TMP5]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x i32> [[TMP4]], i32 0
; CHECK-NEXT:    [[HIR_CMP_39:%.*]] = icmp sgt i32 [[TMP6]], [[TMP7]]
; CHECK-NEXT:    br i1 [[HIR_CMP_39]], label [[THEN_39:%.*]], label [[IFMERGE_39:%.*]]
; CHECK:       then.39:
; CHECK-NEXT:    store i32 1, ptr [[DIR:%.*]], align 4
; CHECK-NEXT:    br label [[IFMERGE_39]]
; CHECK:       ifmerge.39:
; CHECK-NEXT:    [[T3_0:%.*]] = phi i32 [ 1, [[THEN_39]] ], [ [[TMP7]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[ARRAYIDX21:%.*]] = getelementptr inbounds [[CLASS_B]], ptr [[THIS]], i64 0, i32 1, i32 0, i64 2
; CHECK-NEXT:    [[GEPLOAD22:%.*]] = load i32, ptr [[ARRAYIDX21]], align 4
; CHECK-NEXT:    [[ARRAYIDX23:%.*]] = getelementptr inbounds [[CLASS_B]], ptr [[THIS]], i64 0, i32 0, i32 0, i64 2
; CHECK-NEXT:    [[GEPLOAD24:%.*]] = load i32, ptr [[ARRAYIDX23]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = sub i32 [[GEPLOAD22]], [[GEPLOAD24]]
; CHECK-NEXT:    [[TMP9:%.*]] = add i32 [[TMP8]], 1
; CHECK-NEXT:    [[HIR_CMP_17:%.*]] = icmp sgt i32 [[TMP9]], [[T3_0]]
; CHECK-NEXT:    br i1 [[HIR_CMP_17]], label [[THEN_17:%.*]], label [[IFMERGE_17:%.*]]
; CHECK:       then.17:
; CHECK-NEXT:    store i32 2, ptr [[DIR]], align 4
; CHECK-NEXT:    br label [[IFMERGE_17]]
; CHECK:       ifmerge.17:
; CHECK-NEXT:    ret void
;
entry:
  %arrayidx.i = getelementptr inbounds %class.B, ptr %this, i64 0, i32 1, i32 0, i64 0
  %0 = load i32, ptr %arrayidx.i, align 4
  %1 = load i32, ptr %this, align 4
  %sub = add i32 %0, 1
  %add = sub i32 %sub, %1
  %arrayIdx = getelementptr inbounds %class.B, ptr %this, i64 0, i32 1, i32 0, i64 1
  %gepload = load i32, ptr %arrayIdx, align 4
  %arrayIdx19 = getelementptr inbounds %class.B, ptr %this, i64 0, i32 0, i32 0, i64 1
  %gepload20 = load i32, ptr %arrayIdx19, align 4
  %2 = sub i32 %gepload, %gepload20
  %3 = add i32 %2, 1
  %hir.cmp.39 = icmp sgt i32 %3, %add
  br i1 %hir.cmp.39, label %then.39, label %ifmerge.39

then.39:                                          ; preds = %entry
  store i32 1, ptr %dir, align 4
  br label %ifmerge.39

ifmerge.39:                                       ; preds = %then.39, %entry
  %t3.0 = phi i32 [ 1, %then.39 ], [ %add, %entry ]
  %arrayIdx21 = getelementptr inbounds %class.B, ptr %this, i64 0, i32 1, i32 0, i64 2
  %gepload22 = load i32, ptr %arrayIdx21, align 4
  %arrayIdx23 = getelementptr inbounds %class.B, ptr %this, i64 0, i32 0, i32 0, i64 2
  %gepload24 = load i32, ptr %arrayIdx23, align 4
  %4 = sub i32 %gepload22, %gepload24
  %5 = add i32 %4, 1
  %hir.cmp.17 = icmp sgt i32 %5, %t3.0
  br i1 %hir.cmp.17, label %then.17, label %ifmerge.17

then.17:                                          ; preds = %ifmerge.39
  store i32 2, ptr %dir, align 4
  br label %ifmerge.17

ifmerge.17:                                       ; preds = %then.17, %ifmerge.39
  ret void
}
