; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes="reassociate" -reassoc-early-exit-for-boolean-expr=0 -S < %s | FileCheck %s
; RUN: opt -passes="reassociate" -reassoc-early-exit-for-boolean-expr=1 -S < %s | FileCheck %s --check-prefix=CHECK-EARLYEXIT

declare void @use(i1)

define void @test1(i1 %x, i1 %y) {
; CHECK-LABEL: @test1(
; CHECK-NEXT:    [[TMP1:%.*]] = and i1 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = and i1 [[X]], [[Y]]
; CHECK-NEXT:    [[TMP3:%.*]] = or i1 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    call void @use(i1 [[TMP1]])
; CHECK-NEXT:    call void @use(i1 [[TMP3]])
; CHECK-NEXT:    ret void
;
; CHECK-EARLYEXIT-LABEL: @test1(
; CHECK-EARLYEXIT-NEXT:    [[TMP1:%.*]] = and i1 [[X:%.*]], [[Y:%.*]]
; CHECK-EARLYEXIT-NEXT:    [[TMP2:%.*]] = and i1 [[Y]], [[X]]
; CHECK-EARLYEXIT-NEXT:    [[TMP3:%.*]] = or i1 [[TMP1]], [[TMP2]]
; CHECK-EARLYEXIT-NEXT:    call void @use(i1 [[TMP1]])
; CHECK-EARLYEXIT-NEXT:    call void @use(i1 [[TMP3]])
; CHECK-EARLYEXIT-NEXT:    ret void
;
  %1 = and i1 %x, %y
  %2 = and i1 %y, %x
  %3 = or i1 %1, %2
  call void @use(i1 %1)
  call void @use(i1 %3)
  ret void
}
