; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -enable-intel-advanced-opts -intel-libirc-allowed -S -passes 'unaligned-nontemporal,verify' -unaligned-nontemporal-buffer-size=1024 < %s | FileCheck %s
target triple = "x86_64-unknown-linux-gnu"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"

define void @example(ptr %dest) "target-features"="+avx512f" {
; CHECK-LABEL: @example(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[DEST1:%.*]] = ptrtoint ptr [[DEST:%.*]] to i64
; CHECK-NEXT:    [[ADDR_NT_STORE_ALLOCA:%.*]] = alloca i8, i64 1112, align 64
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [[__NONTEMPORAL_BUFFER_DATA:%.*]], ptr [[ADDR_NT_STORE_ALLOCA]], i32 0, i32 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr [[__NONTEMPORAL_BUFFER_DATA]], ptr [[ADDR_NT_STORE_ALLOCA]], i32 0, i32 1
; CHECK-NEXT:    store i64 [[DEST1]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = and i64 [[DEST1]], 63
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr [[__NONTEMPORAL_BUFFER_DATA]], ptr [[ADDR_NT_STORE_ALLOCA]], i32 0, i32 2
; CHECK-NEXT:    store i64 [[TMP2]], ptr [[TMP3]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr [[__NONTEMPORAL_BUFFER_DATA]], ptr [[ADDR_NT_STORE_ALLOCA]], i32 0, i32 3
; CHECK-NEXT:    store i64 0, ptr [[TMP4]], align 8
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT:%.*]], [[LOOP_SPLIT:%.*]] ]
; CHECK-NEXT:    [[ADDR_NT_BUF_IDX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[ADDR_NT_BUF_POST_PHI:%.*]], [[LOOP_SPLIT]] ]
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[SPLAT:%.*]] = insertelement <8 x i64> zeroinitializer, i64 [[INDEX]], i32 0
; CHECK-NEXT:    [[ADDR:%.*]] = getelementptr inbounds <8 x i64>, ptr [[DEST]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [1 x <8 x i64>], ptr [[TMP0]], i64 [[ADDR_NT_BUF_IDX]], i64 0
; CHECK-NEXT:    store <8 x i64> [[SPLAT]], ptr [[TMP5]], align 8
; CHECK-NEXT:    [[ADDR_NT_BUF_IDX2:%.*]] = add nuw nsw i64 [[ADDR_NT_BUF_IDX]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i64 16, [[ADDR_NT_BUF_IDX2]]
; CHECK-NEXT:    br i1 [[TMP6]], label [[ADDR_NT_BUF_DRAIN:%.*]], label [[LOOP_SPLIT]]
; CHECK:       addr.nt_buf_drain:
; CHECK-NEXT:    call void @__libirc_nontemporal_store(ptr [[ADDR_NT_STORE_ALLOCA]], i64 1024, i32 0)
; CHECK-NEXT:    br label [[LOOP_SPLIT]]
; CHECK:       loop.split:
; CHECK-NEXT:    [[ADDR_NT_BUF_POST_PHI]] = phi i64 [ [[ADDR_NT_BUF_IDX2]], [[LOOP]] ], [ 0, [[ADDR_NT_BUF_DRAIN]] ]
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i64 [[INDEX]], 10000
; CHECK-NEXT:    br i1 [[COND]], label [[EXIT:%.*]], label [[LOOP]]
; CHECK:       exit:
; CHECK-NEXT:    [[TMP7:%.*]] = mul i64 [[ADDR_NT_BUF_POST_PHI]], 64
; CHECK-NEXT:    call void @__libirc_nontemporal_store(ptr [[ADDR_NT_STORE_ALLOCA]], i64 [[TMP7]], i32 1)
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %index = phi i64 [ 0, %entry ], [ %index.next, %loop ]
  %index.next = add i64 %index, 1
  %splat = insertelement <8 x i64> zeroinitializer, i64 %index, i32 0
  %addr = getelementptr inbounds <8 x i64>, ptr %dest, i64 %index
  store <8 x i64> %splat, ptr %addr, align 16, !nontemporal !0
  %cond = icmp eq i64 %index, 10000
  br i1 %cond, label %exit, label %loop

exit:
  ret void
}

!0 = !{i32 1}
