; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes="instcombine" < %s -S | FileCheck %s

define dso_local i1 @test_or(float %A0, float %A1, float %A2, float %B0, float %B1, float %B2, float %C0, float %C1, float %C2) local_unnamed_addr {
; CHECK-LABEL: @test_or(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[S0:%.*]] = fsub fast float [[A0:%.*]], [[B0:%.*]]
; CHECK-NEXT:    [[Z0:%.*]] = fmul fast float [[S0]], [[C0:%.*]]
; CHECK-NEXT:    [[S1:%.*]] = fsub fast float [[A1:%.*]], [[B1:%.*]]
; CHECK-NEXT:    [[Z1:%.*]] = fmul fast float [[S1]], [[C1:%.*]]
; CHECK-NEXT:    [[S2:%.*]] = fsub fast float [[A2:%.*]], [[B2:%.*]]
; CHECK-NEXT:    [[Z2:%.*]] = fmul fast float [[S2]], [[C2:%.*]]
; CHECK-NEXT:    [[O0:%.*]] = fcmp fast ole float [[Z0]], [[Z1]]
; CHECK-NEXT:    [[TMP0:%.*]] = select i1 [[O0]], float [[Z0]], float [[Z1]]
; CHECK-NEXT:    [[O1:%.*]] = fcmp fast ole float [[TMP0]], [[Z2]]
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[O1]], float [[TMP0]], float [[Z2]]
; CHECK-NEXT:    [[O2:%.*]] = fcmp fast olt float [[TMP1]], 0.000000e+00
; CHECK-NEXT:    br i1 [[O2]], label [[T:%.*]], label [[F:%.*]]
; CHECK:       t:
; CHECK-NEXT:    ret i1 false
; CHECK:       f:
; CHECK-NEXT:    ret i1 true
;
entry:
  %S0 = fsub fast float %A0, %B0
  %Z0 = fmul fast float %S0, %C0
  %S1 = fsub fast float %A1, %B1
  %Z1 = fmul fast float %S1, %C1
  %S2 = fsub fast float %A2, %B2
  %Z2 = fmul fast float %S2, %C2
  %O0 = fcmp fast olt float %Z0, 0.000000e+00
  %O1 = fcmp fast olt float %Z1, 0.000000e+00
  %OR0 = select i1 %O0, i1 true, i1 %O1
  %O2 = fcmp fast olt float %Z2, 0.000000e+00
  %OR1 = select i1 %OR0, i1 true, i1 %O2
  br i1 %OR1, label %t, label %f
t:
  ret i1 false
f:
  ret i1 true
}

define dso_local i1 @test_and(float %A0, float %A1, float %A2, float %B0, float %B1, float %B2, float %C0, float %C1, float %C2) local_unnamed_addr {
; CHECK-LABEL: @test_and(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[S0:%.*]] = fsub fast float [[A0:%.*]], [[B0:%.*]]
; CHECK-NEXT:    [[Z0:%.*]] = fmul fast float [[S0]], [[C0:%.*]]
; CHECK-NEXT:    [[S1:%.*]] = fsub fast float [[A1:%.*]], [[B1:%.*]]
; CHECK-NEXT:    [[Z1:%.*]] = fmul fast float [[S1]], [[C1:%.*]]
; CHECK-NEXT:    [[S2:%.*]] = fsub fast float [[A2:%.*]], [[B2:%.*]]
; CHECK-NEXT:    [[Z2:%.*]] = fmul fast float [[S2]], [[C2:%.*]]
; CHECK-NEXT:    [[O0:%.*]] = fcmp fast oge float [[Z0]], [[Z1]]
; CHECK-NEXT:    [[TMP0:%.*]] = select i1 [[O0]], float [[Z0]], float [[Z1]]
; CHECK-NEXT:    [[O1:%.*]] = fcmp fast oge float [[TMP0]], [[Z2]]
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[O1]], float [[TMP0]], float [[Z2]]
; CHECK-NEXT:    [[O2:%.*]] = fcmp fast olt float [[TMP1]], 0.000000e+00
; CHECK-NEXT:    br i1 [[O2]], label [[T:%.*]], label [[F:%.*]]
; CHECK:       t:
; CHECK-NEXT:    ret i1 false
; CHECK:       f:
; CHECK-NEXT:    ret i1 true
;
entry:
  %S0 = fsub fast float %A0, %B0
  %Z0 = fmul fast float %S0, %C0
  %S1 = fsub fast float %A1, %B1
  %Z1 = fmul fast float %S1, %C1
  %S2 = fsub fast float %A2, %B2
  %Z2 = fmul fast float %S2, %C2
  %O0 = fcmp fast olt float %Z0, 0.000000e+00
  %O1 = fcmp fast olt float %Z1, 0.000000e+00
  %OR0 = select i1 %O0, i1 %O1, i1 false
  %O2 = fcmp fast olt float %Z2, 0.000000e+00
  %OR1 = select i1 %OR0, i1 %O2, i1 false
  br i1 %OR1, label %t, label %f
t:
  ret i1 false
f:
  ret i1 true
}

