; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: intel_feature_isa_avx_movget
; RUN: llc < %s -O0 -verify-machineinstrs -mtriple=i686-unknown-unknown --show-mc-encoding -mattr=+avx2,+avxmovget | FileCheck %s --check-prefixes=X86
; RUN: llc < %s -O0 -verify-machineinstrs -mtriple=x86_64-unknown-unknown --show-mc-encoding -mattr=+avx2,+avxmovget | FileCheck %s --check-prefixes=X64

define <4 x i32> @test_int_x86_vmovget128(i8* %A) {
; X86-LABEL: test_int_x86_vmovget128:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vmovget (%eax), %xmm0 # encoding: [0xc4,0xe2,0x7a,0xc5,0x00]
; X86-NEXT:    retl # encoding: [0xc3]
;
; X64-LABEL: test_int_x86_vmovget128:
; X64:       # %bb.0:
; X64-NEXT:    vmovget (%rdi), %xmm0 # encoding: [0xc4,0xe2,0x7a,0xc5,0x07]
; X64-NEXT:    retq # encoding: [0xc3]
  %ret = call <4 x i32> @llvm.x86.vmovget128(i8* %A)
  ret <4 x i32> %ret
}
declare <4 x i32> @llvm.x86.vmovget128(i8* %A)

define <8 x i32> @test_int_x86_vmovget256(i8* %A) {
; X86-LABEL: test_int_x86_vmovget256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax # encoding: [0x8b,0x44,0x24,0x04]
; X86-NEXT:    vmovget (%eax), %ymm0 # encoding: [0xc4,0xe2,0x7e,0xc5,0x00]
; X86-NEXT:    retl # encoding: [0xc3]
;
; X64-LABEL: test_int_x86_vmovget256:
; X64:       # %bb.0:
; X64-NEXT:    vmovget (%rdi), %ymm0 # encoding: [0xc4,0xe2,0x7e,0xc5,0x07]
; X64-NEXT:    retq # encoding: [0xc3]
  %ret = call <8 x i32> @llvm.x86.vmovget256(i8* %A)
  ret <8 x i32> %ret
}
declare <8 x i32> @llvm.x86.vmovget256(i8* %A)
