; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; REQUIRES: intel_feature_markercount
; RUN: opt %s -O1 -S -function-marker-count=me -loop-marker-count=me -mtriple=x86_64 -stop-after=markercount-intrinsic-inserter | FileCheck %s

define i32 @g(i1 %cmp) {
; CHECK-LABEL: @g(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    tail call void @llvm.mark.prolog()
; CHECK-NEXT:    br i1 [[CMP:%.*]], label [[LOOP:%.*]], label [[EXIT:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    tail call void @llvm.mark.loop.header()
; CHECK-NEXT:    br label [[LOOP]]
; CHECK:       exit:
; CHECK-NEXT:    tail call void @llvm.mark.epilog()
; CHECK-NEXT:    ret i32 0
;
entry:
  br i1 %cmp, label %loop, label %exit

loop:                                        ; preds = %loop, %entry
  br label %loop

exit:                                         ; preds = %entry
  ret i32 0
}
