; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=x86_64-unknown-linux-gnu %s -o - | FileCheck %s

; Align the top of stack to 16 when has function call in inlineasm.
; If other special alignment required in inlineasm, let user make sure that.

define dso_local void @test_fn() {
; CHECK-LABEL: test_fn:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    #APP
; CHECK-EMPTY:
; CHECK-NEXT:    callq *bar
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
entry:
  tail call void asm sideeffect inteldialect "call qword ptr ${0:P}", "*m,~{dirflag},~{fpsr},~{flags}"(void (...)* nonnull elementtype(void (...)) @bar)
  ret void
}

declare dso_local void @bar(...)
