; INTEL_FEATURE_SW_ADVANCED
; REQUIRES: intel_feature_sw_advanced
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+avx | FileCheck %s --check-prefix=CHECK-NOPINIT
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+x87 -enable-intel-advanced-opts -intel-libirc-allowed -O0 | FileCheck %s --check-prefix=CHECK-NOPINIT
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+x87 -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-X87
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+cmov -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-CMOV
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+mmx -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-MMX
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+sse -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-SSE
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+sse2 -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-SSE2
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+avx -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-AVX
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+avx512f -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-AVX512
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+avx512f -mattr=+cldemote -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-AVX512
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+avx512f -mattr=+sse2 -mattr=+cldemote -mattr=-sse2 -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-AVX512
; RUN: llc < %s -mtriple=x86_64-windows-msvc -mattr=+avx512bw -mattr=+avx512f -mattr=+avx -mattr=+sse2 -mattr=+sse -mattr=+mmx -mattr=+cmov -mattr=+x87 -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-MIX

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"

define dso_local i32 @MAIN__() local_unnamed_addr #0 {
; CHECK-NOPINIT-LABEL: MAIN__:
; CHECK-NOPINIT:       # %bb.0:
; CHECK-NOPINIT-NEXT:    xorl %eax, %eax
; CHECK-NOPINIT-NEXT:    retq
;
; CHECK-PINIT-X87-LABEL: MAIN__:
; CHECK-PINIT-X87:       # %bb.0:
; CHECK-PINIT-X87-NEXT:    subq $40, %rsp
; CHECK-PINIT-X87-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-X87-NEXT:    .seh_endprologue
; CHECK-PINIT-X87-NEXT:    movl $2, %edx
; CHECK-PINIT-X87-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-X87-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-X87-NEXT:    xorl %eax, %eax
; CHECK-PINIT-X87-NEXT:    addq $40, %rsp
; CHECK-PINIT-X87-NEXT:    retq
; CHECK-PINIT-X87-NEXT:    .seh_endproc
;
; CHECK-PINIT-CMOV-LABEL: MAIN__:
; CHECK-PINIT-CMOV:       # %bb.0:
; CHECK-PINIT-CMOV-NEXT:    subq $40, %rsp
; CHECK-PINIT-CMOV-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-CMOV-NEXT:    .seh_endprologue
; CHECK-PINIT-CMOV-NEXT:    movl $4, %edx
; CHECK-PINIT-CMOV-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-CMOV-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-CMOV-NEXT:    xorl %eax, %eax
; CHECK-PINIT-CMOV-NEXT:    addq $40, %rsp
; CHECK-PINIT-CMOV-NEXT:    retq
; CHECK-PINIT-CMOV-NEXT:    .seh_endproc
;
; CHECK-PINIT-MMX-LABEL: MAIN__:
; CHECK-PINIT-MMX:       # %bb.0:
; CHECK-PINIT-MMX-NEXT:    subq $40, %rsp
; CHECK-PINIT-MMX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-MMX-NEXT:    .seh_endprologue
; CHECK-PINIT-MMX-NEXT:    movl $8, %edx
; CHECK-PINIT-MMX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-MMX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MMX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MMX-NEXT:    addq $40, %rsp
; CHECK-PINIT-MMX-NEXT:    retq
; CHECK-PINIT-MMX-NEXT:    .seh_endproc
;
; CHECK-PINIT-SSE-LABEL: MAIN__:
; CHECK-PINIT-SSE:       # %bb.0:
; CHECK-PINIT-SSE-NEXT:    subq $40, %rsp
; CHECK-PINIT-SSE-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-SSE-NEXT:    .seh_endprologue
; CHECK-PINIT-SSE-NEXT:    movl $32, %edx
; CHECK-PINIT-SSE-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-SSE-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE-NEXT:    addq $40, %rsp
; CHECK-PINIT-SSE-NEXT:    retq
; CHECK-PINIT-SSE-NEXT:    .seh_endproc
;
; CHECK-PINIT-SSE2-LABEL: MAIN__:
; CHECK-PINIT-SSE2:       # %bb.0:
; CHECK-PINIT-SSE2-NEXT:    subq $40, %rsp
; CHECK-PINIT-SSE2-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-SSE2-NEXT:    .seh_endprologue
; CHECK-PINIT-SSE2-NEXT:    movl $64, %edx
; CHECK-PINIT-SSE2-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-SSE2-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE2-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE2-NEXT:    addq $40, %rsp
; CHECK-PINIT-SSE2-NEXT:    retq
; CHECK-PINIT-SSE2-NEXT:    .seh_endproc
;
; CHECK-PINIT-AVX-LABEL: MAIN__:
; CHECK-PINIT-AVX:       # %bb.0:
; CHECK-PINIT-AVX-NEXT:    subq $40, %rsp
; CHECK-PINIT-AVX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-AVX-NEXT:    .seh_endprologue
; CHECK-PINIT-AVX-NEXT:    movl $65536, %edx # imm = 0x10000
; CHECK-PINIT-AVX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-AVX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX-NEXT:    addq $40, %rsp
; CHECK-PINIT-AVX-NEXT:    retq
; CHECK-PINIT-AVX-NEXT:    .seh_endproc
;
; CHECK-PINIT-AVX512-LABEL: MAIN__:
; CHECK-PINIT-AVX512:       # %bb.0:
; CHECK-PINIT-AVX512-NEXT:    subq $40, %rsp
; CHECK-PINIT-AVX512-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-AVX512-NEXT:    .seh_endprologue
; CHECK-PINIT-AVX512-NEXT:    movl $134217728, %edx # imm = 0x8000000
; CHECK-PINIT-AVX512-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-AVX512-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX512-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX512-NEXT:    addq $40, %rsp
; CHECK-PINIT-AVX512-NEXT:    retq
; CHECK-PINIT-AVX512-NEXT:    .seh_endproc
;
; CHECK-PINIT-MIX-LABEL: MAIN__:
; CHECK-PINIT-MIX:       # %bb.0:
; CHECK-PINIT-MIX-NEXT:    subq $40, %rsp
; CHECK-PINIT-MIX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-MIX-NEXT:    .seh_endprologue
; CHECK-PINIT-MIX-NEXT:    movabsq $137573236846, %rdx # imm = 0x200801006E
; CHECK-PINIT-MIX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-MIX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MIX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MIX-NEXT:    addq $40, %rsp
; CHECK-PINIT-MIX-NEXT:    retq
; CHECK-PINIT-MIX-NEXT:    .seh_endproc
  ret i32 0
}

define dso_local i32 @main() local_unnamed_addr #0 {
; CHECK-NOPINIT-LABEL: main:
; CHECK-NOPINIT:       # %bb.0:
; CHECK-NOPINIT-NEXT:    xorl %eax, %eax
; CHECK-NOPINIT-NEXT:    retq
;
; CHECK-PINIT-X87-LABEL: main:
; CHECK-PINIT-X87:       # %bb.0:
; CHECK-PINIT-X87-NEXT:    subq $40, %rsp
; CHECK-PINIT-X87-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-X87-NEXT:    .seh_endprologue
; CHECK-PINIT-X87-NEXT:    movl $2, %edx
; CHECK-PINIT-X87-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-X87-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-X87-NEXT:    xorl %eax, %eax
; CHECK-PINIT-X87-NEXT:    addq $40, %rsp
; CHECK-PINIT-X87-NEXT:    retq
; CHECK-PINIT-X87-NEXT:    .seh_endproc
;
; CHECK-PINIT-CMOV-LABEL: main:
; CHECK-PINIT-CMOV:       # %bb.0:
; CHECK-PINIT-CMOV-NEXT:    subq $40, %rsp
; CHECK-PINIT-CMOV-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-CMOV-NEXT:    .seh_endprologue
; CHECK-PINIT-CMOV-NEXT:    movl $4, %edx
; CHECK-PINIT-CMOV-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-CMOV-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-CMOV-NEXT:    xorl %eax, %eax
; CHECK-PINIT-CMOV-NEXT:    addq $40, %rsp
; CHECK-PINIT-CMOV-NEXT:    retq
; CHECK-PINIT-CMOV-NEXT:    .seh_endproc
;
; CHECK-PINIT-MMX-LABEL: main:
; CHECK-PINIT-MMX:       # %bb.0:
; CHECK-PINIT-MMX-NEXT:    subq $40, %rsp
; CHECK-PINIT-MMX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-MMX-NEXT:    .seh_endprologue
; CHECK-PINIT-MMX-NEXT:    movl $8, %edx
; CHECK-PINIT-MMX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-MMX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MMX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MMX-NEXT:    addq $40, %rsp
; CHECK-PINIT-MMX-NEXT:    retq
; CHECK-PINIT-MMX-NEXT:    .seh_endproc
;
; CHECK-PINIT-SSE-LABEL: main:
; CHECK-PINIT-SSE:       # %bb.0:
; CHECK-PINIT-SSE-NEXT:    subq $40, %rsp
; CHECK-PINIT-SSE-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-SSE-NEXT:    .seh_endprologue
; CHECK-PINIT-SSE-NEXT:    movl $32, %edx
; CHECK-PINIT-SSE-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-SSE-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE-NEXT:    addq $40, %rsp
; CHECK-PINIT-SSE-NEXT:    retq
; CHECK-PINIT-SSE-NEXT:    .seh_endproc
;
; CHECK-PINIT-SSE2-LABEL: main:
; CHECK-PINIT-SSE2:       # %bb.0:
; CHECK-PINIT-SSE2-NEXT:    subq $40, %rsp
; CHECK-PINIT-SSE2-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-SSE2-NEXT:    .seh_endprologue
; CHECK-PINIT-SSE2-NEXT:    movl $64, %edx
; CHECK-PINIT-SSE2-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-SSE2-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE2-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE2-NEXT:    addq $40, %rsp
; CHECK-PINIT-SSE2-NEXT:    retq
; CHECK-PINIT-SSE2-NEXT:    .seh_endproc
;
; CHECK-PINIT-AVX-LABEL: main:
; CHECK-PINIT-AVX:       # %bb.0:
; CHECK-PINIT-AVX-NEXT:    subq $40, %rsp
; CHECK-PINIT-AVX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-AVX-NEXT:    .seh_endprologue
; CHECK-PINIT-AVX-NEXT:    movl $65536, %edx # imm = 0x10000
; CHECK-PINIT-AVX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-AVX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX-NEXT:    addq $40, %rsp
; CHECK-PINIT-AVX-NEXT:    retq
; CHECK-PINIT-AVX-NEXT:    .seh_endproc
;
; CHECK-PINIT-AVX512-LABEL: main:
; CHECK-PINIT-AVX512:       # %bb.0:
; CHECK-PINIT-AVX512-NEXT:    subq $40, %rsp
; CHECK-PINIT-AVX512-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-AVX512-NEXT:    .seh_endprologue
; CHECK-PINIT-AVX512-NEXT:    movl $134217728, %edx # imm = 0x8000000
; CHECK-PINIT-AVX512-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-AVX512-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX512-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX512-NEXT:    addq $40, %rsp
; CHECK-PINIT-AVX512-NEXT:    retq
; CHECK-PINIT-AVX512-NEXT:    .seh_endproc
;
; CHECK-PINIT-MIX-LABEL: main:
; CHECK-PINIT-MIX:       # %bb.0:
; CHECK-PINIT-MIX-NEXT:    subq $40, %rsp
; CHECK-PINIT-MIX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-MIX-NEXT:    .seh_endprologue
; CHECK-PINIT-MIX-NEXT:    movabsq $137573236846, %rdx # imm = 0x200801006E
; CHECK-PINIT-MIX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-MIX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MIX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MIX-NEXT:    addq $40, %rsp
; CHECK-PINIT-MIX-NEXT:    retq
; CHECK-PINIT-MIX-NEXT:    .seh_endproc
  ret i32 0
}

define dso_local i32 @wmain() local_unnamed_addr #0 {
; CHECK-NOPINIT-LABEL: wmain:
; CHECK-NOPINIT:       # %bb.0:
; CHECK-NOPINIT-NEXT:    xorl %eax, %eax
; CHECK-NOPINIT-NEXT:    retq
;
; CHECK-PINIT-X87-LABEL: wmain:
; CHECK-PINIT-X87:       # %bb.0:
; CHECK-PINIT-X87-NEXT:    subq $40, %rsp
; CHECK-PINIT-X87-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-X87-NEXT:    .seh_endprologue
; CHECK-PINIT-X87-NEXT:    movl $2, %edx
; CHECK-PINIT-X87-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-X87-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-X87-NEXT:    xorl %eax, %eax
; CHECK-PINIT-X87-NEXT:    addq $40, %rsp
; CHECK-PINIT-X87-NEXT:    retq
; CHECK-PINIT-X87-NEXT:    .seh_endproc
;
; CHECK-PINIT-CMOV-LABEL: wmain:
; CHECK-PINIT-CMOV:       # %bb.0:
; CHECK-PINIT-CMOV-NEXT:    subq $40, %rsp
; CHECK-PINIT-CMOV-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-CMOV-NEXT:    .seh_endprologue
; CHECK-PINIT-CMOV-NEXT:    movl $4, %edx
; CHECK-PINIT-CMOV-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-CMOV-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-CMOV-NEXT:    xorl %eax, %eax
; CHECK-PINIT-CMOV-NEXT:    addq $40, %rsp
; CHECK-PINIT-CMOV-NEXT:    retq
; CHECK-PINIT-CMOV-NEXT:    .seh_endproc
;
; CHECK-PINIT-MMX-LABEL: wmain:
; CHECK-PINIT-MMX:       # %bb.0:
; CHECK-PINIT-MMX-NEXT:    subq $40, %rsp
; CHECK-PINIT-MMX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-MMX-NEXT:    .seh_endprologue
; CHECK-PINIT-MMX-NEXT:    movl $8, %edx
; CHECK-PINIT-MMX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-MMX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MMX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MMX-NEXT:    addq $40, %rsp
; CHECK-PINIT-MMX-NEXT:    retq
; CHECK-PINIT-MMX-NEXT:    .seh_endproc
;
; CHECK-PINIT-SSE-LABEL: wmain:
; CHECK-PINIT-SSE:       # %bb.0:
; CHECK-PINIT-SSE-NEXT:    subq $40, %rsp
; CHECK-PINIT-SSE-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-SSE-NEXT:    .seh_endprologue
; CHECK-PINIT-SSE-NEXT:    movl $32, %edx
; CHECK-PINIT-SSE-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-SSE-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE-NEXT:    addq $40, %rsp
; CHECK-PINIT-SSE-NEXT:    retq
; CHECK-PINIT-SSE-NEXT:    .seh_endproc
;
; CHECK-PINIT-SSE2-LABEL: wmain:
; CHECK-PINIT-SSE2:       # %bb.0:
; CHECK-PINIT-SSE2-NEXT:    subq $40, %rsp
; CHECK-PINIT-SSE2-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-SSE2-NEXT:    .seh_endprologue
; CHECK-PINIT-SSE2-NEXT:    movl $64, %edx
; CHECK-PINIT-SSE2-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-SSE2-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE2-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE2-NEXT:    addq $40, %rsp
; CHECK-PINIT-SSE2-NEXT:    retq
; CHECK-PINIT-SSE2-NEXT:    .seh_endproc
;
; CHECK-PINIT-AVX-LABEL: wmain:
; CHECK-PINIT-AVX:       # %bb.0:
; CHECK-PINIT-AVX-NEXT:    subq $40, %rsp
; CHECK-PINIT-AVX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-AVX-NEXT:    .seh_endprologue
; CHECK-PINIT-AVX-NEXT:    movl $65536, %edx # imm = 0x10000
; CHECK-PINIT-AVX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-AVX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX-NEXT:    addq $40, %rsp
; CHECK-PINIT-AVX-NEXT:    retq
; CHECK-PINIT-AVX-NEXT:    .seh_endproc
;
; CHECK-PINIT-AVX512-LABEL: wmain:
; CHECK-PINIT-AVX512:       # %bb.0:
; CHECK-PINIT-AVX512-NEXT:    subq $40, %rsp
; CHECK-PINIT-AVX512-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-AVX512-NEXT:    .seh_endprologue
; CHECK-PINIT-AVX512-NEXT:    movl $134217728, %edx # imm = 0x8000000
; CHECK-PINIT-AVX512-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-AVX512-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX512-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX512-NEXT:    addq $40, %rsp
; CHECK-PINIT-AVX512-NEXT:    retq
; CHECK-PINIT-AVX512-NEXT:    .seh_endproc
;
; CHECK-PINIT-MIX-LABEL: wmain:
; CHECK-PINIT-MIX:       # %bb.0:
; CHECK-PINIT-MIX-NEXT:    subq $40, %rsp
; CHECK-PINIT-MIX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-MIX-NEXT:    .seh_endprologue
; CHECK-PINIT-MIX-NEXT:    movabsq $137573236846, %rdx # imm = 0x200801006E
; CHECK-PINIT-MIX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-MIX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MIX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MIX-NEXT:    addq $40, %rsp
; CHECK-PINIT-MIX-NEXT:    retq
; CHECK-PINIT-MIX-NEXT:    .seh_endproc
  ret i32 0
}

define dso_local i32 @WinMain() local_unnamed_addr #0 {
; CHECK-NOPINIT-LABEL: WinMain:
; CHECK-NOPINIT:       # %bb.0:
; CHECK-NOPINIT-NEXT:    xorl %eax, %eax
; CHECK-NOPINIT-NEXT:    retq
;
; CHECK-PINIT-X87-LABEL: WinMain:
; CHECK-PINIT-X87:       # %bb.0:
; CHECK-PINIT-X87-NEXT:    subq $40, %rsp
; CHECK-PINIT-X87-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-X87-NEXT:    .seh_endprologue
; CHECK-PINIT-X87-NEXT:    movl $2, %edx
; CHECK-PINIT-X87-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-X87-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-X87-NEXT:    xorl %eax, %eax
; CHECK-PINIT-X87-NEXT:    addq $40, %rsp
; CHECK-PINIT-X87-NEXT:    retq
; CHECK-PINIT-X87-NEXT:    .seh_endproc
;
; CHECK-PINIT-CMOV-LABEL: WinMain:
; CHECK-PINIT-CMOV:       # %bb.0:
; CHECK-PINIT-CMOV-NEXT:    subq $40, %rsp
; CHECK-PINIT-CMOV-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-CMOV-NEXT:    .seh_endprologue
; CHECK-PINIT-CMOV-NEXT:    movl $4, %edx
; CHECK-PINIT-CMOV-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-CMOV-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-CMOV-NEXT:    xorl %eax, %eax
; CHECK-PINIT-CMOV-NEXT:    addq $40, %rsp
; CHECK-PINIT-CMOV-NEXT:    retq
; CHECK-PINIT-CMOV-NEXT:    .seh_endproc
;
; CHECK-PINIT-MMX-LABEL: WinMain:
; CHECK-PINIT-MMX:       # %bb.0:
; CHECK-PINIT-MMX-NEXT:    subq $40, %rsp
; CHECK-PINIT-MMX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-MMX-NEXT:    .seh_endprologue
; CHECK-PINIT-MMX-NEXT:    movl $8, %edx
; CHECK-PINIT-MMX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-MMX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MMX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MMX-NEXT:    addq $40, %rsp
; CHECK-PINIT-MMX-NEXT:    retq
; CHECK-PINIT-MMX-NEXT:    .seh_endproc
;
; CHECK-PINIT-SSE-LABEL: WinMain:
; CHECK-PINIT-SSE:       # %bb.0:
; CHECK-PINIT-SSE-NEXT:    subq $40, %rsp
; CHECK-PINIT-SSE-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-SSE-NEXT:    .seh_endprologue
; CHECK-PINIT-SSE-NEXT:    movl $32, %edx
; CHECK-PINIT-SSE-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-SSE-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE-NEXT:    addq $40, %rsp
; CHECK-PINIT-SSE-NEXT:    retq
; CHECK-PINIT-SSE-NEXT:    .seh_endproc
;
; CHECK-PINIT-SSE2-LABEL: WinMain:
; CHECK-PINIT-SSE2:       # %bb.0:
; CHECK-PINIT-SSE2-NEXT:    subq $40, %rsp
; CHECK-PINIT-SSE2-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-SSE2-NEXT:    .seh_endprologue
; CHECK-PINIT-SSE2-NEXT:    movl $64, %edx
; CHECK-PINIT-SSE2-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-SSE2-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE2-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE2-NEXT:    addq $40, %rsp
; CHECK-PINIT-SSE2-NEXT:    retq
; CHECK-PINIT-SSE2-NEXT:    .seh_endproc
;
; CHECK-PINIT-AVX-LABEL: WinMain:
; CHECK-PINIT-AVX:       # %bb.0:
; CHECK-PINIT-AVX-NEXT:    subq $40, %rsp
; CHECK-PINIT-AVX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-AVX-NEXT:    .seh_endprologue
; CHECK-PINIT-AVX-NEXT:    movl $65536, %edx # imm = 0x10000
; CHECK-PINIT-AVX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-AVX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX-NEXT:    addq $40, %rsp
; CHECK-PINIT-AVX-NEXT:    retq
; CHECK-PINIT-AVX-NEXT:    .seh_endproc
;
; CHECK-PINIT-AVX512-LABEL: WinMain:
; CHECK-PINIT-AVX512:       # %bb.0:
; CHECK-PINIT-AVX512-NEXT:    subq $40, %rsp
; CHECK-PINIT-AVX512-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-AVX512-NEXT:    .seh_endprologue
; CHECK-PINIT-AVX512-NEXT:    movl $134217728, %edx # imm = 0x8000000
; CHECK-PINIT-AVX512-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-AVX512-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX512-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX512-NEXT:    addq $40, %rsp
; CHECK-PINIT-AVX512-NEXT:    retq
; CHECK-PINIT-AVX512-NEXT:    .seh_endproc
;
; CHECK-PINIT-MIX-LABEL: WinMain:
; CHECK-PINIT-MIX:       # %bb.0:
; CHECK-PINIT-MIX-NEXT:    subq $40, %rsp
; CHECK-PINIT-MIX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-MIX-NEXT:    .seh_endprologue
; CHECK-PINIT-MIX-NEXT:    movabsq $137573236846, %rdx # imm = 0x200801006E
; CHECK-PINIT-MIX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-MIX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MIX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MIX-NEXT:    addq $40, %rsp
; CHECK-PINIT-MIX-NEXT:    retq
; CHECK-PINIT-MIX-NEXT:    .seh_endproc
  ret i32 0
}

define dso_local i32 @wWinMain() local_unnamed_addr #0 {
; CHECK-NOPINIT-LABEL: wWinMain:
; CHECK-NOPINIT:       # %bb.0:
; CHECK-NOPINIT-NEXT:    xorl %eax, %eax
; CHECK-NOPINIT-NEXT:    retq
;
; CHECK-PINIT-X87-LABEL: wWinMain:
; CHECK-PINIT-X87:       # %bb.0:
; CHECK-PINIT-X87-NEXT:    subq $40, %rsp
; CHECK-PINIT-X87-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-X87-NEXT:    .seh_endprologue
; CHECK-PINIT-X87-NEXT:    movl $2, %edx
; CHECK-PINIT-X87-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-X87-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-X87-NEXT:    xorl %eax, %eax
; CHECK-PINIT-X87-NEXT:    addq $40, %rsp
; CHECK-PINIT-X87-NEXT:    retq
; CHECK-PINIT-X87-NEXT:    .seh_endproc
;
; CHECK-PINIT-CMOV-LABEL: wWinMain:
; CHECK-PINIT-CMOV:       # %bb.0:
; CHECK-PINIT-CMOV-NEXT:    subq $40, %rsp
; CHECK-PINIT-CMOV-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-CMOV-NEXT:    .seh_endprologue
; CHECK-PINIT-CMOV-NEXT:    movl $4, %edx
; CHECK-PINIT-CMOV-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-CMOV-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-CMOV-NEXT:    xorl %eax, %eax
; CHECK-PINIT-CMOV-NEXT:    addq $40, %rsp
; CHECK-PINIT-CMOV-NEXT:    retq
; CHECK-PINIT-CMOV-NEXT:    .seh_endproc
;
; CHECK-PINIT-MMX-LABEL: wWinMain:
; CHECK-PINIT-MMX:       # %bb.0:
; CHECK-PINIT-MMX-NEXT:    subq $40, %rsp
; CHECK-PINIT-MMX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-MMX-NEXT:    .seh_endprologue
; CHECK-PINIT-MMX-NEXT:    movl $8, %edx
; CHECK-PINIT-MMX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-MMX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MMX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MMX-NEXT:    addq $40, %rsp
; CHECK-PINIT-MMX-NEXT:    retq
; CHECK-PINIT-MMX-NEXT:    .seh_endproc
;
; CHECK-PINIT-SSE-LABEL: wWinMain:
; CHECK-PINIT-SSE:       # %bb.0:
; CHECK-PINIT-SSE-NEXT:    subq $40, %rsp
; CHECK-PINIT-SSE-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-SSE-NEXT:    .seh_endprologue
; CHECK-PINIT-SSE-NEXT:    movl $32, %edx
; CHECK-PINIT-SSE-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-SSE-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE-NEXT:    addq $40, %rsp
; CHECK-PINIT-SSE-NEXT:    retq
; CHECK-PINIT-SSE-NEXT:    .seh_endproc
;
; CHECK-PINIT-SSE2-LABEL: wWinMain:
; CHECK-PINIT-SSE2:       # %bb.0:
; CHECK-PINIT-SSE2-NEXT:    subq $40, %rsp
; CHECK-PINIT-SSE2-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-SSE2-NEXT:    .seh_endprologue
; CHECK-PINIT-SSE2-NEXT:    movl $64, %edx
; CHECK-PINIT-SSE2-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-SSE2-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE2-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE2-NEXT:    addq $40, %rsp
; CHECK-PINIT-SSE2-NEXT:    retq
; CHECK-PINIT-SSE2-NEXT:    .seh_endproc
;
; CHECK-PINIT-AVX-LABEL: wWinMain:
; CHECK-PINIT-AVX:       # %bb.0:
; CHECK-PINIT-AVX-NEXT:    subq $40, %rsp
; CHECK-PINIT-AVX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-AVX-NEXT:    .seh_endprologue
; CHECK-PINIT-AVX-NEXT:    movl $65536, %edx # imm = 0x10000
; CHECK-PINIT-AVX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-AVX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX-NEXT:    addq $40, %rsp
; CHECK-PINIT-AVX-NEXT:    retq
; CHECK-PINIT-AVX-NEXT:    .seh_endproc
;
; CHECK-PINIT-AVX512-LABEL: wWinMain:
; CHECK-PINIT-AVX512:       # %bb.0:
; CHECK-PINIT-AVX512-NEXT:    subq $40, %rsp
; CHECK-PINIT-AVX512-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-AVX512-NEXT:    .seh_endprologue
; CHECK-PINIT-AVX512-NEXT:    movl $134217728, %edx # imm = 0x8000000
; CHECK-PINIT-AVX512-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-AVX512-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX512-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX512-NEXT:    addq $40, %rsp
; CHECK-PINIT-AVX512-NEXT:    retq
; CHECK-PINIT-AVX512-NEXT:    .seh_endproc
;
; CHECK-PINIT-MIX-LABEL: wWinMain:
; CHECK-PINIT-MIX:       # %bb.0:
; CHECK-PINIT-MIX-NEXT:    subq $40, %rsp
; CHECK-PINIT-MIX-NEXT:    .seh_stackalloc 40
; CHECK-PINIT-MIX-NEXT:    .seh_endprologue
; CHECK-PINIT-MIX-NEXT:    movabsq $137573236846, %rdx # imm = 0x200801006E
; CHECK-PINIT-MIX-NEXT:    xorl %ecx, %ecx
; CHECK-PINIT-MIX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MIX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MIX-NEXT:    addq $40, %rsp
; CHECK-PINIT-MIX-NEXT:    retq
; CHECK-PINIT-MIX-NEXT:    .seh_endproc
  ret i32 0
}
attributes #0 = { norecurse nounwind readnone uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"icx (ICX) dev.8.x.0"}
; end INTEL_FEATURE_SW_ADVANCED
