; INTEL_FEATURE_SW_ADVANCED
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: intel_feature_sw_advanced
; RUN: llc -mtriple=x86_64-- < %s | FileCheck %s --check-prefixes=CHECK,NO-PC80
; RUN: llc -mtriple=x86_64-- < %s -x87-precision=80 | FileCheck %s --check-prefixes=CHECK,PC80
; RUN: llc -mtriple=x86_64-- -O0 < %s -x87-precision=80 | FileCheck %s --check-prefixes=CHECK,PC80

define i32 @main() #0 {
; NO-PC80-LABEL: main:
; NO-PC80:       # %bb.0:
; NO-PC80-NEXT:    movw $4735, -{{[0-9]+}}(%rsp) # imm = 0x127F
; NO-PC80-NEXT:    #APP
; NO-PC80-NEXT:    fldcw -{{[0-9]+}}(%rsp)
; NO-PC80-NEXT:    #NO_APP
; NO-PC80-NEXT:    xorl %eax, %eax
; NO-PC80-NEXT:    retq
;
; PC80-LABEL: main:
; PC80:       # %bb.0:
; PC80-NEXT:    movw $4991, -{{[0-9]+}}(%rsp) # imm = 0x137F
; PC80-NEXT:    #APP
; PC80-NEXT:    fldcw -{{[0-9]+}}(%rsp)
; PC80-NEXT:    #NO_APP
; PC80-NEXT:    xorl %eax, %eax
; PC80-NEXT:    retq
  ret i32 0
}

define i32 @foo() #1 {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    retq
  ret i32 0
}

attributes #0 = { "x87-precision"="64" }
attributes #1 = { "x87-precision"="32" }
; end INTEL_FEATURE_SW_ADVANCED
