; INTEL_FEATURE_ISA_BF16_BASE
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: intel_feature_isa_bf16_base
; TODO: Add SSE2 tests when vector emulation bfloat on SSE2 is supported.
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512fp16,+avx512vl | FileCheck %s --check-prefix=AVX512FP16

define <8 x bfloat> @extract_v16bf16_v8bf16_0(<16 x bfloat> %x) {
; AVX512FP16-LABEL: extract_v16bf16_v8bf16_0:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512FP16-NEXT:    vzeroupper
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <16 x bfloat> %x, <16 x bfloat> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x bfloat> %a
}

define <8 x bfloat> @extract_v16bf16_v8bf16_1(<16 x bfloat> %x) {
; AVX512FP16-LABEL: extract_v16bf16_v8bf16_1:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512FP16-NEXT:    vzeroupper
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <16 x bfloat> %x, <16 x bfloat> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <8 x bfloat> %a
}

define <8 x bfloat> @extract_v32bf16_v8bf16_0(<32 x bfloat> %x) {
; AVX512FP16-LABEL: extract_v32bf16_v8bf16_0:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    # kill: def $xmm0 killed $xmm0 killed $zmm0
; AVX512FP16-NEXT:    vzeroupper
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <32 x bfloat> %x, <32 x bfloat> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x bfloat> %a
}

define <8 x bfloat> @extract_v32bf16_v8bf16_1(<32 x bfloat> %x) {
; AVX512FP16-LABEL: extract_v32bf16_v8bf16_1:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512FP16-NEXT:    vzeroupper
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <32 x bfloat> %x, <32 x bfloat> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <8 x bfloat> %a
}

define <8 x bfloat> @extract_v32bf16_v8bf16_2(<32 x bfloat> %x) {
; AVX512FP16-LABEL: extract_v32bf16_v8bf16_2:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    vextractf32x4 $2, %zmm0, %xmm0
; AVX512FP16-NEXT:    vzeroupper
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <32 x bfloat> %x, <32 x bfloat> undef, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
  ret <8 x bfloat> %a
}

define <8 x bfloat> @extract_v32bf16_v8bf16_3(<32 x bfloat> %x) {
; AVX512FP16-LABEL: extract_v32bf16_v8bf16_3:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    vextractf32x4 $3, %zmm0, %xmm0
; AVX512FP16-NEXT:    vzeroupper
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <32 x bfloat> %x, <32 x bfloat> undef, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <8 x bfloat> %a
}

define <16 x bfloat> @extract_v32bf16_v81616_0(<32 x bfloat> %x) {
; AVX512FP16-LABEL: extract_v32bf16_v81616_0:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    # kill: def $ymm0 killed $ymm0 killed $zmm0
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <32 x bfloat> %x, <32 x bfloat> undef, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x bfloat> %a
}

define <16 x bfloat> @extract_v32bf16_v81616_1(<32 x bfloat> %x) {
; AVX512FP16-LABEL: extract_v32bf16_v81616_1:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    vextractf64x4 $1, %zmm0, %ymm0
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <32 x bfloat> %x, <32 x bfloat> undef, <16 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <16 x bfloat> %a
}

define <16 x bfloat> @concat_v8bf16(<8 x bfloat> %x, <8 x bfloat> %y) {
; AVX512FP16-LABEL: concat_v8bf16:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    # kill: def $xmm0 killed $xmm0 def $ymm0
; AVX512FP16-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <8 x bfloat> %x, <8 x bfloat> %y, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x bfloat> %a
}

define <32 x bfloat> @concat_v16bf16(<16 x bfloat> %x, <16 x bfloat> %y) {
; AVX512FP16-LABEL: concat_v16bf16:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    # kill: def $ymm0 killed $ymm0 def $zmm0
; AVX512FP16-NEXT:    vinsertf64x4 $1, %ymm1, %zmm0, %zmm0
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <16 x bfloat> %x, <16 x bfloat> %y, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <32 x bfloat> %a
}

define <16 x bfloat> @concat_zero_v8bf16(<8 x bfloat> %x, <8 x bfloat> %y) {
; AVX512FP16-LABEL: concat_zero_v8bf16:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    vmovaps %xmm0, %xmm0
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <8 x bfloat> %x, <8 x bfloat> zeroinitializer, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x bfloat> %a
}

define <32 x bfloat> @concat_zero_v16bf16(<16 x bfloat> %x, <16 x bfloat> %y) {
; AVX512FP16-LABEL: concat_zero_v16bf16:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    vmovaps %ymm0, %ymm0
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <16 x bfloat> %x, <16 x bfloat> zeroinitializer, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <32 x bfloat> %a
}

define <32 x bfloat> @insert_v8bf16_v32bf16_0(<32 x bfloat> %x, <8 x bfloat> %y) {
; AVX512FP16-LABEL: insert_v8bf16_v32bf16_0:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    vinsertf32x4 $0, %xmm1, %zmm0, %zmm0
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <8 x bfloat> %y, <8 x bfloat> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %b = shufflevector <32 x bfloat> %x, <32 x bfloat> %a, <32 x i32> <i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <32 x bfloat> %b
}

define <32 x bfloat> @insert_v8bf16_v32bf16_1(<32 x bfloat> %x, <8 x bfloat> %y) {
; AVX512FP16-LABEL: insert_v8bf16_v32bf16_1:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    vinsertf32x4 $1, %xmm1, %zmm0, %zmm0
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <8 x bfloat> %y, <8 x bfloat> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %b = shufflevector <32 x bfloat> %x, <32 x bfloat> %a, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <32 x bfloat> %b
}

define <32 x bfloat> @insert_v8bf16_v32bf16_2(<32 x bfloat> %x, <8 x bfloat> %y) {
; AVX512FP16-LABEL: insert_v8bf16_v32bf16_2:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    vinsertf32x4 $2, %xmm1, %zmm0, %zmm0
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <8 x bfloat> %y, <8 x bfloat> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %b = shufflevector <32 x bfloat> %x, <32 x bfloat> %a, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <32 x bfloat> %b
}

define <32 x bfloat> @insert_v8bf16_v32bf16_3(<32 x bfloat> %x, <8 x bfloat> %y) {
; AVX512FP16-LABEL: insert_v8bf16_v32bf16_3:
; AVX512FP16:       # %bb.0:
; AVX512FP16-NEXT:    vinsertf32x4 $3, %xmm1, %zmm0, %zmm0
; AVX512FP16-NEXT:    ret{{[l|q]}}
  %a = shufflevector <8 x bfloat> %y, <8 x bfloat> undef, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %b = shufflevector <32 x bfloat> %x, <32 x bfloat> %a, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39>
  ret <32 x bfloat> %b
}
; end INTEL_FEATURE_ISA_BF16_BASE
