; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=avx512vl,avx512bw,avx512dq -enable-intel-advanced-opts | FileCheck %s

define <8 x i32> @x264_pixel_satd_8x4(i8* %pix1, i32 %i_pix1, i8* %pix2, i32 %i_pix2) {
; CHECK-LABEL: x264_pixel_satd_8x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movslq %esi, %rax
; CHECK-NEXT:    movslq %ecx, %rcx
; CHECK-NEXT:    vmovq {{.*#+}} xmm0 = mem[0],zero
; CHECK-NEXT:    vmovq {{.*#+}} xmm1 = mem[0],zero
; CHECK-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; CHECK-NEXT:    vmovdqa {{.*#+}} xmm1 = [0,4,1,5,2,6,3,7,8,12,9,13,10,14,11,15]
; CHECK-NEXT:    vpshufb %xmm1, %xmm0, %xmm0
; CHECK-NEXT:    vpmovzxbw {{.*#+}} ymm0 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero,xmm0[8],zero,xmm0[9],zero,xmm0[10],zero,xmm0[11],zero,xmm0[12],zero,xmm0[13],zero,xmm0[14],zero,xmm0[15],zero
; CHECK-NEXT:    vmovq {{.*#+}} xmm2 = mem[0],zero
; CHECK-NEXT:    vmovq {{.*#+}} xmm3 = mem[0],zero
; CHECK-NEXT:    vpunpcklqdq {{.*#+}} xmm2 = xmm3[0],xmm2[0]
; CHECK-NEXT:    vpshufb %xmm1, %xmm2, %xmm1
; CHECK-NEXT:    vpmovzxbw {{.*#+}} ymm1 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero,xmm1[8],zero,xmm1[9],zero,xmm1[10],zero,xmm1[11],zero,xmm1[12],zero,xmm1[13],zero,xmm1[14],zero,xmm1[15],zero
; CHECK-NEXT:    vpsubd %ymm0, %ymm1, %ymm0
; CHECK-NEXT:    retq
entry:
  %idx.ext = sext i32 %i_pix1 to i64
  %idx.ext63 = sext i32 %i_pix2 to i64
  %add.ptr = getelementptr inbounds i8, i8* %pix1, i64 %idx.ext
  %add.ptr64 = getelementptr inbounds i8, i8* %pix2, i64 %idx.ext63
  %0 = bitcast i8* %pix1 to <8 x i8>*
  %1 = load <8 x i8>, <8 x i8>* %0, align 1
  %LoadCoalescingShuffle_ = shufflevector <8 x i8> %1, <8 x i8> undef, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %2 = bitcast i8* %add.ptr to <8 x i8>*
  %3 = bitcast i8* %pix2 to <8 x i8>*
  %4 = load <8 x i8>, <8 x i8>* %2, align 1
  %5 = load <8 x i8>, <8 x i8>* %3, align 1
  %LoadCoalescingShuffle_164 = shufflevector <8 x i8> %4, <8 x i8> undef, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %LoadCoalescingShuffle_166 = shufflevector <8 x i8> %5, <8 x i8> undef, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %LoadCoalescingShuffle_165 = shufflevector <8 x i8> %4, <8 x i8> undef, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %LoadCoalescingShuffle_163 = shufflevector <8 x i8> %1, <8 x i8> undef, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %SplitLoadShuffle125 = shufflevector <4 x i8> %LoadCoalescingShuffle_, <4 x i8> %LoadCoalescingShuffle_164, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %6 = bitcast i8* %add.ptr64 to <8 x i8>*
  %7 = load <8 x i8>, <8 x i8>* %6, align 1
  %LoadCoalescingShuffle_168 = shufflevector <8 x i8> %7, <8 x i8> undef, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %LoadCoalescingShuffle_169 = shufflevector <8 x i8> %7, <8 x i8> undef, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %SplitLoadShuffle126 = shufflevector <4 x i8> %LoadCoalescingShuffle_166, <4 x i8> %LoadCoalescingShuffle_168, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %SplitLoadShuffle = shufflevector <4 x i8> %LoadCoalescingShuffle_163, <4 x i8> %LoadCoalescingShuffle_165, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %LoadCoalescingShuffle_167 = shufflevector <8 x i8> %5, <8 x i8> undef, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %8 = zext <8 x i8> %SplitLoadShuffle125 to <8 x i32>
  %9 = zext <8 x i8> %SplitLoadShuffle126 to <8 x i32>
  %10 = zext <8 x i8> %SplitLoadShuffle to <8 x i32>
  %SplitLoadShuffle124 = shufflevector <4 x i8> %LoadCoalescingShuffle_167, <4 x i8> %LoadCoalescingShuffle_169, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %11 = zext <8 x i8> %SplitLoadShuffle124 to <8 x i32>
  %12 = sub nsw <8 x i32> %10, %11
  %13 = shl nsw <8 x i32> %12, <i32 16, i32 16, i32 16, i32 16, i32 16, i32 16, i32 16, i32 16>
  %14 = sub nsw <8 x i32> %8, %9
  %15 = add nsw <8 x i32> %13, %14
  ret <8 x i32> %15
}
