; INTEL_FEATURE_SW_ADVANCED
; REQUIRES: intel_feature_sw_advanced
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; Do not set daz/ftz if with optnone attribute.
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=FEATURE-INIT
; RUN: llc -O0 < %s -mtriple=x86_64-unknown-unknown -mattr=+sse -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=NO-INIT-O0
; RUN: llc -O2 < %s -mtriple=x86_64-unknown-unknown -mattr=+sse -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=NO-INIT-O2
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse | FileCheck %s --check-prefix=CHECK-PINIT-FTZ
; RUN: llc -O0 < %s -mtriple=x86_64-unknown-unknown -mattr=+sse | FileCheck %s --check-prefix=NO-INIT-O0
; RUN: llc -O2 < %s -mtriple=x86_64-unknown-unknown -mattr=+sse | FileCheck %s --check-prefix=NO-INIT-O2
; RUN: llc -O0 < %s -mtriple=x86_64-unknown-unknown -mattr=+x87 | FileCheck %s --check-prefix=X87-INIT-O0
; RUN: llc -O2 < %s -mtriple=x86_64-unknown-unknown -mattr=+x87 | FileCheck %s --check-prefix=X87-INIT-O2
; RUN: llc -O0 < %s -mtriple=x86_64-unknown-unknown -mattr=+x87 -x87-precision=80 | FileCheck %s --check-prefix=X87-P80-INIT-O0
; RUN: llc -O2 < %s -mtriple=x86_64-unknown-unknown -mattr=+x87 -x87-precision=80 | FileCheck %s --check-prefix=X87-P80-INIT-O2

define dso_local i32 @main() #0 {
; FEATURE-INIT-LABEL: main:
; FEATURE-INIT:       # %bb.0: # %entry
; FEATURE-INIT-NEXT:    movl $0, -{{[0-9]+}}(%rsp)
; FEATURE-INIT-NEXT:    xorl %eax, %eax
; FEATURE-INIT-NEXT:    retq
;
; NO-INIT-O0-LABEL: main:
; NO-INIT-O0:       # %bb.0: # %entry
; NO-INIT-O0-NEXT:    movl $0, -{{[0-9]+}}(%rsp)
; NO-INIT-O0-NEXT:    xorl %eax, %eax
; NO-INIT-O0-NEXT:    retq
;
; NO-INIT-O2-LABEL: main:
; NO-INIT-O2:       # %bb.0: # %entry
; NO-INIT-O2-NEXT:    movl $0, -{{[0-9]+}}(%rsp)
; NO-INIT-O2-NEXT:    xorl %eax, %eax
; NO-INIT-O2-NEXT:    retq
;
; CHECK-PINIT-FTZ-LABEL: main:
; CHECK-PINIT-FTZ:       # %bb.0: # %entry
; CHECK-PINIT-FTZ-NEXT:    movl $0, -{{[0-9]+}}(%rsp)
; CHECK-PINIT-FTZ-NEXT:    xorl %eax, %eax
; CHECK-PINIT-FTZ-NEXT:    retq
;
; X87-INIT-O0-LABEL: main:
; X87-INIT-O0:       # %bb.0: # %entry
; X87-INIT-O0-NEXT:    movl $0, -{{[0-9]+}}(%rsp)
; X87-INIT-O0-NEXT:    xorl %eax, %eax
; X87-INIT-O0-NEXT:    retq
;
; X87-INIT-O2-LABEL: main:
; X87-INIT-O2:       # %bb.0: # %entry
; X87-INIT-O2-NEXT:    movl $0, -{{[0-9]+}}(%rsp)
; X87-INIT-O2-NEXT:    xorl %eax, %eax
; X87-INIT-O2-NEXT:    retq
;
; X87-P80-INIT-O0-LABEL: main:
; X87-P80-INIT-O0:       # %bb.0: # %entry
; X87-P80-INIT-O0-NEXT:    movw $4991, -{{[0-9]+}}(%rsp) # imm = 0x137F
; X87-P80-INIT-O0-NEXT:    #APP
; X87-P80-INIT-O0-NEXT:    fldcw -{{[0-9]+}}(%rsp)
; X87-P80-INIT-O0-NEXT:    #NO_APP
; X87-P80-INIT-O0-NEXT:    movl $0, -{{[0-9]+}}(%rsp)
; X87-P80-INIT-O0-NEXT:    xorl %eax, %eax
; X87-P80-INIT-O0-NEXT:    retq
;
; X87-P80-INIT-O2-LABEL: main:
; X87-P80-INIT-O2:       # %bb.0: # %entry
; X87-P80-INIT-O2-NEXT:    movw $4991, -{{[0-9]+}}(%rsp) # imm = 0x137F
; X87-P80-INIT-O2-NEXT:    #APP
; X87-P80-INIT-O2-NEXT:    fldcw -{{[0-9]+}}(%rsp)
; X87-P80-INIT-O2-NEXT:    #NO_APP
; X87-P80-INIT-O2-NEXT:    movl $0, -{{[0-9]+}}(%rsp)
; X87-P80-INIT-O2-NEXT:    xorl %eax, %eax
; X87-P80-INIT-O2-NEXT:    retq

; NO-INIT-LABEL: main:
; NO-INIT:       # %bb.0: # %entry
; NO-INIT-NEXT:    xorl %eax, %eax
; NO-INIT-NEXT:    movl $0, -{{[0-9]+}}(%rsp)
; NO-INIT-NEXT:    retq
entry:
  %retval = alloca i32, align 4
  store i32 0, ptr %retval, align 4
  ret i32 0
}
attributes #0 = { noinline nounwind optnone uwtable "denormal-fp-math"="preserve-sign,preserve-sign" }
; end INTEL_FEATURE_SW_ADVANCED
