; INTEL_FEATURE_SW_ADVANCED
; REQUIRES: intel_feature_sw_advanced
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=i686-- < %s | FileCheck %s --check-prefixes=CHECK,CHECK-NO-PC80
; RUN: llc -mtriple=i686-- < %s -x87-precision=80 | FileCheck %s --check-prefixes=CHECK,CHECK-PC80-32
; RUN: llc -mtriple=i686-- < %s -mattr=-x87 | FileCheck %s --check-prefixes=CHECK,CHECK-NO-PC80
; RUN: llc -mtriple=i686-- < %s -mattr=-x87 -x87-precision=80 | FileCheck %s --check-prefixes=CHECK,CHECK-NO-PC80
; RUN: llc -mtriple=x86_64-- < %s | FileCheck %s --check-prefixes=CHECK,CHECK-NO-PC80
; RUN: llc -mtriple=x86_64-- < %s -x87-precision=80 | FileCheck %s --check-prefixes=CHECK,CHECK-PC80-64
; RUN: llc -mtriple=x86_64-- < %s -mattr=-x87 | FileCheck %s --check-prefixes=CHECK,CHECK-NO-PC80
; RUN: llc -mtriple=x86_64-- < %s -mattr=-x87 -x87-precision=80 | FileCheck %s --check-prefixes=CHECK,CHECK-NO-PC80
; RUN: llc -mtriple=x86_64-- < %s -x87-precision=64 | FileCheck %s --check-prefixes=CHECK,CHECK-PC64
; RUN: llc -mtriple=x86_64-- < %s -x87-precision=32 | FileCheck %s --check-prefixes=CHECK,CHECK-PC32

define i32 @main() {
; CHECK-NO-PC80-LABEL: main:
; CHECK-NO-PC80:       # %bb.0:
; CHECK-NO-PC80-NEXT:    xorl %eax, %eax
; CHECK-NO-PC80-NEXT:    ret{{[l|q]}}
;
; CHECK-PC80-32-LABEL: main:
; CHECK-PC80-32:       # %bb.0:
; CHECK-PC80-32-NEXT:    subl $2, %esp
; CHECK-PC80-32-NEXT:    .cfi_def_cfa_offset 6
; CHECK-PC80-32-NEXT:    movw $4991, (%esp) # imm = 0x137F
; CHECK-PC80-32-NEXT:    #APP
; CHECK-PC80-32-NEXT:    fldcw (%esp)
; CHECK-PC80-32-NEXT:    #NO_APP
; CHECK-PC80-32-NEXT:    xorl %eax, %eax
; CHECK-PC80-32-NEXT:    addl $2, %esp
; CHECK-PC80-32-NEXT:    .cfi_def_cfa_offset 4
; CHECK-PC80-32-NEXT:    retl
;
; CHECK-PC80-64-LABEL: main:
; CHECK-PC80-64:       # %bb.0:
; CHECK-PC80-64-NEXT:    movw $4991, -{{[0-9]+}}(%rsp) # imm = 0x137F
; CHECK-PC80-64-NEXT:    #APP
; CHECK-PC80-64-NEXT:    fldcw -{{[0-9]+}}(%rsp)
; CHECK-PC80-64-NEXT:    #NO_APP
; CHECK-PC80-64-NEXT:    xorl %eax, %eax
; CHECK-PC80-64-NEXT:    retq
;
; CHECK-PC64-LABEL: main:
; CHECK-PC64:       # %bb.0:
; CHECK-PC64-NEXT:    movw $4735, -{{[0-9]+}}(%rsp) # imm = 0x127F
; CHECK-PC64-NEXT:    #APP
; CHECK-PC64-NEXT:    fldcw -{{[0-9]+}}(%rsp)
; CHECK-PC64-NEXT:    #NO_APP
; CHECK-PC64-NEXT:    xorl %eax, %eax
; CHECK-PC64-NEXT:    retq
;
; CHECK-PC32-LABEL: main:
; CHECK-PC32:       # %bb.0:
; CHECK-PC32-NEXT:    movw $4223, -{{[0-9]+}}(%rsp) # imm = 0x107F
; CHECK-PC32-NEXT:    #APP
; CHECK-PC32-NEXT:    fldcw -{{[0-9]+}}(%rsp)
; CHECK-PC32-NEXT:    #NO_APP
; CHECK-PC32-NEXT:    xorl %eax, %eax
; CHECK-PC32-NEXT:    retq
  ret i32 0
}

define i32 @foo() {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    ret{{[l|q]}}
  ret i32 0
}
; end INTEL_FEATURE_SW_ADVANCED

