# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -o - %s -mtriple=x86_64-- -mcpu=skx -fp-contract=fast -enable-unsafe-fp-math -run-pass=global-fma | FileCheck %s
---
#
name:            test_mm512_fnmadd_pd
alignment:       16
tracksRegLiveness: true
registers:
  - { id: 0, class: vr512 }
  - { id: 1, class: vr512 }
  - { id: 2, class: vr512 }
  - { id: 3, class: vr512 }
liveins:
  - { reg: '$zmm0', virtual-reg: '%0' }
  - { reg: '$zmm1', virtual-reg: '%1' }
  - { reg: '$zmm2', virtual-reg: '%2' }
frameInfo:
  maxAlignment:    1
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $zmm0, $zmm1, $zmm2

    ; CHECK-LABEL: name: test_mm512_fnmadd_pd
    ; CHECK: liveins: $zmm0, $zmm1, $zmm2
    ; CHECK: [[COPY:%[0-9]+]]:vr512 = COPY $zmm2
    ; CHECK: [[COPY1:%[0-9]+]]:vr512 = COPY $zmm1
    ; CHECK: [[COPY2:%[0-9]+]]:vr512 = COPY $zmm0
    ; CHECK: %4:vr512 = nofpexcept VFNMADD213PDZr [[COPY2]], [[COPY1]], [[COPY]], implicit $mxcsr
    ; CHECK: $zmm0 = COPY %4
    ; CHECK: RET 0, $zmm0
    %2:vr512 = COPY $zmm2
    %1:vr512 = COPY $zmm1
    %0:vr512 = COPY $zmm0
    %3:vr512 = nnan ninf nsz arcp contract afn reassoc nofpexcept VMULPDZrr %0:vr512, %1:vr512, implicit $mxcsr
    %4:vr512 = nnan ninf nsz arcp contract afn reassoc nofpexcept VSUBPDZrr %2:vr512, killed %3:vr512, implicit $mxcsr
    $zmm0 = COPY %4
    RET 0, $zmm0

...

---
#
name:            test_mm512_fnmadd_ps
alignment:       16
tracksRegLiveness: true
registers:
  - { id: 0, class: vr512 }
  - { id: 1, class: vr512 }
  - { id: 2, class: vr512 }
  - { id: 3, class: vr512 }
liveins:
  - { reg: '$zmm0', virtual-reg: '%0' }
  - { reg: '$zmm1', virtual-reg: '%1' }
  - { reg: '$zmm2', virtual-reg: '%2' }
frameInfo:
  maxAlignment:    1
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $zmm0, $zmm1, $zmm2

    ; CHECK-LABEL: name: test_mm512_fnmadd_ps
    ; CHECK: liveins: $zmm0, $zmm1, $zmm2
    ; CHECK: [[COPY:%[0-9]+]]:vr512 = COPY $zmm2
    ; CHECK: [[COPY1:%[0-9]+]]:vr512 = COPY $zmm1
    ; CHECK: [[COPY2:%[0-9]+]]:vr512 = COPY $zmm0
    ; CHECK: %4:vr512 = nofpexcept VFNMADD213PSZr [[COPY2]], [[COPY1]], [[COPY]], implicit $mxcsr
    ; CHECK: $zmm0 = COPY %4
    ; CHECK: RET 0, $zmm0
    %2:vr512 = COPY $zmm2
    %1:vr512 = COPY $zmm1
    %0:vr512 = COPY $zmm0
    %3:vr512 = nnan ninf nsz arcp contract afn reassoc nofpexcept VMULPSZrr %0:vr512, %1:vr512, implicit $mxcsr
    %4:vr512 = nnan ninf nsz arcp contract afn reassoc nofpexcept VSUBPSZrr %2:vr512, killed %3:vr512, implicit $mxcsr
    $zmm0 = COPY %4
    RET 0, $zmm0

...
