; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc -mtriple=x86_64-unknown-linux-gnu %s -o - | FileCheck %s --check-prefix=NOADV
; RUN: llc -enable-intel-advanced-opts -mtriple=i686-unknown-linux-gnu %s -o - | FileCheck %s --check-prefix=CHECK
; RUN: llc -enable-intel-advanced-opts -mtriple=x86_64-unknown-linux-gnu %s -o - | FileCheck %s --check-prefix=CHECK

define i16 @short() {
; NOADV-LABEL: short:
; NOADV:       # %bb.0: # %entry
; NOADV-NEXT:    movw $5, %ax
; NOADV-NEXT:    retq
;
; CHECK-LABEL: short:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl $5, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    ret{{[l|q]}}
entry:
  ret i16 5
}

define i8 @char() {
; NOADV-LABEL: char:
; NOADV:       # %bb.0: # %entry
; NOADV-NEXT:    movb $-5, %al
; NOADV-NEXT:    retq
;
; CHECK-LABEL: char:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl $-5, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    ret{{[l|q]}}
entry:
  ret i8 -5
}
