; INTEL_FEATURE_SW_ADVANCED
; REQUIRES: intel_feature_sw_advanced
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx | FileCheck %s --check-prefix=CHECK-NOPINIT
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+x87 -enable-intel-advanced-opts -intel-libirc-allowed -O0 | FileCheck %s --check-prefix=CHECK-NOPINIT
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+x87 -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-X87
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+cmov -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-CMOV
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+mmx -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-MMX
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-SSE
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse2 -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-SSE2
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-AVX
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512f -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-AVX512
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512f -mattr=+cldemote -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-AVX512
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512f -mattr=+sse2 -mattr=+cldemote -mattr=-sse2 -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-AVX512
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512bw -mattr=+cldemote -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-AVX512BW
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512bw -mattr=+avx512f -mattr=+avx -mattr=+sse2 -mattr=+sse -mattr=+mmx -mattr=+cmov -mattr=+x87 -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-MIX
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+amx-tile -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-AMX
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+amx-int8 -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-AMX
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+amx-bf16 -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-AMX
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avxvnni -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-AVXVNNI
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+kl -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-KL
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+widekl -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=CHECK-PINIT-WIDEKL

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define dso_local i32 @MAIN__() local_unnamed_addr #0 {
; CHECK-NOPINIT-LABEL: MAIN__:
; CHECK-NOPINIT:       # %bb.0:
; CHECK-NOPINIT-NEXT:    xorl %eax, %eax
; CHECK-NOPINIT-NEXT:    retq
;
; CHECK-PINIT-X87-LABEL: MAIN__:
; CHECK-PINIT-X87:       # %bb.0:
; CHECK-PINIT-X87-NEXT:    pushq %rax
; CHECK-PINIT-X87-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-X87-NEXT:    movl $2, %esi
; CHECK-PINIT-X87-NEXT:    xorl %edi, %edi
; CHECK-PINIT-X87-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-X87-NEXT:    xorl %eax, %eax
; CHECK-PINIT-X87-NEXT:    popq %rcx
; CHECK-PINIT-X87-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-X87-NEXT:    retq
;
; CHECK-PINIT-CMOV-LABEL: MAIN__:
; CHECK-PINIT-CMOV:       # %bb.0:
; CHECK-PINIT-CMOV-NEXT:    pushq %rax
; CHECK-PINIT-CMOV-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-CMOV-NEXT:    movl $4, %esi
; CHECK-PINIT-CMOV-NEXT:    xorl %edi, %edi
; CHECK-PINIT-CMOV-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-CMOV-NEXT:    xorl %eax, %eax
; CHECK-PINIT-CMOV-NEXT:    popq %rcx
; CHECK-PINIT-CMOV-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-CMOV-NEXT:    retq
;
; CHECK-PINIT-MMX-LABEL: MAIN__:
; CHECK-PINIT-MMX:       # %bb.0:
; CHECK-PINIT-MMX-NEXT:    pushq %rax
; CHECK-PINIT-MMX-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-MMX-NEXT:    movl $8, %esi
; CHECK-PINIT-MMX-NEXT:    xorl %edi, %edi
; CHECK-PINIT-MMX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MMX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MMX-NEXT:    popq %rcx
; CHECK-PINIT-MMX-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-MMX-NEXT:    retq
;
; CHECK-PINIT-SSE-LABEL: MAIN__:
; CHECK-PINIT-SSE:       # %bb.0:
; CHECK-PINIT-SSE-NEXT:    pushq %rax
; CHECK-PINIT-SSE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-SSE-NEXT:    movl $32, %esi
; CHECK-PINIT-SSE-NEXT:    xorl %edi, %edi
; CHECK-PINIT-SSE-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE-NEXT:    popq %rcx
; CHECK-PINIT-SSE-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-SSE-NEXT:    retq
;
; CHECK-PINIT-SSE2-LABEL: MAIN__:
; CHECK-PINIT-SSE2:       # %bb.0:
; CHECK-PINIT-SSE2-NEXT:    pushq %rax
; CHECK-PINIT-SSE2-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-SSE2-NEXT:    movl $64, %esi
; CHECK-PINIT-SSE2-NEXT:    xorl %edi, %edi
; CHECK-PINIT-SSE2-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE2-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE2-NEXT:    popq %rcx
; CHECK-PINIT-SSE2-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-SSE2-NEXT:    retq
;
; CHECK-PINIT-AVX-LABEL: MAIN__:
; CHECK-PINIT-AVX:       # %bb.0:
; CHECK-PINIT-AVX-NEXT:    pushq %rax
; CHECK-PINIT-AVX-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-AVX-NEXT:    movl $65536, %esi # imm = 0x10000
; CHECK-PINIT-AVX-NEXT:    xorl %edi, %edi
; CHECK-PINIT-AVX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX-NEXT:    popq %rcx
; CHECK-PINIT-AVX-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-AVX-NEXT:    retq
;
; CHECK-PINIT-AVX512-LABEL: MAIN__:
; CHECK-PINIT-AVX512:       # %bb.0:
; CHECK-PINIT-AVX512-NEXT:    pushq %rax
; CHECK-PINIT-AVX512-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-AVX512-NEXT:    movl $134217728, %esi # imm = 0x8000000
; CHECK-PINIT-AVX512-NEXT:    xorl %edi, %edi
; CHECK-PINIT-AVX512-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX512-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX512-NEXT:    popq %rcx
; CHECK-PINIT-AVX512-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-AVX512-NEXT:    retq
;
; CHECK-PINIT-AVX512BW-LABEL: MAIN__:
; CHECK-PINIT-AVX512BW:       # %bb.0:
; CHECK-PINIT-AVX512BW-NEXT:    pushq %rax
; CHECK-PINIT-AVX512BW-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-AVX512BW-NEXT:    movabsq $137438953472, %rsi # imm = 0x2000000000
; CHECK-PINIT-AVX512BW-NEXT:    xorl %edi, %edi
; CHECK-PINIT-AVX512BW-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX512BW-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX512BW-NEXT:    popq %rcx
; CHECK-PINIT-AVX512BW-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-AVX512BW-NEXT:    retq
;
; CHECK-PINIT-MIX-LABEL: MAIN__:
; CHECK-PINIT-MIX:       # %bb.0:
; CHECK-PINIT-MIX-NEXT:    pushq %rax
; CHECK-PINIT-MIX-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-MIX-NEXT:    movabsq $137573236846, %rsi # imm = 0x200801006E
; CHECK-PINIT-MIX-NEXT:    xorl %edi, %edi
; CHECK-PINIT-MIX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MIX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MIX-NEXT:    popq %rcx
; CHECK-PINIT-MIX-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-MIX-NEXT:    retq
;
; CHECK-PINIT-AMX-LABEL: MAIN__:
; CHECK-PINIT-AMX:       # %bb.0:
; CHECK-PINIT-AMX-NEXT:    pushq %rax
; CHECK-PINIT-AMX-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-AMX-NEXT:    xorl %edi, %edi
; CHECK-PINIT-AMX-NEXT:    xorl %esi, %esi
; CHECK-PINIT-AMX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AMX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AMX-NEXT:    popq %rcx
; CHECK-PINIT-AMX-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-AMX-NEXT:    retq
;
; CHECK-PINIT-AVXVNNI-LABEL: MAIN__:
; CHECK-PINIT-AVXVNNI:       # %bb.0:
; CHECK-PINIT-AVXVNNI-NEXT:    pushq %rax
; CHECK-PINIT-AVXVNNI-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-AVXVNNI-NEXT:    xorl %edi, %edi
; CHECK-PINIT-AVXVNNI-NEXT:    xorl %esi, %esi
; CHECK-PINIT-AVXVNNI-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVXVNNI-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVXVNNI-NEXT:    popq %rcx
; CHECK-PINIT-AVXVNNI-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-AVXVNNI-NEXT:    retq
;
; CHECK-PINIT-KL-LABEL: MAIN__:
; CHECK-PINIT-KL:       # %bb.0:
; CHECK-PINIT-KL-NEXT:    pushq %rax
; CHECK-PINIT-KL-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-KL-NEXT:    xorl %edi, %edi
; CHECK-PINIT-KL-NEXT:    xorl %esi, %esi
; CHECK-PINIT-KL-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-KL-NEXT:    xorl %eax, %eax
; CHECK-PINIT-KL-NEXT:    popq %rcx
; CHECK-PINIT-KL-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-KL-NEXT:    retq
;
; CHECK-PINIT-WIDEKL-LABEL: MAIN__:
; CHECK-PINIT-WIDEKL:       # %bb.0:
; CHECK-PINIT-WIDEKL-NEXT:    pushq %rax
; CHECK-PINIT-WIDEKL-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-WIDEKL-NEXT:    xorl %edi, %edi
; CHECK-PINIT-WIDEKL-NEXT:    xorl %esi, %esi
; CHECK-PINIT-WIDEKL-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-WIDEKL-NEXT:    xorl %eax, %eax
; CHECK-PINIT-WIDEKL-NEXT:    popq %rcx
; CHECK-PINIT-WIDEKL-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-WIDEKL-NEXT:    retq


  ret i32 0
}

; Function Attrs: norecurse nounwind readnone uwtable
define dso_local i32 @main() local_unnamed_addr #0 {
; CHECK-NOPINIT-LABEL: main:
; CHECK-NOPINIT:       # %bb.0:
; CHECK-NOPINIT-NEXT:    xorl %eax, %eax
; CHECK-NOPINIT-NEXT:    retq
;
; CHECK-PINIT-X87-LABEL: main:
; CHECK-PINIT-X87:       # %bb.0:
; CHECK-PINIT-X87-NEXT:    pushq %rax
; CHECK-PINIT-X87-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-X87-NEXT:    movl $2, %esi
; CHECK-PINIT-X87-NEXT:    xorl %edi, %edi
; CHECK-PINIT-X87-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-X87-NEXT:    xorl %eax, %eax
; CHECK-PINIT-X87-NEXT:    popq %rcx
; CHECK-PINIT-X87-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-X87-NEXT:    retq
;
; CHECK-PINIT-CMOV-LABEL: main:
; CHECK-PINIT-CMOV:       # %bb.0:
; CHECK-PINIT-CMOV-NEXT:    pushq %rax
; CHECK-PINIT-CMOV-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-CMOV-NEXT:    movl $4, %esi
; CHECK-PINIT-CMOV-NEXT:    xorl %edi, %edi
; CHECK-PINIT-CMOV-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-CMOV-NEXT:    xorl %eax, %eax
; CHECK-PINIT-CMOV-NEXT:    popq %rcx
; CHECK-PINIT-CMOV-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-CMOV-NEXT:    retq
;
; CHECK-PINIT-MMX-LABEL: main:
; CHECK-PINIT-MMX:       # %bb.0:
; CHECK-PINIT-MMX-NEXT:    pushq %rax
; CHECK-PINIT-MMX-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-MMX-NEXT:    movl $8, %esi
; CHECK-PINIT-MMX-NEXT:    xorl %edi, %edi
; CHECK-PINIT-MMX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MMX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MMX-NEXT:    popq %rcx
; CHECK-PINIT-MMX-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-MMX-NEXT:    retq
;
; CHECK-PINIT-SSE-LABEL: main:
; CHECK-PINIT-SSE:       # %bb.0:
; CHECK-PINIT-SSE-NEXT:    pushq %rax
; CHECK-PINIT-SSE-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-SSE-NEXT:    movl $32, %esi
; CHECK-PINIT-SSE-NEXT:    xorl %edi, %edi
; CHECK-PINIT-SSE-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE-NEXT:    popq %rcx
; CHECK-PINIT-SSE-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-SSE-NEXT:    retq
;
; CHECK-PINIT-SSE2-LABEL: main:
; CHECK-PINIT-SSE2:       # %bb.0:
; CHECK-PINIT-SSE2-NEXT:    pushq %rax
; CHECK-PINIT-SSE2-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-SSE2-NEXT:    movl $64, %esi
; CHECK-PINIT-SSE2-NEXT:    xorl %edi, %edi
; CHECK-PINIT-SSE2-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-SSE2-NEXT:    xorl %eax, %eax
; CHECK-PINIT-SSE2-NEXT:    popq %rcx
; CHECK-PINIT-SSE2-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-SSE2-NEXT:    retq
;
; CHECK-PINIT-AVX-LABEL: main:
; CHECK-PINIT-AVX:       # %bb.0:
; CHECK-PINIT-AVX-NEXT:    pushq %rax
; CHECK-PINIT-AVX-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-AVX-NEXT:    movl $65536, %esi # imm = 0x10000
; CHECK-PINIT-AVX-NEXT:    xorl %edi, %edi
; CHECK-PINIT-AVX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX-NEXT:    popq %rcx
; CHECK-PINIT-AVX-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-AVX-NEXT:    retq
;
; CHECK-PINIT-AVX512-LABEL: main:
; CHECK-PINIT-AVX512:       # %bb.0:
; CHECK-PINIT-AVX512-NEXT:    pushq %rax
; CHECK-PINIT-AVX512-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-AVX512-NEXT:    movl $134217728, %esi # imm = 0x8000000
; CHECK-PINIT-AVX512-NEXT:    xorl %edi, %edi
; CHECK-PINIT-AVX512-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX512-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX512-NEXT:    popq %rcx
; CHECK-PINIT-AVX512-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-AVX512-NEXT:    retq
;
; CHECK-PINIT-AVX512BW-LABEL: main:
; CHECK-PINIT-AVX512BW:       # %bb.0:
; CHECK-PINIT-AVX512BW-NEXT:    pushq %rax
; CHECK-PINIT-AVX512BW-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-AVX512BW-NEXT:    movabsq $137438953472, %rsi # imm = 0x2000000000
; CHECK-PINIT-AVX512BW-NEXT:    xorl %edi, %edi
; CHECK-PINIT-AVX512BW-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVX512BW-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVX512BW-NEXT:    popq %rcx
; CHECK-PINIT-AVX512BW-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-AVX512BW-NEXT:    retq
;
; CHECK-PINIT-MIX-LABEL: main:
; CHECK-PINIT-MIX:       # %bb.0:
; CHECK-PINIT-MIX-NEXT:    pushq %rax
; CHECK-PINIT-MIX-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-MIX-NEXT:    movabsq $137573236846, %rsi # imm = 0x200801006E
; CHECK-PINIT-MIX-NEXT:    xorl %edi, %edi
; CHECK-PINIT-MIX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-MIX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-MIX-NEXT:    popq %rcx
; CHECK-PINIT-MIX-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-MIX-NEXT:    retq
;
; CHECK-PINIT-AMX-LABEL: main:
; CHECK-PINIT-AMX:       # %bb.0:
; CHECK-PINIT-AMX-NEXT:    pushq %rax
; CHECK-PINIT-AMX-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-AMX-NEXT:    xorl %edi, %edi
; CHECK-PINIT-AMX-NEXT:    xorl %esi, %esi
; CHECK-PINIT-AMX-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AMX-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AMX-NEXT:    popq %rcx
; CHECK-PINIT-AMX-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-AMX-NEXT:    retq
;
; CHECK-PINIT-AVXVNNI-LABEL: main:
; CHECK-PINIT-AVXVNNI:       # %bb.0:
; CHECK-PINIT-AVXVNNI-NEXT:    pushq %rax
; CHECK-PINIT-AVXVNNI-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-AVXVNNI-NEXT:    xorl %edi, %edi
; CHECK-PINIT-AVXVNNI-NEXT:    xorl %esi, %esi
; CHECK-PINIT-AVXVNNI-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-AVXVNNI-NEXT:    xorl %eax, %eax
; CHECK-PINIT-AVXVNNI-NEXT:    popq %rcx
; CHECK-PINIT-AVXVNNI-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-AVXVNNI-NEXT:    retq
;
; CHECK-PINIT-KL-LABEL: main:
; CHECK-PINIT-KL:       # %bb.0:
; CHECK-PINIT-KL-NEXT:    pushq %rax
; CHECK-PINIT-KL-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-KL-NEXT:    xorl %edi, %edi
; CHECK-PINIT-KL-NEXT:    xorl %esi, %esi
; CHECK-PINIT-KL-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-KL-NEXT:    xorl %eax, %eax
; CHECK-PINIT-KL-NEXT:    popq %rcx
; CHECK-PINIT-KL-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-KL-NEXT:    retq
;
; CHECK-PINIT-WIDEKL-LABEL: main:
; CHECK-PINIT-WIDEKL:       # %bb.0:
; CHECK-PINIT-WIDEKL-NEXT:    pushq %rax
; CHECK-PINIT-WIDEKL-NEXT:    .cfi_def_cfa_offset 16
; CHECK-PINIT-WIDEKL-NEXT:    xorl %edi, %edi
; CHECK-PINIT-WIDEKL-NEXT:    xorl %esi, %esi
; CHECK-PINIT-WIDEKL-NEXT:    callq __intel_new_feature_proc_init
; CHECK-PINIT-WIDEKL-NEXT:    xorl %eax, %eax
; CHECK-PINIT-WIDEKL-NEXT:    popq %rcx
; CHECK-PINIT-WIDEKL-NEXT:    .cfi_def_cfa_offset 8
; CHECK-PINIT-WIDEKL-NEXT:    retq


  ret i32 0
}

attributes #0 = { norecurse nounwind readnone uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"icx (ICX) dev.8.x.0"}
; end INTEL_FEATURE_SW_ADVANCED
