; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=i686-pc-linux-gnu | FileCheck %s -check-prefix=ALIGN
; RUN: llc < %s -mtriple=i686-pc-linux-gnu -align-loops=32 | FileCheck %s -check-prefix=ALIGN32
; RUN: llc < %s -mtriple=i686-pc-linux-gnu -align-loops=256 | FileCheck %s -check-prefix=ALIGN256

declare void @foo()

; ALIGN:      .p2align 7, 0x90
; ALIGN32:    .p2align 7, 0x90
; ALIGN256:   .p2align 8, 0x90

define void @test(i32 %n, i32 %m) #0 {
entry:
  br label %outer

outer:
  %outer.iv = phi i32 [0, %entry], [%outer.iv.next, %outer_bb]
  br label %inner

inner:
  %inner.iv = phi i32 [0, %outer], [%inner.iv.next, %inner]
  call void @foo()
  %inner.iv.next = add i32 %inner.iv, 1
  %inner.cond = icmp ne i32 %inner.iv.next, %m
  br i1 %inner.cond, label %inner, label %outer_bb

outer_bb:
  %outer.iv.next = add i32 %outer.iv, 1
  %outer.cond = icmp ne i32 %outer.iv.next, %n
  br i1 %outer.cond, label %outer, label %exit

exit:
  ret void
}

attributes #0 = { "intel-code-align"="128" }
