; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=avx512fp16 | FileCheck %s --check-prefixes=CHECK

define <8 x half> @svml_cc_v8i1(<8 x half> %x, <8 x i16> %mask) {
; CHECK-LABEL: svml_cc_v8i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vpxor %xmm2, %xmm2, %xmm2
; CHECK-NEXT:    vpcmpeqw %xmm2, %xmm1, %xmm1
; CHECK-NEXT:    callq *mysvml_v8f16_v8i1@{{.*}}(%rip)
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %m = icmp eq <8 x i16> %mask, zeroinitializer
  %res = call svml_cc <8 x half> @mysvml_v8f16_v8i1(<8 x half> %x, <8 x i1> %m)
  ret <8 x half> %res
}

define <16 x half> @svml_cc_v16i1(<16 x half> %x, <16 x i16> %mask) {
; CHECK-LABEL: svml_cc_v16i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vpxor %xmm2, %xmm2, %xmm2
; CHECK-NEXT:    vpcmpeqw %ymm2, %ymm1, %ymm1
; CHECK-NEXT:    callq *mysvml_v16f16_v16i1@{{.*}}(%rip)
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %m = icmp eq <16 x i16> %mask, zeroinitializer
  %res = call svml_cc <16 x half> @mysvml_v16f16_v16i1(<16 x half> %x, <16 x i1> %m)
  ret <16 x half> %res
}

define <32 x half> @svml_cc_v32i1(<32 x half> %x, <32 x i16> %mask) {
; CHECK-LABEL: svml_cc_v32i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vptestnmw %zmm1, %zmm1, %k1
; CHECK-NEXT:    callq *mysvml_v32f16_v32i1@{{.*}}(%rip)
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %m = icmp eq <32 x i16> %mask, zeroinitializer
  %res = call svml_cc <32 x half> @mysvml_v32f16_v32i1(<32 x half> %x, <32 x i1> %m)
  ret <32 x half> %res
}

declare <8 x half> @mysvml_v8f16_v8i1(<8 x half>, <8 x i1>)
declare <16 x half> @mysvml_v16f16_v16i1(<16 x half>, <16 x i1>)
declare <32 x half> @mysvml_v32f16_v32i1(<32 x half>, <32 x i1>)
