; INTEL_FEATURE_SW_ADVANCED
; REQUIRES: intel_feature_sw_advanced
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=FEATURE-INIT
; RUN: llc -O0 < %s -mtriple=x86_64-unknown-unknown -mattr=+sse -enable-intel-advanced-opts -intel-libirc-allowed | FileCheck %s --check-prefix=NO-INIT
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse | FileCheck %s --check-prefix=CHECK-PINIT-FTZ
; RUN: llc -O0 < %s -mtriple=x86_64-unknown-unknown -mattr=+sse | FileCheck %s --check-prefix=NO-INIT

define dso_local i32 @main() #0 {
; FEATURE-INIT-LABEL: main:
; FEATURE-INIT:       # %bb.0: # %entry
; FEATURE-INIT-NEXT:    pushq %rax
; FEATURE-INIT-NEXT:    .cfi_def_cfa_offset 16
; FEATURE-INIT-NEXT:    movl $32, %esi
; FEATURE-INIT-NEXT:    movl $3, %edi
; FEATURE-INIT-NEXT:    callq __intel_new_feature_proc_init@PLT
; FEATURE-INIT-NEXT:    movl $0, {{[0-9]+}}(%rsp)
; FEATURE-INIT-NEXT:    xorl %eax, %eax
; FEATURE-INIT-NEXT:    popq %rcx
; FEATURE-INIT-NEXT:    .cfi_def_cfa_offset 8
; FEATURE-INIT-NEXT:    retq
;
; NO-INIT-LABEL: main:
; NO-INIT:       # %bb.0: # %entry
; NO-INIT-NEXT:    movl $0, -{{[0-9]+}}(%rsp)
; NO-INIT-NEXT:    xorl %eax, %eax
; NO-INIT-NEXT:    retq
;
; CHECK-PINIT-FTZ-LABEL: main:
; CHECK-PINIT-FTZ:       # %bb.0: # %entry
; CHECK-PINIT-FTZ-NEXT:    stmxcsr -{{[0-9]+}}(%rsp)
; CHECK-PINIT-FTZ-NEXT:    orl $32832, -{{[0-9]+}}(%rsp) # imm = 0x8040
; CHECK-PINIT-FTZ-NEXT:    ldmxcsr -{{[0-9]+}}(%rsp)
; CHECK-PINIT-FTZ-NEXT:    movl $0, -{{[0-9]+}}(%rsp)
; CHECK-PINIT-FTZ-NEXT:    xorl %eax, %eax
; CHECK-PINIT-FTZ-NEXT:    retq
entry:
  %retval = alloca i32, align 4
  store i32 0, i32* %retval, align 4
  ret i32 0
}
attributes #0 = { "denormal-fp-math"="preserve-sign,preserve-sign" }
; end INTEL_FEATURE_SW_ADVANCED
