; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=avx512f | FileCheck %s

define <8 x double> @svml_cc_v8i1(<8 x double> %x, <8 x i64> %mask) {
; CHECK-LABEL: svml_cc_v8i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vptestnmq %zmm1, %zmm1, %k1
; CHECK-NEXT:    callq *mysvml_v8f64_v8i1@GOTPCREL(%rip)
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %m = icmp eq <8 x i64> %mask, zeroinitializer
  %res = call svml_cc <8 x double> @mysvml_v8f64_v8i1(<8 x double> %x, <8 x i1> %m)
  ret <8 x double> %res
}

define <16 x float> @svml_cc_v16i1(<16 x float> %x, <16 x i32> %mask) {
; CHECK-LABEL: svml_cc_v16i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vptestnmd %zmm1, %zmm1, %k1
; CHECK-NEXT:    callq *mysvml_v16f32_v16i1@GOTPCREL(%rip)
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %m = icmp eq <16 x i32> %mask, zeroinitializer
  %res = call svml_cc <16 x float> @mysvml_v16f32_v16i1(<16 x float> %x, <16 x i1> %m)
  ret <16 x float> %res
}

declare <8 x double> @mysvml_v8f64_v8i1(<8 x double>, <8 x i1>)
declare <16 x float> @mysvml_v16f32_v16i1(<16 x float>, <16 x i1>)
