# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -o - %s -mtriple=x86_64-- -mcpu=core-avx2 -fp-contract=fast -enable-unsafe-fp-math -run-pass=global-fma | FileCheck %s

...
---
name:            foo
alignment:       16
tracksRegLiveness: true
registers:
  - { id: 0, class: vr128 }
  - { id: 1, class: vr128 }
  - { id: 2, class: vr128 }
  - { id: 3, class: vr128 }
frameInfo:
  maxAlignment:    1
machineFunctionInfo: {}
body:             |
  bb.0.entry:

    liveins: $rdi, $rsi
    ; CHECK-LABEL: name: foo
    ; CHECK: liveins: $rdi, $rsi
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %t16:gr64 = COPY $rdi
    ; CHECK-NEXT: %t18:gr64_nosp = COPY $rsi
    ; CHECK-NEXT: %t100:vr128 = VMOVUPSrm %t16, 2, %t18, 16, $noreg
    ; CHECK-NEXT: %t610:vr128 = VPERMILPDri %t100, 1
    ; CHECK-NEXT: %t740:vr128 = VMOVUPSrm %t16, 2, %t18, 48, $noreg
    ; CHECK-NEXT: %t669:vr128 = VMOVUPSrm %t16, 2, %t18, 64, $noreg
    ; CHECK-NEXT: %t637:vr128 = VMOVUPSrm %t16, 2, %t18, 80, $noreg
    ; CHECK-NEXT: %t29:fr64 = VMOVSDrm_alt %t16, 2, %t18, 0, $noreg
    ; CHECK-NEXT: %t30:fr64 = VMOVSDrm_alt %t16, 2, %t18, 8, $noreg
    ; CHECK-NEXT: %t312:fr64 = COPY %t100
    ; CHECK-NEXT: %t741:vr128 = nnan ninf nsz arcp contract afn reassoc nofpexcept VMULPDrr killed %t740, killed %t669, implicit $mxcsr
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vr128 = COPY %t312
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vr128 = COPY %t29
    ; CHECK-NEXT: %20:vr128 = nofpexcept VFMADD213PDr [[COPY]], [[COPY1]], %t741, implicit $mxcsr
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vr128 = COPY %t30
    ; CHECK-NEXT: %t743:vr128 = nofpexcept VFMADD213PDr %t610, [[COPY2]], killed %20, implicit $mxcsr
    ; CHECK-NEXT: %t744:vr128 = nnan ninf nsz arcp contract afn reassoc nofpexcept VMULPDrr %t741, %t637, implicit $mxcsr
    ; CHECK-NEXT: %t745:vr128 = VBLENDPDrri killed %t744, killed %t743, 1
    ; CHECK-NEXT: $xmm0 = COPY %t745
    ; CHECK-NEXT: RET 0, $xmm0
    %t16:gr64 = COPY $rdi
    %t18:gr64_nosp = COPY $rsi

    %t100:vr128 = VMOVUPSrm %t16:gr64, 2, %t18:gr64_nosp, 16, $noreg
    %t610:vr128 = VPERMILPDri %t100:vr128, 1
    %t740:vr128 = VMOVUPSrm %t16:gr64, 2, %t18:gr64_nosp, 48, $noreg
    %t669:vr128 = VMOVUPSrm %t16:gr64, 2, %t18:gr64_nosp, 64, $noreg
    %t637:vr128 = VMOVUPSrm %t16:gr64, 2, %t18:gr64_nosp, 80, $noreg

    %t29:fr64 = VMOVSDrm_alt %t16:gr64, 2, %t18:gr64_nosp, 0, $noreg
    %t30:fr64 = VMOVSDrm_alt %t16:gr64, 2, %t18:gr64_nosp, 8, $noreg
    %t312:fr64 = COPY %t100:vr128

    %t677:fr64  = nnan ninf nsz arcp contract afn reassoc nofpexcept VMULSDrr %t312:fr64, %t29:fr64, implicit $mxcsr
    %t679:vr128 = nnan ninf nsz arcp contract afn reassoc nofpexcept VFMADD213SDr %t30:fr64, %t610:vr128, killed %t677:fr64, implicit $mxcsr
    %t741:vr128 = nnan ninf nsz arcp contract afn reassoc nofpexcept VMULPDrr killed %t740:vr128, killed %t669:vr128, implicit $mxcsr
    %t743:vr128 = nnan ninf nsz arcp contract afn reassoc nofpexcept VADDPDrr %t741:vr128, %t679:vr128, implicit $mxcsr
    %t744:vr128 = nnan ninf nsz arcp contract afn reassoc nofpexcept VMULPDrr %t741:vr128, %t637:vr128, implicit $mxcsr

    %t745:vr128 = VBLENDPDrri killed %t744:vr128, killed %t743:vr128, 1


    $xmm0 = COPY %t745
    RET 0, $xmm0
...
