; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s | FileCheck %s
; CMPLRIL0-24981: Using VRNDSCALESD instead of VCVTTSD2SI+VCVTSI2SD.
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: nofree norecurse nosync nounwind readnone uwtable willreturn mustprogress
define dso_local double @test1(double %a) local_unnamed_addr #0 {
; CHECK-LABEL: test1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vroundsd $3, %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    retq
entry:
  %conv = fptosi double %a to i64
  %conv1 = sitofp i64 %conv to double
  ret double %conv1
}

; Function Attrs: nofree norecurse nosync nounwind readnone uwtable willreturn mustprogress
define dso_local double @test2(double %a) local_unnamed_addr #0 {
; CHECK-LABEL: test2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vroundsd $3, %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    retq
entry:
  %conv = fptosi double %a to i32
  %conv1 = sitofp i32 %conv to double
  ret double %conv1
}

; Function Attrs: nofree norecurse nosync nounwind readnone uwtable willreturn mustprogress
define dso_local float @test3(float %a) local_unnamed_addr #0 {
; CHECK-LABEL: test3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vroundss $3, %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    retq
entry:
  %conv = fptosi float %a to i32
  %conv1 = sitofp i32 %conv to float
  ret float %conv1
}

attributes #0 = { nofree norecurse nosync nounwind readnone uwtable willreturn mustprogress "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+avx,+avx2,+avx512f,+cx8,+f16c,+fma,+fxsr,+mmx,+popcnt,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+ssse3,+x87,+xsave" "tune-cpu"="generic" }

!llvm.module.flags = !{!0, !1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"uwtable", i32 1}
