; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=avx2 | FileCheck %s
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=avx512f | FileCheck %s

define <4 x double> @svml_cc_v4i1(<4 x double> %x, <4 x i64> %mask) {
; CHECK-LABEL: svml_cc_v4i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vpxor %xmm2, %xmm2, %xmm2
; CHECK-NEXT:    vpcmpeqq %ymm2, %ymm1, %ymm1
; CHECK-NEXT:    callq *mysvml_v4f64_v4i1@GOTPCREL(%rip)
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %m = icmp eq <4 x i64> %mask, zeroinitializer
  %res = call svml_unified_cc_256 <4 x double> @mysvml_v4f64_v4i1(<4 x double> %x, <4 x i1> %m)
  ret <4 x double> %res
}

define <8 x float> @svml_cc_v8i1(<8 x float> %x, <8 x i32> %mask) {
; CHECK-LABEL: svml_cc_v8i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vpxor %xmm2, %xmm2, %xmm2
; CHECK-NEXT:    vpcmpeqd %ymm2, %ymm1, %ymm1
; CHECK-NEXT:    callq *mysvml_v8f32_v8i1@GOTPCREL(%rip)
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %m = icmp eq <8 x i32> %mask, zeroinitializer
  %res = call svml_unified_cc_256 <8 x float> @mysvml_v8f32_v8i1(<8 x float> %x, <8 x i1> %m)
  ret <8 x float> %res
}

declare <4 x double> @mysvml_v4f64_v4i1(<4 x double>, <4 x i1>)
declare <8 x float> @mysvml_v8f32_v8i1(<8 x float>, <8 x i1>)
