; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc < %s | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-win32-msvc-elf"

%"class.sycl::_V1::id" = type { %"class.sycl::_V1::detail::array" }
%"class.sycl::_V1::detail::array" = type { [1 x i64] }
%"class.sycl::_V1::vec" = type { <2 x half> }

; Function Attrs: nofree nosync nounwind memory(argmem: readwrite)
declare !kernel_arg_addr_space !3 !kernel_arg_access_qual !12 !kernel_arg_type !13 !kernel_arg_base_type !13 !kernel_arg_type_qual !14 !arg_type_null_val !15 !no_barrier_path !16 !kernel_has_sub_groups !17 !kernel_has_global_sync !17 !kernel_execution_length !18 !max_wg_dimensions !19 !local_buffer_size !19 !barrier_buffer_size !19 !kernel_wrapper !20 !private_memory_size !19 !vectorized_width !21 !spirv.ParameterDecorations !22 void @___ZTS6kernelILi4300078EE_separated_args(ptr addrspace(1) noalias nocapture writeonly align 4, ptr noalias nocapture readonly byval(%"class.sycl::_V1::id") align 8, ptr addrspace(3) noalias, ptr noalias, ptr noalias, [4 x i64], ptr noalias, ptr noalias) local_unnamed_addr #0

; Function Attrs: convergent mustprogress nofree nounwind willreturn memory(none)
declare intel_ocl_bicc_avx512 <2 x half> @__ocl_svml_z1_atan2s2(<2 x half> noundef, <2 x half> noundef) local_unnamed_addr #1

; Function Attrs: nofree nosync nounwind memory(argmem: readwrite)
define void @_ZTS6kernelILi4300078EE(ptr noalias %UniformArgs, ptr noalias %pWGId, ptr noalias %RuntimeHandle) local_unnamed_addr #0 !kernel_arg_addr_space !3 !kernel_arg_access_qual !12 !kernel_arg_type !13 !kernel_arg_base_type !13 !kernel_arg_type_qual !14 !arg_type_null_val !15 !no_barrier_path !16 !kernel_has_sub_groups !17 !kernel_has_global_sync !17 !kernel_execution_length !18 !max_wg_dimensions !19 !local_buffer_size !19 !barrier_buffer_size !19 !private_memory_size !19 !vectorized_width !21 !spirv.ParameterDecorations !22 {
; CHECK-LABEL: _ZTS6kernelILi4300078EE:
; CHECK:       # %bb.0: # %wrapper_entry
; CHECK-NEXT:    pushq %rsi
; CHECK-NEXT:    pushq %rdi
; CHECK-NEXT:    subq $40, %rsp
; CHECK-NEXT:    movq (%rcx), %rsi
; CHECK-NEXT:    movq 8(%rcx), %rdi
; CHECK-NEXT:    movdqa {{.*#+}} xmm0 = <5.1514E-1,7.2852E-1,u,u,u,u,u,u>
; CHECK-NEXT:    movaps {{.*#+}} xmm1 = <2.5122E-1,7.2559E-1,u,u,u,u,u,u>
; CHECK-NEXT:    callq __ocl_svml_z1_atan2s2@PLT
; CHECK-NEXT:    pextrw $0, %xmm0, %eax
; CHECK-NEXT:    psrld $16, %xmm0
; CHECK-NEXT:    movw %ax, (%rsi,%rdi,4)
; CHECK-NEXT:    pextrw $0, %xmm0, %eax
; CHECK-NEXT:    movw %ax, 2(%rsi,%rdi,4)
; CHECK-NEXT:    addq $40, %rsp
; CHECK-NEXT:    popq %rdi
; CHECK-NEXT:    popq %rsi
; CHECK-NEXT:    retq
wrapper_entry:
  %explicit_0 = load ptr addrspace(1), ptr %UniformArgs, align 8, !restrict !28
  %explicit_1 = getelementptr i64, ptr %UniformArgs, i64 1
  %explicit_1.ptr.sroa.0.0.copyload = load i64, ptr %explicit_1, align 1
  %call.i = call contract intel_ocl_bicc_avx512 <2 x half> @__ocl_svml_z1_atan2s2(<2 x half> noundef <half 0xH381F, half 0xH39D4>, <2 x half> noundef <half 0xH3405, half 0xH39CE>) #2
  %0 = getelementptr inbounds %"class.sycl::_V1::vec", ptr addrspace(1) %explicit_0, i64 %explicit_1.ptr.sroa.0.0.copyload
  store <2 x half> %call.i, ptr addrspace(1) %0, align 4
  ret void
}

attributes #0 = { nofree nosync nounwind memory(argmem: readwrite) "min-legal-vector-width"="64" "prefer-vector-width"="512" }
attributes #1 = { convergent mustprogress nofree nounwind willreturn memory(none) "denormal-fp-math"="dynamic,dynamic" "min-legal-vector-width"="32" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "stackrealign" }
attributes #2 = { convergent nounwind willreturn memory(none) }

!spirv.MemoryModel = !{!0}
!opencl.enable.FP_CONTRACT = !{}
!spirv.Source = !{!1}
!opencl.spir.version = !{!2}
!opencl.ocl.version = !{!3}
!opencl.used.extensions = !{!4}
!opencl.used.optional.core.features = !{!4}
!spirv.Generator = !{!5}
!sycl.kernels = !{!6}
!sycl.stat.type = !{!7}
!sycl.stat.exec_time = !{!8}
!sycl.stat.run_time_version = !{!9}
!sycl.stat.workload_name = !{!10}
!sycl.stat.module_name = !{!11}

!0 = !{i32 2, i32 2}
!1 = !{i32 4, i32 100000}
!2 = !{i32 1, i32 2}
!3 = !{i32 1, i32 0}
!4 = !{}
!5 = !{i16 6, i16 14}
!6 = !{ptr @___ZTS6kernelILi4300078EE_separated_args}
!7 = !{!"all"}
!8 = !{!"2023-10-08 13:14:32"}
!9 = !{!"2023.17.10.0"}
!10 = !{!"a"}
!11 = !{!"a1"}
!12 = !{!"none", !"none"}
!13 = !{!"class.sycl::_V1::vec*", !"class.sycl::_V1::id"}
!14 = !{!"", !""}
!15 = !{ptr addrspace(1) null, ptr null}
!16 = !{i1 true}
!17 = !{i1 false}
!18 = !{i32 5}
!19 = !{i32 0}
!20 = !{ptr @_ZTS6kernelILi4300078EE}
!21 = !{i32 1}
!22 = !{!23, !25}
!23 = !{!24}
!24 = !{i32 44, i32 4}
!25 = !{!26, !27}
!26 = !{i32 38, i32 2}
!27 = !{i32 44, i32 8}
!28 = !{null}
