; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s -mtriple=x86_64-unknown -mattr=+ndd -x86-cmov-converter=false -verify-machineinstrs | FileCheck %s

define i8 @cmov8rr(i8 %0) {
; CHECK-LABEL: cmov8rr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmpb $1, %dil
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    cmovel %edi, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
  %2 = icmp eq i8 %0, 1
  %3 = select i1 %2, i8 %0, i8 1
  ret i8 %3
}

define i16 @cmov16rr(i16 %0) {
; CHECK-LABEL: cmov16rr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmpw $1, %di
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    cmovnel %edi, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
  %2 = icmp ne i16 %0, 1
  %3 = select i1 %2, i16 %0, i16 1
  ret i16 %3
}

define i32 @cmov32rr(i32 %0) {
; CHECK-LABEL: cmov32rr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    testl %edi, %edi
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    cmovnel %edi, %eax
; CHECK-NEXT:    retq
  %2 = icmp ugt i32 %0, 1
  %3 = select i1 %2, i32 %0, i32 1
  ret i32 %3
}

define i64 @cmov64rr(i64 %0) {
; CHECK-LABEL: cmov64rr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    testq %rdi, %rdi
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    cmoveq %rdi, %rax
; CHECK-NEXT:    retq
  %2 = icmp ult i64 %0, 1
  %3 = select i1 %2, i64 %0, i64 1
  ret i64 %3
}

define i8 @cmov8rm(i8 %a, i8 %b, i8 %x, ptr %y.ptr) {
; CHECK-LABEL: cmov8rm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cmpb %sil, %dil
; CHECK-NEXT:    cmoval %edi, %edx, %eax
; CHECK-NEXT:    movzbl (%rcx), %ecx
; CHECK-NEXT:    cmovbel %edx, %ecx
; CHECK-NEXT:    addb %cl, %al
; CHECK-NEXT:    retq
entry:
  %cond = icmp ugt i8 %a, %b
  %y = load i8, ptr %y.ptr
  %z2 = select i1 %cond, i8 %a, i8 %x
  %z1 = select i1 %cond, i8 %y, i8 %x
  %s1 = add i8 %z1, %z2
  ret i8 %s1
}

define i16 @cmov16rm(i16 %a, i16 %b, i16 %x, ptr %y.ptr) {
; CHECK-LABEL: cmov16rm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cmpw %si, %di
; CHECK-NEXT:    cmoval %edi, %edx, %eax
; CHECK-NEXT:    cmovaw (%rcx), %dx, %cx
; CHECK-NEXT:    addl %ecx, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
entry:
  %cond = icmp ugt i16 %a, %b
  %y = load i16, ptr %y.ptr
  %z2 = select i1 %cond, i16 %a, i16 %x
  %z1 = select i1 %cond, i16 %y, i16 %x
  %s1 = add i16 %z1, %z2
  ret i16 %s1
}

define i32 @cmov32rm(i32 %a, i32 %b, i32 %x, ptr %y.ptr) {
; CHECK-LABEL: cmov32rm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cmpl %esi, %edi
; CHECK-NEXT:    cmoval %edi, %edx, %eax
; CHECK-NEXT:    cmoval (%rcx), %edx, %ecx
; CHECK-NEXT:    addl %ecx, %eax
; CHECK-NEXT:    retq
entry:
  %cond = icmp ugt i32 %a, %b
  %y = load i32, ptr %y.ptr
  %z2 = select i1 %cond, i32 %a, i32 %x
  %z1 = select i1 %cond, i32 %y, i32 %x
  %s1 = add i32 %z1, %z2
  ret i32 %s1
}

define i64 @cmov64rm(i64 %a, i64 %b, i64 %x, ptr %y.ptr) {
; CHECK-LABEL: cmov64rm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cmpq %rsi, %rdi
; CHECK-NEXT:    cmovaq %rdi, %rdx, %rax
; CHECK-NEXT:    cmovaq (%rcx), %rdx, %rcx
; CHECK-NEXT:    addq %rcx, %rax
; CHECK-NEXT:    retq
entry:
  %cond = icmp ugt i64 %a, %b
  %y = load i64, ptr %y.ptr
  %z2 = select i1 %cond, i64 %a, i64 %x
  %z1 = select i1 %cond, i64 %y, i64 %x
  %s1 = add i64 %z1, %z2
  ret i64 %s1
}

define i8 @cmov8rm_inv(i8 %a, i8 %x, ptr %y.ptr) {
; CHECK-LABEL: cmov8rm_inv:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    testb %dil, %dil
; CHECK-NEXT:    movzbl (%rdx), %eax
; CHECK-NEXT:    cmovsl %esi, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
entry:
  %y = load i8, ptr %y.ptr
  %cmp = icmp slt i8 %a, 0
  %cmov = select i1 %cmp, i8 %x, i8 %y
  ret i8 %cmov
}

define i16 @cmov16rm_inv(i16 %a, i16 %x, ptr %y.ptr) {
; CHECK-LABEL: cmov16rm_inv:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    testw %di, %di
; CHECK-NEXT:    cmovnsw (%rdx), %si, %ax
; CHECK-NEXT:    retq
entry:
  %y = load i16, ptr %y.ptr
  %cmp = icmp slt i16 %a, 0
  %cmov = select i1 %cmp, i16 %x, i16 %y
  ret i16 %cmov
}

define i32 @cmov32rm_inv(i32 %a, i32 %x, ptr %y.ptr) {
; CHECK-LABEL: cmov32rm_inv:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    testl %edi, %edi
; CHECK-NEXT:    cmovnsl (%rdx), %esi, %eax
; CHECK-NEXT:    retq
entry:
  %y = load i32, ptr %y.ptr
  %cmp = icmp slt i32 %a, 0
  %cmov = select i1 %cmp, i32 %x, i32 %y
  ret i32 %cmov
}

define i64 @cmov64rm_inv(i64 %a, i64 %x, ptr %y.ptr) {
; CHECK-LABEL: cmov64rm_inv:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    testq %rdi, %rdi
; CHECK-NEXT:    cmovnsq (%rdx), %rsi, %rax
; CHECK-NEXT:    retq
entry:
  %y = load i64, ptr %y.ptr
  %cmp = icmp slt i64 %a, 0
  %cmov = select i1 %cmp, i64 %x, i64 %y
  ret i64 %cmov
}
