; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=x86_64-linux -mattr=+movbe,+egpr --show-mc-encoding < %s | FileCheck %s

declare i16 @llvm.bswap.i16(i16) nounwind readnone
declare i32 @llvm.bswap.i32(i32) nounwind readnone
declare i64 @llvm.bswap.i64(i64) nounwind readnone

define void @test1(ptr nocapture %x, i16 %y) nounwind {
; CHECK-LABEL: test1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movbew %si, (%rdi) # EVEX TO LEGACY Compression encoding: [0x66,0x0f,0x38,0xf1,0x37]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %bswap = call i16 @llvm.bswap.i16(i16 %y)
  store i16 %bswap, ptr %x, align 2
  ret void
}

define i16 @test2(ptr %x) nounwind {
; CHECK-LABEL: test2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movbew (%rdi), %ax # EVEX TO LEGACY Compression encoding: [0x66,0x0f,0x38,0xf0,0x07]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %load = load i16, ptr %x, align 2
  %bswap = call i16 @llvm.bswap.i16(i16 %load)
  ret i16 %bswap
}

define void @test3(ptr nocapture %x, i32 %y) nounwind {
; CHECK-LABEL: test3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movbel %esi, (%rdi) # EVEX TO LEGACY Compression encoding: [0x0f,0x38,0xf1,0x37]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %bswap = call i32 @llvm.bswap.i32(i32 %y)
  store i32 %bswap, ptr %x, align 4
  ret void
}

define i32 @test4(ptr %x) nounwind {
; CHECK-LABEL: test4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movbel (%rdi), %eax # EVEX TO LEGACY Compression encoding: [0x0f,0x38,0xf0,0x07]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %load = load i32, ptr %x, align 4
  %bswap = call i32 @llvm.bswap.i32(i32 %load)
  ret i32 %bswap
}

define void @test5(ptr %x, i64 %y) nounwind {
; CHECK-LABEL: test5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movbeq %rsi, (%rdi) # EVEX TO LEGACY Compression encoding: [0x48,0x0f,0x38,0xf1,0x37]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %bswap = call i64 @llvm.bswap.i64(i64 %y)
  store i64 %bswap, ptr %x, align 8
  ret void
}

define i64 @test6(ptr %x) nounwind {
; CHECK-LABEL: test6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movbeq (%rdi), %rax # EVEX TO LEGACY Compression encoding: [0x48,0x0f,0x38,0xf0,0x07]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %load = load i64, ptr %x, align 8
  %bswap = call i64 @llvm.bswap.i64(i64 %load)
  ret i64 %bswap
}
