; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown -mattr=+ndd| FileCheck %s --check-prefix=X64
; RUN: llc < %s -mtriple=x86_64-unknown -mattr=+popcnt,+ndd | FileCheck %s --check-prefix=X64-POPCNT

define i8 @cnt8(i8 %x) nounwind readnone {
; X64-LABEL: cnt8:
; X64:       # %bb.0:
; X64-NEXT:    shrb %dil, %al
; X64-NEXT:    andb $85, %al
; X64-NEXT:    subb %al, %dil, %al
; X64-NEXT:    andb $51, %al, %cl
; X64-NEXT:    shrb $2, %al
; X64-NEXT:    andb $51, %al
; X64-NEXT:    addb %cl, %al
; X64-NEXT:    shrb $4, %al, %cl
; X64-NEXT:    addb %cl, %al
; X64-NEXT:    andb $15, %al
; X64-NEXT:    retq
;
; X64-POPCNT-LABEL: cnt8:
; X64-POPCNT:       # %bb.0:
; X64-POPCNT-NEXT:    movzbl %dil, %eax
; X64-POPCNT-NEXT:    popcntl %eax, %eax
; X64-POPCNT-NEXT:    # kill: def $al killed $al killed $eax
; X64-POPCNT-NEXT:    retq
  %cnt = tail call i8 @llvm.ctpop.i8(i8 %x)
  ret i8 %cnt
}

define i16 @cnt16(i16 %x) nounwind readnone {
; X64-LABEL: cnt16:
; X64:       # %bb.0:
; X64-NEXT:    shrl %edi, %eax
; X64-NEXT:    andl $21845, %eax # imm = 0x5555
; X64-NEXT:    subl %eax, %edi, %eax
; X64-NEXT:    andl $13107, %eax, %ecx # imm = 0x3333
; X64-NEXT:    shrl $2, %eax
; X64-NEXT:    andl $13107, %eax # imm = 0x3333
; X64-NEXT:    addl %ecx, %eax
; X64-NEXT:    shrl $4, %eax, %ecx
; X64-NEXT:    addl %ecx, %eax
; X64-NEXT:    andl $3855, %eax # imm = 0xF0F
; X64-NEXT:    shrl $8, %eax, %ecx
; X64-NEXT:    addl %ecx, %eax
; X64-NEXT:    movzbl %al, %eax
; X64-NEXT:    # kill: def $ax killed $ax killed $eax
; X64-NEXT:    retq
;
; X64-POPCNT-LABEL: cnt16:
; X64-POPCNT:       # %bb.0:
; X64-POPCNT-NEXT:    movzwl %di, %eax
; X64-POPCNT-NEXT:    popcntl %eax, %eax
; X64-POPCNT-NEXT:    # kill: def $ax killed $ax killed $eax
; X64-POPCNT-NEXT:    retq
  %cnt = tail call i16 @llvm.ctpop.i16(i16 %x)
  ret i16 %cnt
}

define i32 @cnt32(i32 %x) nounwind readnone {
; X64-LABEL: cnt32:
; X64:       # %bb.0:
; X64-NEXT:    shrl %edi, %eax
; X64-NEXT:    andl $1431655765, %eax # imm = 0x55555555
; X64-NEXT:    subl %eax, %edi, %eax
; X64-NEXT:    andl $858993459, %eax, %ecx # imm = 0x33333333
; X64-NEXT:    shrl $2, %eax
; X64-NEXT:    andl $858993459, %eax # imm = 0x33333333
; X64-NEXT:    addl %ecx, %eax
; X64-NEXT:    shrl $4, %eax, %ecx
; X64-NEXT:    addl %ecx, %eax
; X64-NEXT:    andl $252645135, %eax # imm = 0xF0F0F0F
; X64-NEXT:    imull $16843009, %eax, %eax # imm = 0x1010101
; X64-NEXT:    shrl $24, %eax
; X64-NEXT:    retq
;
; X64-POPCNT-LABEL: cnt32:
; X64-POPCNT:       # %bb.0:
; X64-POPCNT-NEXT:    popcntl %edi, %eax
; X64-POPCNT-NEXT:    retq
  %cnt = tail call i32 @llvm.ctpop.i32(i32 %x)
  ret i32 %cnt
}

define i64 @cnt64(i64 %x) nounwind readnone {
; X64-LABEL: cnt64:
; X64:       # %bb.0:
; X64-NEXT:    shrq %rdi, %rax
; X64-NEXT:    movabsq $6148914691236517205, %rcx # imm = 0x5555555555555555
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    subq %rax, %rdi, %rax
; X64-NEXT:    movabsq $3689348814741910323, %rcx # imm = 0x3333333333333333
; X64-NEXT:    andq %rcx, %rax, %rdx
; X64-NEXT:    shrq $2, %rax
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    addq %rdx, %rax
; X64-NEXT:    shrq $4, %rax, %rcx
; X64-NEXT:    addq %rcx, %rax
; X64-NEXT:    movabsq $1085102592571150095, %rcx # imm = 0xF0F0F0F0F0F0F0F
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    movabsq $72340172838076673, %rcx # imm = 0x101010101010101
; X64-NEXT:    imulq %rcx, %rax
; X64-NEXT:    shrq $56, %rax
; X64-NEXT:    retq
;
; X64-POPCNT-LABEL: cnt64:
; X64-POPCNT:       # %bb.0:
; X64-POPCNT-NEXT:    popcntq %rdi, %rax
; X64-POPCNT-NEXT:    retq
  %cnt = tail call i64 @llvm.ctpop.i64(i64 %x)
  ret i64 %cnt
}

define i128 @cnt128(i128 %x) nounwind readnone {
; X64-LABEL: cnt128:
; X64:       # %bb.0:
; X64-NEXT:    shrq %rsi, %rax
; X64-NEXT:    movabsq $6148914691236517205, %rcx # imm = 0x5555555555555555
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    subq %rax, %rsi, %rax
; X64-NEXT:    movabsq $3689348814741910323, %rdx # imm = 0x3333333333333333
; X64-NEXT:    andq %rdx, %rax, %rsi
; X64-NEXT:    shrq $2, %rax
; X64-NEXT:    andq %rdx, %rax
; X64-NEXT:    addq %rsi, %rax
; X64-NEXT:    shrq $4, %rax, %rsi
; X64-NEXT:    addq %rsi, %rax
; X64-NEXT:    movabsq $1085102592571150095, %rsi # imm = 0xF0F0F0F0F0F0F0F
; X64-NEXT:    andq %rsi, %rax
; X64-NEXT:    movabsq $72340172838076673, %r8 # imm = 0x101010101010101
; X64-NEXT:    imulq %r8, %rax
; X64-NEXT:    shrq $56, %rax
; X64-NEXT:    shrq %rdi, %r9
; X64-NEXT:    andq %r9, %rcx
; X64-NEXT:    subq %rcx, %rdi, %rcx
; X64-NEXT:    andq %rdx, %rcx, %rdi
; X64-NEXT:    shrq $2, %rcx
; X64-NEXT:    andq %rdx, %rcx
; X64-NEXT:    addq %rdi, %rcx
; X64-NEXT:    shrq $4, %rcx, %rdx
; X64-NEXT:    addq %rdx, %rcx
; X64-NEXT:    andq %rsi, %rcx
; X64-NEXT:    imulq %r8, %rcx
; X64-NEXT:    shrq $56, %rcx
; X64-NEXT:    addq %rcx, %rax
; X64-NEXT:    xorl %edx, %edx
; X64-NEXT:    retq
;
; X64-POPCNT-LABEL: cnt128:
; X64-POPCNT:       # %bb.0:
; X64-POPCNT-NEXT:    popcntq %rsi, %rax
; X64-POPCNT-NEXT:    popcntq %rdi, %rcx
; X64-POPCNT-NEXT:    addq %rcx, %rax
; X64-POPCNT-NEXT:    xorl %edx, %edx
; X64-POPCNT-NEXT:    retq
  %cnt = tail call i128 @llvm.ctpop.i128(i128 %x)
  ret i128 %cnt
}

define i64 @cnt64_noimplicitfloat(i64 %x) nounwind readnone noimplicitfloat  {
; X64-LABEL: cnt64_noimplicitfloat:
; X64:       # %bb.0:
; X64-NEXT:    shrq %rdi, %rax
; X64-NEXT:    movabsq $6148914691236517205, %rcx # imm = 0x5555555555555555
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    subq %rax, %rdi, %rax
; X64-NEXT:    movabsq $3689348814741910323, %rcx # imm = 0x3333333333333333
; X64-NEXT:    andq %rcx, %rax, %rdx
; X64-NEXT:    shrq $2, %rax
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    addq %rdx, %rax
; X64-NEXT:    shrq $4, %rax, %rcx
; X64-NEXT:    addq %rcx, %rax
; X64-NEXT:    movabsq $1085102592571150095, %rcx # imm = 0xF0F0F0F0F0F0F0F
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    movabsq $72340172838076673, %rcx # imm = 0x101010101010101
; X64-NEXT:    imulq %rcx, %rax
; X64-NEXT:    shrq $56, %rax
; X64-NEXT:    retq
;
; X64-POPCNT-LABEL: cnt64_noimplicitfloat:
; X64-POPCNT:       # %bb.0:
; X64-POPCNT-NEXT:    popcntq %rdi, %rax
; X64-POPCNT-NEXT:    retq
  %cnt = tail call i64 @llvm.ctpop.i64(i64 %x)
  ret i64 %cnt
}

define i32 @cnt32_optsize(i32 %x) nounwind readnone optsize {
; X64-LABEL: cnt32_optsize:
; X64:       # %bb.0:
; X64-NEXT:    shrl %edi, %eax
; X64-NEXT:    andl $1431655765, %eax # imm = 0x55555555
; X64-NEXT:    subl %eax, %edi, %eax
; X64-NEXT:    movl $858993459, %ecx # imm = 0x33333333
; X64-NEXT:    andl %ecx, %eax, %edx
; X64-NEXT:    shrl $2, %eax
; X64-NEXT:    andl %ecx, %eax
; X64-NEXT:    addl %edx, %eax
; X64-NEXT:    shrl $4, %eax, %ecx
; X64-NEXT:    addl %ecx, %eax
; X64-NEXT:    andl $252645135, %eax # imm = 0xF0F0F0F
; X64-NEXT:    imull $16843009, %eax, %eax # imm = 0x1010101
; X64-NEXT:    shrl $24, %eax
; X64-NEXT:    retq
;
; X64-POPCNT-LABEL: cnt32_optsize:
; X64-POPCNT:       # %bb.0:
; X64-POPCNT-NEXT:    popcntl %edi, %eax
; X64-POPCNT-NEXT:    retq
  %cnt = tail call i32 @llvm.ctpop.i32(i32 %x)
  ret i32 %cnt
}

define i64 @cnt64_optsize(i64 %x) nounwind readnone optsize {
; X64-LABEL: cnt64_optsize:
; X64:       # %bb.0:
; X64-NEXT:    shrq %rdi, %rax
; X64-NEXT:    movabsq $6148914691236517205, %rcx # imm = 0x5555555555555555
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    subq %rax, %rdi, %rax
; X64-NEXT:    movabsq $3689348814741910323, %rcx # imm = 0x3333333333333333
; X64-NEXT:    andq %rcx, %rax, %rdx
; X64-NEXT:    shrq $2, %rax
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    addq %rdx, %rax
; X64-NEXT:    shrq $4, %rax, %rcx
; X64-NEXT:    addq %rcx, %rax
; X64-NEXT:    movabsq $1085102592571150095, %rcx # imm = 0xF0F0F0F0F0F0F0F
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    movabsq $72340172838076673, %rcx # imm = 0x101010101010101
; X64-NEXT:    imulq %rcx, %rax
; X64-NEXT:    shrq $56, %rax
; X64-NEXT:    retq
;
; X64-POPCNT-LABEL: cnt64_optsize:
; X64-POPCNT:       # %bb.0:
; X64-POPCNT-NEXT:    popcntq %rdi, %rax
; X64-POPCNT-NEXT:    retq
  %cnt = tail call i64 @llvm.ctpop.i64(i64 %x)
  ret i64 %cnt
}

define i128 @cnt128_optsize(i128 %x) nounwind readnone optsize {
; X64-LABEL: cnt128_optsize:
; X64:       # %bb.0:
; X64-NEXT:    shrq %rsi, %rax
; X64-NEXT:    movabsq $6148914691236517205, %rcx # imm = 0x5555555555555555
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    subq %rax, %rsi, %rax
; X64-NEXT:    movabsq $3689348814741910323, %rdx # imm = 0x3333333333333333
; X64-NEXT:    andq %rdx, %rax, %rsi
; X64-NEXT:    shrq $2, %rax
; X64-NEXT:    andq %rdx, %rax
; X64-NEXT:    addq %rsi, %rax
; X64-NEXT:    shrq $4, %rax, %rsi
; X64-NEXT:    addq %rsi, %rax
; X64-NEXT:    movabsq $1085102592571150095, %rsi # imm = 0xF0F0F0F0F0F0F0F
; X64-NEXT:    andq %rsi, %rax
; X64-NEXT:    movabsq $72340172838076673, %r8 # imm = 0x101010101010101
; X64-NEXT:    imulq %r8, %rax
; X64-NEXT:    shrq $56, %rax
; X64-NEXT:    shrq %rdi, %r9
; X64-NEXT:    andq %r9, %rcx
; X64-NEXT:    subq %rcx, %rdi, %rcx
; X64-NEXT:    andq %rdx, %rcx, %rdi
; X64-NEXT:    shrq $2, %rcx
; X64-NEXT:    andq %rdx, %rcx
; X64-NEXT:    addq %rdi, %rcx
; X64-NEXT:    shrq $4, %rcx, %rdx
; X64-NEXT:    addq %rdx, %rcx
; X64-NEXT:    andq %rsi, %rcx
; X64-NEXT:    imulq %r8, %rcx
; X64-NEXT:    shrq $56, %rcx
; X64-NEXT:    addq %rcx, %rax
; X64-NEXT:    xorl %edx, %edx
; X64-NEXT:    retq
;
; X64-POPCNT-LABEL: cnt128_optsize:
; X64-POPCNT:       # %bb.0:
; X64-POPCNT-NEXT:    popcntq %rsi, %rax
; X64-POPCNT-NEXT:    popcntq %rdi, %rcx
; X64-POPCNT-NEXT:    addq %rcx, %rax
; X64-POPCNT-NEXT:    xorl %edx, %edx
; X64-POPCNT-NEXT:    retq
  %cnt = tail call i128 @llvm.ctpop.i128(i128 %x)
  ret i128 %cnt
}

define i32 @cnt32_pgso(i32 %x) nounwind readnone !prof !14 {
; X64-LABEL: cnt32_pgso:
; X64:       # %bb.0:
; X64-NEXT:    shrl %edi, %eax
; X64-NEXT:    andl $1431655765, %eax # imm = 0x55555555
; X64-NEXT:    subl %eax, %edi, %eax
; X64-NEXT:    movl $858993459, %ecx # imm = 0x33333333
; X64-NEXT:    andl %ecx, %eax, %edx
; X64-NEXT:    shrl $2, %eax
; X64-NEXT:    andl %ecx, %eax
; X64-NEXT:    addl %edx, %eax
; X64-NEXT:    shrl $4, %eax, %ecx
; X64-NEXT:    addl %ecx, %eax
; X64-NEXT:    andl $252645135, %eax # imm = 0xF0F0F0F
; X64-NEXT:    imull $16843009, %eax, %eax # imm = 0x1010101
; X64-NEXT:    shrl $24, %eax
; X64-NEXT:    retq
;
; X64-POPCNT-LABEL: cnt32_pgso:
; X64-POPCNT:       # %bb.0:
; X64-POPCNT-NEXT:    popcntl %edi, %eax
; X64-POPCNT-NEXT:    retq
  %cnt = tail call i32 @llvm.ctpop.i32(i32 %x)
  ret i32 %cnt
}

define i64 @cnt64_pgso(i64 %x) nounwind readnone !prof !14 {
; X64-LABEL: cnt64_pgso:
; X64:       # %bb.0:
; X64-NEXT:    shrq %rdi, %rax
; X64-NEXT:    movabsq $6148914691236517205, %rcx # imm = 0x5555555555555555
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    subq %rax, %rdi, %rax
; X64-NEXT:    movabsq $3689348814741910323, %rcx # imm = 0x3333333333333333
; X64-NEXT:    andq %rcx, %rax, %rdx
; X64-NEXT:    shrq $2, %rax
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    addq %rdx, %rax
; X64-NEXT:    shrq $4, %rax, %rcx
; X64-NEXT:    addq %rcx, %rax
; X64-NEXT:    movabsq $1085102592571150095, %rcx # imm = 0xF0F0F0F0F0F0F0F
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    movabsq $72340172838076673, %rcx # imm = 0x101010101010101
; X64-NEXT:    imulq %rcx, %rax
; X64-NEXT:    shrq $56, %rax
; X64-NEXT:    retq
;
; X64-POPCNT-LABEL: cnt64_pgso:
; X64-POPCNT:       # %bb.0:
; X64-POPCNT-NEXT:    popcntq %rdi, %rax
; X64-POPCNT-NEXT:    retq
  %cnt = tail call i64 @llvm.ctpop.i64(i64 %x)
  ret i64 %cnt
}

define i128 @cnt128_pgso(i128 %x) nounwind readnone !prof !14 {
; X64-LABEL: cnt128_pgso:
; X64:       # %bb.0:
; X64-NEXT:    shrq %rsi, %rax
; X64-NEXT:    movabsq $6148914691236517205, %rcx # imm = 0x5555555555555555
; X64-NEXT:    andq %rcx, %rax
; X64-NEXT:    subq %rax, %rsi, %rax
; X64-NEXT:    movabsq $3689348814741910323, %rdx # imm = 0x3333333333333333
; X64-NEXT:    andq %rdx, %rax, %rsi
; X64-NEXT:    shrq $2, %rax
; X64-NEXT:    andq %rdx, %rax
; X64-NEXT:    addq %rsi, %rax
; X64-NEXT:    shrq $4, %rax, %rsi
; X64-NEXT:    addq %rsi, %rax
; X64-NEXT:    movabsq $1085102592571150095, %rsi # imm = 0xF0F0F0F0F0F0F0F
; X64-NEXT:    andq %rsi, %rax
; X64-NEXT:    movabsq $72340172838076673, %r8 # imm = 0x101010101010101
; X64-NEXT:    imulq %r8, %rax
; X64-NEXT:    shrq $56, %rax
; X64-NEXT:    shrq %rdi, %r9
; X64-NEXT:    andq %r9, %rcx
; X64-NEXT:    subq %rcx, %rdi, %rcx
; X64-NEXT:    andq %rdx, %rcx, %rdi
; X64-NEXT:    shrq $2, %rcx
; X64-NEXT:    andq %rdx, %rcx
; X64-NEXT:    addq %rdi, %rcx
; X64-NEXT:    shrq $4, %rcx, %rdx
; X64-NEXT:    addq %rdx, %rcx
; X64-NEXT:    andq %rsi, %rcx
; X64-NEXT:    imulq %r8, %rcx
; X64-NEXT:    shrq $56, %rcx
; X64-NEXT:    addq %rcx, %rax
; X64-NEXT:    xorl %edx, %edx
; X64-NEXT:    retq
;
; X64-POPCNT-LABEL: cnt128_pgso:
; X64-POPCNT:       # %bb.0:
; X64-POPCNT-NEXT:    popcntq %rsi, %rax
; X64-POPCNT-NEXT:    popcntq %rdi, %rcx
; X64-POPCNT-NEXT:    addq %rcx, %rax
; X64-POPCNT-NEXT:    xorl %edx, %edx
; X64-POPCNT-NEXT:    retq
  %cnt = tail call i128 @llvm.ctpop.i128(i128 %x)
  ret i128 %cnt
}

define i32 @popcount_zext_i32(i16 zeroext %x) {
; X64-LABEL: popcount_zext_i32:
; X64:       # %bb.0:
; X64-NEXT:    shrl %edi, %eax
; X64-NEXT:    andl $21845, %eax # imm = 0x5555
; X64-NEXT:    subl %eax, %edi, %eax
; X64-NEXT:    andl $13107, %eax, %ecx # imm = 0x3333
; X64-NEXT:    shrl $2, %eax
; X64-NEXT:    andl $13107, %eax # imm = 0x3333
; X64-NEXT:    addl %ecx, %eax
; X64-NEXT:    shrl $4, %eax, %ecx
; X64-NEXT:    addl %ecx, %eax
; X64-NEXT:    andl $3855, %eax # imm = 0xF0F
; X64-NEXT:    shrl $8, %eax, %ecx
; X64-NEXT:    addl %ecx, %eax
; X64-NEXT:    movzbl %al, %eax
; X64-NEXT:    retq
;
; X64-POPCNT-LABEL: popcount_zext_i32:
; X64-POPCNT:       # %bb.0:
; X64-POPCNT-NEXT:    popcntl %edi, %eax
; X64-POPCNT-NEXT:    retq
  %cnt = tail call i16 @llvm.ctpop.i16(i16 %x)
  %z = zext i16 %cnt to i32
  ret i32 %z
}

declare i8 @llvm.ctpop.i8(i8) nounwind readnone
declare i16 @llvm.ctpop.i16(i16) nounwind readnone
declare i32 @llvm.ctpop.i32(i32) nounwind readnone
declare i64 @llvm.ctpop.i64(i64) nounwind readnone
declare i128 @llvm.ctpop.i128(i128) nounwind readnone

!llvm.module.flags = !{!0}
!0 = !{i32 1, !"ProfileSummary", !1}
!1 = !{!2, !3, !4, !5, !6, !7, !8, !9}
!2 = !{!"ProfileFormat", !"InstrProf"}
!3 = !{!"TotalCount", i64 10000}
!4 = !{!"MaxCount", i64 10}
!5 = !{!"MaxInternalCount", i64 1}
!6 = !{!"MaxFunctionCount", i64 1000}
!7 = !{!"NumCounts", i64 3}
!8 = !{!"NumFunctions", i64 3}
!9 = !{!"DetailedSummary", !10}
!10 = !{!11, !12, !13}
!11 = !{i32 10000, i64 100, i32 1}
!12 = !{i32 999000, i64 100, i32 1}
!13 = !{i32 999999, i64 1, i32 2}
!14 = !{!"function_entry_count", i64 0}
