; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown -mattr=+ndd -verify-machineinstrs | FileCheck %s

define i8 @ror8m1(ptr %ptr) {
; CHECK-LABEL: ror8m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rorb (%rdi), %al
; CHECK-NEXT:    retq
entry:
  %a = load i8, ptr %ptr
  %0 = lshr i8 %a, 1
  %1 = shl i8 %a, 7
  %ror = or i8 %0, %1
  ret i8 %ror
}

define i16 @ror16m1(ptr %ptr) {
; CHECK-LABEL: ror16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rorw (%rdi), %ax
; CHECK-NEXT:    retq
entry:
  %a = load i16, ptr %ptr
  %0 = lshr i16 %a, 1
  %1 = shl i16 %a, 15
  %ror = or i16 %0, %1
  ret i16 %ror
}

define i32 @ror32m1(ptr %ptr) {
; CHECK-LABEL: ror32m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rorl (%rdi), %eax
; CHECK-NEXT:    retq
entry:
  %a = load i32, ptr %ptr
  %0 = lshr i32 %a, 1
  %1 = shl i32 %a, 31
  %ror = or i32 %0, %1
  ret i32 %ror
}

define i64 @ror64m1(ptr %ptr) {
; CHECK-LABEL: ror64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rorq (%rdi), %rax
; CHECK-NEXT:    retq
entry:
  %a = load i64, ptr %ptr
  %0 = lshr i64 %a, 1
  %1 = shl i64 %a, 63
  %ror = or i64 %0, %1
  ret i64 %ror
}

define i8 @ror8mcl(ptr %ptr, i8 %cl) {
; CHECK-LABEL: ror8mcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    rorb %cl, (%rdi), %al
; CHECK-NEXT:    retq
entry:
  %a = load i8, ptr %ptr
  %0 = lshr i8 %a, %cl
  %1 = sub i8 8, %cl
  %2 = shl i8 %a, %1
  %ror = or i8 %0, %2
  ret i8 %ror
}

define i16 @ror16mcl(ptr %ptr, i16 %cl) {
; CHECK-LABEL: ror16mcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    rorw %cl, (%rdi), %ax
; CHECK-NEXT:    retq
entry:
  %a = load i16, ptr %ptr
  %0 = lshr i16 %a, %cl
  %1 = sub i16 16, %cl
  %2 = shl i16 %a, %1
  %ror = or i16 %0, %2
  ret i16 %ror
}

define i32 @ror32mcl(ptr %ptr, i32 %cl) {
; CHECK-LABEL: ror32mcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    rorl %cl, (%rdi), %eax
; CHECK-NEXT:    retq
entry:
  %a = load i32, ptr %ptr
  %0 = lshr i32 %a, %cl
  %1 = sub i32 32, %cl
  %2 = shl i32 %a, %1
  %ror = or i32 %0, %2
  ret i32 %ror
}

define i64 @ror64mcl(ptr %ptr, i64 %cl) {
; CHECK-LABEL: ror64mcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $rcx
; CHECK-NEXT:    rorq %cl, (%rdi), %rax
; CHECK-NEXT:    retq
entry:
  %a = load i64, ptr %ptr
  %0 = lshr i64 %a, %cl
  %1 = sub i64 64, %cl
  %2 = shl i64 %a, %1
  %ror = or i64 %0, %2
  ret i64 %ror
}

define i8 @ror8mi(ptr %ptr) {
; CHECK-LABEL: ror8mi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rolb $5, (%rdi), %al
; CHECK-NEXT:    retq
entry:
  %a = load i8, ptr %ptr
  %0 = lshr i8 %a, 3
  %1 = shl i8 %a, 5
  %ror = or i8 %0, %1
  ret i8 %ror
}

define i16 @ror16mi(ptr %ptr) {
; CHECK-LABEL: ror16mi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rolw $13, (%rdi), %ax
; CHECK-NEXT:    retq
entry:
  %a = load i16, ptr %ptr
  %0 = lshr i16 %a, 3
  %1 = shl i16 %a, 13
  %ror = or i16 %0, %1
  ret i16 %ror
}

define i32 @ror32mi(ptr %ptr) {
; CHECK-LABEL: ror32mi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    roll $29, (%rdi), %eax
; CHECK-NEXT:    retq
entry:
  %a = load i32, ptr %ptr
  %0 = lshr i32 %a, 3
  %1 = shl i32 %a, 29
  %ror = or i32 %0, %1
  ret i32 %ror
}

define i64 @ror64mi(ptr %ptr) {
; CHECK-LABEL: ror64mi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rolq $61, (%rdi), %rax
; CHECK-NEXT:    retq
entry:
  %a = load i64, ptr %ptr
  %0 = lshr i64 %a, 3
  %1 = shl i64 %a, 61
  %ror = or i64 %0, %1
  ret i64 %ror
}

define i8 @ror8r1(i8 noundef %a) {
; CHECK-LABEL: ror8r1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rorb %dil, %al
; CHECK-NEXT:    retq
entry:
  %0 = lshr i8 %a, 1
  %1 = shl i8 %a, 7
  %ror = or i8 %0, %1
  ret i8 %ror
}

define i16 @ror16r1(i16 noundef %a) {
; CHECK-LABEL: ror16r1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rorw %di, %ax
; CHECK-NEXT:    retq
entry:
  %0 = lshr i16 %a, 1
  %1 = shl i16 %a, 15
  %ror = or i16 %0, %1
  ret i16 %ror
}

define i32 @ror32r1(i32 noundef %a) {
; CHECK-LABEL: ror32r1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rorl %edi, %eax
; CHECK-NEXT:    retq
entry:
  %0 = lshr i32 %a, 1
  %1 = shl i32 %a, 31
  %ror = or i32 %0, %1
  ret i32 %ror
}

define i64 @ror64r1(i64 noundef %a) {
; CHECK-LABEL: ror64r1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rorq %rdi, %rax
; CHECK-NEXT:    retq
entry:
  %0 = lshr i64 %a, 1
  %1 = shl i64 %a, 63
  %ror = or i64 %0, %1
  ret i64 %ror
}

define i8 @ror8rcl(i8 noundef %a, i8 %cl) {
; CHECK-LABEL: ror8rcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    rorb %cl, %dil, %al
; CHECK-NEXT:    retq
entry:
  %0 = lshr i8 %a, %cl
  %1 = sub i8 8, %cl
  %2 = shl i8 %a, %1
  %ror = or i8 %0, %2
  ret i8 %ror
}

define i16 @ror16rcl(i16 noundef %a, i16 %cl) {
; CHECK-LABEL: ror16rcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    rorw %cl, %di, %ax
; CHECK-NEXT:    retq
entry:
  %0 = lshr i16 %a, %cl
  %1 = sub i16 16, %cl
  %2 = shl i16 %a, %1
  %ror = or i16 %0, %2
  ret i16 %ror
}

define i32 @ror32rcl(i32 noundef %a, i32 %cl) {
; CHECK-LABEL: ror32rcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    rorl %cl, %edi, %eax
; CHECK-NEXT:    retq
entry:
  %0 = lshr i32 %a, %cl
  %1 = sub i32 32, %cl
  %2 = shl i32 %a, %1
  %ror = or i32 %0, %2
  ret i32 %ror
}

define i64 @ror64rcl(i64 noundef %a, i64 %cl) {
; CHECK-LABEL: ror64rcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $rcx
; CHECK-NEXT:    rorq %cl, %rdi, %rax
; CHECK-NEXT:    retq
entry:
  %0 = lshr i64 %a, %cl
  %1 = sub i64 64, %cl
  %2 = shl i64 %a, %1
  %ror = or i64 %0, %2
  ret i64 %ror
}

define i8 @ror8ri(i8 noundef %a) {
; CHECK-LABEL: ror8ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rolb $5, %dil, %al
; CHECK-NEXT:    retq
entry:
  %0 = lshr i8 %a, 3
  %1 = shl i8 %a, 5
  %ror = or i8 %0, %1
  ret i8 %ror
}

define i16 @ror16ri(i16 noundef %a) {
; CHECK-LABEL: ror16ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rolw $13, %di, %ax
; CHECK-NEXT:    retq
entry:
  %0 = lshr i16 %a, 3
  %1 = shl i16 %a, 13
  %ror = or i16 %0, %1
  ret i16 %ror
}

define i32 @ror32ri(i32 noundef %a) {
; CHECK-LABEL: ror32ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    roll $29, %edi, %eax
; CHECK-NEXT:    retq
entry:
  %0 = lshr i32 %a, 3
  %1 = shl i32 %a, 29
  %ror = or i32 %0, %1
  ret i32 %ror
}

define i64 @ror64ri(i64 noundef %a) {
; CHECK-LABEL: ror64ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rolq $61, %rdi, %rax
; CHECK-NEXT:    retq
entry:
  %0 = lshr i64 %a, 3
  %1 = shl i64 %a, 61
  %ror = or i64 %0, %1
  ret i64 %ror
}

define void @ror8m1_legacy(ptr %ptr) {
; CHECK-LABEL: ror8m1_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rolb $7, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i8, ptr %ptr
  %0 = lshr i8 %a, 1
  %1 = shl i8 %a, 7
  %ror = or i8 %0, %1
  store i8 %ror, ptr %ptr
  ret void
}

define void @ror16m1_legacy(ptr %ptr) {
; CHECK-LABEL: ror16m1_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movzwl (%rdi), %eax
; CHECK-NEXT:    shrl %eax, %ecx
; CHECK-NEXT:    shll $7, %eax
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    movw %ax, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i16, ptr %ptr
  %0 = lshr i16 %a, 1
  %1 = shl i16 %a, 7
  %ror = or i16 %0, %1
  store i16 %ror, ptr %ptr
  ret void
}

define void @ror32m1_legacy(ptr %ptr) {
; CHECK-LABEL: ror32m1_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl (%rdi), %eax
; CHECK-NEXT:    shrl %eax, %ecx
; CHECK-NEXT:    shll $7, %eax
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    movl %eax, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i32, ptr %ptr
  %0 = lshr i32 %a, 1
  %1 = shl i32 %a, 7
  %ror = or i32 %0, %1
  store i32 %ror, ptr %ptr
  ret void
}

define void @ror64m1_legacy(ptr %ptr) {
; CHECK-LABEL: ror64m1_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq (%rdi), %rax
; CHECK-NEXT:    shrq %rax, %rcx
; CHECK-NEXT:    shlq $7, %rax
; CHECK-NEXT:    orq %rcx, %rax
; CHECK-NEXT:    movq %rax, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i64, ptr %ptr
  %0 = lshr i64 %a, 1
  %1 = shl i64 %a, 7
  %ror = or i64 %0, %1
  store i64 %ror, ptr %ptr
  ret void
}

define void @ror8mcl_legacy(ptr %ptr, i8 %cl) {
; CHECK-LABEL: ror8mcl_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    rorb %cl, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i8, ptr %ptr
  %0 = lshr i8 %a, %cl
  %1 = sub i8 8, %cl
  %2 = shl i8 %a, %1
  %ror = or i8 %0, %2
  store i8 %ror, ptr %ptr
  ret void
}

define void @ror16mcl_legacy(ptr %ptr, i16 %cl) {
; CHECK-LABEL: ror16mcl_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    rorw %cl, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i16, ptr %ptr
  %0 = lshr i16 %a, %cl
  %1 = sub i16 16, %cl
  %2 = shl i16 %a, %1
  %ror = or i16 %0, %2
  store i16 %ror, ptr %ptr
  ret void
}

define void @ror32mcl_legacy(ptr %ptr, i32 %cl) {
; CHECK-LABEL: ror32mcl_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    rorl %cl, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i32, ptr %ptr
  %0 = lshr i32 %a, %cl
  %1 = sub i32 32, %cl
  %2 = shl i32 %a, %1
  %ror = or i32 %0, %2
  store i32 %ror, ptr %ptr
  ret void
}

define void @ror64mcl_legacy(ptr %ptr, i64 %cl) {
; CHECK-LABEL: ror64mcl_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $rcx
; CHECK-NEXT:    rorq %cl, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i64, ptr %ptr
  %0 = lshr i64 %a, %cl
  %1 = sub i64 64, %cl
  %2 = shl i64 %a, %1
  %ror = or i64 %0, %2
  store i64 %ror, ptr %ptr
  ret void
}

define void @ror8mi_legacy(ptr %ptr) {
; CHECK-LABEL: ror8mi_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    rolb $5, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i8, ptr %ptr
  %0 = lshr i8 %a, 3
  %1 = shl i8 %a, 5
  %ror = or i8 %0, %1
  store i8 %ror, ptr %ptr
  ret void
}

define void @ror16mi_legacy(ptr %ptr) {
; CHECK-LABEL: ror16mi_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movzwl (%rdi), %eax
; CHECK-NEXT:    shrl $3, %eax, %ecx
; CHECK-NEXT:    shll $5, %eax
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    movw %ax, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i16, ptr %ptr
  %0 = lshr i16 %a, 3
  %1 = shl i16 %a, 5
  %ror = or i16 %0, %1
  store i16 %ror, ptr %ptr
  ret void
}

define void @ror32mi_legacy(ptr %ptr) {
; CHECK-LABEL: ror32mi_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl (%rdi), %eax
; CHECK-NEXT:    shrl $3, %eax, %ecx
; CHECK-NEXT:    shll $5, %eax
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    movl %eax, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i32, ptr %ptr
  %0 = lshr i32 %a, 3
  %1 = shl i32 %a, 5
  %ror = or i32 %0, %1
  store i32 %ror, ptr %ptr
  ret void
}

define void @ror64mi_legacy(ptr %ptr) {
; CHECK-LABEL: ror64mi_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq (%rdi), %rax
; CHECK-NEXT:    shrq $3, %rax, %rcx
; CHECK-NEXT:    shlq $5, %rax
; CHECK-NEXT:    orq %rcx, %rax
; CHECK-NEXT:    movq %rax, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i64, ptr %ptr
  %0 = lshr i64 %a, 3
  %1 = shl i64 %a, 5
  %ror = or i64 %0, %1
  store i64 %ror, ptr %ptr
  ret void
}
