; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown -mattr=+ndd -verify-machineinstrs | FileCheck %s

define i8 @shr8m1(ptr %ptr) {
; CHECK-LABEL: shr8m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrb (%rdi), %al
; CHECK-NEXT:    retq
entry:
  %a = load i8, ptr %ptr
  %shr = lshr i8 %a, 1
  ret i8 %shr
}

define i16 @shr16m1(ptr %ptr) {
; CHECK-LABEL: shr16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movzwl (%rdi), %eax
; CHECK-NEXT:    shrl %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
entry:
  %a = load i16, ptr %ptr
  %shr = lshr i16 %a, 1
  ret i16 %shr
}

define i32 @shr32m1(ptr %ptr) {
; CHECK-LABEL: shr32m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrl (%rdi), %eax
; CHECK-NEXT:    retq
entry:
  %a = load i32, ptr %ptr
  %shr = lshr i32 %a, 1
  ret i32 %shr
}

define i64 @shr64m1(ptr %ptr) {
; CHECK-LABEL: shr64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrq (%rdi), %rax
; CHECK-NEXT:    retq
entry:
  %a = load i64, ptr %ptr
  %shr = lshr i64 %a, 1
  ret i64 %shr
}

define i8 @shr8mcl(ptr %ptr, i8 %cl) {
; CHECK-LABEL: shr8mcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrb %cl, (%rdi), %al
; CHECK-NEXT:    retq
entry:
  %a = load i8, ptr %ptr
  %shr = lshr i8 %a, %cl
  ret i8 %shr
}

define i16 @shr16mcl(ptr %ptr, i16 %cl) {
; CHECK-LABEL: shr16mcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    movzwl (%rdi), %eax
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
entry:
  %a = load i16, ptr %ptr
  %shr = lshr i16 %a, %cl
  ret i16 %shr
}

define i32 @shr32mcl(ptr %ptr, i32 %cl) {
; CHECK-LABEL: shr32mcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, (%rdi), %eax
; CHECK-NEXT:    retq
entry:
  %a = load i32, ptr %ptr
  %shr = lshr i32 %a, %cl
  ret i32 %shr
}

define i64 @shr64mcl(ptr %ptr, i64 %cl) {
; CHECK-LABEL: shr64mcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $rcx
; CHECK-NEXT:    shrq %cl, (%rdi), %rax
; CHECK-NEXT:    retq
entry:
  %a = load i64, ptr %ptr
  %shr = lshr i64 %a, %cl
  ret i64 %shr
}

define i8 @shr8mi(ptr %ptr) {
; CHECK-LABEL: shr8mi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrb $4, (%rdi), %al
; CHECK-NEXT:    retq
entry:
  %a = load i8, ptr %ptr
  %shr = lshr i8 %a, 4
  ret i8 %shr
}

define i16 @shr16mi(ptr %ptr) {
; CHECK-LABEL: shr16mi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movzwl (%rdi), %eax
; CHECK-NEXT:    shrl $4, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
entry:
  %a = load i16, ptr %ptr
  %shr = lshr i16 %a, 4
  ret i16 %shr
}

define i32 @shr32mi(ptr %ptr) {
; CHECK-LABEL: shr32mi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrl $4, (%rdi), %eax
; CHECK-NEXT:    retq
entry:
  %a = load i32, ptr %ptr
  %shr = lshr i32 %a, 4
  ret i32 %shr
}

define i64 @shr64mi(ptr %ptr) {
; CHECK-LABEL: shr64mi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrq $4, (%rdi), %rax
; CHECK-NEXT:    retq
entry:
  %a = load i64, ptr %ptr
  %shr = lshr i64 %a, 4
  ret i64 %shr
}

define i8 @shr8r1(i8 noundef %a) {
; CHECK-LABEL: shr8r1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrb %dil, %al
; CHECK-NEXT:    retq
entry:
  %shr = lshr i8 %a, 1
  ret i8 %shr
}

define i16 @shr16r1(i16 noundef %a) {
; CHECK-LABEL: shr16r1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movzwl %di, %eax
; CHECK-NEXT:    shrl %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
entry:
  %shr = lshr i16 %a, 1
  ret i16 %shr
}

define i32 @shr32r1(i32 noundef %a) {
; CHECK-LABEL: shr32r1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrl %edi, %eax
; CHECK-NEXT:    retq
entry:
  %shr = lshr i32 %a, 1
  ret i32 %shr
}

define i64 @shr64r1(i64 noundef %a) {
; CHECK-LABEL: shr64r1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrq %rdi, %rax
; CHECK-NEXT:    retq
entry:
  %shr = lshr i64 %a, 1
  ret i64 %shr
}

define i8 @shr8rcl(i8 noundef %a, i8 %cl) {
; CHECK-LABEL: shr8rcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrb %cl, %dil, %al
; CHECK-NEXT:    retq
entry:
  %shr = lshr i8 %a, %cl
  ret i8 %shr
}

define i16 @shr16rcl(i16 noundef %a, i16 %cl) {
; CHECK-LABEL: shr16rcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    movzwl %di, %eax
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
entry:
  %shr = lshr i16 %a, %cl
  ret i16 %shr
}

define i32 @shr32rcl(i32 noundef %a, i32 %cl) {
; CHECK-LABEL: shr32rcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, %edi, %eax
; CHECK-NEXT:    retq
entry:
  %shr = lshr i32 %a, %cl
  ret i32 %shr
}

define i64 @shr64rcl(i64 noundef %a, i64 %cl) {
; CHECK-LABEL: shr64rcl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $rcx
; CHECK-NEXT:    shrq %cl, %rdi, %rax
; CHECK-NEXT:    retq
entry:
  %shr = lshr i64 %a, %cl
  ret i64 %shr
}

define i8 @shr8ri(i8 noundef %a) {
; CHECK-LABEL: shr8ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrb $4, %dil, %al
; CHECK-NEXT:    retq
entry:
  %shr = lshr i8 %a, 4
  ret i8 %shr
}

define i16 @shr16ri(i16 noundef %a) {
; CHECK-LABEL: shr16ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movzwl %di, %eax
; CHECK-NEXT:    shrl $4, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
entry:
  %shr = lshr i16 %a, 4
  ret i16 %shr
}

define i32 @shr32ri(i32 noundef %a) {
; CHECK-LABEL: shr32ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrl $4, %edi, %eax
; CHECK-NEXT:    retq
entry:
  %shr = lshr i32 %a, 4
  ret i32 %shr
}

define i64 @shr64ri(i64 noundef %a) {
; CHECK-LABEL: shr64ri:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrq $4, %rdi, %rax
; CHECK-NEXT:    retq
entry:
  %shr = lshr i64 %a, 4
  ret i64 %shr
}

define void @shr8m1_legacy(ptr %ptr) {
; CHECK-LABEL: shr8m1_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrb (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i8, ptr %ptr
  %shr = lshr i8 %a, 1
  store i8 %shr, ptr %ptr
  ret void
}

define void @shr16m1_legacy(ptr %ptr) {
; CHECK-LABEL: shr16m1_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrw (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i16, ptr %ptr
  %shr = lshr i16 %a, 1
  store i16 %shr, ptr %ptr
  ret void
}

define void @shr32m1_legacy(ptr %ptr) {
; CHECK-LABEL: shr32m1_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrl (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i32, ptr %ptr
  %shr = lshr i32 %a, 1
  store i32 %shr, ptr %ptr
  ret void
}

define void @shr64m1_legacy(ptr %ptr) {
; CHECK-LABEL: shr64m1_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrq (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i64, ptr %ptr
  %shr = lshr i64 %a, 1
  store i64 %shr, ptr %ptr
  ret void
}

define void @shr8mi_legacy(ptr %ptr) {
; CHECK-LABEL: shr8mi_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrb $4, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i8, ptr %ptr
  %shr = lshr i8 %a, 4
  store i8 %shr, ptr %ptr
  ret void
}

define void @shr16mi_legacy(ptr %ptr) {
; CHECK-LABEL: shr16mi_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrw $4, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i16, ptr %ptr
  %shr = lshr i16 %a, 4
  store i16 %shr, ptr %ptr
  ret void
}

define void @shr32mi_legacy(ptr %ptr) {
; CHECK-LABEL: shr32mi_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrl $4, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i32, ptr %ptr
  %shr = lshr i32 %a, 4
  store i32 %shr, ptr %ptr
  ret void
}

define void @shr64mi_legacy(ptr %ptr) {
; CHECK-LABEL: shr64mi_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shrq $4, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i64, ptr %ptr
  %shr = lshr i64 %a, 4
  store i64 %shr, ptr %ptr
  ret void
}

define void @shr8mcl_legacy(ptr %ptr, i8 %cl) {
; CHECK-LABEL: shr8mcl_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrb %cl, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i8, ptr %ptr
  %shr = lshr i8 %a, %cl
  store i8 %shr, ptr %ptr
  ret void
}

define void @shr16mcl_legacy(ptr %ptr, i16 %cl) {
; CHECK-LABEL: shr16mcl_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrw %cl, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i16, ptr %ptr
  %shr = lshr i16 %a, %cl
  store i16 %shr, ptr %ptr
  ret void
}

define void @shr32mcl_legacy(ptr %ptr, i32 %cl) {
; CHECK-LABEL: shr32mcl_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i32, ptr %ptr
  %shr = lshr i32 %a, %cl
  store i32 %shr, ptr %ptr
  ret void
}

define void @shr64mcl_legacy(ptr %ptr, i64 %cl) {
; CHECK-LABEL: shr64mcl_legacy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $rcx
; CHECK-NEXT:    shrq %cl, (%rdi)
; CHECK-NEXT:    retq
entry:
  %a = load i64, ptr %ptr
  %shr = lshr i64 %a, %cl
  store i64 %shr, ptr %ptr
  ret void
}
