; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-- -mattr=-macrofusion,+branchfusion,+ndd -post-RA-scheduler=0 | FileCheck %s --check-prefixes=BRANCHFUSIONONLY_NOPOSTRA
; RUN: llc < %s -mtriple=x86_64-- -mattr=+macrofusion,-branchfusion,+ndd -post-RA-scheduler=0 | FileCheck %s --check-prefixes=MACROFUSION_NOPOSTRA

; testb should be scheduled right before je to enable macro-fusion.

define i32 @macrofuse_test_je(i32 %flags, ptr %p) nounwind {
; BRANCHFUSIONONLY_NOPOSTRA-LABEL: macrofuse_test_je:
; BRANCHFUSIONONLY_NOPOSTRA:       # %bb.0: # %entry
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    xorl %eax, %eax
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    movb $1, (%rsi)
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    testl $512, %edi # imm = 0x200
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    je .LBB0_2
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:  # %bb.1: # %if.then
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    movl $1, %eax
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:  .LBB0_2: # %if.end
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    retq
;
; MACROFUSION_NOPOSTRA-LABEL: macrofuse_test_je:
; MACROFUSION_NOPOSTRA:       # %bb.0: # %entry
; MACROFUSION_NOPOSTRA-NEXT:    xorl %eax, %eax
; MACROFUSION_NOPOSTRA-NEXT:    movb $1, (%rsi)
; MACROFUSION_NOPOSTRA-NEXT:    testl $512, %edi # imm = 0x200
; MACROFUSION_NOPOSTRA-NEXT:    je .LBB0_2
; MACROFUSION_NOPOSTRA-NEXT:  # %bb.1: # %if.then
; MACROFUSION_NOPOSTRA-NEXT:    movl $1, %eax
; MACROFUSION_NOPOSTRA-NEXT:  .LBB0_2: # %if.end
; MACROFUSION_NOPOSTRA-NEXT:    retq
entry:
  %and = and i32 %flags, 512
  %tobool = icmp eq i32 %and, 0
  store i8 1, ptr %p
  br i1 %tobool, label %if.end, label %if.then

if.then:
  br label %if.end

if.end:
  %hasflag = phi i32 [ 1, %if.then ], [ 0, %entry ]
  ret i32 %hasflag
}

define i32 @macrofuse_cmp_je(i32 %flags, ptr %p) nounwind {
; BRANCHFUSIONONLY_NOPOSTRA-LABEL: macrofuse_cmp_je:
; BRANCHFUSIONONLY_NOPOSTRA:       # %bb.0: # %entry
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    movb $1, (%rsi)
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    cmpl $512, %edi # imm = 0x200
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    je .LBB1_1
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:  # %bb.2: # %if.then
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    movl $1, %eax
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    retq
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:  .LBB1_1:
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    xorl %eax, %eax
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    retq
;
; MACROFUSION_NOPOSTRA-LABEL: macrofuse_cmp_je:
; MACROFUSION_NOPOSTRA:       # %bb.0: # %entry
; MACROFUSION_NOPOSTRA-NEXT:    movb $1, (%rsi)
; MACROFUSION_NOPOSTRA-NEXT:    cmpl $512, %edi # imm = 0x200
; MACROFUSION_NOPOSTRA-NEXT:    je .LBB1_1
; MACROFUSION_NOPOSTRA-NEXT:  # %bb.2: # %if.then
; MACROFUSION_NOPOSTRA-NEXT:    movl $1, %eax
; MACROFUSION_NOPOSTRA-NEXT:    retq
; MACROFUSION_NOPOSTRA-NEXT:  .LBB1_1:
; MACROFUSION_NOPOSTRA-NEXT:    xorl %eax, %eax
; MACROFUSION_NOPOSTRA-NEXT:    retq
entry:
  %sub = sub i32 %flags, 512
  %tobool = icmp eq i32 %sub, 0
  store i8 1, ptr %p
  br i1 %tobool, label %if.end, label %if.then

if.then:
  br label %if.end

if.end:
  %hasflag = phi i32 [ 1, %if.then ], [ 0, %entry ]
  ret i32 %hasflag
}

define i32 @macrofuse_alu_je(i32 %flags, ptr %p) nounwind {
; BRANCHFUSIONONLY_NOPOSTRA-LABEL: macrofuse_alu_je:
; BRANCHFUSIONONLY_NOPOSTRA:       # %bb.0: # %entry
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    addl $-512, %edi, %eax # imm = 0xFE00
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    movb $1, (%rsi)
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    je .LBB2_2
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:  # %bb.1: # %if.then
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    movl $1, %eax
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:  .LBB2_2: # %if.end
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    retq
;
; MACROFUSION_NOPOSTRA-LABEL: macrofuse_alu_je:
; MACROFUSION_NOPOSTRA:       # %bb.0: # %entry
; MACROFUSION_NOPOSTRA-NEXT:    movb $1, (%rsi)
; MACROFUSION_NOPOSTRA-NEXT:    addl $-512, %edi, %eax # imm = 0xFE00
; MACROFUSION_NOPOSTRA-NEXT:    je .LBB2_2
; MACROFUSION_NOPOSTRA-NEXT:  # %bb.1: # %if.then
; MACROFUSION_NOPOSTRA-NEXT:    movl $1, %eax
; MACROFUSION_NOPOSTRA-NEXT:  .LBB2_2: # %if.end
; MACROFUSION_NOPOSTRA-NEXT:    retq
entry:
  %sub = sub i32 %flags, 512
  %tobool = icmp eq i32 %sub, 0
  store i8 1, ptr %p
  br i1 %tobool, label %if.end, label %if.then

if.then:
  br label %if.end

if.end:
  %hasflag = phi i32 [ 1, %if.then ], [ %sub, %entry ]
  ret i32 %hasflag
}

define i32 @macrofuse_dec_je(i32 %flags, ptr %p) nounwind {
; BRANCHFUSIONONLY_NOPOSTRA-LABEL: macrofuse_dec_je:
; BRANCHFUSIONONLY_NOPOSTRA:       # %bb.0: # %entry
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    decl %edi, %eax
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    movb $1, (%rsi)
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    je .LBB3_2
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:  # %bb.1: # %if.then
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    movl $1, %eax
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:  .LBB3_2: # %if.end
; BRANCHFUSIONONLY_NOPOSTRA-NEXT:    retq
;
; MACROFUSION_NOPOSTRA-LABEL: macrofuse_dec_je:
; MACROFUSION_NOPOSTRA:       # %bb.0: # %entry
; MACROFUSION_NOPOSTRA-NEXT:    movb $1, (%rsi)
; MACROFUSION_NOPOSTRA-NEXT:    decl %edi, %eax
; MACROFUSION_NOPOSTRA-NEXT:    je .LBB3_2
; MACROFUSION_NOPOSTRA-NEXT:  # %bb.1: # %if.then
; MACROFUSION_NOPOSTRA-NEXT:    movl $1, %eax
; MACROFUSION_NOPOSTRA-NEXT:  .LBB3_2: # %if.end
; MACROFUSION_NOPOSTRA-NEXT:    retq
entry:
  %sub = sub i32 %flags, 1
  %tobool = icmp eq i32 %sub, 0
  store i8 1, ptr %p
  br i1 %tobool, label %if.end, label %if.then

if.then:
  br label %if.end

if.end:
  %hasflag = phi i32 [ 1, %if.then ], [ %sub, %entry ]
  ret i32 %hasflag
}
