<<<<<<< HEAD:.github/workflows/sycl_precommit.yml
name: SYCL
=======
name: SYCL Pre Commit on Linux
>>>>>>> 8d87832f2eccc0c8dae11e1ae8009a3816f2018a:.github/workflows/sycl_precommit_linux.yml

on:
  pull_request:
    branches:
    - sycl
<<<<<<< HEAD:.github/workflows/sycl_precommit_linux.yml
=======
    - sycl-devops-pr/**
    # Do not run builds if changes are only in the following locations
    paths-ignore:
    - '.github/ISSUE_TEMPLATE/**'
    - '.github/CODEOWNERS'
    - 'sycl/doc/**'
    - 'sycl/gdb/**'
    - 'clang/docs/**'
    - '**.md'
    - '**.rst'
    - '.github/workflows/sycl_windows_*.yml'
    - 'devops/containers/**'
    - 'devops/actions/build_container/**'
>>>>>>> 68bff9ffaffa8bce67b2632c7e2d9ec09b1481b2:.github/workflows/sycl_linux_precommit.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/intel/llvm/sycl_ubuntu2004_nightly:no-drivers
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Run clang-format
      uses: ./devops/actions/clang-format
<<<<<<< HEAD:.github/workflows/sycl_precommit.yml
=======
      with:
        path: src

  # This job generates matrix of tests for SYCL End-to-End tests
  test_matrix:
    needs: [detect_changes]
    if: |
      !contains(needs.detect_changes.outputs.filters, 'ci')
    name: Generate Test Matrix
    uses: ./.github/workflows/sycl_gen_test_matrix.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      lts_config: "hip_amdgpu;lin_intel;esimd_emu;cuda_aws"
>>>>>>> 8d87832f2eccc0c8dae11e1ae8009a3816f2018a:.github/workflows/sycl_precommit_linux.yml

  linux_default:
    name: Default Linux
    # Only build and test patches, that have passed all linter checks, because
    # the next commit is likely to be a follow-up on that job.
    needs: lint
    if: always() && (success() || contains(github.event.pull_request.labels.*.name, 'ignore-lint'))
    uses: intel/llvm/.github/workflows/sycl_linux_build_and_test.yml@sycl
    with:
      build_runs_on: "build"
      build_cache_root: "/__w/"
      build_cache_size: "8G"
      build_artifact_suffix: "default"
      build_cache_suffix: "default"
<<<<<<< HEAD:.github/workflows/sycl_precommit.yml
      lts_config: "hip_amdgpu;ocl_x64"
=======
      lts_matrix: ${{ needs.test_matrix.outputs.lts_lx_matrix }}
      lts_aws_matrix: ${{ needs.test_matrix.outputs.lts_aws_matrix }}
      check_filters: ${{ needs.detect_changes.outputs.filters }}

  linux_e2e_on_nightly:
    name: Linux SYCL E2E on Nightly
    needs: [detect_changes]
    if: |
      !contains(needs.detect_changes.outputs.filters, 'test_build')
      && !contains(needs.detect_changes.outputs.filters, 'ci')
    uses: ./.github/workflows/linux_matrix_e2e_on_nightly.yml
    secrets: inherit
    with:
      ref: ${{ github.event.pull_request.head.sha }}
>>>>>>> 8d87832f2eccc0c8dae11e1ae8009a3816f2018a:.github/workflows/sycl_precommit_linux.yml
