// INTEL_FEATURE_MARKERCOUNT
// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: intel_feature_markercount
// RUN: %clang_cc1 -S -triple=x86_64-linux-gnu -emit-llvm -O1 -ffunction-marker-count=me  %s -o - | FileCheck --check-prefix=FM %s
// RUN: %clang_cc1 -S -triple=x86_64-linux-gnu -emit-llvm -O1 -floop-marker-count=me %s -o - | FileCheck --check-prefix=LM %s
// RUN: %clang_cc1 -S -triple=x86_64-linux-gnu -emit-llvm -O1 -ffunction-marker-count=me -foverride-marker-count-file=%S/Inputs/intel-override-marker-count-file.json %s -o - | FileCheck --check-prefix=FILE %s

// FM-LABEL: @f(
// FM-NEXT:  entry:
// FM-NEXT:    tail call void @llvm.mark.prolog()
// FM-NEXT:    tail call void @llvm.mark.epilog()
// FM-NEXT:    ret void
//
// LM-LABEL: @f(
// LM-NEXT:  entry:
// LM-NEXT:    ret void
//
// FILE-LABEL: @f(
// FILE-NEXT:  entry:
// FILE-NEXT:    ret void
//
void f() {}

// FM-LABEL: @g(
// FM-NEXT:  entry:
// FM-NEXT:    tail call void @llvm.mark.prolog()
// FM-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i32 [[A:%.*]], 0
// FM-NEXT:    br i1 [[TOBOOL_NOT]], label [[IF_THEN:%.*]], label [[LOOP:%.*]]
// FM:       if.then:
// FM-NEXT:    tail call void @llvm.mark.epilog()
// FM-NEXT:    ret i32 0
// FM:       loop:
// FM-NEXT:    br label [[LOOP]]
//
// LM-LABEL: @g(
// LM-NEXT:  entry:
// LM-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i32 [[A:%.*]], 0
// LM-NEXT:    br i1 [[TOBOOL_NOT]], label [[IF_THEN:%.*]], label [[LOOP:%.*]]
// LM:       if.then:
// LM-NEXT:    ret i32 0
// LM:       loop:
// LM-NEXT:    tail call void @llvm.mark.loop.header()
// LM-NEXT:    br label [[LOOP]]
//
// FILE-LABEL: @g(
// FILE-NEXT:  entry:
// FILE-NEXT:    tail call void @llvm.mark.prolog()
// FILE-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i32 [[A:%.*]], 0
// FILE-NEXT:    br i1 [[TOBOOL_NOT]], label [[IF_THEN:%.*]], label [[LOOP:%.*]]
// FILE:       if.then:
// FILE-NEXT:    tail call void @llvm.mark.epilog()
// FILE-NEXT:    ret i32 0
// FILE:       loop:
// FILE-NEXT:    br label [[LOOP]]
//
int g(int a) {
  if (!a)
    return 0;
loop:
  for (;;)
    goto loop;
}
// end INTEL_FEATURE_MARKERCOUNT
